./run_extra.sh mnist a adversarial carlini 7068
./run_extra.sh mnist a relu carlini 7068
./run_extra.sh mnist b standard carlini 7068
./run_extra.sh mnist b adversarial carlini 7068
./run_extra.sh mnist b relu carlini 7068
./run_extra.sh mnist c standard carlini 7068
./run_extra.sh mnist c adversarial carlini 7068
./run_extra.sh mnist c relu carlini 7068
./run_extra.sh mnist a standard carlini 3800
./run_extra.sh mnist a adversarial carlini 3800
./run_extra.sh mnist a relu carlini 3800
./run_extra.sh mnist b standard carlini 3800
./run_extra.sh mnist b adversarial carlini 3800
./run_extra.sh mnist b relu carlini 3800
./run_extra.sh mnist c standard carlini 3800
./run_extra.sh mnist c adversarial carlini 3800
./run_extra.sh mnist c relu carlini 3800
./run_extra.sh mnist a standard carlini 9074
./run_extra.sh mnist a adversarial carlini 9074
./run_extra.sh mnist a relu carlini 9074
./run_extra.sh mnist b standard carlini 9074
./run_extra.sh mnist b adversarial carlini 9074
./run_extra.sh mnist b relu carlini 9074
./run_extra.sh mnist c standard carlini 9074
./run_extra.sh mnist c adversarial carlini 9074
./run_extra.sh mnist c relu carlini 9074
./run_extra.sh mnist a standard carlini 4174
./run_extra.sh mnist a adversarial carlini 4174
./run_extra.sh mnist a relu carlini 4174
./run_extra.sh mnist b standard carlini 4174
./run_extra.sh mnist b adversarial carlini 4174
./run_extra.sh mnist b relu carlini 4174
./run_extra.sh mnist c standard carlini 4174
./run_extra.sh mnist c adversarial carlini 4174
./run_extra.sh mnist c relu carlini 4174
./run_extra.sh mnist a standard carlini 1398
./run_extra.sh mnist a adversarial carlini 1398
./run_extra.sh mnist a relu carlini 1398
./run_extra.sh mnist b standard carlini 1398
./run_extra.sh mnist b adversarial carlini 1398
./run_extra.sh mnist b relu carlini 1398
./run_extra.sh mnist c standard carlini 1398
./run_extra.sh mnist c adversarial carlini 1398
./run_extra.sh mnist c relu carlini 1398
./run_extra.sh mnist a standard carlini 9829
./run_extra.sh mnist a adversarial carlini 9829
./run_extra.sh mnist a relu carlini 9829
./run_extra.sh mnist b standard carlini 9829
./run_extra.sh mnist b adversarial carlini 9829
./run_extra.sh mnist b relu carlini 9829
./run_extra.sh mnist c standard carlini 9829
./run_extra.sh mnist c adversarial carlini 9829
./run_extra.sh mnist c relu carlini 9829
./run_extra.sh mnist a standard carlini 4997
./run_extra.sh mnist a adversarial carlini 4997
./run_extra.sh mnist a relu carlini 4997
./run_extra.sh mnist b standard carlini 4997
./run_extra.sh mnist b adversarial carlini 4997
./run_extra.sh mnist b relu carlini 4997
./run_extra.sh mnist c standard carlini 4997
./run_extra.sh mnist c adversarial carlini 4997
./run_extra.sh mnist c relu carlini 4997
./run_extra.sh mnist a standard carlini 6062
./run_extra.sh mnist a adversarial carlini 6062
./run_extra.sh mnist a relu carlini 6062
./run_extra.sh mnist b standard carlini 6062
./run_extra.sh mnist b adversarial carlini 6062
./run_extra.sh mnist b relu carlini 6062
./run_extra.sh mnist c standard carlini 6062
./run_extra.sh mnist c adversarial carlini 6062
./run_extra.sh mnist c relu carlini 6062
./run_extra.sh mnist a standard carlini 8453
./run_extra.sh mnist a adversarial carlini 8453
./run_extra.sh mnist a relu carlini 8453
./run_extra.sh mnist b standard carlini 8453
./run_extra.sh mnist b adversarial carlini 8453
./run_extra.sh mnist b relu carlini 8453
./run_extra.sh mnist c standard carlini 8453
./run_extra.sh mnist c adversarial carlini 8453
./run_extra.sh mnist c relu carlini 8453
./run_extra.sh mnist a standard carlini 683
./run_extra.sh mnist a adversarial carlini 683
./run_extra.sh mnist a relu carlini 683
./run_extra.sh mnist b standard carlini 683
./run_extra.sh mnist b adversarial carlini 683
./run_extra.sh mnist b relu carlini 683
./run_extra.sh mnist c standard carlini 683
./run_extra.sh mnist c adversarial carlini 683
./run_extra.sh mnist c relu carlini 683
./run_extra.sh mnist a standard carlini 6261
./run_extra.sh mnist a adversarial carlini 6261
./run_extra.sh mnist a relu carlini 6261
./run_extra.sh mnist b standard carlini 6261
./run_extra.sh mnist b adversarial carlini 6261
./run_extra.sh mnist b relu carlini 6261
./run_extra.sh mnist c standard carlini 6261
./run_extra.sh mnist c adversarial carlini 6261
./run_extra.sh mnist c relu carlini 6261
./run_extra.sh mnist a standard carlini 6751
./run_extra.sh mnist a adversarial carlini 6751
./run_extra.sh mnist a relu carlini 6751
./run_extra.sh mnist b standard carlini 6751
./run_extra.sh mnist b adversarial carlini 6751
./run_extra.sh mnist b relu carlini 6751
./run_extra.sh mnist c standard carlini 6751
./run_extra.sh mnist c adversarial carlini 6751
./run_extra.sh mnist c relu carlini 6751
./run_extra.sh mnist a standard carlini 5168
./run_extra.sh mnist a adversarial carlini 5168
./run_extra.sh mnist a relu carlini 5168
./run_extra.sh mnist b standard carlini 5168
./run_extra.sh mnist b adversarial carlini 5168
./run_extra.sh mnist b relu carlini 5168
./run_extra.sh mnist c standard carlini 5168
./run_extra.sh mnist c adversarial carlini 5168
./run_extra.sh mnist c relu carlini 5168
./run_extra.sh mnist a standard carlini 8322
./run_extra.sh mnist a adversarial carlini 8322
./run_extra.sh mnist a relu carlini 8322
./run_extra.sh mnist b standard carlini 8322
./run_extra.sh mnist b adversarial carlini 8322
./run_extra.sh mnist b relu carlini 8322
./run_extra.sh mnist c standard carlini 8322
./run_extra.sh mnist c adversarial carlini 8322
./run_extra.sh mnist c relu carlini 8322
./run_extra.sh mnist a standard carlini 1598
./run_extra.sh mnist a adversarial carlini 1598
./run_extra.sh mnist a relu carlini 1598
./run_extra.sh mnist b standard carlini 1598
./run_extra.sh mnist b adversarial carlini 1598
./run_extra.sh mnist b relu carlini 1598
./run_extra.sh mnist c standard carlini 1598
./run_extra.sh mnist c adversarial carlini 1598
./run_extra.sh mnist c relu carlini 1598
./run_extra.sh mnist a standard carlini 5495
./run_extra.sh mnist a adversarial carlini 5495
./run_extra.sh mnist a relu carlini 5495
./run_extra.sh mnist b standard carlini 5495
./run_extra.sh mnist b adversarial carlini 5495
./run_extra.sh mnist b relu carlini 5495
./run_extra.sh mnist c standard carlini 5495
./run_extra.sh mnist c adversarial carlini 5495
./run_extra.sh mnist c relu carlini 5495
./run_extra.sh mnist a standard carlini 4287
./run_extra.sh mnist a adversarial carlini 4287
./run_extra.sh mnist a relu carlini 4287
./run_extra.sh mnist b standard carlini 4287
./run_extra.sh mnist b adversarial carlini 4287
./run_extra.sh mnist b relu carlini 4287
./run_extra.sh mnist c standard carlini 4287
./run_extra.sh mnist c adversarial carlini 4287
./run_extra.sh mnist c relu carlini 4287
./run_extra.sh mnist a standard carlini 3078
./run_extra.sh mnist a adversarial carlini 3078
./run_extra.sh mnist a relu carlini 3078
./run_extra.sh mnist b standard carlini 3078
./run_extra.sh mnist b adversarial carlini 3078
./run_extra.sh mnist b relu carlini 3078
./run_extra.sh mnist c standard carlini 3078
./run_extra.sh mnist c adversarial carlini 3078
./run_extra.sh mnist c relu carlini 3078
./run_extra.sh mnist a standard carlini 7660
./run_extra.sh mnist a adversarial carlini 7660
./run_extra.sh mnist a relu carlini 7660
./run_extra.sh mnist b standard carlini 7660
./run_extra.sh mnist b adversarial carlini 7660
./run_extra.sh mnist b relu carlini 7660
./run_extra.sh mnist c standard carlini 7660
./run_extra.sh mnist c adversarial carlini 7660
./run_extra.sh mnist c relu carlini 7660
./run_extra.sh mnist a standard carlini 4889
./run_extra.sh mnist a adversarial carlini 4889
./run_extra.sh mnist a relu carlini 4889
./run_extra.sh mnist b standard carlini 4889
./run_extra.sh mnist b adversarial carlini 4889
./run_extra.sh mnist b relu carlini 4889
./run_extra.sh mnist c standard carlini 4889
./run_extra.sh mnist c adversarial carlini 4889
./run_extra.sh mnist c relu carlini 4889
./run_extra.sh mnist a standard carlini 5373
./run_extra.sh mnist a adversarial carlini 5373
./run_extra.sh mnist a relu carlini 5373
./run_extra.sh mnist b standard carlini 5373
./run_extra.sh mnist b adversarial carlini 5373
./run_extra.sh mnist b relu carlini 5373
./run_extra.sh mnist c standard carlini 5373
./run_extra.sh mnist c adversarial carlini 5373
./run_extra.sh mnist c relu carlini 5373
./run_extra.sh mnist a standard carlini 2562
./run_extra.sh mnist a adversarial carlini 2562
./run_extra.sh mnist a relu carlini 2562
./run_extra.sh mnist b standard carlini 2562
./run_extra.sh mnist b adversarial carlini 2562
./run_extra.sh mnist b relu carlini 2562
./run_extra.sh mnist c standard carlini 2562
./run_extra.sh mnist c adversarial carlini 2562
./run_extra.sh mnist c relu carlini 2562
./run_extra.sh mnist a standard carlini 3323
./run_extra.sh mnist a adversarial carlini 3323
./run_extra.sh mnist a relu carlini 3323
./run_extra.sh mnist b standard carlini 3323
./run_extra.sh mnist b adversarial carlini 3323
./run_extra.sh mnist b relu carlini 3323
./run_extra.sh mnist c standard carlini 3323
./run_extra.sh mnist c adversarial carlini 3323
./run_extra.sh mnist c relu carlini 3323
./run_extra.sh mnist a standard carlini 2231
./run_extra.sh mnist a adversarial carlini 2231
./run_extra.sh mnist a relu carlini 2231
./run_extra.sh mnist b standard carlini 2231
./run_extra.sh mnist b adversarial carlini 2231
./run_extra.sh mnist b relu carlini 2231
./run_extra.sh mnist c standard carlini 2231
./run_extra.sh mnist c adversarial carlini 2231
./run_extra.sh mnist c relu carlini 2231
./run_extra.sh mnist a standard carlini 8964
./run_extra.sh mnist a adversarial carlini 8964
./run_extra.sh mnist a relu carlini 8964
./run_extra.sh mnist b standard carlini 8964
./run_extra.sh mnist b adversarial carlini 8964
./run_extra.sh mnist b relu carlini 8964
./run_extra.sh mnist c standard carlini 8964
./run_extra.sh mnist c adversarial carlini 8964
./run_extra.sh mnist c relu carlini 8964
./run_extra.sh mnist a standard carlini 9936
./run_extra.sh mnist a adversarial carlini 9936
./run_extra.sh mnist a relu carlini 9936
./run_extra.sh mnist b standard carlini 9936
./run_extra.sh mnist b adversarial carlini 9936
./run_extra.sh mnist b relu carlini 9936
./run_extra.sh mnist c standard carlini 9936
./run_extra.sh mnist c adversarial carlini 9936
./run_extra.sh mnist c relu carlini 9936
./run_extra.sh mnist a standard carlini 405
./run_extra.sh mnist a adversarial carlini 405
./run_extra.sh mnist a relu carlini 405
./run_extra.sh mnist b standard carlini 405
./run_extra.sh mnist b adversarial carlini 405
./run_extra.sh mnist b relu carlini 405
./run_extra.sh mnist c standard carlini 405
./run_extra.sh mnist c adversarial carlini 405
./run_extra.sh mnist c relu carlini 405
./run_extra.sh mnist a standard carlini 308
./run_extra.sh mnist a adversarial carlini 308
./run_extra.sh mnist a relu carlini 308
./run_extra.sh mnist b standard carlini 308
./run_extra.sh mnist b adversarial carlini 308
./run_extra.sh mnist b relu carlini 308
./run_extra.sh mnist c standard carlini 308
./run_extra.sh mnist c adversarial carlini 308
./run_extra.sh mnist c relu carlini 308
./run_extra.sh mnist a standard carlini 6454
./run_extra.sh mnist a adversarial carlini 6454
./run_extra.sh mnist a relu carlini 6454
./run_extra.sh mnist b standard carlini 6454
./run_extra.sh mnist b adversarial carlini 6454
./run_extra.sh mnist b relu carlini 6454
./run_extra.sh mnist c standard carlini 6454
./run_extra.sh mnist c adversarial carlini 6454
./run_extra.sh mnist c relu carlini 6454
./run_extra.sh mnist a standard carlini 4389
./run_extra.sh mnist a adversarial carlini 4389
./run_extra.sh mnist a relu carlini 4389
./run_extra.sh mnist b standard carlini 4389
./run_extra.sh mnist b adversarial carlini 4389
./run_extra.sh mnist b relu carlini 4389
./run_extra.sh mnist c standard carlini 4389
./run_extra.sh mnist c adversarial carlini 4389
./run_extra.sh mnist c relu carlini 4389
./run_extra.sh mnist a standard carlini 6432
./run_extra.sh mnist a adversarial carlini 6432
./run_extra.sh mnist a relu carlini 6432
./run_extra.sh mnist b standard carlini 6432
./run_extra.sh mnist b adversarial carlini 6432
./run_extra.sh mnist b relu carlini 6432
./run_extra.sh mnist c standard carlini 6432
./run_extra.sh mnist c adversarial carlini 6432
./run_extra.sh mnist c relu carlini 6432
./run_extra.sh mnist a standard carlini 5358
./run_extra.sh mnist a adversarial carlini 5358
./run_extra.sh mnist a relu carlini 5358
./run_extra.sh mnist b standard carlini 5358
./run_extra.sh mnist b adversarial carlini 5358
./run_extra.sh mnist b relu carlini 5358
./run_extra.sh mnist c standard carlini 5358
./run_extra.sh mnist c adversarial carlini 5358
./run_extra.sh mnist c relu carlini 5358
./run_extra.sh mnist a standard carlini 4938
./run_extra.sh mnist a adversarial carlini 4938
./run_extra.sh mnist a relu carlini 4938
./run_extra.sh mnist b standard carlini 4938
./run_extra.sh mnist b adversarial carlini 4938
./run_extra.sh mnist b relu carlini 4938
./run_extra.sh mnist c standard carlini 4938
./run_extra.sh mnist c adversarial carlini 4938
./run_extra.sh mnist c relu carlini 4938
./run_extra.sh mnist a standard carlini 3241
./run_extra.sh mnist a adversarial carlini 3241
./run_extra.sh mnist a relu carlini 3241
./run_extra.sh mnist b standard carlini 3241
./run_extra.sh mnist b adversarial carlini 3241
./run_extra.sh mnist b relu carlini 3241
./run_extra.sh mnist c standard carlini 3241
./run_extra.sh mnist c adversarial carlini 3241
./run_extra.sh mnist c relu carlini 3241
./run_extra.sh mnist a standard carlini 7017
./run_extra.sh mnist a adversarial carlini 7017
./run_extra.sh mnist a relu carlini 7017
./run_extra.sh mnist b standard carlini 7017
./run_extra.sh mnist b adversarial carlini 7017
./run_extra.sh mnist b relu carlini 7017
./run_extra.sh mnist c standard carlini 7017
./run_extra.sh mnist c adversarial carlini 7017
./run_extra.sh mnist c relu carlini 7017
./run_extra.sh mnist a standard carlini 2452
./run_extra.sh mnist a adversarial carlini 2452
./run_extra.sh mnist a relu carlini 2452
./run_extra.sh mnist b standard carlini 2452
./run_extra.sh mnist b adversarial carlini 2452
./run_extra.sh mnist b relu carlini 2452
./run_extra.sh mnist c standard carlini 2452
./run_extra.sh mnist c adversarial carlini 2452
./run_extra.sh mnist c relu carlini 2452
./run_extra.sh mnist a standard carlini 5124
./run_extra.sh mnist a adversarial carlini 5124
./run_extra.sh mnist a relu carlini 5124
./run_extra.sh mnist b standard carlini 5124
./run_extra.sh mnist b adversarial carlini 5124
./run_extra.sh mnist b relu carlini 5124
./run_extra.sh mnist c standard carlini 5124
./run_extra.sh mnist c adversarial carlini 5124
./run_extra.sh mnist c relu carlini 5124
./run_extra.sh mnist a standard carlini 4753
./run_extra.sh mnist a adversarial carlini 4753
./run_extra.sh mnist a relu carlini 4753
./run_extra.sh mnist b standard carlini 4753
./run_extra.sh mnist b adversarial carlini 4753
./run_extra.sh mnist b relu carlini 4753
./run_extra.sh mnist c standard carlini 4753
./run_extra.sh mnist c adversarial carlini 4753
./run_extra.sh mnist c relu carlini 4753
./run_extra.sh mnist a standard carlini 7720
./run_extra.sh mnist a adversarial carlini 7720
./run_extra.sh mnist a relu carlini 7720
./run_extra.sh mnist b standard carlini 7720
./run_extra.sh mnist b adversarial carlini 7720
./run_extra.sh mnist b relu carlini 7720
./run_extra.sh mnist c standard carlini 7720
./run_extra.sh mnist c adversarial carlini 7720
./run_extra.sh mnist c relu carlini 7720
./run_extra.sh mnist a standard carlini 5477
./run_extra.sh mnist a adversarial carlini 5477
./run_extra.sh mnist a relu carlini 5477
./run_extra.sh mnist b standard carlini 5477
./run_extra.sh mnist b adversarial carlini 5477
./run_extra.sh mnist b relu carlini 5477
./run_extra.sh mnist c standard carlini 5477
./run_extra.sh mnist c adversarial carlini 5477
./run_extra.sh mnist c relu carlini 5477
./run_extra.sh mnist a standard carlini 3910
./run_extra.sh mnist a adversarial carlini 3910
./run_extra.sh mnist a relu carlini 3910
./run_extra.sh mnist b standard carlini 3910
./run_extra.sh mnist b adversarial carlini 3910
./run_extra.sh mnist b relu carlini 3910
./run_extra.sh mnist c standard carlini 3910
./run_extra.sh mnist c adversarial carlini 3910
./run_extra.sh mnist c relu carlini 3910
./run_extra.sh mnist a standard carlini 7335
./run_extra.sh mnist a adversarial carlini 7335
./run_extra.sh mnist a relu carlini 7335
./run_extra.sh mnist b standard carlini 7335
./run_extra.sh mnist b adversarial carlini 7335
./run_extra.sh mnist b relu carlini 7335
./run_extra.sh mnist c standard carlini 7335
./run_extra.sh mnist c adversarial carlini 7335
./run_extra.sh mnist c relu carlini 7335
./run_extra.sh mnist a standard carlini 2782
./run_extra.sh mnist a adversarial carlini 2782
./run_extra.sh mnist a relu carlini 2782
./run_extra.sh mnist b standard carlini 2782
./run_extra.sh mnist b adversarial carlini 2782
./run_extra.sh mnist b relu carlini 2782
./run_extra.sh mnist c standard carlini 2782
./run_extra.sh mnist c adversarial carlini 2782
./run_extra.sh mnist c relu carlini 2782
./run_extra.sh mnist a standard carlini 9020
./run_extra.sh mnist a adversarial carlini 9020
./run_extra.sh mnist a relu carlini 9020
./run_extra.sh mnist b standard carlini 9020
./run_extra.sh mnist b adversarial carlini 9020
./run_extra.sh mnist b relu carlini 9020
./run_extra.sh mnist c standard carlini 9020
./run_extra.sh mnist c adversarial carlini 9020
./run_extra.sh mnist c relu carlini 9020
./run_extra.sh mnist a standard carlini 6159
./run_extra.sh mnist a adversarial carlini 6159
./run_extra.sh mnist a relu carlini 6159
./run_extra.sh mnist b standard carlini 6159
./run_extra.sh mnist b adversarial carlini 6159
./run_extra.sh mnist b relu carlini 6159
./run_extra.sh mnist c standard carlini 6159
./run_extra.sh mnist c adversarial carlini 6159
./run_extra.sh mnist c relu carlini 6159
./run_extra.sh mnist a standard carlini 7572
./run_extra.sh mnist a adversarial carlini 7572
./run_extra.sh mnist a relu carlini 7572
./run_extra.sh mnist b standard carlini 7572
./run_extra.sh mnist b adversarial carlini 7572
./run_extra.sh mnist b relu carlini 7572
./run_extra.sh mnist c standard carlini 7572
./run_extra.sh mnist c adversarial carlini 7572
./run_extra.sh mnist c relu carlini 7572
./run_extra.sh mnist a standard carlini 6166
./run_extra.sh mnist a adversarial carlini 6166
./run_extra.sh mnist a relu carlini 6166
./run_extra.sh mnist b standard carlini 6166
./run_extra.sh mnist b adversarial carlini 6166
./run_extra.sh mnist b relu carlini 6166
./run_extra.sh mnist c standard carlini 6166
./run_extra.sh mnist c adversarial carlini 6166
./run_extra.sh mnist c relu carlini 6166
./run_extra.sh mnist a standard carlini 4342
./run_extra.sh mnist a adversarial carlini 4342
./run_extra.sh mnist a relu carlini 4342
./run_extra.sh mnist b standard carlini 4342
./run_extra.sh mnist b adversarial carlini 4342
./run_extra.sh mnist b relu carlini 4342
./run_extra.sh mnist c standard carlini 4342
./run_extra.sh mnist c adversarial carlini 4342
./run_extra.sh mnist c relu carlini 4342
./run_extra.sh mnist a standard carlini 3728
./run_extra.sh mnist a adversarial carlini 3728
./run_extra.sh mnist a relu carlini 3728
./run_extra.sh mnist b standard carlini 3728
./run_extra.sh mnist b adversarial carlini 3728
./run_extra.sh mnist b relu carlini 3728
./run_extra.sh mnist c standard carlini 3728
./run_extra.sh mnist c adversarial carlini 3728
./run_extra.sh mnist c relu carlini 3728
./run_extra.sh mnist a standard carlini 6003
./run_extra.sh mnist a adversarial carlini 6003
./run_extra.sh mnist a relu carlini 6003
./run_extra.sh mnist b standard carlini 6003
./run_extra.sh mnist b adversarial carlini 6003
./run_extra.sh mnist b relu carlini 6003
./run_extra.sh mnist c standard carlini 6003
./run_extra.sh mnist c adversarial carlini 6003
./run_extra.sh mnist c relu carlini 6003
./run_extra.sh mnist a standard carlini 3484
./run_extra.sh mnist a adversarial carlini 3484
./run_extra.sh mnist a relu carlini 3484
./run_extra.sh mnist b standard carlini 3484
./run_extra.sh mnist b adversarial carlini 3484
./run_extra.sh mnist b relu carlini 3484
./run_extra.sh mnist c standard carlini 3484
./run_extra.sh mnist c adversarial carlini 3484
./run_extra.sh mnist c relu carlini 3484
./run_extra.sh mnist a standard carlini 1605
./run_extra.sh mnist a adversarial carlini 1605
./run_extra.sh mnist a relu carlini 1605
./run_extra.sh mnist b standard carlini 1605
./run_extra.sh mnist b adversarial carlini 1605
./run_extra.sh mnist b relu carlini 1605
./run_extra.sh mnist c standard carlini 1605
./run_extra.sh mnist c adversarial carlini 1605
./run_extra.sh mnist c relu carlini 1605
./run_extra.sh mnist a standard carlini 2048
./run_extra.sh mnist a adversarial carlini 2048
./run_extra.sh mnist a relu carlini 2048
./run_extra.sh mnist b standard carlini 2048
./run_extra.sh mnist b adversarial carlini 2048
./run_extra.sh mnist b relu carlini 2048
./run_extra.sh mnist c standard carlini 2048
./run_extra.sh mnist c adversarial carlini 2048
./run_extra.sh mnist c relu carlini 2048
./run_extra.sh mnist a standard carlini 7290
./run_extra.sh mnist a adversarial carlini 7290
./run_extra.sh mnist a relu carlini 7290
./run_extra.sh mnist b standard carlini 7290
./run_extra.sh mnist b adversarial carlini 7290
./run_extra.sh mnist b relu carlini 7290
./run_extra.sh mnist c standard carlini 7290
./run_extra.sh mnist c adversarial carlini 7290
./run_extra.sh mnist c relu carlini 7290
./run_extra.sh mnist a standard carlini 5521
./run_extra.sh mnist a adversarial carlini 5521
./run_extra.sh mnist a relu carlini 5521
./run_extra.sh mnist b standard carlini 5521
./run_extra.sh mnist b adversarial carlini 5521
./run_extra.sh mnist b relu carlini 5521
./run_extra.sh mnist c standard carlini 5521
./run_extra.sh mnist c adversarial carlini 5521
./run_extra.sh mnist c relu carlini 5521
./run_extra.sh mnist a standard carlini 983
./run_extra.sh mnist a adversarial carlini 983
./run_extra.sh mnist a relu carlini 983
./run_extra.sh mnist b standard carlini 983
./run_extra.sh mnist b adversarial carlini 983
./run_extra.sh mnist b relu carlini 983
./run_extra.sh mnist c standard carlini 983
./run_extra.sh mnist c adversarial carlini 983
./run_extra.sh mnist c relu carlini 983
./run_extra.sh mnist a standard carlini 1497
./run_extra.sh mnist a adversarial carlini 1497
./run_extra.sh mnist a relu carlini 1497
./run_extra.sh mnist b standard carlini 1497
./run_extra.sh mnist b adversarial carlini 1497
./run_extra.sh mnist b relu carlini 1497
./run_extra.sh mnist c standard carlini 1497
./run_extra.sh mnist c adversarial carlini 1497
./run_extra.sh mnist c relu carlini 1497
./run_extra.sh mnist a standard carlini 5278
./run_extra.sh mnist a adversarial carlini 5278
./run_extra.sh mnist a relu carlini 5278
./run_extra.sh mnist b standard carlini 5278
./run_extra.sh mnist b adversarial carlini 5278
./run_extra.sh mnist b relu carlini 5278
./run_extra.sh mnist c standard carlini 5278
./run_extra.sh mnist c adversarial carlini 5278
./run_extra.sh mnist c relu carlini 5278
./run_extra.sh mnist a standard carlini 1496
./run_extra.sh mnist a adversarial carlini 1496
./run_extra.sh mnist a relu carlini 1496
./run_extra.sh mnist b standard carlini 1496
./run_extra.sh mnist b adversarial carlini 1496
./run_extra.sh mnist b relu carlini 1496
./run_extra.sh mnist c standard carlini 1496
./run_extra.sh mnist c adversarial carlini 1496
./run_extra.sh mnist c relu carlini 1496
./run_extra.sh mnist a standard carlini 9080
./run_extra.sh mnist a adversarial carlini 9080
./run_extra.sh mnist a relu carlini 9080
./run_extra.sh mnist b standard carlini 9080
./run_extra.sh mnist b adversarial carlini 9080
./run_extra.sh mnist b relu carlini 9080
./run_extra.sh mnist c standard carlini 9080
./run_extra.sh mnist c adversarial carlini 9080
./run_extra.sh mnist c relu carlini 9080
./run_extra.sh mnist a standard carlini 1148
./run_extra.sh mnist a adversarial carlini 1148
./run_extra.sh mnist a relu carlini 1148
./run_extra.sh mnist b standard carlini 1148
./run_extra.sh mnist b adversarial carlini 1148
./run_extra.sh mnist b relu carlini 1148
./run_extra.sh mnist c standard carlini 1148
./run_extra.sh mnist c adversarial carlini 1148
./run_extra.sh mnist c relu carlini 1148
./run_extra.sh mnist a standard carlini 8525
./run_extra.sh mnist a adversarial carlini 8525
./run_extra.sh mnist a relu carlini 8525
./run_extra.sh mnist b standard carlini 8525
./run_extra.sh mnist b adversarial carlini 8525
./run_extra.sh mnist b relu carlini 8525
./run_extra.sh mnist c standard carlini 8525
./run_extra.sh mnist c adversarial carlini 8525
./run_extra.sh mnist c relu carlini 8525
./run_extra.sh mnist a standard carlini 529
./run_extra.sh mnist a adversarial carlini 529
./run_extra.sh mnist a relu carlini 529
./run_extra.sh mnist b standard carlini 529
./run_extra.sh mnist b adversarial carlini 529
./run_extra.sh mnist b relu carlini 529
./run_extra.sh mnist c standard carlini 529
./run_extra.sh mnist c adversarial carlini 529
./run_extra.sh mnist c relu carlini 529
./run_extra.sh mnist a standard carlini 3378
./run_extra.sh mnist a adversarial carlini 3378
./run_extra.sh mnist a relu carlini 3378
./run_extra.sh mnist b standard carlini 3378
./run_extra.sh mnist b adversarial carlini 3378
./run_extra.sh mnist b relu carlini 3378
./run_extra.sh mnist c standard carlini 3378
./run_extra.sh mnist c adversarial carlini 3378
./run_extra.sh mnist c relu carlini 3378
./run_extra.sh mnist a standard carlini 6387
./run_extra.sh mnist a adversarial carlini 6387
./run_extra.sh mnist a relu carlini 6387
./run_extra.sh mnist b standard carlini 6387
./run_extra.sh mnist b adversarial carlini 6387
./run_extra.sh mnist b relu carlini 6387
./run_extra.sh mnist c standard carlini 6387
./run_extra.sh mnist c adversarial carlini 6387
./run_extra.sh mnist c relu carlini 6387
./run_extra.sh mnist a standard carlini 1961
./run_extra.sh mnist a adversarial carlini 1961
./run_extra.sh mnist a relu carlini 1961
./run_extra.sh mnist b standard carlini 1961
./run_extra.sh mnist b adversarial carlini 1961
./run_extra.sh mnist b relu carlini 1961
./run_extra.sh mnist c standard carlini 1961
./run_extra.sh mnist c adversarial carlini 1961
./run_extra.sh mnist c relu carlini 1961
./run_extra.sh mnist a standard carlini 1444
./run_extra.sh mnist a adversarial carlini 1444
./run_extra.sh mnist a relu carlini 1444
./run_extra.sh mnist b standard carlini 1444
./run_extra.sh mnist b adversarial carlini 1444
./run_extra.sh mnist b relu carlini 1444
./run_extra.sh mnist c standard carlini 1444
./run_extra.sh mnist c adversarial carlini 1444
./run_extra.sh mnist c relu carlini 1444
./run_extra.sh mnist a standard carlini 4131
./run_extra.sh mnist a adversarial carlini 4131
./run_extra.sh mnist a relu carlini 4131
./run_extra.sh mnist b standard carlini 4131
./run_extra.sh mnist b adversarial carlini 4131
./run_extra.sh mnist b relu carlini 4131
./run_extra.sh mnist c standard carlini 4131
./run_extra.sh mnist c adversarial carlini 4131
./run_extra.sh mnist c relu carlini 4131
./run_extra.sh mnist a standard carlini 414
./run_extra.sh mnist a adversarial carlini 414
./run_extra.sh mnist a relu carlini 414
./run_extra.sh mnist b standard carlini 414
./run_extra.sh mnist b adversarial carlini 414
./run_extra.sh mnist b relu carlini 414
./run_extra.sh mnist c standard carlini 414
./run_extra.sh mnist c adversarial carlini 414
./run_extra.sh mnist c relu carlini 414
./run_extra.sh mnist a standard carlini 9193
./run_extra.sh mnist a adversarial carlini 9193
./run_extra.sh mnist a relu carlini 9193
./run_extra.sh mnist b standard carlini 9193
./run_extra.sh mnist b adversarial carlini 9193
./run_extra.sh mnist b relu carlini 9193
./run_extra.sh mnist c standard carlini 9193
./run_extra.sh mnist c adversarial carlini 9193
./run_extra.sh mnist c relu carlini 9193
./run_extra.sh mnist a standard carlini 7060
./run_extra.sh mnist a adversarial carlini 7060
./run_extra.sh mnist a relu carlini 7060
./run_extra.sh mnist b standard carlini 7060
./run_extra.sh mnist b adversarial carlini 7060
./run_extra.sh mnist b relu carlini 7060
./run_extra.sh mnist c standard carlini 7060
./run_extra.sh mnist c adversarial carlini 7060
./run_extra.sh mnist c relu carlini 7060
./run_extra.sh mnist a standard carlini 8516
./run_extra.sh mnist a adversarial carlini 8516
./run_extra.sh mnist a relu carlini 8516
./run_extra.sh mnist b standard carlini 8516
./run_extra.sh mnist b adversarial carlini 8516
./run_extra.sh mnist b relu carlini 8516
./run_extra.sh mnist c standard carlini 8516
./run_extra.sh mnist c adversarial carlini 8516
./run_extra.sh mnist c relu carlini 8516
./run_extra.sh mnist a standard carlini 8218
./run_extra.sh mnist a adversarial carlini 8218
./run_extra.sh mnist a relu carlini 8218
./run_extra.sh mnist b standard carlini 8218
./run_extra.sh mnist b adversarial carlini 8218
./run_extra.sh mnist b relu carlini 8218
./run_extra.sh mnist c standard carlini 8218
./run_extra.sh mnist c adversarial carlini 8218
./run_extra.sh mnist c relu carlini 8218
./run_extra.sh mnist a standard carlini 3113
./run_extra.sh mnist a adversarial carlini 3113
./run_extra.sh mnist a relu carlini 3113
./run_extra.sh mnist b standard carlini 3113
./run_extra.sh mnist b adversarial carlini 3113
./run_extra.sh mnist b relu carlini 3113
./run_extra.sh mnist c standard carlini 3113
./run_extra.sh mnist c adversarial carlini 3113
./run_extra.sh mnist c relu carlini 3113
./run_extra.sh mnist a standard carlini 9700
./run_extra.sh mnist a adversarial carlini 9700
./run_extra.sh mnist a relu carlini 9700
./run_extra.sh mnist b standard carlini 9700
./run_extra.sh mnist b adversarial carlini 9700
./run_extra.sh mnist b relu carlini 9700
./run_extra.sh mnist c standard carlini 9700
./run_extra.sh mnist c adversarial carlini 9700
./run_extra.sh mnist c relu carlini 9700
./run_extra.sh mnist a standard carlini 5866
./run_extra.sh mnist a adversarial carlini 5866
./run_extra.sh mnist a relu carlini 5866
./run_extra.sh mnist b standard carlini 5866
./run_extra.sh mnist b adversarial carlini 5866
./run_extra.sh mnist b relu carlini 5866
./run_extra.sh mnist c standard carlini 5866
./run_extra.sh mnist c adversarial carlini 5866
./run_extra.sh mnist c relu carlini 5866
./run_extra.sh mnist a standard carlini 2934
./run_extra.sh mnist a adversarial carlini 2934
./run_extra.sh mnist a relu carlini 2934
./run_extra.sh mnist b standard carlini 2934
./run_extra.sh mnist b adversarial carlini 2934
./run_extra.sh mnist b relu carlini 2934
./run_extra.sh mnist c standard carlini 2934
./run_extra.sh mnist c adversarial carlini 2934
./run_extra.sh mnist c relu carlini 2934
./run_extra.sh mnist a standard carlini 884
./run_extra.sh mnist a adversarial carlini 884
./run_extra.sh mnist a relu carlini 884
./run_extra.sh mnist b standard carlini 884
./run_extra.sh mnist b adversarial carlini 884
./run_extra.sh mnist b relu carlini 884
./run_extra.sh mnist c standard carlini 884
./run_extra.sh mnist c adversarial carlini 884
./run_extra.sh mnist c relu carlini 884
./run_extra.sh mnist a standard carlini 8603
./run_extra.sh mnist a adversarial carlini 8603
./run_extra.sh mnist a relu carlini 8603
./run_extra.sh mnist b standard carlini 8603
./run_extra.sh mnist b adversarial carlini 8603
./run_extra.sh mnist b relu carlini 8603
./run_extra.sh mnist c standard carlini 8603
./run_extra.sh mnist c adversarial carlini 8603
./run_extra.sh mnist c relu carlini 8603
./run_extra.sh mnist a standard carlini 3411
./run_extra.sh mnist a adversarial carlini 3411
./run_extra.sh mnist a relu carlini 3411
./run_extra.sh mnist b standard carlini 3411
./run_extra.sh mnist b adversarial carlini 3411
./run_extra.sh mnist b relu carlini 3411
./run_extra.sh mnist c standard carlini 3411
./run_extra.sh mnist c adversarial carlini 3411
./run_extra.sh mnist c relu carlini 3411
./run_extra.sh mnist a standard carlini 1104
./run_extra.sh mnist a adversarial carlini 1104
./run_extra.sh mnist a relu carlini 1104
./run_extra.sh mnist b standard carlini 1104
./run_extra.sh mnist b adversarial carlini 1104
./run_extra.sh mnist b relu carlini 1104
./run_extra.sh mnist c standard carlini 1104
./run_extra.sh mnist c adversarial carlini 1104
./run_extra.sh mnist c relu carlini 1104
./run_extra.sh mnist a standard carlini 9200
./run_extra.sh mnist a adversarial carlini 9200
./run_extra.sh mnist a relu carlini 9200
./run_extra.sh mnist b standard carlini 9200
./run_extra.sh mnist b adversarial carlini 9200
./run_extra.sh mnist b relu carlini 9200
./run_extra.sh mnist c standard carlini 9200
./run_extra.sh mnist c adversarial carlini 9200
./run_extra.sh mnist c relu carlini 9200
./run_extra.sh mnist a standard carlini 9141
./run_extra.sh mnist a adversarial carlini 9141
./run_extra.sh mnist a relu carlini 9141
./run_extra.sh mnist b standard carlini 9141
./run_extra.sh mnist b adversarial carlini 9141
./run_extra.sh mnist b relu carlini 9141
./run_extra.sh mnist c standard carlini 9141
./run_extra.sh mnist c adversarial carlini 9141
./run_extra.sh mnist c relu carlini 9141
./run_extra.sh mnist a standard carlini 2213
./run_extra.sh mnist a adversarial carlini 2213
./run_extra.sh mnist a relu carlini 2213
./run_extra.sh mnist b standard carlini 2213
./run_extra.sh mnist b adversarial carlini 2213
./run_extra.sh mnist b relu carlini 2213
./run_extra.sh mnist c standard carlini 2213
./run_extra.sh mnist c adversarial carlini 2213
./run_extra.sh mnist c relu carlini 2213
./run_extra.sh mnist a standard carlini 8646
./run_extra.sh mnist a adversarial carlini 8646
./run_extra.sh mnist a relu carlini 8646
./run_extra.sh mnist b standard carlini 8646
./run_extra.sh mnist b adversarial carlini 8646
./run_extra.sh mnist b relu carlini 8646
./run_extra.sh mnist c standard carlini 8646
./run_extra.sh mnist c adversarial carlini 8646
./run_extra.sh mnist c relu carlini 8646
./run_extra.sh mnist a standard carlini 4989
./run_extra.sh mnist a adversarial carlini 4989
./run_extra.sh mnist a relu carlini 4989
./run_extra.sh mnist b standard carlini 4989
./run_extra.sh mnist b adversarial carlini 4989
./run_extra.sh mnist b relu carlini 4989
./run_extra.sh mnist c standard carlini 4989
./run_extra.sh mnist c adversarial carlini 4989
./run_extra.sh mnist c relu carlini 4989
./run_extra.sh mnist a standard carlini 9978
./run_extra.sh mnist a adversarial carlini 9978
./run_extra.sh mnist a relu carlini 9978
./run_extra.sh mnist b standard carlini 9978
./run_extra.sh mnist b adversarial carlini 9978
./run_extra.sh mnist b relu carlini 9978
./run_extra.sh mnist c standard carlini 9978
./run_extra.sh mnist c adversarial carlini 9978
./run_extra.sh mnist c relu carlini 9978
./run_extra.sh mnist a standard carlini 5145
./run_extra.sh mnist a adversarial carlini 5145
./run_extra.sh mnist a relu carlini 5145
./run_extra.sh mnist b standard carlini 5145
./run_extra.sh mnist b adversarial carlini 5145
./run_extra.sh mnist b relu carlini 5145
./run_extra.sh mnist c standard carlini 5145
./run_extra.sh mnist c adversarial carlini 5145
./run_extra.sh mnist c relu carlini 5145
./run_extra.sh mnist a standard carlini 7189
./run_extra.sh mnist a adversarial carlini 7189
./run_extra.sh mnist a relu carlini 7189
./run_extra.sh mnist b standard carlini 7189
./run_extra.sh mnist b adversarial carlini 7189
./run_extra.sh mnist b relu carlini 7189
./run_extra.sh mnist c standard carlini 7189
./run_extra.sh mnist c adversarial carlini 7189
./run_extra.sh mnist c relu carlini 7189
./run_extra.sh mnist a standard carlini 9319
./run_extra.sh mnist a adversarial carlini 9319
./run_extra.sh mnist a relu carlini 9319
./run_extra.sh mnist b standard carlini 9319
./run_extra.sh mnist b adversarial carlini 9319
./run_extra.sh mnist b relu carlini 9319
./run_extra.sh mnist c standard carlini 9319
./run_extra.sh mnist c adversarial carlini 9319
./run_extra.sh mnist c relu carlini 9319
./run_extra.sh mnist a standard carlini 9479
./run_extra.sh mnist a adversarial carlini 9479
./run_extra.sh mnist a relu carlini 9479
./run_extra.sh mnist b standard carlini 9479
./run_extra.sh mnist b adversarial carlini 9479
./run_extra.sh mnist b relu carlini 9479
./run_extra.sh mnist c standard carlini 9479
./run_extra.sh mnist c adversarial carlini 9479
./run_extra.sh mnist c relu carlini 9479
./run_extra.sh mnist a standard carlini 1162
./run_extra.sh mnist a adversarial carlini 1162
./run_extra.sh mnist a relu carlini 1162
./run_extra.sh mnist b standard carlini 1162
./run_extra.sh mnist b adversarial carlini 1162
./run_extra.sh mnist b relu carlini 1162
./run_extra.sh mnist c standard carlini 1162
./run_extra.sh mnist c adversarial carlini 1162
./run_extra.sh mnist c relu carlini 1162
./run_extra.sh mnist a standard carlini 4872
./run_extra.sh mnist a adversarial carlini 4872
./run_extra.sh mnist a relu carlini 4872
./run_extra.sh mnist b standard carlini 4872
./run_extra.sh mnist b adversarial carlini 4872
./run_extra.sh mnist b relu carlini 4872
./run_extra.sh mnist c standard carlini 4872
./run_extra.sh mnist c adversarial carlini 4872
./run_extra.sh mnist c relu carlini 4872
./run_extra.sh mnist a standard carlini 7333
./run_extra.sh mnist a adversarial carlini 7333
./run_extra.sh mnist a relu carlini 7333
./run_extra.sh mnist b standard carlini 7333
./run_extra.sh mnist b adversarial carlini 7333
./run_extra.sh mnist b relu carlini 7333
./run_extra.sh mnist c standard carlini 7333
./run_extra.sh mnist c adversarial carlini 7333
./run_extra.sh mnist c relu carlini 7333
./run_extra.sh mnist a standard carlini 8432
./run_extra.sh mnist a adversarial carlini 8432
./run_extra.sh mnist a relu carlini 8432
./run_extra.sh mnist b standard carlini 8432
./run_extra.sh mnist b adversarial carlini 8432
./run_extra.sh mnist b relu carlini 8432
./run_extra.sh mnist c standard carlini 8432
./run_extra.sh mnist c adversarial carlini 8432
./run_extra.sh mnist c relu carlini 8432
./run_extra.sh mnist a standard carlini 6894
./run_extra.sh mnist a adversarial carlini 6894
./run_extra.sh mnist a relu carlini 6894
./run_extra.sh mnist b standard carlini 6894
./run_extra.sh mnist b adversarial carlini 6894
./run_extra.sh mnist b relu carlini 6894
./run_extra.sh mnist c standard carlini 6894
./run_extra.sh mnist c adversarial carlini 6894
./run_extra.sh mnist c relu carlini 6894
./run_extra.sh mnist a standard carlini 4249
./run_extra.sh mnist a adversarial carlini 4249
./run_extra.sh mnist a relu carlini 4249
./run_extra.sh mnist b standard carlini 4249
./run_extra.sh mnist b adversarial carlini 4249
./run_extra.sh mnist b relu carlini 4249
./run_extra.sh mnist c standard carlini 4249
./run_extra.sh mnist c adversarial carlini 4249
./run_extra.sh mnist c relu carlini 4249
./run_extra.sh mnist a standard carlini 9064
./run_extra.sh mnist a adversarial carlini 9064
./run_extra.sh mnist a relu carlini 9064
./run_extra.sh mnist b standard carlini 9064
./run_extra.sh mnist b adversarial carlini 9064
./run_extra.sh mnist b relu carlini 9064
./run_extra.sh mnist c standard carlini 9064
./run_extra.sh mnist c adversarial carlini 9064
./run_extra.sh mnist c relu carlini 9064
./run_extra.sh mnist a standard carlini 3115
./run_extra.sh mnist a adversarial carlini 3115
./run_extra.sh mnist a relu carlini 3115
./run_extra.sh mnist b standard carlini 3115
./run_extra.sh mnist b adversarial carlini 3115
./run_extra.sh mnist b relu carlini 3115
./run_extra.sh mnist c standard carlini 3115
./run_extra.sh mnist c adversarial carlini 3115
./run_extra.sh mnist c relu carlini 3115
./run_extra.sh mnist a standard carlini 1106
./run_extra.sh mnist a adversarial carlini 1106
./run_extra.sh mnist a relu carlini 1106
./run_extra.sh mnist b standard carlini 1106
./run_extra.sh mnist b adversarial carlini 1106
./run_extra.sh mnist b relu carlini 1106
./run_extra.sh mnist c standard carlini 1106
./run_extra.sh mnist c adversarial carlini 1106
./run_extra.sh mnist c relu carlini 1106
./run_extra.sh mnist a standard carlini 5080
./run_extra.sh mnist a adversarial carlini 5080
./run_extra.sh mnist a relu carlini 5080
./run_extra.sh mnist b standard carlini 5080
./run_extra.sh mnist b adversarial carlini 5080
./run_extra.sh mnist b relu carlini 5080
./run_extra.sh mnist c standard carlini 5080
./run_extra.sh mnist c adversarial carlini 5080
./run_extra.sh mnist c relu carlini 5080
./run_extra.sh mnist a standard carlini 630
./run_extra.sh mnist a adversarial carlini 630
./run_extra.sh mnist a relu carlini 630
./run_extra.sh mnist b standard carlini 630
./run_extra.sh mnist b adversarial carlini 630
./run_extra.sh mnist b relu carlini 630
./run_extra.sh mnist c standard carlini 630
./run_extra.sh mnist c adversarial carlini 630
./run_extra.sh mnist c relu carlini 630
./run_extra.sh mnist a standard carlini 8528
./run_extra.sh mnist a adversarial carlini 8528
./run_extra.sh mnist a relu carlini 8528
./run_extra.sh mnist b standard carlini 8528
./run_extra.sh mnist b adversarial carlini 8528
./run_extra.sh mnist b relu carlini 8528
./run_extra.sh mnist c standard carlini 8528
./run_extra.sh mnist c adversarial carlini 8528
./run_extra.sh mnist c relu carlini 8528
./run_extra.sh mnist a standard carlini 7085
./run_extra.sh mnist a adversarial carlini 7085
./run_extra.sh mnist a relu carlini 7085
./run_extra.sh mnist b standard carlini 7085
./run_extra.sh mnist b adversarial carlini 7085
./run_extra.sh mnist b relu carlini 7085
./run_extra.sh mnist c standard carlini 7085
./run_extra.sh mnist c adversarial carlini 7085
./run_extra.sh mnist c relu carlini 7085
./run_extra.sh mnist a standard carlini 9831
./run_extra.sh mnist a adversarial carlini 9831
./run_extra.sh mnist a relu carlini 9831
./run_extra.sh mnist b standard carlini 9831
./run_extra.sh mnist b adversarial carlini 9831
./run_extra.sh mnist b relu carlini 9831
./run_extra.sh mnist c standard carlini 9831
./run_extra.sh mnist c adversarial carlini 9831
./run_extra.sh mnist c relu carlini 9831
./run_extra.sh mnist a standard carlini 7691
./run_extra.sh mnist a adversarial carlini 7691
./run_extra.sh mnist a relu carlini 7691
./run_extra.sh mnist b standard carlini 7691
./run_extra.sh mnist b adversarial carlini 7691
./run_extra.sh mnist b relu carlini 7691
./run_extra.sh mnist c standard carlini 7691
./run_extra.sh mnist c adversarial carlini 7691
./run_extra.sh mnist c relu carlini 7691
./run_extra.sh mnist a standard carlini 5790
./run_extra.sh mnist a adversarial carlini 5790
./run_extra.sh mnist a relu carlini 5790
./run_extra.sh mnist b standard carlini 5790
./run_extra.sh mnist b adversarial carlini 5790
./run_extra.sh mnist b relu carlini 5790
./run_extra.sh mnist c standard carlini 5790
./run_extra.sh mnist c adversarial carlini 5790
./run_extra.sh mnist c relu carlini 5790
./run_extra.sh mnist a standard carlini 6980
./run_extra.sh mnist a adversarial carlini 6980
./run_extra.sh mnist a relu carlini 6980
./run_extra.sh mnist b standard carlini 6980
./run_extra.sh mnist b adversarial carlini 6980
./run_extra.sh mnist b relu carlini 6980
./run_extra.sh mnist c standard carlini 6980
./run_extra.sh mnist c adversarial carlini 6980
./run_extra.sh mnist c relu carlini 6980
./run_extra.sh mnist a standard carlini 3048
./run_extra.sh mnist a adversarial carlini 3048
./run_extra.sh mnist a relu carlini 3048
./run_extra.sh mnist b standard carlini 3048
./run_extra.sh mnist b adversarial carlini 3048
./run_extra.sh mnist b relu carlini 3048
./run_extra.sh mnist c standard carlini 3048
./run_extra.sh mnist c adversarial carlini 3048
./run_extra.sh mnist c relu carlini 3048
./run_extra.sh mnist a standard carlini 6727
./run_extra.sh mnist a adversarial carlini 6727
./run_extra.sh mnist a relu carlini 6727
./run_extra.sh mnist b standard carlini 6727
./run_extra.sh mnist b adversarial carlini 6727
./run_extra.sh mnist b relu carlini 6727
./run_extra.sh mnist c standard carlini 6727
./run_extra.sh mnist c adversarial carlini 6727
./run_extra.sh mnist c relu carlini 6727
./run_extra.sh mnist a standard carlini 2155
./run_extra.sh mnist a adversarial carlini 2155
./run_extra.sh mnist a relu carlini 2155
./run_extra.sh mnist b standard carlini 2155
./run_extra.sh mnist b adversarial carlini 2155
./run_extra.sh mnist b relu carlini 2155
./run_extra.sh mnist c standard carlini 2155
./run_extra.sh mnist c adversarial carlini 2155
./run_extra.sh mnist c relu carlini 2155
./run_extra.sh mnist a standard carlini 9395
./run_extra.sh mnist a adversarial carlini 9395
./run_extra.sh mnist a relu carlini 9395
./run_extra.sh mnist b standard carlini 9395
./run_extra.sh mnist b adversarial carlini 9395
./run_extra.sh mnist b relu carlini 9395
./run_extra.sh mnist c standard carlini 9395
./run_extra.sh mnist c adversarial carlini 9395
./run_extra.sh mnist c relu carlini 9395
./run_extra.sh mnist a standard carlini 2674
./run_extra.sh mnist a adversarial carlini 2674
./run_extra.sh mnist a relu carlini 2674
./run_extra.sh mnist b standard carlini 2674
./run_extra.sh mnist b adversarial carlini 2674
./run_extra.sh mnist b relu carlini 2674
./run_extra.sh mnist c standard carlini 2674
./run_extra.sh mnist c adversarial carlini 2674
./run_extra.sh mnist c relu carlini 2674
./run_extra.sh mnist a standard carlini 6346
./run_extra.sh mnist a adversarial carlini 6346
./run_extra.sh mnist a relu carlini 6346
./run_extra.sh mnist b standard carlini 6346
./run_extra.sh mnist b adversarial carlini 6346
./run_extra.sh mnist b relu carlini 6346
./run_extra.sh mnist c standard carlini 6346
./run_extra.sh mnist c adversarial carlini 6346
./run_extra.sh mnist c relu carlini 6346
./run_extra.sh mnist a standard carlini 800
./run_extra.sh mnist a adversarial carlini 800
./run_extra.sh mnist a relu carlini 800
./run_extra.sh mnist b standard carlini 800
./run_extra.sh mnist b adversarial carlini 800
./run_extra.sh mnist b relu carlini 800
./run_extra.sh mnist c standard carlini 800
./run_extra.sh mnist c adversarial carlini 800
./run_extra.sh mnist c relu carlini 800
./run_extra.sh mnist a standard carlini 4591
./run_extra.sh mnist a adversarial carlini 4591
./run_extra.sh mnist a relu carlini 4591
./run_extra.sh mnist b standard carlini 4591
./run_extra.sh mnist b adversarial carlini 4591
./run_extra.sh mnist b relu carlini 4591
./run_extra.sh mnist c standard carlini 4591
./run_extra.sh mnist c adversarial carlini 4591
./run_extra.sh mnist c relu carlini 4591
./run_extra.sh mnist a standard carlini 1352
./run_extra.sh mnist a adversarial carlini 1352
./run_extra.sh mnist a relu carlini 1352
./run_extra.sh mnist b standard carlini 1352
./run_extra.sh mnist b adversarial carlini 1352
./run_extra.sh mnist b relu carlini 1352
./run_extra.sh mnist c standard carlini 1352
./run_extra.sh mnist c adversarial carlini 1352
./run_extra.sh mnist c relu carlini 1352
./run_extra.sh mnist a standard carlini 1609
./run_extra.sh mnist a adversarial carlini 1609
./run_extra.sh mnist a relu carlini 1609
./run_extra.sh mnist b standard carlini 1609
./run_extra.sh mnist b adversarial carlini 1609
./run_extra.sh mnist b relu carlini 1609
./run_extra.sh mnist c standard carlini 1609
./run_extra.sh mnist c adversarial carlini 1609
./run_extra.sh mnist c relu carlini 1609
./run_extra.sh mnist a standard carlini 2667
./run_extra.sh mnist a adversarial carlini 2667
./run_extra.sh mnist a relu carlini 2667
./run_extra.sh mnist b standard carlini 2667
./run_extra.sh mnist b adversarial carlini 2667
./run_extra.sh mnist b relu carlini 2667
./run_extra.sh mnist c standard carlini 2667
./run_extra.sh mnist c adversarial carlini 2667
./run_extra.sh mnist c relu carlini 2667
./run_extra.sh mnist a standard carlini 8856
./run_extra.sh mnist a adversarial carlini 8856
./run_extra.sh mnist a relu carlini 8856
./run_extra.sh mnist b standard carlini 8856
./run_extra.sh mnist b adversarial carlini 8856
./run_extra.sh mnist b relu carlini 8856
./run_extra.sh mnist c standard carlini 8856
./run_extra.sh mnist c adversarial carlini 8856
./run_extra.sh mnist c relu carlini 8856
./run_extra.sh mnist a standard carlini 5743
./run_extra.sh mnist a adversarial carlini 5743
./run_extra.sh mnist a relu carlini 5743
./run_extra.sh mnist b standard carlini 5743
./run_extra.sh mnist b adversarial carlini 5743
./run_extra.sh mnist b relu carlini 5743
./run_extra.sh mnist c standard carlini 5743
./run_extra.sh mnist c adversarial carlini 5743
./run_extra.sh mnist c relu carlini 5743
./run_extra.sh mnist a standard carlini 7241
./run_extra.sh mnist a adversarial carlini 7241
./run_extra.sh mnist a relu carlini 7241
./run_extra.sh mnist b standard carlini 7241
./run_extra.sh mnist b adversarial carlini 7241
./run_extra.sh mnist b relu carlini 7241
./run_extra.sh mnist c standard carlini 7241
./run_extra.sh mnist c adversarial carlini 7241
./run_extra.sh mnist c relu carlini 7241
./run_extra.sh mnist a standard carlini 9021
./run_extra.sh mnist a adversarial carlini 9021
./run_extra.sh mnist a relu carlini 9021
./run_extra.sh mnist b standard carlini 9021
./run_extra.sh mnist b adversarial carlini 9021
./run_extra.sh mnist b relu carlini 9021
./run_extra.sh mnist c standard carlini 9021
./run_extra.sh mnist c adversarial carlini 9021
./run_extra.sh mnist c relu carlini 9021
./run_extra.sh mnist a standard carlini 2680
./run_extra.sh mnist a adversarial carlini 2680
./run_extra.sh mnist a relu carlini 2680
./run_extra.sh mnist b standard carlini 2680
./run_extra.sh mnist b adversarial carlini 2680
./run_extra.sh mnist b relu carlini 2680
./run_extra.sh mnist c standard carlini 2680
./run_extra.sh mnist c adversarial carlini 2680
./run_extra.sh mnist c relu carlini 2680
./run_extra.sh mnist a standard carlini 4077
./run_extra.sh mnist a adversarial carlini 4077
./run_extra.sh mnist a relu carlini 4077
./run_extra.sh mnist b standard carlini 4077
./run_extra.sh mnist b adversarial carlini 4077
./run_extra.sh mnist b relu carlini 4077
./run_extra.sh mnist c standard carlini 4077
./run_extra.sh mnist c adversarial carlini 4077
./run_extra.sh mnist c relu carlini 4077
./run_extra.sh mnist a standard carlini 895
./run_extra.sh mnist a adversarial carlini 895
./run_extra.sh mnist a relu carlini 895
./run_extra.sh mnist b standard carlini 895
./run_extra.sh mnist b adversarial carlini 895
./run_extra.sh mnist b relu carlini 895
./run_extra.sh mnist c standard carlini 895
./run_extra.sh mnist c adversarial carlini 895
./run_extra.sh mnist c relu carlini 895
./run_extra.sh mnist a standard carlini 3506
./run_extra.sh mnist a adversarial carlini 3506
./run_extra.sh mnist a relu carlini 3506
./run_extra.sh mnist b standard carlini 3506
./run_extra.sh mnist b adversarial carlini 3506
./run_extra.sh mnist b relu carlini 3506
./run_extra.sh mnist c standard carlini 3506
./run_extra.sh mnist c adversarial carlini 3506
./run_extra.sh mnist c relu carlini 3506
./run_extra.sh mnist a standard carlini 2505
./run_extra.sh mnist a adversarial carlini 2505
./run_extra.sh mnist a relu carlini 2505
./run_extra.sh mnist b standard carlini 2505
./run_extra.sh mnist b adversarial carlini 2505
./run_extra.sh mnist b relu carlini 2505
./run_extra.sh mnist c standard carlini 2505
./run_extra.sh mnist c adversarial carlini 2505
./run_extra.sh mnist c relu carlini 2505
./run_extra.sh mnist a standard carlini 5004
./run_extra.sh mnist a adversarial carlini 5004
./run_extra.sh mnist a relu carlini 5004
./run_extra.sh mnist b standard carlini 5004
./run_extra.sh mnist b adversarial carlini 5004
./run_extra.sh mnist b relu carlini 5004
./run_extra.sh mnist c standard carlini 5004
./run_extra.sh mnist c adversarial carlini 5004
./run_extra.sh mnist c relu carlini 5004
./run_extra.sh mnist a standard carlini 7808
./run_extra.sh mnist a adversarial carlini 7808
./run_extra.sh mnist a relu carlini 7808
./run_extra.sh mnist b standard carlini 7808
./run_extra.sh mnist b adversarial carlini 7808
./run_extra.sh mnist b relu carlini 7808
./run_extra.sh mnist c standard carlini 7808
./run_extra.sh mnist c adversarial carlini 7808
./run_extra.sh mnist c relu carlini 7808
./run_extra.sh mnist a standard carlini 5372
./run_extra.sh mnist a adversarial carlini 5372
./run_extra.sh mnist a relu carlini 5372
./run_extra.sh mnist b standard carlini 5372
./run_extra.sh mnist b adversarial carlini 5372
./run_extra.sh mnist b relu carlini 5372
./run_extra.sh mnist c standard carlini 5372
./run_extra.sh mnist c adversarial carlini 5372
./run_extra.sh mnist c relu carlini 5372
./run_extra.sh mnist a standard carlini 8373
./run_extra.sh mnist a adversarial carlini 8373
./run_extra.sh mnist a relu carlini 8373
./run_extra.sh mnist b standard carlini 8373
./run_extra.sh mnist b adversarial carlini 8373
./run_extra.sh mnist b relu carlini 8373
./run_extra.sh mnist c standard carlini 8373
./run_extra.sh mnist c adversarial carlini 8373
./run_extra.sh mnist c relu carlini 8373
./run_extra.sh mnist a standard carlini 6753
./run_extra.sh mnist a adversarial carlini 6753
./run_extra.sh mnist a relu carlini 6753
./run_extra.sh mnist b standard carlini 6753
./run_extra.sh mnist b adversarial carlini 6753
./run_extra.sh mnist b relu carlini 6753
./run_extra.sh mnist c standard carlini 6753
./run_extra.sh mnist c adversarial carlini 6753
./run_extra.sh mnist c relu carlini 6753
./run_extra.sh mnist a standard carlini 5116
./run_extra.sh mnist a adversarial carlini 5116
./run_extra.sh mnist a relu carlini 5116
./run_extra.sh mnist b standard carlini 5116
./run_extra.sh mnist b adversarial carlini 5116
./run_extra.sh mnist b relu carlini 5116
./run_extra.sh mnist c standard carlini 5116
./run_extra.sh mnist c adversarial carlini 5116
./run_extra.sh mnist c relu carlini 5116
./run_extra.sh mnist a standard carlini 4403
./run_extra.sh mnist a adversarial carlini 4403
./run_extra.sh mnist a relu carlini 4403
./run_extra.sh mnist b standard carlini 4403
./run_extra.sh mnist b adversarial carlini 4403
./run_extra.sh mnist b relu carlini 4403
./run_extra.sh mnist c standard carlini 4403
./run_extra.sh mnist c adversarial carlini 4403
./run_extra.sh mnist c relu carlini 4403
./run_extra.sh mnist a standard carlini 2284
./run_extra.sh mnist a adversarial carlini 2284
./run_extra.sh mnist a relu carlini 2284
./run_extra.sh mnist b standard carlini 2284
./run_extra.sh mnist b adversarial carlini 2284
./run_extra.sh mnist b relu carlini 2284
./run_extra.sh mnist c standard carlini 2284
./run_extra.sh mnist c adversarial carlini 2284
./run_extra.sh mnist c relu carlini 2284
./run_extra.sh mnist a standard carlini 4420
./run_extra.sh mnist a adversarial carlini 4420
./run_extra.sh mnist a relu carlini 4420
./run_extra.sh mnist b standard carlini 4420
./run_extra.sh mnist b adversarial carlini 4420
./run_extra.sh mnist b relu carlini 4420
./run_extra.sh mnist c standard carlini 4420
./run_extra.sh mnist c adversarial carlini 4420
./run_extra.sh mnist c relu carlini 4420
./run_extra.sh mnist a standard carlini 7416
./run_extra.sh mnist a adversarial carlini 7416
./run_extra.sh mnist a relu carlini 7416
./run_extra.sh mnist b standard carlini 7416
./run_extra.sh mnist b adversarial carlini 7416
./run_extra.sh mnist b relu carlini 7416
./run_extra.sh mnist c standard carlini 7416
./run_extra.sh mnist c adversarial carlini 7416
./run_extra.sh mnist c relu carlini 7416
./run_extra.sh mnist a standard carlini 2459
./run_extra.sh mnist a adversarial carlini 2459
./run_extra.sh mnist a relu carlini 2459
./run_extra.sh mnist b standard carlini 2459
./run_extra.sh mnist b adversarial carlini 2459
./run_extra.sh mnist b relu carlini 2459
./run_extra.sh mnist c standard carlini 2459
./run_extra.sh mnist c adversarial carlini 2459
./run_extra.sh mnist c relu carlini 2459
./run_extra.sh mnist a standard carlini 9464
./run_extra.sh mnist a adversarial carlini 9464
./run_extra.sh mnist a relu carlini 9464
./run_extra.sh mnist b standard carlini 9464
./run_extra.sh mnist b adversarial carlini 9464
./run_extra.sh mnist b relu carlini 9464
./run_extra.sh mnist c standard carlini 9464
./run_extra.sh mnist c adversarial carlini 9464
./run_extra.sh mnist c relu carlini 9464
./run_extra.sh mnist a standard carlini 409
./run_extra.sh mnist a adversarial carlini 409
./run_extra.sh mnist a relu carlini 409
./run_extra.sh mnist b standard carlini 409
./run_extra.sh mnist b adversarial carlini 409
./run_extra.sh mnist b relu carlini 409
./run_extra.sh mnist c standard carlini 409
./run_extra.sh mnist c adversarial carlini 409
./run_extra.sh mnist c relu carlini 409
./run_extra.sh mnist a standard carlini 4819
./run_extra.sh mnist a adversarial carlini 4819
./run_extra.sh mnist a relu carlini 4819
./run_extra.sh mnist b standard carlini 4819
./run_extra.sh mnist b adversarial carlini 4819
./run_extra.sh mnist b relu carlini 4819
./run_extra.sh mnist c standard carlini 4819
./run_extra.sh mnist c adversarial carlini 4819
./run_extra.sh mnist c relu carlini 4819
./run_extra.sh mnist a standard carlini 1384
./run_extra.sh mnist a adversarial carlini 1384
./run_extra.sh mnist a relu carlini 1384
./run_extra.sh mnist b standard carlini 1384
./run_extra.sh mnist b adversarial carlini 1384
./run_extra.sh mnist b relu carlini 1384
./run_extra.sh mnist c standard carlini 1384
./run_extra.sh mnist c adversarial carlini 1384
./run_extra.sh mnist c relu carlini 1384
./run_extra.sh mnist a standard carlini 5222
./run_extra.sh mnist a adversarial carlini 5222
./run_extra.sh mnist a relu carlini 5222
./run_extra.sh mnist b standard carlini 5222
./run_extra.sh mnist b adversarial carlini 5222
./run_extra.sh mnist b relu carlini 5222
./run_extra.sh mnist c standard carlini 5222
./run_extra.sh mnist c adversarial carlini 5222
./run_extra.sh mnist c relu carlini 5222
./run_extra.sh mnist a standard carlini 6749
./run_extra.sh mnist a adversarial carlini 6749
./run_extra.sh mnist a relu carlini 6749
./run_extra.sh mnist b standard carlini 6749
./run_extra.sh mnist b adversarial carlini 6749
./run_extra.sh mnist b relu carlini 6749
./run_extra.sh mnist c standard carlini 6749
./run_extra.sh mnist c adversarial carlini 6749
./run_extra.sh mnist c relu carlini 6749
./run_extra.sh mnist a standard carlini 8869
./run_extra.sh mnist a adversarial carlini 8869
./run_extra.sh mnist a relu carlini 8869
./run_extra.sh mnist b standard carlini 8869
./run_extra.sh mnist b adversarial carlini 8869
./run_extra.sh mnist b relu carlini 8869
./run_extra.sh mnist c standard carlini 8869
./run_extra.sh mnist c adversarial carlini 8869
./run_extra.sh mnist c relu carlini 8869
./run_extra.sh mnist a standard carlini 3698
./run_extra.sh mnist a adversarial carlini 3698
./run_extra.sh mnist a relu carlini 3698
./run_extra.sh mnist b standard carlini 3698
./run_extra.sh mnist b adversarial carlini 3698
./run_extra.sh mnist b relu carlini 3698
./run_extra.sh mnist c standard carlini 3698
./run_extra.sh mnist c adversarial carlini 3698
./run_extra.sh mnist c relu carlini 3698
./run_extra.sh mnist a standard carlini 9748
./run_extra.sh mnist a adversarial carlini 9748
./run_extra.sh mnist a relu carlini 9748
./run_extra.sh mnist b standard carlini 9748
./run_extra.sh mnist b adversarial carlini 9748
./run_extra.sh mnist b relu carlini 9748
./run_extra.sh mnist c standard carlini 9748
./run_extra.sh mnist c adversarial carlini 9748
./run_extra.sh mnist c relu carlini 9748
./run_extra.sh mnist a standard carlini 5686
./run_extra.sh mnist a adversarial carlini 5686
./run_extra.sh mnist a relu carlini 5686
./run_extra.sh mnist b standard carlini 5686
./run_extra.sh mnist b adversarial carlini 5686
./run_extra.sh mnist b relu carlini 5686
./run_extra.sh mnist c standard carlini 5686
./run_extra.sh mnist c adversarial carlini 5686
./run_extra.sh mnist c relu carlini 5686
./run_extra.sh mnist a standard carlini 337
./run_extra.sh mnist a adversarial carlini 337
./run_extra.sh mnist a relu carlini 337
./run_extra.sh mnist b standard carlini 337
./run_extra.sh mnist b adversarial carlini 337
./run_extra.sh mnist b relu carlini 337
./run_extra.sh mnist c standard carlini 337
./run_extra.sh mnist c adversarial carlini 337
./run_extra.sh mnist c relu carlini 337
./run_extra.sh mnist a standard carlini 3748
./run_extra.sh mnist a adversarial carlini 3748
./run_extra.sh mnist a relu carlini 3748
./run_extra.sh mnist b standard carlini 3748
./run_extra.sh mnist b adversarial carlini 3748
./run_extra.sh mnist b relu carlini 3748
./run_extra.sh mnist c standard carlini 3748
./run_extra.sh mnist c adversarial carlini 3748
./run_extra.sh mnist c relu carlini 3748
./run_extra.sh mnist a standard carlini 3776
./run_extra.sh mnist a adversarial carlini 3776
./run_extra.sh mnist a relu carlini 3776
./run_extra.sh mnist b standard carlini 3776
./run_extra.sh mnist b adversarial carlini 3776
./run_extra.sh mnist b relu carlini 3776
./run_extra.sh mnist c standard carlini 3776
./run_extra.sh mnist c adversarial carlini 3776
./run_extra.sh mnist c relu carlini 3776
./run_extra.sh mnist a standard carlini 4376
./run_extra.sh mnist a adversarial carlini 4376
./run_extra.sh mnist a relu carlini 4376
./run_extra.sh mnist b standard carlini 4376
./run_extra.sh mnist b adversarial carlini 4376
./run_extra.sh mnist b relu carlini 4376
./run_extra.sh mnist c standard carlini 4376
./run_extra.sh mnist c adversarial carlini 4376
./run_extra.sh mnist c relu carlini 4376
./run_extra.sh mnist a standard carlini 8053
./run_extra.sh mnist a adversarial carlini 8053
./run_extra.sh mnist a relu carlini 8053
./run_extra.sh mnist b standard carlini 8053
./run_extra.sh mnist b adversarial carlini 8053
./run_extra.sh mnist b relu carlini 8053
./run_extra.sh mnist c standard carlini 8053
./run_extra.sh mnist c adversarial carlini 8053
./run_extra.sh mnist c relu carlini 8053
./run_extra.sh mnist a standard carlini 9542
./run_extra.sh mnist a adversarial carlini 9542
./run_extra.sh mnist a relu carlini 9542
./run_extra.sh mnist b standard carlini 9542
./run_extra.sh mnist b adversarial carlini 9542
./run_extra.sh mnist b relu carlini 9542
./run_extra.sh mnist c standard carlini 9542
./run_extra.sh mnist c adversarial carlini 9542
./run_extra.sh mnist c relu carlini 9542
./run_extra.sh mnist a standard carlini 4350
./run_extra.sh mnist a adversarial carlini 4350
./run_extra.sh mnist a relu carlini 4350
./run_extra.sh mnist b standard carlini 4350
./run_extra.sh mnist b adversarial carlini 4350
./run_extra.sh mnist b relu carlini 4350
./run_extra.sh mnist c standard carlini 4350
./run_extra.sh mnist c adversarial carlini 4350
./run_extra.sh mnist c relu carlini 4350
./run_extra.sh mnist a standard carlini 8096
./run_extra.sh mnist a adversarial carlini 8096
./run_extra.sh mnist a relu carlini 8096
./run_extra.sh mnist b standard carlini 8096
./run_extra.sh mnist b adversarial carlini 8096
./run_extra.sh mnist b relu carlini 8096
./run_extra.sh mnist c standard carlini 8096
./run_extra.sh mnist c adversarial carlini 8096
./run_extra.sh mnist c relu carlini 8096
./run_extra.sh mnist a standard carlini 6139
./run_extra.sh mnist a adversarial carlini 6139
./run_extra.sh mnist a relu carlini 6139
./run_extra.sh mnist b standard carlini 6139
./run_extra.sh mnist b adversarial carlini 6139
./run_extra.sh mnist b relu carlini 6139
./run_extra.sh mnist c standard carlini 6139
./run_extra.sh mnist c adversarial carlini 6139
./run_extra.sh mnist c relu carlini 6139
./run_extra.sh mnist a standard carlini 4736
./run_extra.sh mnist a adversarial carlini 4736
./run_extra.sh mnist a relu carlini 4736
./run_extra.sh mnist b standard carlini 4736
./run_extra.sh mnist b adversarial carlini 4736
./run_extra.sh mnist b relu carlini 4736
./run_extra.sh mnist c standard carlini 4736
./run_extra.sh mnist c adversarial carlini 4736
./run_extra.sh mnist c relu carlini 4736
./run_extra.sh mnist a standard carlini 5489
./run_extra.sh mnist a adversarial carlini 5489
./run_extra.sh mnist a relu carlini 5489
./run_extra.sh mnist b standard carlini 5489
./run_extra.sh mnist b adversarial carlini 5489
./run_extra.sh mnist b relu carlini 5489
./run_extra.sh mnist c standard carlini 5489
./run_extra.sh mnist c adversarial carlini 5489
./run_extra.sh mnist c relu carlini 5489
./run_extra.sh mnist a standard carlini 3730
./run_extra.sh mnist a adversarial carlini 3730
./run_extra.sh mnist a relu carlini 3730
./run_extra.sh mnist b standard carlini 3730
./run_extra.sh mnist b adversarial carlini 3730
./run_extra.sh mnist b relu carlini 3730
./run_extra.sh mnist c standard carlini 3730
./run_extra.sh mnist c adversarial carlini 3730
./run_extra.sh mnist c relu carlini 3730
./run_extra.sh mnist a standard carlini 2922
./run_extra.sh mnist a adversarial carlini 2922
./run_extra.sh mnist a relu carlini 2922
./run_extra.sh mnist b standard carlini 2922
./run_extra.sh mnist b adversarial carlini 2922
./run_extra.sh mnist b relu carlini 2922
./run_extra.sh mnist c standard carlini 2922
./run_extra.sh mnist c adversarial carlini 2922
./run_extra.sh mnist c relu carlini 2922
./run_extra.sh mnist a standard carlini 8538
./run_extra.sh mnist a adversarial carlini 8538
./run_extra.sh mnist a relu carlini 8538
./run_extra.sh mnist b standard carlini 8538
./run_extra.sh mnist b adversarial carlini 8538
./run_extra.sh mnist b relu carlini 8538
./run_extra.sh mnist c standard carlini 8538
./run_extra.sh mnist c adversarial carlini 8538
./run_extra.sh mnist c relu carlini 8538
./run_extra.sh mnist a standard carlini 3944
./run_extra.sh mnist a adversarial carlini 3944
./run_extra.sh mnist a relu carlini 3944
./run_extra.sh mnist b standard carlini 3944
./run_extra.sh mnist b adversarial carlini 3944
./run_extra.sh mnist b relu carlini 3944
./run_extra.sh mnist c standard carlini 3944
./run_extra.sh mnist c adversarial carlini 3944
./run_extra.sh mnist c relu carlini 3944
./run_extra.sh mnist a standard carlini 7180
./run_extra.sh mnist a adversarial carlini 7180
./run_extra.sh mnist a relu carlini 7180
./run_extra.sh mnist b standard carlini 7180
./run_extra.sh mnist b adversarial carlini 7180
./run_extra.sh mnist b relu carlini 7180
./run_extra.sh mnist c standard carlini 7180
./run_extra.sh mnist c adversarial carlini 7180
./run_extra.sh mnist c relu carlini 7180
./run_extra.sh mnist a standard carlini 1406
./run_extra.sh mnist a adversarial carlini 1406
./run_extra.sh mnist a relu carlini 1406
./run_extra.sh mnist b standard carlini 1406
./run_extra.sh mnist b adversarial carlini 1406
./run_extra.sh mnist b relu carlini 1406
./run_extra.sh mnist c standard carlini 1406
./run_extra.sh mnist c adversarial carlini 1406
./run_extra.sh mnist c relu carlini 1406
./run_extra.sh mnist a standard carlini 9440
./run_extra.sh mnist a adversarial carlini 9440
./run_extra.sh mnist a relu carlini 9440
./run_extra.sh mnist b standard carlini 9440
./run_extra.sh mnist b adversarial carlini 9440
./run_extra.sh mnist b relu carlini 9440
./run_extra.sh mnist c standard carlini 9440
./run_extra.sh mnist c adversarial carlini 9440
./run_extra.sh mnist c relu carlini 9440
./run_extra.sh mnist a standard carlini 9873
./run_extra.sh mnist a adversarial carlini 9873
./run_extra.sh mnist a relu carlini 9873
./run_extra.sh mnist b standard carlini 9873
./run_extra.sh mnist b adversarial carlini 9873
./run_extra.sh mnist b relu carlini 9873
./run_extra.sh mnist c standard carlini 9873
./run_extra.sh mnist c adversarial carlini 9873
./run_extra.sh mnist c relu carlini 9873
./run_extra.sh mnist a standard carlini 396
./run_extra.sh mnist a adversarial carlini 396
./run_extra.sh mnist a relu carlini 396
./run_extra.sh mnist b standard carlini 396
./run_extra.sh mnist b adversarial carlini 396
./run_extra.sh mnist b relu carlini 396
./run_extra.sh mnist c standard carlini 396
./run_extra.sh mnist c adversarial carlini 396
./run_extra.sh mnist c relu carlini 396
./run_extra.sh mnist a standard carlini 5292
./run_extra.sh mnist a adversarial carlini 5292
./run_extra.sh mnist a relu carlini 5292
./run_extra.sh mnist b standard carlini 5292
./run_extra.sh mnist b adversarial carlini 5292
./run_extra.sh mnist b relu carlini 5292
./run_extra.sh mnist c standard carlini 5292
./run_extra.sh mnist c adversarial carlini 5292
./run_extra.sh mnist c relu carlini 5292
./run_extra.sh mnist a standard carlini 2771
./run_extra.sh mnist a adversarial carlini 2771
./run_extra.sh mnist a relu carlini 2771
./run_extra.sh mnist b standard carlini 2771
./run_extra.sh mnist b adversarial carlini 2771
./run_extra.sh mnist b relu carlini 2771
./run_extra.sh mnist c standard carlini 2771
./run_extra.sh mnist c adversarial carlini 2771
./run_extra.sh mnist c relu carlini 2771
./run_extra.sh mnist a standard carlini 4911
./run_extra.sh mnist a adversarial carlini 4911
./run_extra.sh mnist a relu carlini 4911
./run_extra.sh mnist b standard carlini 4911
./run_extra.sh mnist b adversarial carlini 4911
./run_extra.sh mnist b relu carlini 4911
./run_extra.sh mnist c standard carlini 4911
./run_extra.sh mnist c adversarial carlini 4911
./run_extra.sh mnist c relu carlini 4911
./run_extra.sh mnist a standard carlini 2891
./run_extra.sh mnist a adversarial carlini 2891
./run_extra.sh mnist a relu carlini 2891
./run_extra.sh mnist b standard carlini 2891
./run_extra.sh mnist b adversarial carlini 2891
./run_extra.sh mnist b relu carlini 2891
./run_extra.sh mnist c standard carlini 2891
./run_extra.sh mnist c adversarial carlini 2891
./run_extra.sh mnist c relu carlini 2891
./run_extra.sh mnist a standard carlini 3675
./run_extra.sh mnist a adversarial carlini 3675
./run_extra.sh mnist a relu carlini 3675
./run_extra.sh mnist b standard carlini 3675
./run_extra.sh mnist b adversarial carlini 3675
./run_extra.sh mnist b relu carlini 3675
./run_extra.sh mnist c standard carlini 3675
./run_extra.sh mnist c adversarial carlini 3675
./run_extra.sh mnist c relu carlini 3675
./run_extra.sh mnist a standard carlini 692
./run_extra.sh mnist a adversarial carlini 692
./run_extra.sh mnist a relu carlini 692
./run_extra.sh mnist b standard carlini 692
./run_extra.sh mnist b adversarial carlini 692
./run_extra.sh mnist b relu carlini 692
./run_extra.sh mnist c standard carlini 692
./run_extra.sh mnist c adversarial carlini 692
./run_extra.sh mnist c relu carlini 692
./run_extra.sh mnist a standard carlini 777
./run_extra.sh mnist a adversarial carlini 777
./run_extra.sh mnist a relu carlini 777
./run_extra.sh mnist b standard carlini 777
./run_extra.sh mnist b adversarial carlini 777
./run_extra.sh mnist b relu carlini 777
./run_extra.sh mnist c standard carlini 777
./run_extra.sh mnist c adversarial carlini 777
./run_extra.sh mnist c relu carlini 777
./run_extra.sh mnist a standard carlini 5406
./run_extra.sh mnist a adversarial carlini 5406
./run_extra.sh mnist a relu carlini 5406
./run_extra.sh mnist b standard carlini 5406
./run_extra.sh mnist b adversarial carlini 5406
./run_extra.sh mnist b relu carlini 5406
./run_extra.sh mnist c standard carlini 5406
./run_extra.sh mnist c adversarial carlini 5406
./run_extra.sh mnist c relu carlini 5406
./run_extra.sh mnist a standard carlini 6073
./run_extra.sh mnist a adversarial carlini 6073
./run_extra.sh mnist a relu carlini 6073
./run_extra.sh mnist b standard carlini 6073
./run_extra.sh mnist b adversarial carlini 6073
./run_extra.sh mnist b relu carlini 6073
./run_extra.sh mnist c standard carlini 6073
./run_extra.sh mnist c adversarial carlini 6073
./run_extra.sh mnist c relu carlini 6073
./run_extra.sh mnist a standard carlini 4905
./run_extra.sh mnist a adversarial carlini 4905
./run_extra.sh mnist a relu carlini 4905
./run_extra.sh mnist b standard carlini 4905
./run_extra.sh mnist b adversarial carlini 4905
./run_extra.sh mnist b relu carlini 4905
./run_extra.sh mnist c standard carlini 4905
./run_extra.sh mnist c adversarial carlini 4905
./run_extra.sh mnist c relu carlini 4905
./run_extra.sh mnist a standard carlini 3054
./run_extra.sh mnist a adversarial carlini 3054
./run_extra.sh mnist a relu carlini 3054
./run_extra.sh mnist b standard carlini 3054
./run_extra.sh mnist b adversarial carlini 3054
./run_extra.sh mnist b relu carlini 3054
./run_extra.sh mnist c standard carlini 3054
./run_extra.sh mnist c adversarial carlini 3054
./run_extra.sh mnist c relu carlini 3054
./run_extra.sh mnist a standard carlini 3536
./run_extra.sh mnist a adversarial carlini 3536
./run_extra.sh mnist a relu carlini 3536
./run_extra.sh mnist b standard carlini 3536
./run_extra.sh mnist b adversarial carlini 3536
./run_extra.sh mnist b relu carlini 3536
./run_extra.sh mnist c standard carlini 3536
./run_extra.sh mnist c adversarial carlini 3536
./run_extra.sh mnist c relu carlini 3536
./run_extra.sh mnist a standard carlini 578
./run_extra.sh mnist a adversarial carlini 578
./run_extra.sh mnist a relu carlini 578
./run_extra.sh mnist b standard carlini 578
./run_extra.sh mnist b adversarial carlini 578
./run_extra.sh mnist b relu carlini 578
./run_extra.sh mnist c standard carlini 578
./run_extra.sh mnist c adversarial carlini 578
./run_extra.sh mnist c relu carlini 578
./run_extra.sh mnist a standard carlini 816
./run_extra.sh mnist a adversarial carlini 816
./run_extra.sh mnist a relu carlini 816
./run_extra.sh mnist b standard carlini 816
./run_extra.sh mnist b adversarial carlini 816
./run_extra.sh mnist b relu carlini 816
./run_extra.sh mnist c standard carlini 816
./run_extra.sh mnist c adversarial carlini 816
./run_extra.sh mnist c relu carlini 816
./run_extra.sh mnist a standard carlini 5256
./run_extra.sh mnist a adversarial carlini 5256
./run_extra.sh mnist a relu carlini 5256
./run_extra.sh mnist b standard carlini 5256
./run_extra.sh mnist b adversarial carlini 5256
./run_extra.sh mnist b relu carlini 5256
./run_extra.sh mnist c standard carlini 5256
./run_extra.sh mnist c adversarial carlini 5256
./run_extra.sh mnist c relu carlini 5256
./run_extra.sh mnist a standard carlini 4892
./run_extra.sh mnist a adversarial carlini 4892
./run_extra.sh mnist a relu carlini 4892
./run_extra.sh mnist b standard carlini 4892
./run_extra.sh mnist b adversarial carlini 4892
./run_extra.sh mnist b relu carlini 4892
./run_extra.sh mnist c standard carlini 4892
./run_extra.sh mnist c adversarial carlini 4892
./run_extra.sh mnist c relu carlini 4892
./run_extra.sh mnist a standard carlini 6854
./run_extra.sh mnist a adversarial carlini 6854
./run_extra.sh mnist a relu carlini 6854
./run_extra.sh mnist b standard carlini 6854
./run_extra.sh mnist b adversarial carlini 6854
./run_extra.sh mnist b relu carlini 6854
./run_extra.sh mnist c standard carlini 6854
./run_extra.sh mnist c adversarial carlini 6854
./run_extra.sh mnist c relu carlini 6854
./run_extra.sh mnist a standard carlini 5629
./run_extra.sh mnist a adversarial carlini 5629
./run_extra.sh mnist a relu carlini 5629
./run_extra.sh mnist b standard carlini 5629
./run_extra.sh mnist b adversarial carlini 5629
./run_extra.sh mnist b relu carlini 5629
./run_extra.sh mnist c standard carlini 5629
./run_extra.sh mnist c adversarial carlini 5629
./run_extra.sh mnist c relu carlini 5629
./run_extra.sh mnist a standard carlini 4483
./run_extra.sh mnist a adversarial carlini 4483
./run_extra.sh mnist a relu carlini 4483
./run_extra.sh mnist b standard carlini 4483
./run_extra.sh mnist b adversarial carlini 4483
./run_extra.sh mnist b relu carlini 4483
./run_extra.sh mnist c standard carlini 4483
./run_extra.sh mnist c adversarial carlini 4483
./run_extra.sh mnist c relu carlini 4483
./run_extra.sh mnist a standard carlini 4590
./run_extra.sh mnist a adversarial carlini 4590
./run_extra.sh mnist a relu carlini 4590
./run_extra.sh mnist b standard carlini 4590
./run_extra.sh mnist b adversarial carlini 4590
./run_extra.sh mnist b relu carlini 4590
./run_extra.sh mnist c standard carlini 4590
./run_extra.sh mnist c adversarial carlini 4590
./run_extra.sh mnist c relu carlini 4590
./run_extra.sh mnist a standard carlini 8879
./run_extra.sh mnist a adversarial carlini 8879
./run_extra.sh mnist a relu carlini 8879
./run_extra.sh mnist b standard carlini 8879
./run_extra.sh mnist b adversarial carlini 8879
./run_extra.sh mnist b relu carlini 8879
./run_extra.sh mnist c standard carlini 8879
./run_extra.sh mnist c adversarial carlini 8879
./run_extra.sh mnist c relu carlini 8879
./run_extra.sh mnist a standard carlini 6011
./run_extra.sh mnist a adversarial carlini 6011
./run_extra.sh mnist a relu carlini 6011
./run_extra.sh mnist b standard carlini 6011
./run_extra.sh mnist b adversarial carlini 6011
./run_extra.sh mnist b relu carlini 6011
./run_extra.sh mnist c standard carlini 6011
./run_extra.sh mnist c adversarial carlini 6011
./run_extra.sh mnist c relu carlini 6011
./run_extra.sh mnist a standard carlini 7319
./run_extra.sh mnist a adversarial carlini 7319
./run_extra.sh mnist a relu carlini 7319
./run_extra.sh mnist b standard carlini 7319
./run_extra.sh mnist b adversarial carlini 7319
./run_extra.sh mnist b relu carlini 7319
./run_extra.sh mnist c standard carlini 7319
./run_extra.sh mnist c adversarial carlini 7319
./run_extra.sh mnist c relu carlini 7319
./run_extra.sh mnist a standard carlini 5666
./run_extra.sh mnist a adversarial carlini 5666
./run_extra.sh mnist a relu carlini 5666
./run_extra.sh mnist b standard carlini 5666
./run_extra.sh mnist b adversarial carlini 5666
./run_extra.sh mnist b relu carlini 5666
./run_extra.sh mnist c standard carlini 5666
./run_extra.sh mnist c adversarial carlini 5666
./run_extra.sh mnist c relu carlini 5666
./run_extra.sh mnist a standard carlini 1096
./run_extra.sh mnist a adversarial carlini 1096
./run_extra.sh mnist a relu carlini 1096
./run_extra.sh mnist b standard carlini 1096
./run_extra.sh mnist b adversarial carlini 1096
./run_extra.sh mnist b relu carlini 1096
./run_extra.sh mnist c standard carlini 1096
./run_extra.sh mnist c adversarial carlini 1096
./run_extra.sh mnist c relu carlini 1096
./run_extra.sh mnist a standard carlini 5615
./run_extra.sh mnist a adversarial carlini 5615
./run_extra.sh mnist a relu carlini 5615
./run_extra.sh mnist b standard carlini 5615
./run_extra.sh mnist b adversarial carlini 5615
./run_extra.sh mnist b relu carlini 5615
./run_extra.sh mnist c standard carlini 5615
./run_extra.sh mnist c adversarial carlini 5615
./run_extra.sh mnist c relu carlini 5615
./run_extra.sh mnist a standard carlini 5327
./run_extra.sh mnist a adversarial carlini 5327
./run_extra.sh mnist a relu carlini 5327
./run_extra.sh mnist b standard carlini 5327
./run_extra.sh mnist b adversarial carlini 5327
./run_extra.sh mnist b relu carlini 5327
./run_extra.sh mnist c standard carlini 5327
./run_extra.sh mnist c adversarial carlini 5327
./run_extra.sh mnist c relu carlini 5327
./run_extra.sh mnist a standard carlini 6178
./run_extra.sh mnist a adversarial carlini 6178
./run_extra.sh mnist a relu carlini 6178
./run_extra.sh mnist b standard carlini 6178
./run_extra.sh mnist b adversarial carlini 6178
./run_extra.sh mnist b relu carlini 6178
./run_extra.sh mnist c standard carlini 6178
./run_extra.sh mnist c adversarial carlini 6178
./run_extra.sh mnist c relu carlini 6178
./run_extra.sh mnist a standard carlini 2127
./run_extra.sh mnist a adversarial carlini 2127
./run_extra.sh mnist a relu carlini 2127
./run_extra.sh mnist b standard carlini 2127
./run_extra.sh mnist b adversarial carlini 2127
./run_extra.sh mnist b relu carlini 2127
./run_extra.sh mnist c standard carlini 2127
./run_extra.sh mnist c adversarial carlini 2127
./run_extra.sh mnist c relu carlini 2127
./run_extra.sh mnist a standard carlini 2289
./run_extra.sh mnist a adversarial carlini 2289
./run_extra.sh mnist a relu carlini 2289
./run_extra.sh mnist b standard carlini 2289
./run_extra.sh mnist b adversarial carlini 2289
./run_extra.sh mnist b relu carlini 2289
./run_extra.sh mnist c standard carlini 2289
./run_extra.sh mnist c adversarial carlini 2289
./run_extra.sh mnist c relu carlini 2289
./run_extra.sh mnist a standard carlini 4064
./run_extra.sh mnist a adversarial carlini 4064
./run_extra.sh mnist a relu carlini 4064
./run_extra.sh mnist b standard carlini 4064
./run_extra.sh mnist b adversarial carlini 4064
./run_extra.sh mnist b relu carlini 4064
./run_extra.sh mnist c standard carlini 4064
./run_extra.sh mnist c adversarial carlini 4064
./run_extra.sh mnist c relu carlini 4064
./run_extra.sh mnist a standard carlini 8083
./run_extra.sh mnist a adversarial carlini 8083
./run_extra.sh mnist a relu carlini 8083
./run_extra.sh mnist b standard carlini 8083
./run_extra.sh mnist b adversarial carlini 8083
./run_extra.sh mnist b relu carlini 8083
./run_extra.sh mnist c standard carlini 8083
./run_extra.sh mnist c adversarial carlini 8083
./run_extra.sh mnist c relu carlini 8083
./run_extra.sh mnist a standard carlini 4231
./run_extra.sh mnist a adversarial carlini 4231
./run_extra.sh mnist a relu carlini 4231
./run_extra.sh mnist b standard carlini 4231
./run_extra.sh mnist b adversarial carlini 4231
./run_extra.sh mnist b relu carlini 4231
./run_extra.sh mnist c standard carlini 4231
./run_extra.sh mnist c adversarial carlini 4231
./run_extra.sh mnist c relu carlini 4231
./run_extra.sh mnist a standard carlini 6374
./run_extra.sh mnist a adversarial carlini 6374
./run_extra.sh mnist a relu carlini 6374
./run_extra.sh mnist b standard carlini 6374
./run_extra.sh mnist b adversarial carlini 6374
./run_extra.sh mnist b relu carlini 6374
./run_extra.sh mnist c standard carlini 6374
./run_extra.sh mnist c adversarial carlini 6374
./run_extra.sh mnist c relu carlini 6374
./run_extra.sh mnist a standard carlini 4573
./run_extra.sh mnist a adversarial carlini 4573
./run_extra.sh mnist a relu carlini 4573
./run_extra.sh mnist b standard carlini 4573
./run_extra.sh mnist b adversarial carlini 4573
./run_extra.sh mnist b relu carlini 4573
./run_extra.sh mnist c standard carlini 4573
./run_extra.sh mnist c adversarial carlini 4573
./run_extra.sh mnist c relu carlini 4573
./run_extra.sh mnist a standard carlini 2605
./run_extra.sh mnist a adversarial carlini 2605
./run_extra.sh mnist a relu carlini 2605
./run_extra.sh mnist b standard carlini 2605
./run_extra.sh mnist b adversarial carlini 2605
./run_extra.sh mnist b relu carlini 2605
./run_extra.sh mnist c standard carlini 2605
./run_extra.sh mnist c adversarial carlini 2605
./run_extra.sh mnist c relu carlini 2605
./run_extra.sh mnist a standard carlini 8072
./run_extra.sh mnist a adversarial carlini 8072
./run_extra.sh mnist a relu carlini 8072
./run_extra.sh mnist b standard carlini 8072
./run_extra.sh mnist b adversarial carlini 8072
./run_extra.sh mnist b relu carlini 8072
./run_extra.sh mnist c standard carlini 8072
./run_extra.sh mnist c adversarial carlini 8072
./run_extra.sh mnist c relu carlini 8072
./run_extra.sh mnist a standard carlini 2216
./run_extra.sh mnist a adversarial carlini 2216
./run_extra.sh mnist a relu carlini 2216
./run_extra.sh mnist b standard carlini 2216
./run_extra.sh mnist b adversarial carlini 2216
./run_extra.sh mnist b relu carlini 2216
./run_extra.sh mnist c standard carlini 2216
./run_extra.sh mnist c adversarial carlini 2216
./run_extra.sh mnist c relu carlini 2216
./run_extra.sh mnist a standard carlini 671
./run_extra.sh mnist a adversarial carlini 671
./run_extra.sh mnist a relu carlini 671
./run_extra.sh mnist b standard carlini 671
./run_extra.sh mnist b adversarial carlini 671
./run_extra.sh mnist b relu carlini 671
./run_extra.sh mnist c standard carlini 671
./run_extra.sh mnist c adversarial carlini 671
./run_extra.sh mnist c relu carlini 671
./run_extra.sh mnist a standard carlini 8154
./run_extra.sh mnist a adversarial carlini 8154
./run_extra.sh mnist a relu carlini 8154
./run_extra.sh mnist b standard carlini 8154
./run_extra.sh mnist b adversarial carlini 8154
./run_extra.sh mnist b relu carlini 8154
./run_extra.sh mnist c standard carlini 8154
./run_extra.sh mnist c adversarial carlini 8154
./run_extra.sh mnist c relu carlini 8154
./run_extra.sh mnist a standard carlini 9075
./run_extra.sh mnist a adversarial carlini 9075
./run_extra.sh mnist a relu carlini 9075
./run_extra.sh mnist b standard carlini 9075
./run_extra.sh mnist b adversarial carlini 9075
./run_extra.sh mnist b relu carlini 9075
./run_extra.sh mnist c standard carlini 9075
./run_extra.sh mnist c adversarial carlini 9075
./run_extra.sh mnist c relu carlini 9075
./run_extra.sh mnist a standard carlini 6748
./run_extra.sh mnist a adversarial carlini 6748
./run_extra.sh mnist a relu carlini 6748
./run_extra.sh mnist b standard carlini 6748
./run_extra.sh mnist b adversarial carlini 6748
./run_extra.sh mnist b relu carlini 6748
./run_extra.sh mnist c standard carlini 6748
./run_extra.sh mnist c adversarial carlini 6748
./run_extra.sh mnist c relu carlini 6748
./run_extra.sh mnist a standard carlini 3826
./run_extra.sh mnist a adversarial carlini 3826
./run_extra.sh mnist a relu carlini 3826
./run_extra.sh mnist b standard carlini 3826
./run_extra.sh mnist b adversarial carlini 3826
./run_extra.sh mnist b relu carlini 3826
./run_extra.sh mnist c standard carlini 3826
./run_extra.sh mnist c adversarial carlini 3826
./run_extra.sh mnist c relu carlini 3826
./run_extra.sh mnist a standard carlini 2367
./run_extra.sh mnist a adversarial carlini 2367
./run_extra.sh mnist a relu carlini 2367
./run_extra.sh mnist b standard carlini 2367
./run_extra.sh mnist b adversarial carlini 2367
./run_extra.sh mnist b relu carlini 2367
./run_extra.sh mnist c standard carlini 2367
./run_extra.sh mnist c adversarial carlini 2367
./run_extra.sh mnist c relu carlini 2367
./run_extra.sh mnist a standard carlini 5297
./run_extra.sh mnist a adversarial carlini 5297
./run_extra.sh mnist a relu carlini 5297
./run_extra.sh mnist b standard carlini 5297
./run_extra.sh mnist b adversarial carlini 5297
./run_extra.sh mnist b relu carlini 5297
./run_extra.sh mnist c standard carlini 5297
./run_extra.sh mnist c adversarial carlini 5297
./run_extra.sh mnist c relu carlini 5297
./run_extra.sh mnist a standard carlini 6020
./run_extra.sh mnist a adversarial carlini 6020
./run_extra.sh mnist a relu carlini 6020
./run_extra.sh mnist b standard carlini 6020
./run_extra.sh mnist b adversarial carlini 6020
./run_extra.sh mnist b relu carlini 6020
./run_extra.sh mnist c standard carlini 6020
./run_extra.sh mnist c adversarial carlini 6020
./run_extra.sh mnist c relu carlini 6020
./run_extra.sh mnist a standard carlini 8005
./run_extra.sh mnist a adversarial carlini 8005
./run_extra.sh mnist a relu carlini 8005
./run_extra.sh mnist b standard carlini 8005
./run_extra.sh mnist b adversarial carlini 8005
./run_extra.sh mnist b relu carlini 8005
./run_extra.sh mnist c standard carlini 8005
./run_extra.sh mnist c adversarial carlini 8005
./run_extra.sh mnist c relu carlini 8005
./run_extra.sh mnist a standard carlini 7491
./run_extra.sh mnist a adversarial carlini 7491
./run_extra.sh mnist a relu carlini 7491
./run_extra.sh mnist b standard carlini 7491
./run_extra.sh mnist b adversarial carlini 7491
./run_extra.sh mnist b relu carlini 7491
./run_extra.sh mnist c standard carlini 7491
./run_extra.sh mnist c adversarial carlini 7491
./run_extra.sh mnist c relu carlini 7491
./run_extra.sh mnist a standard carlini 258
./run_extra.sh mnist a adversarial carlini 258
./run_extra.sh mnist a relu carlini 258
./run_extra.sh mnist b standard carlini 258
./run_extra.sh mnist b adversarial carlini 258
./run_extra.sh mnist b relu carlini 258
./run_extra.sh mnist c standard carlini 258
./run_extra.sh mnist c adversarial carlini 258
./run_extra.sh mnist c relu carlini 258
./run_extra.sh mnist a standard carlini 4702
./run_extra.sh mnist a adversarial carlini 4702
./run_extra.sh mnist a relu carlini 4702
./run_extra.sh mnist b standard carlini 4702
./run_extra.sh mnist b adversarial carlini 4702
./run_extra.sh mnist b relu carlini 4702
./run_extra.sh mnist c standard carlini 4702
./run_extra.sh mnist c adversarial carlini 4702
./run_extra.sh mnist c relu carlini 4702
./run_extra.sh mnist a standard carlini 5581
./run_extra.sh mnist a adversarial carlini 5581
./run_extra.sh mnist a relu carlini 5581
./run_extra.sh mnist b standard carlini 5581
./run_extra.sh mnist b adversarial carlini 5581
./run_extra.sh mnist b relu carlini 5581
./run_extra.sh mnist c standard carlini 5581
./run_extra.sh mnist c adversarial carlini 5581
./run_extra.sh mnist c relu carlini 5581
./run_extra.sh mnist a standard carlini 4950
./run_extra.sh mnist a adversarial carlini 4950
./run_extra.sh mnist a relu carlini 4950
./run_extra.sh mnist b standard carlini 4950
./run_extra.sh mnist b adversarial carlini 4950
./run_extra.sh mnist b relu carlini 4950
./run_extra.sh mnist c standard carlini 4950
./run_extra.sh mnist c adversarial carlini 4950
./run_extra.sh mnist c relu carlini 4950
./run_extra.sh mnist a standard carlini 7341
./run_extra.sh mnist a adversarial carlini 7341
./run_extra.sh mnist a relu carlini 7341
./run_extra.sh mnist b standard carlini 7341
./run_extra.sh mnist b adversarial carlini 7341
./run_extra.sh mnist b relu carlini 7341
./run_extra.sh mnist c standard carlini 7341
./run_extra.sh mnist c adversarial carlini 7341
./run_extra.sh mnist c relu carlini 7341
./run_extra.sh mnist a standard carlini 2172
./run_extra.sh mnist a adversarial carlini 2172
./run_extra.sh mnist a relu carlini 2172
./run_extra.sh mnist b standard carlini 2172
./run_extra.sh mnist b adversarial carlini 2172
./run_extra.sh mnist b relu carlini 2172
./run_extra.sh mnist c standard carlini 2172
./run_extra.sh mnist c adversarial carlini 2172
./run_extra.sh mnist c relu carlini 2172
./run_extra.sh mnist a standard carlini 7140
./run_extra.sh mnist a adversarial carlini 7140
./run_extra.sh mnist a relu carlini 7140
./run_extra.sh mnist b standard carlini 7140
./run_extra.sh mnist b adversarial carlini 7140
./run_extra.sh mnist b relu carlini 7140
./run_extra.sh mnist c standard carlini 7140
./run_extra.sh mnist c adversarial carlini 7140
./run_extra.sh mnist c relu carlini 7140
./run_extra.sh mnist a standard carlini 3248
./run_extra.sh mnist a adversarial carlini 3248
./run_extra.sh mnist a relu carlini 3248
./run_extra.sh mnist b standard carlini 3248
./run_extra.sh mnist b adversarial carlini 3248
./run_extra.sh mnist b relu carlini 3248
./run_extra.sh mnist c standard carlini 3248
./run_extra.sh mnist c adversarial carlini 3248
./run_extra.sh mnist c relu carlini 3248
./run_extra.sh mnist a standard carlini 3680
./run_extra.sh mnist a adversarial carlini 3680
./run_extra.sh mnist a relu carlini 3680
./run_extra.sh mnist b standard carlini 3680
./run_extra.sh mnist b adversarial carlini 3680
./run_extra.sh mnist b relu carlini 3680
./run_extra.sh mnist c standard carlini 3680
./run_extra.sh mnist c adversarial carlini 3680
./run_extra.sh mnist c relu carlini 3680
./run_extra.sh mnist a standard carlini 1693
./run_extra.sh mnist a adversarial carlini 1693
./run_extra.sh mnist a relu carlini 1693
./run_extra.sh mnist b standard carlini 1693
./run_extra.sh mnist b adversarial carlini 1693
./run_extra.sh mnist b relu carlini 1693
./run_extra.sh mnist c standard carlini 1693
./run_extra.sh mnist c adversarial carlini 1693
./run_extra.sh mnist c relu carlini 1693
./run_extra.sh mnist a standard carlini 397
./run_extra.sh mnist a adversarial carlini 397
./run_extra.sh mnist a relu carlini 397
./run_extra.sh mnist b standard carlini 397
./run_extra.sh mnist b adversarial carlini 397
./run_extra.sh mnist b relu carlini 397
./run_extra.sh mnist c standard carlini 397
./run_extra.sh mnist c adversarial carlini 397
