./run_extra.sh mnist b adversarial carlini 9144
./run_extra.sh mnist b relu carlini 9144
./run_extra.sh mnist c standard carlini 9144
./run_extra.sh mnist c adversarial carlini 9144
./run_extra.sh mnist c relu carlini 9144
./run_extra.sh mnist a standard carlini 9292
./run_extra.sh mnist a adversarial carlini 9292
./run_extra.sh mnist a relu carlini 9292
./run_extra.sh mnist b standard carlini 9292
./run_extra.sh mnist b adversarial carlini 9292
./run_extra.sh mnist b relu carlini 9292
./run_extra.sh mnist c standard carlini 9292
./run_extra.sh mnist c adversarial carlini 9292
./run_extra.sh mnist c relu carlini 9292
./run_extra.sh mnist a standard carlini 8018
./run_extra.sh mnist a adversarial carlini 8018
./run_extra.sh mnist a relu carlini 8018
./run_extra.sh mnist b standard carlini 8018
./run_extra.sh mnist b adversarial carlini 8018
./run_extra.sh mnist b relu carlini 8018
./run_extra.sh mnist c standard carlini 8018
./run_extra.sh mnist c adversarial carlini 8018
./run_extra.sh mnist c relu carlini 8018
./run_extra.sh mnist a standard carlini 627
./run_extra.sh mnist a adversarial carlini 627
./run_extra.sh mnist a relu carlini 627
./run_extra.sh mnist b standard carlini 627
./run_extra.sh mnist b adversarial carlini 627
./run_extra.sh mnist b relu carlini 627
./run_extra.sh mnist c standard carlini 627
./run_extra.sh mnist c adversarial carlini 627
./run_extra.sh mnist c relu carlini 627
./run_extra.sh mnist a standard carlini 7082
./run_extra.sh mnist a adversarial carlini 7082
./run_extra.sh mnist a relu carlini 7082
./run_extra.sh mnist b standard carlini 7082
./run_extra.sh mnist b adversarial carlini 7082
./run_extra.sh mnist b relu carlini 7082
./run_extra.sh mnist c standard carlini 7082
./run_extra.sh mnist c adversarial carlini 7082
./run_extra.sh mnist c relu carlini 7082
./run_extra.sh mnist a standard carlini 7739
./run_extra.sh mnist a adversarial carlini 7739
./run_extra.sh mnist a relu carlini 7739
./run_extra.sh mnist b standard carlini 7739
./run_extra.sh mnist b adversarial carlini 7739
./run_extra.sh mnist b relu carlini 7739
./run_extra.sh mnist c standard carlini 7739
./run_extra.sh mnist c adversarial carlini 7739
./run_extra.sh mnist c relu carlini 7739
./run_extra.sh mnist a standard carlini 4274
./run_extra.sh mnist a adversarial carlini 4274
./run_extra.sh mnist a relu carlini 4274
./run_extra.sh mnist b standard carlini 4274
./run_extra.sh mnist b adversarial carlini 4274
./run_extra.sh mnist b relu carlini 4274
./run_extra.sh mnist c standard carlini 4274
./run_extra.sh mnist c adversarial carlini 4274
./run_extra.sh mnist c relu carlini 4274
./run_extra.sh mnist a standard carlini 725
./run_extra.sh mnist a adversarial carlini 725
./run_extra.sh mnist a relu carlini 725
./run_extra.sh mnist b standard carlini 725
./run_extra.sh mnist b adversarial carlini 725
./run_extra.sh mnist b relu carlini 725
./run_extra.sh mnist c standard carlini 725
./run_extra.sh mnist c adversarial carlini 725
./run_extra.sh mnist c relu carlini 725
./run_extra.sh mnist a standard carlini 6089
./run_extra.sh mnist a adversarial carlini 6089
./run_extra.sh mnist a relu carlini 6089
./run_extra.sh mnist b standard carlini 6089
./run_extra.sh mnist b adversarial carlini 6089
./run_extra.sh mnist b relu carlini 6089
./run_extra.sh mnist c standard carlini 6089
./run_extra.sh mnist c adversarial carlini 6089
./run_extra.sh mnist c relu carlini 6089
./run_extra.sh mnist a standard carlini 9859
./run_extra.sh mnist a adversarial carlini 9859
./run_extra.sh mnist a relu carlini 9859
./run_extra.sh mnist b standard carlini 9859
./run_extra.sh mnist b adversarial carlini 9859
./run_extra.sh mnist b relu carlini 9859
./run_extra.sh mnist c standard carlini 9859
./run_extra.sh mnist c adversarial carlini 9859
./run_extra.sh mnist c relu carlini 9859
./run_extra.sh mnist a standard carlini 1405
./run_extra.sh mnist a adversarial carlini 1405
./run_extra.sh mnist a relu carlini 1405
./run_extra.sh mnist b standard carlini 1405
./run_extra.sh mnist b adversarial carlini 1405
./run_extra.sh mnist b relu carlini 1405
./run_extra.sh mnist c standard carlini 1405
./run_extra.sh mnist c adversarial carlini 1405
./run_extra.sh mnist c relu carlini 1405
./run_extra.sh mnist a standard carlini 4327
./run_extra.sh mnist a adversarial carlini 4327
./run_extra.sh mnist a relu carlini 4327
./run_extra.sh mnist b standard carlini 4327
./run_extra.sh mnist b adversarial carlini 4327
./run_extra.sh mnist b relu carlini 4327
./run_extra.sh mnist c standard carlini 4327
./run_extra.sh mnist c adversarial carlini 4327
./run_extra.sh mnist c relu carlini 4327
./run_extra.sh mnist a standard carlini 1481
./run_extra.sh mnist a adversarial carlini 1481
./run_extra.sh mnist a relu carlini 1481
./run_extra.sh mnist b standard carlini 1481
./run_extra.sh mnist b adversarial carlini 1481
./run_extra.sh mnist b relu carlini 1481
./run_extra.sh mnist c standard carlini 1481
./run_extra.sh mnist c adversarial carlini 1481
./run_extra.sh mnist c relu carlini 1481
./run_extra.sh mnist a standard carlini 1039
./run_extra.sh mnist a adversarial carlini 1039
./run_extra.sh mnist a relu carlini 1039
./run_extra.sh mnist b standard carlini 1039
./run_extra.sh mnist b adversarial carlini 1039
./run_extra.sh mnist b relu carlini 1039
./run_extra.sh mnist c standard carlini 1039
./run_extra.sh mnist c adversarial carlini 1039
./run_extra.sh mnist c relu carlini 1039
./run_extra.sh mnist a standard carlini 3559
./run_extra.sh mnist a adversarial carlini 3559
./run_extra.sh mnist a relu carlini 3559
./run_extra.sh mnist b standard carlini 3559
./run_extra.sh mnist b adversarial carlini 3559
./run_extra.sh mnist b relu carlini 3559
./run_extra.sh mnist c standard carlini 3559
./run_extra.sh mnist c adversarial carlini 3559
./run_extra.sh mnist c relu carlini 3559
./run_extra.sh mnist a standard carlini 6348
./run_extra.sh mnist a adversarial carlini 6348
./run_extra.sh mnist a relu carlini 6348
./run_extra.sh mnist b standard carlini 6348
./run_extra.sh mnist b adversarial carlini 6348
./run_extra.sh mnist b relu carlini 6348
./run_extra.sh mnist c standard carlini 6348
./run_extra.sh mnist c adversarial carlini 6348
./run_extra.sh mnist c relu carlini 6348
./run_extra.sh mnist a standard carlini 4866
./run_extra.sh mnist a adversarial carlini 4866
./run_extra.sh mnist a relu carlini 4866
./run_extra.sh mnist b standard carlini 4866
./run_extra.sh mnist b adversarial carlini 4866
./run_extra.sh mnist b relu carlini 4866
./run_extra.sh mnist c standard carlini 4866
./run_extra.sh mnist c adversarial carlini 4866
./run_extra.sh mnist c relu carlini 4866
./run_extra.sh mnist a standard carlini 9334
./run_extra.sh mnist a adversarial carlini 9334
./run_extra.sh mnist a relu carlini 9334
./run_extra.sh mnist b standard carlini 9334
./run_extra.sh mnist b adversarial carlini 9334
./run_extra.sh mnist b relu carlini 9334
./run_extra.sh mnist c standard carlini 9334
./run_extra.sh mnist c adversarial carlini 9334
./run_extra.sh mnist c relu carlini 9334
./run_extra.sh mnist a standard carlini 8897
./run_extra.sh mnist a adversarial carlini 8897
./run_extra.sh mnist a relu carlini 8897
./run_extra.sh mnist b standard carlini 8897
./run_extra.sh mnist b adversarial carlini 8897
./run_extra.sh mnist b relu carlini 8897
./run_extra.sh mnist c standard carlini 8897
./run_extra.sh mnist c adversarial carlini 8897
./run_extra.sh mnist c relu carlini 8897
./run_extra.sh mnist a standard carlini 4700
./run_extra.sh mnist a adversarial carlini 4700
./run_extra.sh mnist a relu carlini 4700
./run_extra.sh mnist b standard carlini 4700
./run_extra.sh mnist b adversarial carlini 4700
./run_extra.sh mnist b relu carlini 4700
./run_extra.sh mnist c standard carlini 4700
./run_extra.sh mnist c adversarial carlini 4700
./run_extra.sh mnist c relu carlini 4700
./run_extra.sh mnist a standard carlini 7958
./run_extra.sh mnist a adversarial carlini 7958
./run_extra.sh mnist a relu carlini 7958
./run_extra.sh mnist b standard carlini 7958
./run_extra.sh mnist b adversarial carlini 7958
./run_extra.sh mnist b relu carlini 7958
./run_extra.sh mnist c standard carlini 7958
./run_extra.sh mnist c adversarial carlini 7958
./run_extra.sh mnist c relu carlini 7958
./run_extra.sh mnist a standard carlini 9529
./run_extra.sh mnist a adversarial carlini 9529
./run_extra.sh mnist a relu carlini 9529
./run_extra.sh mnist b standard carlini 9529
./run_extra.sh mnist b adversarial carlini 9529
./run_extra.sh mnist b relu carlini 9529
./run_extra.sh mnist c standard carlini 9529
./run_extra.sh mnist c adversarial carlini 9529
./run_extra.sh mnist c relu carlini 9529
./run_extra.sh mnist a standard carlini 5111
./run_extra.sh mnist a adversarial carlini 5111
./run_extra.sh mnist a relu carlini 5111
./run_extra.sh mnist b standard carlini 5111
./run_extra.sh mnist b adversarial carlini 5111
./run_extra.sh mnist b relu carlini 5111
./run_extra.sh mnist c standard carlini 5111
./run_extra.sh mnist c adversarial carlini 5111
./run_extra.sh mnist c relu carlini 5111
./run_extra.sh mnist a standard carlini 7502
./run_extra.sh mnist a adversarial carlini 7502
./run_extra.sh mnist a relu carlini 7502
./run_extra.sh mnist b standard carlini 7502
./run_extra.sh mnist b adversarial carlini 7502
./run_extra.sh mnist b relu carlini 7502
./run_extra.sh mnist c standard carlini 7502
./run_extra.sh mnist c adversarial carlini 7502
./run_extra.sh mnist c relu carlini 7502
./run_extra.sh mnist a standard carlini 1267
./run_extra.sh mnist a adversarial carlini 1267
./run_extra.sh mnist a relu carlini 1267
./run_extra.sh mnist b standard carlini 1267
./run_extra.sh mnist b adversarial carlini 1267
./run_extra.sh mnist b relu carlini 1267
./run_extra.sh mnist c standard carlini 1267
./run_extra.sh mnist c adversarial carlini 1267
./run_extra.sh mnist c relu carlini 1267
./run_extra.sh mnist a standard carlini 9260
./run_extra.sh mnist a adversarial carlini 9260
./run_extra.sh mnist a relu carlini 9260
./run_extra.sh mnist b standard carlini 9260
./run_extra.sh mnist b adversarial carlini 9260
./run_extra.sh mnist b relu carlini 9260
./run_extra.sh mnist c standard carlini 9260
./run_extra.sh mnist c adversarial carlini 9260
./run_extra.sh mnist c relu carlini 9260
./run_extra.sh mnist a standard carlini 9858
./run_extra.sh mnist a adversarial carlini 9858
./run_extra.sh mnist a relu carlini 9858
./run_extra.sh mnist b standard carlini 9858
./run_extra.sh mnist b adversarial carlini 9858
./run_extra.sh mnist b relu carlini 9858
./run_extra.sh mnist c standard carlini 9858
./run_extra.sh mnist c adversarial carlini 9858
./run_extra.sh mnist c relu carlini 9858
./run_extra.sh mnist a standard carlini 5721
./run_extra.sh mnist a adversarial carlini 5721
./run_extra.sh mnist a relu carlini 5721
./run_extra.sh mnist b standard carlini 5721
./run_extra.sh mnist b adversarial carlini 5721
./run_extra.sh mnist b relu carlini 5721
./run_extra.sh mnist c standard carlini 5721
./run_extra.sh mnist c adversarial carlini 5721
./run_extra.sh mnist c relu carlini 5721
./run_extra.sh mnist a standard carlini 3897
./run_extra.sh mnist a adversarial carlini 3897
./run_extra.sh mnist a relu carlini 3897
./run_extra.sh mnist b standard carlini 3897
./run_extra.sh mnist b adversarial carlini 3897
./run_extra.sh mnist b relu carlini 3897
./run_extra.sh mnist c standard carlini 3897
./run_extra.sh mnist c adversarial carlini 3897
./run_extra.sh mnist c relu carlini 3897
./run_extra.sh mnist a standard carlini 3163
./run_extra.sh mnist a adversarial carlini 3163
./run_extra.sh mnist a relu carlini 3163
./run_extra.sh mnist b standard carlini 3163
./run_extra.sh mnist b adversarial carlini 3163
./run_extra.sh mnist b relu carlini 3163
./run_extra.sh mnist c standard carlini 3163
./run_extra.sh mnist c adversarial carlini 3163
./run_extra.sh mnist c relu carlini 3163
./run_extra.sh mnist a standard carlini 5771
./run_extra.sh mnist a adversarial carlini 5771
./run_extra.sh mnist a relu carlini 5771
./run_extra.sh mnist b standard carlini 5771
./run_extra.sh mnist b adversarial carlini 5771
./run_extra.sh mnist b relu carlini 5771
./run_extra.sh mnist c standard carlini 5771
./run_extra.sh mnist c adversarial carlini 5771
./run_extra.sh mnist c relu carlini 5771
./run_extra.sh mnist a standard carlini 3168
./run_extra.sh mnist a adversarial carlini 3168
./run_extra.sh mnist a relu carlini 3168
./run_extra.sh mnist b standard carlini 3168
./run_extra.sh mnist b adversarial carlini 3168
./run_extra.sh mnist b relu carlini 3168
./run_extra.sh mnist c standard carlini 3168
./run_extra.sh mnist c adversarial carlini 3168
./run_extra.sh mnist c relu carlini 3168
./run_extra.sh mnist a standard carlini 4058
./run_extra.sh mnist a adversarial carlini 4058
./run_extra.sh mnist a relu carlini 4058
./run_extra.sh mnist b standard carlini 4058
./run_extra.sh mnist b adversarial carlini 4058
./run_extra.sh mnist b relu carlini 4058
./run_extra.sh mnist c standard carlini 4058
./run_extra.sh mnist c adversarial carlini 4058
./run_extra.sh mnist c relu carlini 4058
./run_extra.sh mnist a standard carlini 8085
./run_extra.sh mnist a adversarial carlini 8085
./run_extra.sh mnist a relu carlini 8085
./run_extra.sh mnist b standard carlini 8085
./run_extra.sh mnist b adversarial carlini 8085
./run_extra.sh mnist b relu carlini 8085
./run_extra.sh mnist c standard carlini 8085
./run_extra.sh mnist c adversarial carlini 8085
./run_extra.sh mnist c relu carlini 8085
./run_extra.sh mnist a standard carlini 8688
./run_extra.sh mnist a adversarial carlini 8688
./run_extra.sh mnist a relu carlini 8688
./run_extra.sh mnist b standard carlini 8688
./run_extra.sh mnist b adversarial carlini 8688
./run_extra.sh mnist b relu carlini 8688
./run_extra.sh mnist c standard carlini 8688
./run_extra.sh mnist c adversarial carlini 8688
./run_extra.sh mnist c relu carlini 8688
./run_extra.sh mnist a standard carlini 2477
./run_extra.sh mnist a adversarial carlini 2477
./run_extra.sh mnist a relu carlini 2477
./run_extra.sh mnist b standard carlini 2477
./run_extra.sh mnist b adversarial carlini 2477
./run_extra.sh mnist b relu carlini 2477
./run_extra.sh mnist c standard carlini 2477
./run_extra.sh mnist c adversarial carlini 2477
./run_extra.sh mnist c relu carlini 2477
./run_extra.sh mnist a standard carlini 9798
./run_extra.sh mnist a adversarial carlini 9798
./run_extra.sh mnist a relu carlini 9798
./run_extra.sh mnist b standard carlini 9798
./run_extra.sh mnist b adversarial carlini 9798
./run_extra.sh mnist b relu carlini 9798
./run_extra.sh mnist c standard carlini 9798
./run_extra.sh mnist c adversarial carlini 9798
./run_extra.sh mnist c relu carlini 9798
./run_extra.sh mnist a standard carlini 2536
./run_extra.sh mnist a adversarial carlini 2536
./run_extra.sh mnist a relu carlini 2536
./run_extra.sh mnist b standard carlini 2536
./run_extra.sh mnist b adversarial carlini 2536
./run_extra.sh mnist b relu carlini 2536
./run_extra.sh mnist c standard carlini 2536
./run_extra.sh mnist c adversarial carlini 2536
./run_extra.sh mnist c relu carlini 2536
./run_extra.sh mnist a standard carlini 3767
./run_extra.sh mnist a adversarial carlini 3767
./run_extra.sh mnist a relu carlini 3767
./run_extra.sh mnist b standard carlini 3767
./run_extra.sh mnist b adversarial carlini 3767
./run_extra.sh mnist b relu carlini 3767
./run_extra.sh mnist c standard carlini 3767
./run_extra.sh mnist c adversarial carlini 3767
./run_extra.sh mnist c relu carlini 3767
./run_extra.sh mnist a standard carlini 5785
./run_extra.sh mnist a adversarial carlini 5785
./run_extra.sh mnist a relu carlini 5785
./run_extra.sh mnist b standard carlini 5785
./run_extra.sh mnist b adversarial carlini 5785
./run_extra.sh mnist b relu carlini 5785
./run_extra.sh mnist c standard carlini 5785
./run_extra.sh mnist c adversarial carlini 5785
./run_extra.sh mnist c relu carlini 5785
./run_extra.sh mnist a standard carlini 4223
./run_extra.sh mnist a adversarial carlini 4223
./run_extra.sh mnist a relu carlini 4223
./run_extra.sh mnist b standard carlini 4223
./run_extra.sh mnist b adversarial carlini 4223
./run_extra.sh mnist b relu carlini 4223
./run_extra.sh mnist c standard carlini 4223
./run_extra.sh mnist c adversarial carlini 4223
./run_extra.sh mnist c relu carlini 4223
./run_extra.sh mnist a standard carlini 5744
./run_extra.sh mnist a adversarial carlini 5744
./run_extra.sh mnist a relu carlini 5744
./run_extra.sh mnist b standard carlini 5744
./run_extra.sh mnist b adversarial carlini 5744
./run_extra.sh mnist b relu carlini 5744
./run_extra.sh mnist c standard carlini 5744
./run_extra.sh mnist c adversarial carlini 5744
./run_extra.sh mnist c relu carlini 5744
./run_extra.sh mnist a standard carlini 7135
./run_extra.sh mnist a adversarial carlini 7135
./run_extra.sh mnist a relu carlini 7135
./run_extra.sh mnist b standard carlini 7135
./run_extra.sh mnist b adversarial carlini 7135
./run_extra.sh mnist b relu carlini 7135
./run_extra.sh mnist c standard carlini 7135
./run_extra.sh mnist c adversarial carlini 7135
./run_extra.sh mnist c relu carlini 7135
./run_extra.sh mnist a standard carlini 2639
./run_extra.sh mnist a adversarial carlini 2639
./run_extra.sh mnist a relu carlini 2639
./run_extra.sh mnist b standard carlini 2639
./run_extra.sh mnist b adversarial carlini 2639
./run_extra.sh mnist b relu carlini 2639
./run_extra.sh mnist c standard carlini 2639
./run_extra.sh mnist c adversarial carlini 2639
./run_extra.sh mnist c relu carlini 2639
./run_extra.sh mnist a standard carlini 1073
./run_extra.sh mnist a adversarial carlini 1073
./run_extra.sh mnist a relu carlini 1073
./run_extra.sh mnist b standard carlini 1073
./run_extra.sh mnist b adversarial carlini 1073
./run_extra.sh mnist b relu carlini 1073
./run_extra.sh mnist c standard carlini 1073
./run_extra.sh mnist c adversarial carlini 1073
./run_extra.sh mnist c relu carlini 1073
./run_extra.sh mnist a standard carlini 4326
./run_extra.sh mnist a adversarial carlini 4326
./run_extra.sh mnist a relu carlini 4326
./run_extra.sh mnist b standard carlini 4326
./run_extra.sh mnist b adversarial carlini 4326
./run_extra.sh mnist b relu carlini 4326
./run_extra.sh mnist c standard carlini 4326
./run_extra.sh mnist c adversarial carlini 4326
./run_extra.sh mnist c relu carlini 4326
./run_extra.sh mnist a standard carlini 3609
./run_extra.sh mnist a adversarial carlini 3609
./run_extra.sh mnist a relu carlini 3609
./run_extra.sh mnist b standard carlini 3609
./run_extra.sh mnist b adversarial carlini 3609
./run_extra.sh mnist b relu carlini 3609
./run_extra.sh mnist c standard carlini 3609
./run_extra.sh mnist c adversarial carlini 3609
./run_extra.sh mnist c relu carlini 3609
./run_extra.sh mnist a standard carlini 5973
./run_extra.sh mnist a adversarial carlini 5973
./run_extra.sh mnist a relu carlini 5973
./run_extra.sh mnist b standard carlini 5973
./run_extra.sh mnist b adversarial carlini 5973
./run_extra.sh mnist b relu carlini 5973
./run_extra.sh mnist c standard carlini 5973
./run_extra.sh mnist c adversarial carlini 5973
./run_extra.sh mnist c relu carlini 5973
./run_extra.sh mnist a standard carlini 1485
./run_extra.sh mnist a adversarial carlini 1485
./run_extra.sh mnist a relu carlini 1485
./run_extra.sh mnist b standard carlini 1485
./run_extra.sh mnist b adversarial carlini 1485
./run_extra.sh mnist b relu carlini 1485
./run_extra.sh mnist c standard carlini 1485
./run_extra.sh mnist c adversarial carlini 1485
./run_extra.sh mnist c relu carlini 1485
./run_extra.sh mnist a standard carlini 9360
./run_extra.sh mnist a adversarial carlini 9360
./run_extra.sh mnist a relu carlini 9360
./run_extra.sh mnist b standard carlini 9360
./run_extra.sh mnist b adversarial carlini 9360
./run_extra.sh mnist b relu carlini 9360
./run_extra.sh mnist c standard carlini 9360
./run_extra.sh mnist c adversarial carlini 9360
./run_extra.sh mnist c relu carlini 9360
./run_extra.sh mnist a standard carlini 3071
./run_extra.sh mnist a adversarial carlini 3071
./run_extra.sh mnist a relu carlini 3071
./run_extra.sh mnist b standard carlini 3071
./run_extra.sh mnist b adversarial carlini 3071
./run_extra.sh mnist b relu carlini 3071
./run_extra.sh mnist c standard carlini 3071
./run_extra.sh mnist c adversarial carlini 3071
./run_extra.sh mnist c relu carlini 3071
./run_extra.sh mnist a standard carlini 3963
./run_extra.sh mnist a adversarial carlini 3963
./run_extra.sh mnist a relu carlini 3963
./run_extra.sh mnist b standard carlini 3963
./run_extra.sh mnist b adversarial carlini 3963
./run_extra.sh mnist b relu carlini 3963
./run_extra.sh mnist c standard carlini 3963
./run_extra.sh mnist c adversarial carlini 3963
./run_extra.sh mnist c relu carlini 3963
./run_extra.sh mnist a standard carlini 564
./run_extra.sh mnist a adversarial carlini 564
./run_extra.sh mnist a relu carlini 564
./run_extra.sh mnist b standard carlini 564
./run_extra.sh mnist b adversarial carlini 564
./run_extra.sh mnist b relu carlini 564
./run_extra.sh mnist c standard carlini 564
./run_extra.sh mnist c adversarial carlini 564
./run_extra.sh mnist c relu carlini 564
./run_extra.sh mnist a standard carlini 1583
./run_extra.sh mnist a adversarial carlini 1583
./run_extra.sh mnist a relu carlini 1583
./run_extra.sh mnist b standard carlini 1583
./run_extra.sh mnist b adversarial carlini 1583
./run_extra.sh mnist b relu carlini 1583
./run_extra.sh mnist c standard carlini 1583
./run_extra.sh mnist c adversarial carlini 1583
./run_extra.sh mnist c relu carlini 1583
./run_extra.sh mnist a standard carlini 4172
./run_extra.sh mnist a adversarial carlini 4172
./run_extra.sh mnist a relu carlini 4172
./run_extra.sh mnist b standard carlini 4172
./run_extra.sh mnist b adversarial carlini 4172
./run_extra.sh mnist b relu carlini 4172
./run_extra.sh mnist c standard carlini 4172
./run_extra.sh mnist c adversarial carlini 4172
./run_extra.sh mnist c relu carlini 4172
./run_extra.sh mnist a standard carlini 4671
./run_extra.sh mnist a adversarial carlini 4671
./run_extra.sh mnist a relu carlini 4671
./run_extra.sh mnist b standard carlini 4671
./run_extra.sh mnist b adversarial carlini 4671
./run_extra.sh mnist b relu carlini 4671
./run_extra.sh mnist c standard carlini 4671
./run_extra.sh mnist c adversarial carlini 4671
./run_extra.sh mnist c relu carlini 4671
./run_extra.sh mnist a standard carlini 6882
./run_extra.sh mnist a adversarial carlini 6882
./run_extra.sh mnist a relu carlini 6882
./run_extra.sh mnist b standard carlini 6882
./run_extra.sh mnist b adversarial carlini 6882
./run_extra.sh mnist b relu carlini 6882
./run_extra.sh mnist c standard carlini 6882
./run_extra.sh mnist c adversarial carlini 6882
./run_extra.sh mnist c relu carlini 6882
./run_extra.sh mnist a standard carlini 8976
./run_extra.sh mnist a adversarial carlini 8976
./run_extra.sh mnist a relu carlini 8976
./run_extra.sh mnist b standard carlini 8976
./run_extra.sh mnist b adversarial carlini 8976
./run_extra.sh mnist b relu carlini 8976
./run_extra.sh mnist c standard carlini 8976
./run_extra.sh mnist c adversarial carlini 8976
./run_extra.sh mnist c relu carlini 8976
./run_extra.sh mnist a standard carlini 904
./run_extra.sh mnist a adversarial carlini 904
./run_extra.sh mnist a relu carlini 904
./run_extra.sh mnist b standard carlini 904
./run_extra.sh mnist b adversarial carlini 904
./run_extra.sh mnist b relu carlini 904
./run_extra.sh mnist c standard carlini 904
./run_extra.sh mnist c adversarial carlini 904
./run_extra.sh mnist c relu carlini 904
./run_extra.sh mnist a standard carlini 5093
./run_extra.sh mnist a adversarial carlini 5093
./run_extra.sh mnist a relu carlini 5093
./run_extra.sh mnist b standard carlini 5093
./run_extra.sh mnist b adversarial carlini 5093
./run_extra.sh mnist b relu carlini 5093
./run_extra.sh mnist c standard carlini 5093
./run_extra.sh mnist c adversarial carlini 5093
./run_extra.sh mnist c relu carlini 5093
./run_extra.sh mnist a standard carlini 7536
./run_extra.sh mnist a adversarial carlini 7536
./run_extra.sh mnist a relu carlini 7536
./run_extra.sh mnist b standard carlini 7536
./run_extra.sh mnist b adversarial carlini 7536
./run_extra.sh mnist b relu carlini 7536
./run_extra.sh mnist c standard carlini 7536
./run_extra.sh mnist c adversarial carlini 7536
./run_extra.sh mnist c relu carlini 7536
./run_extra.sh mnist a standard carlini 5691
./run_extra.sh mnist a adversarial carlini 5691
./run_extra.sh mnist a relu carlini 5691
./run_extra.sh mnist b standard carlini 5691
./run_extra.sh mnist b adversarial carlini 5691
./run_extra.sh mnist b relu carlini 5691
./run_extra.sh mnist c standard carlini 5691
./run_extra.sh mnist c adversarial carlini 5691
./run_extra.sh mnist c relu carlini 5691
./run_extra.sh mnist a standard carlini 9648
./run_extra.sh mnist a adversarial carlini 9648
./run_extra.sh mnist a relu carlini 9648
./run_extra.sh mnist b standard carlini 9648
./run_extra.sh mnist b adversarial carlini 9648
./run_extra.sh mnist b relu carlini 9648
./run_extra.sh mnist c standard carlini 9648
./run_extra.sh mnist c adversarial carlini 9648
./run_extra.sh mnist c relu carlini 9648
./run_extra.sh mnist a standard carlini 9963
./run_extra.sh mnist a adversarial carlini 9963
./run_extra.sh mnist a relu carlini 9963
./run_extra.sh mnist b standard carlini 9963
./run_extra.sh mnist b adversarial carlini 9963
./run_extra.sh mnist b relu carlini 9963
./run_extra.sh mnist c standard carlini 9963
./run_extra.sh mnist c adversarial carlini 9963
./run_extra.sh mnist c relu carlini 9963
./run_extra.sh mnist a standard carlini 4826
./run_extra.sh mnist a adversarial carlini 4826
./run_extra.sh mnist a relu carlini 4826
./run_extra.sh mnist b standard carlini 4826
./run_extra.sh mnist b adversarial carlini 4826
./run_extra.sh mnist b relu carlini 4826
./run_extra.sh mnist c standard carlini 4826
./run_extra.sh mnist c adversarial carlini 4826
./run_extra.sh mnist c relu carlini 4826
./run_extra.sh mnist a standard carlini 8753
./run_extra.sh mnist a adversarial carlini 8753
./run_extra.sh mnist a relu carlini 8753
./run_extra.sh mnist b standard carlini 8753
./run_extra.sh mnist b adversarial carlini 8753
./run_extra.sh mnist b relu carlini 8753
./run_extra.sh mnist c standard carlini 8753
./run_extra.sh mnist c adversarial carlini 8753
./run_extra.sh mnist c relu carlini 8753
./run_extra.sh mnist a standard carlini 6146
./run_extra.sh mnist a adversarial carlini 6146
./run_extra.sh mnist a relu carlini 6146
./run_extra.sh mnist b standard carlini 6146
./run_extra.sh mnist b adversarial carlini 6146
./run_extra.sh mnist b relu carlini 6146
./run_extra.sh mnist c standard carlini 6146
./run_extra.sh mnist c adversarial carlini 6146
./run_extra.sh mnist c relu carlini 6146
./run_extra.sh mnist a standard carlini 8580
./run_extra.sh mnist a adversarial carlini 8580
./run_extra.sh mnist a relu carlini 8580
./run_extra.sh mnist b standard carlini 8580
./run_extra.sh mnist b adversarial carlini 8580
./run_extra.sh mnist b relu carlini 8580
./run_extra.sh mnist c standard carlini 8580
./run_extra.sh mnist c adversarial carlini 8580
./run_extra.sh mnist c relu carlini 8580
./run_extra.sh mnist a standard carlini 2645
./run_extra.sh mnist a adversarial carlini 2645
./run_extra.sh mnist a relu carlini 2645
./run_extra.sh mnist b standard carlini 2645
./run_extra.sh mnist b adversarial carlini 2645
./run_extra.sh mnist b relu carlini 2645
./run_extra.sh mnist c standard carlini 2645
./run_extra.sh mnist c adversarial carlini 2645
./run_extra.sh mnist c relu carlini 2645
./run_extra.sh mnist a standard carlini 8814
./run_extra.sh mnist a adversarial carlini 8814
./run_extra.sh mnist a relu carlini 8814
./run_extra.sh mnist b standard carlini 8814
./run_extra.sh mnist b adversarial carlini 8814
./run_extra.sh mnist b relu carlini 8814
./run_extra.sh mnist c standard carlini 8814
./run_extra.sh mnist c adversarial carlini 8814
./run_extra.sh mnist c relu carlini 8814
./run_extra.sh mnist a standard carlini 3144
./run_extra.sh mnist a adversarial carlini 3144
./run_extra.sh mnist a relu carlini 3144
./run_extra.sh mnist b standard carlini 3144
./run_extra.sh mnist b adversarial carlini 3144
./run_extra.sh mnist b relu carlini 3144
./run_extra.sh mnist c standard carlini 3144
./run_extra.sh mnist c adversarial carlini 3144
./run_extra.sh mnist c relu carlini 3144
./run_extra.sh mnist a standard carlini 9227
./run_extra.sh mnist a adversarial carlini 9227
./run_extra.sh mnist a relu carlini 9227
./run_extra.sh mnist b standard carlini 9227
./run_extra.sh mnist b adversarial carlini 9227
./run_extra.sh mnist b relu carlini 9227
./run_extra.sh mnist c standard carlini 9227
./run_extra.sh mnist c adversarial carlini 9227
./run_extra.sh mnist c relu carlini 9227
./run_extra.sh mnist a standard carlini 3328
./run_extra.sh mnist a adversarial carlini 3328
./run_extra.sh mnist a relu carlini 3328
./run_extra.sh mnist b standard carlini 3328
./run_extra.sh mnist b adversarial carlini 3328
./run_extra.sh mnist b relu carlini 3328
./run_extra.sh mnist c standard carlini 3328
./run_extra.sh mnist c adversarial carlini 3328
./run_extra.sh mnist c relu carlini 3328
./run_extra.sh mnist a standard carlini 912
./run_extra.sh mnist a adversarial carlini 912
./run_extra.sh mnist a relu carlini 912
./run_extra.sh mnist b standard carlini 912
./run_extra.sh mnist b adversarial carlini 912
./run_extra.sh mnist b relu carlini 912
./run_extra.sh mnist c standard carlini 912
./run_extra.sh mnist c adversarial carlini 912
./run_extra.sh mnist c relu carlini 912
./run_extra.sh mnist a standard carlini 9647
./run_extra.sh mnist a adversarial carlini 9647
./run_extra.sh mnist a relu carlini 9647
./run_extra.sh mnist b standard carlini 9647
./run_extra.sh mnist b adversarial carlini 9647
./run_extra.sh mnist b relu carlini 9647
./run_extra.sh mnist c standard carlini 9647
./run_extra.sh mnist c adversarial carlini 9647
./run_extra.sh mnist c relu carlini 9647
./run_extra.sh mnist a standard carlini 9017
./run_extra.sh mnist a adversarial carlini 9017
./run_extra.sh mnist a relu carlini 9017
./run_extra.sh mnist b standard carlini 9017
./run_extra.sh mnist b adversarial carlini 9017
./run_extra.sh mnist b relu carlini 9017
./run_extra.sh mnist c standard carlini 9017
./run_extra.sh mnist c adversarial carlini 9017
./run_extra.sh mnist c relu carlini 9017
./run_extra.sh mnist a standard carlini 5704
./run_extra.sh mnist a adversarial carlini 5704
./run_extra.sh mnist a relu carlini 5704
./run_extra.sh mnist b standard carlini 5704
./run_extra.sh mnist b adversarial carlini 5704
./run_extra.sh mnist b relu carlini 5704
./run_extra.sh mnist c standard carlini 5704
./run_extra.sh mnist c adversarial carlini 5704
./run_extra.sh mnist c relu carlini 5704
./run_extra.sh mnist a standard carlini 5694
./run_extra.sh mnist a adversarial carlini 5694
./run_extra.sh mnist a relu carlini 5694
./run_extra.sh mnist b standard carlini 5694
./run_extra.sh mnist b adversarial carlini 5694
./run_extra.sh mnist b relu carlini 5694
./run_extra.sh mnist c standard carlini 5694
./run_extra.sh mnist c adversarial carlini 5694
./run_extra.sh mnist c relu carlini 5694
./run_extra.sh mnist a standard carlini 5760
./run_extra.sh mnist a adversarial carlini 5760
./run_extra.sh mnist a relu carlini 5760
./run_extra.sh mnist b standard carlini 5760
./run_extra.sh mnist b adversarial carlini 5760
./run_extra.sh mnist b relu carlini 5760
./run_extra.sh mnist c standard carlini 5760
./run_extra.sh mnist c adversarial carlini 5760
./run_extra.sh mnist c relu carlini 5760
./run_extra.sh mnist a standard carlini 9675
./run_extra.sh mnist a adversarial carlini 9675
./run_extra.sh mnist a relu carlini 9675
./run_extra.sh mnist b standard carlini 9675
./run_extra.sh mnist b adversarial carlini 9675
./run_extra.sh mnist b relu carlini 9675
./run_extra.sh mnist c standard carlini 9675
./run_extra.sh mnist c adversarial carlini 9675
./run_extra.sh mnist c relu carlini 9675
./run_extra.sh mnist a standard carlini 4533
./run_extra.sh mnist a adversarial carlini 4533
./run_extra.sh mnist a relu carlini 4533
./run_extra.sh mnist b standard carlini 4533
./run_extra.sh mnist b adversarial carlini 4533
./run_extra.sh mnist b relu carlini 4533
./run_extra.sh mnist c standard carlini 4533
./run_extra.sh mnist c adversarial carlini 4533
./run_extra.sh mnist c relu carlini 4533
./run_extra.sh mnist a standard carlini 8368
./run_extra.sh mnist a adversarial carlini 8368
./run_extra.sh mnist a relu carlini 8368
./run_extra.sh mnist b standard carlini 8368
./run_extra.sh mnist b adversarial carlini 8368
./run_extra.sh mnist b relu carlini 8368
./run_extra.sh mnist c standard carlini 8368
./run_extra.sh mnist c adversarial carlini 8368
./run_extra.sh mnist c relu carlini 8368
./run_extra.sh mnist a standard carlini 3688
./run_extra.sh mnist a adversarial carlini 3688
./run_extra.sh mnist a relu carlini 3688
./run_extra.sh mnist b standard carlini 3688
./run_extra.sh mnist b adversarial carlini 3688
./run_extra.sh mnist b relu carlini 3688
./run_extra.sh mnist c standard carlini 3688
./run_extra.sh mnist c adversarial carlini 3688
./run_extra.sh mnist c relu carlini 3688
./run_extra.sh mnist a standard carlini 3725
./run_extra.sh mnist a adversarial carlini 3725
./run_extra.sh mnist a relu carlini 3725
./run_extra.sh mnist b standard carlini 3725
./run_extra.sh mnist b adversarial carlini 3725
./run_extra.sh mnist b relu carlini 3725
./run_extra.sh mnist c standard carlini 3725
./run_extra.sh mnist c adversarial carlini 3725
./run_extra.sh mnist c relu carlini 3725
./run_extra.sh mnist a standard carlini 9277
./run_extra.sh mnist a adversarial carlini 9277
./run_extra.sh mnist a relu carlini 9277
./run_extra.sh mnist b standard carlini 9277
./run_extra.sh mnist b adversarial carlini 9277
./run_extra.sh mnist b relu carlini 9277
./run_extra.sh mnist c standard carlini 9277
./run_extra.sh mnist c adversarial carlini 9277
./run_extra.sh mnist c relu carlini 9277
./run_extra.sh mnist a standard carlini 7885
./run_extra.sh mnist a adversarial carlini 7885
./run_extra.sh mnist a relu carlini 7885
./run_extra.sh mnist b standard carlini 7885
./run_extra.sh mnist b adversarial carlini 7885
./run_extra.sh mnist b relu carlini 7885
./run_extra.sh mnist c standard carlini 7885
./run_extra.sh mnist c adversarial carlini 7885
./run_extra.sh mnist c relu carlini 7885
./run_extra.sh mnist a standard carlini 5156
./run_extra.sh mnist a adversarial carlini 5156
./run_extra.sh mnist a relu carlini 5156
./run_extra.sh mnist b standard carlini 5156
./run_extra.sh mnist b adversarial carlini 5156
./run_extra.sh mnist b relu carlini 5156
./run_extra.sh mnist c standard carlini 5156
./run_extra.sh mnist c adversarial carlini 5156
./run_extra.sh mnist c relu carlini 5156
./run_extra.sh mnist a standard carlini 3494
./run_extra.sh mnist a adversarial carlini 3494
./run_extra.sh mnist a relu carlini 3494
./run_extra.sh mnist b standard carlini 3494
./run_extra.sh mnist b adversarial carlini 3494
./run_extra.sh mnist b relu carlini 3494
./run_extra.sh mnist c standard carlini 3494
./run_extra.sh mnist c adversarial carlini 3494
./run_extra.sh mnist c relu carlini 3494
./run_extra.sh mnist a standard carlini 4823
./run_extra.sh mnist a adversarial carlini 4823
./run_extra.sh mnist a relu carlini 4823
./run_extra.sh mnist b standard carlini 4823
./run_extra.sh mnist b adversarial carlini 4823
./run_extra.sh mnist b relu carlini 4823
./run_extra.sh mnist c standard carlini 4823
./run_extra.sh mnist c adversarial carlini 4823
./run_extra.sh mnist c relu carlini 4823
./run_extra.sh mnist a standard carlini 484
./run_extra.sh mnist a adversarial carlini 484
./run_extra.sh mnist a relu carlini 484
./run_extra.sh mnist b standard carlini 484
./run_extra.sh mnist b adversarial carlini 484
./run_extra.sh mnist b relu carlini 484
./run_extra.sh mnist c standard carlini 484
./run_extra.sh mnist c adversarial carlini 484
./run_extra.sh mnist c relu carlini 484
./run_extra.sh mnist a standard carlini 3684
./run_extra.sh mnist a adversarial carlini 3684
./run_extra.sh mnist a relu carlini 3684
./run_extra.sh mnist b standard carlini 3684
./run_extra.sh mnist b adversarial carlini 3684
./run_extra.sh mnist b relu carlini 3684
./run_extra.sh mnist c standard carlini 3684
./run_extra.sh mnist c adversarial carlini 3684
./run_extra.sh mnist c relu carlini 3684
./run_extra.sh mnist a standard carlini 1777
./run_extra.sh mnist a adversarial carlini 1777
./run_extra.sh mnist a relu carlini 1777
./run_extra.sh mnist b standard carlini 1777
./run_extra.sh mnist b adversarial carlini 1777
./run_extra.sh mnist b relu carlini 1777
./run_extra.sh mnist c standard carlini 1777
./run_extra.sh mnist c adversarial carlini 1777
./run_extra.sh mnist c relu carlini 1777
./run_extra.sh mnist a standard carlini 5888
./run_extra.sh mnist a adversarial carlini 5888
./run_extra.sh mnist a relu carlini 5888
./run_extra.sh mnist b standard carlini 5888
./run_extra.sh mnist b adversarial carlini 5888
./run_extra.sh mnist b relu carlini 5888
./run_extra.sh mnist c standard carlini 5888
./run_extra.sh mnist c adversarial carlini 5888
./run_extra.sh mnist c relu carlini 5888
./run_extra.sh mnist a standard carlini 7872
./run_extra.sh mnist a adversarial carlini 7872
./run_extra.sh mnist a relu carlini 7872
./run_extra.sh mnist b standard carlini 7872
./run_extra.sh mnist b adversarial carlini 7872
./run_extra.sh mnist b relu carlini 7872
./run_extra.sh mnist c standard carlini 7872
./run_extra.sh mnist c adversarial carlini 7872
./run_extra.sh mnist c relu carlini 7872
./run_extra.sh mnist a standard carlini 4076
./run_extra.sh mnist a adversarial carlini 4076
./run_extra.sh mnist a relu carlini 4076
./run_extra.sh mnist b standard carlini 4076
./run_extra.sh mnist b adversarial carlini 4076
./run_extra.sh mnist b relu carlini 4076
./run_extra.sh mnist c standard carlini 4076
./run_extra.sh mnist c adversarial carlini 4076
./run_extra.sh mnist c relu carlini 4076
./run_extra.sh mnist a standard carlini 4831
./run_extra.sh mnist a adversarial carlini 4831
./run_extra.sh mnist a relu carlini 4831
./run_extra.sh mnist b standard carlini 4831
./run_extra.sh mnist b adversarial carlini 4831
./run_extra.sh mnist b relu carlini 4831
./run_extra.sh mnist c standard carlini 4831
./run_extra.sh mnist c adversarial carlini 4831
./run_extra.sh mnist c relu carlini 4831
./run_extra.sh mnist a standard carlini 9189
./run_extra.sh mnist a adversarial carlini 9189
./run_extra.sh mnist a relu carlini 9189
./run_extra.sh mnist b standard carlini 9189
./run_extra.sh mnist b adversarial carlini 9189
./run_extra.sh mnist b relu carlini 9189
./run_extra.sh mnist c standard carlini 9189
./run_extra.sh mnist c adversarial carlini 9189
./run_extra.sh mnist c relu carlini 9189
./run_extra.sh mnist a standard carlini 5415
./run_extra.sh mnist a adversarial carlini 5415
./run_extra.sh mnist a relu carlini 5415
./run_extra.sh mnist b standard carlini 5415
./run_extra.sh mnist b adversarial carlini 5415
./run_extra.sh mnist b relu carlini 5415
./run_extra.sh mnist c standard carlini 5415
./run_extra.sh mnist c adversarial carlini 5415
./run_extra.sh mnist c relu carlini 5415
./run_extra.sh mnist a standard carlini 7869
./run_extra.sh mnist a adversarial carlini 7869
./run_extra.sh mnist a relu carlini 7869
./run_extra.sh mnist b standard carlini 7869
./run_extra.sh mnist b adversarial carlini 7869
./run_extra.sh mnist b relu carlini 7869
./run_extra.sh mnist c standard carlini 7869
./run_extra.sh mnist c adversarial carlini 7869
./run_extra.sh mnist c relu carlini 7869
./run_extra.sh mnist a standard carlini 3255
./run_extra.sh mnist a adversarial carlini 3255
./run_extra.sh mnist a relu carlini 3255
./run_extra.sh mnist b standard carlini 3255
./run_extra.sh mnist b adversarial carlini 3255
./run_extra.sh mnist b relu carlini 3255
./run_extra.sh mnist c standard carlini 3255
./run_extra.sh mnist c adversarial carlini 3255
./run_extra.sh mnist c relu carlini 3255
./run_extra.sh mnist a standard carlini 9838
./run_extra.sh mnist a adversarial carlini 9838
./run_extra.sh mnist a relu carlini 9838
./run_extra.sh mnist b standard carlini 9838
./run_extra.sh mnist b adversarial carlini 9838
./run_extra.sh mnist b relu carlini 9838
./run_extra.sh mnist c standard carlini 9838
./run_extra.sh mnist c adversarial carlini 9838
./run_extra.sh mnist c relu carlini 9838
./run_extra.sh mnist a standard carlini 3687
./run_extra.sh mnist a adversarial carlini 3687
./run_extra.sh mnist a relu carlini 3687
./run_extra.sh mnist b standard carlini 3687
./run_extra.sh mnist b adversarial carlini 3687
./run_extra.sh mnist b relu carlini 3687
./run_extra.sh mnist c standard carlini 3687
./run_extra.sh mnist c adversarial carlini 3687
./run_extra.sh mnist c relu carlini 3687
./run_extra.sh mnist a standard carlini 9401
./run_extra.sh mnist a adversarial carlini 9401
./run_extra.sh mnist a relu carlini 9401
./run_extra.sh mnist b standard carlini 9401
./run_extra.sh mnist b adversarial carlini 9401
./run_extra.sh mnist b relu carlini 9401
./run_extra.sh mnist c standard carlini 9401
./run_extra.sh mnist c adversarial carlini 9401
./run_extra.sh mnist c relu carlini 9401
./run_extra.sh mnist a standard carlini 9158
./run_extra.sh mnist a adversarial carlini 9158
./run_extra.sh mnist a relu carlini 9158
./run_extra.sh mnist b standard carlini 9158
./run_extra.sh mnist b adversarial carlini 9158
./run_extra.sh mnist b relu carlini 9158
./run_extra.sh mnist c standard carlini 9158
./run_extra.sh mnist c adversarial carlini 9158
./run_extra.sh mnist c relu carlini 9158
./run_extra.sh mnist a standard carlini 7035
./run_extra.sh mnist a adversarial carlini 7035
./run_extra.sh mnist a relu carlini 7035
./run_extra.sh mnist b standard carlini 7035
./run_extra.sh mnist b adversarial carlini 7035
./run_extra.sh mnist b relu carlini 7035
./run_extra.sh mnist c standard carlini 7035
./run_extra.sh mnist c adversarial carlini 7035
./run_extra.sh mnist c relu carlini 7035
./run_extra.sh mnist a standard carlini 979
./run_extra.sh mnist a adversarial carlini 979
./run_extra.sh mnist a relu carlini 979
./run_extra.sh mnist b standard carlini 979
./run_extra.sh mnist b adversarial carlini 979
./run_extra.sh mnist b relu carlini 979
./run_extra.sh mnist c standard carlini 979
./run_extra.sh mnist c adversarial carlini 979
./run_extra.sh mnist c relu carlini 979
./run_extra.sh mnist a standard carlini 9448
./run_extra.sh mnist a adversarial carlini 9448
./run_extra.sh mnist a relu carlini 9448
./run_extra.sh mnist b standard carlini 9448
./run_extra.sh mnist b adversarial carlini 9448
./run_extra.sh mnist b relu carlini 9448
./run_extra.sh mnist c standard carlini 9448
./run_extra.sh mnist c adversarial carlini 9448
./run_extra.sh mnist c relu carlini 9448
./run_extra.sh mnist a standard carlini 7121
./run_extra.sh mnist a adversarial carlini 7121
./run_extra.sh mnist a relu carlini 7121
./run_extra.sh mnist b standard carlini 7121
./run_extra.sh mnist b adversarial carlini 7121
./run_extra.sh mnist b relu carlini 7121
./run_extra.sh mnist c standard carlini 7121
./run_extra.sh mnist c adversarial carlini 7121
./run_extra.sh mnist c relu carlini 7121
./run_extra.sh mnist a standard carlini 9046
./run_extra.sh mnist a adversarial carlini 9046
./run_extra.sh mnist a relu carlini 9046
./run_extra.sh mnist b standard carlini 9046
./run_extra.sh mnist b adversarial carlini 9046
./run_extra.sh mnist b relu carlini 9046
./run_extra.sh mnist c standard carlini 9046
./run_extra.sh mnist c adversarial carlini 9046
./run_extra.sh mnist c relu carlini 9046
./run_extra.sh mnist a standard carlini 1321
./run_extra.sh mnist a adversarial carlini 1321
./run_extra.sh mnist a relu carlini 1321
./run_extra.sh mnist b standard carlini 1321
./run_extra.sh mnist b adversarial carlini 1321
./run_extra.sh mnist b relu carlini 1321
./run_extra.sh mnist c standard carlini 1321
./run_extra.sh mnist c adversarial carlini 1321
./run_extra.sh mnist c relu carlini 1321
./run_extra.sh mnist a standard carlini 5682
./run_extra.sh mnist a adversarial carlini 5682
./run_extra.sh mnist a relu carlini 5682
./run_extra.sh mnist b standard carlini 5682
./run_extra.sh mnist b adversarial carlini 5682
./run_extra.sh mnist b relu carlini 5682
./run_extra.sh mnist c standard carlini 5682
./run_extra.sh mnist c adversarial carlini 5682
./run_extra.sh mnist c relu carlini 5682
./run_extra.sh mnist a standard carlini 3218
./run_extra.sh mnist a adversarial carlini 3218
./run_extra.sh mnist a relu carlini 3218
./run_extra.sh mnist b standard carlini 3218
./run_extra.sh mnist b adversarial carlini 3218
./run_extra.sh mnist b relu carlini 3218
./run_extra.sh mnist c standard carlini 3218
./run_extra.sh mnist c adversarial carlini 3218
./run_extra.sh mnist c relu carlini 3218
./run_extra.sh mnist a standard carlini 641
./run_extra.sh mnist a adversarial carlini 641
./run_extra.sh mnist a relu carlini 641
./run_extra.sh mnist b standard carlini 641
./run_extra.sh mnist b adversarial carlini 641
./run_extra.sh mnist b relu carlini 641
./run_extra.sh mnist c standard carlini 641
./run_extra.sh mnist c adversarial carlini 641
./run_extra.sh mnist c relu carlini 641
./run_extra.sh mnist a standard carlini 6550
./run_extra.sh mnist a adversarial carlini 6550
./run_extra.sh mnist a relu carlini 6550
./run_extra.sh mnist b standard carlini 6550
./run_extra.sh mnist b adversarial carlini 6550
./run_extra.sh mnist b relu carlini 6550
./run_extra.sh mnist c standard carlini 6550
./run_extra.sh mnist c adversarial carlini 6550
./run_extra.sh mnist c relu carlini 6550
./run_extra.sh mnist a standard carlini 6245
./run_extra.sh mnist a adversarial carlini 6245
./run_extra.sh mnist a relu carlini 6245
./run_extra.sh mnist b standard carlini 6245
./run_extra.sh mnist b adversarial carlini 6245
./run_extra.sh mnist b relu carlini 6245
./run_extra.sh mnist c standard carlini 6245
./run_extra.sh mnist c adversarial carlini 6245
./run_extra.sh mnist c relu carlini 6245
./run_extra.sh mnist a standard carlini 797
./run_extra.sh mnist a adversarial carlini 797
./run_extra.sh mnist a relu carlini 797
./run_extra.sh mnist b standard carlini 797
./run_extra.sh mnist b adversarial carlini 797
./run_extra.sh mnist b relu carlini 797
./run_extra.sh mnist c standard carlini 797
./run_extra.sh mnist c adversarial carlini 797
./run_extra.sh mnist c relu carlini 797
./run_extra.sh mnist a standard carlini 6654
./run_extra.sh mnist a adversarial carlini 6654
./run_extra.sh mnist a relu carlini 6654
./run_extra.sh mnist b standard carlini 6654
./run_extra.sh mnist b adversarial carlini 6654
./run_extra.sh mnist b relu carlini 6654
./run_extra.sh mnist c standard carlini 6654
./run_extra.sh mnist c adversarial carlini 6654
./run_extra.sh mnist c relu carlini 6654
./run_extra.sh mnist a standard carlini 3734
./run_extra.sh mnist a adversarial carlini 3734
./run_extra.sh mnist a relu carlini 3734
./run_extra.sh mnist b standard carlini 3734
./run_extra.sh mnist b adversarial carlini 3734
./run_extra.sh mnist b relu carlini 3734
./run_extra.sh mnist c standard carlini 3734
./run_extra.sh mnist c adversarial carlini 3734
./run_extra.sh mnist c relu carlini 3734
./run_extra.sh mnist a standard carlini 8302
./run_extra.sh mnist a adversarial carlini 8302
./run_extra.sh mnist a relu carlini 8302
./run_extra.sh mnist b standard carlini 8302
./run_extra.sh mnist b adversarial carlini 8302
./run_extra.sh mnist b relu carlini 8302
./run_extra.sh mnist c standard carlini 8302
./run_extra.sh mnist c adversarial carlini 8302
./run_extra.sh mnist c relu carlini 8302
./run_extra.sh mnist a standard carlini 5954
./run_extra.sh mnist a adversarial carlini 5954
./run_extra.sh mnist a relu carlini 5954
./run_extra.sh mnist b standard carlini 5954
./run_extra.sh mnist b adversarial carlini 5954
./run_extra.sh mnist b relu carlini 5954
./run_extra.sh mnist c standard carlini 5954
./run_extra.sh mnist c adversarial carlini 5954
./run_extra.sh mnist c relu carlini 5954
./run_extra.sh mnist a standard carlini 1018
./run_extra.sh mnist a adversarial carlini 1018
./run_extra.sh mnist a relu carlini 1018
./run_extra.sh mnist b standard carlini 1018
./run_extra.sh mnist b adversarial carlini 1018
./run_extra.sh mnist b relu carlini 1018
./run_extra.sh mnist c standard carlini 1018
./run_extra.sh mnist c adversarial carlini 1018
./run_extra.sh mnist c relu carlini 1018
./run_extra.sh mnist a standard carlini 6901
./run_extra.sh mnist a adversarial carlini 6901
./run_extra.sh mnist a relu carlini 6901
./run_extra.sh mnist b standard carlini 6901
./run_extra.sh mnist b adversarial carlini 6901
./run_extra.sh mnist b relu carlini 6901
./run_extra.sh mnist c standard carlini 6901
./run_extra.sh mnist c adversarial carlini 6901
./run_extra.sh mnist c relu carlini 6901
./run_extra.sh mnist a standard carlini 9145
./run_extra.sh mnist a adversarial carlini 9145
./run_extra.sh mnist a relu carlini 9145
./run_extra.sh mnist b standard carlini 9145
./run_extra.sh mnist b adversarial carlini 9145
./run_extra.sh mnist b relu carlini 9145
./run_extra.sh mnist c standard carlini 9145
./run_extra.sh mnist c adversarial carlini 9145
./run_extra.sh mnist c relu carlini 9145
./run_extra.sh mnist a standard carlini 1171
./run_extra.sh mnist a adversarial carlini 1171
./run_extra.sh mnist a relu carlini 1171
./run_extra.sh mnist b standard carlini 1171
./run_extra.sh mnist b adversarial carlini 1171
./run_extra.sh mnist b relu carlini 1171
./run_extra.sh mnist c standard carlini 1171
./run_extra.sh mnist c adversarial carlini 1171
./run_extra.sh mnist c relu carlini 1171
./run_extra.sh mnist a standard carlini 4710
./run_extra.sh mnist a adversarial carlini 4710
./run_extra.sh mnist a relu carlini 4710
./run_extra.sh mnist b standard carlini 4710
./run_extra.sh mnist b adversarial carlini 4710
./run_extra.sh mnist b relu carlini 4710
./run_extra.sh mnist c standard carlini 4710
./run_extra.sh mnist c adversarial carlini 4710
./run_extra.sh mnist c relu carlini 4710
./run_extra.sh mnist a standard carlini 9247
./run_extra.sh mnist a adversarial carlini 9247
./run_extra.sh mnist a relu carlini 9247
./run_extra.sh mnist b standard carlini 9247
./run_extra.sh mnist b adversarial carlini 9247
./run_extra.sh mnist b relu carlini 9247
./run_extra.sh mnist c standard carlini 9247
./run_extra.sh mnist c adversarial carlini 9247
./run_extra.sh mnist c relu carlini 9247
./run_extra.sh mnist a standard carlini 5955
./run_extra.sh mnist a adversarial carlini 5955
./run_extra.sh mnist a relu carlini 5955
./run_extra.sh mnist b standard carlini 5955
./run_extra.sh mnist b adversarial carlini 5955
./run_extra.sh mnist b relu carlini 5955
./run_extra.sh mnist c standard carlini 5955
./run_extra.sh mnist c adversarial carlini 5955
./run_extra.sh mnist c relu carlini 5955
./run_extra.sh mnist a standard carlini 6760
./run_extra.sh mnist a adversarial carlini 6760
./run_extra.sh mnist a relu carlini 6760
./run_extra.sh mnist b standard carlini 6760
./run_extra.sh mnist b adversarial carlini 6760
./run_extra.sh mnist b relu carlini 6760
./run_extra.sh mnist c standard carlini 6760
./run_extra.sh mnist c adversarial carlini 6760
./run_extra.sh mnist c relu carlini 6760
./run_extra.sh mnist a standard carlini 9002
./run_extra.sh mnist a adversarial carlini 9002
./run_extra.sh mnist a relu carlini 9002
./run_extra.sh mnist b standard carlini 9002
./run_extra.sh mnist b adversarial carlini 9002
./run_extra.sh mnist b relu carlini 9002
./run_extra.sh mnist c standard carlini 9002
./run_extra.sh mnist c adversarial carlini 9002
./run_extra.sh mnist c relu carlini 9002
./run_extra.sh mnist a standard carlini 9690
./run_extra.sh mnist a adversarial carlini 9690
./run_extra.sh mnist a relu carlini 9690
./run_extra.sh mnist b standard carlini 9690
./run_extra.sh mnist b adversarial carlini 9690
./run_extra.sh mnist b relu carlini 9690
./run_extra.sh mnist c standard carlini 9690
./run_extra.sh mnist c adversarial carlini 9690
./run_extra.sh mnist c relu carlini 9690
./run_extra.sh mnist a standard carlini 6900
./run_extra.sh mnist a adversarial carlini 6900
./run_extra.sh mnist a relu carlini 6900
./run_extra.sh mnist b standard carlini 6900
./run_extra.sh mnist b adversarial carlini 6900
./run_extra.sh mnist b relu carlini 6900
./run_extra.sh mnist c standard carlini 6900
./run_extra.sh mnist c adversarial carlini 6900
./run_extra.sh mnist c relu carlini 6900
./run_extra.sh mnist a standard carlini 4196
./run_extra.sh mnist a adversarial carlini 4196
./run_extra.sh mnist a relu carlini 4196
./run_extra.sh mnist b standard carlini 4196
./run_extra.sh mnist b adversarial carlini 4196
./run_extra.sh mnist b relu carlini 4196
./run_extra.sh mnist c standard carlini 4196
./run_extra.sh mnist c adversarial carlini 4196
./run_extra.sh mnist c relu carlini 4196
./run_extra.sh mnist a standard carlini 2788
./run_extra.sh mnist a adversarial carlini 2788
./run_extra.sh mnist a relu carlini 2788
./run_extra.sh mnist b standard carlini 2788
./run_extra.sh mnist b adversarial carlini 2788
./run_extra.sh mnist b relu carlini 2788
./run_extra.sh mnist c standard carlini 2788
./run_extra.sh mnist c adversarial carlini 2788
./run_extra.sh mnist c relu carlini 2788
./run_extra.sh mnist a standard carlini 8717
./run_extra.sh mnist a adversarial carlini 8717
./run_extra.sh mnist a relu carlini 8717
./run_extra.sh mnist b standard carlini 8717
./run_extra.sh mnist b adversarial carlini 8717
./run_extra.sh mnist b relu carlini 8717
./run_extra.sh mnist c standard carlini 8717
./run_extra.sh mnist c adversarial carlini 8717
./run_extra.sh mnist c relu carlini 8717
./run_extra.sh mnist a standard carlini 315
./run_extra.sh mnist a adversarial carlini 315
./run_extra.sh mnist a relu carlini 315
./run_extra.sh mnist b standard carlini 315
./run_extra.sh mnist b adversarial carlini 315
./run_extra.sh mnist b relu carlini 315
./run_extra.sh mnist c standard carlini 315
./run_extra.sh mnist c adversarial carlini 315
./run_extra.sh mnist c relu carlini 315
./run_extra.sh mnist a standard carlini 5840
./run_extra.sh mnist a adversarial carlini 5840
./run_extra.sh mnist a relu carlini 5840
./run_extra.sh mnist b standard carlini 5840
./run_extra.sh mnist b adversarial carlini 5840
./run_extra.sh mnist b relu carlini 5840
./run_extra.sh mnist c standard carlini 5840
./run_extra.sh mnist c adversarial carlini 5840
./run_extra.sh mnist c relu carlini 5840
./run_extra.sh mnist a standard carlini 2918
./run_extra.sh mnist a adversarial carlini 2918
./run_extra.sh mnist a relu carlini 2918
./run_extra.sh mnist b standard carlini 2918
./run_extra.sh mnist b adversarial carlini 2918
./run_extra.sh mnist b relu carlini 2918
./run_extra.sh mnist c standard carlini 2918
./run_extra.sh mnist c adversarial carlini 2918
./run_extra.sh mnist c relu carlini 2918
./run_extra.sh mnist a standard carlini 6560
./run_extra.sh mnist a adversarial carlini 6560
./run_extra.sh mnist a relu carlini 6560
./run_extra.sh mnist b standard carlini 6560
./run_extra.sh mnist b adversarial carlini 6560
./run_extra.sh mnist b relu carlini 6560
./run_extra.sh mnist c standard carlini 6560
./run_extra.sh mnist c adversarial carlini 6560
./run_extra.sh mnist c relu carlini 6560
./run_extra.sh mnist a standard carlini 8910
./run_extra.sh mnist a adversarial carlini 8910
./run_extra.sh mnist a relu carlini 8910
./run_extra.sh mnist b standard carlini 8910
./run_extra.sh mnist b adversarial carlini 8910
./run_extra.sh mnist b relu carlini 8910
./run_extra.sh mnist c standard carlini 8910
./run_extra.sh mnist c adversarial carlini 8910
./run_extra.sh mnist c relu carlini 8910
./run_extra.sh mnist a standard carlini 2001
./run_extra.sh mnist a adversarial carlini 2001
./run_extra.sh mnist a relu carlini 2001
./run_extra.sh mnist b standard carlini 2001
./run_extra.sh mnist b adversarial carlini 2001
./run_extra.sh mnist b relu carlini 2001
./run_extra.sh mnist c standard carlini 2001
./run_extra.sh mnist c adversarial carlini 2001
./run_extra.sh mnist c relu carlini 2001
./run_extra.sh mnist a standard carlini 3694
./run_extra.sh mnist a adversarial carlini 3694
./run_extra.sh mnist a relu carlini 3694
./run_extra.sh mnist b standard carlini 3694
./run_extra.sh mnist b adversarial carlini 3694
./run_extra.sh mnist b relu carlini 3694
./run_extra.sh mnist c standard carlini 3694
./run_extra.sh mnist c adversarial carlini 3694
./run_extra.sh mnist c relu carlini 3694
./run_extra.sh mnist a standard carlini 1137
./run_extra.sh mnist a adversarial carlini 1137
./run_extra.sh mnist a relu carlini 1137
./run_extra.sh mnist b standard carlini 1137
./run_extra.sh mnist b adversarial carlini 1137
./run_extra.sh mnist b relu carlini 1137
./run_extra.sh mnist c standard carlini 1137
./run_extra.sh mnist c adversarial carlini 1137
./run_extra.sh mnist c relu carlini 1137
./run_extra.sh mnist a standard carlini 9728
./run_extra.sh mnist a adversarial carlini 9728
./run_extra.sh mnist a relu carlini 9728
./run_extra.sh mnist b standard carlini 9728
./run_extra.sh mnist b adversarial carlini 9728
./run_extra.sh mnist b relu carlini 9728
./run_extra.sh mnist c standard carlini 9728
./run_extra.sh mnist c adversarial carlini 9728
./run_extra.sh mnist c relu carlini 9728
./run_extra.sh mnist a standard carlini 5120
./run_extra.sh mnist a adversarial carlini 5120
./run_extra.sh mnist a relu carlini 5120
./run_extra.sh mnist b standard carlini 5120
./run_extra.sh mnist b adversarial carlini 5120
./run_extra.sh mnist b relu carlini 5120
./run_extra.sh mnist c standard carlini 5120
./run_extra.sh mnist c adversarial carlini 5120
./run_extra.sh mnist c relu carlini 5120
./run_extra.sh mnist a standard carlini 3843
./run_extra.sh mnist a adversarial carlini 3843
./run_extra.sh mnist a relu carlini 3843
./run_extra.sh mnist b standard carlini 3843
./run_extra.sh mnist b adversarial carlini 3843
./run_extra.sh mnist b relu carlini 3843
./run_extra.sh mnist c standard carlini 3843
./run_extra.sh mnist c adversarial carlini 3843
./run_extra.sh mnist c relu carlini 3843
./run_extra.sh mnist a standard carlini 562
./run_extra.sh mnist a adversarial carlini 562
./run_extra.sh mnist a relu carlini 562
./run_extra.sh mnist b standard carlini 562
./run_extra.sh mnist b adversarial carlini 562
./run_extra.sh mnist b relu carlini 562
./run_extra.sh mnist c standard carlini 562
./run_extra.sh mnist c adversarial carlini 562
./run_extra.sh mnist c relu carlini 562
./run_extra.sh mnist a standard carlini 9544
./run_extra.sh mnist a adversarial carlini 9544
./run_extra.sh mnist a relu carlini 9544
./run_extra.sh mnist b standard carlini 9544
./run_extra.sh mnist b adversarial carlini 9544
./run_extra.sh mnist b relu carlini 9544
./run_extra.sh mnist c standard carlini 9544
./run_extra.sh mnist c adversarial carlini 9544
./run_extra.sh mnist c relu carlini 9544
./run_extra.sh mnist a standard carlini 6287
./run_extra.sh mnist a adversarial carlini 6287
./run_extra.sh mnist a relu carlini 6287
./run_extra.sh mnist b standard carlini 6287
./run_extra.sh mnist b adversarial carlini 6287
./run_extra.sh mnist b relu carlini 6287
./run_extra.sh mnist c standard carlini 6287
./run_extra.sh mnist c adversarial carlini 6287
./run_extra.sh mnist c relu carlini 6287
./run_extra.sh mnist a standard carlini 5588
./run_extra.sh mnist a adversarial carlini 5588
./run_extra.sh mnist a relu carlini 5588
./run_extra.sh mnist b standard carlini 5588
./run_extra.sh mnist b adversarial carlini 5588
./run_extra.sh mnist b relu carlini 5588
./run_extra.sh mnist c standard carlini 5588
./run_extra.sh mnist c adversarial carlini 5588
./run_extra.sh mnist c relu carlini 5588
./run_extra.sh mnist a standard carlini 4313
./run_extra.sh mnist a adversarial carlini 4313
./run_extra.sh mnist a relu carlini 4313
./run_extra.sh mnist b standard carlini 4313
./run_extra.sh mnist b adversarial carlini 4313
./run_extra.sh mnist b relu carlini 4313
./run_extra.sh mnist c standard carlini 4313
./run_extra.sh mnist c adversarial carlini 4313
./run_extra.sh mnist c relu carlini 4313
./run_extra.sh mnist a standard carlini 7551
./run_extra.sh mnist a adversarial carlini 7551
./run_extra.sh mnist a relu carlini 7551
./run_extra.sh mnist b standard carlini 7551
./run_extra.sh mnist b adversarial carlini 7551
./run_extra.sh mnist b relu carlini 7551
./run_extra.sh mnist c standard carlini 7551
./run_extra.sh mnist c adversarial carlini 7551
./run_extra.sh mnist c relu carlini 7551
./run_extra.sh mnist a standard carlini 4271
./run_extra.sh mnist a adversarial carlini 4271
./run_extra.sh mnist a relu carlini 4271
./run_extra.sh mnist b standard carlini 4271
./run_extra.sh mnist b adversarial carlini 4271
./run_extra.sh mnist b relu carlini 4271
./run_extra.sh mnist c standard carlini 4271
./run_extra.sh mnist c adversarial carlini 4271
./run_extra.sh mnist c relu carlini 4271
./run_extra.sh mnist a standard carlini 7700
./run_extra.sh mnist a adversarial carlini 7700
./run_extra.sh mnist a relu carlini 7700
./run_extra.sh mnist b standard carlini 7700
./run_extra.sh mnist b adversarial carlini 7700
./run_extra.sh mnist b relu carlini 7700
./run_extra.sh mnist c standard carlini 7700
./run_extra.sh mnist c adversarial carlini 7700
./run_extra.sh mnist c relu carlini 7700
./run_extra.sh mnist a standard carlini 7855
./run_extra.sh mnist a adversarial carlini 7855
./run_extra.sh mnist a relu carlini 7855
./run_extra.sh mnist b standard carlini 7855
./run_extra.sh mnist b adversarial carlini 7855
./run_extra.sh mnist b relu carlini 7855
./run_extra.sh mnist c standard carlini 7855
./run_extra.sh mnist c adversarial carlini 7855
./run_extra.sh mnist c relu carlini 7855
./run_extra.sh mnist a standard carlini 1817
./run_extra.sh mnist a adversarial carlini 1817
./run_extra.sh mnist a relu carlini 1817
./run_extra.sh mnist b standard carlini 1817
./run_extra.sh mnist b adversarial carlini 1817
./run_extra.sh mnist b relu carlini 1817
./run_extra.sh mnist c standard carlini 1817
./run_extra.sh mnist c adversarial carlini 1817
./run_extra.sh mnist c relu carlini 1817
./run_extra.sh mnist a standard carlini 3067
./run_extra.sh mnist a adversarial carlini 3067
./run_extra.sh mnist a relu carlini 3067
./run_extra.sh mnist b standard carlini 3067
./run_extra.sh mnist b adversarial carlini 3067
./run_extra.sh mnist b relu carlini 3067
./run_extra.sh mnist c standard carlini 3067
./run_extra.sh mnist c adversarial carlini 3067
./run_extra.sh mnist c relu carlini 3067
./run_extra.sh mnist a standard carlini 8621
./run_extra.sh mnist a adversarial carlini 8621
./run_extra.sh mnist a relu carlini 8621
./run_extra.sh mnist b standard carlini 8621
./run_extra.sh mnist b adversarial carlini 8621
./run_extra.sh mnist b relu carlini 8621
./run_extra.sh mnist c standard carlini 8621
./run_extra.sh mnist c adversarial carlini 8621
./run_extra.sh mnist c relu carlini 8621
./run_extra.sh mnist a standard carlini 8961
./run_extra.sh mnist a adversarial carlini 8961
./run_extra.sh mnist a relu carlini 8961
./run_extra.sh mnist b standard carlini 8961
./run_extra.sh mnist b adversarial carlini 8961
./run_extra.sh mnist b relu carlini 8961
./run_extra.sh mnist c standard carlini 8961
./run_extra.sh mnist c adversarial carlini 8961
./run_extra.sh mnist c relu carlini 8961
./run_extra.sh mnist a standard carlini 1236
./run_extra.sh mnist a adversarial carlini 1236
./run_extra.sh mnist a relu carlini 1236
./run_extra.sh mnist b standard carlini 1236
./run_extra.sh mnist b adversarial carlini 1236
./run_extra.sh mnist b relu carlini 1236
./run_extra.sh mnist c standard carlini 1236
./run_extra.sh mnist c adversarial carlini 1236
./run_extra.sh mnist c relu carlini 1236
./run_extra.sh mnist a standard carlini 1973
./run_extra.sh mnist a adversarial carlini 1973
./run_extra.sh mnist a relu carlini 1973
./run_extra.sh mnist b standard carlini 1973
./run_extra.sh mnist b adversarial carlini 1973
./run_extra.sh mnist b relu carlini 1973
./run_extra.sh mnist c standard carlini 1973
./run_extra.sh mnist c adversarial carlini 1973
./run_extra.sh mnist c relu carlini 1973
./run_extra.sh mnist a standard carlini 6843
./run_extra.sh mnist a adversarial carlini 6843
./run_extra.sh mnist a relu carlini 6843
./run_extra.sh mnist b standard carlini 6843
./run_extra.sh mnist b adversarial carlini 6843
./run_extra.sh mnist b relu carlini 6843
./run_extra.sh mnist c standard carlini 6843
./run_extra.sh mnist c adversarial carlini 6843
./run_extra.sh mnist c relu carlini 6843
./run_extra.sh mnist a standard carlini 3686
./run_extra.sh mnist a adversarial carlini 3686
./run_extra.sh mnist a relu carlini 3686
./run_extra.sh mnist b standard carlini 3686
./run_extra.sh mnist b adversarial carlini 3686
./run_extra.sh mnist b relu carlini 3686
./run_extra.sh mnist c standard carlini 3686
./run_extra.sh mnist c adversarial carlini 3686
./run_extra.sh mnist c relu carlini 3686
./run_extra.sh mnist a standard carlini 901
./run_extra.sh mnist a adversarial carlini 901
./run_extra.sh mnist a relu carlini 901
./run_extra.sh mnist b standard carlini 901
./run_extra.sh mnist b adversarial carlini 901
./run_extra.sh mnist b relu carlini 901
./run_extra.sh mnist c standard carlini 901
./run_extra.sh mnist c adversarial carlini 901
./run_extra.sh mnist c relu carlini 901
./run_extra.sh mnist a standard carlini 5731
./run_extra.sh mnist a adversarial carlini 5731
./run_extra.sh mnist a relu carlini 5731
./run_extra.sh mnist b standard carlini 5731
./run_extra.sh mnist b adversarial carlini 5731
./run_extra.sh mnist b relu carlini 5731
./run_extra.sh mnist c standard carlini 5731
./run_extra.sh mnist c adversarial carlini 5731
./run_extra.sh mnist c relu carlini 5731
./run_extra.sh mnist a standard carlini 3990
./run_extra.sh mnist a adversarial carlini 3990
./run_extra.sh mnist a relu carlini 3990
./run_extra.sh mnist b standard carlini 3990
./run_extra.sh mnist b adversarial carlini 3990
./run_extra.sh mnist b relu carlini 3990
./run_extra.sh mnist c standard carlini 3990
./run_extra.sh mnist c adversarial carlini 3990
./run_extra.sh mnist c relu carlini 3990
./run_extra.sh mnist a standard carlini 9911
./run_extra.sh mnist a adversarial carlini 9911
./run_extra.sh mnist a relu carlini 9911
./run_extra.sh mnist b standard carlini 9911
./run_extra.sh mnist b adversarial carlini 9911
./run_extra.sh mnist b relu carlini 9911
./run_extra.sh mnist c standard carlini 9911
./run_extra.sh mnist c adversarial carlini 9911
./run_extra.sh mnist c relu carlini 9911
./run_extra.sh mnist a standard carlini 951
./run_extra.sh mnist a adversarial carlini 951
./run_extra.sh mnist a relu carlini 951
./run_extra.sh mnist b standard carlini 951
./run_extra.sh mnist b adversarial carlini 951
./run_extra.sh mnist b relu carlini 951
./run_extra.sh mnist c standard carlini 951
./run_extra.sh mnist c adversarial carlini 951
./run_extra.sh mnist c relu carlini 951
./run_extra.sh mnist a standard carlini 5360
./run_extra.sh mnist a adversarial carlini 5360
./run_extra.sh mnist a relu carlini 5360
./run_extra.sh mnist b standard carlini 5360
./run_extra.sh mnist b adversarial carlini 5360
./run_extra.sh mnist b relu carlini 5360
./run_extra.sh mnist c standard carlini 5360
./run_extra.sh mnist c adversarial carlini 5360
./run_extra.sh mnist c relu carlini 5360
./run_extra.sh mnist a standard carlini 3729
./run_extra.sh mnist a adversarial carlini 3729
./run_extra.sh mnist a relu carlini 3729
./run_extra.sh mnist b standard carlini 3729
./run_extra.sh mnist b adversarial carlini 3729
./run_extra.sh mnist b relu carlini 3729
./run_extra.sh mnist c standard carlini 3729
./run_extra.sh mnist c adversarial carlini 3729
./run_extra.sh mnist c relu carlini 3729
./run_extra.sh mnist a standard carlini 1400
./run_extra.sh mnist a adversarial carlini 1400
./run_extra.sh mnist a relu carlini 1400
./run_extra.sh mnist b standard carlini 1400
./run_extra.sh mnist b adversarial carlini 1400
./run_extra.sh mnist b relu carlini 1400
./run_extra.sh mnist c standard carlini 1400
./run_extra.sh mnist c adversarial carlini 1400
./run_extra.sh mnist c relu carlini 1400
./run_extra.sh mnist a standard carlini 6590
./run_extra.sh mnist a adversarial carlini 6590
./run_extra.sh mnist a relu carlini 6590
./run_extra.sh mnist b standard carlini 6590
./run_extra.sh mnist b adversarial carlini 6590
./run_extra.sh mnist b relu carlini 6590
./run_extra.sh mnist c standard carlini 6590
./run_extra.sh mnist c adversarial carlini 6590
./run_extra.sh mnist c relu carlini 6590
./run_extra.sh mnist a standard carlini 2609
./run_extra.sh mnist a adversarial carlini 2609
./run_extra.sh mnist a relu carlini 2609
./run_extra.sh mnist b standard carlini 2609
./run_extra.sh mnist b adversarial carlini 2609
./run_extra.sh mnist b relu carlini 2609
./run_extra.sh mnist c standard carlini 2609
./run_extra.sh mnist c adversarial carlini 2609
./run_extra.sh mnist c relu carlini 2609
./run_extra.sh mnist a standard carlini 6621
./run_extra.sh mnist a adversarial carlini 6621
./run_extra.sh mnist a relu carlini 6621
./run_extra.sh mnist b standard carlini 6621
./run_extra.sh mnist b adversarial carlini 6621
./run_extra.sh mnist b relu carlini 6621
./run_extra.sh mnist c standard carlini 6621
./run_extra.sh mnist c adversarial carlini 6621
./run_extra.sh mnist c relu carlini 6621
./run_extra.sh mnist a standard carlini 4439
./run_extra.sh mnist a adversarial carlini 4439
./run_extra.sh mnist a relu carlini 4439
./run_extra.sh mnist b standard carlini 4439
./run_extra.sh mnist b adversarial carlini 4439
./run_extra.sh mnist b relu carlini 4439
./run_extra.sh mnist c standard carlini 4439
./run_extra.sh mnist c adversarial carlini 4439
./run_extra.sh mnist c relu carlini 4439
./run_extra.sh mnist a standard carlini 7864
./run_extra.sh mnist a adversarial carlini 7864
./run_extra.sh mnist a relu carlini 7864
./run_extra.sh mnist b standard carlini 7864
./run_extra.sh mnist b adversarial carlini 7864
./run_extra.sh mnist b relu carlini 7864
./run_extra.sh mnist c standard carlini 7864
./run_extra.sh mnist c adversarial carlini 7864
./run_extra.sh mnist c relu carlini 7864
./run_extra.sh mnist a standard carlini 7356
./run_extra.sh mnist a adversarial carlini 7356
./run_extra.sh mnist a relu carlini 7356
./run_extra.sh mnist b standard carlini 7356
./run_extra.sh mnist b adversarial carlini 7356
./run_extra.sh mnist b relu carlini 7356
./run_extra.sh mnist c standard carlini 7356
./run_extra.sh mnist c adversarial carlini 7356
./run_extra.sh mnist c relu carlini 7356
./run_extra.sh mnist a standard carlini 6873
./run_extra.sh mnist a adversarial carlini 6873
./run_extra.sh mnist a relu carlini 6873
./run_extra.sh mnist b standard carlini 6873
./run_extra.sh mnist b adversarial carlini 6873
./run_extra.sh mnist b relu carlini 6873
./run_extra.sh mnist c standard carlini 6873
./run_extra.sh mnist c adversarial carlini 6873
./run_extra.sh mnist c relu carlini 6873
./run_extra.sh mnist a standard carlini 8009
./run_extra.sh mnist a adversarial carlini 8009
./run_extra.sh mnist a relu carlini 8009
./run_extra.sh mnist b standard carlini 8009
./run_extra.sh mnist b adversarial carlini 8009
./run_extra.sh mnist b relu carlini 8009
./run_extra.sh mnist c standard carlini 8009
./run_extra.sh mnist c adversarial carlini 8009
./run_extra.sh mnist c relu carlini 8009
./run_extra.sh mnist a standard carlini 5723
./run_extra.sh mnist a adversarial carlini 5723
./run_extra.sh mnist a relu carlini 5723
./run_extra.sh mnist b standard carlini 5723
./run_extra.sh mnist b adversarial carlini 5723
./run_extra.sh mnist b relu carlini 5723
./run_extra.sh mnist c standard carlini 5723
./run_extra.sh mnist c adversarial carlini 5723
./run_extra.sh mnist c relu carlini 5723
./run_extra.sh mnist a standard carlini 8810
./run_extra.sh mnist a adversarial carlini 8810
./run_extra.sh mnist a relu carlini 8810
./run_extra.sh mnist b standard carlini 8810
./run_extra.sh mnist b adversarial carlini 8810
./run_extra.sh mnist b relu carlini 8810
./run_extra.sh mnist c standard carlini 8810
./run_extra.sh mnist c adversarial carlini 8810
./run_extra.sh mnist c relu carlini 8810
./run_extra.sh mnist a standard carlini 269
./run_extra.sh mnist a adversarial carlini 269
./run_extra.sh mnist a relu carlini 269
./run_extra.sh mnist b standard carlini 269
./run_extra.sh mnist b adversarial carlini 269
./run_extra.sh mnist b relu carlini 269
./run_extra.sh mnist c standard carlini 269
./run_extra.sh mnist c adversarial carlini 269
./run_extra.sh mnist c relu carlini 269
./run_extra.sh mnist a standard carlini 766
./run_extra.sh mnist a adversarial carlini 766
./run_extra.sh mnist a relu carlini 766
./run_extra.sh mnist b standard carlini 766
./run_extra.sh mnist b adversarial carlini 766
./run_extra.sh mnist b relu carlini 766
./run_extra.sh mnist c standard carlini 766
./run_extra.sh mnist c adversarial carlini 766
./run_extra.sh mnist c relu carlini 766
./run_extra.sh mnist a standard carlini 5076
./run_extra.sh mnist a adversarial carlini 5076
./run_extra.sh mnist a relu carlini 5076
./run_extra.sh mnist b standard carlini 5076
./run_extra.sh mnist b adversarial carlini 5076
./run_extra.sh mnist b relu carlini 5076
./run_extra.sh mnist c standard carlini 5076
./run_extra.sh mnist c adversarial carlini 5076
./run_extra.sh mnist c relu carlini 5076
./run_extra.sh mnist a standard carlini 2969
./run_extra.sh mnist a adversarial carlini 2969
./run_extra.sh mnist a relu carlini 2969
./run_extra.sh mnist b standard carlini 2969
./run_extra.sh mnist b adversarial carlini 2969
./run_extra.sh mnist b relu carlini 2969
./run_extra.sh mnist c standard carlini 2969
./run_extra.sh mnist c adversarial carlini 2969
./run_extra.sh mnist c relu carlini 2969
./run_extra.sh mnist a standard carlini 9364
./run_extra.sh mnist a adversarial carlini 9364
./run_extra.sh mnist a relu carlini 9364
./run_extra.sh mnist b standard carlini 9364
./run_extra.sh mnist b adversarial carlini 9364
./run_extra.sh mnist b relu carlini 9364
./run_extra.sh mnist c standard carlini 9364
./run_extra.sh mnist c adversarial carlini 9364
./run_extra.sh mnist c relu carlini 9364
./run_extra.sh mnist a standard carlini 1208
./run_extra.sh mnist a adversarial carlini 1208
./run_extra.sh mnist a relu carlini 1208
./run_extra.sh mnist b standard carlini 1208
./run_extra.sh mnist b adversarial carlini 1208
./run_extra.sh mnist b relu carlini 1208
./run_extra.sh mnist c standard carlini 1208
./run_extra.sh mnist c adversarial carlini 1208
./run_extra.sh mnist c relu carlini 1208
./run_extra.sh mnist a standard carlini 992
./run_extra.sh mnist a adversarial carlini 992
./run_extra.sh mnist a relu carlini 992
./run_extra.sh mnist b standard carlini 992
./run_extra.sh mnist b adversarial carlini 992
./run_extra.sh mnist b relu carlini 992
./run_extra.sh mnist c standard carlini 992
./run_extra.sh mnist c adversarial carlini 992
./run_extra.sh mnist c relu carlini 992
./run_extra.sh mnist a standard carlini 3999
./run_extra.sh mnist a adversarial carlini 3999
./run_extra.sh mnist a relu carlini 3999
./run_extra.sh mnist b standard carlini 3999
./run_extra.sh mnist b adversarial carlini 3999
./run_extra.sh mnist b relu carlini 3999
./run_extra.sh mnist c standard carlini 3999
./run_extra.sh mnist c adversarial carlini 3999
./run_extra.sh mnist c relu carlini 3999
./run_extra.sh mnist a standard carlini 5553
./run_extra.sh mnist a adversarial carlini 5553
./run_extra.sh mnist a relu carlini 5553
./run_extra.sh mnist b standard carlini 5553
./run_extra.sh mnist b adversarial carlini 5553
./run_extra.sh mnist b relu carlini 5553
./run_extra.sh mnist c standard carlini 5553
./run_extra.sh mnist c adversarial carlini 5553
./run_extra.sh mnist c relu carlini 5553
./run_extra.sh mnist a standard carlini 3209
./run_extra.sh mnist a adversarial carlini 3209
./run_extra.sh mnist a relu carlini 3209
./run_extra.sh mnist b standard carlini 3209
./run_extra.sh mnist b adversarial carlini 3209
./run_extra.sh mnist b relu carlini 3209
./run_extra.sh mnist c standard carlini 3209
./run_extra.sh mnist c adversarial carlini 3209
./run_extra.sh mnist c relu carlini 3209
./run_extra.sh mnist a standard carlini 9444
./run_extra.sh mnist a adversarial carlini 9444
./run_extra.sh mnist a relu carlini 9444
./run_extra.sh mnist b standard carlini 9444
./run_extra.sh mnist b adversarial carlini 9444
./run_extra.sh mnist b relu carlini 9444
./run_extra.sh mnist c standard carlini 9444
./run_extra.sh mnist c adversarial carlini 9444
./run_extra.sh mnist c relu carlini 9444
./run_extra.sh mnist a standard carlini 9673
./run_extra.sh mnist a adversarial carlini 9673
./run_extra.sh mnist a relu carlini 9673
./run_extra.sh mnist b standard carlini 9673
./run_extra.sh mnist b adversarial carlini 9673
./run_extra.sh mnist b relu carlini 9673
./run_extra.sh mnist c standard carlini 9673
./run_extra.sh mnist c adversarial carlini 9673
./run_extra.sh mnist c relu carlini 9673
./run_extra.sh mnist a standard carlini 6667
./run_extra.sh mnist a adversarial carlini 6667
./run_extra.sh mnist a relu carlini 6667
./run_extra.sh mnist b standard carlini 6667
./run_extra.sh mnist b adversarial carlini 6667
./run_extra.sh mnist b relu carlini 6667
./run_extra.sh mnist c standard carlini 6667
./run_extra.sh mnist c adversarial carlini 6667
./run_extra.sh mnist c relu carlini 6667
./run_extra.sh mnist a standard carlini 9695
./run_extra.sh mnist a adversarial carlini 9695
./run_extra.sh mnist a relu carlini 9695
./run_extra.sh mnist b standard carlini 9695
./run_extra.sh mnist b adversarial carlini 9695
./run_extra.sh mnist b relu carlini 9695
./run_extra.sh mnist c standard carlini 9695
./run_extra.sh mnist c adversarial carlini 9695
./run_extra.sh mnist c relu carlini 9695
./run_extra.sh mnist a standard carlini 7541
./run_extra.sh mnist a adversarial carlini 7541
./run_extra.sh mnist a relu carlini 7541
./run_extra.sh mnist b standard carlini 7541
./run_extra.sh mnist b adversarial carlini 7541
./run_extra.sh mnist b relu carlini 7541
./run_extra.sh mnist c standard carlini 7541
./run_extra.sh mnist c adversarial carlini 7541
./run_extra.sh mnist c relu carlini 7541
./run_extra.sh mnist a standard carlini 6786
./run_extra.sh mnist a adversarial carlini 6786
./run_extra.sh mnist a relu carlini 6786
./run_extra.sh mnist b standard carlini 6786
./run_extra.sh mnist b adversarial carlini 6786
./run_extra.sh mnist b relu carlini 6786
./run_extra.sh mnist c standard carlini 6786
./run_extra.sh mnist c adversarial carlini 6786
./run_extra.sh mnist c relu carlini 6786
./run_extra.sh mnist a standard carlini 4176
./run_extra.sh mnist a adversarial carlini 4176
./run_extra.sh mnist a relu carlini 4176
./run_extra.sh mnist b standard carlini 4176
./run_extra.sh mnist b adversarial carlini 4176
./run_extra.sh mnist b relu carlini 4176
./run_extra.sh mnist c standard carlini 4176
./run_extra.sh mnist c adversarial carlini 4176
./run_extra.sh mnist c relu carlini 4176
./run_extra.sh mnist a standard carlini 8560
./run_extra.sh mnist a adversarial carlini 8560
./run_extra.sh mnist a relu carlini 8560
./run_extra.sh mnist b standard carlini 8560
./run_extra.sh mnist b adversarial carlini 8560
./run_extra.sh mnist b relu carlini 8560
./run_extra.sh mnist c standard carlini 8560
./run_extra.sh mnist c adversarial carlini 8560
./run_extra.sh mnist c relu carlini 8560
./run_extra.sh mnist a standard carlini 2831
./run_extra.sh mnist a adversarial carlini 2831
./run_extra.sh mnist a relu carlini 2831
./run_extra.sh mnist b standard carlini 2831
./run_extra.sh mnist b adversarial carlini 2831
./run_extra.sh mnist b relu carlini 2831
./run_extra.sh mnist c standard carlini 2831
./run_extra.sh mnist c adversarial carlini 2831
./run_extra.sh mnist c relu carlini 2831
./run_extra.sh mnist a standard carlini 2567
./run_extra.sh mnist a adversarial carlini 2567
./run_extra.sh mnist a relu carlini 2567
./run_extra.sh mnist b standard carlini 2567
./run_extra.sh mnist b adversarial carlini 2567
./run_extra.sh mnist b relu carlini 2567
./run_extra.sh mnist c standard carlini 2567
./run_extra.sh mnist c adversarial carlini 2567
./run_extra.sh mnist c relu carlini 2567
./run_extra.sh mnist a standard carlini 7200
./run_extra.sh mnist a adversarial carlini 7200
./run_extra.sh mnist a relu carlini 7200
./run_extra.sh mnist b standard carlini 7200
./run_extra.sh mnist b adversarial carlini 7200
./run_extra.sh mnist b relu carlini 7200
./run_extra.sh mnist c standard carlini 7200
./run_extra.sh mnist c adversarial carlini 7200
./run_extra.sh mnist c relu carlini 7200
./run_extra.sh mnist a standard carlini 2772
./run_extra.sh mnist a adversarial carlini 2772
./run_extra.sh mnist a relu carlini 2772
./run_extra.sh mnist b standard carlini 2772
./run_extra.sh mnist b adversarial carlini 2772
./run_extra.sh mnist b relu carlini 2772
./run_extra.sh mnist c standard carlini 2772
./run_extra.sh mnist c adversarial carlini 2772
./run_extra.sh mnist c relu carlini 2772
./run_extra.sh mnist a standard carlini 4481
./run_extra.sh mnist a adversarial carlini 4481
./run_extra.sh mnist a relu carlini 4481
./run_extra.sh mnist b standard carlini 4481
./run_extra.sh mnist b adversarial carlini 4481
./run_extra.sh mnist b relu carlini 4481
./run_extra.sh mnist c standard carlini 4481
./run_extra.sh mnist c adversarial carlini 4481
./run_extra.sh mnist c relu carlini 4481
./run_extra.sh mnist a standard carlini 4634
./run_extra.sh mnist a adversarial carlini 4634
./run_extra.sh mnist a relu carlini 4634
./run_extra.sh mnist b standard carlini 4634
./run_extra.sh mnist b adversarial carlini 4634
./run_extra.sh mnist b relu carlini 4634
./run_extra.sh mnist c standard carlini 4634
./run_extra.sh mnist c adversarial carlini 4634
./run_extra.sh mnist c relu carlini 4634
./run_extra.sh mnist a standard carlini 1296
./run_extra.sh mnist a adversarial carlini 1296
./run_extra.sh mnist a relu carlini 1296
./run_extra.sh mnist b standard carlini 1296
./run_extra.sh mnist b adversarial carlini 1296
./run_extra.sh mnist b relu carlini 1296
./run_extra.sh mnist c standard carlini 1296
./run_extra.sh mnist c adversarial carlini 1296
./run_extra.sh mnist c relu carlini 1296
./run_extra.sh mnist a standard carlini 4133
./run_extra.sh mnist a adversarial carlini 4133
./run_extra.sh mnist a relu carlini 4133
./run_extra.sh mnist b standard carlini 4133
./run_extra.sh mnist b adversarial carlini 4133
./run_extra.sh mnist b relu carlini 4133
./run_extra.sh mnist c standard carlini 4133
./run_extra.sh mnist c adversarial carlini 4133
./run_extra.sh mnist c relu carlini 4133
./run_extra.sh mnist a standard carlini 3374
./run_extra.sh mnist a adversarial carlini 3374
./run_extra.sh mnist a relu carlini 3374
./run_extra.sh mnist b standard carlini 3374
./run_extra.sh mnist b adversarial carlini 3374
./run_extra.sh mnist b relu carlini 3374
./run_extra.sh mnist c standard carlini 3374
./run_extra.sh mnist c adversarial carlini 3374
./run_extra.sh mnist c relu carlini 3374
./run_extra.sh mnist a standard carlini 6864
./run_extra.sh mnist a adversarial carlini 6864
./run_extra.sh mnist a relu carlini 6864
./run_extra.sh mnist b standard carlini 6864
./run_extra.sh mnist b adversarial carlini 6864
./run_extra.sh mnist b relu carlini 6864
./run_extra.sh mnist c standard carlini 6864
./run_extra.sh mnist c adversarial carlini 6864
./run_extra.sh mnist c relu carlini 6864
./run_extra.sh mnist a standard carlini 6052
./run_extra.sh mnist a adversarial carlini 6052
./run_extra.sh mnist a relu carlini 6052
./run_extra.sh mnist b standard carlini 6052
./run_extra.sh mnist b adversarial carlini 6052
./run_extra.sh mnist b relu carlini 6052
./run_extra.sh mnist c standard carlini 6052
./run_extra.sh mnist c adversarial carlini 6052
./run_extra.sh mnist c relu carlini 6052
./run_extra.sh mnist a standard carlini 4514
./run_extra.sh mnist a adversarial carlini 4514
./run_extra.sh mnist a relu carlini 4514
./run_extra.sh mnist b standard carlini 4514
./run_extra.sh mnist b adversarial carlini 4514
./run_extra.sh mnist b relu carlini 4514
./run_extra.sh mnist c standard carlini 4514
./run_extra.sh mnist c adversarial carlini 4514
./run_extra.sh mnist c relu carlini 4514
./run_extra.sh mnist a standard carlini 9574
./run_extra.sh mnist a adversarial carlini 9574
./run_extra.sh mnist a relu carlini 9574
./run_extra.sh mnist b standard carlini 9574
./run_extra.sh mnist b adversarial carlini 9574
./run_extra.sh mnist b relu carlini 9574
./run_extra.sh mnist c standard carlini 9574
./run_extra.sh mnist c adversarial carlini 9574
./run_extra.sh mnist c relu carlini 9574
./run_extra.sh mnist a standard carlini 6424
./run_extra.sh mnist a adversarial carlini 6424
./run_extra.sh mnist a relu carlini 6424
./run_extra.sh mnist b standard carlini 6424
./run_extra.sh mnist b adversarial carlini 6424
./run_extra.sh mnist b relu carlini 6424
./run_extra.sh mnist c standard carlini 6424
./run_extra.sh mnist c adversarial carlini 6424
./run_extra.sh mnist c relu carlini 6424
./run_extra.sh mnist a standard carlini 1811
./run_extra.sh mnist a adversarial carlini 1811
./run_extra.sh mnist a relu carlini 1811
./run_extra.sh mnist b standard carlini 1811
./run_extra.sh mnist b adversarial carlini 1811
./run_extra.sh mnist b relu carlini 1811
./run_extra.sh mnist c standard carlini 1811
./run_extra.sh mnist c adversarial carlini 1811
./run_extra.sh mnist c relu carlini 1811
./run_extra.sh mnist a standard carlini 8800
./run_extra.sh mnist a adversarial carlini 8800
./run_extra.sh mnist a relu carlini 8800
./run_extra.sh mnist b standard carlini 8800
./run_extra.sh mnist b adversarial carlini 8800
./run_extra.sh mnist b relu carlini 8800
./run_extra.sh mnist c standard carlini 8800
./run_extra.sh mnist c adversarial carlini 8800
./run_extra.sh mnist c relu carlini 8800
./run_extra.sh mnist a standard carlini 651
./run_extra.sh mnist a adversarial carlini 651
./run_extra.sh mnist a relu carlini 651
./run_extra.sh mnist b standard carlini 651
./run_extra.sh mnist b adversarial carlini 651
./run_extra.sh mnist b relu carlini 651
./run_extra.sh mnist c standard carlini 651
./run_extra.sh mnist c adversarial carlini 651
./run_extra.sh mnist c relu carlini 651
./run_extra.sh mnist a standard carlini 1795
./run_extra.sh mnist a adversarial carlini 1795
./run_extra.sh mnist a relu carlini 1795
./run_extra.sh mnist b standard carlini 1795
./run_extra.sh mnist b adversarial carlini 1795
./run_extra.sh mnist b relu carlini 1795
./run_extra.sh mnist c standard carlini 1795
./run_extra.sh mnist c adversarial carlini 1795
./run_extra.sh mnist c relu carlini 1795
./run_extra.sh mnist a standard carlini 7688
./run_extra.sh mnist a adversarial carlini 7688
./run_extra.sh mnist a relu carlini 7688
./run_extra.sh mnist b standard carlini 7688
./run_extra.sh mnist b adversarial carlini 7688
./run_extra.sh mnist b relu carlini 7688
./run_extra.sh mnist c standard carlini 7688
./run_extra.sh mnist c adversarial carlini 7688
./run_extra.sh mnist c relu carlini 7688
./run_extra.sh mnist a standard carlini 9361
./run_extra.sh mnist a adversarial carlini 9361
./run_extra.sh mnist a relu carlini 9361
./run_extra.sh mnist b standard carlini 9361
./run_extra.sh mnist b adversarial carlini 9361
./run_extra.sh mnist b relu carlini 9361
./run_extra.sh mnist c standard carlini 9361
./run_extra.sh mnist c adversarial carlini 9361
./run_extra.sh mnist c relu carlini 9361
./run_extra.sh mnist a standard carlini 4718
./run_extra.sh mnist a adversarial carlini 4718
./run_extra.sh mnist a relu carlini 4718
./run_extra.sh mnist b standard carlini 4718
./run_extra.sh mnist b adversarial carlini 4718
./run_extra.sh mnist b relu carlini 4718
./run_extra.sh mnist c standard carlini 4718
./run_extra.sh mnist c adversarial carlini 4718
./run_extra.sh mnist c relu carlini 4718
./run_extra.sh mnist a standard carlini 1595
./run_extra.sh mnist a adversarial carlini 1595
./run_extra.sh mnist a relu carlini 1595
./run_extra.sh mnist b standard carlini 1595
./run_extra.sh mnist b adversarial carlini 1595
./run_extra.sh mnist b relu carlini 1595
./run_extra.sh mnist c standard carlini 1595
./run_extra.sh mnist c adversarial carlini 1595
./run_extra.sh mnist c relu carlini 1595
./run_extra.sh mnist a standard carlini 7633
./run_extra.sh mnist a adversarial carlini 7633
./run_extra.sh mnist a relu carlini 7633
./run_extra.sh mnist b standard carlini 7633
./run_extra.sh mnist b adversarial carlini 7633
./run_extra.sh mnist b relu carlini 7633
./run_extra.sh mnist c standard carlini 7633
./run_extra.sh mnist c adversarial carlini 7633
./run_extra.sh mnist c relu carlini 7633
./run_extra.sh mnist a standard carlini 4462
./run_extra.sh mnist a adversarial carlini 4462
./run_extra.sh mnist a relu carlini 4462
./run_extra.sh mnist b standard carlini 4462
./run_extra.sh mnist b adversarial carlini 4462
./run_extra.sh mnist b relu carlini 4462
./run_extra.sh mnist c standard carlini 4462
./run_extra.sh mnist c adversarial carlini 4462
./run_extra.sh mnist c relu carlini 4462
./run_extra.sh mnist a standard carlini 3339
./run_extra.sh mnist a adversarial carlini 3339
./run_extra.sh mnist a relu carlini 3339
./run_extra.sh mnist b standard carlini 3339
./run_extra.sh mnist b adversarial carlini 3339
./run_extra.sh mnist b relu carlini 3339
./run_extra.sh mnist c standard carlini 3339
./run_extra.sh mnist c adversarial carlini 3339
./run_extra.sh mnist c relu carlini 3339
./run_extra.sh mnist a standard carlini 4157
./run_extra.sh mnist a adversarial carlini 4157
./run_extra.sh mnist a relu carlini 4157
./run_extra.sh mnist b standard carlini 4157
./run_extra.sh mnist b adversarial carlini 4157
./run_extra.sh mnist b relu carlini 4157
./run_extra.sh mnist c standard carlini 4157
./run_extra.sh mnist c adversarial carlini 4157
./run_extra.sh mnist c relu carlini 4157
./run_extra.sh mnist a standard carlini 7562
./run_extra.sh mnist a adversarial carlini 7562
./run_extra.sh mnist a relu carlini 7562
./run_extra.sh mnist b standard carlini 7562
./run_extra.sh mnist b adversarial carlini 7562
./run_extra.sh mnist b relu carlini 7562
./run_extra.sh mnist c standard carlini 7562
./run_extra.sh mnist c adversarial carlini 7562
./run_extra.sh mnist c relu carlini 7562
./run_extra.sh mnist a standard carlini 2868
./run_extra.sh mnist a adversarial carlini 2868
./run_extra.sh mnist a relu carlini 2868
./run_extra.sh mnist b standard carlini 2868
./run_extra.sh mnist b adversarial carlini 2868
./run_extra.sh mnist b relu carlini 2868
./run_extra.sh mnist c standard carlini 2868
./run_extra.sh mnist c adversarial carlini 2868
./run_extra.sh mnist c relu carlini 2868
./run_extra.sh mnist a standard carlini 3817
./run_extra.sh mnist a adversarial carlini 3817
./run_extra.sh mnist a relu carlini 3817
./run_extra.sh mnist b standard carlini 3817
./run_extra.sh mnist b adversarial carlini 3817
./run_extra.sh mnist b relu carlini 3817
./run_extra.sh mnist c standard carlini 3817
./run_extra.sh mnist c adversarial carlini 3817
./run_extra.sh mnist c relu carlini 3817
./run_extra.sh mnist a standard carlini 9761
./run_extra.sh mnist a adversarial carlini 9761
./run_extra.sh mnist a relu carlini 9761
./run_extra.sh mnist b standard carlini 9761
./run_extra.sh mnist b adversarial carlini 9761
./run_extra.sh mnist b relu carlini 9761
./run_extra.sh mnist c standard carlini 9761
./run_extra.sh mnist c adversarial carlini 9761
./run_extra.sh mnist c relu carlini 9761
./run_extra.sh mnist a standard carlini 5287
./run_extra.sh mnist a adversarial carlini 5287
