./run_extra.sh mnist a adversarial carlini 4769
./run_extra.sh mnist a relu carlini 4769
./run_extra.sh mnist b standard carlini 4769
./run_extra.sh mnist b adversarial carlini 4769
./run_extra.sh mnist b relu carlini 4769
./run_extra.sh mnist c standard carlini 4769
./run_extra.sh mnist c adversarial carlini 4769
./run_extra.sh mnist c relu carlini 4769
./run_extra.sh mnist a standard carlini 1468
./run_extra.sh mnist a adversarial carlini 1468
./run_extra.sh mnist a relu carlini 1468
./run_extra.sh mnist b standard carlini 1468
./run_extra.sh mnist b adversarial carlini 1468
./run_extra.sh mnist b relu carlini 1468
./run_extra.sh mnist c standard carlini 1468
./run_extra.sh mnist c adversarial carlini 1468
./run_extra.sh mnist c relu carlini 1468
./run_extra.sh mnist a standard carlini 3188
./run_extra.sh mnist a adversarial carlini 3188
./run_extra.sh mnist a relu carlini 3188
./run_extra.sh mnist b standard carlini 3188
./run_extra.sh mnist b adversarial carlini 3188
./run_extra.sh mnist b relu carlini 3188
./run_extra.sh mnist c standard carlini 3188
./run_extra.sh mnist c adversarial carlini 3188
./run_extra.sh mnist c relu carlini 3188
./run_extra.sh mnist a standard carlini 2225
./run_extra.sh mnist a adversarial carlini 2225
./run_extra.sh mnist a relu carlini 2225
./run_extra.sh mnist b standard carlini 2225
./run_extra.sh mnist b adversarial carlini 2225
./run_extra.sh mnist b relu carlini 2225
./run_extra.sh mnist c standard carlini 2225
./run_extra.sh mnist c adversarial carlini 2225
./run_extra.sh mnist c relu carlini 2225
./run_extra.sh mnist a standard carlini 2712
./run_extra.sh mnist a adversarial carlini 2712
./run_extra.sh mnist a relu carlini 2712
./run_extra.sh mnist b standard carlini 2712
./run_extra.sh mnist b adversarial carlini 2712
./run_extra.sh mnist b relu carlini 2712
./run_extra.sh mnist c standard carlini 2712
./run_extra.sh mnist c adversarial carlini 2712
./run_extra.sh mnist c relu carlini 2712
./run_extra.sh mnist a standard carlini 6452
./run_extra.sh mnist a adversarial carlini 6452
./run_extra.sh mnist a relu carlini 6452
./run_extra.sh mnist b standard carlini 6452
./run_extra.sh mnist b adversarial carlini 6452
./run_extra.sh mnist b relu carlini 6452
./run_extra.sh mnist c standard carlini 6452
./run_extra.sh mnist c adversarial carlini 6452
./run_extra.sh mnist c relu carlini 6452
./run_extra.sh mnist a standard carlini 8820
./run_extra.sh mnist a adversarial carlini 8820
./run_extra.sh mnist a relu carlini 8820
./run_extra.sh mnist b standard carlini 8820
./run_extra.sh mnist b adversarial carlini 8820
./run_extra.sh mnist b relu carlini 8820
./run_extra.sh mnist c standard carlini 8820
./run_extra.sh mnist c adversarial carlini 8820
./run_extra.sh mnist c relu carlini 8820
./run_extra.sh mnist a standard carlini 5472
./run_extra.sh mnist a adversarial carlini 5472
./run_extra.sh mnist a relu carlini 5472
./run_extra.sh mnist b standard carlini 5472
./run_extra.sh mnist b adversarial carlini 5472
./run_extra.sh mnist b relu carlini 5472
./run_extra.sh mnist c standard carlini 5472
./run_extra.sh mnist c adversarial carlini 5472
./run_extra.sh mnist c relu carlini 5472
./run_extra.sh mnist a standard carlini 428
./run_extra.sh mnist a adversarial carlini 428
./run_extra.sh mnist a relu carlini 428
./run_extra.sh mnist b standard carlini 428
./run_extra.sh mnist b adversarial carlini 428
./run_extra.sh mnist b relu carlini 428
./run_extra.sh mnist c standard carlini 428
./run_extra.sh mnist c adversarial carlini 428
./run_extra.sh mnist c relu carlini 428
./run_extra.sh mnist a standard carlini 4136
./run_extra.sh mnist a adversarial carlini 4136
./run_extra.sh mnist a relu carlini 4136
./run_extra.sh mnist b standard carlini 4136
./run_extra.sh mnist b adversarial carlini 4136
./run_extra.sh mnist b relu carlini 4136
./run_extra.sh mnist c standard carlini 4136
./run_extra.sh mnist c adversarial carlini 4136
./run_extra.sh mnist c relu carlini 4136
./run_extra.sh mnist a standard carlini 9111
./run_extra.sh mnist a adversarial carlini 9111
./run_extra.sh mnist a relu carlini 9111
./run_extra.sh mnist b standard carlini 9111
./run_extra.sh mnist b adversarial carlini 9111
./run_extra.sh mnist b relu carlini 9111
./run_extra.sh mnist c standard carlini 9111
./run_extra.sh mnist c adversarial carlini 9111
./run_extra.sh mnist c relu carlini 9111
./run_extra.sh mnist a standard carlini 9119
./run_extra.sh mnist a adversarial carlini 9119
./run_extra.sh mnist a relu carlini 9119
./run_extra.sh mnist b standard carlini 9119
./run_extra.sh mnist b adversarial carlini 9119
./run_extra.sh mnist b relu carlini 9119
./run_extra.sh mnist c standard carlini 9119
./run_extra.sh mnist c adversarial carlini 9119
./run_extra.sh mnist c relu carlini 9119
./run_extra.sh mnist a standard carlini 1737
./run_extra.sh mnist a adversarial carlini 1737
./run_extra.sh mnist a relu carlini 1737
./run_extra.sh mnist b standard carlini 1737
./run_extra.sh mnist b adversarial carlini 1737
./run_extra.sh mnist b relu carlini 1737
./run_extra.sh mnist c standard carlini 1737
./run_extra.sh mnist c adversarial carlini 1737
./run_extra.sh mnist c relu carlini 1737
./run_extra.sh mnist a standard carlini 2355
./run_extra.sh mnist a adversarial carlini 2355
./run_extra.sh mnist a relu carlini 2355
./run_extra.sh mnist b standard carlini 2355
./run_extra.sh mnist b adversarial carlini 2355
./run_extra.sh mnist b relu carlini 2355
./run_extra.sh mnist c standard carlini 2355
./run_extra.sh mnist c adversarial carlini 2355
./run_extra.sh mnist c relu carlini 2355
./run_extra.sh mnist a standard carlini 527
./run_extra.sh mnist a adversarial carlini 527
./run_extra.sh mnist a relu carlini 527
./run_extra.sh mnist b standard carlini 527
./run_extra.sh mnist b adversarial carlini 527
./run_extra.sh mnist b relu carlini 527
./run_extra.sh mnist c standard carlini 527
./run_extra.sh mnist c adversarial carlini 527
./run_extra.sh mnist c relu carlini 527
./run_extra.sh mnist a standard carlini 3305
./run_extra.sh mnist a adversarial carlini 3305
./run_extra.sh mnist a relu carlini 3305
./run_extra.sh mnist b standard carlini 3305
./run_extra.sh mnist b adversarial carlini 3305
./run_extra.sh mnist b relu carlini 3305
./run_extra.sh mnist c standard carlini 3305
./run_extra.sh mnist c adversarial carlini 3305
./run_extra.sh mnist c relu carlini 3305
./run_extra.sh mnist a standard carlini 7742
./run_extra.sh mnist a adversarial carlini 7742
./run_extra.sh mnist a relu carlini 7742
./run_extra.sh mnist b standard carlini 7742
./run_extra.sh mnist b adversarial carlini 7742
./run_extra.sh mnist b relu carlini 7742
./run_extra.sh mnist c standard carlini 7742
./run_extra.sh mnist c adversarial carlini 7742
./run_extra.sh mnist c relu carlini 7742
./run_extra.sh mnist a standard carlini 6933
./run_extra.sh mnist a adversarial carlini 6933
./run_extra.sh mnist a relu carlini 6933
./run_extra.sh mnist b standard carlini 6933
./run_extra.sh mnist b adversarial carlini 6933
./run_extra.sh mnist b relu carlini 6933
./run_extra.sh mnist c standard carlini 6933
./run_extra.sh mnist c adversarial carlini 6933
./run_extra.sh mnist c relu carlini 6933
./run_extra.sh mnist a standard carlini 475
./run_extra.sh mnist a adversarial carlini 475
./run_extra.sh mnist a relu carlini 475
./run_extra.sh mnist b standard carlini 475
./run_extra.sh mnist b adversarial carlini 475
./run_extra.sh mnist b relu carlini 475
./run_extra.sh mnist c standard carlini 475
./run_extra.sh mnist c adversarial carlini 475
./run_extra.sh mnist c relu carlini 475
./run_extra.sh mnist a standard carlini 2646
./run_extra.sh mnist a adversarial carlini 2646
./run_extra.sh mnist a relu carlini 2646
./run_extra.sh mnist b standard carlini 2646
./run_extra.sh mnist b adversarial carlini 2646
./run_extra.sh mnist b relu carlini 2646
./run_extra.sh mnist c standard carlini 2646
./run_extra.sh mnist c adversarial carlini 2646
./run_extra.sh mnist c relu carlini 2646
./run_extra.sh mnist a standard carlini 4550
./run_extra.sh mnist a adversarial carlini 4550
./run_extra.sh mnist a relu carlini 4550
./run_extra.sh mnist b standard carlini 4550
./run_extra.sh mnist b adversarial carlini 4550
./run_extra.sh mnist b relu carlini 4550
./run_extra.sh mnist c standard carlini 4550
./run_extra.sh mnist c adversarial carlini 4550
./run_extra.sh mnist c relu carlini 4550
./run_extra.sh mnist a standard carlini 2522
./run_extra.sh mnist a adversarial carlini 2522
./run_extra.sh mnist a relu carlini 2522
./run_extra.sh mnist b standard carlini 2522
./run_extra.sh mnist b adversarial carlini 2522
./run_extra.sh mnist b relu carlini 2522
./run_extra.sh mnist c standard carlini 2522
./run_extra.sh mnist c adversarial carlini 2522
./run_extra.sh mnist c relu carlini 2522
./run_extra.sh mnist a standard carlini 7733
./run_extra.sh mnist a adversarial carlini 7733
./run_extra.sh mnist a relu carlini 7733
./run_extra.sh mnist b standard carlini 7733
./run_extra.sh mnist b adversarial carlini 7733
./run_extra.sh mnist b relu carlini 7733
./run_extra.sh mnist c standard carlini 7733
./run_extra.sh mnist c adversarial carlini 7733
./run_extra.sh mnist c relu carlini 7733
./run_extra.sh mnist a standard carlini 7126
./run_extra.sh mnist a adversarial carlini 7126
./run_extra.sh mnist a relu carlini 7126
./run_extra.sh mnist b standard carlini 7126
./run_extra.sh mnist b adversarial carlini 7126
./run_extra.sh mnist b relu carlini 7126
./run_extra.sh mnist c standard carlini 7126
./run_extra.sh mnist c adversarial carlini 7126
./run_extra.sh mnist c relu carlini 7126
./run_extra.sh mnist a standard carlini 8327
./run_extra.sh mnist a adversarial carlini 8327
./run_extra.sh mnist a relu carlini 8327
./run_extra.sh mnist b standard carlini 8327
./run_extra.sh mnist b adversarial carlini 8327
./run_extra.sh mnist b relu carlini 8327
./run_extra.sh mnist c standard carlini 8327
./run_extra.sh mnist c adversarial carlini 8327
./run_extra.sh mnist c relu carlini 8327
./run_extra.sh mnist a standard carlini 6128
./run_extra.sh mnist a adversarial carlini 6128
./run_extra.sh mnist a relu carlini 6128
./run_extra.sh mnist b standard carlini 6128
./run_extra.sh mnist b adversarial carlini 6128
./run_extra.sh mnist b relu carlini 6128
./run_extra.sh mnist c standard carlini 6128
./run_extra.sh mnist c adversarial carlini 6128
./run_extra.sh mnist c relu carlini 6128
./run_extra.sh mnist a standard carlini 8078
./run_extra.sh mnist a adversarial carlini 8078
./run_extra.sh mnist a relu carlini 8078
./run_extra.sh mnist b standard carlini 8078
./run_extra.sh mnist b adversarial carlini 8078
./run_extra.sh mnist b relu carlini 8078
./run_extra.sh mnist c standard carlini 8078
./run_extra.sh mnist c adversarial carlini 8078
./run_extra.sh mnist c relu carlini 8078
./run_extra.sh mnist a standard carlini 7686
./run_extra.sh mnist a adversarial carlini 7686
./run_extra.sh mnist a relu carlini 7686
./run_extra.sh mnist b standard carlini 7686
./run_extra.sh mnist b adversarial carlini 7686
./run_extra.sh mnist b relu carlini 7686
./run_extra.sh mnist c standard carlini 7686
./run_extra.sh mnist c adversarial carlini 7686
./run_extra.sh mnist c relu carlini 7686
./run_extra.sh mnist a standard carlini 4045
./run_extra.sh mnist a adversarial carlini 4045
./run_extra.sh mnist a relu carlini 4045
./run_extra.sh mnist b standard carlini 4045
./run_extra.sh mnist b adversarial carlini 4045
./run_extra.sh mnist b relu carlini 4045
./run_extra.sh mnist c standard carlini 4045
./run_extra.sh mnist c adversarial carlini 4045
./run_extra.sh mnist c relu carlini 4045
./run_extra.sh mnist a standard carlini 3630
./run_extra.sh mnist a adversarial carlini 3630
./run_extra.sh mnist a relu carlini 3630
./run_extra.sh mnist b standard carlini 3630
./run_extra.sh mnist b adversarial carlini 3630
./run_extra.sh mnist b relu carlini 3630
./run_extra.sh mnist c standard carlini 3630
./run_extra.sh mnist c adversarial carlini 3630
./run_extra.sh mnist c relu carlini 3630
./run_extra.sh mnist a standard carlini 3344
./run_extra.sh mnist a adversarial carlini 3344
./run_extra.sh mnist a relu carlini 3344
./run_extra.sh mnist b standard carlini 3344
./run_extra.sh mnist b adversarial carlini 3344
./run_extra.sh mnist b relu carlini 3344
./run_extra.sh mnist c standard carlini 3344
./run_extra.sh mnist c adversarial carlini 3344
./run_extra.sh mnist c relu carlini 3344
./run_extra.sh mnist a standard carlini 1394
./run_extra.sh mnist a adversarial carlini 1394
./run_extra.sh mnist a relu carlini 1394
./run_extra.sh mnist b standard carlini 1394
./run_extra.sh mnist b adversarial carlini 1394
./run_extra.sh mnist b relu carlini 1394
./run_extra.sh mnist c standard carlini 1394
./run_extra.sh mnist c adversarial carlini 1394
./run_extra.sh mnist c relu carlini 1394
./run_extra.sh mnist a standard carlini 2189
./run_extra.sh mnist a adversarial carlini 2189
./run_extra.sh mnist a relu carlini 2189
./run_extra.sh mnist b standard carlini 2189
./run_extra.sh mnist b adversarial carlini 2189
./run_extra.sh mnist b relu carlini 2189
./run_extra.sh mnist c standard carlini 2189
./run_extra.sh mnist c adversarial carlini 2189
./run_extra.sh mnist c relu carlini 2189
./run_extra.sh mnist a standard carlini 9975
./run_extra.sh mnist a adversarial carlini 9975
./run_extra.sh mnist a relu carlini 9975
./run_extra.sh mnist b standard carlini 9975
./run_extra.sh mnist b adversarial carlini 9975
./run_extra.sh mnist b relu carlini 9975
./run_extra.sh mnist c standard carlini 9975
./run_extra.sh mnist c adversarial carlini 9975
./run_extra.sh mnist c relu carlini 9975
./run_extra.sh mnist a standard carlini 8345
./run_extra.sh mnist a adversarial carlini 8345
./run_extra.sh mnist a relu carlini 8345
./run_extra.sh mnist b standard carlini 8345
./run_extra.sh mnist b adversarial carlini 8345
./run_extra.sh mnist b relu carlini 8345
./run_extra.sh mnist c standard carlini 8345
./run_extra.sh mnist c adversarial carlini 8345
./run_extra.sh mnist c relu carlini 8345
./run_extra.sh mnist a standard carlini 8465
./run_extra.sh mnist a adversarial carlini 8465
./run_extra.sh mnist a relu carlini 8465
./run_extra.sh mnist b standard carlini 8465
./run_extra.sh mnist b adversarial carlini 8465
./run_extra.sh mnist b relu carlini 8465
./run_extra.sh mnist c standard carlini 8465
./run_extra.sh mnist c adversarial carlini 8465
./run_extra.sh mnist c relu carlini 8465
./run_extra.sh mnist a standard carlini 2402
./run_extra.sh mnist a adversarial carlini 2402
./run_extra.sh mnist a relu carlini 2402
./run_extra.sh mnist b standard carlini 2402
./run_extra.sh mnist b adversarial carlini 2402
./run_extra.sh mnist b relu carlini 2402
./run_extra.sh mnist c standard carlini 2402
./run_extra.sh mnist c adversarial carlini 2402
./run_extra.sh mnist c relu carlini 2402
./run_extra.sh mnist a standard carlini 9177
./run_extra.sh mnist a adversarial carlini 9177
./run_extra.sh mnist a relu carlini 9177
./run_extra.sh mnist b standard carlini 9177
./run_extra.sh mnist b adversarial carlini 9177
./run_extra.sh mnist b relu carlini 9177
./run_extra.sh mnist c standard carlini 9177
./run_extra.sh mnist c adversarial carlini 9177
./run_extra.sh mnist c relu carlini 9177
./run_extra.sh mnist a standard carlini 8954
./run_extra.sh mnist a adversarial carlini 8954
./run_extra.sh mnist a relu carlini 8954
./run_extra.sh mnist b standard carlini 8954
./run_extra.sh mnist b adversarial carlini 8954
./run_extra.sh mnist b relu carlini 8954
./run_extra.sh mnist c standard carlini 8954
./run_extra.sh mnist c adversarial carlini 8954
./run_extra.sh mnist c relu carlini 8954
./run_extra.sh mnist a standard carlini 8318
./run_extra.sh mnist a adversarial carlini 8318
./run_extra.sh mnist a relu carlini 8318
./run_extra.sh mnist b standard carlini 8318
./run_extra.sh mnist b adversarial carlini 8318
./run_extra.sh mnist b relu carlini 8318
./run_extra.sh mnist c standard carlini 8318
./run_extra.sh mnist c adversarial carlini 8318
./run_extra.sh mnist c relu carlini 8318
./run_extra.sh mnist a standard carlini 2850
./run_extra.sh mnist a adversarial carlini 2850
./run_extra.sh mnist a relu carlini 2850
./run_extra.sh mnist b standard carlini 2850
./run_extra.sh mnist b adversarial carlini 2850
./run_extra.sh mnist b relu carlini 2850
./run_extra.sh mnist c standard carlini 2850
./run_extra.sh mnist c adversarial carlini 2850
./run_extra.sh mnist c relu carlini 2850
./run_extra.sh mnist a standard carlini 1393
./run_extra.sh mnist a adversarial carlini 1393
./run_extra.sh mnist a relu carlini 1393
./run_extra.sh mnist b standard carlini 1393
./run_extra.sh mnist b adversarial carlini 1393
./run_extra.sh mnist b relu carlini 1393
./run_extra.sh mnist c standard carlini 1393
./run_extra.sh mnist c adversarial carlini 1393
./run_extra.sh mnist c relu carlini 1393
./run_extra.sh mnist a standard carlini 4258
./run_extra.sh mnist a adversarial carlini 4258
./run_extra.sh mnist a relu carlini 4258
./run_extra.sh mnist b standard carlini 4258
./run_extra.sh mnist b adversarial carlini 4258
./run_extra.sh mnist b relu carlini 4258
./run_extra.sh mnist c standard carlini 4258
./run_extra.sh mnist c adversarial carlini 4258
./run_extra.sh mnist c relu carlini 4258
./run_extra.sh mnist a standard carlini 3133
./run_extra.sh mnist a adversarial carlini 3133
./run_extra.sh mnist a relu carlini 3133
./run_extra.sh mnist b standard carlini 3133
./run_extra.sh mnist b adversarial carlini 3133
./run_extra.sh mnist b relu carlini 3133
./run_extra.sh mnist c standard carlini 3133
./run_extra.sh mnist c adversarial carlini 3133
./run_extra.sh mnist c relu carlini 3133
./run_extra.sh mnist a standard carlini 8784
./run_extra.sh mnist a adversarial carlini 8784
./run_extra.sh mnist a relu carlini 8784
./run_extra.sh mnist b standard carlini 8784
./run_extra.sh mnist b adversarial carlini 8784
./run_extra.sh mnist b relu carlini 8784
./run_extra.sh mnist c standard carlini 8784
./run_extra.sh mnist c adversarial carlini 8784
./run_extra.sh mnist c relu carlini 8784
./run_extra.sh mnist a standard carlini 639
./run_extra.sh mnist a adversarial carlini 639
./run_extra.sh mnist a relu carlini 639
./run_extra.sh mnist b standard carlini 639
./run_extra.sh mnist b adversarial carlini 639
./run_extra.sh mnist b relu carlini 639
./run_extra.sh mnist c standard carlini 639
./run_extra.sh mnist c adversarial carlini 639
./run_extra.sh mnist c relu carlini 639
./run_extra.sh mnist a standard carlini 7509
./run_extra.sh mnist a adversarial carlini 7509
./run_extra.sh mnist a relu carlini 7509
./run_extra.sh mnist b standard carlini 7509
./run_extra.sh mnist b adversarial carlini 7509
./run_extra.sh mnist b relu carlini 7509
./run_extra.sh mnist c standard carlini 7509
./run_extra.sh mnist c adversarial carlini 7509
./run_extra.sh mnist c relu carlini 7509
./run_extra.sh mnist a standard carlini 1671
./run_extra.sh mnist a adversarial carlini 1671
./run_extra.sh mnist a relu carlini 1671
./run_extra.sh mnist b standard carlini 1671
./run_extra.sh mnist b adversarial carlini 1671
./run_extra.sh mnist b relu carlini 1671
./run_extra.sh mnist c standard carlini 1671
./run_extra.sh mnist c adversarial carlini 1671
./run_extra.sh mnist c relu carlini 1671
./run_extra.sh mnist a standard carlini 7194
./run_extra.sh mnist a adversarial carlini 7194
./run_extra.sh mnist a relu carlini 7194
./run_extra.sh mnist b standard carlini 7194
./run_extra.sh mnist b adversarial carlini 7194
./run_extra.sh mnist b relu carlini 7194
./run_extra.sh mnist c standard carlini 7194
./run_extra.sh mnist c adversarial carlini 7194
./run_extra.sh mnist c relu carlini 7194
./run_extra.sh mnist a standard carlini 6443
./run_extra.sh mnist a adversarial carlini 6443
./run_extra.sh mnist a relu carlini 6443
./run_extra.sh mnist b standard carlini 6443
./run_extra.sh mnist b adversarial carlini 6443
./run_extra.sh mnist b relu carlini 6443
./run_extra.sh mnist c standard carlini 6443
./run_extra.sh mnist c adversarial carlini 6443
./run_extra.sh mnist c relu carlini 6443
./run_extra.sh mnist a standard carlini 6976
./run_extra.sh mnist a adversarial carlini 6976
./run_extra.sh mnist a relu carlini 6976
./run_extra.sh mnist b standard carlini 6976
./run_extra.sh mnist b adversarial carlini 6976
./run_extra.sh mnist b relu carlini 6976
./run_extra.sh mnist c standard carlini 6976
./run_extra.sh mnist c adversarial carlini 6976
./run_extra.sh mnist c relu carlini 6976
./run_extra.sh mnist a standard carlini 9072
./run_extra.sh mnist a adversarial carlini 9072
./run_extra.sh mnist a relu carlini 9072
./run_extra.sh mnist b standard carlini 9072
./run_extra.sh mnist b adversarial carlini 9072
./run_extra.sh mnist b relu carlini 9072
./run_extra.sh mnist c standard carlini 9072
./run_extra.sh mnist c adversarial carlini 9072
./run_extra.sh mnist c relu carlini 9072
./run_extra.sh mnist a standard carlini 3343
./run_extra.sh mnist a adversarial carlini 3343
./run_extra.sh mnist a relu carlini 3343
./run_extra.sh mnist b standard carlini 3343
./run_extra.sh mnist b adversarial carlini 3343
./run_extra.sh mnist b relu carlini 3343
./run_extra.sh mnist c standard carlini 3343
./run_extra.sh mnist c adversarial carlini 3343
./run_extra.sh mnist c relu carlini 3343
./run_extra.sh mnist a standard carlini 5138
./run_extra.sh mnist a adversarial carlini 5138
./run_extra.sh mnist a relu carlini 5138
./run_extra.sh mnist b standard carlini 5138
./run_extra.sh mnist b adversarial carlini 5138
./run_extra.sh mnist b relu carlini 5138
./run_extra.sh mnist c standard carlini 5138
./run_extra.sh mnist c adversarial carlini 5138
./run_extra.sh mnist c relu carlini 5138
./run_extra.sh mnist a standard carlini 6356
./run_extra.sh mnist a adversarial carlini 6356
./run_extra.sh mnist a relu carlini 6356
./run_extra.sh mnist b standard carlini 6356
./run_extra.sh mnist b adversarial carlini 6356
./run_extra.sh mnist b relu carlini 6356
./run_extra.sh mnist c standard carlini 6356
./run_extra.sh mnist c adversarial carlini 6356
./run_extra.sh mnist c relu carlini 6356
./run_extra.sh mnist a standard carlini 7810
./run_extra.sh mnist a adversarial carlini 7810
./run_extra.sh mnist a relu carlini 7810
./run_extra.sh mnist b standard carlini 7810
./run_extra.sh mnist b adversarial carlini 7810
./run_extra.sh mnist b relu carlini 7810
./run_extra.sh mnist c standard carlini 7810
./run_extra.sh mnist c adversarial carlini 7810
./run_extra.sh mnist c relu carlini 7810
./run_extra.sh mnist a standard carlini 4865
./run_extra.sh mnist a adversarial carlini 4865
./run_extra.sh mnist a relu carlini 4865
./run_extra.sh mnist b standard carlini 4865
./run_extra.sh mnist b adversarial carlini 4865
./run_extra.sh mnist b relu carlini 4865
./run_extra.sh mnist c standard carlini 4865
./run_extra.sh mnist c adversarial carlini 4865
./run_extra.sh mnist c relu carlini 4865
./run_extra.sh mnist a standard carlini 1297
./run_extra.sh mnist a adversarial carlini 1297
./run_extra.sh mnist a relu carlini 1297
./run_extra.sh mnist b standard carlini 1297
./run_extra.sh mnist b adversarial carlini 1297
./run_extra.sh mnist b relu carlini 1297
./run_extra.sh mnist c standard carlini 1297
./run_extra.sh mnist c adversarial carlini 1297
./run_extra.sh mnist c relu carlini 1297
./run_extra.sh mnist a standard carlini 9385
./run_extra.sh mnist a adversarial carlini 9385
./run_extra.sh mnist a relu carlini 9385
./run_extra.sh mnist b standard carlini 9385
./run_extra.sh mnist b adversarial carlini 9385
./run_extra.sh mnist b relu carlini 9385
./run_extra.sh mnist c standard carlini 9385
./run_extra.sh mnist c adversarial carlini 9385
./run_extra.sh mnist c relu carlini 9385
./run_extra.sh mnist a standard carlini 3466
./run_extra.sh mnist a adversarial carlini 3466
./run_extra.sh mnist a relu carlini 3466
./run_extra.sh mnist b standard carlini 3466
./run_extra.sh mnist b adversarial carlini 3466
./run_extra.sh mnist b relu carlini 3466
./run_extra.sh mnist c standard carlini 3466
./run_extra.sh mnist c adversarial carlini 3466
./run_extra.sh mnist c relu carlini 3466
./run_extra.sh mnist a standard carlini 9984
./run_extra.sh mnist a adversarial carlini 9984
./run_extra.sh mnist a relu carlini 9984
./run_extra.sh mnist b standard carlini 9984
./run_extra.sh mnist b adversarial carlini 9984
./run_extra.sh mnist b relu carlini 9984
./run_extra.sh mnist c standard carlini 9984
./run_extra.sh mnist c adversarial carlini 9984
./run_extra.sh mnist c relu carlini 9984
./run_extra.sh mnist a standard carlini 5989
./run_extra.sh mnist a adversarial carlini 5989
./run_extra.sh mnist a relu carlini 5989
./run_extra.sh mnist b standard carlini 5989
./run_extra.sh mnist b adversarial carlini 5989
./run_extra.sh mnist b relu carlini 5989
./run_extra.sh mnist c standard carlini 5989
./run_extra.sh mnist c adversarial carlini 5989
./run_extra.sh mnist c relu carlini 5989
./run_extra.sh mnist a standard carlini 838
./run_extra.sh mnist a adversarial carlini 838
./run_extra.sh mnist a relu carlini 838
./run_extra.sh mnist b standard carlini 838
./run_extra.sh mnist b adversarial carlini 838
./run_extra.sh mnist b relu carlini 838
./run_extra.sh mnist c standard carlini 838
./run_extra.sh mnist c adversarial carlini 838
./run_extra.sh mnist c relu carlini 838
./run_extra.sh mnist a standard carlini 2935
./run_extra.sh mnist a adversarial carlini 2935
./run_extra.sh mnist a relu carlini 2935
./run_extra.sh mnist b standard carlini 2935
./run_extra.sh mnist b adversarial carlini 2935
./run_extra.sh mnist b relu carlini 2935
./run_extra.sh mnist c standard carlini 2935
./run_extra.sh mnist c adversarial carlini 2935
./run_extra.sh mnist c relu carlini 2935
./run_extra.sh mnist a standard carlini 5611
./run_extra.sh mnist a adversarial carlini 5611
./run_extra.sh mnist a relu carlini 5611
./run_extra.sh mnist b standard carlini 5611
./run_extra.sh mnist b adversarial carlini 5611
./run_extra.sh mnist b relu carlini 5611
./run_extra.sh mnist c standard carlini 5611
./run_extra.sh mnist c adversarial carlini 5611
./run_extra.sh mnist c relu carlini 5611
./run_extra.sh mnist a standard carlini 2217
./run_extra.sh mnist a adversarial carlini 2217
./run_extra.sh mnist a relu carlini 2217
./run_extra.sh mnist b standard carlini 2217
./run_extra.sh mnist b adversarial carlini 2217
./run_extra.sh mnist b relu carlini 2217
./run_extra.sh mnist c standard carlini 2217
./run_extra.sh mnist c adversarial carlini 2217
./run_extra.sh mnist c relu carlini 2217
./run_extra.sh mnist a standard carlini 551
./run_extra.sh mnist a adversarial carlini 551
./run_extra.sh mnist a relu carlini 551
./run_extra.sh mnist b standard carlini 551
./run_extra.sh mnist b adversarial carlini 551
./run_extra.sh mnist b relu carlini 551
./run_extra.sh mnist c standard carlini 551
./run_extra.sh mnist c adversarial carlini 551
./run_extra.sh mnist c relu carlini 551
./run_extra.sh mnist a standard carlini 6042
./run_extra.sh mnist a adversarial carlini 6042
./run_extra.sh mnist a relu carlini 6042
./run_extra.sh mnist b standard carlini 6042
./run_extra.sh mnist b adversarial carlini 6042
./run_extra.sh mnist b relu carlini 6042
./run_extra.sh mnist c standard carlini 6042
./run_extra.sh mnist c adversarial carlini 6042
./run_extra.sh mnist c relu carlini 6042
./run_extra.sh mnist a standard carlini 6323
./run_extra.sh mnist a adversarial carlini 6323
./run_extra.sh mnist a relu carlini 6323
./run_extra.sh mnist b standard carlini 6323
./run_extra.sh mnist b adversarial carlini 6323
./run_extra.sh mnist b relu carlini 6323
./run_extra.sh mnist c standard carlini 6323
./run_extra.sh mnist c adversarial carlini 6323
./run_extra.sh mnist c relu carlini 6323
./run_extra.sh mnist a standard carlini 6688
./run_extra.sh mnist a adversarial carlini 6688
./run_extra.sh mnist a relu carlini 6688
./run_extra.sh mnist b standard carlini 6688
./run_extra.sh mnist b adversarial carlini 6688
./run_extra.sh mnist b relu carlini 6688
./run_extra.sh mnist c standard carlini 6688
./run_extra.sh mnist c adversarial carlini 6688
./run_extra.sh mnist c relu carlini 6688
./run_extra.sh mnist a standard carlini 3065
./run_extra.sh mnist a adversarial carlini 3065
./run_extra.sh mnist a relu carlini 3065
./run_extra.sh mnist b standard carlini 3065
./run_extra.sh mnist b adversarial carlini 3065
./run_extra.sh mnist b relu carlini 3065
./run_extra.sh mnist c standard carlini 3065
./run_extra.sh mnist c adversarial carlini 3065
./run_extra.sh mnist c relu carlini 3065
./run_extra.sh mnist a standard carlini 6005
./run_extra.sh mnist a adversarial carlini 6005
./run_extra.sh mnist a relu carlini 6005
./run_extra.sh mnist b standard carlini 6005
./run_extra.sh mnist b adversarial carlini 6005
./run_extra.sh mnist b relu carlini 6005
./run_extra.sh mnist c standard carlini 6005
./run_extra.sh mnist c adversarial carlini 6005
./run_extra.sh mnist c relu carlini 6005
./run_extra.sh mnist a standard carlini 1247
./run_extra.sh mnist a adversarial carlini 1247
./run_extra.sh mnist a relu carlini 1247
./run_extra.sh mnist b standard carlini 1247
./run_extra.sh mnist b adversarial carlini 1247
./run_extra.sh mnist b relu carlini 1247
./run_extra.sh mnist c standard carlini 1247
./run_extra.sh mnist c adversarial carlini 1247
./run_extra.sh mnist c relu carlini 1247
./run_extra.sh mnist a standard carlini 6425
./run_extra.sh mnist a adversarial carlini 6425
./run_extra.sh mnist a relu carlini 6425
./run_extra.sh mnist b standard carlini 6425
./run_extra.sh mnist b adversarial carlini 6425
./run_extra.sh mnist b relu carlini 6425
./run_extra.sh mnist c standard carlini 6425
./run_extra.sh mnist c adversarial carlini 6425
./run_extra.sh mnist c relu carlini 6425
./run_extra.sh mnist a standard carlini 8822
./run_extra.sh mnist a adversarial carlini 8822
./run_extra.sh mnist a relu carlini 8822
./run_extra.sh mnist b standard carlini 8822
./run_extra.sh mnist b adversarial carlini 8822
./run_extra.sh mnist b relu carlini 8822
./run_extra.sh mnist c standard carlini 8822
./run_extra.sh mnist c adversarial carlini 8822
./run_extra.sh mnist c relu carlini 8822
./run_extra.sh mnist a standard carlini 6385
./run_extra.sh mnist a adversarial carlini 6385
./run_extra.sh mnist a relu carlini 6385
./run_extra.sh mnist b standard carlini 6385
./run_extra.sh mnist b adversarial carlini 6385
./run_extra.sh mnist b relu carlini 6385
./run_extra.sh mnist c standard carlini 6385
./run_extra.sh mnist c adversarial carlini 6385
./run_extra.sh mnist c relu carlini 6385
./run_extra.sh mnist a standard carlini 2940
./run_extra.sh mnist a adversarial carlini 2940
./run_extra.sh mnist a relu carlini 2940
./run_extra.sh mnist b standard carlini 2940
./run_extra.sh mnist b adversarial carlini 2940
./run_extra.sh mnist b relu carlini 2940
./run_extra.sh mnist c standard carlini 2940
./run_extra.sh mnist c adversarial carlini 2940
./run_extra.sh mnist c relu carlini 2940
./run_extra.sh mnist a standard carlini 8143
./run_extra.sh mnist a adversarial carlini 8143
./run_extra.sh mnist a relu carlini 8143
./run_extra.sh mnist b standard carlini 8143
./run_extra.sh mnist b adversarial carlini 8143
./run_extra.sh mnist b relu carlini 8143
./run_extra.sh mnist c standard carlini 8143
./run_extra.sh mnist c adversarial carlini 8143
./run_extra.sh mnist c relu carlini 8143
./run_extra.sh mnist a standard carlini 8825
./run_extra.sh mnist a adversarial carlini 8825
./run_extra.sh mnist a relu carlini 8825
./run_extra.sh mnist b standard carlini 8825
./run_extra.sh mnist b adversarial carlini 8825
./run_extra.sh mnist b relu carlini 8825
./run_extra.sh mnist c standard carlini 8825
./run_extra.sh mnist c adversarial carlini 8825
./run_extra.sh mnist c relu carlini 8825
./run_extra.sh mnist a standard carlini 8169
./run_extra.sh mnist a adversarial carlini 8169
./run_extra.sh mnist a relu carlini 8169
./run_extra.sh mnist b standard carlini 8169
./run_extra.sh mnist b adversarial carlini 8169
./run_extra.sh mnist b relu carlini 8169
./run_extra.sh mnist c standard carlini 8169
./run_extra.sh mnist c adversarial carlini 8169
./run_extra.sh mnist c relu carlini 8169
./run_extra.sh mnist a standard carlini 5510
./run_extra.sh mnist a adversarial carlini 5510
./run_extra.sh mnist a relu carlini 5510
./run_extra.sh mnist b standard carlini 5510
./run_extra.sh mnist b adversarial carlini 5510
./run_extra.sh mnist b relu carlini 5510
./run_extra.sh mnist c standard carlini 5510
./run_extra.sh mnist c adversarial carlini 5510
./run_extra.sh mnist c relu carlini 5510
./run_extra.sh mnist a standard carlini 8943
./run_extra.sh mnist a adversarial carlini 8943
./run_extra.sh mnist a relu carlini 8943
./run_extra.sh mnist b standard carlini 8943
./run_extra.sh mnist b adversarial carlini 8943
./run_extra.sh mnist b relu carlini 8943
./run_extra.sh mnist c standard carlini 8943
./run_extra.sh mnist c adversarial carlini 8943
./run_extra.sh mnist c relu carlini 8943
./run_extra.sh mnist a standard carlini 3300
./run_extra.sh mnist a adversarial carlini 3300
./run_extra.sh mnist a relu carlini 3300
./run_extra.sh mnist b standard carlini 3300
./run_extra.sh mnist b adversarial carlini 3300
./run_extra.sh mnist b relu carlini 3300
./run_extra.sh mnist c standard carlini 3300
./run_extra.sh mnist c adversarial carlini 3300
./run_extra.sh mnist c relu carlini 3300
./run_extra.sh mnist a standard carlini 7577
./run_extra.sh mnist a adversarial carlini 7577
./run_extra.sh mnist a relu carlini 7577
./run_extra.sh mnist b standard carlini 7577
./run_extra.sh mnist b adversarial carlini 7577
./run_extra.sh mnist b relu carlini 7577
./run_extra.sh mnist c standard carlini 7577
./run_extra.sh mnist c adversarial carlini 7577
./run_extra.sh mnist c relu carlini 7577
./run_extra.sh mnist a standard carlini 7109
./run_extra.sh mnist a adversarial carlini 7109
./run_extra.sh mnist a relu carlini 7109
./run_extra.sh mnist b standard carlini 7109
./run_extra.sh mnist b adversarial carlini 7109
./run_extra.sh mnist b relu carlini 7109
./run_extra.sh mnist c standard carlini 7109
./run_extra.sh mnist c adversarial carlini 7109
./run_extra.sh mnist c relu carlini 7109
./run_extra.sh mnist a standard carlini 503
./run_extra.sh mnist a adversarial carlini 503
./run_extra.sh mnist a relu carlini 503
./run_extra.sh mnist b standard carlini 503
./run_extra.sh mnist b adversarial carlini 503
./run_extra.sh mnist b relu carlini 503
./run_extra.sh mnist c standard carlini 503
./run_extra.sh mnist c adversarial carlini 503
./run_extra.sh mnist c relu carlini 503
./run_extra.sh mnist a standard carlini 9475
./run_extra.sh mnist a adversarial carlini 9475
./run_extra.sh mnist a relu carlini 9475
./run_extra.sh mnist b standard carlini 9475
./run_extra.sh mnist b adversarial carlini 9475
./run_extra.sh mnist b relu carlini 9475
./run_extra.sh mnist c standard carlini 9475
./run_extra.sh mnist c adversarial carlini 9475
./run_extra.sh mnist c relu carlini 9475
./run_extra.sh mnist a standard carlini 8770
./run_extra.sh mnist a adversarial carlini 8770
./run_extra.sh mnist a relu carlini 8770
./run_extra.sh mnist b standard carlini 8770
./run_extra.sh mnist b adversarial carlini 8770
./run_extra.sh mnist b relu carlini 8770
./run_extra.sh mnist c standard carlini 8770
./run_extra.sh mnist c adversarial carlini 8770
./run_extra.sh mnist c relu carlini 8770
./run_extra.sh mnist a standard carlini 2898
./run_extra.sh mnist a adversarial carlini 2898
./run_extra.sh mnist a relu carlini 2898
./run_extra.sh mnist b standard carlini 2898
./run_extra.sh mnist b adversarial carlini 2898
./run_extra.sh mnist b relu carlini 2898
./run_extra.sh mnist c standard carlini 2898
./run_extra.sh mnist c adversarial carlini 2898
./run_extra.sh mnist c relu carlini 2898
./run_extra.sh mnist a standard carlini 6302
./run_extra.sh mnist a adversarial carlini 6302
./run_extra.sh mnist a relu carlini 6302
./run_extra.sh mnist b standard carlini 6302
./run_extra.sh mnist b adversarial carlini 6302
./run_extra.sh mnist b relu carlini 6302
./run_extra.sh mnist c standard carlini 6302
./run_extra.sh mnist c adversarial carlini 6302
./run_extra.sh mnist c relu carlini 6302
./run_extra.sh mnist a standard carlini 900
./run_extra.sh mnist a adversarial carlini 900
./run_extra.sh mnist a relu carlini 900
./run_extra.sh mnist b standard carlini 900
./run_extra.sh mnist b adversarial carlini 900
./run_extra.sh mnist b relu carlini 900
./run_extra.sh mnist c standard carlini 900
./run_extra.sh mnist c adversarial carlini 900
./run_extra.sh mnist c relu carlini 900
./run_extra.sh mnist a standard carlini 8430
./run_extra.sh mnist a adversarial carlini 8430
./run_extra.sh mnist a relu carlini 8430
./run_extra.sh mnist b standard carlini 8430
./run_extra.sh mnist b adversarial carlini 8430
./run_extra.sh mnist b relu carlini 8430
./run_extra.sh mnist c standard carlini 8430
./run_extra.sh mnist c adversarial carlini 8430
./run_extra.sh mnist c relu carlini 8430
./run_extra.sh mnist a standard carlini 6816
./run_extra.sh mnist a adversarial carlini 6816
./run_extra.sh mnist a relu carlini 6816
./run_extra.sh mnist b standard carlini 6816
./run_extra.sh mnist b adversarial carlini 6816
./run_extra.sh mnist b relu carlini 6816
./run_extra.sh mnist c standard carlini 6816
./run_extra.sh mnist c adversarial carlini 6816
./run_extra.sh mnist c relu carlini 6816
./run_extra.sh mnist a standard carlini 5844
./run_extra.sh mnist a adversarial carlini 5844
./run_extra.sh mnist a relu carlini 5844
./run_extra.sh mnist b standard carlini 5844
./run_extra.sh mnist b adversarial carlini 5844
./run_extra.sh mnist b relu carlini 5844
./run_extra.sh mnist c standard carlini 5844
./run_extra.sh mnist c adversarial carlini 5844
./run_extra.sh mnist c relu carlini 5844
./run_extra.sh mnist a standard carlini 263
./run_extra.sh mnist a adversarial carlini 263
./run_extra.sh mnist a relu carlini 263
./run_extra.sh mnist b standard carlini 263
./run_extra.sh mnist b adversarial carlini 263
./run_extra.sh mnist b relu carlini 263
./run_extra.sh mnist c standard carlini 263
./run_extra.sh mnist c adversarial carlini 263
./run_extra.sh mnist c relu carlini 263
./run_extra.sh mnist a standard carlini 4645
./run_extra.sh mnist a adversarial carlini 4645
./run_extra.sh mnist a relu carlini 4645
./run_extra.sh mnist b standard carlini 4645
./run_extra.sh mnist b adversarial carlini 4645
./run_extra.sh mnist b relu carlini 4645
./run_extra.sh mnist c standard carlini 4645
./run_extra.sh mnist c adversarial carlini 4645
./run_extra.sh mnist c relu carlini 4645
./run_extra.sh mnist a standard carlini 6651
./run_extra.sh mnist a adversarial carlini 6651
./run_extra.sh mnist a relu carlini 6651
./run_extra.sh mnist b standard carlini 6651
./run_extra.sh mnist b adversarial carlini 6651
./run_extra.sh mnist b relu carlini 6651
./run_extra.sh mnist c standard carlini 6651
./run_extra.sh mnist c adversarial carlini 6651
./run_extra.sh mnist c relu carlini 6651
./run_extra.sh mnist a standard carlini 2248
./run_extra.sh mnist a adversarial carlini 2248
./run_extra.sh mnist a relu carlini 2248
./run_extra.sh mnist b standard carlini 2248
./run_extra.sh mnist b adversarial carlini 2248
./run_extra.sh mnist b relu carlini 2248
./run_extra.sh mnist c standard carlini 2248
./run_extra.sh mnist c adversarial carlini 2248
./run_extra.sh mnist c relu carlini 2248
./run_extra.sh mnist a standard carlini 5106
./run_extra.sh mnist a adversarial carlini 5106
./run_extra.sh mnist a relu carlini 5106
./run_extra.sh mnist b standard carlini 5106
./run_extra.sh mnist b adversarial carlini 5106
./run_extra.sh mnist b relu carlini 5106
./run_extra.sh mnist c standard carlini 5106
./run_extra.sh mnist c adversarial carlini 5106
./run_extra.sh mnist c relu carlini 5106
./run_extra.sh mnist a standard carlini 8890
./run_extra.sh mnist a adversarial carlini 8890
./run_extra.sh mnist a relu carlini 8890
./run_extra.sh mnist b standard carlini 8890
./run_extra.sh mnist b adversarial carlini 8890
./run_extra.sh mnist b relu carlini 8890
./run_extra.sh mnist c standard carlini 8890
./run_extra.sh mnist c adversarial carlini 8890
./run_extra.sh mnist c relu carlini 8890
./run_extra.sh mnist a standard carlini 5687
./run_extra.sh mnist a adversarial carlini 5687
./run_extra.sh mnist a relu carlini 5687
./run_extra.sh mnist b standard carlini 5687
./run_extra.sh mnist b adversarial carlini 5687
./run_extra.sh mnist b relu carlini 5687
./run_extra.sh mnist c standard carlini 5687
./run_extra.sh mnist c adversarial carlini 5687
./run_extra.sh mnist c relu carlini 5687
./run_extra.sh mnist a standard carlini 923
./run_extra.sh mnist a adversarial carlini 923
./run_extra.sh mnist a relu carlini 923
./run_extra.sh mnist b standard carlini 923
./run_extra.sh mnist b adversarial carlini 923
./run_extra.sh mnist b relu carlini 923
./run_extra.sh mnist c standard carlini 923
./run_extra.sh mnist c adversarial carlini 923
./run_extra.sh mnist c relu carlini 923
./run_extra.sh mnist a standard carlini 2031
./run_extra.sh mnist a adversarial carlini 2031
./run_extra.sh mnist a relu carlini 2031
./run_extra.sh mnist b standard carlini 2031
./run_extra.sh mnist b adversarial carlini 2031
./run_extra.sh mnist b relu carlini 2031
./run_extra.sh mnist c standard carlini 2031
./run_extra.sh mnist c adversarial carlini 2031
./run_extra.sh mnist c relu carlini 2031
./run_extra.sh mnist a standard carlini 8674
./run_extra.sh mnist a adversarial carlini 8674
./run_extra.sh mnist a relu carlini 8674
./run_extra.sh mnist b standard carlini 8674
./run_extra.sh mnist b adversarial carlini 8674
./run_extra.sh mnist b relu carlini 8674
./run_extra.sh mnist c standard carlini 8674
./run_extra.sh mnist c adversarial carlini 8674
./run_extra.sh mnist c relu carlini 8674
./run_extra.sh mnist a standard carlini 5280
./run_extra.sh mnist a adversarial carlini 5280
./run_extra.sh mnist a relu carlini 5280
./run_extra.sh mnist b standard carlini 5280
./run_extra.sh mnist b adversarial carlini 5280
./run_extra.sh mnist b relu carlini 5280
./run_extra.sh mnist c standard carlini 5280
./run_extra.sh mnist c adversarial carlini 5280
./run_extra.sh mnist c relu carlini 5280
./run_extra.sh mnist a standard carlini 9809
./run_extra.sh mnist a adversarial carlini 9809
./run_extra.sh mnist a relu carlini 9809
./run_extra.sh mnist b standard carlini 9809
./run_extra.sh mnist b adversarial carlini 9809
./run_extra.sh mnist b relu carlini 9809
./run_extra.sh mnist c standard carlini 9809
./run_extra.sh mnist c adversarial carlini 9809
./run_extra.sh mnist c relu carlini 9809
./run_extra.sh mnist a standard carlini 8927
./run_extra.sh mnist a adversarial carlini 8927
./run_extra.sh mnist a relu carlini 8927
./run_extra.sh mnist b standard carlini 8927
./run_extra.sh mnist b adversarial carlini 8927
./run_extra.sh mnist b relu carlini 8927
./run_extra.sh mnist c standard carlini 8927
./run_extra.sh mnist c adversarial carlini 8927
./run_extra.sh mnist c relu carlini 8927
./run_extra.sh mnist a standard carlini 5439
./run_extra.sh mnist a adversarial carlini 5439
./run_extra.sh mnist a relu carlini 5439
./run_extra.sh mnist b standard carlini 5439
./run_extra.sh mnist b adversarial carlini 5439
./run_extra.sh mnist b relu carlini 5439
./run_extra.sh mnist c standard carlini 5439
./run_extra.sh mnist c adversarial carlini 5439
./run_extra.sh mnist c relu carlini 5439
./run_extra.sh mnist a standard carlini 8142
./run_extra.sh mnist a adversarial carlini 8142
./run_extra.sh mnist a relu carlini 8142
./run_extra.sh mnist b standard carlini 8142
./run_extra.sh mnist b adversarial carlini 8142
./run_extra.sh mnist b relu carlini 8142
./run_extra.sh mnist c standard carlini 8142
./run_extra.sh mnist c adversarial carlini 8142
./run_extra.sh mnist c relu carlini 8142
./run_extra.sh mnist a standard carlini 2634
./run_extra.sh mnist a adversarial carlini 2634
./run_extra.sh mnist a relu carlini 2634
./run_extra.sh mnist b standard carlini 2634
./run_extra.sh mnist b adversarial carlini 2634
./run_extra.sh mnist b relu carlini 2634
./run_extra.sh mnist c standard carlini 2634
./run_extra.sh mnist c adversarial carlini 2634
./run_extra.sh mnist c relu carlini 2634
./run_extra.sh mnist a standard carlini 2184
./run_extra.sh mnist a adversarial carlini 2184
./run_extra.sh mnist a relu carlini 2184
./run_extra.sh mnist b standard carlini 2184
./run_extra.sh mnist b adversarial carlini 2184
./run_extra.sh mnist b relu carlini 2184
./run_extra.sh mnist c standard carlini 2184
./run_extra.sh mnist c adversarial carlini 2184
./run_extra.sh mnist c relu carlini 2184
./run_extra.sh mnist a standard carlini 7152
./run_extra.sh mnist a adversarial carlini 7152
./run_extra.sh mnist a relu carlini 7152
./run_extra.sh mnist b standard carlini 7152
./run_extra.sh mnist b adversarial carlini 7152
./run_extra.sh mnist b relu carlini 7152
./run_extra.sh mnist c standard carlini 7152
./run_extra.sh mnist c adversarial carlini 7152
./run_extra.sh mnist c relu carlini 7152
./run_extra.sh mnist a standard carlini 5926
./run_extra.sh mnist a adversarial carlini 5926
./run_extra.sh mnist a relu carlini 5926
./run_extra.sh mnist b standard carlini 5926
./run_extra.sh mnist b adversarial carlini 5926
./run_extra.sh mnist b relu carlini 5926
./run_extra.sh mnist c standard carlini 5926
./run_extra.sh mnist c adversarial carlini 5926
./run_extra.sh mnist c relu carlini 5926
./run_extra.sh mnist a standard carlini 8919
./run_extra.sh mnist a adversarial carlini 8919
./run_extra.sh mnist a relu carlini 8919
./run_extra.sh mnist b standard carlini 8919
./run_extra.sh mnist b adversarial carlini 8919
./run_extra.sh mnist b relu carlini 8919
./run_extra.sh mnist c standard carlini 8919
./run_extra.sh mnist c adversarial carlini 8919
./run_extra.sh mnist c relu carlini 8919
./run_extra.sh mnist a standard carlini 1889
./run_extra.sh mnist a adversarial carlini 1889
./run_extra.sh mnist a relu carlini 1889
./run_extra.sh mnist b standard carlini 1889
./run_extra.sh mnist b adversarial carlini 1889
./run_extra.sh mnist b relu carlini 1889
./run_extra.sh mnist c standard carlini 1889
./run_extra.sh mnist c adversarial carlini 1889
./run_extra.sh mnist c relu carlini 1889
./run_extra.sh mnist a standard carlini 9140
./run_extra.sh mnist a adversarial carlini 9140
./run_extra.sh mnist a relu carlini 9140
./run_extra.sh mnist b standard carlini 9140
./run_extra.sh mnist b adversarial carlini 9140
./run_extra.sh mnist b relu carlini 9140
./run_extra.sh mnist c standard carlini 9140
./run_extra.sh mnist c adversarial carlini 9140
./run_extra.sh mnist c relu carlini 9140
./run_extra.sh mnist a standard carlini 7948
./run_extra.sh mnist a adversarial carlini 7948
./run_extra.sh mnist a relu carlini 7948
./run_extra.sh mnist b standard carlini 7948
./run_extra.sh mnist b adversarial carlini 7948
./run_extra.sh mnist b relu carlini 7948
./run_extra.sh mnist c standard carlini 7948
./run_extra.sh mnist c adversarial carlini 7948
./run_extra.sh mnist c relu carlini 7948
./run_extra.sh mnist a standard carlini 4410
./run_extra.sh mnist a adversarial carlini 4410
./run_extra.sh mnist a relu carlini 4410
./run_extra.sh mnist b standard carlini 4410
./run_extra.sh mnist b adversarial carlini 4410
./run_extra.sh mnist b relu carlini 4410
./run_extra.sh mnist c standard carlini 4410
./run_extra.sh mnist c adversarial carlini 4410
./run_extra.sh mnist c relu carlini 4410
./run_extra.sh mnist a standard carlini 1683
./run_extra.sh mnist a adversarial carlini 1683
./run_extra.sh mnist a relu carlini 1683
./run_extra.sh mnist b standard carlini 1683
./run_extra.sh mnist b adversarial carlini 1683
./run_extra.sh mnist b relu carlini 1683
./run_extra.sh mnist c standard carlini 1683
./run_extra.sh mnist c adversarial carlini 1683
./run_extra.sh mnist c relu carlini 1683
./run_extra.sh mnist a standard carlini 8234
./run_extra.sh mnist a adversarial carlini 8234
./run_extra.sh mnist a relu carlini 8234
./run_extra.sh mnist b standard carlini 8234
./run_extra.sh mnist b adversarial carlini 8234
./run_extra.sh mnist b relu carlini 8234
./run_extra.sh mnist c standard carlini 8234
./run_extra.sh mnist c adversarial carlini 8234
./run_extra.sh mnist c relu carlini 8234
./run_extra.sh mnist a standard carlini 7786
./run_extra.sh mnist a adversarial carlini 7786
./run_extra.sh mnist a relu carlini 7786
./run_extra.sh mnist b standard carlini 7786
./run_extra.sh mnist b adversarial carlini 7786
./run_extra.sh mnist b relu carlini 7786
./run_extra.sh mnist c standard carlini 7786
./run_extra.sh mnist c adversarial carlini 7786
./run_extra.sh mnist c relu carlini 7786
./run_extra.sh mnist a standard carlini 1659
./run_extra.sh mnist a adversarial carlini 1659
./run_extra.sh mnist a relu carlini 1659
./run_extra.sh mnist b standard carlini 1659
./run_extra.sh mnist b adversarial carlini 1659
./run_extra.sh mnist b relu carlini 1659
./run_extra.sh mnist c standard carlini 1659
./run_extra.sh mnist c adversarial carlini 1659
./run_extra.sh mnist c relu carlini 1659
./run_extra.sh mnist a standard carlini 7676
./run_extra.sh mnist a adversarial carlini 7676
./run_extra.sh mnist a relu carlini 7676
./run_extra.sh mnist b standard carlini 7676
./run_extra.sh mnist b adversarial carlini 7676
./run_extra.sh mnist b relu carlini 7676
./run_extra.sh mnist c standard carlini 7676
./run_extra.sh mnist c adversarial carlini 7676
./run_extra.sh mnist c relu carlini 7676
./run_extra.sh mnist a standard carlini 9584
./run_extra.sh mnist a adversarial carlini 9584
./run_extra.sh mnist a relu carlini 9584
./run_extra.sh mnist b standard carlini 9584
./run_extra.sh mnist b adversarial carlini 9584
./run_extra.sh mnist b relu carlini 9584
./run_extra.sh mnist c standard carlini 9584
./run_extra.sh mnist c adversarial carlini 9584
./run_extra.sh mnist c relu carlini 9584
./run_extra.sh mnist a standard carlini 4445
./run_extra.sh mnist a adversarial carlini 4445
./run_extra.sh mnist a relu carlini 4445
./run_extra.sh mnist b standard carlini 4445
./run_extra.sh mnist b adversarial carlini 4445
./run_extra.sh mnist b relu carlini 4445
./run_extra.sh mnist c standard carlini 4445
./run_extra.sh mnist c adversarial carlini 4445
./run_extra.sh mnist c relu carlini 4445
./run_extra.sh mnist a standard carlini 9328
./run_extra.sh mnist a adversarial carlini 9328
./run_extra.sh mnist a relu carlini 9328
./run_extra.sh mnist b standard carlini 9328
./run_extra.sh mnist b adversarial carlini 9328
./run_extra.sh mnist b relu carlini 9328
./run_extra.sh mnist c standard carlini 9328
./run_extra.sh mnist c adversarial carlini 9328
./run_extra.sh mnist c relu carlini 9328
./run_extra.sh mnist a standard carlini 6030
./run_extra.sh mnist a adversarial carlini 6030
./run_extra.sh mnist a relu carlini 6030
./run_extra.sh mnist b standard carlini 6030
./run_extra.sh mnist b adversarial carlini 6030
./run_extra.sh mnist b relu carlini 6030
./run_extra.sh mnist c standard carlini 6030
./run_extra.sh mnist c adversarial carlini 6030
./run_extra.sh mnist c relu carlini 6030
./run_extra.sh mnist a standard carlini 9457
./run_extra.sh mnist a adversarial carlini 9457
./run_extra.sh mnist a relu carlini 9457
./run_extra.sh mnist b standard carlini 9457
./run_extra.sh mnist b adversarial carlini 9457
./run_extra.sh mnist b relu carlini 9457
./run_extra.sh mnist c standard carlini 9457
./run_extra.sh mnist c adversarial carlini 9457
./run_extra.sh mnist c relu carlini 9457
./run_extra.sh mnist a standard carlini 7336
./run_extra.sh mnist a adversarial carlini 7336
./run_extra.sh mnist a relu carlini 7336
./run_extra.sh mnist b standard carlini 7336
./run_extra.sh mnist b adversarial carlini 7336
./run_extra.sh mnist b relu carlini 7336
./run_extra.sh mnist c standard carlini 7336
./run_extra.sh mnist c adversarial carlini 7336
./run_extra.sh mnist c relu carlini 7336
./run_extra.sh mnist a standard carlini 7481
./run_extra.sh mnist a adversarial carlini 7481
./run_extra.sh mnist a relu carlini 7481
./run_extra.sh mnist b standard carlini 7481
./run_extra.sh mnist b adversarial carlini 7481
./run_extra.sh mnist b relu carlini 7481
./run_extra.sh mnist c standard carlini 7481
./run_extra.sh mnist c adversarial carlini 7481
./run_extra.sh mnist c relu carlini 7481
./run_extra.sh mnist a standard carlini 6031
./run_extra.sh mnist a adversarial carlini 6031
./run_extra.sh mnist a relu carlini 6031
./run_extra.sh mnist b standard carlini 6031
./run_extra.sh mnist b adversarial carlini 6031
./run_extra.sh mnist b relu carlini 6031
./run_extra.sh mnist c standard carlini 6031
./run_extra.sh mnist c adversarial carlini 6031
./run_extra.sh mnist c relu carlini 6031
./run_extra.sh mnist a standard carlini 3761
./run_extra.sh mnist a adversarial carlini 3761
./run_extra.sh mnist a relu carlini 3761
./run_extra.sh mnist b standard carlini 3761
./run_extra.sh mnist b adversarial carlini 3761
./run_extra.sh mnist b relu carlini 3761
./run_extra.sh mnist c standard carlini 3761
./run_extra.sh mnist c adversarial carlini 3761
./run_extra.sh mnist c relu carlini 3761
./run_extra.sh mnist a standard carlini 5338
./run_extra.sh mnist a adversarial carlini 5338
./run_extra.sh mnist a relu carlini 5338
./run_extra.sh mnist b standard carlini 5338
./run_extra.sh mnist b adversarial carlini 5338
./run_extra.sh mnist b relu carlini 5338
./run_extra.sh mnist c standard carlini 5338
./run_extra.sh mnist c adversarial carlini 5338
./run_extra.sh mnist c relu carlini 5338
./run_extra.sh mnist a standard carlini 8199
./run_extra.sh mnist a adversarial carlini 8199
./run_extra.sh mnist a relu carlini 8199
./run_extra.sh mnist b standard carlini 8199
./run_extra.sh mnist b adversarial carlini 8199
./run_extra.sh mnist b relu carlini 8199
./run_extra.sh mnist c standard carlini 8199
./run_extra.sh mnist c adversarial carlini 8199
./run_extra.sh mnist c relu carlini 8199
./run_extra.sh mnist a standard carlini 4155
./run_extra.sh mnist a adversarial carlini 4155
./run_extra.sh mnist a relu carlini 4155
./run_extra.sh mnist b standard carlini 4155
./run_extra.sh mnist b adversarial carlini 4155
./run_extra.sh mnist b relu carlini 4155
./run_extra.sh mnist c standard carlini 4155
./run_extra.sh mnist c adversarial carlini 4155
./run_extra.sh mnist c relu carlini 4155
./run_extra.sh mnist a standard carlini 3503
./run_extra.sh mnist a adversarial carlini 3503
./run_extra.sh mnist a relu carlini 3503
./run_extra.sh mnist b standard carlini 3503
./run_extra.sh mnist b adversarial carlini 3503
./run_extra.sh mnist b relu carlini 3503
./run_extra.sh mnist c standard carlini 3503
./run_extra.sh mnist c adversarial carlini 3503
./run_extra.sh mnist c relu carlini 3503
./run_extra.sh mnist a standard carlini 9011
./run_extra.sh mnist a adversarial carlini 9011
./run_extra.sh mnist a relu carlini 9011
./run_extra.sh mnist b standard carlini 9011
./run_extra.sh mnist b adversarial carlini 9011
./run_extra.sh mnist b relu carlini 9011
./run_extra.sh mnist c standard carlini 9011
./run_extra.sh mnist c adversarial carlini 9011
./run_extra.sh mnist c relu carlini 9011
./run_extra.sh mnist a standard carlini 7393
./run_extra.sh mnist a adversarial carlini 7393
./run_extra.sh mnist a relu carlini 7393
./run_extra.sh mnist b standard carlini 7393
./run_extra.sh mnist b adversarial carlini 7393
./run_extra.sh mnist b relu carlini 7393
./run_extra.sh mnist c standard carlini 7393
./run_extra.sh mnist c adversarial carlini 7393
./run_extra.sh mnist c relu carlini 7393
./run_extra.sh mnist a standard carlini 1123
./run_extra.sh mnist a adversarial carlini 1123
./run_extra.sh mnist a relu carlini 1123
./run_extra.sh mnist b standard carlini 1123
./run_extra.sh mnist b adversarial carlini 1123
./run_extra.sh mnist b relu carlini 1123
./run_extra.sh mnist c standard carlini 1123
./run_extra.sh mnist c adversarial carlini 1123
./run_extra.sh mnist c relu carlini 1123
./run_extra.sh mnist a standard carlini 981
./run_extra.sh mnist a adversarial carlini 981
./run_extra.sh mnist a relu carlini 981
./run_extra.sh mnist b standard carlini 981
./run_extra.sh mnist b adversarial carlini 981
./run_extra.sh mnist b relu carlini 981
./run_extra.sh mnist c standard carlini 981
./run_extra.sh mnist c adversarial carlini 981
./run_extra.sh mnist c relu carlini 981
./run_extra.sh mnist a standard carlini 3992
./run_extra.sh mnist a adversarial carlini 3992
./run_extra.sh mnist a relu carlini 3992
./run_extra.sh mnist b standard carlini 3992
./run_extra.sh mnist b adversarial carlini 3992
./run_extra.sh mnist b relu carlini 3992
./run_extra.sh mnist c standard carlini 3992
./run_extra.sh mnist c adversarial carlini 3992
./run_extra.sh mnist c relu carlini 3992
./run_extra.sh mnist a standard carlini 3200
./run_extra.sh mnist a adversarial carlini 3200
./run_extra.sh mnist a relu carlini 3200
./run_extra.sh mnist b standard carlini 3200
./run_extra.sh mnist b adversarial carlini 3200
./run_extra.sh mnist b relu carlini 3200
./run_extra.sh mnist c standard carlini 3200
./run_extra.sh mnist c adversarial carlini 3200
./run_extra.sh mnist c relu carlini 3200
./run_extra.sh mnist a standard carlini 7788
./run_extra.sh mnist a adversarial carlini 7788
./run_extra.sh mnist a relu carlini 7788
./run_extra.sh mnist b standard carlini 7788
./run_extra.sh mnist b adversarial carlini 7788
./run_extra.sh mnist b relu carlini 7788
./run_extra.sh mnist c standard carlini 7788
./run_extra.sh mnist c adversarial carlini 7788
./run_extra.sh mnist c relu carlini 7788
./run_extra.sh mnist a standard carlini 2847
./run_extra.sh mnist a adversarial carlini 2847
./run_extra.sh mnist a relu carlini 2847
./run_extra.sh mnist b standard carlini 2847
./run_extra.sh mnist b adversarial carlini 2847
./run_extra.sh mnist b relu carlini 2847
./run_extra.sh mnist c standard carlini 2847
./run_extra.sh mnist c adversarial carlini 2847
./run_extra.sh mnist c relu carlini 2847
./run_extra.sh mnist a standard carlini 2702
./run_extra.sh mnist a adversarial carlini 2702
./run_extra.sh mnist a relu carlini 2702
./run_extra.sh mnist b standard carlini 2702
./run_extra.sh mnist b adversarial carlini 2702
./run_extra.sh mnist b relu carlini 2702
./run_extra.sh mnist c standard carlini 2702
./run_extra.sh mnist c adversarial carlini 2702
./run_extra.sh mnist c relu carlini 2702
./run_extra.sh mnist a standard carlini 5726
./run_extra.sh mnist a adversarial carlini 5726
./run_extra.sh mnist a relu carlini 5726
./run_extra.sh mnist b standard carlini 5726
./run_extra.sh mnist b adversarial carlini 5726
./run_extra.sh mnist b relu carlini 5726
./run_extra.sh mnist c standard carlini 5726
./run_extra.sh mnist c adversarial carlini 5726
./run_extra.sh mnist c relu carlini 5726
./run_extra.sh mnist a standard carlini 697
./run_extra.sh mnist a adversarial carlini 697
./run_extra.sh mnist a relu carlini 697
./run_extra.sh mnist b standard carlini 697
./run_extra.sh mnist b adversarial carlini 697
./run_extra.sh mnist b relu carlini 697
./run_extra.sh mnist c standard carlini 697
./run_extra.sh mnist c adversarial carlini 697
./run_extra.sh mnist c relu carlini 697
./run_extra.sh mnist a standard carlini 7701
./run_extra.sh mnist a adversarial carlini 7701
./run_extra.sh mnist a relu carlini 7701
./run_extra.sh mnist b standard carlini 7701
./run_extra.sh mnist b adversarial carlini 7701
./run_extra.sh mnist b relu carlini 7701
./run_extra.sh mnist c standard carlini 7701
./run_extra.sh mnist c adversarial carlini 7701
./run_extra.sh mnist c relu carlini 7701
./run_extra.sh mnist a standard carlini 8672
./run_extra.sh mnist a adversarial carlini 8672
./run_extra.sh mnist a relu carlini 8672
./run_extra.sh mnist b standard carlini 8672
./run_extra.sh mnist b adversarial carlini 8672
./run_extra.sh mnist b relu carlini 8672
./run_extra.sh mnist c standard carlini 8672
./run_extra.sh mnist c adversarial carlini 8672
./run_extra.sh mnist c relu carlini 8672
./run_extra.sh mnist a standard carlini 857
./run_extra.sh mnist a adversarial carlini 857
./run_extra.sh mnist a relu carlini 857
./run_extra.sh mnist b standard carlini 857
./run_extra.sh mnist b adversarial carlini 857
./run_extra.sh mnist b relu carlini 857
./run_extra.sh mnist c standard carlini 857
./run_extra.sh mnist c adversarial carlini 857
./run_extra.sh mnist c relu carlini 857
./run_extra.sh mnist a standard carlini 469
./run_extra.sh mnist a adversarial carlini 469
./run_extra.sh mnist a relu carlini 469
./run_extra.sh mnist b standard carlini 469
./run_extra.sh mnist b adversarial carlini 469
./run_extra.sh mnist b relu carlini 469
./run_extra.sh mnist c standard carlini 469
./run_extra.sh mnist c adversarial carlini 469
./run_extra.sh mnist c relu carlini 469
./run_extra.sh mnist a standard carlini 456
./run_extra.sh mnist a adversarial carlini 456
./run_extra.sh mnist a relu carlini 456
./run_extra.sh mnist b standard carlini 456
./run_extra.sh mnist b adversarial carlini 456
./run_extra.sh mnist b relu carlini 456
./run_extra.sh mnist c standard carlini 456
./run_extra.sh mnist c adversarial carlini 456
./run_extra.sh mnist c relu carlini 456
./run_extra.sh mnist a standard carlini 6380
./run_extra.sh mnist a adversarial carlini 6380
./run_extra.sh mnist a relu carlini 6380
./run_extra.sh mnist b standard carlini 6380
./run_extra.sh mnist b adversarial carlini 6380
./run_extra.sh mnist b relu carlini 6380
./run_extra.sh mnist c standard carlini 6380
./run_extra.sh mnist c adversarial carlini 6380
./run_extra.sh mnist c relu carlini 6380
./run_extra.sh mnist a standard carlini 7580
./run_extra.sh mnist a adversarial carlini 7580
./run_extra.sh mnist a relu carlini 7580
./run_extra.sh mnist b standard carlini 7580
./run_extra.sh mnist b adversarial carlini 7580
./run_extra.sh mnist b relu carlini 7580
./run_extra.sh mnist c standard carlini 7580
./run_extra.sh mnist c adversarial carlini 7580
./run_extra.sh mnist c relu carlini 7580
./run_extra.sh mnist a standard carlini 9969
./run_extra.sh mnist a adversarial carlini 9969
./run_extra.sh mnist a relu carlini 9969
./run_extra.sh mnist b standard carlini 9969
./run_extra.sh mnist b adversarial carlini 9969
./run_extra.sh mnist b relu carlini 9969
./run_extra.sh mnist c standard carlini 9969
./run_extra.sh mnist c adversarial carlini 9969
./run_extra.sh mnist c relu carlini 9969
./run_extra.sh mnist a standard carlini 3262
./run_extra.sh mnist a adversarial carlini 3262
./run_extra.sh mnist a relu carlini 3262
./run_extra.sh mnist b standard carlini 3262
./run_extra.sh mnist b adversarial carlini 3262
./run_extra.sh mnist b relu carlini 3262
./run_extra.sh mnist c standard carlini 3262
./run_extra.sh mnist c adversarial carlini 3262
./run_extra.sh mnist c relu carlini 3262
./run_extra.sh mnist a standard carlini 7488
./run_extra.sh mnist a adversarial carlini 7488
./run_extra.sh mnist a relu carlini 7488
./run_extra.sh mnist b standard carlini 7488
./run_extra.sh mnist b adversarial carlini 7488
./run_extra.sh mnist b relu carlini 7488
./run_extra.sh mnist c standard carlini 7488
./run_extra.sh mnist c adversarial carlini 7488
./run_extra.sh mnist c relu carlini 7488
./run_extra.sh mnist a standard carlini 572
./run_extra.sh mnist a adversarial carlini 572
./run_extra.sh mnist a relu carlini 572
./run_extra.sh mnist b standard carlini 572
./run_extra.sh mnist b adversarial carlini 572
./run_extra.sh mnist b relu carlini 572
./run_extra.sh mnist c standard carlini 572
./run_extra.sh mnist c adversarial carlini 572
./run_extra.sh mnist c relu carlini 572
./run_extra.sh mnist a standard carlini 2571
./run_extra.sh mnist a adversarial carlini 2571
./run_extra.sh mnist a relu carlini 2571
./run_extra.sh mnist b standard carlini 2571
./run_extra.sh mnist b adversarial carlini 2571
./run_extra.sh mnist b relu carlini 2571
./run_extra.sh mnist c standard carlini 2571
./run_extra.sh mnist c adversarial carlini 2571
./run_extra.sh mnist c relu carlini 2571
./run_extra.sh mnist a standard carlini 9043
./run_extra.sh mnist a adversarial carlini 9043
./run_extra.sh mnist a relu carlini 9043
./run_extra.sh mnist b standard carlini 9043
./run_extra.sh mnist b adversarial carlini 9043
./run_extra.sh mnist b relu carlini 9043
./run_extra.sh mnist c standard carlini 9043
./run_extra.sh mnist c adversarial carlini 9043
./run_extra.sh mnist c relu carlini 9043
./run_extra.sh mnist a standard carlini 7233
./run_extra.sh mnist a adversarial carlini 7233
./run_extra.sh mnist a relu carlini 7233
./run_extra.sh mnist b standard carlini 7233
./run_extra.sh mnist b adversarial carlini 7233
./run_extra.sh mnist b relu carlini 7233
./run_extra.sh mnist c standard carlini 7233
./run_extra.sh mnist c adversarial carlini 7233
./run_extra.sh mnist c relu carlini 7233
./run_extra.sh mnist a standard carlini 4851
./run_extra.sh mnist a adversarial carlini 4851
./run_extra.sh mnist a relu carlini 4851
./run_extra.sh mnist b standard carlini 4851
./run_extra.sh mnist b adversarial carlini 4851
./run_extra.sh mnist b relu carlini 4851
./run_extra.sh mnist c standard carlini 4851
./run_extra.sh mnist c adversarial carlini 4851
./run_extra.sh mnist c relu carlini 4851
./run_extra.sh mnist a standard carlini 9503
./run_extra.sh mnist a adversarial carlini 9503
./run_extra.sh mnist a relu carlini 9503
./run_extra.sh mnist b standard carlini 9503
./run_extra.sh mnist b adversarial carlini 9503
./run_extra.sh mnist b relu carlini 9503
./run_extra.sh mnist c standard carlini 9503
./run_extra.sh mnist c adversarial carlini 9503
./run_extra.sh mnist c relu carlini 9503
./run_extra.sh mnist a standard carlini 8881
./run_extra.sh mnist a adversarial carlini 8881
./run_extra.sh mnist a relu carlini 8881
./run_extra.sh mnist b standard carlini 8881
./run_extra.sh mnist b adversarial carlini 8881
./run_extra.sh mnist b relu carlini 8881
./run_extra.sh mnist c standard carlini 8881
./run_extra.sh mnist c adversarial carlini 8881
./run_extra.sh mnist c relu carlini 8881
./run_extra.sh mnist a standard carlini 9979
./run_extra.sh mnist a adversarial carlini 9979
./run_extra.sh mnist a relu carlini 9979
./run_extra.sh mnist b standard carlini 9979
./run_extra.sh mnist b adversarial carlini 9979
./run_extra.sh mnist b relu carlini 9979
./run_extra.sh mnist c standard carlini 9979
./run_extra.sh mnist c adversarial carlini 9979
./run_extra.sh mnist c relu carlini 9979
./run_extra.sh mnist a standard carlini 659
./run_extra.sh mnist a adversarial carlini 659
./run_extra.sh mnist a relu carlini 659
./run_extra.sh mnist b standard carlini 659
./run_extra.sh mnist b adversarial carlini 659
./run_extra.sh mnist b relu carlini 659
./run_extra.sh mnist c standard carlini 659
./run_extra.sh mnist c adversarial carlini 659
./run_extra.sh mnist c relu carlini 659
./run_extra.sh mnist a standard carlini 7278
./run_extra.sh mnist a adversarial carlini 7278
./run_extra.sh mnist a relu carlini 7278
./run_extra.sh mnist b standard carlini 7278
./run_extra.sh mnist b adversarial carlini 7278
./run_extra.sh mnist b relu carlini 7278
./run_extra.sh mnist c standard carlini 7278
./run_extra.sh mnist c adversarial carlini 7278
./run_extra.sh mnist c relu carlini 7278
./run_extra.sh mnist a standard carlini 9863
./run_extra.sh mnist a adversarial carlini 9863
./run_extra.sh mnist a relu carlini 9863
./run_extra.sh mnist b standard carlini 9863
./run_extra.sh mnist b adversarial carlini 9863
./run_extra.sh mnist b relu carlini 9863
./run_extra.sh mnist c standard carlini 9863
./run_extra.sh mnist c adversarial carlini 9863
./run_extra.sh mnist c relu carlini 9863
./run_extra.sh mnist a standard carlini 5085
./run_extra.sh mnist a adversarial carlini 5085
./run_extra.sh mnist a relu carlini 5085
./run_extra.sh mnist b standard carlini 5085
./run_extra.sh mnist b adversarial carlini 5085
./run_extra.sh mnist b relu carlini 5085
./run_extra.sh mnist c standard carlini 5085
./run_extra.sh mnist c adversarial carlini 5085
./run_extra.sh mnist c relu carlini 5085
./run_extra.sh mnist a standard carlini 3511
./run_extra.sh mnist a adversarial carlini 3511
./run_extra.sh mnist a relu carlini 3511
./run_extra.sh mnist b standard carlini 3511
./run_extra.sh mnist b adversarial carlini 3511
./run_extra.sh mnist b relu carlini 3511
./run_extra.sh mnist c standard carlini 3511
./run_extra.sh mnist c adversarial carlini 3511
./run_extra.sh mnist c relu carlini 3511
./run_extra.sh mnist a standard carlini 4868
./run_extra.sh mnist a adversarial carlini 4868
./run_extra.sh mnist a relu carlini 4868
./run_extra.sh mnist b standard carlini 4868
./run_extra.sh mnist b adversarial carlini 4868
./run_extra.sh mnist b relu carlini 4868
./run_extra.sh mnist c standard carlini 4868
./run_extra.sh mnist c adversarial carlini 4868
./run_extra.sh mnist c relu carlini 4868
./run_extra.sh mnist a standard carlini 1307
./run_extra.sh mnist a adversarial carlini 1307
./run_extra.sh mnist a relu carlini 1307
./run_extra.sh mnist b standard carlini 1307
./run_extra.sh mnist b adversarial carlini 1307
./run_extra.sh mnist b relu carlini 1307
./run_extra.sh mnist c standard carlini 1307
./run_extra.sh mnist c adversarial carlini 1307
./run_extra.sh mnist c relu carlini 1307
./run_extra.sh mnist a standard carlini 9236
./run_extra.sh mnist a adversarial carlini 9236
./run_extra.sh mnist a relu carlini 9236
./run_extra.sh mnist b standard carlini 9236
./run_extra.sh mnist b adversarial carlini 9236
./run_extra.sh mnist b relu carlini 9236
./run_extra.sh mnist c standard carlini 9236
./run_extra.sh mnist c adversarial carlini 9236
./run_extra.sh mnist c relu carlini 9236
./run_extra.sh mnist a standard carlini 1991
./run_extra.sh mnist a adversarial carlini 1991
./run_extra.sh mnist a relu carlini 1991
./run_extra.sh mnist b standard carlini 1991
./run_extra.sh mnist b adversarial carlini 1991
./run_extra.sh mnist b relu carlini 1991
./run_extra.sh mnist c standard carlini 1991
./run_extra.sh mnist c adversarial carlini 1991
./run_extra.sh mnist c relu carlini 1991
./run_extra.sh mnist a standard carlini 1487
./run_extra.sh mnist a adversarial carlini 1487
./run_extra.sh mnist a relu carlini 1487
./run_extra.sh mnist b standard carlini 1487
./run_extra.sh mnist b adversarial carlini 1487
./run_extra.sh mnist b relu carlini 1487
./run_extra.sh mnist c standard carlini 1487
./run_extra.sh mnist c adversarial carlini 1487
./run_extra.sh mnist c relu carlini 1487
./run_extra.sh mnist a standard carlini 4789
./run_extra.sh mnist a adversarial carlini 4789
./run_extra.sh mnist a relu carlini 4789
./run_extra.sh mnist b standard carlini 4789
./run_extra.sh mnist b adversarial carlini 4789
./run_extra.sh mnist b relu carlini 4789
./run_extra.sh mnist c standard carlini 4789
./run_extra.sh mnist c adversarial carlini 4789
./run_extra.sh mnist c relu carlini 4789
./run_extra.sh mnist a standard carlini 8348
./run_extra.sh mnist a adversarial carlini 8348
./run_extra.sh mnist a relu carlini 8348
./run_extra.sh mnist b standard carlini 8348
./run_extra.sh mnist b adversarial carlini 8348
./run_extra.sh mnist b relu carlini 8348
./run_extra.sh mnist c standard carlini 8348
./run_extra.sh mnist c adversarial carlini 8348
./run_extra.sh mnist c relu carlini 8348
./run_extra.sh mnist a standard carlini 3226
./run_extra.sh mnist a adversarial carlini 3226
./run_extra.sh mnist a relu carlini 3226
./run_extra.sh mnist b standard carlini 3226
./run_extra.sh mnist b adversarial carlini 3226
./run_extra.sh mnist b relu carlini 3226
./run_extra.sh mnist c standard carlini 3226
./run_extra.sh mnist c adversarial carlini 3226
./run_extra.sh mnist c relu carlini 3226
./run_extra.sh mnist a standard carlini 949
./run_extra.sh mnist a adversarial carlini 949
./run_extra.sh mnist a relu carlini 949
./run_extra.sh mnist b standard carlini 949
./run_extra.sh mnist b adversarial carlini 949
./run_extra.sh mnist b relu carlini 949
./run_extra.sh mnist c standard carlini 949
./run_extra.sh mnist c adversarial carlini 949
./run_extra.sh mnist c relu carlini 949
./run_extra.sh mnist a standard carlini 6597
./run_extra.sh mnist a adversarial carlini 6597
./run_extra.sh mnist a relu carlini 6597
./run_extra.sh mnist b standard carlini 6597
./run_extra.sh mnist b adversarial carlini 6597
./run_extra.sh mnist b relu carlini 6597
./run_extra.sh mnist c standard carlini 6597
./run_extra.sh mnist c adversarial carlini 6597
./run_extra.sh mnist c relu carlini 6597
./run_extra.sh mnist a standard carlini 9594
./run_extra.sh mnist a adversarial carlini 9594
./run_extra.sh mnist a relu carlini 9594
./run_extra.sh mnist b standard carlini 9594
./run_extra.sh mnist b adversarial carlini 9594
./run_extra.sh mnist b relu carlini 9594
./run_extra.sh mnist c standard carlini 9594
./run_extra.sh mnist c adversarial carlini 9594
./run_extra.sh mnist c relu carlini 9594
./run_extra.sh mnist a standard carlini 7876
./run_extra.sh mnist a adversarial carlini 7876
./run_extra.sh mnist a relu carlini 7876
./run_extra.sh mnist b standard carlini 7876
./run_extra.sh mnist b adversarial carlini 7876
./run_extra.sh mnist b relu carlini 7876
./run_extra.sh mnist c standard carlini 7876
./run_extra.sh mnist c adversarial carlini 7876
./run_extra.sh mnist c relu carlini 7876
./run_extra.sh mnist a standard carlini 7165
./run_extra.sh mnist a adversarial carlini 7165
./run_extra.sh mnist a relu carlini 7165
./run_extra.sh mnist b standard carlini 7165
./run_extra.sh mnist b adversarial carlini 7165
./run_extra.sh mnist b relu carlini 7165
./run_extra.sh mnist c standard carlini 7165
./run_extra.sh mnist c adversarial carlini 7165
./run_extra.sh mnist c relu carlini 7165
./run_extra.sh mnist a standard carlini 2509
./run_extra.sh mnist a adversarial carlini 2509
./run_extra.sh mnist a relu carlini 2509
./run_extra.sh mnist b standard carlini 2509
./run_extra.sh mnist b adversarial carlini 2509
./run_extra.sh mnist b relu carlini 2509
./run_extra.sh mnist c standard carlini 2509
./run_extra.sh mnist c adversarial carlini 2509
./run_extra.sh mnist c relu carlini 2509
./run_extra.sh mnist a standard carlini 656
./run_extra.sh mnist a adversarial carlini 656
./run_extra.sh mnist a relu carlini 656
./run_extra.sh mnist b standard carlini 656
./run_extra.sh mnist b adversarial carlini 656
./run_extra.sh mnist b relu carlini 656
./run_extra.sh mnist c standard carlini 656
./run_extra.sh mnist c adversarial carlini 656
./run_extra.sh mnist c relu carlini 656
./run_extra.sh mnist a standard carlini 3665
./run_extra.sh mnist a adversarial carlini 3665
./run_extra.sh mnist a relu carlini 3665
./run_extra.sh mnist b standard carlini 3665
./run_extra.sh mnist b adversarial carlini 3665
./run_extra.sh mnist b relu carlini 3665
./run_extra.sh mnist c standard carlini 3665
./run_extra.sh mnist c adversarial carlini 3665
./run_extra.sh mnist c relu carlini 3665
./run_extra.sh mnist a standard carlini 3757
./run_extra.sh mnist a adversarial carlini 3757
./run_extra.sh mnist a relu carlini 3757
./run_extra.sh mnist b standard carlini 3757
./run_extra.sh mnist b adversarial carlini 3757
./run_extra.sh mnist b relu carlini 3757
./run_extra.sh mnist c standard carlini 3757
./run_extra.sh mnist c adversarial carlini 3757
./run_extra.sh mnist c relu carlini 3757
./run_extra.sh mnist a standard carlini 5341
./run_extra.sh mnist a adversarial carlini 5341
./run_extra.sh mnist a relu carlini 5341
./run_extra.sh mnist b standard carlini 5341
./run_extra.sh mnist b adversarial carlini 5341
./run_extra.sh mnist b relu carlini 5341
./run_extra.sh mnist c standard carlini 5341
./run_extra.sh mnist c adversarial carlini 5341
./run_extra.sh mnist c relu carlini 5341
./run_extra.sh mnist a standard carlini 2550
./run_extra.sh mnist a adversarial carlini 2550
./run_extra.sh mnist a relu carlini 2550
./run_extra.sh mnist b standard carlini 2550
./run_extra.sh mnist b adversarial carlini 2550
./run_extra.sh mnist b relu carlini 2550
./run_extra.sh mnist c standard carlini 2550
./run_extra.sh mnist c adversarial carlini 2550
./run_extra.sh mnist c relu carlini 2550
./run_extra.sh mnist a standard carlini 9509
./run_extra.sh mnist a adversarial carlini 9509
./run_extra.sh mnist a relu carlini 9509
./run_extra.sh mnist b standard carlini 9509
./run_extra.sh mnist b adversarial carlini 9509
./run_extra.sh mnist b relu carlini 9509
./run_extra.sh mnist c standard carlini 9509
./run_extra.sh mnist c adversarial carlini 9509
./run_extra.sh mnist c relu carlini 9509
./run_extra.sh mnist a standard carlini 5185
./run_extra.sh mnist a adversarial carlini 5185
./run_extra.sh mnist a relu carlini 5185
./run_extra.sh mnist b standard carlini 5185
./run_extra.sh mnist b adversarial carlini 5185
./run_extra.sh mnist b relu carlini 5185
./run_extra.sh mnist c standard carlini 5185
./run_extra.sh mnist c adversarial carlini 5185
./run_extra.sh mnist c relu carlini 5185
./run_extra.sh mnist a standard carlini 7172
./run_extra.sh mnist a adversarial carlini 7172
./run_extra.sh mnist a relu carlini 7172
./run_extra.sh mnist b standard carlini 7172
./run_extra.sh mnist b adversarial carlini 7172
./run_extra.sh mnist b relu carlini 7172
./run_extra.sh mnist c standard carlini 7172
./run_extra.sh mnist c adversarial carlini 7172
./run_extra.sh mnist c relu carlini 7172
./run_extra.sh mnist a standard carlini 3951
./run_extra.sh mnist a adversarial carlini 3951
./run_extra.sh mnist a relu carlini 3951
./run_extra.sh mnist b standard carlini 3951
./run_extra.sh mnist b adversarial carlini 3951
./run_extra.sh mnist b relu carlini 3951
./run_extra.sh mnist c standard carlini 3951
./run_extra.sh mnist c adversarial carlini 3951
./run_extra.sh mnist c relu carlini 3951
./run_extra.sh mnist a standard carlini 995
./run_extra.sh mnist a adversarial carlini 995
./run_extra.sh mnist a relu carlini 995
./run_extra.sh mnist b standard carlini 995
./run_extra.sh mnist b adversarial carlini 995
./run_extra.sh mnist b relu carlini 995
./run_extra.sh mnist c standard carlini 995
./run_extra.sh mnist c adversarial carlini 995
./run_extra.sh mnist c relu carlini 995
./run_extra.sh mnist a standard carlini 7119
./run_extra.sh mnist a adversarial carlini 7119
./run_extra.sh mnist a relu carlini 7119
./run_extra.sh mnist b standard carlini 7119
./run_extra.sh mnist b adversarial carlini 7119
./run_extra.sh mnist b relu carlini 7119
./run_extra.sh mnist c standard carlini 7119
./run_extra.sh mnist c adversarial carlini 7119
./run_extra.sh mnist c relu carlini 7119
./run_extra.sh mnist a standard carlini 8754
./run_extra.sh mnist a adversarial carlini 8754
./run_extra.sh mnist a relu carlini 8754
./run_extra.sh mnist b standard carlini 8754
./run_extra.sh mnist b adversarial carlini 8754
./run_extra.sh mnist b relu carlini 8754
./run_extra.sh mnist c standard carlini 8754
./run_extra.sh mnist c adversarial carlini 8754
./run_extra.sh mnist c relu carlini 8754
./run_extra.sh mnist a standard carlini 933
./run_extra.sh mnist a adversarial carlini 933
./run_extra.sh mnist a relu carlini 933
./run_extra.sh mnist b standard carlini 933
./run_extra.sh mnist b adversarial carlini 933
./run_extra.sh mnist b relu carlini 933
./run_extra.sh mnist c standard carlini 933
./run_extra.sh mnist c adversarial carlini 933
./run_extra.sh mnist c relu carlini 933
./run_extra.sh mnist a standard carlini 3711
./run_extra.sh mnist a adversarial carlini 3711
./run_extra.sh mnist a relu carlini 3711
./run_extra.sh mnist b standard carlini 3711
./run_extra.sh mnist b adversarial carlini 3711
./run_extra.sh mnist b relu carlini 3711
./run_extra.sh mnist c standard carlini 3711
./run_extra.sh mnist c adversarial carlini 3711
./run_extra.sh mnist c relu carlini 3711
./run_extra.sh mnist a standard carlini 2729
./run_extra.sh mnist a adversarial carlini 2729
./run_extra.sh mnist a relu carlini 2729
./run_extra.sh mnist b standard carlini 2729
./run_extra.sh mnist b adversarial carlini 2729
./run_extra.sh mnist b relu carlini 2729
./run_extra.sh mnist c standard carlini 2729
./run_extra.sh mnist c adversarial carlini 2729
./run_extra.sh mnist c relu carlini 2729
./run_extra.sh mnist a standard carlini 6239
./run_extra.sh mnist a adversarial carlini 6239
./run_extra.sh mnist a relu carlini 6239
./run_extra.sh mnist b standard carlini 6239
./run_extra.sh mnist b adversarial carlini 6239
./run_extra.sh mnist b relu carlini 6239
./run_extra.sh mnist c standard carlini 6239
./run_extra.sh mnist c adversarial carlini 6239
./run_extra.sh mnist c relu carlini 6239
./run_extra.sh mnist a standard carlini 3842
./run_extra.sh mnist a adversarial carlini 3842
./run_extra.sh mnist a relu carlini 3842
./run_extra.sh mnist b standard carlini 3842
./run_extra.sh mnist b adversarial carlini 3842
./run_extra.sh mnist b relu carlini 3842
./run_extra.sh mnist c standard carlini 3842
./run_extra.sh mnist c adversarial carlini 3842
./run_extra.sh mnist c relu carlini 3842
./run_extra.sh mnist a standard carlini 2338
./run_extra.sh mnist a adversarial carlini 2338
./run_extra.sh mnist a relu carlini 2338
./run_extra.sh mnist b standard carlini 2338
./run_extra.sh mnist b adversarial carlini 2338
./run_extra.sh mnist b relu carlini 2338
./run_extra.sh mnist c standard carlini 2338
./run_extra.sh mnist c adversarial carlini 2338
./run_extra.sh mnist c relu carlini 2338
./run_extra.sh mnist a standard carlini 1864
./run_extra.sh mnist a adversarial carlini 1864
./run_extra.sh mnist a relu carlini 1864
./run_extra.sh mnist b standard carlini 1864
./run_extra.sh mnist b adversarial carlini 1864
./run_extra.sh mnist b relu carlini 1864
./run_extra.sh mnist c standard carlini 1864
./run_extra.sh mnist c adversarial carlini 1864
./run_extra.sh mnist c relu carlini 1864
./run_extra.sh mnist a standard carlini 2457
./run_extra.sh mnist a adversarial carlini 2457
./run_extra.sh mnist a relu carlini 2457
./run_extra.sh mnist b standard carlini 2457
./run_extra.sh mnist b adversarial carlini 2457
./run_extra.sh mnist b relu carlini 2457
./run_extra.sh mnist c standard carlini 2457
./run_extra.sh mnist c adversarial carlini 2457
./run_extra.sh mnist c relu carlini 2457
./run_extra.sh mnist a standard carlini 9532
./run_extra.sh mnist a adversarial carlini 9532
./run_extra.sh mnist a relu carlini 9532
./run_extra.sh mnist b standard carlini 9532
./run_extra.sh mnist b adversarial carlini 9532
./run_extra.sh mnist b relu carlini 9532
./run_extra.sh mnist c standard carlini 9532
./run_extra.sh mnist c adversarial carlini 9532
./run_extra.sh mnist c relu carlini 9532
./run_extra.sh mnist a standard carlini 4707
./run_extra.sh mnist a adversarial carlini 4707
./run_extra.sh mnist a relu carlini 4707
./run_extra.sh mnist b standard carlini 4707
./run_extra.sh mnist b adversarial carlini 4707
./run_extra.sh mnist b relu carlini 4707
./run_extra.sh mnist c standard carlini 4707
./run_extra.sh mnist c adversarial carlini 4707
./run_extra.sh mnist c relu carlini 4707
./run_extra.sh mnist a standard carlini 9929
./run_extra.sh mnist a adversarial carlini 9929
./run_extra.sh mnist a relu carlini 9929
./run_extra.sh mnist b standard carlini 9929
./run_extra.sh mnist b adversarial carlini 9929
./run_extra.sh mnist b relu carlini 9929
./run_extra.sh mnist c standard carlini 9929
./run_extra.sh mnist c adversarial carlini 9929
./run_extra.sh mnist c relu carlini 9929
./run_extra.sh mnist a standard carlini 4720
./run_extra.sh mnist a adversarial carlini 4720
./run_extra.sh mnist a relu carlini 4720
./run_extra.sh mnist b standard carlini 4720
./run_extra.sh mnist b adversarial carlini 4720
./run_extra.sh mnist b relu carlini 4720
./run_extra.sh mnist c standard carlini 4720
./run_extra.sh mnist c adversarial carlini 4720
./run_extra.sh mnist c relu carlini 4720
./run_extra.sh mnist a standard carlini 7698
./run_extra.sh mnist a adversarial carlini 7698
./run_extra.sh mnist a relu carlini 7698
./run_extra.sh mnist b standard carlini 7698
./run_extra.sh mnist b adversarial carlini 7698
./run_extra.sh mnist b relu carlini 7698
./run_extra.sh mnist c standard carlini 7698
./run_extra.sh mnist c adversarial carlini 7698
./run_extra.sh mnist c relu carlini 7698
./run_extra.sh mnist a standard carlini 268
./run_extra.sh mnist a adversarial carlini 268
./run_extra.sh mnist a relu carlini 268
./run_extra.sh mnist b standard carlini 268
./run_extra.sh mnist b adversarial carlini 268
./run_extra.sh mnist b relu carlini 268
./run_extra.sh mnist c standard carlini 268
./run_extra.sh mnist c adversarial carlini 268
./run_extra.sh mnist c relu carlini 268
./run_extra.sh mnist a standard carlini 8010
./run_extra.sh mnist a adversarial carlini 8010
./run_extra.sh mnist a relu carlini 8010
./run_extra.sh mnist b standard carlini 8010
./run_extra.sh mnist b adversarial carlini 8010
./run_extra.sh mnist b relu carlini 8010
./run_extra.sh mnist c standard carlini 8010
./run_extra.sh mnist c adversarial carlini 8010
./run_extra.sh mnist c relu carlini 8010
./run_extra.sh mnist a standard carlini 497
./run_extra.sh mnist a adversarial carlini 497
./run_extra.sh mnist a relu carlini 497
./run_extra.sh mnist b standard carlini 497
./run_extra.sh mnist b adversarial carlini 497
./run_extra.sh mnist b relu carlini 497
./run_extra.sh mnist c standard carlini 497
./run_extra.sh mnist c adversarial carlini 497
./run_extra.sh mnist c relu carlini 497
./run_extra.sh mnist a standard carlini 4307
./run_extra.sh mnist a adversarial carlini 4307
./run_extra.sh mnist a relu carlini 4307
./run_extra.sh mnist b standard carlini 4307
./run_extra.sh mnist b adversarial carlini 4307
./run_extra.sh mnist b relu carlini 4307
./run_extra.sh mnist c standard carlini 4307
./run_extra.sh mnist c adversarial carlini 4307
./run_extra.sh mnist c relu carlini 4307
./run_extra.sh mnist a standard carlini 9477
./run_extra.sh mnist a adversarial carlini 9477
./run_extra.sh mnist a relu carlini 9477
./run_extra.sh mnist b standard carlini 9477
./run_extra.sh mnist b adversarial carlini 9477
./run_extra.sh mnist b relu carlini 9477
./run_extra.sh mnist c standard carlini 9477
./run_extra.sh mnist c adversarial carlini 9477
./run_extra.sh mnist c relu carlini 9477
./run_extra.sh mnist a standard carlini 5404
./run_extra.sh mnist a adversarial carlini 5404
./run_extra.sh mnist a relu carlini 5404
./run_extra.sh mnist b standard carlini 5404
./run_extra.sh mnist b adversarial carlini 5404
./run_extra.sh mnist b relu carlini 5404
./run_extra.sh mnist c standard carlini 5404
./run_extra.sh mnist c adversarial carlini 5404
./run_extra.sh mnist c relu carlini 5404
./run_extra.sh mnist a standard carlini 5045
./run_extra.sh mnist a adversarial carlini 5045
./run_extra.sh mnist a relu carlini 5045
./run_extra.sh mnist b standard carlini 5045
./run_extra.sh mnist b adversarial carlini 5045
./run_extra.sh mnist b relu carlini 5045
./run_extra.sh mnist c standard carlini 5045
./run_extra.sh mnist c adversarial carlini 5045
./run_extra.sh mnist c relu carlini 5045
./run_extra.sh mnist a standard carlini 5418
./run_extra.sh mnist a adversarial carlini 5418
./run_extra.sh mnist a relu carlini 5418
./run_extra.sh mnist b standard carlini 5418
./run_extra.sh mnist b adversarial carlini 5418
./run_extra.sh mnist b relu carlini 5418
./run_extra.sh mnist c standard carlini 5418
