./run_extra.sh mnist c standard carlini 8202
./run_extra.sh mnist c adversarial carlini 8202
./run_extra.sh mnist c relu carlini 8202
./run_extra.sh mnist a standard carlini 4974
./run_extra.sh mnist a adversarial carlini 4974
./run_extra.sh mnist a relu carlini 4974
./run_extra.sh mnist b standard carlini 4974
./run_extra.sh mnist b adversarial carlini 4974
./run_extra.sh mnist b relu carlini 4974
./run_extra.sh mnist c standard carlini 4974
./run_extra.sh mnist c adversarial carlini 4974
./run_extra.sh mnist c relu carlini 4974
./run_extra.sh mnist a standard carlini 1314
./run_extra.sh mnist a adversarial carlini 1314
./run_extra.sh mnist a relu carlini 1314
./run_extra.sh mnist b standard carlini 1314
./run_extra.sh mnist b adversarial carlini 1314
./run_extra.sh mnist b relu carlini 1314
./run_extra.sh mnist c standard carlini 1314
./run_extra.sh mnist c adversarial carlini 1314
./run_extra.sh mnist c relu carlini 1314
./run_extra.sh mnist a standard carlini 2806
./run_extra.sh mnist a adversarial carlini 2806
./run_extra.sh mnist a relu carlini 2806
./run_extra.sh mnist b standard carlini 2806
./run_extra.sh mnist b adversarial carlini 2806
./run_extra.sh mnist b relu carlini 2806
./run_extra.sh mnist c standard carlini 2806
./run_extra.sh mnist c adversarial carlini 2806
./run_extra.sh mnist c relu carlini 2806
./run_extra.sh mnist a standard carlini 1192
./run_extra.sh mnist a adversarial carlini 1192
./run_extra.sh mnist a relu carlini 1192
./run_extra.sh mnist b standard carlini 1192
./run_extra.sh mnist b adversarial carlini 1192
./run_extra.sh mnist b relu carlini 1192
./run_extra.sh mnist c standard carlini 1192
./run_extra.sh mnist c adversarial carlini 1192
./run_extra.sh mnist c relu carlini 1192
./run_extra.sh mnist a standard carlini 5586
./run_extra.sh mnist a adversarial carlini 5586
./run_extra.sh mnist a relu carlini 5586
./run_extra.sh mnist b standard carlini 5586
./run_extra.sh mnist b adversarial carlini 5586
./run_extra.sh mnist b relu carlini 5586
./run_extra.sh mnist c standard carlini 5586
./run_extra.sh mnist c adversarial carlini 5586
./run_extra.sh mnist c relu carlini 5586
./run_extra.sh mnist a standard carlini 6557
./run_extra.sh mnist a adversarial carlini 6557
./run_extra.sh mnist a relu carlini 6557
./run_extra.sh mnist b standard carlini 6557
./run_extra.sh mnist b adversarial carlini 6557
./run_extra.sh mnist b relu carlini 6557
./run_extra.sh mnist c standard carlini 6557
./run_extra.sh mnist c adversarial carlini 6557
./run_extra.sh mnist c relu carlini 6557
./run_extra.sh mnist a standard carlini 2553
./run_extra.sh mnist a adversarial carlini 2553
./run_extra.sh mnist a relu carlini 2553
./run_extra.sh mnist b standard carlini 2553
./run_extra.sh mnist b adversarial carlini 2553
./run_extra.sh mnist b relu carlini 2553
./run_extra.sh mnist c standard carlini 2553
./run_extra.sh mnist c adversarial carlini 2553
./run_extra.sh mnist c relu carlini 2553
./run_extra.sh mnist a standard carlini 1694
./run_extra.sh mnist a adversarial carlini 1694
./run_extra.sh mnist a relu carlini 1694
./run_extra.sh mnist b standard carlini 1694
./run_extra.sh mnist b adversarial carlini 1694
./run_extra.sh mnist b relu carlini 1694
./run_extra.sh mnist c standard carlini 1694
./run_extra.sh mnist c adversarial carlini 1694
./run_extra.sh mnist c relu carlini 1694
./run_extra.sh mnist a standard carlini 7396
./run_extra.sh mnist a adversarial carlini 7396
./run_extra.sh mnist a relu carlini 7396
./run_extra.sh mnist b standard carlini 7396
./run_extra.sh mnist b adversarial carlini 7396
./run_extra.sh mnist b relu carlini 7396
./run_extra.sh mnist c standard carlini 7396
./run_extra.sh mnist c adversarial carlini 7396
./run_extra.sh mnist c relu carlini 7396
./run_extra.sh mnist a standard carlini 2287
./run_extra.sh mnist a adversarial carlini 2287
./run_extra.sh mnist a relu carlini 2287
./run_extra.sh mnist b standard carlini 2287
./run_extra.sh mnist b adversarial carlini 2287
./run_extra.sh mnist b relu carlini 2287
./run_extra.sh mnist c standard carlini 2287
./run_extra.sh mnist c adversarial carlini 2287
./run_extra.sh mnist c relu carlini 2287
./run_extra.sh mnist a standard carlini 6471
./run_extra.sh mnist a adversarial carlini 6471
./run_extra.sh mnist a relu carlini 6471
./run_extra.sh mnist b standard carlini 6471
./run_extra.sh mnist b adversarial carlini 6471
./run_extra.sh mnist b relu carlini 6471
./run_extra.sh mnist c standard carlini 6471
./run_extra.sh mnist c adversarial carlini 6471
./run_extra.sh mnist c relu carlini 6471
./run_extra.sh mnist a standard carlini 3348
./run_extra.sh mnist a adversarial carlini 3348
./run_extra.sh mnist a relu carlini 3348
./run_extra.sh mnist b standard carlini 3348
./run_extra.sh mnist b adversarial carlini 3348
./run_extra.sh mnist b relu carlini 3348
./run_extra.sh mnist c standard carlini 3348
./run_extra.sh mnist c adversarial carlini 3348
./run_extra.sh mnist c relu carlini 3348
./run_extra.sh mnist a standard carlini 1521
./run_extra.sh mnist a adversarial carlini 1521
./run_extra.sh mnist a relu carlini 1521
./run_extra.sh mnist b standard carlini 1521
./run_extra.sh mnist b adversarial carlini 1521
./run_extra.sh mnist b relu carlini 1521
./run_extra.sh mnist c standard carlini 1521
./run_extra.sh mnist c adversarial carlini 1521
./run_extra.sh mnist c relu carlini 1521
./run_extra.sh mnist a standard carlini 4356
./run_extra.sh mnist a adversarial carlini 4356
./run_extra.sh mnist a relu carlini 4356
./run_extra.sh mnist b standard carlini 4356
./run_extra.sh mnist b adversarial carlini 4356
./run_extra.sh mnist b relu carlini 4356
./run_extra.sh mnist c standard carlini 4356
./run_extra.sh mnist c adversarial carlini 4356
./run_extra.sh mnist c relu carlini 4356
./run_extra.sh mnist a standard carlini 3068
./run_extra.sh mnist a adversarial carlini 3068
./run_extra.sh mnist a relu carlini 3068
./run_extra.sh mnist b standard carlini 3068
./run_extra.sh mnist b adversarial carlini 3068
./run_extra.sh mnist b relu carlini 3068
./run_extra.sh mnist c standard carlini 3068
./run_extra.sh mnist c adversarial carlini 3068
./run_extra.sh mnist c relu carlini 3068
./run_extra.sh mnist a standard carlini 5633
./run_extra.sh mnist a adversarial carlini 5633
./run_extra.sh mnist a relu carlini 5633
./run_extra.sh mnist b standard carlini 5633
./run_extra.sh mnist b adversarial carlini 5633
./run_extra.sh mnist b relu carlini 5633
./run_extra.sh mnist c standard carlini 5633
./run_extra.sh mnist c adversarial carlini 5633
./run_extra.sh mnist c relu carlini 5633
./run_extra.sh mnist a standard carlini 2822
./run_extra.sh mnist a adversarial carlini 2822
./run_extra.sh mnist a relu carlini 2822
./run_extra.sh mnist b standard carlini 2822
./run_extra.sh mnist b adversarial carlini 2822
./run_extra.sh mnist b relu carlini 2822
./run_extra.sh mnist c standard carlini 2822
./run_extra.sh mnist c adversarial carlini 2822
./run_extra.sh mnist c relu carlini 2822
./run_extra.sh mnist a standard carlini 3643
./run_extra.sh mnist a adversarial carlini 3643
./run_extra.sh mnist a relu carlini 3643
./run_extra.sh mnist b standard carlini 3643
./run_extra.sh mnist b adversarial carlini 3643
./run_extra.sh mnist b relu carlini 3643
./run_extra.sh mnist c standard carlini 3643
./run_extra.sh mnist c adversarial carlini 3643
./run_extra.sh mnist c relu carlini 3643
./run_extra.sh mnist a standard carlini 5924
./run_extra.sh mnist a adversarial carlini 5924
./run_extra.sh mnist a relu carlini 5924
./run_extra.sh mnist b standard carlini 5924
./run_extra.sh mnist b adversarial carlini 5924
./run_extra.sh mnist b relu carlini 5924
./run_extra.sh mnist c standard carlini 5924
./run_extra.sh mnist c adversarial carlini 5924
./run_extra.sh mnist c relu carlini 5924
./run_extra.sh mnist a standard carlini 1691
./run_extra.sh mnist a adversarial carlini 1691
./run_extra.sh mnist a relu carlini 1691
./run_extra.sh mnist b standard carlini 1691
./run_extra.sh mnist b adversarial carlini 1691
./run_extra.sh mnist b relu carlini 1691
./run_extra.sh mnist c standard carlini 1691
./run_extra.sh mnist c adversarial carlini 1691
./run_extra.sh mnist c relu carlini 1691
./run_extra.sh mnist a standard carlini 3617
./run_extra.sh mnist a adversarial carlini 3617
./run_extra.sh mnist a relu carlini 3617
./run_extra.sh mnist b standard carlini 3617
./run_extra.sh mnist b adversarial carlini 3617
./run_extra.sh mnist b relu carlini 3617
./run_extra.sh mnist c standard carlini 3617
./run_extra.sh mnist c adversarial carlini 3617
./run_extra.sh mnist c relu carlini 3617
./run_extra.sh mnist a standard carlini 6176
./run_extra.sh mnist a adversarial carlini 6176
./run_extra.sh mnist a relu carlini 6176
./run_extra.sh mnist b standard carlini 6176
./run_extra.sh mnist b adversarial carlini 6176
./run_extra.sh mnist b relu carlini 6176
./run_extra.sh mnist c standard carlini 6176
./run_extra.sh mnist c adversarial carlini 6176
./run_extra.sh mnist c relu carlini 6176
./run_extra.sh mnist a standard carlini 1767
./run_extra.sh mnist a adversarial carlini 1767
./run_extra.sh mnist a relu carlini 1767
./run_extra.sh mnist b standard carlini 1767
./run_extra.sh mnist b adversarial carlini 1767
./run_extra.sh mnist b relu carlini 1767
./run_extra.sh mnist c standard carlini 1767
./run_extra.sh mnist c adversarial carlini 1767
./run_extra.sh mnist c relu carlini 1767
./run_extra.sh mnist a standard carlini 2272
./run_extra.sh mnist a adversarial carlini 2272
./run_extra.sh mnist a relu carlini 2272
./run_extra.sh mnist b standard carlini 2272
./run_extra.sh mnist b adversarial carlini 2272
./run_extra.sh mnist b relu carlini 2272
./run_extra.sh mnist c standard carlini 2272
./run_extra.sh mnist c adversarial carlini 2272
./run_extra.sh mnist c relu carlini 2272
./run_extra.sh mnist a standard carlini 8370
./run_extra.sh mnist a adversarial carlini 8370
./run_extra.sh mnist a relu carlini 8370
./run_extra.sh mnist b standard carlini 8370
./run_extra.sh mnist b adversarial carlini 8370
./run_extra.sh mnist b relu carlini 8370
./run_extra.sh mnist c standard carlini 8370
./run_extra.sh mnist c adversarial carlini 8370
./run_extra.sh mnist c relu carlini 8370
./run_extra.sh mnist a standard carlini 1751
./run_extra.sh mnist a adversarial carlini 1751
./run_extra.sh mnist a relu carlini 1751
./run_extra.sh mnist b standard carlini 1751
./run_extra.sh mnist b adversarial carlini 1751
./run_extra.sh mnist b relu carlini 1751
./run_extra.sh mnist c standard carlini 1751
./run_extra.sh mnist c adversarial carlini 1751
./run_extra.sh mnist c relu carlini 1751
./run_extra.sh mnist a standard carlini 8211
./run_extra.sh mnist a adversarial carlini 8211
./run_extra.sh mnist a relu carlini 8211
./run_extra.sh mnist b standard carlini 8211
./run_extra.sh mnist b adversarial carlini 8211
./run_extra.sh mnist b relu carlini 8211
./run_extra.sh mnist c standard carlini 8211
./run_extra.sh mnist c adversarial carlini 8211
./run_extra.sh mnist c relu carlini 8211
./run_extra.sh mnist a standard carlini 3120
./run_extra.sh mnist a adversarial carlini 3120
./run_extra.sh mnist a relu carlini 3120
./run_extra.sh mnist b standard carlini 3120
./run_extra.sh mnist b adversarial carlini 3120
./run_extra.sh mnist b relu carlini 3120
./run_extra.sh mnist c standard carlini 3120
./run_extra.sh mnist c adversarial carlini 3120
./run_extra.sh mnist c relu carlini 3120
./run_extra.sh mnist a standard carlini 4908
./run_extra.sh mnist a adversarial carlini 4908
./run_extra.sh mnist a relu carlini 4908
./run_extra.sh mnist b standard carlini 4908
./run_extra.sh mnist b adversarial carlini 4908
./run_extra.sh mnist b relu carlini 4908
./run_extra.sh mnist c standard carlini 4908
./run_extra.sh mnist c adversarial carlini 4908
./run_extra.sh mnist c relu carlini 4908
./run_extra.sh mnist a standard carlini 3560
./run_extra.sh mnist a adversarial carlini 3560
./run_extra.sh mnist a relu carlini 3560
./run_extra.sh mnist b standard carlini 3560
./run_extra.sh mnist b adversarial carlini 3560
./run_extra.sh mnist b relu carlini 3560
./run_extra.sh mnist c standard carlini 3560
./run_extra.sh mnist c adversarial carlini 3560
./run_extra.sh mnist c relu carlini 3560
./run_extra.sh mnist a standard carlini 9793
./run_extra.sh mnist a adversarial carlini 9793
./run_extra.sh mnist a relu carlini 9793
./run_extra.sh mnist b standard carlini 9793
./run_extra.sh mnist b adversarial carlini 9793
./run_extra.sh mnist b relu carlini 9793
./run_extra.sh mnist c standard carlini 9793
./run_extra.sh mnist c adversarial carlini 9793
./run_extra.sh mnist c relu carlini 9793
./run_extra.sh mnist a standard carlini 5782
./run_extra.sh mnist a adversarial carlini 5782
./run_extra.sh mnist a relu carlini 5782
./run_extra.sh mnist b standard carlini 5782
./run_extra.sh mnist b adversarial carlini 5782
./run_extra.sh mnist b relu carlini 5782
./run_extra.sh mnist c standard carlini 5782
./run_extra.sh mnist c adversarial carlini 5782
./run_extra.sh mnist c relu carlini 5782
./run_extra.sh mnist a standard carlini 6293
./run_extra.sh mnist a adversarial carlini 6293
./run_extra.sh mnist a relu carlini 6293
./run_extra.sh mnist b standard carlini 6293
./run_extra.sh mnist b adversarial carlini 6293
./run_extra.sh mnist b relu carlini 6293
./run_extra.sh mnist c standard carlini 6293
./run_extra.sh mnist c adversarial carlini 6293
./run_extra.sh mnist c relu carlini 6293
./run_extra.sh mnist a standard carlini 2351
./run_extra.sh mnist a adversarial carlini 2351
./run_extra.sh mnist a relu carlini 2351
./run_extra.sh mnist b standard carlini 2351
./run_extra.sh mnist b adversarial carlini 2351
./run_extra.sh mnist b relu carlini 2351
./run_extra.sh mnist c standard carlini 2351
./run_extra.sh mnist c adversarial carlini 2351
./run_extra.sh mnist c relu carlini 2351
./run_extra.sh mnist a standard carlini 5698
./run_extra.sh mnist a adversarial carlini 5698
./run_extra.sh mnist a relu carlini 5698
./run_extra.sh mnist b standard carlini 5698
./run_extra.sh mnist b adversarial carlini 5698
./run_extra.sh mnist b relu carlini 5698
./run_extra.sh mnist c standard carlini 5698
./run_extra.sh mnist c adversarial carlini 5698
./run_extra.sh mnist c relu carlini 5698
./run_extra.sh mnist a standard carlini 2300
./run_extra.sh mnist a adversarial carlini 2300
./run_extra.sh mnist a relu carlini 2300
./run_extra.sh mnist b standard carlini 2300
./run_extra.sh mnist b adversarial carlini 2300
./run_extra.sh mnist b relu carlini 2300
./run_extra.sh mnist c standard carlini 2300
./run_extra.sh mnist c adversarial carlini 2300
./run_extra.sh mnist c relu carlini 2300
./run_extra.sh mnist a standard carlini 3465
./run_extra.sh mnist a adversarial carlini 3465
./run_extra.sh mnist a relu carlini 3465
./run_extra.sh mnist b standard carlini 3465
./run_extra.sh mnist b adversarial carlini 3465
./run_extra.sh mnist b relu carlini 3465
./run_extra.sh mnist c standard carlini 3465
./run_extra.sh mnist c adversarial carlini 3465
./run_extra.sh mnist c relu carlini 3465
./run_extra.sh mnist a standard carlini 4029
./run_extra.sh mnist a adversarial carlini 4029
./run_extra.sh mnist a relu carlini 4029
./run_extra.sh mnist b standard carlini 4029
./run_extra.sh mnist b adversarial carlini 4029
./run_extra.sh mnist b relu carlini 4029
./run_extra.sh mnist c standard carlini 4029
./run_extra.sh mnist c adversarial carlini 4029
./run_extra.sh mnist c relu carlini 4029
./run_extra.sh mnist a standard carlini 4440
./run_extra.sh mnist a adversarial carlini 4440
./run_extra.sh mnist a relu carlini 4440
./run_extra.sh mnist b standard carlini 4440
./run_extra.sh mnist b adversarial carlini 4440
./run_extra.sh mnist b relu carlini 4440
./run_extra.sh mnist c standard carlini 4440
./run_extra.sh mnist c adversarial carlini 4440
./run_extra.sh mnist c relu carlini 4440
./run_extra.sh mnist a standard carlini 1542
./run_extra.sh mnist a adversarial carlini 1542
./run_extra.sh mnist a relu carlini 1542
./run_extra.sh mnist b standard carlini 1542
./run_extra.sh mnist b adversarial carlini 1542
./run_extra.sh mnist b relu carlini 1542
./run_extra.sh mnist c standard carlini 1542
./run_extra.sh mnist c adversarial carlini 1542
./run_extra.sh mnist c relu carlini 1542
./run_extra.sh mnist a standard carlini 9134
./run_extra.sh mnist a adversarial carlini 9134
./run_extra.sh mnist a relu carlini 9134
./run_extra.sh mnist b standard carlini 9134
./run_extra.sh mnist b adversarial carlini 9134
./run_extra.sh mnist b relu carlini 9134
./run_extra.sh mnist c standard carlini 9134
./run_extra.sh mnist c adversarial carlini 9134
./run_extra.sh mnist c relu carlini 9134
./run_extra.sh mnist a standard carlini 6818
./run_extra.sh mnist a adversarial carlini 6818
./run_extra.sh mnist a relu carlini 6818
./run_extra.sh mnist b standard carlini 6818
./run_extra.sh mnist b adversarial carlini 6818
./run_extra.sh mnist b relu carlini 6818
./run_extra.sh mnist c standard carlini 6818
./run_extra.sh mnist c adversarial carlini 6818
./run_extra.sh mnist c relu carlini 6818
./run_extra.sh mnist a standard carlini 4814
./run_extra.sh mnist a adversarial carlini 4814
./run_extra.sh mnist a relu carlini 4814
./run_extra.sh mnist b standard carlini 4814
./run_extra.sh mnist b adversarial carlini 4814
./run_extra.sh mnist b relu carlini 4814
./run_extra.sh mnist c standard carlini 4814
./run_extra.sh mnist c adversarial carlini 4814
./run_extra.sh mnist c relu carlini 4814
./run_extra.sh mnist a standard carlini 4929
./run_extra.sh mnist a adversarial carlini 4929
./run_extra.sh mnist a relu carlini 4929
./run_extra.sh mnist b standard carlini 4929
./run_extra.sh mnist b adversarial carlini 4929
./run_extra.sh mnist b relu carlini 4929
./run_extra.sh mnist c standard carlini 4929
./run_extra.sh mnist c adversarial carlini 4929
./run_extra.sh mnist c relu carlini 4929
./run_extra.sh mnist a standard carlini 4588
./run_extra.sh mnist a adversarial carlini 4588
./run_extra.sh mnist a relu carlini 4588
./run_extra.sh mnist b standard carlini 4588
./run_extra.sh mnist b adversarial carlini 4588
./run_extra.sh mnist b relu carlini 4588
./run_extra.sh mnist c standard carlini 4588
./run_extra.sh mnist c adversarial carlini 4588
./run_extra.sh mnist c relu carlini 4588
./run_extra.sh mnist a standard carlini 6295
./run_extra.sh mnist a adversarial carlini 6295
./run_extra.sh mnist a relu carlini 6295
./run_extra.sh mnist b standard carlini 6295
./run_extra.sh mnist b adversarial carlini 6295
./run_extra.sh mnist b relu carlini 6295
./run_extra.sh mnist c standard carlini 6295
./run_extra.sh mnist c adversarial carlini 6295
./run_extra.sh mnist c relu carlini 6295
./run_extra.sh mnist a standard carlini 9876
./run_extra.sh mnist a adversarial carlini 9876
./run_extra.sh mnist a relu carlini 9876
./run_extra.sh mnist b standard carlini 9876
./run_extra.sh mnist b adversarial carlini 9876
./run_extra.sh mnist b relu carlini 9876
./run_extra.sh mnist c standard carlini 9876
./run_extra.sh mnist c adversarial carlini 9876
./run_extra.sh mnist c relu carlini 9876
./run_extra.sh mnist a standard carlini 6825
./run_extra.sh mnist a adversarial carlini 6825
./run_extra.sh mnist a relu carlini 6825
./run_extra.sh mnist b standard carlini 6825
./run_extra.sh mnist b adversarial carlini 6825
./run_extra.sh mnist b relu carlini 6825
./run_extra.sh mnist c standard carlini 6825
./run_extra.sh mnist c adversarial carlini 6825
./run_extra.sh mnist c relu carlini 6825
./run_extra.sh mnist a standard carlini 9980
./run_extra.sh mnist a adversarial carlini 9980
./run_extra.sh mnist a relu carlini 9980
./run_extra.sh mnist b standard carlini 9980
./run_extra.sh mnist b adversarial carlini 9980
./run_extra.sh mnist b relu carlini 9980
./run_extra.sh mnist c standard carlini 9980
./run_extra.sh mnist c adversarial carlini 9980
./run_extra.sh mnist c relu carlini 9980
./run_extra.sh mnist a standard carlini 6838
./run_extra.sh mnist a adversarial carlini 6838
./run_extra.sh mnist a relu carlini 6838
./run_extra.sh mnist b standard carlini 6838
./run_extra.sh mnist b adversarial carlini 6838
./run_extra.sh mnist b relu carlini 6838
./run_extra.sh mnist c standard carlini 6838
./run_extra.sh mnist c adversarial carlini 6838
./run_extra.sh mnist c relu carlini 6838
./run_extra.sh mnist a standard carlini 6741
./run_extra.sh mnist a adversarial carlini 6741
./run_extra.sh mnist a relu carlini 6741
./run_extra.sh mnist b standard carlini 6741
./run_extra.sh mnist b adversarial carlini 6741
./run_extra.sh mnist b relu carlini 6741
./run_extra.sh mnist c standard carlini 6741
./run_extra.sh mnist c adversarial carlini 6741
./run_extra.sh mnist c relu carlini 6741
./run_extra.sh mnist a standard carlini 1008
./run_extra.sh mnist a adversarial carlini 1008
./run_extra.sh mnist a relu carlini 1008
./run_extra.sh mnist b standard carlini 1008
./run_extra.sh mnist b adversarial carlini 1008
./run_extra.sh mnist b relu carlini 1008
./run_extra.sh mnist c standard carlini 1008
./run_extra.sh mnist c adversarial carlini 1008
./run_extra.sh mnist c relu carlini 1008
./run_extra.sh mnist a standard carlini 4295
./run_extra.sh mnist a adversarial carlini 4295
./run_extra.sh mnist a relu carlini 4295
./run_extra.sh mnist b standard carlini 4295
./run_extra.sh mnist b adversarial carlini 4295
./run_extra.sh mnist b relu carlini 4295
./run_extra.sh mnist c standard carlini 4295
./run_extra.sh mnist c adversarial carlini 4295
./run_extra.sh mnist c relu carlini 4295
./run_extra.sh mnist a standard carlini 4587
./run_extra.sh mnist a adversarial carlini 4587
./run_extra.sh mnist a relu carlini 4587
./run_extra.sh mnist b standard carlini 4587
./run_extra.sh mnist b adversarial carlini 4587
./run_extra.sh mnist b relu carlini 4587
./run_extra.sh mnist c standard carlini 4587
./run_extra.sh mnist c adversarial carlini 4587
./run_extra.sh mnist c relu carlini 4587
./run_extra.sh mnist a standard carlini 2325
./run_extra.sh mnist a adversarial carlini 2325
./run_extra.sh mnist a relu carlini 2325
./run_extra.sh mnist b standard carlini 2325
./run_extra.sh mnist b adversarial carlini 2325
./run_extra.sh mnist b relu carlini 2325
./run_extra.sh mnist c standard carlini 2325
./run_extra.sh mnist c adversarial carlini 2325
./run_extra.sh mnist c relu carlini 2325
./run_extra.sh mnist a standard carlini 4566
./run_extra.sh mnist a adversarial carlini 4566
./run_extra.sh mnist a relu carlini 4566
./run_extra.sh mnist b standard carlini 4566
./run_extra.sh mnist b adversarial carlini 4566
./run_extra.sh mnist b relu carlini 4566
./run_extra.sh mnist c standard carlini 4566
./run_extra.sh mnist c adversarial carlini 4566
./run_extra.sh mnist c relu carlini 4566
./run_extra.sh mnist a standard carlini 2797
./run_extra.sh mnist a adversarial carlini 2797
./run_extra.sh mnist a relu carlini 2797
./run_extra.sh mnist b standard carlini 2797
./run_extra.sh mnist b adversarial carlini 2797
./run_extra.sh mnist b relu carlini 2797
./run_extra.sh mnist c standard carlini 2797
./run_extra.sh mnist c adversarial carlini 2797
./run_extra.sh mnist c relu carlini 2797
./run_extra.sh mnist a standard carlini 1459
./run_extra.sh mnist a adversarial carlini 1459
./run_extra.sh mnist a relu carlini 1459
./run_extra.sh mnist b standard carlini 1459
./run_extra.sh mnist b adversarial carlini 1459
./run_extra.sh mnist b relu carlini 1459
./run_extra.sh mnist c standard carlini 1459
./run_extra.sh mnist c adversarial carlini 1459
./run_extra.sh mnist c relu carlini 1459
./run_extra.sh mnist a standard carlini 3928
./run_extra.sh mnist a adversarial carlini 3928
./run_extra.sh mnist a relu carlini 3928
./run_extra.sh mnist b standard carlini 3928
./run_extra.sh mnist b adversarial carlini 3928
./run_extra.sh mnist b relu carlini 3928
./run_extra.sh mnist c standard carlini 3928
./run_extra.sh mnist c adversarial carlini 3928
./run_extra.sh mnist c relu carlini 3928
./run_extra.sh mnist a standard carlini 6490
./run_extra.sh mnist a adversarial carlini 6490
./run_extra.sh mnist a relu carlini 6490
./run_extra.sh mnist b standard carlini 6490
./run_extra.sh mnist b adversarial carlini 6490
./run_extra.sh mnist b relu carlini 6490
./run_extra.sh mnist c standard carlini 6490
./run_extra.sh mnist c adversarial carlini 6490
./run_extra.sh mnist c relu carlini 6490
./run_extra.sh mnist a standard carlini 5950
./run_extra.sh mnist a adversarial carlini 5950
./run_extra.sh mnist a relu carlini 5950
./run_extra.sh mnist b standard carlini 5950
./run_extra.sh mnist b adversarial carlini 5950
./run_extra.sh mnist b relu carlini 5950
./run_extra.sh mnist c standard carlini 5950
./run_extra.sh mnist c adversarial carlini 5950
./run_extra.sh mnist c relu carlini 5950
./run_extra.sh mnist a standard carlini 6269
./run_extra.sh mnist a adversarial carlini 6269
./run_extra.sh mnist a relu carlini 6269
./run_extra.sh mnist b standard carlini 6269
./run_extra.sh mnist b adversarial carlini 6269
./run_extra.sh mnist b relu carlini 6269
./run_extra.sh mnist c standard carlini 6269
./run_extra.sh mnist c adversarial carlini 6269
./run_extra.sh mnist c relu carlini 6269
./run_extra.sh mnist a standard carlini 3879
./run_extra.sh mnist a adversarial carlini 3879
./run_extra.sh mnist a relu carlini 3879
./run_extra.sh mnist b standard carlini 3879
./run_extra.sh mnist b adversarial carlini 3879
./run_extra.sh mnist b relu carlini 3879
./run_extra.sh mnist c standard carlini 3879
./run_extra.sh mnist c adversarial carlini 3879
./run_extra.sh mnist c relu carlini 3879
./run_extra.sh mnist a standard carlini 6198
./run_extra.sh mnist a adversarial carlini 6198
./run_extra.sh mnist a relu carlini 6198
./run_extra.sh mnist b standard carlini 6198
./run_extra.sh mnist b adversarial carlini 6198
./run_extra.sh mnist b relu carlini 6198
./run_extra.sh mnist c standard carlini 6198
./run_extra.sh mnist c adversarial carlini 6198
./run_extra.sh mnist c relu carlini 6198
./run_extra.sh mnist a standard carlini 8844
./run_extra.sh mnist a adversarial carlini 8844
./run_extra.sh mnist a relu carlini 8844
./run_extra.sh mnist b standard carlini 8844
./run_extra.sh mnist b adversarial carlini 8844
./run_extra.sh mnist b relu carlini 8844
./run_extra.sh mnist c standard carlini 8844
./run_extra.sh mnist c adversarial carlini 8844
./run_extra.sh mnist c relu carlini 8844
./run_extra.sh mnist a standard carlini 7107
./run_extra.sh mnist a adversarial carlini 7107
./run_extra.sh mnist a relu carlini 7107
./run_extra.sh mnist b standard carlini 7107
./run_extra.sh mnist b adversarial carlini 7107
./run_extra.sh mnist b relu carlini 7107
./run_extra.sh mnist c standard carlini 7107
./run_extra.sh mnist c adversarial carlini 7107
./run_extra.sh mnist c relu carlini 7107
./run_extra.sh mnist a standard carlini 5424
./run_extra.sh mnist a adversarial carlini 5424
./run_extra.sh mnist a relu carlini 5424
./run_extra.sh mnist b standard carlini 5424
./run_extra.sh mnist b adversarial carlini 5424
./run_extra.sh mnist b relu carlini 5424
./run_extra.sh mnist c standard carlini 5424
./run_extra.sh mnist c adversarial carlini 5424
./run_extra.sh mnist c relu carlini 5424
./run_extra.sh mnist a standard carlini 358
./run_extra.sh mnist a adversarial carlini 358
./run_extra.sh mnist a relu carlini 358
./run_extra.sh mnist b standard carlini 358
./run_extra.sh mnist b adversarial carlini 358
./run_extra.sh mnist b relu carlini 358
./run_extra.sh mnist c standard carlini 358
./run_extra.sh mnist c adversarial carlini 358
./run_extra.sh mnist c relu carlini 358
./run_extra.sh mnist a standard carlini 1740
./run_extra.sh mnist a adversarial carlini 1740
./run_extra.sh mnist a relu carlini 1740
./run_extra.sh mnist b standard carlini 1740
./run_extra.sh mnist b adversarial carlini 1740
./run_extra.sh mnist b relu carlini 1740
./run_extra.sh mnist c standard carlini 1740
./run_extra.sh mnist c adversarial carlini 1740
./run_extra.sh mnist c relu carlini 1740
./run_extra.sh mnist a standard carlini 6641
./run_extra.sh mnist a adversarial carlini 6641
./run_extra.sh mnist a relu carlini 6641
./run_extra.sh mnist b standard carlini 6641
./run_extra.sh mnist b adversarial carlini 6641
./run_extra.sh mnist b relu carlini 6641
./run_extra.sh mnist c standard carlini 6641
./run_extra.sh mnist c adversarial carlini 6641
./run_extra.sh mnist c relu carlini 6641
./run_extra.sh mnist a standard carlini 6850
./run_extra.sh mnist a adversarial carlini 6850
./run_extra.sh mnist a relu carlini 6850
./run_extra.sh mnist b standard carlini 6850
./run_extra.sh mnist b adversarial carlini 6850
./run_extra.sh mnist b relu carlini 6850
./run_extra.sh mnist c standard carlini 6850
./run_extra.sh mnist c adversarial carlini 6850
./run_extra.sh mnist c relu carlini 6850
./run_extra.sh mnist a standard carlini 6241
./run_extra.sh mnist a adversarial carlini 6241
./run_extra.sh mnist a relu carlini 6241
./run_extra.sh mnist b standard carlini 6241
./run_extra.sh mnist b adversarial carlini 6241
./run_extra.sh mnist b relu carlini 6241
./run_extra.sh mnist c standard carlini 6241
./run_extra.sh mnist c adversarial carlini 6241
./run_extra.sh mnist c relu carlini 6241
./run_extra.sh mnist a standard carlini 1919
./run_extra.sh mnist a adversarial carlini 1919
./run_extra.sh mnist a relu carlini 1919
./run_extra.sh mnist b standard carlini 1919
./run_extra.sh mnist b adversarial carlini 1919
./run_extra.sh mnist b relu carlini 1919
./run_extra.sh mnist c standard carlini 1919
./run_extra.sh mnist c adversarial carlini 1919
./run_extra.sh mnist c relu carlini 1919
./run_extra.sh mnist a standard carlini 9368
./run_extra.sh mnist a adversarial carlini 9368
./run_extra.sh mnist a relu carlini 9368
./run_extra.sh mnist b standard carlini 9368
./run_extra.sh mnist b adversarial carlini 9368
./run_extra.sh mnist b relu carlini 9368
./run_extra.sh mnist c standard carlini 9368
./run_extra.sh mnist c adversarial carlini 9368
./run_extra.sh mnist c relu carlini 9368
./run_extra.sh mnist a standard carlini 1858
./run_extra.sh mnist a adversarial carlini 1858
./run_extra.sh mnist a relu carlini 1858
./run_extra.sh mnist b standard carlini 1858
./run_extra.sh mnist b adversarial carlini 1858
./run_extra.sh mnist b relu carlini 1858
./run_extra.sh mnist c standard carlini 1858
./run_extra.sh mnist c adversarial carlini 1858
./run_extra.sh mnist c relu carlini 1858
./run_extra.sh mnist a standard carlini 2732
./run_extra.sh mnist a adversarial carlini 2732
./run_extra.sh mnist a relu carlini 2732
./run_extra.sh mnist b standard carlini 2732
./run_extra.sh mnist b adversarial carlini 2732
./run_extra.sh mnist b relu carlini 2732
./run_extra.sh mnist c standard carlini 2732
./run_extra.sh mnist c adversarial carlini 2732
./run_extra.sh mnist c relu carlini 2732
./run_extra.sh mnist a standard carlini 1701
./run_extra.sh mnist a adversarial carlini 1701
./run_extra.sh mnist a relu carlini 1701
./run_extra.sh mnist b standard carlini 1701
./run_extra.sh mnist b adversarial carlini 1701
./run_extra.sh mnist b relu carlini 1701
./run_extra.sh mnist c standard carlini 1701
./run_extra.sh mnist c adversarial carlini 1701
./run_extra.sh mnist c relu carlini 1701
./run_extra.sh mnist a standard carlini 311
./run_extra.sh mnist a adversarial carlini 311
./run_extra.sh mnist a relu carlini 311
./run_extra.sh mnist b standard carlini 311
./run_extra.sh mnist b adversarial carlini 311
./run_extra.sh mnist b relu carlini 311
./run_extra.sh mnist c standard carlini 311
./run_extra.sh mnist c adversarial carlini 311
./run_extra.sh mnist c relu carlini 311
./run_extra.sh mnist a standard carlini 7979
./run_extra.sh mnist a adversarial carlini 7979
./run_extra.sh mnist a relu carlini 7979
./run_extra.sh mnist b standard carlini 7979
./run_extra.sh mnist b adversarial carlini 7979
./run_extra.sh mnist b relu carlini 7979
./run_extra.sh mnist c standard carlini 7979
./run_extra.sh mnist c adversarial carlini 7979
./run_extra.sh mnist c relu carlini 7979
./run_extra.sh mnist a standard carlini 7765
./run_extra.sh mnist a adversarial carlini 7765
./run_extra.sh mnist a relu carlini 7765
./run_extra.sh mnist b standard carlini 7765
./run_extra.sh mnist b adversarial carlini 7765
./run_extra.sh mnist b relu carlini 7765
./run_extra.sh mnist c standard carlini 7765
./run_extra.sh mnist c adversarial carlini 7765
./run_extra.sh mnist c relu carlini 7765
./run_extra.sh mnist a standard carlini 3964
./run_extra.sh mnist a adversarial carlini 3964
./run_extra.sh mnist a relu carlini 3964
./run_extra.sh mnist b standard carlini 3964
./run_extra.sh mnist b adversarial carlini 3964
./run_extra.sh mnist b relu carlini 3964
./run_extra.sh mnist c standard carlini 3964
./run_extra.sh mnist c adversarial carlini 3964
./run_extra.sh mnist c relu carlini 3964
./run_extra.sh mnist a standard carlini 7791
./run_extra.sh mnist a adversarial carlini 7791
./run_extra.sh mnist a relu carlini 7791
./run_extra.sh mnist b standard carlini 7791
./run_extra.sh mnist b adversarial carlini 7791
./run_extra.sh mnist b relu carlini 7791
./run_extra.sh mnist c standard carlini 7791
./run_extra.sh mnist c adversarial carlini 7791
./run_extra.sh mnist c relu carlini 7791
./run_extra.sh mnist a standard carlini 4867
./run_extra.sh mnist a adversarial carlini 4867
./run_extra.sh mnist a relu carlini 4867
./run_extra.sh mnist b standard carlini 4867
./run_extra.sh mnist b adversarial carlini 4867
./run_extra.sh mnist b relu carlini 4867
./run_extra.sh mnist c standard carlini 4867
./run_extra.sh mnist c adversarial carlini 4867
./run_extra.sh mnist c relu carlini 4867
./run_extra.sh mnist a standard carlini 9207
./run_extra.sh mnist a adversarial carlini 9207
./run_extra.sh mnist a relu carlini 9207
./run_extra.sh mnist b standard carlini 9207
./run_extra.sh mnist b adversarial carlini 9207
./run_extra.sh mnist b relu carlini 9207
./run_extra.sh mnist c standard carlini 9207
./run_extra.sh mnist c adversarial carlini 9207
./run_extra.sh mnist c relu carlini 9207
./run_extra.sh mnist a standard carlini 6235
./run_extra.sh mnist a adversarial carlini 6235
./run_extra.sh mnist a relu carlini 6235
./run_extra.sh mnist b standard carlini 6235
./run_extra.sh mnist b adversarial carlini 6235
./run_extra.sh mnist b relu carlini 6235
./run_extra.sh mnist c standard carlini 6235
./run_extra.sh mnist c adversarial carlini 6235
./run_extra.sh mnist c relu carlini 6235
./run_extra.sh mnist a standard carlini 5112
./run_extra.sh mnist a adversarial carlini 5112
./run_extra.sh mnist a relu carlini 5112
./run_extra.sh mnist b standard carlini 5112
./run_extra.sh mnist b adversarial carlini 5112
./run_extra.sh mnist b relu carlini 5112
./run_extra.sh mnist c standard carlini 5112
./run_extra.sh mnist c adversarial carlini 5112
./run_extra.sh mnist c relu carlini 5112
./run_extra.sh mnist a standard carlini 6485
./run_extra.sh mnist a adversarial carlini 6485
./run_extra.sh mnist a relu carlini 6485
./run_extra.sh mnist b standard carlini 6485
./run_extra.sh mnist b adversarial carlini 6485
./run_extra.sh mnist b relu carlini 6485
./run_extra.sh mnist c standard carlini 6485
./run_extra.sh mnist c adversarial carlini 6485
./run_extra.sh mnist c relu carlini 6485
./run_extra.sh mnist a standard carlini 4986
./run_extra.sh mnist a adversarial carlini 4986
./run_extra.sh mnist a relu carlini 4986
./run_extra.sh mnist b standard carlini 4986
./run_extra.sh mnist b adversarial carlini 4986
./run_extra.sh mnist b relu carlini 4986
./run_extra.sh mnist c standard carlini 4986
./run_extra.sh mnist c adversarial carlini 4986
./run_extra.sh mnist c relu carlini 4986
./run_extra.sh mnist a standard carlini 6326
./run_extra.sh mnist a adversarial carlini 6326
./run_extra.sh mnist a relu carlini 6326
./run_extra.sh mnist b standard carlini 6326
./run_extra.sh mnist b adversarial carlini 6326
./run_extra.sh mnist b relu carlini 6326
./run_extra.sh mnist c standard carlini 6326
./run_extra.sh mnist c adversarial carlini 6326
./run_extra.sh mnist c relu carlini 6326
./run_extra.sh mnist a standard carlini 7906
./run_extra.sh mnist a adversarial carlini 7906
./run_extra.sh mnist a relu carlini 7906
./run_extra.sh mnist b standard carlini 7906
./run_extra.sh mnist b adversarial carlini 7906
./run_extra.sh mnist b relu carlini 7906
./run_extra.sh mnist c standard carlini 7906
./run_extra.sh mnist c adversarial carlini 7906
./run_extra.sh mnist c relu carlini 7906
./run_extra.sh mnist a standard carlini 3201
./run_extra.sh mnist a adversarial carlini 3201
./run_extra.sh mnist a relu carlini 3201
./run_extra.sh mnist b standard carlini 3201
./run_extra.sh mnist b adversarial carlini 3201
./run_extra.sh mnist b relu carlini 3201
./run_extra.sh mnist c standard carlini 3201
./run_extra.sh mnist c adversarial carlini 3201
./run_extra.sh mnist c relu carlini 3201
./run_extra.sh mnist a standard carlini 3314
./run_extra.sh mnist a adversarial carlini 3314
./run_extra.sh mnist a relu carlini 3314
./run_extra.sh mnist b standard carlini 3314
./run_extra.sh mnist b adversarial carlini 3314
./run_extra.sh mnist b relu carlini 3314
./run_extra.sh mnist c standard carlini 3314
./run_extra.sh mnist c adversarial carlini 3314
./run_extra.sh mnist c relu carlini 3314
./run_extra.sh mnist a standard carlini 7399
./run_extra.sh mnist a adversarial carlini 7399
./run_extra.sh mnist a relu carlini 7399
./run_extra.sh mnist b standard carlini 7399
./run_extra.sh mnist b adversarial carlini 7399
./run_extra.sh mnist b relu carlini 7399
./run_extra.sh mnist c standard carlini 7399
./run_extra.sh mnist c adversarial carlini 7399
./run_extra.sh mnist c relu carlini 7399
./run_extra.sh mnist a standard carlini 3372
./run_extra.sh mnist a adversarial carlini 3372
./run_extra.sh mnist a relu carlini 3372
./run_extra.sh mnist b standard carlini 3372
./run_extra.sh mnist b adversarial carlini 3372
./run_extra.sh mnist b relu carlini 3372
./run_extra.sh mnist c standard carlini 3372
./run_extra.sh mnist c adversarial carlini 3372
./run_extra.sh mnist c relu carlini 3372
./run_extra.sh mnist a standard carlini 919
./run_extra.sh mnist a adversarial carlini 919
./run_extra.sh mnist a relu carlini 919
./run_extra.sh mnist b standard carlini 919
./run_extra.sh mnist b adversarial carlini 919
./run_extra.sh mnist b relu carlini 919
./run_extra.sh mnist c standard carlini 919
./run_extra.sh mnist c adversarial carlini 919
./run_extra.sh mnist c relu carlini 919
./run_extra.sh mnist a standard carlini 9745
./run_extra.sh mnist a adversarial carlini 9745
./run_extra.sh mnist a relu carlini 9745
./run_extra.sh mnist b standard carlini 9745
./run_extra.sh mnist b adversarial carlini 9745
./run_extra.sh mnist b relu carlini 9745
./run_extra.sh mnist c standard carlini 9745
./run_extra.sh mnist c adversarial carlini 9745
./run_extra.sh mnist c relu carlini 9745
./run_extra.sh mnist a standard carlini 3147
./run_extra.sh mnist a adversarial carlini 3147
./run_extra.sh mnist a relu carlini 3147
./run_extra.sh mnist b standard carlini 3147
./run_extra.sh mnist b adversarial carlini 3147
./run_extra.sh mnist b relu carlini 3147
./run_extra.sh mnist c standard carlini 3147
./run_extra.sh mnist c adversarial carlini 3147
./run_extra.sh mnist c relu carlini 3147
./run_extra.sh mnist a standard carlini 8779
./run_extra.sh mnist a adversarial carlini 8779
./run_extra.sh mnist a relu carlini 8779
./run_extra.sh mnist b standard carlini 8779
./run_extra.sh mnist b adversarial carlini 8779
./run_extra.sh mnist b relu carlini 8779
./run_extra.sh mnist c standard carlini 8779
./run_extra.sh mnist c adversarial carlini 8779
./run_extra.sh mnist c relu carlini 8779
./run_extra.sh mnist a standard carlini 2383
./run_extra.sh mnist a adversarial carlini 2383
./run_extra.sh mnist a relu carlini 2383
./run_extra.sh mnist b standard carlini 2383
./run_extra.sh mnist b adversarial carlini 2383
./run_extra.sh mnist b relu carlini 2383
./run_extra.sh mnist c standard carlini 2383
./run_extra.sh mnist c adversarial carlini 2383
./run_extra.sh mnist c relu carlini 2383
./run_extra.sh mnist a standard carlini 3976
./run_extra.sh mnist a adversarial carlini 3976
./run_extra.sh mnist a relu carlini 3976
./run_extra.sh mnist b standard carlini 3976
./run_extra.sh mnist b adversarial carlini 3976
./run_extra.sh mnist b relu carlini 3976
./run_extra.sh mnist c standard carlini 3976
./run_extra.sh mnist c adversarial carlini 3976
./run_extra.sh mnist c relu carlini 3976
./run_extra.sh mnist a standard carlini 4071
./run_extra.sh mnist a adversarial carlini 4071
./run_extra.sh mnist a relu carlini 4071
./run_extra.sh mnist b standard carlini 4071
./run_extra.sh mnist b adversarial carlini 4071
./run_extra.sh mnist b relu carlini 4071
./run_extra.sh mnist c standard carlini 4071
./run_extra.sh mnist c adversarial carlini 4071
./run_extra.sh mnist c relu carlini 4071
./run_extra.sh mnist a standard carlini 4432
./run_extra.sh mnist a adversarial carlini 4432
./run_extra.sh mnist a relu carlini 4432
./run_extra.sh mnist b standard carlini 4432
./run_extra.sh mnist b adversarial carlini 4432
./run_extra.sh mnist b relu carlini 4432
./run_extra.sh mnist c standard carlini 4432
./run_extra.sh mnist c adversarial carlini 4432
./run_extra.sh mnist c relu carlini 4432
./run_extra.sh mnist a standard carlini 829
./run_extra.sh mnist a adversarial carlini 829
./run_extra.sh mnist a relu carlini 829
./run_extra.sh mnist b standard carlini 829
./run_extra.sh mnist b adversarial carlini 829
./run_extra.sh mnist b relu carlini 829
./run_extra.sh mnist c standard carlini 829
./run_extra.sh mnist c adversarial carlini 829
./run_extra.sh mnist c relu carlini 829
./run_extra.sh mnist a standard carlini 5751
./run_extra.sh mnist a adversarial carlini 5751
./run_extra.sh mnist a relu carlini 5751
./run_extra.sh mnist b standard carlini 5751
./run_extra.sh mnist b adversarial carlini 5751
./run_extra.sh mnist b relu carlini 5751
./run_extra.sh mnist c standard carlini 5751
./run_extra.sh mnist c adversarial carlini 5751
./run_extra.sh mnist c relu carlini 5751
./run_extra.sh mnist a standard carlini 6018
./run_extra.sh mnist a adversarial carlini 6018
./run_extra.sh mnist a relu carlini 6018
./run_extra.sh mnist b standard carlini 6018
./run_extra.sh mnist b adversarial carlini 6018
./run_extra.sh mnist b relu carlini 6018
./run_extra.sh mnist c standard carlini 6018
./run_extra.sh mnist c adversarial carlini 6018
./run_extra.sh mnist c relu carlini 6018
./run_extra.sh mnist a standard carlini 7425
./run_extra.sh mnist a adversarial carlini 7425
./run_extra.sh mnist a relu carlini 7425
./run_extra.sh mnist b standard carlini 7425
./run_extra.sh mnist b adversarial carlini 7425
./run_extra.sh mnist b relu carlini 7425
./run_extra.sh mnist c standard carlini 7425
./run_extra.sh mnist c adversarial carlini 7425
./run_extra.sh mnist c relu carlini 7425
./run_extra.sh mnist a standard carlini 9287
./run_extra.sh mnist a adversarial carlini 9287
./run_extra.sh mnist a relu carlini 9287
./run_extra.sh mnist b standard carlini 9287
./run_extra.sh mnist b adversarial carlini 9287
./run_extra.sh mnist b relu carlini 9287
./run_extra.sh mnist c standard carlini 9287
./run_extra.sh mnist c adversarial carlini 9287
./run_extra.sh mnist c relu carlini 9287
./run_extra.sh mnist a standard carlini 384
./run_extra.sh mnist a adversarial carlini 384
./run_extra.sh mnist a relu carlini 384
./run_extra.sh mnist b standard carlini 384
./run_extra.sh mnist b adversarial carlini 384
./run_extra.sh mnist b relu carlini 384
./run_extra.sh mnist c standard carlini 384
./run_extra.sh mnist c adversarial carlini 384
./run_extra.sh mnist c relu carlini 384
./run_extra.sh mnist a standard carlini 8977
./run_extra.sh mnist a adversarial carlini 8977
./run_extra.sh mnist a relu carlini 8977
./run_extra.sh mnist b standard carlini 8977
./run_extra.sh mnist b adversarial carlini 8977
./run_extra.sh mnist b relu carlini 8977
./run_extra.sh mnist c standard carlini 8977
./run_extra.sh mnist c adversarial carlini 8977
./run_extra.sh mnist c relu carlini 8977
./run_extra.sh mnist a standard carlini 448
./run_extra.sh mnist a adversarial carlini 448
./run_extra.sh mnist a relu carlini 448
./run_extra.sh mnist b standard carlini 448
./run_extra.sh mnist b adversarial carlini 448
./run_extra.sh mnist b relu carlini 448
./run_extra.sh mnist c standard carlini 448
./run_extra.sh mnist c adversarial carlini 448
./run_extra.sh mnist c relu carlini 448
./run_extra.sh mnist a standard carlini 6224
./run_extra.sh mnist a adversarial carlini 6224
./run_extra.sh mnist a relu carlini 6224
./run_extra.sh mnist b standard carlini 6224
./run_extra.sh mnist b adversarial carlini 6224
./run_extra.sh mnist b relu carlini 6224
./run_extra.sh mnist c standard carlini 6224
./run_extra.sh mnist c adversarial carlini 6224
./run_extra.sh mnist c relu carlini 6224
./run_extra.sh mnist a standard carlini 8653
./run_extra.sh mnist a adversarial carlini 8653
./run_extra.sh mnist a relu carlini 8653
./run_extra.sh mnist b standard carlini 8653
./run_extra.sh mnist b adversarial carlini 8653
./run_extra.sh mnist b relu carlini 8653
./run_extra.sh mnist c standard carlini 8653
./run_extra.sh mnist c adversarial carlini 8653
./run_extra.sh mnist c relu carlini 8653
./run_extra.sh mnist a standard carlini 6186
./run_extra.sh mnist a adversarial carlini 6186
./run_extra.sh mnist a relu carlini 6186
./run_extra.sh mnist b standard carlini 6186
./run_extra.sh mnist b adversarial carlini 6186
./run_extra.sh mnist b relu carlini 6186
./run_extra.sh mnist c standard carlini 6186
./run_extra.sh mnist c adversarial carlini 6186
./run_extra.sh mnist c relu carlini 6186
./run_extra.sh mnist a standard carlini 8347
./run_extra.sh mnist a adversarial carlini 8347
./run_extra.sh mnist a relu carlini 8347
./run_extra.sh mnist b standard carlini 8347
./run_extra.sh mnist b adversarial carlini 8347
./run_extra.sh mnist b relu carlini 8347
./run_extra.sh mnist c standard carlini 8347
./run_extra.sh mnist c adversarial carlini 8347
./run_extra.sh mnist c relu carlini 8347
./run_extra.sh mnist a standard carlini 6615
./run_extra.sh mnist a adversarial carlini 6615
./run_extra.sh mnist a relu carlini 6615
./run_extra.sh mnist b standard carlini 6615
./run_extra.sh mnist b adversarial carlini 6615
./run_extra.sh mnist b relu carlini 6615
./run_extra.sh mnist c standard carlini 6615
./run_extra.sh mnist c adversarial carlini 6615
./run_extra.sh mnist c relu carlini 6615
./run_extra.sh mnist a standard carlini 302
./run_extra.sh mnist a adversarial carlini 302
./run_extra.sh mnist a relu carlini 302
./run_extra.sh mnist b standard carlini 302
./run_extra.sh mnist b adversarial carlini 302
./run_extra.sh mnist b relu carlini 302
./run_extra.sh mnist c standard carlini 302
./run_extra.sh mnist c adversarial carlini 302
./run_extra.sh mnist c relu carlini 302
./run_extra.sh mnist a standard carlini 6973
./run_extra.sh mnist a adversarial carlini 6973
./run_extra.sh mnist a relu carlini 6973
./run_extra.sh mnist b standard carlini 6973
./run_extra.sh mnist b adversarial carlini 6973
./run_extra.sh mnist b relu carlini 6973
./run_extra.sh mnist c standard carlini 6973
./run_extra.sh mnist c adversarial carlini 6973
./run_extra.sh mnist c relu carlini 6973
./run_extra.sh mnist a standard carlini 2532
./run_extra.sh mnist a adversarial carlini 2532
./run_extra.sh mnist a relu carlini 2532
./run_extra.sh mnist b standard carlini 2532
./run_extra.sh mnist b adversarial carlini 2532
./run_extra.sh mnist b relu carlini 2532
./run_extra.sh mnist c standard carlini 2532
./run_extra.sh mnist c adversarial carlini 2532
./run_extra.sh mnist c relu carlini 2532
./run_extra.sh mnist a standard carlini 5395
./run_extra.sh mnist a adversarial carlini 5395
./run_extra.sh mnist a relu carlini 5395
./run_extra.sh mnist b standard carlini 5395
./run_extra.sh mnist b adversarial carlini 5395
./run_extra.sh mnist b relu carlini 5395
./run_extra.sh mnist c standard carlini 5395
./run_extra.sh mnist c adversarial carlini 5395
./run_extra.sh mnist c relu carlini 5395
./run_extra.sh mnist a standard carlini 1840
./run_extra.sh mnist a adversarial carlini 1840
./run_extra.sh mnist a relu carlini 1840
./run_extra.sh mnist b standard carlini 1840
./run_extra.sh mnist b adversarial carlini 1840
./run_extra.sh mnist b relu carlini 1840
./run_extra.sh mnist c standard carlini 1840
./run_extra.sh mnist c adversarial carlini 1840
./run_extra.sh mnist c relu carlini 1840
./run_extra.sh mnist a standard carlini 2449
./run_extra.sh mnist a adversarial carlini 2449
./run_extra.sh mnist a relu carlini 2449
./run_extra.sh mnist b standard carlini 2449
./run_extra.sh mnist b adversarial carlini 2449
./run_extra.sh mnist b relu carlini 2449
./run_extra.sh mnist c standard carlini 2449
./run_extra.sh mnist c adversarial carlini 2449
./run_extra.sh mnist c relu carlini 2449
./run_extra.sh mnist a standard carlini 4492
./run_extra.sh mnist a adversarial carlini 4492
./run_extra.sh mnist a relu carlini 4492
./run_extra.sh mnist b standard carlini 4492
./run_extra.sh mnist b adversarial carlini 4492
./run_extra.sh mnist b relu carlini 4492
./run_extra.sh mnist c standard carlini 4492
./run_extra.sh mnist c adversarial carlini 4492
./run_extra.sh mnist c relu carlini 4492
./run_extra.sh mnist a standard carlini 1434
./run_extra.sh mnist a adversarial carlini 1434
./run_extra.sh mnist a relu carlini 1434
./run_extra.sh mnist b standard carlini 1434
./run_extra.sh mnist b adversarial carlini 1434
./run_extra.sh mnist b relu carlini 1434
./run_extra.sh mnist c standard carlini 1434
./run_extra.sh mnist c adversarial carlini 1434
./run_extra.sh mnist c relu carlini 1434
./run_extra.sh mnist a standard carlini 3798
./run_extra.sh mnist a adversarial carlini 3798
./run_extra.sh mnist a relu carlini 3798
./run_extra.sh mnist b standard carlini 3798
./run_extra.sh mnist b adversarial carlini 3798
./run_extra.sh mnist b relu carlini 3798
./run_extra.sh mnist c standard carlini 3798
./run_extra.sh mnist c adversarial carlini 3798
./run_extra.sh mnist c relu carlini 3798
./run_extra.sh mnist a standard carlini 7613
./run_extra.sh mnist a adversarial carlini 7613
./run_extra.sh mnist a relu carlini 7613
./run_extra.sh mnist b standard carlini 7613
./run_extra.sh mnist b adversarial carlini 7613
./run_extra.sh mnist b relu carlini 7613
./run_extra.sh mnist c standard carlini 7613
./run_extra.sh mnist c adversarial carlini 7613
./run_extra.sh mnist c relu carlini 7613
./run_extra.sh mnist a standard carlini 9405
./run_extra.sh mnist a adversarial carlini 9405
./run_extra.sh mnist a relu carlini 9405
./run_extra.sh mnist b standard carlini 9405
./run_extra.sh mnist b adversarial carlini 9405
./run_extra.sh mnist b relu carlini 9405
./run_extra.sh mnist c standard carlini 9405
./run_extra.sh mnist c adversarial carlini 9405
./run_extra.sh mnist c relu carlini 9405
./run_extra.sh mnist a standard carlini 645
./run_extra.sh mnist a adversarial carlini 645
./run_extra.sh mnist a relu carlini 645
./run_extra.sh mnist b standard carlini 645
./run_extra.sh mnist b adversarial carlini 645
./run_extra.sh mnist b relu carlini 645
./run_extra.sh mnist c standard carlini 645
./run_extra.sh mnist c adversarial carlini 645
./run_extra.sh mnist c relu carlini 645
./run_extra.sh mnist a standard carlini 6532
./run_extra.sh mnist a adversarial carlini 6532
./run_extra.sh mnist a relu carlini 6532
./run_extra.sh mnist b standard carlini 6532
./run_extra.sh mnist b adversarial carlini 6532
./run_extra.sh mnist b relu carlini 6532
./run_extra.sh mnist c standard carlini 6532
./run_extra.sh mnist c adversarial carlini 6532
./run_extra.sh mnist c relu carlini 6532
./run_extra.sh mnist a standard carlini 9263
./run_extra.sh mnist a adversarial carlini 9263
./run_extra.sh mnist a relu carlini 9263
./run_extra.sh mnist b standard carlini 9263
./run_extra.sh mnist b adversarial carlini 9263
./run_extra.sh mnist b relu carlini 9263
./run_extra.sh mnist c standard carlini 9263
./run_extra.sh mnist c adversarial carlini 9263
./run_extra.sh mnist c relu carlini 9263
./run_extra.sh mnist a standard carlini 567
./run_extra.sh mnist a adversarial carlini 567
./run_extra.sh mnist a relu carlini 567
./run_extra.sh mnist b standard carlini 567
./run_extra.sh mnist b adversarial carlini 567
./run_extra.sh mnist b relu carlini 567
./run_extra.sh mnist c standard carlini 567
./run_extra.sh mnist c adversarial carlini 567
./run_extra.sh mnist c relu carlini 567
./run_extra.sh mnist a standard carlini 6081
./run_extra.sh mnist a adversarial carlini 6081
./run_extra.sh mnist a relu carlini 6081
./run_extra.sh mnist b standard carlini 6081
./run_extra.sh mnist b adversarial carlini 6081
./run_extra.sh mnist b relu carlini 6081
./run_extra.sh mnist c standard carlini 6081
./run_extra.sh mnist c adversarial carlini 6081
./run_extra.sh mnist c relu carlini 6081
./run_extra.sh mnist a standard carlini 2581
./run_extra.sh mnist a adversarial carlini 2581
./run_extra.sh mnist a relu carlini 2581
./run_extra.sh mnist b standard carlini 2581
./run_extra.sh mnist b adversarial carlini 2581
./run_extra.sh mnist b relu carlini 2581
./run_extra.sh mnist c standard carlini 2581
./run_extra.sh mnist c adversarial carlini 2581
./run_extra.sh mnist c relu carlini 2581
./run_extra.sh mnist a standard carlini 9575
./run_extra.sh mnist a adversarial carlini 9575
./run_extra.sh mnist a relu carlini 9575
./run_extra.sh mnist b standard carlini 9575
./run_extra.sh mnist b adversarial carlini 9575
./run_extra.sh mnist b relu carlini 9575
./run_extra.sh mnist c standard carlini 9575
./run_extra.sh mnist c adversarial carlini 9575
./run_extra.sh mnist c relu carlini 9575
./run_extra.sh mnist a standard carlini 1883
./run_extra.sh mnist a adversarial carlini 1883
./run_extra.sh mnist a relu carlini 1883
./run_extra.sh mnist b standard carlini 1883
./run_extra.sh mnist b adversarial carlini 1883
./run_extra.sh mnist b relu carlini 1883
./run_extra.sh mnist c standard carlini 1883
./run_extra.sh mnist c adversarial carlini 1883
./run_extra.sh mnist c relu carlini 1883
./run_extra.sh mnist a standard carlini 3864
./run_extra.sh mnist a adversarial carlini 3864
./run_extra.sh mnist a relu carlini 3864
./run_extra.sh mnist b standard carlini 3864
./run_extra.sh mnist b adversarial carlini 3864
./run_extra.sh mnist b relu carlini 3864
./run_extra.sh mnist c standard carlini 3864
./run_extra.sh mnist c adversarial carlini 3864
./run_extra.sh mnist c relu carlini 3864
./run_extra.sh mnist a standard carlini 9229
./run_extra.sh mnist a adversarial carlini 9229
./run_extra.sh mnist a relu carlini 9229
./run_extra.sh mnist b standard carlini 9229
./run_extra.sh mnist b adversarial carlini 9229
./run_extra.sh mnist b relu carlini 9229
./run_extra.sh mnist c standard carlini 9229
./run_extra.sh mnist c adversarial carlini 9229
./run_extra.sh mnist c relu carlini 9229
./run_extra.sh mnist a standard carlini 5757
./run_extra.sh mnist a adversarial carlini 5757
./run_extra.sh mnist a relu carlini 5757
./run_extra.sh mnist b standard carlini 5757
./run_extra.sh mnist b adversarial carlini 5757
./run_extra.sh mnist b relu carlini 5757
./run_extra.sh mnist c standard carlini 5757
./run_extra.sh mnist c adversarial carlini 5757
./run_extra.sh mnist c relu carlini 5757
./run_extra.sh mnist a standard carlini 7128
./run_extra.sh mnist a adversarial carlini 7128
./run_extra.sh mnist a relu carlini 7128
./run_extra.sh mnist b standard carlini 7128
./run_extra.sh mnist b adversarial carlini 7128
./run_extra.sh mnist b relu carlini 7128
./run_extra.sh mnist c standard carlini 7128
./run_extra.sh mnist c adversarial carlini 7128
./run_extra.sh mnist c relu carlini 7128
./run_extra.sh mnist a standard carlini 666
./run_extra.sh mnist a adversarial carlini 666
./run_extra.sh mnist a relu carlini 666
./run_extra.sh mnist b standard carlini 666
./run_extra.sh mnist b adversarial carlini 666
./run_extra.sh mnist b relu carlini 666
./run_extra.sh mnist c standard carlini 666
./run_extra.sh mnist c adversarial carlini 666
./run_extra.sh mnist c relu carlini 666
./run_extra.sh mnist a standard carlini 4956
./run_extra.sh mnist a adversarial carlini 4956
./run_extra.sh mnist a relu carlini 4956
./run_extra.sh mnist b standard carlini 4956
./run_extra.sh mnist b adversarial carlini 4956
./run_extra.sh mnist b relu carlini 4956
./run_extra.sh mnist c standard carlini 4956
./run_extra.sh mnist c adversarial carlini 4956
./run_extra.sh mnist c relu carlini 4956
./run_extra.sh mnist a standard carlini 7328
./run_extra.sh mnist a adversarial carlini 7328
./run_extra.sh mnist a relu carlini 7328
./run_extra.sh mnist b standard carlini 7328
./run_extra.sh mnist b adversarial carlini 7328
./run_extra.sh mnist b relu carlini 7328
./run_extra.sh mnist c standard carlini 7328
./run_extra.sh mnist c adversarial carlini 7328
./run_extra.sh mnist c relu carlini 7328
./run_extra.sh mnist a standard carlini 7362
./run_extra.sh mnist a adversarial carlini 7362
./run_extra.sh mnist a relu carlini 7362
./run_extra.sh mnist b standard carlini 7362
./run_extra.sh mnist b adversarial carlini 7362
./run_extra.sh mnist b relu carlini 7362
./run_extra.sh mnist c standard carlini 7362
./run_extra.sh mnist c adversarial carlini 7362
./run_extra.sh mnist c relu carlini 7362
./run_extra.sh mnist a standard carlini 9065
./run_extra.sh mnist a adversarial carlini 9065
./run_extra.sh mnist a relu carlini 9065
./run_extra.sh mnist b standard carlini 9065
./run_extra.sh mnist b adversarial carlini 9065
./run_extra.sh mnist b relu carlini 9065
./run_extra.sh mnist c standard carlini 9065
./run_extra.sh mnist c adversarial carlini 9065
./run_extra.sh mnist c relu carlini 9065
./run_extra.sh mnist a standard carlini 6058
./run_extra.sh mnist a adversarial carlini 6058
./run_extra.sh mnist a relu carlini 6058
./run_extra.sh mnist b standard carlini 6058
./run_extra.sh mnist b adversarial carlini 6058
./run_extra.sh mnist b relu carlini 6058
./run_extra.sh mnist c standard carlini 6058
./run_extra.sh mnist c adversarial carlini 6058
./run_extra.sh mnist c relu carlini 6058
./run_extra.sh mnist a standard carlini 8555
./run_extra.sh mnist a adversarial carlini 8555
./run_extra.sh mnist a relu carlini 8555
./run_extra.sh mnist b standard carlini 8555
./run_extra.sh mnist b adversarial carlini 8555
./run_extra.sh mnist b relu carlini 8555
./run_extra.sh mnist c standard carlini 8555
./run_extra.sh mnist c adversarial carlini 8555
./run_extra.sh mnist c relu carlini 8555
./run_extra.sh mnist a standard carlini 9466
./run_extra.sh mnist a adversarial carlini 9466
./run_extra.sh mnist a relu carlini 9466
./run_extra.sh mnist b standard carlini 9466
./run_extra.sh mnist b adversarial carlini 9466
./run_extra.sh mnist b relu carlini 9466
./run_extra.sh mnist c standard carlini 9466
./run_extra.sh mnist c adversarial carlini 9466
./run_extra.sh mnist c relu carlini 9466
./run_extra.sh mnist a standard carlini 7511
./run_extra.sh mnist a adversarial carlini 7511
./run_extra.sh mnist a relu carlini 7511
./run_extra.sh mnist b standard carlini 7511
./run_extra.sh mnist b adversarial carlini 7511
./run_extra.sh mnist b relu carlini 7511
./run_extra.sh mnist c standard carlini 7511
./run_extra.sh mnist c adversarial carlini 7511
./run_extra.sh mnist c relu carlini 7511
./run_extra.sh mnist a standard carlini 847
./run_extra.sh mnist a adversarial carlini 847
./run_extra.sh mnist a relu carlini 847
./run_extra.sh mnist b standard carlini 847
./run_extra.sh mnist b adversarial carlini 847
./run_extra.sh mnist b relu carlini 847
./run_extra.sh mnist c standard carlini 847
./run_extra.sh mnist c adversarial carlini 847
./run_extra.sh mnist c relu carlini 847
./run_extra.sh mnist a standard carlini 1724
./run_extra.sh mnist a adversarial carlini 1724
./run_extra.sh mnist a relu carlini 1724
./run_extra.sh mnist b standard carlini 1724
./run_extra.sh mnist b adversarial carlini 1724
./run_extra.sh mnist b relu carlini 1724
./run_extra.sh mnist c standard carlini 1724
./run_extra.sh mnist c adversarial carlini 1724
./run_extra.sh mnist c relu carlini 1724
./run_extra.sh mnist a standard carlini 3796
./run_extra.sh mnist a adversarial carlini 3796
./run_extra.sh mnist a relu carlini 3796
./run_extra.sh mnist b standard carlini 3796
./run_extra.sh mnist b adversarial carlini 3796
./run_extra.sh mnist b relu carlini 3796
./run_extra.sh mnist c standard carlini 3796
./run_extra.sh mnist c adversarial carlini 3796
./run_extra.sh mnist c relu carlini 3796
./run_extra.sh mnist a standard carlini 1552
./run_extra.sh mnist a adversarial carlini 1552
./run_extra.sh mnist a relu carlini 1552
./run_extra.sh mnist b standard carlini 1552
./run_extra.sh mnist b adversarial carlini 1552
./run_extra.sh mnist b relu carlini 1552
./run_extra.sh mnist c standard carlini 1552
./run_extra.sh mnist c adversarial carlini 1552
./run_extra.sh mnist c relu carlini 1552
./run_extra.sh mnist a standard carlini 8476
./run_extra.sh mnist a adversarial carlini 8476
./run_extra.sh mnist a relu carlini 8476
./run_extra.sh mnist b standard carlini 8476
./run_extra.sh mnist b adversarial carlini 8476
./run_extra.sh mnist b relu carlini 8476
./run_extra.sh mnist c standard carlini 8476
./run_extra.sh mnist c adversarial carlini 8476
./run_extra.sh mnist c relu carlini 8476
./run_extra.sh mnist a standard carlini 9808
./run_extra.sh mnist a adversarial carlini 9808
./run_extra.sh mnist a relu carlini 9808
./run_extra.sh mnist b standard carlini 9808
./run_extra.sh mnist b adversarial carlini 9808
./run_extra.sh mnist b relu carlini 9808
./run_extra.sh mnist c standard carlini 9808
./run_extra.sh mnist c adversarial carlini 9808
./run_extra.sh mnist c relu carlini 9808
./run_extra.sh mnist a standard carlini 922
./run_extra.sh mnist a adversarial carlini 922
./run_extra.sh mnist a relu carlini 922
./run_extra.sh mnist b standard carlini 922
./run_extra.sh mnist b adversarial carlini 922
./run_extra.sh mnist b relu carlini 922
./run_extra.sh mnist c standard carlini 922
./run_extra.sh mnist c adversarial carlini 922
./run_extra.sh mnist c relu carlini 922
./run_extra.sh mnist a standard carlini 8548
./run_extra.sh mnist a adversarial carlini 8548
./run_extra.sh mnist a relu carlini 8548
./run_extra.sh mnist b standard carlini 8548
./run_extra.sh mnist b adversarial carlini 8548
./run_extra.sh mnist b relu carlini 8548
./run_extra.sh mnist c standard carlini 8548
./run_extra.sh mnist c adversarial carlini 8548
./run_extra.sh mnist c relu carlini 8548
./run_extra.sh mnist a standard carlini 4103
./run_extra.sh mnist a adversarial carlini 4103
./run_extra.sh mnist a relu carlini 4103
./run_extra.sh mnist b standard carlini 4103
./run_extra.sh mnist b adversarial carlini 4103
./run_extra.sh mnist b relu carlini 4103
./run_extra.sh mnist c standard carlini 4103
./run_extra.sh mnist c adversarial carlini 4103
./run_extra.sh mnist c relu carlini 4103
./run_extra.sh mnist a standard carlini 5547
./run_extra.sh mnist a adversarial carlini 5547
./run_extra.sh mnist a relu carlini 5547
./run_extra.sh mnist b standard carlini 5547
./run_extra.sh mnist b adversarial carlini 5547
./run_extra.sh mnist b relu carlini 5547
./run_extra.sh mnist c standard carlini 5547
./run_extra.sh mnist c adversarial carlini 5547
./run_extra.sh mnist c relu carlini 5547
./run_extra.sh mnist a standard carlini 7994
./run_extra.sh mnist a adversarial carlini 7994
./run_extra.sh mnist a relu carlini 7994
./run_extra.sh mnist b standard carlini 7994
./run_extra.sh mnist b adversarial carlini 7994
./run_extra.sh mnist b relu carlini 7994
./run_extra.sh mnist c standard carlini 7994
./run_extra.sh mnist c adversarial carlini 7994
./run_extra.sh mnist c relu carlini 7994
./run_extra.sh mnist a standard carlini 5183
./run_extra.sh mnist a adversarial carlini 5183
./run_extra.sh mnist a relu carlini 5183
./run_extra.sh mnist b standard carlini 5183
./run_extra.sh mnist b adversarial carlini 5183
./run_extra.sh mnist b relu carlini 5183
./run_extra.sh mnist c standard carlini 5183
./run_extra.sh mnist c adversarial carlini 5183
./run_extra.sh mnist c relu carlini 5183
./run_extra.sh mnist a standard carlini 1723
./run_extra.sh mnist a adversarial carlini 1723
./run_extra.sh mnist a relu carlini 1723
./run_extra.sh mnist b standard carlini 1723
./run_extra.sh mnist b adversarial carlini 1723
./run_extra.sh mnist b relu carlini 1723
./run_extra.sh mnist c standard carlini 1723
./run_extra.sh mnist c adversarial carlini 1723
./run_extra.sh mnist c relu carlini 1723
./run_extra.sh mnist a standard carlini 6334
./run_extra.sh mnist a adversarial carlini 6334
./run_extra.sh mnist a relu carlini 6334
./run_extra.sh mnist b standard carlini 6334
./run_extra.sh mnist b adversarial carlini 6334
./run_extra.sh mnist b relu carlini 6334
./run_extra.sh mnist c standard carlini 6334
./run_extra.sh mnist c adversarial carlini 6334
./run_extra.sh mnist c relu carlini 6334
./run_extra.sh mnist a standard carlini 6153
./run_extra.sh mnist a adversarial carlini 6153
./run_extra.sh mnist a relu carlini 6153
./run_extra.sh mnist b standard carlini 6153
./run_extra.sh mnist b adversarial carlini 6153
./run_extra.sh mnist b relu carlini 6153
./run_extra.sh mnist c standard carlini 6153
./run_extra.sh mnist c adversarial carlini 6153
./run_extra.sh mnist c relu carlini 6153
./run_extra.sh mnist a standard carlini 3299
./run_extra.sh mnist a adversarial carlini 3299
./run_extra.sh mnist a relu carlini 3299
./run_extra.sh mnist b standard carlini 3299
./run_extra.sh mnist b adversarial carlini 3299
./run_extra.sh mnist b relu carlini 3299
./run_extra.sh mnist c standard carlini 3299
./run_extra.sh mnist c adversarial carlini 3299
./run_extra.sh mnist c relu carlini 3299
./run_extra.sh mnist a standard carlini 8418
./run_extra.sh mnist a adversarial carlini 8418
./run_extra.sh mnist a relu carlini 8418
./run_extra.sh mnist b standard carlini 8418
./run_extra.sh mnist b adversarial carlini 8418
./run_extra.sh mnist b relu carlini 8418
./run_extra.sh mnist c standard carlini 8418
./run_extra.sh mnist c adversarial carlini 8418
./run_extra.sh mnist c relu carlini 8418
./run_extra.sh mnist a standard carlini 2570
./run_extra.sh mnist a adversarial carlini 2570
./run_extra.sh mnist a relu carlini 2570
./run_extra.sh mnist b standard carlini 2570
./run_extra.sh mnist b adversarial carlini 2570
./run_extra.sh mnist b relu carlini 2570
./run_extra.sh mnist c standard carlini 2570
./run_extra.sh mnist c adversarial carlini 2570
./run_extra.sh mnist c relu carlini 2570
./run_extra.sh mnist a standard carlini 2783
./run_extra.sh mnist a adversarial carlini 2783
./run_extra.sh mnist a relu carlini 2783
./run_extra.sh mnist b standard carlini 2783
./run_extra.sh mnist b adversarial carlini 2783
./run_extra.sh mnist b relu carlini 2783
./run_extra.sh mnist c standard carlini 2783
./run_extra.sh mnist c adversarial carlini 2783
./run_extra.sh mnist c relu carlini 2783
./run_extra.sh mnist a standard carlini 7034
./run_extra.sh mnist a adversarial carlini 7034
./run_extra.sh mnist a relu carlini 7034
./run_extra.sh mnist b standard carlini 7034
./run_extra.sh mnist b adversarial carlini 7034
./run_extra.sh mnist b relu carlini 7034
./run_extra.sh mnist c standard carlini 7034
./run_extra.sh mnist c adversarial carlini 7034
./run_extra.sh mnist c relu carlini 7034
./run_extra.sh mnist a standard carlini 542
./run_extra.sh mnist a adversarial carlini 542
./run_extra.sh mnist a relu carlini 542
./run_extra.sh mnist b standard carlini 542
./run_extra.sh mnist b adversarial carlini 542
./run_extra.sh mnist b relu carlini 542
./run_extra.sh mnist c standard carlini 542
./run_extra.sh mnist c adversarial carlini 542
./run_extra.sh mnist c relu carlini 542
./run_extra.sh mnist a standard carlini 2641
./run_extra.sh mnist a adversarial carlini 2641
./run_extra.sh mnist a relu carlini 2641
./run_extra.sh mnist b standard carlini 2641
./run_extra.sh mnist b adversarial carlini 2641
./run_extra.sh mnist b relu carlini 2641
./run_extra.sh mnist c standard carlini 2641
./run_extra.sh mnist c adversarial carlini 2641
./run_extra.sh mnist c relu carlini 2641
./run_extra.sh mnist a standard carlini 5740
./run_extra.sh mnist a adversarial carlini 5740
./run_extra.sh mnist a relu carlini 5740
./run_extra.sh mnist b standard carlini 5740
./run_extra.sh mnist b adversarial carlini 5740
./run_extra.sh mnist b relu carlini 5740
./run_extra.sh mnist c standard carlini 5740
./run_extra.sh mnist c adversarial carlini 5740
./run_extra.sh mnist c relu carlini 5740
./run_extra.sh mnist a standard carlini 4701
./run_extra.sh mnist a adversarial carlini 4701
./run_extra.sh mnist a relu carlini 4701
./run_extra.sh mnist b standard carlini 4701
./run_extra.sh mnist b adversarial carlini 4701
./run_extra.sh mnist b relu carlini 4701
./run_extra.sh mnist c standard carlini 4701
./run_extra.sh mnist c adversarial carlini 4701
./run_extra.sh mnist c relu carlini 4701
./run_extra.sh mnist a standard carlini 1983
./run_extra.sh mnist a adversarial carlini 1983
./run_extra.sh mnist a relu carlini 1983
./run_extra.sh mnist b standard carlini 1983
./run_extra.sh mnist b adversarial carlini 1983
./run_extra.sh mnist b relu carlini 1983
./run_extra.sh mnist c standard carlini 1983
./run_extra.sh mnist c adversarial carlini 1983
./run_extra.sh mnist c relu carlini 1983
./run_extra.sh mnist a standard carlini 6681
./run_extra.sh mnist a adversarial carlini 6681
./run_extra.sh mnist a relu carlini 6681
./run_extra.sh mnist b standard carlini 6681
./run_extra.sh mnist b adversarial carlini 6681
./run_extra.sh mnist b relu carlini 6681
./run_extra.sh mnist c standard carlini 6681
./run_extra.sh mnist c adversarial carlini 6681
./run_extra.sh mnist c relu carlini 6681
./run_extra.sh mnist a standard carlini 500
./run_extra.sh mnist a adversarial carlini 500
./run_extra.sh mnist a relu carlini 500
./run_extra.sh mnist b standard carlini 500
./run_extra.sh mnist b adversarial carlini 500
./run_extra.sh mnist b relu carlini 500
./run_extra.sh mnist c standard carlini 500
./run_extra.sh mnist c adversarial carlini 500
./run_extra.sh mnist c relu carlini 500
./run_extra.sh mnist a standard carlini 8402
./run_extra.sh mnist a adversarial carlini 8402
./run_extra.sh mnist a relu carlini 8402
./run_extra.sh mnist b standard carlini 8402
./run_extra.sh mnist b adversarial carlini 8402
./run_extra.sh mnist b relu carlini 8402
./run_extra.sh mnist c standard carlini 8402
./run_extra.sh mnist c adversarial carlini 8402
./run_extra.sh mnist c relu carlini 8402
./run_extra.sh mnist a standard carlini 5126
./run_extra.sh mnist a adversarial carlini 5126
./run_extra.sh mnist a relu carlini 5126
./run_extra.sh mnist b standard carlini 5126
./run_extra.sh mnist b adversarial carlini 5126
./run_extra.sh mnist b relu carlini 5126
./run_extra.sh mnist c standard carlini 5126
./run_extra.sh mnist c adversarial carlini 5126
./run_extra.sh mnist c relu carlini 5126
./run_extra.sh mnist a standard carlini 2689
./run_extra.sh mnist a adversarial carlini 2689
./run_extra.sh mnist a relu carlini 2689
./run_extra.sh mnist b standard carlini 2689
./run_extra.sh mnist b adversarial carlini 2689
./run_extra.sh mnist b relu carlini 2689
./run_extra.sh mnist c standard carlini 2689
./run_extra.sh mnist c adversarial carlini 2689
./run_extra.sh mnist c relu carlini 2689
./run_extra.sh mnist a standard carlini 9208
./run_extra.sh mnist a adversarial carlini 9208
./run_extra.sh mnist a relu carlini 9208
./run_extra.sh mnist b standard carlini 9208
./run_extra.sh mnist b adversarial carlini 9208
./run_extra.sh mnist b relu carlini 9208
./run_extra.sh mnist c standard carlini 9208
./run_extra.sh mnist c adversarial carlini 9208
./run_extra.sh mnist c relu carlini 9208
./run_extra.sh mnist a standard carlini 7557
./run_extra.sh mnist a adversarial carlini 7557
./run_extra.sh mnist a relu carlini 7557
./run_extra.sh mnist b standard carlini 7557
./run_extra.sh mnist b adversarial carlini 7557
./run_extra.sh mnist b relu carlini 7557
./run_extra.sh mnist c standard carlini 7557
./run_extra.sh mnist c adversarial carlini 7557
./run_extra.sh mnist c relu carlini 7557
./run_extra.sh mnist a standard carlini 4293
./run_extra.sh mnist a adversarial carlini 4293
./run_extra.sh mnist a relu carlini 4293
./run_extra.sh mnist b standard carlini 4293
./run_extra.sh mnist b adversarial carlini 4293
./run_extra.sh mnist b relu carlini 4293
./run_extra.sh mnist c standard carlini 4293
./run_extra.sh mnist c adversarial carlini 4293
./run_extra.sh mnist c relu carlini 4293
./run_extra.sh mnist a standard carlini 6448
./run_extra.sh mnist a adversarial carlini 6448
./run_extra.sh mnist a relu carlini 6448
./run_extra.sh mnist b standard carlini 6448
./run_extra.sh mnist b adversarial carlini 6448
./run_extra.sh mnist b relu carlini 6448
./run_extra.sh mnist c standard carlini 6448
./run_extra.sh mnist c adversarial carlini 6448
./run_extra.sh mnist c relu carlini 6448
./run_extra.sh mnist a standard carlini 8049
./run_extra.sh mnist a adversarial carlini 8049
./run_extra.sh mnist a relu carlini 8049
./run_extra.sh mnist b standard carlini 8049
./run_extra.sh mnist b adversarial carlini 8049
./run_extra.sh mnist b relu carlini 8049
./run_extra.sh mnist c standard carlini 8049
./run_extra.sh mnist c adversarial carlini 8049
./run_extra.sh mnist c relu carlini 8049
./run_extra.sh mnist a standard carlini 4426
./run_extra.sh mnist a adversarial carlini 4426
./run_extra.sh mnist a relu carlini 4426
./run_extra.sh mnist b standard carlini 4426
./run_extra.sh mnist b adversarial carlini 4426
./run_extra.sh mnist b relu carlini 4426
./run_extra.sh mnist c standard carlini 4426
./run_extra.sh mnist c adversarial carlini 4426
./run_extra.sh mnist c relu carlini 4426
./run_extra.sh mnist a standard carlini 7294
./run_extra.sh mnist a adversarial carlini 7294
./run_extra.sh mnist a relu carlini 7294
./run_extra.sh mnist b standard carlini 7294
./run_extra.sh mnist b adversarial carlini 7294
./run_extra.sh mnist b relu carlini 7294
./run_extra.sh mnist c standard carlini 7294
./run_extra.sh mnist c adversarial carlini 7294
./run_extra.sh mnist c relu carlini 7294
./run_extra.sh mnist a standard carlini 4471
./run_extra.sh mnist a adversarial carlini 4471
./run_extra.sh mnist a relu carlini 4471
./run_extra.sh mnist b standard carlini 4471
./run_extra.sh mnist b adversarial carlini 4471
./run_extra.sh mnist b relu carlini 4471
./run_extra.sh mnist c standard carlini 4471
./run_extra.sh mnist c adversarial carlini 4471
./run_extra.sh mnist c relu carlini 4471
./run_extra.sh mnist a standard carlini 1936
./run_extra.sh mnist a adversarial carlini 1936
./run_extra.sh mnist a relu carlini 1936
./run_extra.sh mnist b standard carlini 1936
./run_extra.sh mnist b adversarial carlini 1936
./run_extra.sh mnist b relu carlini 1936
./run_extra.sh mnist c standard carlini 1936
./run_extra.sh mnist c adversarial carlini 1936
./run_extra.sh mnist c relu carlini 1936
./run_extra.sh mnist a standard carlini 1091
./run_extra.sh mnist a adversarial carlini 1091
./run_extra.sh mnist a relu carlini 1091
./run_extra.sh mnist b standard carlini 1091
./run_extra.sh mnist b adversarial carlini 1091
./run_extra.sh mnist b relu carlini 1091
./run_extra.sh mnist c standard carlini 1091
./run_extra.sh mnist c adversarial carlini 1091
./run_extra.sh mnist c relu carlini 1091
./run_extra.sh mnist a standard carlini 1601
./run_extra.sh mnist a adversarial carlini 1601
./run_extra.sh mnist a relu carlini 1601
./run_extra.sh mnist b standard carlini 1601
./run_extra.sh mnist b adversarial carlini 1601
./run_extra.sh mnist b relu carlini 1601
./run_extra.sh mnist c standard carlini 1601
./run_extra.sh mnist c adversarial carlini 1601
./run_extra.sh mnist c relu carlini 1601
./run_extra.sh mnist a standard carlini 1951
./run_extra.sh mnist a adversarial carlini 1951
./run_extra.sh mnist a relu carlini 1951
./run_extra.sh mnist b standard carlini 1951
./run_extra.sh mnist b adversarial carlini 1951
./run_extra.sh mnist b relu carlini 1951
./run_extra.sh mnist c standard carlini 1951
./run_extra.sh mnist c adversarial carlini 1951
./run_extra.sh mnist c relu carlini 1951
./run_extra.sh mnist a standard carlini 3208
./run_extra.sh mnist a adversarial carlini 3208
./run_extra.sh mnist a relu carlini 3208
./run_extra.sh mnist b standard carlini 3208
./run_extra.sh mnist b adversarial carlini 3208
./run_extra.sh mnist b relu carlini 3208
./run_extra.sh mnist c standard carlini 3208
./run_extra.sh mnist c adversarial carlini 3208
./run_extra.sh mnist c relu carlini 3208
./run_extra.sh mnist a standard carlini 2537
./run_extra.sh mnist a adversarial carlini 2537
./run_extra.sh mnist a relu carlini 2537
./run_extra.sh mnist b standard carlini 2537
./run_extra.sh mnist b adversarial carlini 2537
./run_extra.sh mnist b relu carlini 2537
./run_extra.sh mnist c standard carlini 2537
./run_extra.sh mnist c adversarial carlini 2537
./run_extra.sh mnist c relu carlini 2537
./run_extra.sh mnist a standard carlini 960
./run_extra.sh mnist a adversarial carlini 960
./run_extra.sh mnist a relu carlini 960
./run_extra.sh mnist b standard carlini 960
./run_extra.sh mnist b adversarial carlini 960
./run_extra.sh mnist b relu carlini 960
./run_extra.sh mnist c standard carlini 960
./run_extra.sh mnist c adversarial carlini 960
./run_extra.sh mnist c relu carlini 960
./run_extra.sh mnist a standard carlini 9340
./run_extra.sh mnist a adversarial carlini 9340
./run_extra.sh mnist a relu carlini 9340
./run_extra.sh mnist b standard carlini 9340
./run_extra.sh mnist b adversarial carlini 9340
./run_extra.sh mnist b relu carlini 9340
./run_extra.sh mnist c standard carlini 9340
./run_extra.sh mnist c adversarial carlini 9340
./run_extra.sh mnist c relu carlini 9340
./run_extra.sh mnist a standard carlini 5330
./run_extra.sh mnist a adversarial carlini 5330
./run_extra.sh mnist a relu carlini 5330
./run_extra.sh mnist b standard carlini 5330
./run_extra.sh mnist b adversarial carlini 5330
./run_extra.sh mnist b relu carlini 5330
./run_extra.sh mnist c standard carlini 5330
./run_extra.sh mnist c adversarial carlini 5330
./run_extra.sh mnist c relu carlini 5330
./run_extra.sh mnist a standard carlini 8267
./run_extra.sh mnist a adversarial carlini 8267
./run_extra.sh mnist a relu carlini 8267
./run_extra.sh mnist b standard carlini 8267
./run_extra.sh mnist b adversarial carlini 8267
./run_extra.sh mnist b relu carlini 8267
./run_extra.sh mnist c standard carlini 8267
./run_extra.sh mnist c adversarial carlini 8267
./run_extra.sh mnist c relu carlini 8267
./run_extra.sh mnist a standard carlini 8959
./run_extra.sh mnist a adversarial carlini 8959
./run_extra.sh mnist a relu carlini 8959
./run_extra.sh mnist b standard carlini 8959
./run_extra.sh mnist b adversarial carlini 8959
./run_extra.sh mnist b relu carlini 8959
./run_extra.sh mnist c standard carlini 8959
./run_extra.sh mnist c adversarial carlini 8959
./run_extra.sh mnist c relu carlini 8959
./run_extra.sh mnist a standard carlini 2534
./run_extra.sh mnist a adversarial carlini 2534
./run_extra.sh mnist a relu carlini 2534
./run_extra.sh mnist b standard carlini 2534
./run_extra.sh mnist b adversarial carlini 2534
./run_extra.sh mnist b relu carlini 2534
./run_extra.sh mnist c standard carlini 2534
./run_extra.sh mnist c adversarial carlini 2534
./run_extra.sh mnist c relu carlini 2534
./run_extra.sh mnist a standard carlini 9211
./run_extra.sh mnist a adversarial carlini 9211
./run_extra.sh mnist a relu carlini 9211
./run_extra.sh mnist b standard carlini 9211
./run_extra.sh mnist b adversarial carlini 9211
./run_extra.sh mnist b relu carlini 9211
./run_extra.sh mnist c standard carlini 9211
./run_extra.sh mnist c adversarial carlini 9211
./run_extra.sh mnist c relu carlini 9211
./run_extra.sh mnist a standard carlini 6294
./run_extra.sh mnist a adversarial carlini 6294
./run_extra.sh mnist a relu carlini 6294
./run_extra.sh mnist b standard carlini 6294
./run_extra.sh mnist b adversarial carlini 6294
./run_extra.sh mnist b relu carlini 6294
./run_extra.sh mnist c standard carlini 6294
./run_extra.sh mnist c adversarial carlini 6294
./run_extra.sh mnist c relu carlini 6294
./run_extra.sh mnist a standard carlini 6795
./run_extra.sh mnist a adversarial carlini 6795
./run_extra.sh mnist a relu carlini 6795
./run_extra.sh mnist b standard carlini 6795
./run_extra.sh mnist b adversarial carlini 6795
./run_extra.sh mnist b relu carlini 6795
./run_extra.sh mnist c standard carlini 6795
./run_extra.sh mnist c adversarial carlini 6795
./run_extra.sh mnist c relu carlini 6795
./run_extra.sh mnist a standard carlini 1866
./run_extra.sh mnist a adversarial carlini 1866
./run_extra.sh mnist a relu carlini 1866
./run_extra.sh mnist b standard carlini 1866
./run_extra.sh mnist b adversarial carlini 1866
./run_extra.sh mnist b relu carlini 1866
./run_extra.sh mnist c standard carlini 1866
./run_extra.sh mnist c adversarial carlini 1866
./run_extra.sh mnist c relu carlini 1866
./run_extra.sh mnist a standard carlini 2546
./run_extra.sh mnist a adversarial carlini 2546
./run_extra.sh mnist a relu carlini 2546
./run_extra.sh mnist b standard carlini 2546
./run_extra.sh mnist b adversarial carlini 2546
./run_extra.sh mnist b relu carlini 2546
./run_extra.sh mnist c standard carlini 2546
./run_extra.sh mnist c adversarial carlini 2546
./run_extra.sh mnist c relu carlini 2546
./run_extra.sh mnist a standard carlini 2916
./run_extra.sh mnist a adversarial carlini 2916
./run_extra.sh mnist a relu carlini 2916
./run_extra.sh mnist b standard carlini 2916
./run_extra.sh mnist b adversarial carlini 2916
./run_extra.sh mnist b relu carlini 2916
./run_extra.sh mnist c standard carlini 2916
./run_extra.sh mnist c adversarial carlini 2916
./run_extra.sh mnist c relu carlini 2916
./run_extra.sh mnist a standard carlini 3645
./run_extra.sh mnist a adversarial carlini 3645
./run_extra.sh mnist a relu carlini 3645
./run_extra.sh mnist b standard carlini 3645
./run_extra.sh mnist b adversarial carlini 3645
./run_extra.sh mnist b relu carlini 3645
./run_extra.sh mnist c standard carlini 3645
./run_extra.sh mnist c adversarial carlini 3645
./run_extra.sh mnist c relu carlini 3645
./run_extra.sh mnist a standard carlini 4919
./run_extra.sh mnist a adversarial carlini 4919
./run_extra.sh mnist a relu carlini 4919
./run_extra.sh mnist b standard carlini 4919
./run_extra.sh mnist b adversarial carlini 4919
./run_extra.sh mnist b relu carlini 4919
./run_extra.sh mnist c standard carlini 4919
./run_extra.sh mnist c adversarial carlini 4919
./run_extra.sh mnist c relu carlini 4919
./run_extra.sh mnist a standard carlini 1812
./run_extra.sh mnist a adversarial carlini 1812
./run_extra.sh mnist a relu carlini 1812
./run_extra.sh mnist b standard carlini 1812
./run_extra.sh mnist b adversarial carlini 1812
./run_extra.sh mnist b relu carlini 1812
./run_extra.sh mnist c standard carlini 1812
./run_extra.sh mnist c adversarial carlini 1812
./run_extra.sh mnist c relu carlini 1812
./run_extra.sh mnist a standard carlini 7193
./run_extra.sh mnist a adversarial carlini 7193
./run_extra.sh mnist a relu carlini 7193
./run_extra.sh mnist b standard carlini 7193
./run_extra.sh mnist b adversarial carlini 7193
./run_extra.sh mnist b relu carlini 7193
./run_extra.sh mnist c standard carlini 7193
./run_extra.sh mnist c adversarial carlini 7193
./run_extra.sh mnist c relu carlini 7193
./run_extra.sh mnist a standard carlini 9244
./run_extra.sh mnist a adversarial carlini 9244
./run_extra.sh mnist a relu carlini 9244
./run_extra.sh mnist b standard carlini 9244
./run_extra.sh mnist b adversarial carlini 9244
./run_extra.sh mnist b relu carlini 9244
./run_extra.sh mnist c standard carlini 9244
./run_extra.sh mnist c adversarial carlini 9244
./run_extra.sh mnist c relu carlini 9244
./run_extra.sh mnist a standard carlini 5804
./run_extra.sh mnist a adversarial carlini 5804
./run_extra.sh mnist a relu carlini 5804
./run_extra.sh mnist b standard carlini 5804
./run_extra.sh mnist b adversarial carlini 5804
./run_extra.sh mnist b relu carlini 5804
./run_extra.sh mnist c standard carlini 5804
./run_extra.sh mnist c adversarial carlini 5804
./run_extra.sh mnist c relu carlini 5804
./run_extra.sh mnist a standard carlini 8328
./run_extra.sh mnist a adversarial carlini 8328
./run_extra.sh mnist a relu carlini 8328
./run_extra.sh mnist b standard carlini 8328
./run_extra.sh mnist b adversarial carlini 8328
./run_extra.sh mnist b relu carlini 8328
./run_extra.sh mnist c standard carlini 8328
./run_extra.sh mnist c adversarial carlini 8328
./run_extra.sh mnist c relu carlini 8328
./run_extra.sh mnist a standard carlini 6637
./run_extra.sh mnist a adversarial carlini 6637
./run_extra.sh mnist a relu carlini 6637
./run_extra.sh mnist b standard carlini 6637
./run_extra.sh mnist b adversarial carlini 6637
./run_extra.sh mnist b relu carlini 6637
./run_extra.sh mnist c standard carlini 6637
./run_extra.sh mnist c adversarial carlini 6637
./run_extra.sh mnist c relu carlini 6637
./run_extra.sh mnist a standard carlini 5969
./run_extra.sh mnist a adversarial carlini 5969
./run_extra.sh mnist a relu carlini 5969
./run_extra.sh mnist b standard carlini 5969
./run_extra.sh mnist b adversarial carlini 5969
./run_extra.sh mnist b relu carlini 5969
./run_extra.sh mnist c standard carlini 5969
./run_extra.sh mnist c adversarial carlini 5969
./run_extra.sh mnist c relu carlini 5969
./run_extra.sh mnist a standard carlini 3439
./run_extra.sh mnist a adversarial carlini 3439
./run_extra.sh mnist a relu carlini 3439
./run_extra.sh mnist b standard carlini 3439
./run_extra.sh mnist b adversarial carlini 3439
./run_extra.sh mnist b relu carlini 3439
./run_extra.sh mnist c standard carlini 3439
./run_extra.sh mnist c adversarial carlini 3439
./run_extra.sh mnist c relu carlini 3439
./run_extra.sh mnist a standard carlini 7740
./run_extra.sh mnist a adversarial carlini 7740
./run_extra.sh mnist a relu carlini 7740
./run_extra.sh mnist b standard carlini 7740
./run_extra.sh mnist b adversarial carlini 7740
./run_extra.sh mnist b relu carlini 7740
./run_extra.sh mnist c standard carlini 7740
./run_extra.sh mnist c adversarial carlini 7740
./run_extra.sh mnist c relu carlini 7740
./run_extra.sh mnist a standard carlini 6728
./run_extra.sh mnist a adversarial carlini 6728
./run_extra.sh mnist a relu carlini 6728
./run_extra.sh mnist b standard carlini 6728
./run_extra.sh mnist b adversarial carlini 6728
./run_extra.sh mnist b relu carlini 6728
./run_extra.sh mnist c standard carlini 6728
./run_extra.sh mnist c adversarial carlini 6728
./run_extra.sh mnist c relu carlini 6728
./run_extra.sh mnist a standard carlini 4622
./run_extra.sh mnist a adversarial carlini 4622
./run_extra.sh mnist a relu carlini 4622
./run_extra.sh mnist b standard carlini 4622
./run_extra.sh mnist b adversarial carlini 4622
./run_extra.sh mnist b relu carlini 4622
./run_extra.sh mnist c standard carlini 4622
./run_extra.sh mnist c adversarial carlini 4622
./run_extra.sh mnist c relu carlini 4622
./run_extra.sh mnist a standard carlini 5097
./run_extra.sh mnist a adversarial carlini 5097
./run_extra.sh mnist a relu carlini 5097
./run_extra.sh mnist b standard carlini 5097
./run_extra.sh mnist b adversarial carlini 5097
./run_extra.sh mnist b relu carlini 5097
./run_extra.sh mnist c standard carlini 5097
./run_extra.sh mnist c adversarial carlini 5097
./run_extra.sh mnist c relu carlini 5097
./run_extra.sh mnist a standard carlini 1464
./run_extra.sh mnist a adversarial carlini 1464
./run_extra.sh mnist a relu carlini 1464
./run_extra.sh mnist b standard carlini 1464
./run_extra.sh mnist b adversarial carlini 1464
./run_extra.sh mnist b relu carlini 1464
./run_extra.sh mnist c standard carlini 1464
./run_extra.sh mnist c adversarial carlini 1464
./run_extra.sh mnist c relu carlini 1464
./run_extra.sh mnist a standard carlini 2168
./run_extra.sh mnist a adversarial carlini 2168
./run_extra.sh mnist a relu carlini 2168
./run_extra.sh mnist b standard carlini 2168
./run_extra.sh mnist b adversarial carlini 2168
./run_extra.sh mnist b relu carlini 2168
./run_extra.sh mnist c standard carlini 2168
./run_extra.sh mnist c adversarial carlini 2168
./run_extra.sh mnist c relu carlini 2168
./run_extra.sh mnist a standard carlini 9342
./run_extra.sh mnist a adversarial carlini 9342
./run_extra.sh mnist a relu carlini 9342
./run_extra.sh mnist b standard carlini 9342
./run_extra.sh mnist b adversarial carlini 9342
./run_extra.sh mnist b relu carlini 9342
./run_extra.sh mnist c standard carlini 9342
./run_extra.sh mnist c adversarial carlini 9342
./run_extra.sh mnist c relu carlini 9342
./run_extra.sh mnist a standard carlini 3618
./run_extra.sh mnist a adversarial carlini 3618
./run_extra.sh mnist a relu carlini 3618
./run_extra.sh mnist b standard carlini 3618
./run_extra.sh mnist b adversarial carlini 3618
./run_extra.sh mnist b relu carlini 3618
./run_extra.sh mnist c standard carlini 3618
./run_extra.sh mnist c adversarial carlini 3618
./run_extra.sh mnist c relu carlini 3618
./run_extra.sh mnist a standard carlini 1061
./run_extra.sh mnist a adversarial carlini 1061
./run_extra.sh mnist a relu carlini 1061
./run_extra.sh mnist b standard carlini 1061
./run_extra.sh mnist b adversarial carlini 1061
./run_extra.sh mnist b relu carlini 1061
./run_extra.sh mnist c standard carlini 1061
./run_extra.sh mnist c adversarial carlini 1061
./run_extra.sh mnist c relu carlini 1061
./run_extra.sh mnist a standard carlini 6047
./run_extra.sh mnist a adversarial carlini 6047
./run_extra.sh mnist a relu carlini 6047
./run_extra.sh mnist b standard carlini 6047
./run_extra.sh mnist b adversarial carlini 6047
./run_extra.sh mnist b relu carlini 6047
./run_extra.sh mnist c standard carlini 6047
./run_extra.sh mnist c adversarial carlini 6047
./run_extra.sh mnist c relu carlini 6047
./run_extra.sh mnist a standard carlini 3443
./run_extra.sh mnist a adversarial carlini 3443
./run_extra.sh mnist a relu carlini 3443
./run_extra.sh mnist b standard carlini 3443
./run_extra.sh mnist b adversarial carlini 3443
./run_extra.sh mnist b relu carlini 3443
./run_extra.sh mnist c standard carlini 3443
./run_extra.sh mnist c adversarial carlini 3443
./run_extra.sh mnist c relu carlini 3443
./run_extra.sh mnist a standard carlini 2853
./run_extra.sh mnist a adversarial carlini 2853
./run_extra.sh mnist a relu carlini 2853
./run_extra.sh mnist b standard carlini 2853
./run_extra.sh mnist b adversarial carlini 2853
./run_extra.sh mnist b relu carlini 2853
./run_extra.sh mnist c standard carlini 2853
./run_extra.sh mnist c adversarial carlini 2853
./run_extra.sh mnist c relu carlini 2853
./run_extra.sh mnist a standard carlini 2573
./run_extra.sh mnist a adversarial carlini 2573
./run_extra.sh mnist a relu carlini 2573
./run_extra.sh mnist b standard carlini 2573
./run_extra.sh mnist b adversarial carlini 2573
./run_extra.sh mnist b relu carlini 2573
./run_extra.sh mnist c standard carlini 2573
./run_extra.sh mnist c adversarial carlini 2573
./run_extra.sh mnist c relu carlini 2573
./run_extra.sh mnist a standard carlini 7677
./run_extra.sh mnist a adversarial carlini 7677
./run_extra.sh mnist a relu carlini 7677
./run_extra.sh mnist b standard carlini 7677
./run_extra.sh mnist b adversarial carlini 7677
./run_extra.sh mnist b relu carlini 7677
./run_extra.sh mnist c standard carlini 7677
./run_extra.sh mnist c adversarial carlini 7677
./run_extra.sh mnist c relu carlini 7677
./run_extra.sh mnist a standard carlini 9144
./run_extra.sh mnist a adversarial carlini 9144
./run_extra.sh mnist a relu carlini 9144
./run_extra.sh mnist b standard carlini 9144
