./run_extra.sh mnist a relu carlini 5287
./run_extra.sh mnist b standard carlini 5287
./run_extra.sh mnist b adversarial carlini 5287
./run_extra.sh mnist b relu carlini 5287
./run_extra.sh mnist c standard carlini 5287
./run_extra.sh mnist c adversarial carlini 5287
./run_extra.sh mnist c relu carlini 5287
./run_extra.sh mnist a standard carlini 3006
./run_extra.sh mnist a adversarial carlini 3006
./run_extra.sh mnist a relu carlini 3006
./run_extra.sh mnist b standard carlini 3006
./run_extra.sh mnist b adversarial carlini 3006
./run_extra.sh mnist b relu carlini 3006
./run_extra.sh mnist c standard carlini 3006
./run_extra.sh mnist c adversarial carlini 3006
./run_extra.sh mnist c relu carlini 3006
./run_extra.sh mnist a standard carlini 855
./run_extra.sh mnist a adversarial carlini 855
./run_extra.sh mnist a relu carlini 855
./run_extra.sh mnist b standard carlini 855
./run_extra.sh mnist b adversarial carlini 855
./run_extra.sh mnist b relu carlini 855
./run_extra.sh mnist c standard carlini 855
./run_extra.sh mnist c adversarial carlini 855
./run_extra.sh mnist c relu carlini 855
./run_extra.sh mnist a standard carlini 3524
./run_extra.sh mnist a adversarial carlini 3524
./run_extra.sh mnist a relu carlini 3524
./run_extra.sh mnist b standard carlini 3524
./run_extra.sh mnist b adversarial carlini 3524
./run_extra.sh mnist b relu carlini 3524
./run_extra.sh mnist c standard carlini 3524
./run_extra.sh mnist c adversarial carlini 3524
./run_extra.sh mnist c relu carlini 3524
./run_extra.sh mnist a standard carlini 3229
./run_extra.sh mnist a adversarial carlini 3229
./run_extra.sh mnist a relu carlini 3229
./run_extra.sh mnist b standard carlini 3229
./run_extra.sh mnist b adversarial carlini 3229
./run_extra.sh mnist b relu carlini 3229
./run_extra.sh mnist c standard carlini 3229
./run_extra.sh mnist c adversarial carlini 3229
./run_extra.sh mnist c relu carlini 3229
./run_extra.sh mnist a standard carlini 2843
./run_extra.sh mnist a adversarial carlini 2843
./run_extra.sh mnist a relu carlini 2843
./run_extra.sh mnist b standard carlini 2843
./run_extra.sh mnist b adversarial carlini 2843
./run_extra.sh mnist b relu carlini 2843
./run_extra.sh mnist c standard carlini 2843
./run_extra.sh mnist c adversarial carlini 2843
./run_extra.sh mnist c relu carlini 2843
./run_extra.sh mnist a standard carlini 6069
./run_extra.sh mnist a adversarial carlini 6069
./run_extra.sh mnist a relu carlini 6069
./run_extra.sh mnist b standard carlini 6069
./run_extra.sh mnist b adversarial carlini 6069
./run_extra.sh mnist b relu carlini 6069
./run_extra.sh mnist c standard carlini 6069
./run_extra.sh mnist c adversarial carlini 6069
./run_extra.sh mnist c relu carlini 6069
./run_extra.sh mnist a standard carlini 3741
./run_extra.sh mnist a adversarial carlini 3741
./run_extra.sh mnist a relu carlini 3741
./run_extra.sh mnist b standard carlini 3741
./run_extra.sh mnist b adversarial carlini 3741
./run_extra.sh mnist b relu carlini 3741
./run_extra.sh mnist c standard carlini 3741
./run_extra.sh mnist c adversarial carlini 3741
./run_extra.sh mnist c relu carlini 3741
./run_extra.sh mnist a standard carlini 1838
./run_extra.sh mnist a adversarial carlini 1838
./run_extra.sh mnist a relu carlini 1838
./run_extra.sh mnist b standard carlini 1838
./run_extra.sh mnist b adversarial carlini 1838
./run_extra.sh mnist b relu carlini 1838
./run_extra.sh mnist c standard carlini 1838
./run_extra.sh mnist c adversarial carlini 1838
./run_extra.sh mnist c relu carlini 1838
./run_extra.sh mnist a standard carlini 603
./run_extra.sh mnist a adversarial carlini 603
./run_extra.sh mnist a relu carlini 603
./run_extra.sh mnist b standard carlini 603
./run_extra.sh mnist b adversarial carlini 603
./run_extra.sh mnist b relu carlini 603
./run_extra.sh mnist c standard carlini 603
./run_extra.sh mnist c adversarial carlini 603
./run_extra.sh mnist c relu carlini 603
./run_extra.sh mnist a standard carlini 7305
./run_extra.sh mnist a adversarial carlini 7305
./run_extra.sh mnist a relu carlini 7305
./run_extra.sh mnist b standard carlini 7305
./run_extra.sh mnist b adversarial carlini 7305
./run_extra.sh mnist b relu carlini 7305
./run_extra.sh mnist c standard carlini 7305
./run_extra.sh mnist c adversarial carlini 7305
./run_extra.sh mnist c relu carlini 7305
./run_extra.sh mnist a standard carlini 4192
./run_extra.sh mnist a adversarial carlini 4192
./run_extra.sh mnist a relu carlini 4192
./run_extra.sh mnist b standard carlini 4192
./run_extra.sh mnist b adversarial carlini 4192
./run_extra.sh mnist b relu carlini 4192
./run_extra.sh mnist c standard carlini 4192
./run_extra.sh mnist c adversarial carlini 4192
./run_extra.sh mnist c relu carlini 4192
./run_extra.sh mnist a standard carlini 5546
./run_extra.sh mnist a adversarial carlini 5546
./run_extra.sh mnist a relu carlini 5546
./run_extra.sh mnist b standard carlini 5546
./run_extra.sh mnist b adversarial carlini 5546
./run_extra.sh mnist b relu carlini 5546
./run_extra.sh mnist c standard carlini 5546
./run_extra.sh mnist c adversarial carlini 5546
./run_extra.sh mnist c relu carlini 5546
./run_extra.sh mnist a standard carlini 2215
./run_extra.sh mnist a adversarial carlini 2215
./run_extra.sh mnist a relu carlini 2215
./run_extra.sh mnist b standard carlini 2215
./run_extra.sh mnist b adversarial carlini 2215
./run_extra.sh mnist b relu carlini 2215
./run_extra.sh mnist c standard carlini 2215
./run_extra.sh mnist c adversarial carlini 2215
./run_extra.sh mnist c relu carlini 2215
./run_extra.sh mnist a standard carlini 7642
./run_extra.sh mnist a adversarial carlini 7642
./run_extra.sh mnist a relu carlini 7642
./run_extra.sh mnist b standard carlini 7642
./run_extra.sh mnist b adversarial carlini 7642
./run_extra.sh mnist b relu carlini 7642
./run_extra.sh mnist c standard carlini 7642
./run_extra.sh mnist c adversarial carlini 7642
./run_extra.sh mnist c relu carlini 7642
./run_extra.sh mnist a standard carlini 7317
./run_extra.sh mnist a adversarial carlini 7317
./run_extra.sh mnist a relu carlini 7317
./run_extra.sh mnist b standard carlini 7317
./run_extra.sh mnist b adversarial carlini 7317
./run_extra.sh mnist b relu carlini 7317
./run_extra.sh mnist c standard carlini 7317
./run_extra.sh mnist c adversarial carlini 7317
./run_extra.sh mnist c relu carlini 7317
./run_extra.sh mnist a standard carlini 8074
./run_extra.sh mnist a adversarial carlini 8074
./run_extra.sh mnist a relu carlini 8074
./run_extra.sh mnist b standard carlini 8074
./run_extra.sh mnist b adversarial carlini 8074
./run_extra.sh mnist b relu carlini 8074
./run_extra.sh mnist c standard carlini 8074
./run_extra.sh mnist c adversarial carlini 8074
./run_extra.sh mnist c relu carlini 8074
./run_extra.sh mnist a standard carlini 3881
./run_extra.sh mnist a adversarial carlini 3881
./run_extra.sh mnist a relu carlini 3881
./run_extra.sh mnist b standard carlini 3881
./run_extra.sh mnist b adversarial carlini 3881
./run_extra.sh mnist b relu carlini 3881
./run_extra.sh mnist c standard carlini 3881
./run_extra.sh mnist c adversarial carlini 3881
./run_extra.sh mnist c relu carlini 3881
./run_extra.sh mnist a standard carlini 3217
./run_extra.sh mnist a adversarial carlini 3217
./run_extra.sh mnist a relu carlini 3217
./run_extra.sh mnist b standard carlini 3217
./run_extra.sh mnist b adversarial carlini 3217
./run_extra.sh mnist b relu carlini 3217
./run_extra.sh mnist c standard carlini 3217
./run_extra.sh mnist c adversarial carlini 3217
./run_extra.sh mnist c relu carlini 3217
./run_extra.sh mnist a standard carlini 4692
./run_extra.sh mnist a adversarial carlini 4692
./run_extra.sh mnist a relu carlini 4692
./run_extra.sh mnist b standard carlini 4692
./run_extra.sh mnist b adversarial carlini 4692
./run_extra.sh mnist b relu carlini 4692
./run_extra.sh mnist c standard carlini 4692
./run_extra.sh mnist c adversarial carlini 4692
./run_extra.sh mnist c relu carlini 4692
./run_extra.sh mnist a standard carlini 4729
./run_extra.sh mnist a adversarial carlini 4729
./run_extra.sh mnist a relu carlini 4729
./run_extra.sh mnist b standard carlini 4729
./run_extra.sh mnist b adversarial carlini 4729
./run_extra.sh mnist b relu carlini 4729
./run_extra.sh mnist c standard carlini 4729
./run_extra.sh mnist c adversarial carlini 4729
./run_extra.sh mnist c relu carlini 4729
./run_extra.sh mnist a standard carlini 8147
./run_extra.sh mnist a adversarial carlini 8147
./run_extra.sh mnist a relu carlini 8147
./run_extra.sh mnist b standard carlini 8147
./run_extra.sh mnist b adversarial carlini 8147
./run_extra.sh mnist b relu carlini 8147
./run_extra.sh mnist c standard carlini 8147
./run_extra.sh mnist c adversarial carlini 8147
./run_extra.sh mnist c relu carlini 8147
./run_extra.sh mnist a standard carlini 6712
./run_extra.sh mnist a adversarial carlini 6712
./run_extra.sh mnist a relu carlini 6712
./run_extra.sh mnist b standard carlini 6712
./run_extra.sh mnist b adversarial carlini 6712
./run_extra.sh mnist b relu carlini 6712
./run_extra.sh mnist c standard carlini 6712
./run_extra.sh mnist c adversarial carlini 6712
./run_extra.sh mnist c relu carlini 6712
./run_extra.sh mnist a standard carlini 5841
./run_extra.sh mnist a adversarial carlini 5841
./run_extra.sh mnist a relu carlini 5841
./run_extra.sh mnist b standard carlini 5841
./run_extra.sh mnist b adversarial carlini 5841
./run_extra.sh mnist b relu carlini 5841
./run_extra.sh mnist c standard carlini 5841
./run_extra.sh mnist c adversarial carlini 5841
./run_extra.sh mnist c relu carlini 5841
./run_extra.sh mnist a standard carlini 3090
./run_extra.sh mnist a adversarial carlini 3090
./run_extra.sh mnist a relu carlini 3090
./run_extra.sh mnist b standard carlini 3090
./run_extra.sh mnist b adversarial carlini 3090
./run_extra.sh mnist b relu carlini 3090
./run_extra.sh mnist c standard carlini 3090
./run_extra.sh mnist c adversarial carlini 3090
./run_extra.sh mnist c relu carlini 3090
./run_extra.sh mnist a standard carlini 8792
./run_extra.sh mnist a adversarial carlini 8792
./run_extra.sh mnist a relu carlini 8792
./run_extra.sh mnist b standard carlini 8792
./run_extra.sh mnist b adversarial carlini 8792
./run_extra.sh mnist b relu carlini 8792
./run_extra.sh mnist c standard carlini 8792
./run_extra.sh mnist c adversarial carlini 8792
./run_extra.sh mnist c relu carlini 8792
./run_extra.sh mnist a standard carlini 9272
./run_extra.sh mnist a adversarial carlini 9272
./run_extra.sh mnist a relu carlini 9272
./run_extra.sh mnist b standard carlini 9272
./run_extra.sh mnist b adversarial carlini 9272
./run_extra.sh mnist b relu carlini 9272
./run_extra.sh mnist c standard carlini 9272
./run_extra.sh mnist c adversarial carlini 9272
./run_extra.sh mnist c relu carlini 9272
./run_extra.sh mnist a standard carlini 1196
./run_extra.sh mnist a adversarial carlini 1196
./run_extra.sh mnist a relu carlini 1196
./run_extra.sh mnist b standard carlini 1196
./run_extra.sh mnist b adversarial carlini 1196
./run_extra.sh mnist b relu carlini 1196
./run_extra.sh mnist c standard carlini 1196
./run_extra.sh mnist c adversarial carlini 1196
./run_extra.sh mnist c relu carlini 1196
./run_extra.sh mnist a standard carlini 1204
./run_extra.sh mnist a adversarial carlini 1204
./run_extra.sh mnist a relu carlini 1204
./run_extra.sh mnist b standard carlini 1204
./run_extra.sh mnist b adversarial carlini 1204
./run_extra.sh mnist b relu carlini 1204
./run_extra.sh mnist c standard carlini 1204
./run_extra.sh mnist c adversarial carlini 1204
./run_extra.sh mnist c relu carlini 1204
./run_extra.sh mnist a standard carlini 6715
./run_extra.sh mnist a adversarial carlini 6715
./run_extra.sh mnist a relu carlini 6715
./run_extra.sh mnist b standard carlini 6715
./run_extra.sh mnist b adversarial carlini 6715
./run_extra.sh mnist b relu carlini 6715
./run_extra.sh mnist c standard carlini 6715
./run_extra.sh mnist c adversarial carlini 6715
./run_extra.sh mnist c relu carlini 6715
./run_extra.sh mnist a standard carlini 8089
./run_extra.sh mnist a adversarial carlini 8089
./run_extra.sh mnist a relu carlini 8089
./run_extra.sh mnist b standard carlini 8089
./run_extra.sh mnist b adversarial carlini 8089
./run_extra.sh mnist b relu carlini 8089
./run_extra.sh mnist c standard carlini 8089
./run_extra.sh mnist c adversarial carlini 8089
./run_extra.sh mnist c relu carlini 8089
./run_extra.sh mnist a standard carlini 9275
./run_extra.sh mnist a adversarial carlini 9275
./run_extra.sh mnist a relu carlini 9275
./run_extra.sh mnist b standard carlini 9275
./run_extra.sh mnist b adversarial carlini 9275
./run_extra.sh mnist b relu carlini 9275
./run_extra.sh mnist c standard carlini 9275
./run_extra.sh mnist c adversarial carlini 9275
./run_extra.sh mnist c relu carlini 9275
./run_extra.sh mnist a standard carlini 8434
./run_extra.sh mnist a adversarial carlini 8434
./run_extra.sh mnist a relu carlini 8434
./run_extra.sh mnist b standard carlini 8434
./run_extra.sh mnist b adversarial carlini 8434
./run_extra.sh mnist b relu carlini 8434
./run_extra.sh mnist c standard carlini 8434
./run_extra.sh mnist c adversarial carlini 8434
./run_extra.sh mnist c relu carlini 8434
./run_extra.sh mnist a standard carlini 3292
./run_extra.sh mnist a adversarial carlini 3292
./run_extra.sh mnist a relu carlini 3292
./run_extra.sh mnist b standard carlini 3292
./run_extra.sh mnist b adversarial carlini 3292
./run_extra.sh mnist b relu carlini 3292
./run_extra.sh mnist c standard carlini 3292
./run_extra.sh mnist c adversarial carlini 3292
./run_extra.sh mnist c relu carlini 3292
./run_extra.sh mnist a standard carlini 993
./run_extra.sh mnist a adversarial carlini 993
./run_extra.sh mnist a relu carlini 993
./run_extra.sh mnist b standard carlini 993
./run_extra.sh mnist b adversarial carlini 993
./run_extra.sh mnist b relu carlini 993
./run_extra.sh mnist c standard carlini 993
./run_extra.sh mnist c adversarial carlini 993
./run_extra.sh mnist c relu carlini 993
./run_extra.sh mnist a standard carlini 5636
./run_extra.sh mnist a adversarial carlini 5636
./run_extra.sh mnist a relu carlini 5636
./run_extra.sh mnist b standard carlini 5636
./run_extra.sh mnist b adversarial carlini 5636
./run_extra.sh mnist b relu carlini 5636
./run_extra.sh mnist c standard carlini 5636
./run_extra.sh mnist c adversarial carlini 5636
./run_extra.sh mnist c relu carlini 5636
./run_extra.sh mnist a standard carlini 8850
./run_extra.sh mnist a adversarial carlini 8850
./run_extra.sh mnist a relu carlini 8850
./run_extra.sh mnist b standard carlini 8850
./run_extra.sh mnist b adversarial carlini 8850
./run_extra.sh mnist b relu carlini 8850
./run_extra.sh mnist c standard carlini 8850
./run_extra.sh mnist c adversarial carlini 8850
./run_extra.sh mnist c relu carlini 8850
./run_extra.sh mnist a standard carlini 9612
./run_extra.sh mnist a adversarial carlini 9612
./run_extra.sh mnist a relu carlini 9612
./run_extra.sh mnist b standard carlini 9612
./run_extra.sh mnist b adversarial carlini 9612
./run_extra.sh mnist b relu carlini 9612
./run_extra.sh mnist c standard carlini 9612
./run_extra.sh mnist c adversarial carlini 9612
./run_extra.sh mnist c relu carlini 9612
./run_extra.sh mnist a standard carlini 2253
./run_extra.sh mnist a adversarial carlini 2253
./run_extra.sh mnist a relu carlini 2253
./run_extra.sh mnist b standard carlini 2253
./run_extra.sh mnist b adversarial carlini 2253
./run_extra.sh mnist b relu carlini 2253
./run_extra.sh mnist c standard carlini 2253
./run_extra.sh mnist c adversarial carlini 2253
./run_extra.sh mnist c relu carlini 2253
./run_extra.sh mnist a standard carlini 7482
./run_extra.sh mnist a adversarial carlini 7482
./run_extra.sh mnist a relu carlini 7482
./run_extra.sh mnist b standard carlini 7482
./run_extra.sh mnist b adversarial carlini 7482
./run_extra.sh mnist b relu carlini 7482
./run_extra.sh mnist c standard carlini 7482
./run_extra.sh mnist c adversarial carlini 7482
./run_extra.sh mnist c relu carlini 7482
./run_extra.sh mnist a standard carlini 3779
./run_extra.sh mnist a adversarial carlini 3779
./run_extra.sh mnist a relu carlini 3779
./run_extra.sh mnist b standard carlini 3779
./run_extra.sh mnist b adversarial carlini 3779
./run_extra.sh mnist b relu carlini 3779
./run_extra.sh mnist c standard carlini 3779
./run_extra.sh mnist c adversarial carlini 3779
./run_extra.sh mnist c relu carlini 3779
./run_extra.sh mnist a standard carlini 6502
./run_extra.sh mnist a adversarial carlini 6502
./run_extra.sh mnist a relu carlini 6502
./run_extra.sh mnist b standard carlini 6502
./run_extra.sh mnist b adversarial carlini 6502
./run_extra.sh mnist b relu carlini 6502
./run_extra.sh mnist c standard carlini 6502
./run_extra.sh mnist c adversarial carlini 6502
./run_extra.sh mnist c relu carlini 6502
./run_extra.sh mnist a standard carlini 9687
./run_extra.sh mnist a adversarial carlini 9687
./run_extra.sh mnist a relu carlini 9687
./run_extra.sh mnist b standard carlini 9687
./run_extra.sh mnist b adversarial carlini 9687
./run_extra.sh mnist b relu carlini 9687
./run_extra.sh mnist c standard carlini 9687
./run_extra.sh mnist c adversarial carlini 9687
./run_extra.sh mnist c relu carlini 9687
./run_extra.sh mnist a standard carlini 8217
./run_extra.sh mnist a adversarial carlini 8217
./run_extra.sh mnist a relu carlini 8217
./run_extra.sh mnist b standard carlini 8217
./run_extra.sh mnist b adversarial carlini 8217
./run_extra.sh mnist b relu carlini 8217
./run_extra.sh mnist c standard carlini 8217
./run_extra.sh mnist c adversarial carlini 8217
./run_extra.sh mnist c relu carlini 8217
./run_extra.sh mnist a standard carlini 4650
./run_extra.sh mnist a adversarial carlini 4650
./run_extra.sh mnist a relu carlini 4650
./run_extra.sh mnist b standard carlini 4650
./run_extra.sh mnist b adversarial carlini 4650
./run_extra.sh mnist b relu carlini 4650
./run_extra.sh mnist c standard carlini 4650
./run_extra.sh mnist c adversarial carlini 4650
./run_extra.sh mnist c relu carlini 4650
./run_extra.sh mnist a standard carlini 9902
./run_extra.sh mnist a adversarial carlini 9902
./run_extra.sh mnist a relu carlini 9902
./run_extra.sh mnist b standard carlini 9902
./run_extra.sh mnist b adversarial carlini 9902
./run_extra.sh mnist b relu carlini 9902
./run_extra.sh mnist c standard carlini 9902
./run_extra.sh mnist c adversarial carlini 9902
./run_extra.sh mnist c relu carlini 9902
./run_extra.sh mnist a standard carlini 2293
./run_extra.sh mnist a adversarial carlini 2293
./run_extra.sh mnist a relu carlini 2293
./run_extra.sh mnist b standard carlini 2293
./run_extra.sh mnist b adversarial carlini 2293
./run_extra.sh mnist b relu carlini 2293
./run_extra.sh mnist c standard carlini 2293
./run_extra.sh mnist c adversarial carlini 2293
./run_extra.sh mnist c relu carlini 2293
./run_extra.sh mnist a standard carlini 4450
./run_extra.sh mnist a adversarial carlini 4450
./run_extra.sh mnist a relu carlini 4450
./run_extra.sh mnist b standard carlini 4450
./run_extra.sh mnist b adversarial carlini 4450
./run_extra.sh mnist b relu carlini 4450
./run_extra.sh mnist c standard carlini 4450
./run_extra.sh mnist c adversarial carlini 4450
./run_extra.sh mnist c relu carlini 4450
./run_extra.sh mnist a standard carlini 3028
./run_extra.sh mnist a adversarial carlini 3028
./run_extra.sh mnist a relu carlini 3028
./run_extra.sh mnist b standard carlini 3028
./run_extra.sh mnist b adversarial carlini 3028
./run_extra.sh mnist b relu carlini 3028
./run_extra.sh mnist c standard carlini 3028
./run_extra.sh mnist c adversarial carlini 3028
./run_extra.sh mnist c relu carlini 3028
./run_extra.sh mnist a standard carlini 6718
./run_extra.sh mnist a adversarial carlini 6718
./run_extra.sh mnist a relu carlini 6718
./run_extra.sh mnist b standard carlini 6718
./run_extra.sh mnist b adversarial carlini 6718
./run_extra.sh mnist b relu carlini 6718
./run_extra.sh mnist c standard carlini 6718
./run_extra.sh mnist c adversarial carlini 6718
./run_extra.sh mnist c relu carlini 6718
./run_extra.sh mnist a standard carlini 8691
./run_extra.sh mnist a adversarial carlini 8691
./run_extra.sh mnist a relu carlini 8691
./run_extra.sh mnist b standard carlini 8691
./run_extra.sh mnist b adversarial carlini 8691
./run_extra.sh mnist b relu carlini 8691
./run_extra.sh mnist c standard carlini 8691
./run_extra.sh mnist c adversarial carlini 8691
./run_extra.sh mnist c relu carlini 8691
./run_extra.sh mnist a standard carlini 6970
./run_extra.sh mnist a adversarial carlini 6970
./run_extra.sh mnist a relu carlini 6970
./run_extra.sh mnist b standard carlini 6970
./run_extra.sh mnist b adversarial carlini 6970
./run_extra.sh mnist b relu carlini 6970
./run_extra.sh mnist c standard carlini 6970
./run_extra.sh mnist c adversarial carlini 6970
./run_extra.sh mnist c relu carlini 6970
./run_extra.sh mnist a standard carlini 5945
./run_extra.sh mnist a adversarial carlini 5945
./run_extra.sh mnist a relu carlini 5945
./run_extra.sh mnist b standard carlini 5945
./run_extra.sh mnist b adversarial carlini 5945
./run_extra.sh mnist b relu carlini 5945
./run_extra.sh mnist c standard carlini 5945
./run_extra.sh mnist c adversarial carlini 5945
./run_extra.sh mnist c relu carlini 5945
./run_extra.sh mnist a standard carlini 7458
./run_extra.sh mnist a adversarial carlini 7458
./run_extra.sh mnist a relu carlini 7458
./run_extra.sh mnist b standard carlini 7458
./run_extra.sh mnist b adversarial carlini 7458
./run_extra.sh mnist b relu carlini 7458
./run_extra.sh mnist c standard carlini 7458
./run_extra.sh mnist c adversarial carlini 7458
./run_extra.sh mnist c relu carlini 7458
./run_extra.sh mnist a standard carlini 3170
./run_extra.sh mnist a adversarial carlini 3170
./run_extra.sh mnist a relu carlini 3170
./run_extra.sh mnist b standard carlini 3170
./run_extra.sh mnist b adversarial carlini 3170
./run_extra.sh mnist b relu carlini 3170
./run_extra.sh mnist c standard carlini 3170
./run_extra.sh mnist c adversarial carlini 3170
./run_extra.sh mnist c relu carlini 3170
./run_extra.sh mnist a standard carlini 8346
./run_extra.sh mnist a adversarial carlini 8346
./run_extra.sh mnist a relu carlini 8346
./run_extra.sh mnist b standard carlini 8346
./run_extra.sh mnist b adversarial carlini 8346
./run_extra.sh mnist b relu carlini 8346
./run_extra.sh mnist c standard carlini 8346
./run_extra.sh mnist c adversarial carlini 8346
./run_extra.sh mnist c relu carlini 8346
./run_extra.sh mnist a standard carlini 7164
./run_extra.sh mnist a adversarial carlini 7164
./run_extra.sh mnist a relu carlini 7164
./run_extra.sh mnist b standard carlini 7164
./run_extra.sh mnist b adversarial carlini 7164
./run_extra.sh mnist b relu carlini 7164
./run_extra.sh mnist c standard carlini 7164
./run_extra.sh mnist c adversarial carlini 7164
./run_extra.sh mnist c relu carlini 7164
./run_extra.sh mnist a standard carlini 3271
./run_extra.sh mnist a adversarial carlini 3271
./run_extra.sh mnist a relu carlini 3271
./run_extra.sh mnist b standard carlini 3271
./run_extra.sh mnist b adversarial carlini 3271
./run_extra.sh mnist b relu carlini 3271
./run_extra.sh mnist c standard carlini 3271
./run_extra.sh mnist c adversarial carlini 3271
./run_extra.sh mnist c relu carlini 3271
./run_extra.sh mnist a standard carlini 5149
./run_extra.sh mnist a adversarial carlini 5149
./run_extra.sh mnist a relu carlini 5149
./run_extra.sh mnist b standard carlini 5149
./run_extra.sh mnist b adversarial carlini 5149
./run_extra.sh mnist b relu carlini 5149
./run_extra.sh mnist c standard carlini 5149
./run_extra.sh mnist c adversarial carlini 5149
./run_extra.sh mnist c relu carlini 5149
./run_extra.sh mnist a standard carlini 4063
./run_extra.sh mnist a adversarial carlini 4063
./run_extra.sh mnist a relu carlini 4063
./run_extra.sh mnist b standard carlini 4063
./run_extra.sh mnist b adversarial carlini 4063
./run_extra.sh mnist b relu carlini 4063
./run_extra.sh mnist c standard carlini 4063
./run_extra.sh mnist c adversarial carlini 4063
./run_extra.sh mnist c relu carlini 4063
./run_extra.sh mnist a standard carlini 1049
./run_extra.sh mnist a adversarial carlini 1049
./run_extra.sh mnist a relu carlini 1049
./run_extra.sh mnist b standard carlini 1049
./run_extra.sh mnist b adversarial carlini 1049
./run_extra.sh mnist b relu carlini 1049
./run_extra.sh mnist c standard carlini 1049
./run_extra.sh mnist c adversarial carlini 1049
./run_extra.sh mnist c relu carlini 1049
./run_extra.sh mnist a standard carlini 9869
./run_extra.sh mnist a adversarial carlini 9869
./run_extra.sh mnist a relu carlini 9869
./run_extra.sh mnist b standard carlini 9869
./run_extra.sh mnist b adversarial carlini 9869
./run_extra.sh mnist b relu carlini 9869
./run_extra.sh mnist c standard carlini 9869
./run_extra.sh mnist c adversarial carlini 9869
./run_extra.sh mnist c relu carlini 9869
./run_extra.sh mnist a standard carlini 5449
./run_extra.sh mnist a adversarial carlini 5449
./run_extra.sh mnist a relu carlini 5449
./run_extra.sh mnist b standard carlini 5449
./run_extra.sh mnist b adversarial carlini 5449
./run_extra.sh mnist b relu carlini 5449
./run_extra.sh mnist c standard carlini 5449
./run_extra.sh mnist c adversarial carlini 5449
./run_extra.sh mnist c relu carlini 5449
./run_extra.sh mnist a standard carlini 6546
./run_extra.sh mnist a adversarial carlini 6546
./run_extra.sh mnist a relu carlini 6546
./run_extra.sh mnist b standard carlini 6546
./run_extra.sh mnist b adversarial carlini 6546
./run_extra.sh mnist b relu carlini 6546
./run_extra.sh mnist c standard carlini 6546
./run_extra.sh mnist c adversarial carlini 6546
./run_extra.sh mnist c relu carlini 6546
./run_extra.sh mnist a standard carlini 5221
./run_extra.sh mnist a adversarial carlini 5221
./run_extra.sh mnist a relu carlini 5221
./run_extra.sh mnist b standard carlini 5221
./run_extra.sh mnist b adversarial carlini 5221
./run_extra.sh mnist b relu carlini 5221
./run_extra.sh mnist c standard carlini 5221
./run_extra.sh mnist c adversarial carlini 5221
./run_extra.sh mnist c relu carlini 5221
./run_extra.sh mnist a standard carlini 6937
./run_extra.sh mnist a adversarial carlini 6937
./run_extra.sh mnist a relu carlini 6937
./run_extra.sh mnist b standard carlini 6937
./run_extra.sh mnist b adversarial carlini 6937
./run_extra.sh mnist b relu carlini 6937
./run_extra.sh mnist c standard carlini 6937
./run_extra.sh mnist c adversarial carlini 6937
./run_extra.sh mnist c relu carlini 6937
./run_extra.sh mnist a standard carlini 5567
./run_extra.sh mnist a adversarial carlini 5567
./run_extra.sh mnist a relu carlini 5567
./run_extra.sh mnist b standard carlini 5567
./run_extra.sh mnist b adversarial carlini 5567
./run_extra.sh mnist b relu carlini 5567
./run_extra.sh mnist c standard carlini 5567
./run_extra.sh mnist c adversarial carlini 5567
./run_extra.sh mnist c relu carlini 5567
./run_extra.sh mnist a standard carlini 6479
./run_extra.sh mnist a adversarial carlini 6479
./run_extra.sh mnist a relu carlini 6479
./run_extra.sh mnist b standard carlini 6479
./run_extra.sh mnist b adversarial carlini 6479
./run_extra.sh mnist b relu carlini 6479
./run_extra.sh mnist c standard carlini 6479
./run_extra.sh mnist c adversarial carlini 6479
./run_extra.sh mnist c relu carlini 6479
./run_extra.sh mnist a standard carlini 3875
./run_extra.sh mnist a adversarial carlini 3875
./run_extra.sh mnist a relu carlini 3875
./run_extra.sh mnist b standard carlini 3875
./run_extra.sh mnist b adversarial carlini 3875
./run_extra.sh mnist b relu carlini 3875
./run_extra.sh mnist c standard carlini 3875
./run_extra.sh mnist c adversarial carlini 3875
./run_extra.sh mnist c relu carlini 3875
./run_extra.sh mnist a standard carlini 7015
./run_extra.sh mnist a adversarial carlini 7015
./run_extra.sh mnist a relu carlini 7015
./run_extra.sh mnist b standard carlini 7015
./run_extra.sh mnist b adversarial carlini 7015
./run_extra.sh mnist b relu carlini 7015
./run_extra.sh mnist c standard carlini 7015
./run_extra.sh mnist c adversarial carlini 7015
./run_extra.sh mnist c relu carlini 7015
./run_extra.sh mnist a standard carlini 2629
./run_extra.sh mnist a adversarial carlini 2629
./run_extra.sh mnist a relu carlini 2629
./run_extra.sh mnist b standard carlini 2629
./run_extra.sh mnist b adversarial carlini 2629
./run_extra.sh mnist b relu carlini 2629
./run_extra.sh mnist c standard carlini 2629
./run_extra.sh mnist c adversarial carlini 2629
./run_extra.sh mnist c relu carlini 2629
./run_extra.sh mnist a standard carlini 9271
./run_extra.sh mnist a adversarial carlini 9271
./run_extra.sh mnist a relu carlini 9271
./run_extra.sh mnist b standard carlini 9271
./run_extra.sh mnist b adversarial carlini 9271
./run_extra.sh mnist b relu carlini 9271
./run_extra.sh mnist c standard carlini 9271
./run_extra.sh mnist c adversarial carlini 9271
./run_extra.sh mnist c relu carlini 9271
./run_extra.sh mnist a standard carlini 7640
./run_extra.sh mnist a adversarial carlini 7640
./run_extra.sh mnist a relu carlini 7640
./run_extra.sh mnist b standard carlini 7640
./run_extra.sh mnist b adversarial carlini 7640
./run_extra.sh mnist b relu carlini 7640
./run_extra.sh mnist c standard carlini 7640
./run_extra.sh mnist c adversarial carlini 7640
./run_extra.sh mnist c relu carlini 7640
./run_extra.sh mnist a standard carlini 9326
./run_extra.sh mnist a adversarial carlini 9326
./run_extra.sh mnist a relu carlini 9326
./run_extra.sh mnist b standard carlini 9326
./run_extra.sh mnist b adversarial carlini 9326
./run_extra.sh mnist b relu carlini 9326
./run_extra.sh mnist c standard carlini 9326
./run_extra.sh mnist c adversarial carlini 9326
./run_extra.sh mnist c relu carlini 9326
./run_extra.sh mnist a standard carlini 6596
./run_extra.sh mnist a adversarial carlini 6596
./run_extra.sh mnist a relu carlini 6596
./run_extra.sh mnist b standard carlini 6596
./run_extra.sh mnist b adversarial carlini 6596
./run_extra.sh mnist b relu carlini 6596
./run_extra.sh mnist c standard carlini 6596
./run_extra.sh mnist c adversarial carlini 6596
./run_extra.sh mnist c relu carlini 6596
./run_extra.sh mnist a standard carlini 8698
./run_extra.sh mnist a adversarial carlini 8698
./run_extra.sh mnist a relu carlini 8698
./run_extra.sh mnist b standard carlini 8698
./run_extra.sh mnist b adversarial carlini 8698
./run_extra.sh mnist b relu carlini 8698
./run_extra.sh mnist c standard carlini 8698
./run_extra.sh mnist c adversarial carlini 8698
./run_extra.sh mnist c relu carlini 8698
./run_extra.sh mnist a standard carlini 9454
./run_extra.sh mnist a adversarial carlini 9454
./run_extra.sh mnist a relu carlini 9454
./run_extra.sh mnist b standard carlini 9454
./run_extra.sh mnist b adversarial carlini 9454
./run_extra.sh mnist b relu carlini 9454
./run_extra.sh mnist c standard carlini 9454
./run_extra.sh mnist c adversarial carlini 9454
./run_extra.sh mnist c relu carlini 9454
./run_extra.sh mnist a standard carlini 2082
./run_extra.sh mnist a adversarial carlini 2082
./run_extra.sh mnist a relu carlini 2082
./run_extra.sh mnist b standard carlini 2082
./run_extra.sh mnist b adversarial carlini 2082
./run_extra.sh mnist b relu carlini 2082
./run_extra.sh mnist c standard carlini 2082
./run_extra.sh mnist c adversarial carlini 2082
./run_extra.sh mnist c relu carlini 2082
./run_extra.sh mnist a standard carlini 3338
./run_extra.sh mnist a adversarial carlini 3338
./run_extra.sh mnist a relu carlini 3338
./run_extra.sh mnist b standard carlini 3338
./run_extra.sh mnist b adversarial carlini 3338
./run_extra.sh mnist b relu carlini 3338
./run_extra.sh mnist c standard carlini 3338
./run_extra.sh mnist c adversarial carlini 3338
./run_extra.sh mnist c relu carlini 3338
./run_extra.sh mnist a standard carlini 389
./run_extra.sh mnist a adversarial carlini 389
./run_extra.sh mnist a relu carlini 389
./run_extra.sh mnist b standard carlini 389
./run_extra.sh mnist b adversarial carlini 389
./run_extra.sh mnist b relu carlini 389
./run_extra.sh mnist c standard carlini 389
./run_extra.sh mnist c adversarial carlini 389
./run_extra.sh mnist c relu carlini 389
./run_extra.sh mnist a standard carlini 5974
./run_extra.sh mnist a adversarial carlini 5974
./run_extra.sh mnist a relu carlini 5974
./run_extra.sh mnist b standard carlini 5974
./run_extra.sh mnist b adversarial carlini 5974
./run_extra.sh mnist b relu carlini 5974
./run_extra.sh mnist c standard carlini 5974
./run_extra.sh mnist c adversarial carlini 5974
./run_extra.sh mnist c relu carlini 5974
./run_extra.sh mnist a standard carlini 2421
./run_extra.sh mnist a adversarial carlini 2421
./run_extra.sh mnist a relu carlini 2421
./run_extra.sh mnist b standard carlini 2421
./run_extra.sh mnist b adversarial carlini 2421
./run_extra.sh mnist b relu carlini 2421
./run_extra.sh mnist c standard carlini 2421
./run_extra.sh mnist c adversarial carlini 2421
./run_extra.sh mnist c relu carlini 2421
./run_extra.sh mnist a standard carlini 7339
./run_extra.sh mnist a adversarial carlini 7339
./run_extra.sh mnist a relu carlini 7339
./run_extra.sh mnist b standard carlini 7339
./run_extra.sh mnist b adversarial carlini 7339
./run_extra.sh mnist b relu carlini 7339
./run_extra.sh mnist c standard carlini 7339
./run_extra.sh mnist c adversarial carlini 7339
./run_extra.sh mnist c relu carlini 7339
./run_extra.sh mnist a standard carlini 7778
./run_extra.sh mnist a adversarial carlini 7778
./run_extra.sh mnist a relu carlini 7778
./run_extra.sh mnist b standard carlini 7778
./run_extra.sh mnist b adversarial carlini 7778
./run_extra.sh mnist b relu carlini 7778
./run_extra.sh mnist c standard carlini 7778
./run_extra.sh mnist c adversarial carlini 7778
./run_extra.sh mnist c relu carlini 7778
./run_extra.sh mnist a standard carlini 6921
./run_extra.sh mnist a adversarial carlini 6921
./run_extra.sh mnist a relu carlini 6921
./run_extra.sh mnist b standard carlini 6921
./run_extra.sh mnist b adversarial carlini 6921
./run_extra.sh mnist b relu carlini 6921
./run_extra.sh mnist c standard carlini 6921
./run_extra.sh mnist c adversarial carlini 6921
./run_extra.sh mnist c relu carlini 6921
./run_extra.sh mnist a standard carlini 6955
./run_extra.sh mnist a adversarial carlini 6955
./run_extra.sh mnist a relu carlini 6955
./run_extra.sh mnist b standard carlini 6955
./run_extra.sh mnist b adversarial carlini 6955
./run_extra.sh mnist b relu carlini 6955
./run_extra.sh mnist c standard carlini 6955
./run_extra.sh mnist c adversarial carlini 6955
./run_extra.sh mnist c relu carlini 6955
./run_extra.sh mnist a standard carlini 3145
./run_extra.sh mnist a adversarial carlini 3145
./run_extra.sh mnist a relu carlini 3145
./run_extra.sh mnist b standard carlini 3145
./run_extra.sh mnist b adversarial carlini 3145
./run_extra.sh mnist b relu carlini 3145
./run_extra.sh mnist c standard carlini 3145
./run_extra.sh mnist c adversarial carlini 3145
./run_extra.sh mnist c relu carlini 3145
./run_extra.sh mnist a standard carlini 1093
./run_extra.sh mnist a adversarial carlini 1093
./run_extra.sh mnist a relu carlini 1093
./run_extra.sh mnist b standard carlini 1093
./run_extra.sh mnist b adversarial carlini 1093
./run_extra.sh mnist b relu carlini 1093
./run_extra.sh mnist c standard carlini 1093
./run_extra.sh mnist c adversarial carlini 1093
./run_extra.sh mnist c relu carlini 1093
./run_extra.sh mnist a standard carlini 2067
./run_extra.sh mnist a adversarial carlini 2067
./run_extra.sh mnist a relu carlini 2067
./run_extra.sh mnist b standard carlini 2067
./run_extra.sh mnist b adversarial carlini 2067
./run_extra.sh mnist b relu carlini 2067
./run_extra.sh mnist c standard carlini 2067
./run_extra.sh mnist c adversarial carlini 2067
./run_extra.sh mnist c relu carlini 2067
./run_extra.sh mnist a standard carlini 3176
./run_extra.sh mnist a adversarial carlini 3176
./run_extra.sh mnist a relu carlini 3176
./run_extra.sh mnist b standard carlini 3176
./run_extra.sh mnist b adversarial carlini 3176
./run_extra.sh mnist b relu carlini 3176
./run_extra.sh mnist c standard carlini 3176
./run_extra.sh mnist c adversarial carlini 3176
./run_extra.sh mnist c relu carlini 3176
./run_extra.sh mnist a standard carlini 1127
./run_extra.sh mnist a adversarial carlini 1127
./run_extra.sh mnist a relu carlini 1127
./run_extra.sh mnist b standard carlini 1127
./run_extra.sh mnist b adversarial carlini 1127
./run_extra.sh mnist b relu carlini 1127
./run_extra.sh mnist c standard carlini 1127
./run_extra.sh mnist c adversarial carlini 1127
./run_extra.sh mnist c relu carlini 1127
./run_extra.sh mnist a standard carlini 4184
./run_extra.sh mnist a adversarial carlini 4184
./run_extra.sh mnist a relu carlini 4184
./run_extra.sh mnist b standard carlini 4184
./run_extra.sh mnist b adversarial carlini 4184
./run_extra.sh mnist b relu carlini 4184
./run_extra.sh mnist c standard carlini 4184
./run_extra.sh mnist c adversarial carlini 4184
./run_extra.sh mnist c relu carlini 4184
./run_extra.sh mnist a standard carlini 5206
./run_extra.sh mnist a adversarial carlini 5206
./run_extra.sh mnist a relu carlini 5206
./run_extra.sh mnist b standard carlini 5206
./run_extra.sh mnist b adversarial carlini 5206
./run_extra.sh mnist b relu carlini 5206
./run_extra.sh mnist c standard carlini 5206
./run_extra.sh mnist c adversarial carlini 5206
./run_extra.sh mnist c relu carlini 5206
./run_extra.sh mnist a standard carlini 2242
./run_extra.sh mnist a adversarial carlini 2242
./run_extra.sh mnist a relu carlini 2242
./run_extra.sh mnist b standard carlini 2242
./run_extra.sh mnist b adversarial carlini 2242
./run_extra.sh mnist b relu carlini 2242
./run_extra.sh mnist c standard carlini 2242
./run_extra.sh mnist c adversarial carlini 2242
./run_extra.sh mnist c relu carlini 2242
./run_extra.sh mnist a standard carlini 646
./run_extra.sh mnist a adversarial carlini 646
./run_extra.sh mnist a relu carlini 646
./run_extra.sh mnist b standard carlini 646
./run_extra.sh mnist b adversarial carlini 646
./run_extra.sh mnist b relu carlini 646
./run_extra.sh mnist c standard carlini 646
./run_extra.sh mnist c adversarial carlini 646
./run_extra.sh mnist c relu carlini 646
./run_extra.sh mnist a standard carlini 1833
./run_extra.sh mnist a adversarial carlini 1833
./run_extra.sh mnist a relu carlini 1833
./run_extra.sh mnist b standard carlini 1833
./run_extra.sh mnist b adversarial carlini 1833
./run_extra.sh mnist b relu carlini 1833
./run_extra.sh mnist c standard carlini 1833
./run_extra.sh mnist c adversarial carlini 1833
./run_extra.sh mnist c relu carlini 1833
./run_extra.sh mnist a standard carlini 462
./run_extra.sh mnist a adversarial carlini 462
./run_extra.sh mnist a relu carlini 462
./run_extra.sh mnist b standard carlini 462
./run_extra.sh mnist b adversarial carlini 462
./run_extra.sh mnist b relu carlini 462
./run_extra.sh mnist c standard carlini 462
./run_extra.sh mnist c adversarial carlini 462
./run_extra.sh mnist c relu carlini 462
./run_extra.sh mnist a standard carlini 6114
./run_extra.sh mnist a adversarial carlini 6114
./run_extra.sh mnist a relu carlini 6114
./run_extra.sh mnist b standard carlini 6114
./run_extra.sh mnist b adversarial carlini 6114
./run_extra.sh mnist b relu carlini 6114
./run_extra.sh mnist c standard carlini 6114
./run_extra.sh mnist c adversarial carlini 6114
./run_extra.sh mnist c relu carlini 6114
./run_extra.sh mnist a standard carlini 3530
./run_extra.sh mnist a adversarial carlini 3530
./run_extra.sh mnist a relu carlini 3530
./run_extra.sh mnist b standard carlini 3530
./run_extra.sh mnist b adversarial carlini 3530
./run_extra.sh mnist b relu carlini 3530
./run_extra.sh mnist c standard carlini 3530
./run_extra.sh mnist c adversarial carlini 3530
./run_extra.sh mnist c relu carlini 3530
./run_extra.sh mnist a standard carlini 2068
./run_extra.sh mnist a adversarial carlini 2068
./run_extra.sh mnist a relu carlini 2068
./run_extra.sh mnist b standard carlini 2068
./run_extra.sh mnist b adversarial carlini 2068
./run_extra.sh mnist b relu carlini 2068
./run_extra.sh mnist c standard carlini 2068
./run_extra.sh mnist c adversarial carlini 2068
./run_extra.sh mnist c relu carlini 2068
./run_extra.sh mnist a standard carlini 6375
./run_extra.sh mnist a adversarial carlini 6375
./run_extra.sh mnist a relu carlini 6375
./run_extra.sh mnist b standard carlini 6375
./run_extra.sh mnist b adversarial carlini 6375
./run_extra.sh mnist b relu carlini 6375
./run_extra.sh mnist c standard carlini 6375
./run_extra.sh mnist c adversarial carlini 6375
./run_extra.sh mnist c relu carlini 6375
./run_extra.sh mnist a standard carlini 4467
./run_extra.sh mnist a adversarial carlini 4467
./run_extra.sh mnist a relu carlini 4467
./run_extra.sh mnist b standard carlini 4467
./run_extra.sh mnist b adversarial carlini 4467
./run_extra.sh mnist b relu carlini 4467
./run_extra.sh mnist c standard carlini 4467
./run_extra.sh mnist c adversarial carlini 4467
./run_extra.sh mnist c relu carlini 4467
./run_extra.sh mnist a standard carlini 7487
./run_extra.sh mnist a adversarial carlini 7487
./run_extra.sh mnist a relu carlini 7487
./run_extra.sh mnist b standard carlini 7487
./run_extra.sh mnist b adversarial carlini 7487
./run_extra.sh mnist b relu carlini 7487
./run_extra.sh mnist c standard carlini 7487
./run_extra.sh mnist c adversarial carlini 7487
./run_extra.sh mnist c relu carlini 7487
./run_extra.sh mnist a standard carlini 391
./run_extra.sh mnist a adversarial carlini 391
./run_extra.sh mnist a relu carlini 391
./run_extra.sh mnist b standard carlini 391
./run_extra.sh mnist b adversarial carlini 391
./run_extra.sh mnist b relu carlini 391
./run_extra.sh mnist c standard carlini 391
./run_extra.sh mnist c adversarial carlini 391
./run_extra.sh mnist c relu carlini 391
./run_extra.sh mnist a standard carlini 6307
./run_extra.sh mnist a adversarial carlini 6307
./run_extra.sh mnist a relu carlini 6307
./run_extra.sh mnist b standard carlini 6307
./run_extra.sh mnist b adversarial carlini 6307
./run_extra.sh mnist b relu carlini 6307
./run_extra.sh mnist c standard carlini 6307
./run_extra.sh mnist c adversarial carlini 6307
./run_extra.sh mnist c relu carlini 6307
./run_extra.sh mnist a standard carlini 1531
./run_extra.sh mnist a adversarial carlini 1531
./run_extra.sh mnist a relu carlini 1531
./run_extra.sh mnist b standard carlini 1531
./run_extra.sh mnist b adversarial carlini 1531
./run_extra.sh mnist b relu carlini 1531
./run_extra.sh mnist c standard carlini 1531
./run_extra.sh mnist c adversarial carlini 1531
./run_extra.sh mnist c relu carlini 1531
./run_extra.sh mnist a standard carlini 8207
./run_extra.sh mnist a adversarial carlini 8207
./run_extra.sh mnist a relu carlini 8207
./run_extra.sh mnist b standard carlini 8207
./run_extra.sh mnist b adversarial carlini 8207
./run_extra.sh mnist b relu carlini 8207
./run_extra.sh mnist c standard carlini 8207
./run_extra.sh mnist c adversarial carlini 8207
./run_extra.sh mnist c relu carlini 8207
./run_extra.sh mnist a standard carlini 9765
./run_extra.sh mnist a adversarial carlini 9765
./run_extra.sh mnist a relu carlini 9765
./run_extra.sh mnist b standard carlini 9765
./run_extra.sh mnist b adversarial carlini 9765
./run_extra.sh mnist b relu carlini 9765
./run_extra.sh mnist c standard carlini 9765
./run_extra.sh mnist c adversarial carlini 9765
./run_extra.sh mnist c relu carlini 9765
./run_extra.sh mnist a standard carlini 6012
./run_extra.sh mnist a adversarial carlini 6012
./run_extra.sh mnist a relu carlini 6012
./run_extra.sh mnist b standard carlini 6012
./run_extra.sh mnist b adversarial carlini 6012
./run_extra.sh mnist b relu carlini 6012
./run_extra.sh mnist c standard carlini 6012
./run_extra.sh mnist c adversarial carlini 6012
./run_extra.sh mnist c relu carlini 6012
./run_extra.sh mnist a standard carlini 6292
./run_extra.sh mnist a adversarial carlini 6292
./run_extra.sh mnist a relu carlini 6292
./run_extra.sh mnist b standard carlini 6292
./run_extra.sh mnist b adversarial carlini 6292
./run_extra.sh mnist b relu carlini 6292
./run_extra.sh mnist c standard carlini 6292
./run_extra.sh mnist c adversarial carlini 6292
./run_extra.sh mnist c relu carlini 6292
./run_extra.sh mnist a standard carlini 1776
./run_extra.sh mnist a adversarial carlini 1776
./run_extra.sh mnist a relu carlini 1776
./run_extra.sh mnist b standard carlini 1776
./run_extra.sh mnist b adversarial carlini 1776
./run_extra.sh mnist b relu carlini 1776
./run_extra.sh mnist c standard carlini 1776
./run_extra.sh mnist c adversarial carlini 1776
./run_extra.sh mnist c relu carlini 1776
./run_extra.sh mnist a standard carlini 8294
./run_extra.sh mnist a adversarial carlini 8294
./run_extra.sh mnist a relu carlini 8294
./run_extra.sh mnist b standard carlini 8294
./run_extra.sh mnist b adversarial carlini 8294
./run_extra.sh mnist b relu carlini 8294
./run_extra.sh mnist c standard carlini 8294
./run_extra.sh mnist c adversarial carlini 8294
./run_extra.sh mnist c relu carlini 8294
./run_extra.sh mnist a standard carlini 3831
./run_extra.sh mnist a adversarial carlini 3831
./run_extra.sh mnist a relu carlini 3831
./run_extra.sh mnist b standard carlini 3831
./run_extra.sh mnist b adversarial carlini 3831
./run_extra.sh mnist b relu carlini 3831
./run_extra.sh mnist c standard carlini 3831
./run_extra.sh mnist c adversarial carlini 3831
./run_extra.sh mnist c relu carlini 3831
./run_extra.sh mnist a standard carlini 9550
./run_extra.sh mnist a adversarial carlini 9550
./run_extra.sh mnist a relu carlini 9550
./run_extra.sh mnist b standard carlini 9550
./run_extra.sh mnist b adversarial carlini 9550
./run_extra.sh mnist b relu carlini 9550
./run_extra.sh mnist c standard carlini 9550
./run_extra.sh mnist c adversarial carlini 9550
./run_extra.sh mnist c relu carlini 9550
./run_extra.sh mnist a standard carlini 9908
./run_extra.sh mnist a adversarial carlini 9908
./run_extra.sh mnist a relu carlini 9908
./run_extra.sh mnist b standard carlini 9908
./run_extra.sh mnist b adversarial carlini 9908
./run_extra.sh mnist b relu carlini 9908
./run_extra.sh mnist c standard carlini 9908
./run_extra.sh mnist c adversarial carlini 9908
./run_extra.sh mnist c relu carlini 9908
./run_extra.sh mnist a standard carlini 4019
./run_extra.sh mnist a adversarial carlini 4019
./run_extra.sh mnist a relu carlini 4019
./run_extra.sh mnist b standard carlini 4019
./run_extra.sh mnist b adversarial carlini 4019
./run_extra.sh mnist b relu carlini 4019
./run_extra.sh mnist c standard carlini 4019
./run_extra.sh mnist c adversarial carlini 4019
./run_extra.sh mnist c relu carlini 4019
./run_extra.sh mnist a standard carlini 7307
./run_extra.sh mnist a adversarial carlini 7307
./run_extra.sh mnist a relu carlini 7307
./run_extra.sh mnist b standard carlini 7307
./run_extra.sh mnist b adversarial carlini 7307
./run_extra.sh mnist b relu carlini 7307
./run_extra.sh mnist c standard carlini 7307
./run_extra.sh mnist c adversarial carlini 7307
./run_extra.sh mnist c relu carlini 7307
./run_extra.sh mnist a standard carlini 1639
./run_extra.sh mnist a adversarial carlini 1639
./run_extra.sh mnist a relu carlini 1639
./run_extra.sh mnist b standard carlini 1639
./run_extra.sh mnist b adversarial carlini 1639
./run_extra.sh mnist b relu carlini 1639
./run_extra.sh mnist c standard carlini 1639
./run_extra.sh mnist c adversarial carlini 1639
./run_extra.sh mnist c relu carlini 1639
./run_extra.sh mnist a standard carlini 1226
./run_extra.sh mnist a adversarial carlini 1226
./run_extra.sh mnist a relu carlini 1226
./run_extra.sh mnist b standard carlini 1226
./run_extra.sh mnist b adversarial carlini 1226
./run_extra.sh mnist b relu carlini 1226
./run_extra.sh mnist c standard carlini 1226
./run_extra.sh mnist c adversarial carlini 1226
./run_extra.sh mnist c relu carlini 1226
./run_extra.sh mnist a standard carlini 7841
./run_extra.sh mnist a adversarial carlini 7841
./run_extra.sh mnist a relu carlini 7841
./run_extra.sh mnist b standard carlini 7841
./run_extra.sh mnist b adversarial carlini 7841
./run_extra.sh mnist b relu carlini 7841
./run_extra.sh mnist c standard carlini 7841
./run_extra.sh mnist c adversarial carlini 7841
./run_extra.sh mnist c relu carlini 7841
./run_extra.sh mnist a standard carlini 5479
./run_extra.sh mnist a adversarial carlini 5479
./run_extra.sh mnist a relu carlini 5479
./run_extra.sh mnist b standard carlini 5479
./run_extra.sh mnist b adversarial carlini 5479
./run_extra.sh mnist b relu carlini 5479
./run_extra.sh mnist c standard carlini 5479
./run_extra.sh mnist c adversarial carlini 5479
./run_extra.sh mnist c relu carlini 5479
./run_extra.sh mnist a standard carlini 3527
./run_extra.sh mnist a adversarial carlini 3527
./run_extra.sh mnist a relu carlini 3527
./run_extra.sh mnist b standard carlini 3527
./run_extra.sh mnist b adversarial carlini 3527
./run_extra.sh mnist b relu carlini 3527
./run_extra.sh mnist c standard carlini 3527
./run_extra.sh mnist c adversarial carlini 3527
./run_extra.sh mnist c relu carlini 3527
./run_extra.sh mnist a standard carlini 5595
./run_extra.sh mnist a adversarial carlini 5595
./run_extra.sh mnist a relu carlini 5595
./run_extra.sh mnist b standard carlini 5595
./run_extra.sh mnist b adversarial carlini 5595
./run_extra.sh mnist b relu carlini 5595
./run_extra.sh mnist c standard carlini 5595
./run_extra.sh mnist c adversarial carlini 5595
./run_extra.sh mnist c relu carlini 5595
./run_extra.sh mnist a standard carlini 7964
./run_extra.sh mnist a adversarial carlini 7964
./run_extra.sh mnist a relu carlini 7964
./run_extra.sh mnist b standard carlini 7964
./run_extra.sh mnist b adversarial carlini 7964
./run_extra.sh mnist b relu carlini 7964
./run_extra.sh mnist c standard carlini 7964
./run_extra.sh mnist c adversarial carlini 7964
./run_extra.sh mnist c relu carlini 7964
./run_extra.sh mnist a standard carlini 2165
./run_extra.sh mnist a adversarial carlini 2165
./run_extra.sh mnist a relu carlini 2165
./run_extra.sh mnist b standard carlini 2165
./run_extra.sh mnist b adversarial carlini 2165
./run_extra.sh mnist b relu carlini 2165
./run_extra.sh mnist c standard carlini 2165
./run_extra.sh mnist c adversarial carlini 2165
./run_extra.sh mnist c relu carlini 2165
./run_extra.sh mnist a standard carlini 7730
./run_extra.sh mnist a adversarial carlini 7730
./run_extra.sh mnist a relu carlini 7730
./run_extra.sh mnist b standard carlini 7730
./run_extra.sh mnist b adversarial carlini 7730
./run_extra.sh mnist b relu carlini 7730
./run_extra.sh mnist c standard carlini 7730
./run_extra.sh mnist c adversarial carlini 7730
./run_extra.sh mnist c relu carlini 7730
./run_extra.sh mnist a standard carlini 5362
./run_extra.sh mnist a adversarial carlini 5362
./run_extra.sh mnist a relu carlini 5362
./run_extra.sh mnist b standard carlini 5362
./run_extra.sh mnist b adversarial carlini 5362
./run_extra.sh mnist b relu carlini 5362
./run_extra.sh mnist c standard carlini 5362
./run_extra.sh mnist c adversarial carlini 5362
./run_extra.sh mnist c relu carlini 5362
./run_extra.sh mnist a standard carlini 8295
./run_extra.sh mnist a adversarial carlini 8295
./run_extra.sh mnist a relu carlini 8295
./run_extra.sh mnist b standard carlini 8295
./run_extra.sh mnist b adversarial carlini 8295
./run_extra.sh mnist b relu carlini 8295
./run_extra.sh mnist c standard carlini 8295
./run_extra.sh mnist c adversarial carlini 8295
./run_extra.sh mnist c relu carlini 8295
./run_extra.sh mnist a standard carlini 5712
./run_extra.sh mnist a adversarial carlini 5712
./run_extra.sh mnist a relu carlini 5712
./run_extra.sh mnist b standard carlini 5712
./run_extra.sh mnist b adversarial carlini 5712
./run_extra.sh mnist b relu carlini 5712
./run_extra.sh mnist c standard carlini 5712
./run_extra.sh mnist c adversarial carlini 5712
./run_extra.sh mnist c relu carlini 5712
./run_extra.sh mnist a standard carlini 8921
./run_extra.sh mnist a adversarial carlini 8921
./run_extra.sh mnist a relu carlini 8921
./run_extra.sh mnist b standard carlini 8921
./run_extra.sh mnist b adversarial carlini 8921
./run_extra.sh mnist b relu carlini 8921
./run_extra.sh mnist c standard carlini 8921
./run_extra.sh mnist c adversarial carlini 8921
./run_extra.sh mnist c relu carlini 8921
./run_extra.sh mnist a standard carlini 4992
./run_extra.sh mnist a adversarial carlini 4992
./run_extra.sh mnist a relu carlini 4992
./run_extra.sh mnist b standard carlini 4992
./run_extra.sh mnist b adversarial carlini 4992
./run_extra.sh mnist b relu carlini 4992
./run_extra.sh mnist c standard carlini 4992
./run_extra.sh mnist c adversarial carlini 4992
./run_extra.sh mnist c relu carlini 4992
./run_extra.sh mnist a standard carlini 9190
./run_extra.sh mnist a adversarial carlini 9190
./run_extra.sh mnist a relu carlini 9190
./run_extra.sh mnist b standard carlini 9190
./run_extra.sh mnist b adversarial carlini 9190
./run_extra.sh mnist b relu carlini 9190
./run_extra.sh mnist c standard carlini 9190
./run_extra.sh mnist c adversarial carlini 9190
./run_extra.sh mnist c relu carlini 9190
./run_extra.sh mnist a standard carlini 1194
./run_extra.sh mnist a adversarial carlini 1194
./run_extra.sh mnist a relu carlini 1194
./run_extra.sh mnist b standard carlini 1194
./run_extra.sh mnist b adversarial carlini 1194
./run_extra.sh mnist b relu carlini 1194
./run_extra.sh mnist c standard carlini 1194
./run_extra.sh mnist c adversarial carlini 1194
./run_extra.sh mnist c relu carlini 1194
./run_extra.sh mnist a standard carlini 6330
./run_extra.sh mnist a adversarial carlini 6330
./run_extra.sh mnist a relu carlini 6330
./run_extra.sh mnist b standard carlini 6330
./run_extra.sh mnist b adversarial carlini 6330
./run_extra.sh mnist b relu carlini 6330
./run_extra.sh mnist c standard carlini 6330
./run_extra.sh mnist c adversarial carlini 6330
./run_extra.sh mnist c relu carlini 6330
./run_extra.sh mnist a standard carlini 5281
./run_extra.sh mnist a adversarial carlini 5281
./run_extra.sh mnist a relu carlini 5281
./run_extra.sh mnist b standard carlini 5281
./run_extra.sh mnist b adversarial carlini 5281
./run_extra.sh mnist b relu carlini 5281
./run_extra.sh mnist c standard carlini 5281
./run_extra.sh mnist c adversarial carlini 5281
./run_extra.sh mnist c relu carlini 5281
./run_extra.sh mnist a standard carlini 4021
./run_extra.sh mnist a adversarial carlini 4021
./run_extra.sh mnist a relu carlini 4021
./run_extra.sh mnist b standard carlini 4021
./run_extra.sh mnist b adversarial carlini 4021
./run_extra.sh mnist b relu carlini 4021
./run_extra.sh mnist c standard carlini 4021
./run_extra.sh mnist c adversarial carlini 4021
./run_extra.sh mnist c relu carlini 4021
./run_extra.sh mnist a standard carlini 6503
./run_extra.sh mnist a adversarial carlini 6503
./run_extra.sh mnist a relu carlini 6503
./run_extra.sh mnist b standard carlini 6503
./run_extra.sh mnist b adversarial carlini 6503
./run_extra.sh mnist b relu carlini 6503
./run_extra.sh mnist c standard carlini 6503
./run_extra.sh mnist c adversarial carlini 6503
./run_extra.sh mnist c relu carlini 6503
./run_extra.sh mnist a standard carlini 7953
./run_extra.sh mnist a adversarial carlini 7953
./run_extra.sh mnist a relu carlini 7953
./run_extra.sh mnist b standard carlini 7953
./run_extra.sh mnist b adversarial carlini 7953
./run_extra.sh mnist b relu carlini 7953
./run_extra.sh mnist c standard carlini 7953
./run_extra.sh mnist c adversarial carlini 7953
./run_extra.sh mnist c relu carlini 7953
./run_extra.sh mnist a standard carlini 9149
./run_extra.sh mnist a adversarial carlini 9149
./run_extra.sh mnist a relu carlini 9149
./run_extra.sh mnist b standard carlini 9149
./run_extra.sh mnist b adversarial carlini 9149
./run_extra.sh mnist b relu carlini 9149
./run_extra.sh mnist c standard carlini 9149
./run_extra.sh mnist c adversarial carlini 9149
./run_extra.sh mnist c relu carlini 9149
./run_extra.sh mnist a standard carlini 275
./run_extra.sh mnist a adversarial carlini 275
./run_extra.sh mnist a relu carlini 275
./run_extra.sh mnist b standard carlini 275
./run_extra.sh mnist b adversarial carlini 275
./run_extra.sh mnist b relu carlini 275
./run_extra.sh mnist c standard carlini 275
./run_extra.sh mnist c adversarial carlini 275
./run_extra.sh mnist c relu carlini 275
./run_extra.sh mnist a standard carlini 5660
./run_extra.sh mnist a adversarial carlini 5660
./run_extra.sh mnist a relu carlini 5660
./run_extra.sh mnist b standard carlini 5660
./run_extra.sh mnist b adversarial carlini 5660
./run_extra.sh mnist b relu carlini 5660
./run_extra.sh mnist c standard carlini 5660
./run_extra.sh mnist c adversarial carlini 5660
./run_extra.sh mnist c relu carlini 5660
./run_extra.sh mnist a standard carlini 5843
./run_extra.sh mnist a adversarial carlini 5843
./run_extra.sh mnist a relu carlini 5843
./run_extra.sh mnist b standard carlini 5843
./run_extra.sh mnist b adversarial carlini 5843
./run_extra.sh mnist b relu carlini 5843
./run_extra.sh mnist c standard carlini 5843
./run_extra.sh mnist c adversarial carlini 5843
./run_extra.sh mnist c relu carlini 5843
./run_extra.sh mnist a standard carlini 9309
./run_extra.sh mnist a adversarial carlini 9309
./run_extra.sh mnist a relu carlini 9309
./run_extra.sh mnist b standard carlini 9309
./run_extra.sh mnist b adversarial carlini 9309
./run_extra.sh mnist b relu carlini 9309
./run_extra.sh mnist c standard carlini 9309
./run_extra.sh mnist c adversarial carlini 9309
./run_extra.sh mnist c relu carlini 9309
./run_extra.sh mnist a standard carlini 2015
./run_extra.sh mnist a adversarial carlini 2015
./run_extra.sh mnist a relu carlini 2015
./run_extra.sh mnist b standard carlini 2015
./run_extra.sh mnist b adversarial carlini 2015
./run_extra.sh mnist b relu carlini 2015
./run_extra.sh mnist c standard carlini 2015
./run_extra.sh mnist c adversarial carlini 2015
./run_extra.sh mnist c relu carlini 2015
./run_extra.sh mnist a standard carlini 5818
./run_extra.sh mnist a adversarial carlini 5818
./run_extra.sh mnist a relu carlini 5818
./run_extra.sh mnist b standard carlini 5818
./run_extra.sh mnist b adversarial carlini 5818
./run_extra.sh mnist b relu carlini 5818
./run_extra.sh mnist c standard carlini 5818
./run_extra.sh mnist c adversarial carlini 5818
./run_extra.sh mnist c relu carlini 5818
./run_extra.sh mnist a standard carlini 5779
./run_extra.sh mnist a adversarial carlini 5779
./run_extra.sh mnist a relu carlini 5779
./run_extra.sh mnist b standard carlini 5779
./run_extra.sh mnist b adversarial carlini 5779
./run_extra.sh mnist b relu carlini 5779
./run_extra.sh mnist c standard carlini 5779
./run_extra.sh mnist c adversarial carlini 5779
./run_extra.sh mnist c relu carlini 5779
./run_extra.sh mnist a standard carlini 8378
./run_extra.sh mnist a adversarial carlini 8378
./run_extra.sh mnist a relu carlini 8378
./run_extra.sh mnist b standard carlini 8378
./run_extra.sh mnist b adversarial carlini 8378
./run_extra.sh mnist b relu carlini 8378
./run_extra.sh mnist c standard carlini 8378
./run_extra.sh mnist c adversarial carlini 8378
./run_extra.sh mnist c relu carlini 8378
./run_extra.sh mnist a standard carlini 2815
./run_extra.sh mnist a adversarial carlini 2815
./run_extra.sh mnist a relu carlini 2815
./run_extra.sh mnist b standard carlini 2815
./run_extra.sh mnist b adversarial carlini 2815
./run_extra.sh mnist b relu carlini 2815
./run_extra.sh mnist c standard carlini 2815
./run_extra.sh mnist c adversarial carlini 2815
./run_extra.sh mnist c relu carlini 2815
./run_extra.sh mnist a standard carlini 5856
./run_extra.sh mnist a adversarial carlini 5856
./run_extra.sh mnist a relu carlini 5856
./run_extra.sh mnist b standard carlini 5856
./run_extra.sh mnist b adversarial carlini 5856
./run_extra.sh mnist b relu carlini 5856
./run_extra.sh mnist c standard carlini 5856
./run_extra.sh mnist c adversarial carlini 5856
./run_extra.sh mnist c relu carlini 5856
./run_extra.sh mnist a standard carlini 6896
./run_extra.sh mnist a adversarial carlini 6896
./run_extra.sh mnist a relu carlini 6896
./run_extra.sh mnist b standard carlini 6896
./run_extra.sh mnist b adversarial carlini 6896
./run_extra.sh mnist b relu carlini 6896
./run_extra.sh mnist c standard carlini 6896
./run_extra.sh mnist c adversarial carlini 6896
./run_extra.sh mnist c relu carlini 6896
./run_extra.sh mnist a standard carlini 7346
./run_extra.sh mnist a adversarial carlini 7346
./run_extra.sh mnist a relu carlini 7346
./run_extra.sh mnist b standard carlini 7346
./run_extra.sh mnist b adversarial carlini 7346
./run_extra.sh mnist b relu carlini 7346
./run_extra.sh mnist c standard carlini 7346
./run_extra.sh mnist c adversarial carlini 7346
./run_extra.sh mnist c relu carlini 7346
./run_extra.sh mnist a standard carlini 4649
./run_extra.sh mnist a adversarial carlini 4649
./run_extra.sh mnist a relu carlini 4649
./run_extra.sh mnist b standard carlini 4649
./run_extra.sh mnist b adversarial carlini 4649
./run_extra.sh mnist b relu carlini 4649
./run_extra.sh mnist c standard carlini 4649
./run_extra.sh mnist c adversarial carlini 4649
./run_extra.sh mnist c relu carlini 4649
./run_extra.sh mnist a standard carlini 7673
./run_extra.sh mnist a adversarial carlini 7673
./run_extra.sh mnist a relu carlini 7673
./run_extra.sh mnist b standard carlini 7673
./run_extra.sh mnist b adversarial carlini 7673
./run_extra.sh mnist b relu carlini 7673
./run_extra.sh mnist c standard carlini 7673
./run_extra.sh mnist c adversarial carlini 7673
./run_extra.sh mnist c relu carlini 7673
./run_extra.sh mnist a standard carlini 2597
./run_extra.sh mnist a adversarial carlini 2597
./run_extra.sh mnist a relu carlini 2597
./run_extra.sh mnist b standard carlini 2597
./run_extra.sh mnist b adversarial carlini 2597
./run_extra.sh mnist b relu carlini 2597
./run_extra.sh mnist c standard carlini 2597
./run_extra.sh mnist c adversarial carlini 2597
./run_extra.sh mnist c relu carlini 2597
./run_extra.sh mnist a standard carlini 2159
./run_extra.sh mnist a adversarial carlini 2159
./run_extra.sh mnist a relu carlini 2159
./run_extra.sh mnist b standard carlini 2159
./run_extra.sh mnist b adversarial carlini 2159
./run_extra.sh mnist b relu carlini 2159
./run_extra.sh mnist c standard carlini 2159
./run_extra.sh mnist c adversarial carlini 2159
./run_extra.sh mnist c relu carlini 2159
./run_extra.sh mnist a standard carlini 4447
./run_extra.sh mnist a adversarial carlini 4447
./run_extra.sh mnist a relu carlini 4447
./run_extra.sh mnist b standard carlini 4447
./run_extra.sh mnist b adversarial carlini 4447
./run_extra.sh mnist b relu carlini 4447
./run_extra.sh mnist c standard carlini 4447
./run_extra.sh mnist c adversarial carlini 4447
./run_extra.sh mnist c relu carlini 4447
./run_extra.sh mnist a standard carlini 9084
./run_extra.sh mnist a adversarial carlini 9084
./run_extra.sh mnist a relu carlini 9084
./run_extra.sh mnist b standard carlini 9084
./run_extra.sh mnist b adversarial carlini 9084
./run_extra.sh mnist b relu carlini 9084
./run_extra.sh mnist c standard carlini 9084
./run_extra.sh mnist c adversarial carlini 9084
./run_extra.sh mnist c relu carlini 9084
./run_extra.sh mnist a standard carlini 4761
./run_extra.sh mnist a adversarial carlini 4761
./run_extra.sh mnist a relu carlini 4761
./run_extra.sh mnist b standard carlini 4761
./run_extra.sh mnist b adversarial carlini 4761
./run_extra.sh mnist b relu carlini 4761
./run_extra.sh mnist c standard carlini 4761
./run_extra.sh mnist c adversarial carlini 4761
./run_extra.sh mnist c relu carlini 4761
./run_extra.sh mnist a standard carlini 4344
./run_extra.sh mnist a adversarial carlini 4344
./run_extra.sh mnist a relu carlini 4344
./run_extra.sh mnist b standard carlini 4344
./run_extra.sh mnist b adversarial carlini 4344
./run_extra.sh mnist b relu carlini 4344
./run_extra.sh mnist c standard carlini 4344
./run_extra.sh mnist c adversarial carlini 4344
./run_extra.sh mnist c relu carlini 4344
./run_extra.sh mnist a standard carlini 8515
./run_extra.sh mnist a adversarial carlini 8515
./run_extra.sh mnist a relu carlini 8515
./run_extra.sh mnist b standard carlini 8515
./run_extra.sh mnist b adversarial carlini 8515
./run_extra.sh mnist b relu carlini 8515
./run_extra.sh mnist c standard carlini 8515
./run_extra.sh mnist c adversarial carlini 8515
./run_extra.sh mnist c relu carlini 8515
./run_extra.sh mnist a standard carlini 9725
./run_extra.sh mnist a adversarial carlini 9725
./run_extra.sh mnist a relu carlini 9725
./run_extra.sh mnist b standard carlini 9725
./run_extra.sh mnist b adversarial carlini 9725
./run_extra.sh mnist b relu carlini 9725
./run_extra.sh mnist c standard carlini 9725
./run_extra.sh mnist c adversarial carlini 9725
./run_extra.sh mnist c relu carlini 9725
./run_extra.sh mnist a standard carlini 4543
./run_extra.sh mnist a adversarial carlini 4543
./run_extra.sh mnist a relu carlini 4543
./run_extra.sh mnist b standard carlini 4543
./run_extra.sh mnist b adversarial carlini 4543
./run_extra.sh mnist b relu carlini 4543
./run_extra.sh mnist c standard carlini 4543
./run_extra.sh mnist c adversarial carlini 4543
./run_extra.sh mnist c relu carlini 4543
./run_extra.sh mnist a standard carlini 5767
./run_extra.sh mnist a adversarial carlini 5767
./run_extra.sh mnist a relu carlini 5767
./run_extra.sh mnist b standard carlini 5767
./run_extra.sh mnist b adversarial carlini 5767
./run_extra.sh mnist b relu carlini 5767
./run_extra.sh mnist c standard carlini 5767
./run_extra.sh mnist c adversarial carlini 5767
./run_extra.sh mnist c relu carlini 5767
./run_extra.sh mnist a standard carlini 9321
./run_extra.sh mnist a adversarial carlini 9321
./run_extra.sh mnist a relu carlini 9321
./run_extra.sh mnist b standard carlini 9321
./run_extra.sh mnist b adversarial carlini 9321
./run_extra.sh mnist b relu carlini 9321
./run_extra.sh mnist c standard carlini 9321
./run_extra.sh mnist c adversarial carlini 9321
./run_extra.sh mnist c relu carlini 9321
./run_extra.sh mnist a standard carlini 3414
./run_extra.sh mnist a adversarial carlini 3414
./run_extra.sh mnist a relu carlini 3414
./run_extra.sh mnist b standard carlini 3414
./run_extra.sh mnist b adversarial carlini 3414
./run_extra.sh mnist b relu carlini 3414
./run_extra.sh mnist c standard carlini 3414
./run_extra.sh mnist c adversarial carlini 3414
./run_extra.sh mnist c relu carlini 3414
./run_extra.sh mnist a standard carlini 1585
./run_extra.sh mnist a adversarial carlini 1585
./run_extra.sh mnist a relu carlini 1585
./run_extra.sh mnist b standard carlini 1585
./run_extra.sh mnist b adversarial carlini 1585
./run_extra.sh mnist b relu carlini 1585
./run_extra.sh mnist c standard carlini 1585
./run_extra.sh mnist c adversarial carlini 1585
./run_extra.sh mnist c relu carlini 1585
./run_extra.sh mnist a standard carlini 1665
./run_extra.sh mnist a adversarial carlini 1665
./run_extra.sh mnist a relu carlini 1665
./run_extra.sh mnist b standard carlini 1665
./run_extra.sh mnist b adversarial carlini 1665
./run_extra.sh mnist b relu carlini 1665
./run_extra.sh mnist c standard carlini 1665
./run_extra.sh mnist c adversarial carlini 1665
./run_extra.sh mnist c relu carlini 1665
./run_extra.sh mnist a standard carlini 7169
./run_extra.sh mnist a adversarial carlini 7169
./run_extra.sh mnist a relu carlini 7169
./run_extra.sh mnist b standard carlini 7169
./run_extra.sh mnist b adversarial carlini 7169
./run_extra.sh mnist b relu carlini 7169
./run_extra.sh mnist c standard carlini 7169
./run_extra.sh mnist c adversarial carlini 7169
./run_extra.sh mnist c relu carlini 7169
./run_extra.sh mnist a standard carlini 5978
./run_extra.sh mnist a adversarial carlini 5978
./run_extra.sh mnist a relu carlini 5978
./run_extra.sh mnist b standard carlini 5978
./run_extra.sh mnist b adversarial carlini 5978
./run_extra.sh mnist b relu carlini 5978
./run_extra.sh mnist c standard carlini 5978
./run_extra.sh mnist c adversarial carlini 5978
./run_extra.sh mnist c relu carlini 5978
./run_extra.sh mnist a standard carlini 7295
./run_extra.sh mnist a adversarial carlini 7295
./run_extra.sh mnist a relu carlini 7295
./run_extra.sh mnist b standard carlini 7295
./run_extra.sh mnist b adversarial carlini 7295
./run_extra.sh mnist b relu carlini 7295
./run_extra.sh mnist c standard carlini 7295
./run_extra.sh mnist c adversarial carlini 7295
./run_extra.sh mnist c relu carlini 7295
./run_extra.sh mnist a standard carlini 1126
./run_extra.sh mnist a adversarial carlini 1126
./run_extra.sh mnist a relu carlini 1126
./run_extra.sh mnist b standard carlini 1126
./run_extra.sh mnist b adversarial carlini 1126
./run_extra.sh mnist b relu carlini 1126
./run_extra.sh mnist c standard carlini 1126
./run_extra.sh mnist c adversarial carlini 1126
./run_extra.sh mnist c relu carlini 1126
./run_extra.sh mnist a standard carlini 7089
./run_extra.sh mnist a adversarial carlini 7089
./run_extra.sh mnist a relu carlini 7089
./run_extra.sh mnist b standard carlini 7089
./run_extra.sh mnist b adversarial carlini 7089
./run_extra.sh mnist b relu carlini 7089
./run_extra.sh mnist c standard carlini 7089
./run_extra.sh mnist c adversarial carlini 7089
./run_extra.sh mnist c relu carlini 7089
./run_extra.sh mnist a standard carlini 8551
./run_extra.sh mnist a adversarial carlini 8551
./run_extra.sh mnist a relu carlini 8551
./run_extra.sh mnist b standard carlini 8551
./run_extra.sh mnist b adversarial carlini 8551
./run_extra.sh mnist b relu carlini 8551
./run_extra.sh mnist c standard carlini 8551
./run_extra.sh mnist c adversarial carlini 8551
./run_extra.sh mnist c relu carlini 8551
./run_extra.sh mnist a standard carlini 3542
./run_extra.sh mnist a adversarial carlini 3542
./run_extra.sh mnist a relu carlini 3542
./run_extra.sh mnist b standard carlini 3542
./run_extra.sh mnist b adversarial carlini 3542
./run_extra.sh mnist b relu carlini 3542
./run_extra.sh mnist c standard carlini 3542
./run_extra.sh mnist c adversarial carlini 3542
./run_extra.sh mnist c relu carlini 3542
./run_extra.sh mnist a standard carlini 4838
./run_extra.sh mnist a adversarial carlini 4838
./run_extra.sh mnist a relu carlini 4838
./run_extra.sh mnist b standard carlini 4838
./run_extra.sh mnist b adversarial carlini 4838
./run_extra.sh mnist b relu carlini 4838
./run_extra.sh mnist c standard carlini 4838
./run_extra.sh mnist c adversarial carlini 4838
./run_extra.sh mnist c relu carlini 4838
./run_extra.sh mnist a standard carlini 1789
./run_extra.sh mnist a adversarial carlini 1789
./run_extra.sh mnist a relu carlini 1789
./run_extra.sh mnist b standard carlini 1789
./run_extra.sh mnist b adversarial carlini 1789
./run_extra.sh mnist b relu carlini 1789
./run_extra.sh mnist c standard carlini 1789
./run_extra.sh mnist c adversarial carlini 1789
./run_extra.sh mnist c relu carlini 1789
./run_extra.sh mnist a standard carlini 6164
./run_extra.sh mnist a adversarial carlini 6164
./run_extra.sh mnist a relu carlini 6164
./run_extra.sh mnist b standard carlini 6164
./run_extra.sh mnist b adversarial carlini 6164
./run_extra.sh mnist b relu carlini 6164
./run_extra.sh mnist c standard carlini 6164
./run_extra.sh mnist c adversarial carlini 6164
./run_extra.sh mnist c relu carlini 6164
./run_extra.sh mnist a standard carlini 1847
./run_extra.sh mnist a adversarial carlini 1847
./run_extra.sh mnist a relu carlini 1847
./run_extra.sh mnist b standard carlini 1847
./run_extra.sh mnist b adversarial carlini 1847
./run_extra.sh mnist b relu carlini 1847
./run_extra.sh mnist c standard carlini 1847
./run_extra.sh mnist c adversarial carlini 1847
./run_extra.sh mnist c relu carlini 1847
./run_extra.sh mnist a standard carlini 7825
./run_extra.sh mnist a adversarial carlini 7825
./run_extra.sh mnist a relu carlini 7825
./run_extra.sh mnist b standard carlini 7825
./run_extra.sh mnist b adversarial carlini 7825
./run_extra.sh mnist b relu carlini 7825
./run_extra.sh mnist c standard carlini 7825
./run_extra.sh mnist c adversarial carlini 7825
./run_extra.sh mnist c relu carlini 7825
./run_extra.sh mnist a standard carlini 9383
./run_extra.sh mnist a adversarial carlini 9383
./run_extra.sh mnist a relu carlini 9383
./run_extra.sh mnist b standard carlini 9383
./run_extra.sh mnist b adversarial carlini 9383
./run_extra.sh mnist b relu carlini 9383
./run_extra.sh mnist c standard carlini 9383
./run_extra.sh mnist c adversarial carlini 9383
./run_extra.sh mnist c relu carlini 9383
./run_extra.sh mnist a standard carlini 3750
./run_extra.sh mnist a adversarial carlini 3750
./run_extra.sh mnist a relu carlini 3750
./run_extra.sh mnist b standard carlini 3750
./run_extra.sh mnist b adversarial carlini 3750
./run_extra.sh mnist b relu carlini 3750
./run_extra.sh mnist c standard carlini 3750
./run_extra.sh mnist c adversarial carlini 3750
./run_extra.sh mnist c relu carlini 3750
./run_extra.sh mnist a standard carlini 4442
./run_extra.sh mnist a adversarial carlini 4442
./run_extra.sh mnist a relu carlini 4442
./run_extra.sh mnist b standard carlini 4442
./run_extra.sh mnist b adversarial carlini 4442
./run_extra.sh mnist b relu carlini 4442
./run_extra.sh mnist c standard carlini 4442
./run_extra.sh mnist c adversarial carlini 4442
./run_extra.sh mnist c relu carlini 4442
./run_extra.sh mnist a standard carlini 663
./run_extra.sh mnist a adversarial carlini 663
./run_extra.sh mnist a relu carlini 663
./run_extra.sh mnist b standard carlini 663
./run_extra.sh mnist b adversarial carlini 663
./run_extra.sh mnist b relu carlini 663
./run_extra.sh mnist c standard carlini 663
./run_extra.sh mnist c adversarial carlini 663
./run_extra.sh mnist c relu carlini 663
./run_extra.sh mnist a standard carlini 6616
./run_extra.sh mnist a adversarial carlini 6616
./run_extra.sh mnist a relu carlini 6616
./run_extra.sh mnist b standard carlini 6616
./run_extra.sh mnist b adversarial carlini 6616
./run_extra.sh mnist b relu carlini 6616
./run_extra.sh mnist c standard carlini 6616
./run_extra.sh mnist c adversarial carlini 6616
./run_extra.sh mnist c relu carlini 6616
./run_extra.sh mnist a standard carlini 3654
./run_extra.sh mnist a adversarial carlini 3654
./run_extra.sh mnist a relu carlini 3654
./run_extra.sh mnist b standard carlini 3654
./run_extra.sh mnist b adversarial carlini 3654
./run_extra.sh mnist b relu carlini 3654
./run_extra.sh mnist c standard carlini 3654
./run_extra.sh mnist c adversarial carlini 3654
./run_extra.sh mnist c relu carlini 3654
./run_extra.sh mnist a standard carlini 3046
./run_extra.sh mnist a adversarial carlini 3046
./run_extra.sh mnist a relu carlini 3046
./run_extra.sh mnist b standard carlini 3046
./run_extra.sh mnist b adversarial carlini 3046
./run_extra.sh mnist b relu carlini 3046
./run_extra.sh mnist c standard carlini 3046
./run_extra.sh mnist c adversarial carlini 3046
./run_extra.sh mnist c relu carlini 3046
./run_extra.sh mnist a standard carlini 8148
./run_extra.sh mnist a adversarial carlini 8148
./run_extra.sh mnist a relu carlini 8148
./run_extra.sh mnist b standard carlini 8148
./run_extra.sh mnist b adversarial carlini 8148
./run_extra.sh mnist b relu carlini 8148
./run_extra.sh mnist c standard carlini 8148
./run_extra.sh mnist c adversarial carlini 8148
./run_extra.sh mnist c relu carlini 8148
./run_extra.sh mnist a standard carlini 7277
./run_extra.sh mnist a adversarial carlini 7277
./run_extra.sh mnist a relu carlini 7277
./run_extra.sh mnist b standard carlini 7277
./run_extra.sh mnist b adversarial carlini 7277
./run_extra.sh mnist b relu carlini 7277
./run_extra.sh mnist c standard carlini 7277
./run_extra.sh mnist c adversarial carlini 7277
./run_extra.sh mnist c relu carlini 7277
./run_extra.sh mnist a standard carlini 1055
./run_extra.sh mnist a adversarial carlini 1055
./run_extra.sh mnist a relu carlini 1055
./run_extra.sh mnist b standard carlini 1055
./run_extra.sh mnist b adversarial carlini 1055
./run_extra.sh mnist b relu carlini 1055
./run_extra.sh mnist c standard carlini 1055
./run_extra.sh mnist c adversarial carlini 1055
./run_extra.sh mnist c relu carlini 1055
./run_extra.sh mnist a standard carlini 856
./run_extra.sh mnist a adversarial carlini 856
./run_extra.sh mnist a relu carlini 856
./run_extra.sh mnist b standard carlini 856
./run_extra.sh mnist b adversarial carlini 856
./run_extra.sh mnist b relu carlini 856
./run_extra.sh mnist c standard carlini 856
./run_extra.sh mnist c adversarial carlini 856
./run_extra.sh mnist c relu carlini 856
./run_extra.sh mnist a standard carlini 6306
./run_extra.sh mnist a adversarial carlini 6306
./run_extra.sh mnist a relu carlini 6306
./run_extra.sh mnist b standard carlini 6306
./run_extra.sh mnist b adversarial carlini 6306
./run_extra.sh mnist b relu carlini 6306
./run_extra.sh mnist c standard carlini 6306
./run_extra.sh mnist c adversarial carlini 6306
./run_extra.sh mnist c relu carlini 6306
./run_extra.sh mnist a standard carlini 1001
./run_extra.sh mnist a adversarial carlini 1001
./run_extra.sh mnist a relu carlini 1001
./run_extra.sh mnist b standard carlini 1001
./run_extra.sh mnist b adversarial carlini 1001
./run_extra.sh mnist b relu carlini 1001
./run_extra.sh mnist c standard carlini 1001
./run_extra.sh mnist c adversarial carlini 1001
./run_extra.sh mnist c relu carlini 1001
./run_extra.sh mnist a standard carlini 7293
./run_extra.sh mnist a adversarial carlini 7293
./run_extra.sh mnist a relu carlini 7293
./run_extra.sh mnist b standard carlini 7293
./run_extra.sh mnist b adversarial carlini 7293
./run_extra.sh mnist b relu carlini 7293
./run_extra.sh mnist c standard carlini 7293
./run_extra.sh mnist c adversarial carlini 7293
./run_extra.sh mnist c relu carlini 7293
./run_extra.sh mnist a standard carlini 3627
./run_extra.sh mnist a adversarial carlini 3627
./run_extra.sh mnist a relu carlini 3627
./run_extra.sh mnist b standard carlini 3627
./run_extra.sh mnist b adversarial carlini 3627
./run_extra.sh mnist b relu carlini 3627
./run_extra.sh mnist c standard carlini 3627
./run_extra.sh mnist c adversarial carlini 3627
./run_extra.sh mnist c relu carlini 3627
./run_extra.sh mnist a standard carlini 8815
./run_extra.sh mnist a adversarial carlini 8815
./run_extra.sh mnist a relu carlini 8815
./run_extra.sh mnist b standard carlini 8815
./run_extra.sh mnist b adversarial carlini 8815
./run_extra.sh mnist b relu carlini 8815
./run_extra.sh mnist c standard carlini 8815
./run_extra.sh mnist c adversarial carlini 8815
./run_extra.sh mnist c relu carlini 8815
./run_extra.sh mnist a standard carlini 8878
./run_extra.sh mnist a adversarial carlini 8878
./run_extra.sh mnist a relu carlini 8878
./run_extra.sh mnist b standard carlini 8878
./run_extra.sh mnist b adversarial carlini 8878
./run_extra.sh mnist b relu carlini 8878
./run_extra.sh mnist c standard carlini 8878
./run_extra.sh mnist c adversarial carlini 8878
./run_extra.sh mnist c relu carlini 8878
./run_extra.sh mnist a standard carlini 5352
./run_extra.sh mnist a adversarial carlini 5352
./run_extra.sh mnist a relu carlini 5352
./run_extra.sh mnist b standard carlini 5352
./run_extra.sh mnist b adversarial carlini 5352
./run_extra.sh mnist b relu carlini 5352
./run_extra.sh mnist c standard carlini 5352
./run_extra.sh mnist c adversarial carlini 5352
./run_extra.sh mnist c relu carlini 5352
./run_extra.sh mnist a standard carlini 8909
./run_extra.sh mnist a adversarial carlini 8909
./run_extra.sh mnist a relu carlini 8909
./run_extra.sh mnist b standard carlini 8909
./run_extra.sh mnist b adversarial carlini 8909
./run_extra.sh mnist b relu carlini 8909
./run_extra.sh mnist c standard carlini 8909
./run_extra.sh mnist c adversarial carlini 8909
./run_extra.sh mnist c relu carlini 8909
./run_extra.sh mnist a standard carlini 6223
./run_extra.sh mnist a adversarial carlini 6223
./run_extra.sh mnist a relu carlini 6223
./run_extra.sh mnist b standard carlini 6223
./run_extra.sh mnist b adversarial carlini 6223
./run_extra.sh mnist b relu carlini 6223
./run_extra.sh mnist c standard carlini 6223
./run_extra.sh mnist c adversarial carlini 6223
./run_extra.sh mnist c relu carlini 6223
./run_extra.sh mnist a standard carlini 8410
./run_extra.sh mnist a adversarial carlini 8410
./run_extra.sh mnist a relu carlini 8410
./run_extra.sh mnist b standard carlini 8410
./run_extra.sh mnist b adversarial carlini 8410
./run_extra.sh mnist b relu carlini 8410
./run_extra.sh mnist c standard carlini 8410
./run_extra.sh mnist c adversarial carlini 8410
./run_extra.sh mnist c relu carlini 8410
./run_extra.sh mnist a standard carlini 2335
./run_extra.sh mnist a adversarial carlini 2335
./run_extra.sh mnist a relu carlini 2335
./run_extra.sh mnist b standard carlini 2335
./run_extra.sh mnist b adversarial carlini 2335
./run_extra.sh mnist b relu carlini 2335
./run_extra.sh mnist c standard carlini 2335
./run_extra.sh mnist c adversarial carlini 2335
./run_extra.sh mnist c relu carlini 2335
./run_extra.sh mnist a standard carlini 9082
./run_extra.sh mnist a adversarial carlini 9082
./run_extra.sh mnist a relu carlini 9082
./run_extra.sh mnist b standard carlini 9082
./run_extra.sh mnist b adversarial carlini 9082
./run_extra.sh mnist b relu carlini 9082
./run_extra.sh mnist c standard carlini 9082
./run_extra.sh mnist c adversarial carlini 9082
./run_extra.sh mnist c relu carlini 9082
./run_extra.sh mnist a standard carlini 6631
./run_extra.sh mnist a adversarial carlini 6631
./run_extra.sh mnist a relu carlini 6631
./run_extra.sh mnist b standard carlini 6631
./run_extra.sh mnist b adversarial carlini 6631
./run_extra.sh mnist b relu carlini 6631
./run_extra.sh mnist c standard carlini 6631
./run_extra.sh mnist c adversarial carlini 6631
./run_extra.sh mnist c relu carlini 6631
./run_extra.sh mnist a standard carlini 5191
./run_extra.sh mnist a adversarial carlini 5191
./run_extra.sh mnist a relu carlini 5191
./run_extra.sh mnist b standard carlini 5191
./run_extra.sh mnist b adversarial carlini 5191
./run_extra.sh mnist b relu carlini 5191
./run_extra.sh mnist c standard carlini 5191
./run_extra.sh mnist c adversarial carlini 5191
./run_extra.sh mnist c relu carlini 5191
./run_extra.sh mnist a standard carlini 4169
./run_extra.sh mnist a adversarial carlini 4169
./run_extra.sh mnist a relu carlini 4169
./run_extra.sh mnist b standard carlini 4169
./run_extra.sh mnist b adversarial carlini 4169
./run_extra.sh mnist b relu carlini 4169
./run_extra.sh mnist c standard carlini 4169
./run_extra.sh mnist c adversarial carlini 4169
./run_extra.sh mnist c relu carlini 4169
./run_extra.sh mnist a standard carlini 3270
./run_extra.sh mnist a adversarial carlini 3270
./run_extra.sh mnist a relu carlini 3270
./run_extra.sh mnist b standard carlini 3270
./run_extra.sh mnist b adversarial carlini 3270
./run_extra.sh mnist b relu carlini 3270
./run_extra.sh mnist c standard carlini 3270
./run_extra.sh mnist c adversarial carlini 3270
./run_extra.sh mnist c relu carlini 3270
./run_extra.sh mnist a standard carlini 8224
./run_extra.sh mnist a adversarial carlini 8224
./run_extra.sh mnist a relu carlini 8224
./run_extra.sh mnist b standard carlini 8224
./run_extra.sh mnist b adversarial carlini 8224
./run_extra.sh mnist b relu carlini 8224
./run_extra.sh mnist c standard carlini 8224
./run_extra.sh mnist c adversarial carlini 8224
./run_extra.sh mnist c relu carlini 8224
./run_extra.sh mnist a standard carlini 1021
./run_extra.sh mnist a adversarial carlini 1021
./run_extra.sh mnist a relu carlini 1021
./run_extra.sh mnist b standard carlini 1021
./run_extra.sh mnist b adversarial carlini 1021
./run_extra.sh mnist b relu carlini 1021
./run_extra.sh mnist c standard carlini 1021
./run_extra.sh mnist c adversarial carlini 1021
./run_extra.sh mnist c relu carlini 1021
./run_extra.sh mnist a standard carlini 1941
./run_extra.sh mnist a adversarial carlini 1941
./run_extra.sh mnist a relu carlini 1941
./run_extra.sh mnist b standard carlini 1941
./run_extra.sh mnist b adversarial carlini 1941
./run_extra.sh mnist b relu carlini 1941
./run_extra.sh mnist c standard carlini 1941
./run_extra.sh mnist c adversarial carlini 1941
./run_extra.sh mnist c relu carlini 1941
./run_extra.sh mnist a standard carlini 7528
./run_extra.sh mnist a adversarial carlini 7528
./run_extra.sh mnist a relu carlini 7528
./run_extra.sh mnist b standard carlini 7528
./run_extra.sh mnist b adversarial carlini 7528
./run_extra.sh mnist b relu carlini 7528
./run_extra.sh mnist c standard carlini 7528
./run_extra.sh mnist c adversarial carlini 7528
./run_extra.sh mnist c relu carlini 7528
./run_extra.sh mnist a standard carlini 7856
./run_extra.sh mnist a adversarial carlini 7856
./run_extra.sh mnist a relu carlini 7856
./run_extra.sh mnist b standard carlini 7856
./run_extra.sh mnist b adversarial carlini 7856
./run_extra.sh mnist b relu carlini 7856
./run_extra.sh mnist c standard carlini 7856
./run_extra.sh mnist c adversarial carlini 7856
./run_extra.sh mnist c relu carlini 7856
./run_extra.sh mnist a standard carlini 8891
./run_extra.sh mnist a adversarial carlini 8891
./run_extra.sh mnist a relu carlini 8891
./run_extra.sh mnist b standard carlini 8891
./run_extra.sh mnist b adversarial carlini 8891
./run_extra.sh mnist b relu carlini 8891
./run_extra.sh mnist c standard carlini 8891
./run_extra.sh mnist c adversarial carlini 8891
./run_extra.sh mnist c relu carlini 8891
./run_extra.sh mnist a standard carlini 1888
./run_extra.sh mnist a adversarial carlini 1888
./run_extra.sh mnist a relu carlini 1888
./run_extra.sh mnist b standard carlini 1888
./run_extra.sh mnist b adversarial carlini 1888
./run_extra.sh mnist b relu carlini 1888
./run_extra.sh mnist c standard carlini 1888
./run_extra.sh mnist c adversarial carlini 1888
./run_extra.sh mnist c relu carlini 1888
./run_extra.sh mnist a standard carlini 4351
./run_extra.sh mnist a adversarial carlini 4351
./run_extra.sh mnist a relu carlini 4351
./run_extra.sh mnist b standard carlini 4351
./run_extra.sh mnist b adversarial carlini 4351
./run_extra.sh mnist b relu carlini 4351
./run_extra.sh mnist c standard carlini 4351
./run_extra.sh mnist c adversarial carlini 4351
./run_extra.sh mnist c relu carlini 4351
./run_extra.sh mnist a standard carlini 4510
./run_extra.sh mnist a adversarial carlini 4510
./run_extra.sh mnist a relu carlini 4510
./run_extra.sh mnist b standard carlini 4510
./run_extra.sh mnist b adversarial carlini 4510
./run_extra.sh mnist b relu carlini 4510
./run_extra.sh mnist c standard carlini 4510
./run_extra.sh mnist c adversarial carlini 4510
./run_extra.sh mnist c relu carlini 4510
./run_extra.sh mnist a standard carlini 2903
./run_extra.sh mnist a adversarial carlini 2903
./run_extra.sh mnist a relu carlini 2903
./run_extra.sh mnist b standard carlini 2903
./run_extra.sh mnist b adversarial carlini 2903
./run_extra.sh mnist b relu carlini 2903
./run_extra.sh mnist c standard carlini 2903
./run_extra.sh mnist c adversarial carlini 2903
./run_extra.sh mnist c relu carlini 2903
./run_extra.sh mnist a standard carlini 1443
./run_extra.sh mnist a adversarial carlini 1443
./run_extra.sh mnist a relu carlini 1443
./run_extra.sh mnist b standard carlini 1443
./run_extra.sh mnist b adversarial carlini 1443
./run_extra.sh mnist b relu carlini 1443
./run_extra.sh mnist c standard carlini 1443
./run_extra.sh mnist c adversarial carlini 1443
./run_extra.sh mnist c relu carlini 1443
./run_extra.sh mnist a standard carlini 8282
./run_extra.sh mnist a adversarial carlini 8282
./run_extra.sh mnist a relu carlini 8282
./run_extra.sh mnist b standard carlini 8282
./run_extra.sh mnist b adversarial carlini 8282
./run_extra.sh mnist b relu carlini 8282
./run_extra.sh mnist c standard carlini 8282
./run_extra.sh mnist c adversarial carlini 8282
./run_extra.sh mnist c relu carlini 8282
./run_extra.sh mnist a standard carlini 6492
./run_extra.sh mnist a adversarial carlini 6492
./run_extra.sh mnist a relu carlini 6492
./run_extra.sh mnist b standard carlini 6492
./run_extra.sh mnist b adversarial carlini 6492
./run_extra.sh mnist b relu carlini 6492
./run_extra.sh mnist c standard carlini 6492
./run_extra.sh mnist c adversarial carlini 6492
./run_extra.sh mnist c relu carlini 6492
./run_extra.sh mnist a standard carlini 4836
./run_extra.sh mnist a adversarial carlini 4836
./run_extra.sh mnist a relu carlini 4836
./run_extra.sh mnist b standard carlini 4836
./run_extra.sh mnist b adversarial carlini 4836
./run_extra.sh mnist b relu carlini 4836
./run_extra.sh mnist c standard carlini 4836
./run_extra.sh mnist c adversarial carlini 4836
./run_extra.sh mnist c relu carlini 4836
./run_extra.sh mnist a standard carlini 9900
./run_extra.sh mnist a adversarial carlini 9900
./run_extra.sh mnist a relu carlini 9900
./run_extra.sh mnist b standard carlini 9900
./run_extra.sh mnist b adversarial carlini 9900
./run_extra.sh mnist b relu carlini 9900
./run_extra.sh mnist c standard carlini 9900
./run_extra.sh mnist c adversarial carlini 9900
./run_extra.sh mnist c relu carlini 9900
./run_extra.sh mnist a standard carlini 2466
./run_extra.sh mnist a adversarial carlini 2466
./run_extra.sh mnist a relu carlini 2466
./run_extra.sh mnist b standard carlini 2466
./run_extra.sh mnist b adversarial carlini 2466
./run_extra.sh mnist b relu carlini 2466
./run_extra.sh mnist c standard carlini 2466
./run_extra.sh mnist c adversarial carlini 2466
./run_extra.sh mnist c relu carlini 2466
./run_extra.sh mnist a standard carlini 9833
./run_extra.sh mnist a adversarial carlini 9833
./run_extra.sh mnist a relu carlini 9833
./run_extra.sh mnist b standard carlini 9833
./run_extra.sh mnist b adversarial carlini 9833
./run_extra.sh mnist b relu carlini 9833
./run_extra.sh mnist c standard carlini 9833
./run_extra.sh mnist c adversarial carlini 9833
./run_extra.sh mnist c relu carlini 9833
./run_extra.sh mnist a standard carlini 1282
./run_extra.sh mnist a adversarial carlini 1282
./run_extra.sh mnist a relu carlini 1282
./run_extra.sh mnist b standard carlini 1282
./run_extra.sh mnist b adversarial carlini 1282
./run_extra.sh mnist b relu carlini 1282
./run_extra.sh mnist c standard carlini 1282
./run_extra.sh mnist c adversarial carlini 1282
./run_extra.sh mnist c relu carlini 1282
./run_extra.sh mnist a standard carlini 6846
./run_extra.sh mnist a adversarial carlini 6846
./run_extra.sh mnist a relu carlini 6846
./run_extra.sh mnist b standard carlini 6846
./run_extra.sh mnist b adversarial carlini 6846
./run_extra.sh mnist b relu carlini 6846
./run_extra.sh mnist c standard carlini 6846
./run_extra.sh mnist c adversarial carlini 6846
./run_extra.sh mnist c relu carlini 6846
./run_extra.sh mnist a standard carlini 3810
./run_extra.sh mnist a adversarial carlini 3810
./run_extra.sh mnist a relu carlini 3810
./run_extra.sh mnist b standard carlini 3810
./run_extra.sh mnist b adversarial carlini 3810
./run_extra.sh mnist b relu carlini 3810
./run_extra.sh mnist c standard carlini 3810
./run_extra.sh mnist c adversarial carlini 3810
./run_extra.sh mnist c relu carlini 3810
./run_extra.sh mnist a standard carlini 3332
./run_extra.sh mnist a adversarial carlini 3332
./run_extra.sh mnist a relu carlini 3332
./run_extra.sh mnist b standard carlini 3332
./run_extra.sh mnist b adversarial carlini 3332
./run_extra.sh mnist b relu carlini 3332
./run_extra.sh mnist c standard carlini 3332
./run_extra.sh mnist c adversarial carlini 3332
./run_extra.sh mnist c relu carlini 3332
./run_extra.sh mnist a standard carlini 1715
./run_extra.sh mnist a adversarial carlini 1715
./run_extra.sh mnist a relu carlini 1715
./run_extra.sh mnist b standard carlini 1715
./run_extra.sh mnist b adversarial carlini 1715
./run_extra.sh mnist b relu carlini 1715
./run_extra.sh mnist c standard carlini 1715
./run_extra.sh mnist c adversarial carlini 1715
./run_extra.sh mnist c relu carlini 1715
