./run_extra.sh mnist a standard carlini 3371
./run_extra.sh mnist a adversarial carlini 3371
./run_extra.sh mnist a relu carlini 3371
./run_extra.sh mnist b standard carlini 3371
./run_extra.sh mnist b adversarial carlini 3371
./run_extra.sh mnist b relu carlini 3371
./run_extra.sh mnist c standard carlini 3371
./run_extra.sh mnist c adversarial carlini 3371
./run_extra.sh mnist c relu carlini 3371
./run_extra.sh mnist a standard carlini 2373
./run_extra.sh mnist a adversarial carlini 2373
./run_extra.sh mnist a relu carlini 2373
./run_extra.sh mnist b standard carlini 2373
./run_extra.sh mnist b adversarial carlini 2373
./run_extra.sh mnist b relu carlini 2373
./run_extra.sh mnist c standard carlini 2373
./run_extra.sh mnist c adversarial carlini 2373
./run_extra.sh mnist c relu carlini 2373
./run_extra.sh mnist a standard carlini 7436
./run_extra.sh mnist a adversarial carlini 7436
./run_extra.sh mnist a relu carlini 7436
./run_extra.sh mnist b standard carlini 7436
./run_extra.sh mnist b adversarial carlini 7436
./run_extra.sh mnist b relu carlini 7436
./run_extra.sh mnist c standard carlini 7436
./run_extra.sh mnist c adversarial carlini 7436
./run_extra.sh mnist c relu carlini 7436
./run_extra.sh mnist a standard carlini 3204
./run_extra.sh mnist a adversarial carlini 3204
./run_extra.sh mnist a relu carlini 3204
./run_extra.sh mnist b standard carlini 3204
./run_extra.sh mnist b adversarial carlini 3204
./run_extra.sh mnist b relu carlini 3204
./run_extra.sh mnist c standard carlini 3204
./run_extra.sh mnist c adversarial carlini 3204
./run_extra.sh mnist c relu carlini 3204
./run_extra.sh mnist a standard carlini 6831
./run_extra.sh mnist a adversarial carlini 6831
./run_extra.sh mnist a relu carlini 6831
./run_extra.sh mnist b standard carlini 6831
./run_extra.sh mnist b adversarial carlini 6831
./run_extra.sh mnist b relu carlini 6831
./run_extra.sh mnist c standard carlini 6831
./run_extra.sh mnist c adversarial carlini 6831
./run_extra.sh mnist c relu carlini 6831
./run_extra.sh mnist a standard carlini 679
./run_extra.sh mnist a adversarial carlini 679
./run_extra.sh mnist a relu carlini 679
./run_extra.sh mnist b standard carlini 679
./run_extra.sh mnist b adversarial carlini 679
./run_extra.sh mnist b relu carlini 679
./run_extra.sh mnist c standard carlini 679
./run_extra.sh mnist c adversarial carlini 679
./run_extra.sh mnist c relu carlini 679
./run_extra.sh mnist a standard carlini 4171
./run_extra.sh mnist a adversarial carlini 4171
./run_extra.sh mnist a relu carlini 4171
./run_extra.sh mnist b standard carlini 4171
./run_extra.sh mnist b adversarial carlini 4171
./run_extra.sh mnist b relu carlini 4171
./run_extra.sh mnist c standard carlini 4171
./run_extra.sh mnist c adversarial carlini 4171
./run_extra.sh mnist c relu carlini 4171
./run_extra.sh mnist a standard carlini 6904
./run_extra.sh mnist a adversarial carlini 6904
./run_extra.sh mnist a relu carlini 6904
./run_extra.sh mnist b standard carlini 6904
./run_extra.sh mnist b adversarial carlini 6904
./run_extra.sh mnist b relu carlini 6904
./run_extra.sh mnist c standard carlini 6904
./run_extra.sh mnist c adversarial carlini 6904
./run_extra.sh mnist c relu carlini 6904
./run_extra.sh mnist a standard carlini 3806
./run_extra.sh mnist a adversarial carlini 3806
./run_extra.sh mnist a relu carlini 3806
./run_extra.sh mnist b standard carlini 3806
./run_extra.sh mnist b adversarial carlini 3806
./run_extra.sh mnist b relu carlini 3806
./run_extra.sh mnist c standard carlini 3806
./run_extra.sh mnist c adversarial carlini 3806
./run_extra.sh mnist c relu carlini 3806
./run_extra.sh mnist a standard carlini 3700
./run_extra.sh mnist a adversarial carlini 3700
./run_extra.sh mnist a relu carlini 3700
./run_extra.sh mnist b standard carlini 3700
./run_extra.sh mnist b adversarial carlini 3700
./run_extra.sh mnist b relu carlini 3700
./run_extra.sh mnist c standard carlini 3700
./run_extra.sh mnist c adversarial carlini 3700
./run_extra.sh mnist c relu carlini 3700
./run_extra.sh mnist a standard carlini 4070
./run_extra.sh mnist a adversarial carlini 4070
./run_extra.sh mnist a relu carlini 4070
./run_extra.sh mnist b standard carlini 4070
./run_extra.sh mnist b adversarial carlini 4070
./run_extra.sh mnist b relu carlini 4070
./run_extra.sh mnist c standard carlini 4070
./run_extra.sh mnist c adversarial carlini 4070
./run_extra.sh mnist c relu carlini 4070
./run_extra.sh mnist a standard carlini 4525
./run_extra.sh mnist a adversarial carlini 4525
./run_extra.sh mnist a relu carlini 4525
./run_extra.sh mnist b standard carlini 4525
./run_extra.sh mnist b adversarial carlini 4525
./run_extra.sh mnist b relu carlini 4525
./run_extra.sh mnist c standard carlini 4525
./run_extra.sh mnist c adversarial carlini 4525
./run_extra.sh mnist c relu carlini 4525
./run_extra.sh mnist a standard carlini 490
./run_extra.sh mnist a adversarial carlini 490
./run_extra.sh mnist a relu carlini 490
./run_extra.sh mnist b standard carlini 490
./run_extra.sh mnist b adversarial carlini 490
./run_extra.sh mnist b relu carlini 490
./run_extra.sh mnist c standard carlini 490
./run_extra.sh mnist c adversarial carlini 490
./run_extra.sh mnist c relu carlini 490
./run_extra.sh mnist a standard carlini 2464
./run_extra.sh mnist a adversarial carlini 2464
./run_extra.sh mnist a relu carlini 2464
./run_extra.sh mnist b standard carlini 2464
./run_extra.sh mnist b adversarial carlini 2464
./run_extra.sh mnist b relu carlini 2464
./run_extra.sh mnist c standard carlini 2464
./run_extra.sh mnist c adversarial carlini 2464
./run_extra.sh mnist c relu carlini 2464
./run_extra.sh mnist a standard carlini 6595
./run_extra.sh mnist a adversarial carlini 6595
./run_extra.sh mnist a relu carlini 6595
./run_extra.sh mnist b standard carlini 6595
./run_extra.sh mnist b adversarial carlini 6595
./run_extra.sh mnist b relu carlini 6595
./run_extra.sh mnist c standard carlini 6595
./run_extra.sh mnist c adversarial carlini 6595
./run_extra.sh mnist c relu carlini 6595
./run_extra.sh mnist a standard carlini 3206
./run_extra.sh mnist a adversarial carlini 3206
./run_extra.sh mnist a relu carlini 3206
./run_extra.sh mnist b standard carlini 3206
./run_extra.sh mnist b adversarial carlini 3206
./run_extra.sh mnist b relu carlini 3206
./run_extra.sh mnist c standard carlini 3206
./run_extra.sh mnist c adversarial carlini 3206
./run_extra.sh mnist c relu carlini 3206
./run_extra.sh mnist a standard carlini 6525
./run_extra.sh mnist a adversarial carlini 6525
./run_extra.sh mnist a relu carlini 6525
./run_extra.sh mnist b standard carlini 6525
./run_extra.sh mnist b adversarial carlini 6525
./run_extra.sh mnist b relu carlini 6525
./run_extra.sh mnist c standard carlini 6525
./run_extra.sh mnist c adversarial carlini 6525
./run_extra.sh mnist c relu carlini 6525
./run_extra.sh mnist a standard carlini 4264
./run_extra.sh mnist a adversarial carlini 4264
./run_extra.sh mnist a relu carlini 4264
./run_extra.sh mnist b standard carlini 4264
./run_extra.sh mnist b adversarial carlini 4264
./run_extra.sh mnist b relu carlini 4264
./run_extra.sh mnist c standard carlini 4264
./run_extra.sh mnist c adversarial carlini 4264
./run_extra.sh mnist c relu carlini 4264
./run_extra.sh mnist a standard carlini 3260
./run_extra.sh mnist a adversarial carlini 3260
./run_extra.sh mnist a relu carlini 3260
./run_extra.sh mnist b standard carlini 3260
./run_extra.sh mnist b adversarial carlini 3260
./run_extra.sh mnist b relu carlini 3260
./run_extra.sh mnist c standard carlini 3260
./run_extra.sh mnist c adversarial carlini 3260
./run_extra.sh mnist c relu carlini 3260
./run_extra.sh mnist a standard carlini 715
./run_extra.sh mnist a adversarial carlini 715
./run_extra.sh mnist a relu carlini 715
./run_extra.sh mnist b standard carlini 715
./run_extra.sh mnist b adversarial carlini 715
./run_extra.sh mnist b relu carlini 715
./run_extra.sh mnist c standard carlini 715
./run_extra.sh mnist c adversarial carlini 715
./run_extra.sh mnist c relu carlini 715
./run_extra.sh mnist a standard carlini 2317
./run_extra.sh mnist a adversarial carlini 2317
./run_extra.sh mnist a relu carlini 2317
./run_extra.sh mnist b standard carlini 2317
./run_extra.sh mnist b adversarial carlini 2317
./run_extra.sh mnist b relu carlini 2317
./run_extra.sh mnist c standard carlini 2317
./run_extra.sh mnist c adversarial carlini 2317
./run_extra.sh mnist c relu carlini 2317
./run_extra.sh mnist a standard carlini 1154
./run_extra.sh mnist a adversarial carlini 1154
./run_extra.sh mnist a relu carlini 1154
./run_extra.sh mnist b standard carlini 1154
./run_extra.sh mnist b adversarial carlini 1154
./run_extra.sh mnist b relu carlini 1154
./run_extra.sh mnist c standard carlini 1154
./run_extra.sh mnist c adversarial carlini 1154
./run_extra.sh mnist c relu carlini 1154
./run_extra.sh mnist a standard carlini 366
./run_extra.sh mnist a adversarial carlini 366
./run_extra.sh mnist a relu carlini 366
./run_extra.sh mnist b standard carlini 366
./run_extra.sh mnist b adversarial carlini 366
./run_extra.sh mnist b relu carlini 366
./run_extra.sh mnist c standard carlini 366
./run_extra.sh mnist c adversarial carlini 366
./run_extra.sh mnist c relu carlini 366
./run_extra.sh mnist a standard carlini 6407
./run_extra.sh mnist a adversarial carlini 6407
./run_extra.sh mnist a relu carlini 6407
./run_extra.sh mnist b standard carlini 6407
./run_extra.sh mnist b adversarial carlini 6407
./run_extra.sh mnist b relu carlini 6407
./run_extra.sh mnist c standard carlini 6407
./run_extra.sh mnist c adversarial carlini 6407
./run_extra.sh mnist c relu carlini 6407
./run_extra.sh mnist a standard carlini 483
./run_extra.sh mnist a adversarial carlini 483
./run_extra.sh mnist a relu carlini 483
./run_extra.sh mnist b standard carlini 483
./run_extra.sh mnist b adversarial carlini 483
./run_extra.sh mnist b relu carlini 483
./run_extra.sh mnist c standard carlini 483
./run_extra.sh mnist c adversarial carlini 483
./run_extra.sh mnist c relu carlini 483
./run_extra.sh mnist a standard carlini 4788
./run_extra.sh mnist a adversarial carlini 4788
./run_extra.sh mnist a relu carlini 4788
./run_extra.sh mnist b standard carlini 4788
./run_extra.sh mnist b adversarial carlini 4788
./run_extra.sh mnist b relu carlini 4788
./run_extra.sh mnist c standard carlini 4788
./run_extra.sh mnist c adversarial carlini 4788
./run_extra.sh mnist c relu carlini 4788
./run_extra.sh mnist a standard carlini 9038
./run_extra.sh mnist a adversarial carlini 9038
./run_extra.sh mnist a relu carlini 9038
./run_extra.sh mnist b standard carlini 9038
./run_extra.sh mnist b adversarial carlini 9038
./run_extra.sh mnist b relu carlini 9038
./run_extra.sh mnist c standard carlini 9038
./run_extra.sh mnist c adversarial carlini 9038
./run_extra.sh mnist c relu carlini 9038
./run_extra.sh mnist a standard carlini 6132
./run_extra.sh mnist a adversarial carlini 6132
./run_extra.sh mnist a relu carlini 6132
./run_extra.sh mnist b standard carlini 6132
./run_extra.sh mnist b adversarial carlini 6132
./run_extra.sh mnist b relu carlini 6132
./run_extra.sh mnist c standard carlini 6132
./run_extra.sh mnist c adversarial carlini 6132
./run_extra.sh mnist c relu carlini 6132
./run_extra.sh mnist a standard carlini 5264
./run_extra.sh mnist a adversarial carlini 5264
./run_extra.sh mnist a relu carlini 5264
./run_extra.sh mnist b standard carlini 5264
./run_extra.sh mnist b adversarial carlini 5264
./run_extra.sh mnist b relu carlini 5264
./run_extra.sh mnist c standard carlini 5264
./run_extra.sh mnist c adversarial carlini 5264
./run_extra.sh mnist c relu carlini 5264
./run_extra.sh mnist a standard carlini 2909
./run_extra.sh mnist a adversarial carlini 2909
./run_extra.sh mnist a relu carlini 2909
./run_extra.sh mnist b standard carlini 2909
./run_extra.sh mnist b adversarial carlini 2909
./run_extra.sh mnist b relu carlini 2909
./run_extra.sh mnist c standard carlini 2909
./run_extra.sh mnist c adversarial carlini 2909
./run_extra.sh mnist c relu carlini 2909
./run_extra.sh mnist a standard carlini 9881
./run_extra.sh mnist a adversarial carlini 9881
./run_extra.sh mnist a relu carlini 9881
./run_extra.sh mnist b standard carlini 9881
./run_extra.sh mnist b adversarial carlini 9881
./run_extra.sh mnist b relu carlini 9881
./run_extra.sh mnist c standard carlini 9881
./run_extra.sh mnist c adversarial carlini 9881
./run_extra.sh mnist c relu carlini 9881
./run_extra.sh mnist a standard carlini 8140
./run_extra.sh mnist a adversarial carlini 8140
./run_extra.sh mnist a relu carlini 8140
./run_extra.sh mnist b standard carlini 8140
./run_extra.sh mnist b adversarial carlini 8140
./run_extra.sh mnist b relu carlini 8140
./run_extra.sh mnist c standard carlini 8140
./run_extra.sh mnist c adversarial carlini 8140
./run_extra.sh mnist c relu carlini 8140
./run_extra.sh mnist a standard carlini 7404
./run_extra.sh mnist a adversarial carlini 7404
./run_extra.sh mnist a relu carlini 7404
./run_extra.sh mnist b standard carlini 7404
./run_extra.sh mnist b adversarial carlini 7404
./run_extra.sh mnist b relu carlini 7404
./run_extra.sh mnist c standard carlini 7404
./run_extra.sh mnist c adversarial carlini 7404
./run_extra.sh mnist c relu carlini 7404
./run_extra.sh mnist a standard carlini 8509
./run_extra.sh mnist a adversarial carlini 8509
./run_extra.sh mnist a relu carlini 8509
./run_extra.sh mnist b standard carlini 8509
./run_extra.sh mnist b adversarial carlini 8509
./run_extra.sh mnist b relu carlini 8509
./run_extra.sh mnist c standard carlini 8509
./run_extra.sh mnist c adversarial carlini 8509
./run_extra.sh mnist c relu carlini 8509
./run_extra.sh mnist a standard carlini 317
./run_extra.sh mnist a adversarial carlini 317
./run_extra.sh mnist a relu carlini 317
./run_extra.sh mnist b standard carlini 317
./run_extra.sh mnist b adversarial carlini 317
./run_extra.sh mnist b relu carlini 317
./run_extra.sh mnist c standard carlini 317
./run_extra.sh mnist c adversarial carlini 317
./run_extra.sh mnist c relu carlini 317
./run_extra.sh mnist a standard carlini 8404
./run_extra.sh mnist a adversarial carlini 8404
./run_extra.sh mnist a relu carlini 8404
./run_extra.sh mnist b standard carlini 8404
./run_extra.sh mnist b adversarial carlini 8404
./run_extra.sh mnist b relu carlini 8404
./run_extra.sh mnist c standard carlini 8404
./run_extra.sh mnist c adversarial carlini 8404
./run_extra.sh mnist c relu carlini 8404
./run_extra.sh mnist a standard carlini 7153
./run_extra.sh mnist a adversarial carlini 7153
./run_extra.sh mnist a relu carlini 7153
./run_extra.sh mnist b standard carlini 7153
./run_extra.sh mnist b adversarial carlini 7153
./run_extra.sh mnist b relu carlini 7153
./run_extra.sh mnist c standard carlini 7153
./run_extra.sh mnist c adversarial carlini 7153
./run_extra.sh mnist c relu carlini 7153
./run_extra.sh mnist a standard carlini 1110
./run_extra.sh mnist a adversarial carlini 1110
./run_extra.sh mnist a relu carlini 1110
./run_extra.sh mnist b standard carlini 1110
./run_extra.sh mnist b adversarial carlini 1110
./run_extra.sh mnist b relu carlini 1110
./run_extra.sh mnist c standard carlini 1110
./run_extra.sh mnist c adversarial carlini 1110
./run_extra.sh mnist c relu carlini 1110
./run_extra.sh mnist a standard carlini 6227
./run_extra.sh mnist a adversarial carlini 6227
./run_extra.sh mnist a relu carlini 6227
./run_extra.sh mnist b standard carlini 6227
./run_extra.sh mnist b adversarial carlini 6227
./run_extra.sh mnist b relu carlini 6227
./run_extra.sh mnist c standard carlini 6227
./run_extra.sh mnist c adversarial carlini 6227
./run_extra.sh mnist c relu carlini 6227
./run_extra.sh mnist a standard carlini 9289
./run_extra.sh mnist a adversarial carlini 9289
./run_extra.sh mnist a relu carlini 9289
./run_extra.sh mnist b standard carlini 9289
./run_extra.sh mnist b adversarial carlini 9289
./run_extra.sh mnist b relu carlini 9289
./run_extra.sh mnist c standard carlini 9289
./run_extra.sh mnist c adversarial carlini 9289
./run_extra.sh mnist c relu carlini 9289
./run_extra.sh mnist a standard carlini 2834
./run_extra.sh mnist a adversarial carlini 2834
./run_extra.sh mnist a relu carlini 2834
./run_extra.sh mnist b standard carlini 2834
./run_extra.sh mnist b adversarial carlini 2834
./run_extra.sh mnist b relu carlini 2834
./run_extra.sh mnist c standard carlini 2834
./run_extra.sh mnist c adversarial carlini 2834
./run_extra.sh mnist c relu carlini 2834
./run_extra.sh mnist a standard carlini 6995
./run_extra.sh mnist a adversarial carlini 6995
./run_extra.sh mnist a relu carlini 6995
./run_extra.sh mnist b standard carlini 6995
./run_extra.sh mnist b adversarial carlini 6995
./run_extra.sh mnist b relu carlini 6995
./run_extra.sh mnist c standard carlini 6995
./run_extra.sh mnist c adversarial carlini 6995
./run_extra.sh mnist c relu carlini 6995
./run_extra.sh mnist a standard carlini 1408
./run_extra.sh mnist a adversarial carlini 1408
./run_extra.sh mnist a relu carlini 1408
./run_extra.sh mnist b standard carlini 1408
./run_extra.sh mnist b adversarial carlini 1408
./run_extra.sh mnist b relu carlini 1408
./run_extra.sh mnist c standard carlini 1408
./run_extra.sh mnist c adversarial carlini 1408
./run_extra.sh mnist c relu carlini 1408
./run_extra.sh mnist a standard carlini 634
./run_extra.sh mnist a adversarial carlini 634
./run_extra.sh mnist a relu carlini 634
./run_extra.sh mnist b standard carlini 634
./run_extra.sh mnist b adversarial carlini 634
./run_extra.sh mnist b relu carlini 634
./run_extra.sh mnist c standard carlini 634
./run_extra.sh mnist c adversarial carlini 634
./run_extra.sh mnist c relu carlini 634
./run_extra.sh mnist a standard carlini 718
./run_extra.sh mnist a adversarial carlini 718
./run_extra.sh mnist a relu carlini 718
./run_extra.sh mnist b standard carlini 718
./run_extra.sh mnist b adversarial carlini 718
./run_extra.sh mnist b relu carlini 718
./run_extra.sh mnist c standard carlini 718
./run_extra.sh mnist c adversarial carlini 718
./run_extra.sh mnist c relu carlini 718
./run_extra.sh mnist a standard carlini 4787
./run_extra.sh mnist a adversarial carlini 4787
./run_extra.sh mnist a relu carlini 4787
./run_extra.sh mnist b standard carlini 4787
./run_extra.sh mnist b adversarial carlini 4787
./run_extra.sh mnist b relu carlini 4787
./run_extra.sh mnist c standard carlini 4787
./run_extra.sh mnist c adversarial carlini 4787
./run_extra.sh mnist c relu carlini 4787
./run_extra.sh mnist a standard carlini 8133
./run_extra.sh mnist a adversarial carlini 8133
./run_extra.sh mnist a relu carlini 8133
./run_extra.sh mnist b standard carlini 8133
./run_extra.sh mnist b adversarial carlini 8133
./run_extra.sh mnist b relu carlini 8133
./run_extra.sh mnist c standard carlini 8133
./run_extra.sh mnist c adversarial carlini 8133
./run_extra.sh mnist c relu carlini 8133
./run_extra.sh mnist a standard carlini 2688
./run_extra.sh mnist a adversarial carlini 2688
./run_extra.sh mnist a relu carlini 2688
./run_extra.sh mnist b standard carlini 2688
./run_extra.sh mnist b adversarial carlini 2688
./run_extra.sh mnist b relu carlini 2688
./run_extra.sh mnist c standard carlini 2688
./run_extra.sh mnist c adversarial carlini 2688
./run_extra.sh mnist c relu carlini 2688
./run_extra.sh mnist a standard carlini 5976
./run_extra.sh mnist a adversarial carlini 5976
./run_extra.sh mnist a relu carlini 5976
./run_extra.sh mnist b standard carlini 5976
./run_extra.sh mnist b adversarial carlini 5976
./run_extra.sh mnist b relu carlini 5976
./run_extra.sh mnist c standard carlini 5976
./run_extra.sh mnist c adversarial carlini 5976
./run_extra.sh mnist c relu carlini 5976
./run_extra.sh mnist a standard carlini 7434
./run_extra.sh mnist a adversarial carlini 7434
./run_extra.sh mnist a relu carlini 7434
./run_extra.sh mnist b standard carlini 7434
./run_extra.sh mnist b adversarial carlini 7434
./run_extra.sh mnist b relu carlini 7434
./run_extra.sh mnist c standard carlini 7434
./run_extra.sh mnist c adversarial carlini 7434
./run_extra.sh mnist c relu carlini 7434
./run_extra.sh mnist a standard carlini 7184
./run_extra.sh mnist a adversarial carlini 7184
./run_extra.sh mnist a relu carlini 7184
./run_extra.sh mnist b standard carlini 7184
./run_extra.sh mnist b adversarial carlini 7184
./run_extra.sh mnist b relu carlini 7184
./run_extra.sh mnist c standard carlini 7184
./run_extra.sh mnist c adversarial carlini 7184
./run_extra.sh mnist c relu carlini 7184
./run_extra.sh mnist a standard carlini 7904
./run_extra.sh mnist a adversarial carlini 7904
./run_extra.sh mnist a relu carlini 7904
./run_extra.sh mnist b standard carlini 7904
./run_extra.sh mnist b adversarial carlini 7904
./run_extra.sh mnist b relu carlini 7904
./run_extra.sh mnist c standard carlini 7904
./run_extra.sh mnist c adversarial carlini 7904
./run_extra.sh mnist c relu carlini 7904
./run_extra.sh mnist a standard carlini 2104
./run_extra.sh mnist a adversarial carlini 2104
./run_extra.sh mnist a relu carlini 2104
./run_extra.sh mnist b standard carlini 2104
./run_extra.sh mnist b adversarial carlini 2104
./run_extra.sh mnist b relu carlini 2104
./run_extra.sh mnist c standard carlini 2104
./run_extra.sh mnist c adversarial carlini 2104
./run_extra.sh mnist c relu carlini 2104
./run_extra.sh mnist a standard carlini 4928
./run_extra.sh mnist a adversarial carlini 4928
./run_extra.sh mnist a relu carlini 4928
./run_extra.sh mnist b standard carlini 4928
./run_extra.sh mnist b adversarial carlini 4928
./run_extra.sh mnist b relu carlini 4928
./run_extra.sh mnist c standard carlini 4928
./run_extra.sh mnist c adversarial carlini 4928
./run_extra.sh mnist c relu carlini 4928
./run_extra.sh mnist a standard carlini 5348
./run_extra.sh mnist a adversarial carlini 5348
./run_extra.sh mnist a relu carlini 5348
./run_extra.sh mnist b standard carlini 5348
./run_extra.sh mnist b adversarial carlini 5348
./run_extra.sh mnist b relu carlini 5348
./run_extra.sh mnist c standard carlini 5348
./run_extra.sh mnist c adversarial carlini 5348
./run_extra.sh mnist c relu carlini 5348
./run_extra.sh mnist a standard carlini 6558
./run_extra.sh mnist a adversarial carlini 6558
./run_extra.sh mnist a relu carlini 6558
./run_extra.sh mnist b standard carlini 6558
./run_extra.sh mnist b adversarial carlini 6558
./run_extra.sh mnist b relu carlini 6558
./run_extra.sh mnist c standard carlini 6558
./run_extra.sh mnist c adversarial carlini 6558
./run_extra.sh mnist c relu carlini 6558
./run_extra.sh mnist a standard carlini 7858
./run_extra.sh mnist a adversarial carlini 7858
./run_extra.sh mnist a relu carlini 7858
./run_extra.sh mnist b standard carlini 7858
./run_extra.sh mnist b adversarial carlini 7858
./run_extra.sh mnist b relu carlini 7858
./run_extra.sh mnist c standard carlini 7858
./run_extra.sh mnist c adversarial carlini 7858
./run_extra.sh mnist c relu carlini 7858
./run_extra.sh mnist a standard carlini 9443
./run_extra.sh mnist a adversarial carlini 9443
./run_extra.sh mnist a relu carlini 9443
./run_extra.sh mnist b standard carlini 9443
./run_extra.sh mnist b adversarial carlini 9443
./run_extra.sh mnist b relu carlini 9443
./run_extra.sh mnist c standard carlini 9443
./run_extra.sh mnist c adversarial carlini 9443
./run_extra.sh mnist c relu carlini 9443
./run_extra.sh mnist a standard carlini 1969
./run_extra.sh mnist a adversarial carlini 1969
./run_extra.sh mnist a relu carlini 1969
./run_extra.sh mnist b standard carlini 1969
./run_extra.sh mnist b adversarial carlini 1969
./run_extra.sh mnist b relu carlini 1969
./run_extra.sh mnist c standard carlini 1969
./run_extra.sh mnist c adversarial carlini 1969
./run_extra.sh mnist c relu carlini 1969
./run_extra.sh mnist a standard carlini 6111
./run_extra.sh mnist a adversarial carlini 6111
./run_extra.sh mnist a relu carlini 6111
./run_extra.sh mnist b standard carlini 6111
./run_extra.sh mnist b adversarial carlini 6111
./run_extra.sh mnist b relu carlini 6111
./run_extra.sh mnist c standard carlini 6111
./run_extra.sh mnist c adversarial carlini 6111
./run_extra.sh mnist c relu carlini 6111
./run_extra.sh mnist a standard carlini 1435
./run_extra.sh mnist a adversarial carlini 1435
./run_extra.sh mnist a relu carlini 1435
./run_extra.sh mnist b standard carlini 1435
./run_extra.sh mnist b adversarial carlini 1435
./run_extra.sh mnist b relu carlini 1435
./run_extra.sh mnist c standard carlini 1435
./run_extra.sh mnist c adversarial carlini 1435
./run_extra.sh mnist c relu carlini 1435
./run_extra.sh mnist a standard carlini 9426
./run_extra.sh mnist a adversarial carlini 9426
./run_extra.sh mnist a relu carlini 9426
./run_extra.sh mnist b standard carlini 9426
./run_extra.sh mnist b adversarial carlini 9426
./run_extra.sh mnist b relu carlini 9426
./run_extra.sh mnist c standard carlini 9426
./run_extra.sh mnist c adversarial carlini 9426
./run_extra.sh mnist c relu carlini 9426
./run_extra.sh mnist a standard carlini 9913
./run_extra.sh mnist a adversarial carlini 9913
./run_extra.sh mnist a relu carlini 9913
./run_extra.sh mnist b standard carlini 9913
./run_extra.sh mnist b adversarial carlini 9913
./run_extra.sh mnist b relu carlini 9913
./run_extra.sh mnist c standard carlini 9913
./run_extra.sh mnist c adversarial carlini 9913
./run_extra.sh mnist c relu carlini 9913
./run_extra.sh mnist a standard carlini 7421
./run_extra.sh mnist a adversarial carlini 7421
./run_extra.sh mnist a relu carlini 7421
./run_extra.sh mnist b standard carlini 7421
./run_extra.sh mnist b adversarial carlini 7421
./run_extra.sh mnist b relu carlini 7421
./run_extra.sh mnist c standard carlini 7421
./run_extra.sh mnist c adversarial carlini 7421
./run_extra.sh mnist c relu carlini 7421
./run_extra.sh mnist a standard carlini 3243
./run_extra.sh mnist a adversarial carlini 3243
./run_extra.sh mnist a relu carlini 3243
./run_extra.sh mnist b standard carlini 3243
./run_extra.sh mnist b adversarial carlini 3243
./run_extra.sh mnist b relu carlini 3243
./run_extra.sh mnist c standard carlini 3243
./run_extra.sh mnist c adversarial carlini 3243
./run_extra.sh mnist c relu carlini 3243
./run_extra.sh mnist a standard carlini 9355
./run_extra.sh mnist a adversarial carlini 9355
./run_extra.sh mnist a relu carlini 9355
./run_extra.sh mnist b standard carlini 9355
./run_extra.sh mnist b adversarial carlini 9355
./run_extra.sh mnist b relu carlini 9355
./run_extra.sh mnist c standard carlini 9355
./run_extra.sh mnist c adversarial carlini 9355
./run_extra.sh mnist c relu carlini 9355
./run_extra.sh mnist a standard carlini 301
./run_extra.sh mnist a adversarial carlini 301
./run_extra.sh mnist a relu carlini 301
./run_extra.sh mnist b standard carlini 301
./run_extra.sh mnist b adversarial carlini 301
./run_extra.sh mnist b relu carlini 301
./run_extra.sh mnist c standard carlini 301
./run_extra.sh mnist c adversarial carlini 301
./run_extra.sh mnist c relu carlini 301
./run_extra.sh mnist a standard carlini 4551
./run_extra.sh mnist a adversarial carlini 4551
./run_extra.sh mnist a relu carlini 4551
./run_extra.sh mnist b standard carlini 4551
./run_extra.sh mnist b adversarial carlini 4551
./run_extra.sh mnist b relu carlini 4551
./run_extra.sh mnist c standard carlini 4551
./run_extra.sh mnist c adversarial carlini 4551
./run_extra.sh mnist c relu carlini 4551
./run_extra.sh mnist a standard carlini 7209
./run_extra.sh mnist a adversarial carlini 7209
./run_extra.sh mnist a relu carlini 7209
./run_extra.sh mnist b standard carlini 7209
./run_extra.sh mnist b adversarial carlini 7209
./run_extra.sh mnist b relu carlini 7209
./run_extra.sh mnist c standard carlini 7209
./run_extra.sh mnist c adversarial carlini 7209
./run_extra.sh mnist c relu carlini 7209
./run_extra.sh mnist a standard carlini 7915
./run_extra.sh mnist a adversarial carlini 7915
./run_extra.sh mnist a relu carlini 7915
./run_extra.sh mnist b standard carlini 7915
./run_extra.sh mnist b adversarial carlini 7915
./run_extra.sh mnist b relu carlini 7915
./run_extra.sh mnist c standard carlini 7915
./run_extra.sh mnist c adversarial carlini 7915
./run_extra.sh mnist c relu carlini 7915
./run_extra.sh mnist a standard carlini 2180
./run_extra.sh mnist a adversarial carlini 2180
./run_extra.sh mnist a relu carlini 2180
./run_extra.sh mnist b standard carlini 2180
./run_extra.sh mnist b adversarial carlini 2180
./run_extra.sh mnist b relu carlini 2180
./run_extra.sh mnist c standard carlini 2180
./run_extra.sh mnist c adversarial carlini 2180
./run_extra.sh mnist c relu carlini 2180
./run_extra.sh mnist a standard carlini 964
./run_extra.sh mnist a adversarial carlini 964
./run_extra.sh mnist a relu carlini 964
./run_extra.sh mnist b standard carlini 964
./run_extra.sh mnist b adversarial carlini 964
./run_extra.sh mnist b relu carlini 964
./run_extra.sh mnist c standard carlini 964
./run_extra.sh mnist c adversarial carlini 964
./run_extra.sh mnist c relu carlini 964
./run_extra.sh mnist a standard carlini 5593
./run_extra.sh mnist a adversarial carlini 5593
./run_extra.sh mnist a relu carlini 5593
./run_extra.sh mnist b standard carlini 5593
./run_extra.sh mnist b adversarial carlini 5593
./run_extra.sh mnist b relu carlini 5593
./run_extra.sh mnist c standard carlini 5593
./run_extra.sh mnist c adversarial carlini 5593
./run_extra.sh mnist c relu carlini 5593
./run_extra.sh mnist a standard carlini 3157
./run_extra.sh mnist a adversarial carlini 3157
./run_extra.sh mnist a relu carlini 3157
./run_extra.sh mnist b standard carlini 3157
./run_extra.sh mnist b adversarial carlini 3157
./run_extra.sh mnist b relu carlini 3157
./run_extra.sh mnist c standard carlini 3157
./run_extra.sh mnist c adversarial carlini 3157
./run_extra.sh mnist c relu carlini 3157
./run_extra.sh mnist a standard carlini 5816
./run_extra.sh mnist a adversarial carlini 5816
./run_extra.sh mnist a relu carlini 5816
./run_extra.sh mnist b standard carlini 5816
./run_extra.sh mnist b adversarial carlini 5816
./run_extra.sh mnist b relu carlini 5816
./run_extra.sh mnist c standard carlini 5816
./run_extra.sh mnist c adversarial carlini 5816
./run_extra.sh mnist c relu carlini 5816
./run_extra.sh mnist a standard carlini 252
./run_extra.sh mnist a adversarial carlini 252
./run_extra.sh mnist a relu carlini 252
./run_extra.sh mnist b standard carlini 252
./run_extra.sh mnist b adversarial carlini 252
./run_extra.sh mnist b relu carlini 252
./run_extra.sh mnist c standard carlini 252
./run_extra.sh mnist c adversarial carlini 252
./run_extra.sh mnist c relu carlini 252
./run_extra.sh mnist a standard carlini 5923
./run_extra.sh mnist a adversarial carlini 5923
./run_extra.sh mnist a relu carlini 5923
./run_extra.sh mnist b standard carlini 5923
./run_extra.sh mnist b adversarial carlini 5923
./run_extra.sh mnist b relu carlini 5923
./run_extra.sh mnist c standard carlini 5923
./run_extra.sh mnist c adversarial carlini 5923
./run_extra.sh mnist c relu carlini 5923
./run_extra.sh mnist a standard carlini 3239
./run_extra.sh mnist a adversarial carlini 3239
./run_extra.sh mnist a relu carlini 3239
./run_extra.sh mnist b standard carlini 3239
./run_extra.sh mnist b adversarial carlini 3239
./run_extra.sh mnist b relu carlini 3239
./run_extra.sh mnist c standard carlini 3239
./run_extra.sh mnist c adversarial carlini 3239
./run_extra.sh mnist c relu carlini 3239
./run_extra.sh mnist a standard carlini 6569
./run_extra.sh mnist a adversarial carlini 6569
./run_extra.sh mnist a relu carlini 6569
./run_extra.sh mnist b standard carlini 6569
./run_extra.sh mnist b adversarial carlini 6569
./run_extra.sh mnist b relu carlini 6569
./run_extra.sh mnist c standard carlini 6569
./run_extra.sh mnist c adversarial carlini 6569
./run_extra.sh mnist c relu carlini 6569
./run_extra.sh mnist a standard carlini 2113
./run_extra.sh mnist a adversarial carlini 2113
./run_extra.sh mnist a relu carlini 2113
./run_extra.sh mnist b standard carlini 2113
./run_extra.sh mnist b adversarial carlini 2113
./run_extra.sh mnist b relu carlini 2113
./run_extra.sh mnist c standard carlini 2113
./run_extra.sh mnist c adversarial carlini 2113
./run_extra.sh mnist c relu carlini 2113
./run_extra.sh mnist a standard carlini 5561
./run_extra.sh mnist a adversarial carlini 5561
./run_extra.sh mnist a relu carlini 5561
./run_extra.sh mnist b standard carlini 5561
./run_extra.sh mnist b adversarial carlini 5561
./run_extra.sh mnist b relu carlini 5561
./run_extra.sh mnist c standard carlini 5561
./run_extra.sh mnist c adversarial carlini 5561
./run_extra.sh mnist c relu carlini 5561
./run_extra.sh mnist a standard carlini 7880
./run_extra.sh mnist a adversarial carlini 7880
./run_extra.sh mnist a relu carlini 7880
./run_extra.sh mnist b standard carlini 7880
./run_extra.sh mnist b adversarial carlini 7880
./run_extra.sh mnist b relu carlini 7880
./run_extra.sh mnist c standard carlini 7880
./run_extra.sh mnist c adversarial carlini 7880
./run_extra.sh mnist c relu carlini 7880
./run_extra.sh mnist a standard carlini 7100
./run_extra.sh mnist a adversarial carlini 7100
./run_extra.sh mnist a relu carlini 7100
./run_extra.sh mnist b standard carlini 7100
./run_extra.sh mnist b adversarial carlini 7100
./run_extra.sh mnist b relu carlini 7100
./run_extra.sh mnist c standard carlini 7100
./run_extra.sh mnist c adversarial carlini 7100
./run_extra.sh mnist c relu carlini 7100
./run_extra.sh mnist a standard carlini 7375
./run_extra.sh mnist a adversarial carlini 7375
./run_extra.sh mnist a relu carlini 7375
./run_extra.sh mnist b standard carlini 7375
./run_extra.sh mnist b adversarial carlini 7375
./run_extra.sh mnist b relu carlini 7375
./run_extra.sh mnist c standard carlini 7375
./run_extra.sh mnist c adversarial carlini 7375
./run_extra.sh mnist c relu carlini 7375
./run_extra.sh mnist a standard carlini 9759
./run_extra.sh mnist a adversarial carlini 9759
./run_extra.sh mnist a relu carlini 9759
./run_extra.sh mnist b standard carlini 9759
./run_extra.sh mnist b adversarial carlini 9759
./run_extra.sh mnist b relu carlini 9759
./run_extra.sh mnist c standard carlini 9759
./run_extra.sh mnist c adversarial carlini 9759
./run_extra.sh mnist c relu carlini 9759
./run_extra.sh mnist a standard carlini 6481
./run_extra.sh mnist a adversarial carlini 6481
./run_extra.sh mnist a relu carlini 6481
./run_extra.sh mnist b standard carlini 6481
./run_extra.sh mnist b adversarial carlini 6481
./run_extra.sh mnist b relu carlini 6481
./run_extra.sh mnist c standard carlini 6481
./run_extra.sh mnist c adversarial carlini 6481
./run_extra.sh mnist c relu carlini 6481
./run_extra.sh mnist a standard carlini 4801
./run_extra.sh mnist a adversarial carlini 4801
./run_extra.sh mnist a relu carlini 4801
./run_extra.sh mnist b standard carlini 4801
./run_extra.sh mnist b adversarial carlini 4801
./run_extra.sh mnist b relu carlini 4801
./run_extra.sh mnist c standard carlini 4801
./run_extra.sh mnist c adversarial carlini 4801
./run_extra.sh mnist c relu carlini 4801
./run_extra.sh mnist a standard carlini 9107
./run_extra.sh mnist a adversarial carlini 9107
./run_extra.sh mnist a relu carlini 9107
./run_extra.sh mnist b standard carlini 9107
./run_extra.sh mnist b adversarial carlini 9107
./run_extra.sh mnist b relu carlini 9107
./run_extra.sh mnist c standard carlini 9107
./run_extra.sh mnist c adversarial carlini 9107
./run_extra.sh mnist c relu carlini 9107
./run_extra.sh mnist a standard carlini 6915
./run_extra.sh mnist a adversarial carlini 6915
./run_extra.sh mnist a relu carlini 6915
./run_extra.sh mnist b standard carlini 6915
./run_extra.sh mnist b adversarial carlini 6915
./run_extra.sh mnist b relu carlini 6915
./run_extra.sh mnist c standard carlini 6915
./run_extra.sh mnist c adversarial carlini 6915
./run_extra.sh mnist c relu carlini 6915
./run_extra.sh mnist a standard carlini 4051
./run_extra.sh mnist a adversarial carlini 4051
./run_extra.sh mnist a relu carlini 4051
./run_extra.sh mnist b standard carlini 4051
./run_extra.sh mnist b adversarial carlini 4051
./run_extra.sh mnist b relu carlini 4051
./run_extra.sh mnist c standard carlini 4051
./run_extra.sh mnist c adversarial carlini 4051
./run_extra.sh mnist c relu carlini 4051
./run_extra.sh mnist a standard carlini 3517
./run_extra.sh mnist a adversarial carlini 3517
./run_extra.sh mnist a relu carlini 3517
./run_extra.sh mnist b standard carlini 3517
./run_extra.sh mnist b adversarial carlini 3517
./run_extra.sh mnist b relu carlini 3517
./run_extra.sh mnist c standard carlini 3517
./run_extra.sh mnist c adversarial carlini 3517
./run_extra.sh mnist c relu carlini 3517
./run_extra.sh mnist a standard carlini 7567
./run_extra.sh mnist a adversarial carlini 7567
./run_extra.sh mnist a relu carlini 7567
./run_extra.sh mnist b standard carlini 7567
./run_extra.sh mnist b adversarial carlini 7567
./run_extra.sh mnist b relu carlini 7567
./run_extra.sh mnist c standard carlini 7567
./run_extra.sh mnist c adversarial carlini 7567
./run_extra.sh mnist c relu carlini 7567
./run_extra.sh mnist a standard carlini 2283
./run_extra.sh mnist a adversarial carlini 2283
./run_extra.sh mnist a relu carlini 2283
./run_extra.sh mnist b standard carlini 2283
./run_extra.sh mnist b adversarial carlini 2283
./run_extra.sh mnist b relu carlini 2283
./run_extra.sh mnist c standard carlini 2283
./run_extra.sh mnist c adversarial carlini 2283
./run_extra.sh mnist c relu carlini 2283
./run_extra.sh mnist a standard carlini 2043
./run_extra.sh mnist a adversarial carlini 2043
./run_extra.sh mnist a relu carlini 2043
./run_extra.sh mnist b standard carlini 2043
./run_extra.sh mnist b adversarial carlini 2043
./run_extra.sh mnist b relu carlini 2043
./run_extra.sh mnist c standard carlini 2043
./run_extra.sh mnist c adversarial carlini 2043
./run_extra.sh mnist c relu carlini 2043
./run_extra.sh mnist a standard carlini 8946
./run_extra.sh mnist a adversarial carlini 8946
./run_extra.sh mnist a relu carlini 8946
./run_extra.sh mnist b standard carlini 8946
./run_extra.sh mnist b adversarial carlini 8946
./run_extra.sh mnist b relu carlini 8946
./run_extra.sh mnist c standard carlini 8946
./run_extra.sh mnist c adversarial carlini 8946
./run_extra.sh mnist c relu carlini 8946
./run_extra.sh mnist a standard carlini 5622
./run_extra.sh mnist a adversarial carlini 5622
./run_extra.sh mnist a relu carlini 5622
./run_extra.sh mnist b standard carlini 5622
./run_extra.sh mnist b adversarial carlini 5622
./run_extra.sh mnist b relu carlini 5622
./run_extra.sh mnist c standard carlini 5622
./run_extra.sh mnist c adversarial carlini 5622
./run_extra.sh mnist c relu carlini 5622
./run_extra.sh mnist a standard carlini 3468
./run_extra.sh mnist a adversarial carlini 3468
./run_extra.sh mnist a relu carlini 3468
./run_extra.sh mnist b standard carlini 3468
./run_extra.sh mnist b adversarial carlini 3468
./run_extra.sh mnist b relu carlini 3468
./run_extra.sh mnist c standard carlini 3468
./run_extra.sh mnist c adversarial carlini 3468
./run_extra.sh mnist c relu carlini 3468
./run_extra.sh mnist a standard carlini 3240
./run_extra.sh mnist a adversarial carlini 3240
./run_extra.sh mnist a relu carlini 3240
./run_extra.sh mnist b standard carlini 3240
./run_extra.sh mnist b adversarial carlini 3240
./run_extra.sh mnist b relu carlini 3240
./run_extra.sh mnist c standard carlini 3240
./run_extra.sh mnist c adversarial carlini 3240
./run_extra.sh mnist c relu carlini 3240
./run_extra.sh mnist a standard carlini 4267
./run_extra.sh mnist a adversarial carlini 4267
./run_extra.sh mnist a relu carlini 4267
./run_extra.sh mnist b standard carlini 4267
./run_extra.sh mnist b adversarial carlini 4267
./run_extra.sh mnist b relu carlini 4267
./run_extra.sh mnist c standard carlini 4267
./run_extra.sh mnist c adversarial carlini 4267
./run_extra.sh mnist c relu carlini 4267
./run_extra.sh mnist a standard carlini 4705
./run_extra.sh mnist a adversarial carlini 4705
./run_extra.sh mnist a relu carlini 4705
./run_extra.sh mnist b standard carlini 4705
./run_extra.sh mnist b adversarial carlini 4705
./run_extra.sh mnist b relu carlini 4705
./run_extra.sh mnist c standard carlini 4705
./run_extra.sh mnist c adversarial carlini 4705
./run_extra.sh mnist c relu carlini 4705
./run_extra.sh mnist a standard carlini 9105
./run_extra.sh mnist a adversarial carlini 9105
./run_extra.sh mnist a relu carlini 9105
./run_extra.sh mnist b standard carlini 9105
./run_extra.sh mnist b adversarial carlini 9105
./run_extra.sh mnist b relu carlini 9105
./run_extra.sh mnist c standard carlini 9105
./run_extra.sh mnist c adversarial carlini 9105
./run_extra.sh mnist c relu carlini 9105
./run_extra.sh mnist a standard carlini 7182
./run_extra.sh mnist a adversarial carlini 7182
./run_extra.sh mnist a relu carlini 7182
./run_extra.sh mnist b standard carlini 7182
./run_extra.sh mnist b adversarial carlini 7182
./run_extra.sh mnist b relu carlini 7182
./run_extra.sh mnist c standard carlini 7182
./run_extra.sh mnist c adversarial carlini 7182
./run_extra.sh mnist c relu carlini 7182
./run_extra.sh mnist a standard carlini 9870
./run_extra.sh mnist a adversarial carlini 9870
./run_extra.sh mnist a relu carlini 9870
./run_extra.sh mnist b standard carlini 9870
./run_extra.sh mnist b adversarial carlini 9870
./run_extra.sh mnist b relu carlini 9870
./run_extra.sh mnist c standard carlini 9870
./run_extra.sh mnist c adversarial carlini 9870
./run_extra.sh mnist c relu carlini 9870
./run_extra.sh mnist a standard carlini 7432
./run_extra.sh mnist a adversarial carlini 7432
./run_extra.sh mnist a relu carlini 7432
./run_extra.sh mnist b standard carlini 7432
./run_extra.sh mnist b adversarial carlini 7432
./run_extra.sh mnist b relu carlini 7432
./run_extra.sh mnist c standard carlini 7432
./run_extra.sh mnist c adversarial carlini 7432
./run_extra.sh mnist c relu carlini 7432
./run_extra.sh mnist a standard carlini 1364
./run_extra.sh mnist a adversarial carlini 1364
./run_extra.sh mnist a relu carlini 1364
./run_extra.sh mnist b standard carlini 1364
./run_extra.sh mnist b adversarial carlini 1364
./run_extra.sh mnist b relu carlini 1364
./run_extra.sh mnist c standard carlini 1364
./run_extra.sh mnist c adversarial carlini 1364
./run_extra.sh mnist c relu carlini 1364
./run_extra.sh mnist a standard carlini 2111
./run_extra.sh mnist a adversarial carlini 2111
./run_extra.sh mnist a relu carlini 2111
./run_extra.sh mnist b standard carlini 2111
./run_extra.sh mnist b adversarial carlini 2111
./run_extra.sh mnist b relu carlini 2111
./run_extra.sh mnist c standard carlini 2111
./run_extra.sh mnist c adversarial carlini 2111
./run_extra.sh mnist c relu carlini 2111
./run_extra.sh mnist a standard carlini 6249
./run_extra.sh mnist a adversarial carlini 6249
./run_extra.sh mnist a relu carlini 6249
./run_extra.sh mnist b standard carlini 6249
./run_extra.sh mnist b adversarial carlini 6249
./run_extra.sh mnist b relu carlini 6249
./run_extra.sh mnist c standard carlini 6249
./run_extra.sh mnist c adversarial carlini 6249
./run_extra.sh mnist c relu carlini 6249
./run_extra.sh mnist a standard carlini 4675
./run_extra.sh mnist a adversarial carlini 4675
./run_extra.sh mnist a relu carlini 4675
./run_extra.sh mnist b standard carlini 4675
./run_extra.sh mnist b adversarial carlini 4675
./run_extra.sh mnist b relu carlini 4675
./run_extra.sh mnist c standard carlini 4675
./run_extra.sh mnist c adversarial carlini 4675
./run_extra.sh mnist c relu carlini 4675
./run_extra.sh mnist a standard carlini 5171
./run_extra.sh mnist a adversarial carlini 5171
./run_extra.sh mnist a relu carlini 5171
./run_extra.sh mnist b standard carlini 5171
./run_extra.sh mnist b adversarial carlini 5171
./run_extra.sh mnist b relu carlini 5171
./run_extra.sh mnist c standard carlini 5171
./run_extra.sh mnist c adversarial carlini 5171
./run_extra.sh mnist c relu carlini 5171
./run_extra.sh mnist a standard carlini 1835
./run_extra.sh mnist a adversarial carlini 1835
./run_extra.sh mnist a relu carlini 1835
./run_extra.sh mnist b standard carlini 1835
./run_extra.sh mnist b adversarial carlini 1835
./run_extra.sh mnist b relu carlini 1835
./run_extra.sh mnist c standard carlini 1835
./run_extra.sh mnist c adversarial carlini 1835
./run_extra.sh mnist c relu carlini 1835
./run_extra.sh mnist a standard carlini 688
./run_extra.sh mnist a adversarial carlini 688
./run_extra.sh mnist a relu carlini 688
./run_extra.sh mnist b standard carlini 688
./run_extra.sh mnist b adversarial carlini 688
./run_extra.sh mnist b relu carlini 688
./run_extra.sh mnist c standard carlini 688
./run_extra.sh mnist c adversarial carlini 688
./run_extra.sh mnist c relu carlini 688
./run_extra.sh mnist a standard carlini 5608
./run_extra.sh mnist a adversarial carlini 5608
./run_extra.sh mnist a relu carlini 5608
./run_extra.sh mnist b standard carlini 5608
./run_extra.sh mnist b adversarial carlini 5608
./run_extra.sh mnist b relu carlini 5608
./run_extra.sh mnist c standard carlini 5608
./run_extra.sh mnist c adversarial carlini 5608
./run_extra.sh mnist c relu carlini 5608
./run_extra.sh mnist a standard carlini 2787
./run_extra.sh mnist a adversarial carlini 2787
./run_extra.sh mnist a relu carlini 2787
./run_extra.sh mnist b standard carlini 2787
./run_extra.sh mnist b adversarial carlini 2787
./run_extra.sh mnist b relu carlini 2787
./run_extra.sh mnist c standard carlini 2787
./run_extra.sh mnist c adversarial carlini 2787
./run_extra.sh mnist c relu carlini 2787
./run_extra.sh mnist a standard carlini 5231
./run_extra.sh mnist a adversarial carlini 5231
./run_extra.sh mnist a relu carlini 5231
./run_extra.sh mnist b standard carlini 5231
./run_extra.sh mnist b adversarial carlini 5231
./run_extra.sh mnist b relu carlini 5231
./run_extra.sh mnist c standard carlini 5231
./run_extra.sh mnist c adversarial carlini 5231
./run_extra.sh mnist c relu carlini 5231
./run_extra.sh mnist a standard carlini 3564
./run_extra.sh mnist a adversarial carlini 3564
./run_extra.sh mnist a relu carlini 3564
./run_extra.sh mnist b standard carlini 3564
./run_extra.sh mnist b adversarial carlini 3564
./run_extra.sh mnist b relu carlini 3564
./run_extra.sh mnist c standard carlini 3564
./run_extra.sh mnist c adversarial carlini 3564
./run_extra.sh mnist c relu carlini 3564
./run_extra.sh mnist a standard carlini 9591
./run_extra.sh mnist a adversarial carlini 9591
./run_extra.sh mnist a relu carlini 9591
./run_extra.sh mnist b standard carlini 9591
./run_extra.sh mnist b adversarial carlini 9591
./run_extra.sh mnist b relu carlini 9591
./run_extra.sh mnist c standard carlini 9591
./run_extra.sh mnist c adversarial carlini 9591
./run_extra.sh mnist c relu carlini 9591
./run_extra.sh mnist a standard carlini 2725
./run_extra.sh mnist a adversarial carlini 2725
./run_extra.sh mnist a relu carlini 2725
./run_extra.sh mnist b standard carlini 2725
./run_extra.sh mnist b adversarial carlini 2725
./run_extra.sh mnist b relu carlini 2725
./run_extra.sh mnist c standard carlini 2725
./run_extra.sh mnist c adversarial carlini 2725
./run_extra.sh mnist c relu carlini 2725
./run_extra.sh mnist a standard carlini 4775
./run_extra.sh mnist a adversarial carlini 4775
./run_extra.sh mnist a relu carlini 4775
./run_extra.sh mnist b standard carlini 4775
./run_extra.sh mnist b adversarial carlini 4775
./run_extra.sh mnist b relu carlini 4775
./run_extra.sh mnist c standard carlini 4775
./run_extra.sh mnist c adversarial carlini 4775
./run_extra.sh mnist c relu carlini 4775
./run_extra.sh mnist a standard carlini 482
./run_extra.sh mnist a adversarial carlini 482
./run_extra.sh mnist a relu carlini 482
./run_extra.sh mnist b standard carlini 482
./run_extra.sh mnist b adversarial carlini 482
./run_extra.sh mnist b relu carlini 482
./run_extra.sh mnist c standard carlini 482
./run_extra.sh mnist c adversarial carlini 482
./run_extra.sh mnist c relu carlini 482
./run_extra.sh mnist a standard carlini 4444
./run_extra.sh mnist a adversarial carlini 4444
./run_extra.sh mnist a relu carlini 4444
./run_extra.sh mnist b standard carlini 4444
./run_extra.sh mnist b adversarial carlini 4444
./run_extra.sh mnist b relu carlini 4444
./run_extra.sh mnist c standard carlini 4444
./run_extra.sh mnist c adversarial carlini 4444
./run_extra.sh mnist c relu carlini 4444
./run_extra.sh mnist a standard carlini 6361
./run_extra.sh mnist a adversarial carlini 6361
./run_extra.sh mnist a relu carlini 6361
./run_extra.sh mnist b standard carlini 6361
./run_extra.sh mnist b adversarial carlini 6361
./run_extra.sh mnist b relu carlini 6361
./run_extra.sh mnist c standard carlini 6361
./run_extra.sh mnist c adversarial carlini 6361
./run_extra.sh mnist c relu carlini 6361
./run_extra.sh mnist a standard carlini 4248
./run_extra.sh mnist a adversarial carlini 4248
./run_extra.sh mnist a relu carlini 4248
./run_extra.sh mnist b standard carlini 4248
./run_extra.sh mnist b adversarial carlini 4248
./run_extra.sh mnist b relu carlini 4248
./run_extra.sh mnist c standard carlini 4248
./run_extra.sh mnist c adversarial carlini 4248
./run_extra.sh mnist c relu carlini 4248
./run_extra.sh mnist a standard carlini 5312
./run_extra.sh mnist a adversarial carlini 5312
./run_extra.sh mnist a relu carlini 5312
./run_extra.sh mnist b standard carlini 5312
./run_extra.sh mnist b adversarial carlini 5312
./run_extra.sh mnist b relu carlini 5312
./run_extra.sh mnist c standard carlini 5312
./run_extra.sh mnist c adversarial carlini 5312
./run_extra.sh mnist c relu carlini 5312
./run_extra.sh mnist a standard carlini 6465
./run_extra.sh mnist a adversarial carlini 6465
./run_extra.sh mnist a relu carlini 6465
./run_extra.sh mnist b standard carlini 6465
./run_extra.sh mnist b adversarial carlini 6465
./run_extra.sh mnist b relu carlini 6465
./run_extra.sh mnist c standard carlini 6465
./run_extra.sh mnist c adversarial carlini 6465
./run_extra.sh mnist c relu carlini 6465
./run_extra.sh mnist a standard carlini 5478
./run_extra.sh mnist a adversarial carlini 5478
./run_extra.sh mnist a relu carlini 5478
./run_extra.sh mnist b standard carlini 5478
./run_extra.sh mnist b adversarial carlini 5478
./run_extra.sh mnist b relu carlini 5478
./run_extra.sh mnist c standard carlini 5478
./run_extra.sh mnist c adversarial carlini 5478
./run_extra.sh mnist c relu carlini 5478
./run_extra.sh mnist a standard carlini 382
./run_extra.sh mnist a adversarial carlini 382
./run_extra.sh mnist a relu carlini 382
./run_extra.sh mnist b standard carlini 382
./run_extra.sh mnist b adversarial carlini 382
./run_extra.sh mnist b relu carlini 382
./run_extra.sh mnist c standard carlini 382
./run_extra.sh mnist c adversarial carlini 382
./run_extra.sh mnist c relu carlini 382
./run_extra.sh mnist a standard carlini 7955
./run_extra.sh mnist a adversarial carlini 7955
./run_extra.sh mnist a relu carlini 7955
./run_extra.sh mnist b standard carlini 7955
./run_extra.sh mnist b adversarial carlini 7955
./run_extra.sh mnist b relu carlini 7955
./run_extra.sh mnist c standard carlini 7955
./run_extra.sh mnist c adversarial carlini 7955
./run_extra.sh mnist c relu carlini 7955
./run_extra.sh mnist a standard carlini 8589
./run_extra.sh mnist a adversarial carlini 8589
./run_extra.sh mnist a relu carlini 8589
./run_extra.sh mnist b standard carlini 8589
./run_extra.sh mnist b adversarial carlini 8589
./run_extra.sh mnist b relu carlini 8589
./run_extra.sh mnist c standard carlini 8589
./run_extra.sh mnist c adversarial carlini 8589
./run_extra.sh mnist c relu carlini 8589
./run_extra.sh mnist a standard carlini 5598
./run_extra.sh mnist a adversarial carlini 5598
./run_extra.sh mnist a relu carlini 5598
./run_extra.sh mnist b standard carlini 5598
./run_extra.sh mnist b adversarial carlini 5598
./run_extra.sh mnist b relu carlini 5598
./run_extra.sh mnist c standard carlini 5598
./run_extra.sh mnist c adversarial carlini 5598
./run_extra.sh mnist c relu carlini 5598
./run_extra.sh mnist a standard carlini 8361
./run_extra.sh mnist a adversarial carlini 8361
./run_extra.sh mnist a relu carlini 8361
./run_extra.sh mnist b standard carlini 8361
./run_extra.sh mnist b adversarial carlini 8361
./run_extra.sh mnist b relu carlini 8361
./run_extra.sh mnist c standard carlini 8361
./run_extra.sh mnist c adversarial carlini 8361
./run_extra.sh mnist c relu carlini 8361
./run_extra.sh mnist a standard carlini 3058
./run_extra.sh mnist a adversarial carlini 3058
./run_extra.sh mnist a relu carlini 3058
./run_extra.sh mnist b standard carlini 3058
./run_extra.sh mnist b adversarial carlini 3058
./run_extra.sh mnist b relu carlini 3058
./run_extra.sh mnist c standard carlini 3058
./run_extra.sh mnist c adversarial carlini 3058
./run_extra.sh mnist c relu carlini 3058
./run_extra.sh mnist a standard carlini 7338
./run_extra.sh mnist a adversarial carlini 7338
./run_extra.sh mnist a relu carlini 7338
./run_extra.sh mnist b standard carlini 7338
./run_extra.sh mnist b adversarial carlini 7338
./run_extra.sh mnist b relu carlini 7338
./run_extra.sh mnist c standard carlini 7338
./run_extra.sh mnist c adversarial carlini 7338
./run_extra.sh mnist c relu carlini 7338
./run_extra.sh mnist a standard carlini 3392
./run_extra.sh mnist a adversarial carlini 3392
./run_extra.sh mnist a relu carlini 3392
./run_extra.sh mnist b standard carlini 3392
./run_extra.sh mnist b adversarial carlini 3392
./run_extra.sh mnist b relu carlini 3392
./run_extra.sh mnist c standard carlini 3392
./run_extra.sh mnist c adversarial carlini 3392
./run_extra.sh mnist c relu carlini 3392
./run_extra.sh mnist a standard carlini 3575
./run_extra.sh mnist a adversarial carlini 3575
./run_extra.sh mnist a relu carlini 3575
./run_extra.sh mnist b standard carlini 3575
./run_extra.sh mnist b adversarial carlini 3575
./run_extra.sh mnist b relu carlini 3575
./run_extra.sh mnist c standard carlini 3575
./run_extra.sh mnist c adversarial carlini 3575
./run_extra.sh mnist c relu carlini 3575
./run_extra.sh mnist a standard carlini 7340
./run_extra.sh mnist a adversarial carlini 7340
./run_extra.sh mnist a relu carlini 7340
./run_extra.sh mnist b standard carlini 7340
./run_extra.sh mnist b adversarial carlini 7340
./run_extra.sh mnist b relu carlini 7340
./run_extra.sh mnist c standard carlini 7340
./run_extra.sh mnist c adversarial carlini 7340
./run_extra.sh mnist c relu carlini 7340
./run_extra.sh mnist a standard carlini 1886
./run_extra.sh mnist a adversarial carlini 1886
./run_extra.sh mnist a relu carlini 1886
./run_extra.sh mnist b standard carlini 1886
./run_extra.sh mnist b adversarial carlini 1886
./run_extra.sh mnist b relu carlini 1886
./run_extra.sh mnist c standard carlini 1886
./run_extra.sh mnist c adversarial carlini 1886
./run_extra.sh mnist c relu carlini 1886
./run_extra.sh mnist a standard carlini 2950
./run_extra.sh mnist a adversarial carlini 2950
./run_extra.sh mnist a relu carlini 2950
./run_extra.sh mnist b standard carlini 2950
./run_extra.sh mnist b adversarial carlini 2950
./run_extra.sh mnist b relu carlini 2950
./run_extra.sh mnist c standard carlini 2950
./run_extra.sh mnist c adversarial carlini 2950
./run_extra.sh mnist c relu carlini 2950
./run_extra.sh mnist a standard carlini 3636
./run_extra.sh mnist a adversarial carlini 3636
./run_extra.sh mnist a relu carlini 3636
./run_extra.sh mnist b standard carlini 3636
./run_extra.sh mnist b adversarial carlini 3636
./run_extra.sh mnist b relu carlini 3636
./run_extra.sh mnist c standard carlini 3636
./run_extra.sh mnist c adversarial carlini 3636
./run_extra.sh mnist c relu carlini 3636
./run_extra.sh mnist a standard carlini 9968
./run_extra.sh mnist a adversarial carlini 9968
./run_extra.sh mnist a relu carlini 9968
./run_extra.sh mnist b standard carlini 9968
./run_extra.sh mnist b adversarial carlini 9968
./run_extra.sh mnist b relu carlini 9968
./run_extra.sh mnist c standard carlini 9968
./run_extra.sh mnist c adversarial carlini 9968
./run_extra.sh mnist c relu carlini 9968
./run_extra.sh mnist a standard carlini 8359
./run_extra.sh mnist a adversarial carlini 8359
./run_extra.sh mnist a relu carlini 8359
./run_extra.sh mnist b standard carlini 8359
./run_extra.sh mnist b adversarial carlini 8359
./run_extra.sh mnist b relu carlini 8359
./run_extra.sh mnist c standard carlini 8359
./run_extra.sh mnist c adversarial carlini 8359
./run_extra.sh mnist c relu carlini 8359
./run_extra.sh mnist a standard carlini 2775
./run_extra.sh mnist a adversarial carlini 2775
./run_extra.sh mnist a relu carlini 2775
./run_extra.sh mnist b standard carlini 2775
./run_extra.sh mnist b adversarial carlini 2775
./run_extra.sh mnist b relu carlini 2775
./run_extra.sh mnist c standard carlini 2775
./run_extra.sh mnist c adversarial carlini 2775
./run_extra.sh mnist c relu carlini 2775
./run_extra.sh mnist a standard carlini 5034
./run_extra.sh mnist a adversarial carlini 5034
./run_extra.sh mnist a relu carlini 5034
./run_extra.sh mnist b standard carlini 5034
./run_extra.sh mnist b adversarial carlini 5034
./run_extra.sh mnist b relu carlini 5034
./run_extra.sh mnist c standard carlini 5034
./run_extra.sh mnist c adversarial carlini 5034
./run_extra.sh mnist c relu carlini 5034
./run_extra.sh mnist a standard carlini 8885
./run_extra.sh mnist a adversarial carlini 8885
./run_extra.sh mnist a relu carlini 8885
./run_extra.sh mnist b standard carlini 8885
./run_extra.sh mnist b adversarial carlini 8885
./run_extra.sh mnist b relu carlini 8885
./run_extra.sh mnist c standard carlini 8885
./run_extra.sh mnist c adversarial carlini 8885
./run_extra.sh mnist c relu carlini 8885
./run_extra.sh mnist a standard carlini 9186
./run_extra.sh mnist a adversarial carlini 9186
./run_extra.sh mnist a relu carlini 9186
./run_extra.sh mnist b standard carlini 9186
./run_extra.sh mnist b adversarial carlini 9186
./run_extra.sh mnist b relu carlini 9186
./run_extra.sh mnist c standard carlini 9186
./run_extra.sh mnist c adversarial carlini 9186
./run_extra.sh mnist c relu carlini 9186
./run_extra.sh mnist a standard carlini 4406
./run_extra.sh mnist a adversarial carlini 4406
./run_extra.sh mnist a relu carlini 4406
./run_extra.sh mnist b standard carlini 4406
./run_extra.sh mnist b adversarial carlini 4406
./run_extra.sh mnist b relu carlini 4406
./run_extra.sh mnist c standard carlini 4406
./run_extra.sh mnist c adversarial carlini 4406
./run_extra.sh mnist c relu carlini 4406
./run_extra.sh mnist a standard carlini 2777
./run_extra.sh mnist a adversarial carlini 2777
./run_extra.sh mnist a relu carlini 2777
./run_extra.sh mnist b standard carlini 2777
./run_extra.sh mnist b adversarial carlini 2777
./run_extra.sh mnist b relu carlini 2777
./run_extra.sh mnist c standard carlini 2777
./run_extra.sh mnist c adversarial carlini 2777
./run_extra.sh mnist c relu carlini 2777
./run_extra.sh mnist a standard carlini 6463
./run_extra.sh mnist a adversarial carlini 6463
./run_extra.sh mnist a relu carlini 6463
./run_extra.sh mnist b standard carlini 6463
./run_extra.sh mnist b adversarial carlini 6463
./run_extra.sh mnist b relu carlini 6463
./run_extra.sh mnist c standard carlini 6463
./run_extra.sh mnist c adversarial carlini 6463
./run_extra.sh mnist c relu carlini 6463
./run_extra.sh mnist a standard carlini 8421
./run_extra.sh mnist a adversarial carlini 8421
./run_extra.sh mnist a relu carlini 8421
./run_extra.sh mnist b standard carlini 8421
./run_extra.sh mnist b adversarial carlini 8421
./run_extra.sh mnist b relu carlini 8421
./run_extra.sh mnist c standard carlini 8421
./run_extra.sh mnist c adversarial carlini 8421
./run_extra.sh mnist c relu carlini 8421
./run_extra.sh mnist a standard carlini 6805
./run_extra.sh mnist a adversarial carlini 6805
./run_extra.sh mnist a relu carlini 6805
./run_extra.sh mnist b standard carlini 6805
./run_extra.sh mnist b adversarial carlini 6805
./run_extra.sh mnist b relu carlini 6805
./run_extra.sh mnist c standard carlini 6805
./run_extra.sh mnist c adversarial carlini 6805
./run_extra.sh mnist c relu carlini 6805
./run_extra.sh mnist a standard carlini 1945
./run_extra.sh mnist a adversarial carlini 1945
./run_extra.sh mnist a relu carlini 1945
./run_extra.sh mnist b standard carlini 1945
./run_extra.sh mnist b adversarial carlini 1945
./run_extra.sh mnist b relu carlini 1945
./run_extra.sh mnist c standard carlini 1945
./run_extra.sh mnist c adversarial carlini 1945
./run_extra.sh mnist c relu carlini 1945
./run_extra.sh mnist a standard carlini 4712
./run_extra.sh mnist a adversarial carlini 4712
./run_extra.sh mnist a relu carlini 4712
./run_extra.sh mnist b standard carlini 4712
./run_extra.sh mnist b adversarial carlini 4712
./run_extra.sh mnist b relu carlini 4712
./run_extra.sh mnist c standard carlini 4712
./run_extra.sh mnist c adversarial carlini 4712
./run_extra.sh mnist c relu carlini 4712
./run_extra.sh mnist a standard carlini 1218
./run_extra.sh mnist a adversarial carlini 1218
./run_extra.sh mnist a relu carlini 1218
./run_extra.sh mnist b standard carlini 1218
./run_extra.sh mnist b adversarial carlini 1218
./run_extra.sh mnist b relu carlini 1218
./run_extra.sh mnist c standard carlini 1218
./run_extra.sh mnist c adversarial carlini 1218
./run_extra.sh mnist c relu carlini 1218
./run_extra.sh mnist a standard carlini 5577
./run_extra.sh mnist a adversarial carlini 5577
./run_extra.sh mnist a relu carlini 5577
./run_extra.sh mnist b standard carlini 5577
./run_extra.sh mnist b adversarial carlini 5577
./run_extra.sh mnist b relu carlini 5577
./run_extra.sh mnist c standard carlini 5577
./run_extra.sh mnist c adversarial carlini 5577
./run_extra.sh mnist c relu carlini 5577
./run_extra.sh mnist a standard carlini 6828
./run_extra.sh mnist a adversarial carlini 6828
./run_extra.sh mnist a relu carlini 6828
./run_extra.sh mnist b standard carlini 6828
./run_extra.sh mnist b adversarial carlini 6828
./run_extra.sh mnist b relu carlini 6828
./run_extra.sh mnist c standard carlini 6828
./run_extra.sh mnist c adversarial carlini 6828
./run_extra.sh mnist c relu carlini 6828
./run_extra.sh mnist a standard carlini 1523
./run_extra.sh mnist a adversarial carlini 1523
./run_extra.sh mnist a relu carlini 1523
./run_extra.sh mnist b standard carlini 1523
./run_extra.sh mnist b adversarial carlini 1523
./run_extra.sh mnist b relu carlini 1523
./run_extra.sh mnist c standard carlini 1523
./run_extra.sh mnist c adversarial carlini 1523
./run_extra.sh mnist c relu carlini 1523
./run_extra.sh mnist a standard carlini 9682
./run_extra.sh mnist a adversarial carlini 9682
./run_extra.sh mnist a relu carlini 9682
./run_extra.sh mnist b standard carlini 9682
./run_extra.sh mnist b adversarial carlini 9682
./run_extra.sh mnist b relu carlini 9682
./run_extra.sh mnist c standard carlini 9682
./run_extra.sh mnist c adversarial carlini 9682
./run_extra.sh mnist c relu carlini 9682
./run_extra.sh mnist a standard carlini 5859
./run_extra.sh mnist a adversarial carlini 5859
./run_extra.sh mnist a relu carlini 5859
./run_extra.sh mnist b standard carlini 5859
./run_extra.sh mnist b adversarial carlini 5859
./run_extra.sh mnist b relu carlini 5859
./run_extra.sh mnist c standard carlini 5859
./run_extra.sh mnist c adversarial carlini 5859
./run_extra.sh mnist c relu carlini 5859
./run_extra.sh mnist a standard carlini 7912
./run_extra.sh mnist a adversarial carlini 7912
./run_extra.sh mnist a relu carlini 7912
./run_extra.sh mnist b standard carlini 7912
./run_extra.sh mnist b adversarial carlini 7912
./run_extra.sh mnist b relu carlini 7912
./run_extra.sh mnist c standard carlini 7912
./run_extra.sh mnist c adversarial carlini 7912
./run_extra.sh mnist c relu carlini 7912
./run_extra.sh mnist a standard carlini 8408
./run_extra.sh mnist a adversarial carlini 8408
./run_extra.sh mnist a relu carlini 8408
./run_extra.sh mnist b standard carlini 8408
./run_extra.sh mnist b adversarial carlini 8408
./run_extra.sh mnist b relu carlini 8408
./run_extra.sh mnist c standard carlini 8408
./run_extra.sh mnist c adversarial carlini 8408
./run_extra.sh mnist c relu carlini 8408
./run_extra.sh mnist a standard carlini 4183
./run_extra.sh mnist a adversarial carlini 4183
./run_extra.sh mnist a relu carlini 4183
./run_extra.sh mnist b standard carlini 4183
./run_extra.sh mnist b adversarial carlini 4183
./run_extra.sh mnist b relu carlini 4183
./run_extra.sh mnist c standard carlini 4183
./run_extra.sh mnist c adversarial carlini 4183
./run_extra.sh mnist c relu carlini 4183
./run_extra.sh mnist a standard carlini 9502
./run_extra.sh mnist a adversarial carlini 9502
./run_extra.sh mnist a relu carlini 9502
./run_extra.sh mnist b standard carlini 9502
./run_extra.sh mnist b adversarial carlini 9502
./run_extra.sh mnist b relu carlini 9502
./run_extra.sh mnist c standard carlini 9502
./run_extra.sh mnist c adversarial carlini 9502
./run_extra.sh mnist c relu carlini 9502
./run_extra.sh mnist a standard carlini 8533
./run_extra.sh mnist a adversarial carlini 8533
./run_extra.sh mnist a relu carlini 8533
./run_extra.sh mnist b standard carlini 8533
./run_extra.sh mnist b adversarial carlini 8533
./run_extra.sh mnist b relu carlini 8533
./run_extra.sh mnist c standard carlini 8533
./run_extra.sh mnist c adversarial carlini 8533
./run_extra.sh mnist c relu carlini 8533
./run_extra.sh mnist a standard carlini 3448
./run_extra.sh mnist a adversarial carlini 3448
./run_extra.sh mnist a relu carlini 3448
./run_extra.sh mnist b standard carlini 3448
./run_extra.sh mnist b adversarial carlini 3448
./run_extra.sh mnist b relu carlini 3448
./run_extra.sh mnist c standard carlini 3448
./run_extra.sh mnist c adversarial carlini 3448
./run_extra.sh mnist c relu carlini 3448
./run_extra.sh mnist a standard carlini 6281
./run_extra.sh mnist a adversarial carlini 6281
./run_extra.sh mnist a relu carlini 6281
./run_extra.sh mnist b standard carlini 6281
./run_extra.sh mnist b adversarial carlini 6281
./run_extra.sh mnist b relu carlini 6281
./run_extra.sh mnist c standard carlini 6281
./run_extra.sh mnist c adversarial carlini 6281
./run_extra.sh mnist c relu carlini 6281
./run_extra.sh mnist a standard carlini 8123
./run_extra.sh mnist a adversarial carlini 8123
./run_extra.sh mnist a relu carlini 8123
./run_extra.sh mnist b standard carlini 8123
./run_extra.sh mnist b adversarial carlini 8123
./run_extra.sh mnist b relu carlini 8123
./run_extra.sh mnist c standard carlini 8123
./run_extra.sh mnist c adversarial carlini 8123
./run_extra.sh mnist c relu carlini 8123
./run_extra.sh mnist a standard carlini 2263
./run_extra.sh mnist a adversarial carlini 2263
./run_extra.sh mnist a relu carlini 2263
./run_extra.sh mnist b standard carlini 2263
./run_extra.sh mnist b adversarial carlini 2263
./run_extra.sh mnist b relu carlini 2263
./run_extra.sh mnist c standard carlini 2263
./run_extra.sh mnist c adversarial carlini 2263
./run_extra.sh mnist c relu carlini 2263
./run_extra.sh mnist a standard carlini 4647
./run_extra.sh mnist a adversarial carlini 4647
./run_extra.sh mnist a relu carlini 4647
./run_extra.sh mnist b standard carlini 4647
./run_extra.sh mnist b adversarial carlini 4647
./run_extra.sh mnist b relu carlini 4647
./run_extra.sh mnist c standard carlini 4647
./run_extra.sh mnist c adversarial carlini 4647
./run_extra.sh mnist c relu carlini 4647
./run_extra.sh mnist a standard carlini 2190
./run_extra.sh mnist a adversarial carlini 2190
./run_extra.sh mnist a relu carlini 2190
./run_extra.sh mnist b standard carlini 2190
./run_extra.sh mnist b adversarial carlini 2190
./run_extra.sh mnist b relu carlini 2190
./run_extra.sh mnist c standard carlini 2190
./run_extra.sh mnist c adversarial carlini 2190
./run_extra.sh mnist c relu carlini 2190
./run_extra.sh mnist a standard carlini 7793
./run_extra.sh mnist a adversarial carlini 7793
./run_extra.sh mnist a relu carlini 7793
./run_extra.sh mnist b standard carlini 7793
./run_extra.sh mnist b adversarial carlini 7793
./run_extra.sh mnist b relu carlini 7793
./run_extra.sh mnist c standard carlini 7793
./run_extra.sh mnist c adversarial carlini 7793
./run_extra.sh mnist c relu carlini 7793
./run_extra.sh mnist a standard carlini 3983
./run_extra.sh mnist a adversarial carlini 3983
./run_extra.sh mnist a relu carlini 3983
./run_extra.sh mnist b standard carlini 3983
./run_extra.sh mnist b adversarial carlini 3983
./run_extra.sh mnist b relu carlini 3983
./run_extra.sh mnist c standard carlini 3983
./run_extra.sh mnist c adversarial carlini 3983
./run_extra.sh mnist c relu carlini 3983
./run_extra.sh mnist a standard carlini 1551
./run_extra.sh mnist a adversarial carlini 1551
./run_extra.sh mnist a relu carlini 1551
./run_extra.sh mnist b standard carlini 1551
./run_extra.sh mnist b adversarial carlini 1551
./run_extra.sh mnist b relu carlini 1551
./run_extra.sh mnist c standard carlini 1551
./run_extra.sh mnist c adversarial carlini 1551
./run_extra.sh mnist c relu carlini 1551
./run_extra.sh mnist a standard carlini 8703
./run_extra.sh mnist a adversarial carlini 8703
./run_extra.sh mnist a relu carlini 8703
./run_extra.sh mnist b standard carlini 8703
./run_extra.sh mnist b adversarial carlini 8703
./run_extra.sh mnist b relu carlini 8703
./run_extra.sh mnist c standard carlini 8703
./run_extra.sh mnist c adversarial carlini 8703
./run_extra.sh mnist c relu carlini 8703
./run_extra.sh mnist a standard carlini 1695
./run_extra.sh mnist a adversarial carlini 1695
./run_extra.sh mnist a relu carlini 1695
./run_extra.sh mnist b standard carlini 1695
./run_extra.sh mnist b adversarial carlini 1695
./run_extra.sh mnist b relu carlini 1695
./run_extra.sh mnist c standard carlini 1695
./run_extra.sh mnist c adversarial carlini 1695
./run_extra.sh mnist c relu carlini 1695
./run_extra.sh mnist a standard carlini 5374
./run_extra.sh mnist a adversarial carlini 5374
./run_extra.sh mnist a relu carlini 5374
./run_extra.sh mnist b standard carlini 5374
./run_extra.sh mnist b adversarial carlini 5374
./run_extra.sh mnist b relu carlini 5374
./run_extra.sh mnist c standard carlini 5374
./run_extra.sh mnist c adversarial carlini 5374
./run_extra.sh mnist c relu carlini 5374
./run_extra.sh mnist a standard carlini 5659
./run_extra.sh mnist a adversarial carlini 5659
./run_extra.sh mnist a relu carlini 5659
./run_extra.sh mnist b standard carlini 5659
./run_extra.sh mnist b adversarial carlini 5659
./run_extra.sh mnist b relu carlini 5659
./run_extra.sh mnist c standard carlini 5659
./run_extra.sh mnist c adversarial carlini 5659
./run_extra.sh mnist c relu carlini 5659
./run_extra.sh mnist a standard carlini 6708
./run_extra.sh mnist a adversarial carlini 6708
./run_extra.sh mnist a relu carlini 6708
./run_extra.sh mnist b standard carlini 6708
./run_extra.sh mnist b adversarial carlini 6708
./run_extra.sh mnist b relu carlini 6708
./run_extra.sh mnist c standard carlini 6708
./run_extra.sh mnist c adversarial carlini 6708
./run_extra.sh mnist c relu carlini 6708
./run_extra.sh mnist a standard carlini 2236
./run_extra.sh mnist a adversarial carlini 2236
./run_extra.sh mnist a relu carlini 2236
./run_extra.sh mnist b standard carlini 2236
./run_extra.sh mnist b adversarial carlini 2236
./run_extra.sh mnist b relu carlini 2236
./run_extra.sh mnist c standard carlini 2236
./run_extra.sh mnist c adversarial carlini 2236
./run_extra.sh mnist c relu carlini 2236
./run_extra.sh mnist a standard carlini 1794
./run_extra.sh mnist a adversarial carlini 1794
./run_extra.sh mnist a relu carlini 1794
./run_extra.sh mnist b standard carlini 1794
./run_extra.sh mnist b adversarial carlini 1794
./run_extra.sh mnist b relu carlini 1794
./run_extra.sh mnist c standard carlini 1794
./run_extra.sh mnist c adversarial carlini 1794
./run_extra.sh mnist c relu carlini 1794
./run_extra.sh mnist a standard carlini 4142
./run_extra.sh mnist a adversarial carlini 4142
./run_extra.sh mnist a relu carlini 4142
./run_extra.sh mnist b standard carlini 4142
./run_extra.sh mnist b adversarial carlini 4142
./run_extra.sh mnist b relu carlini 4142
./run_extra.sh mnist c standard carlini 4142
./run_extra.sh mnist c adversarial carlini 4142
./run_extra.sh mnist c relu carlini 4142
./run_extra.sh mnist a standard carlini 3787
./run_extra.sh mnist a adversarial carlini 3787
./run_extra.sh mnist a relu carlini 3787
./run_extra.sh mnist b standard carlini 3787
./run_extra.sh mnist b adversarial carlini 3787
./run_extra.sh mnist b relu carlini 3787
./run_extra.sh mnist c standard carlini 3787
./run_extra.sh mnist c adversarial carlini 3787
./run_extra.sh mnist c relu carlini 3787
./run_extra.sh mnist a standard carlini 9965
./run_extra.sh mnist a adversarial carlini 9965
./run_extra.sh mnist a relu carlini 9965
./run_extra.sh mnist b standard carlini 9965
./run_extra.sh mnist b adversarial carlini 9965
./run_extra.sh mnist b relu carlini 9965
./run_extra.sh mnist c standard carlini 9965
./run_extra.sh mnist c adversarial carlini 9965
./run_extra.sh mnist c relu carlini 9965
./run_extra.sh mnist a standard carlini 6082
./run_extra.sh mnist a adversarial carlini 6082
./run_extra.sh mnist a relu carlini 6082
./run_extra.sh mnist b standard carlini 6082
./run_extra.sh mnist b adversarial carlini 6082
./run_extra.sh mnist b relu carlini 6082
./run_extra.sh mnist c standard carlini 6082
./run_extra.sh mnist c adversarial carlini 6082
./run_extra.sh mnist c relu carlini 6082
./run_extra.sh mnist a standard carlini 5809
./run_extra.sh mnist a adversarial carlini 5809
./run_extra.sh mnist a relu carlini 5809
./run_extra.sh mnist b standard carlini 5809
./run_extra.sh mnist b adversarial carlini 5809
./run_extra.sh mnist b relu carlini 5809
./run_extra.sh mnist c standard carlini 5809
./run_extra.sh mnist c adversarial carlini 5809
./run_extra.sh mnist c relu carlini 5809
./run_extra.sh mnist a standard carlini 9890
./run_extra.sh mnist a adversarial carlini 9890
./run_extra.sh mnist a relu carlini 9890
./run_extra.sh mnist b standard carlini 9890
./run_extra.sh mnist b adversarial carlini 9890
./run_extra.sh mnist b relu carlini 9890
./run_extra.sh mnist c standard carlini 9890
./run_extra.sh mnist c adversarial carlini 9890
./run_extra.sh mnist c relu carlini 9890
./run_extra.sh mnist a standard carlini 4010
./run_extra.sh mnist a adversarial carlini 4010
./run_extra.sh mnist a relu carlini 4010
./run_extra.sh mnist b standard carlini 4010
./run_extra.sh mnist b adversarial carlini 4010
./run_extra.sh mnist b relu carlini 4010
./run_extra.sh mnist c standard carlini 4010
./run_extra.sh mnist c adversarial carlini 4010
./run_extra.sh mnist c relu carlini 4010
./run_extra.sh mnist a standard carlini 6148
./run_extra.sh mnist a adversarial carlini 6148
./run_extra.sh mnist a relu carlini 6148
./run_extra.sh mnist b standard carlini 6148
./run_extra.sh mnist b adversarial carlini 6148
./run_extra.sh mnist b relu carlini 6148
./run_extra.sh mnist c standard carlini 6148
./run_extra.sh mnist c adversarial carlini 6148
./run_extra.sh mnist c relu carlini 6148
./run_extra.sh mnist a standard carlini 2465
./run_extra.sh mnist a adversarial carlini 2465
./run_extra.sh mnist a relu carlini 2465
./run_extra.sh mnist b standard carlini 2465
./run_extra.sh mnist b adversarial carlini 2465
./run_extra.sh mnist b relu carlini 2465
./run_extra.sh mnist c standard carlini 2465
./run_extra.sh mnist c adversarial carlini 2465
./run_extra.sh mnist c relu carlini 2465
./run_extra.sh mnist a standard carlini 9359
./run_extra.sh mnist a adversarial carlini 9359
./run_extra.sh mnist a relu carlini 9359
./run_extra.sh mnist b standard carlini 9359
./run_extra.sh mnist b adversarial carlini 9359
./run_extra.sh mnist b relu carlini 9359
./run_extra.sh mnist c standard carlini 9359
./run_extra.sh mnist c adversarial carlini 9359
./run_extra.sh mnist c relu carlini 9359
./run_extra.sh mnist a standard carlini 9098
./run_extra.sh mnist a adversarial carlini 9098
./run_extra.sh mnist a relu carlini 9098
./run_extra.sh mnist b standard carlini 9098
./run_extra.sh mnist b adversarial carlini 9098
./run_extra.sh mnist b relu carlini 9098
./run_extra.sh mnist c standard carlini 9098
./run_extra.sh mnist c adversarial carlini 9098
./run_extra.sh mnist c relu carlini 9098
./run_extra.sh mnist a standard carlini 2004
./run_extra.sh mnist a adversarial carlini 2004
./run_extra.sh mnist a relu carlini 2004
./run_extra.sh mnist b standard carlini 2004
./run_extra.sh mnist b adversarial carlini 2004
./run_extra.sh mnist b relu carlini 2004
./run_extra.sh mnist c standard carlini 2004
./run_extra.sh mnist c adversarial carlini 2004
./run_extra.sh mnist c relu carlini 2004
./run_extra.sh mnist a standard carlini 7616
./run_extra.sh mnist a adversarial carlini 7616
./run_extra.sh mnist a relu carlini 7616
./run_extra.sh mnist b standard carlini 7616
./run_extra.sh mnist b adversarial carlini 7616
./run_extra.sh mnist b relu carlini 7616
./run_extra.sh mnist c standard carlini 7616
./run_extra.sh mnist c adversarial carlini 7616
./run_extra.sh mnist c relu carlini 7616
./run_extra.sh mnist a standard carlini 5823
./run_extra.sh mnist a adversarial carlini 5823
./run_extra.sh mnist a relu carlini 5823
./run_extra.sh mnist b standard carlini 5823
./run_extra.sh mnist b adversarial carlini 5823
./run_extra.sh mnist b relu carlini 5823
./run_extra.sh mnist c standard carlini 5823
./run_extra.sh mnist c adversarial carlini 5823
./run_extra.sh mnist c relu carlini 5823
./run_extra.sh mnist a standard carlini 6812
./run_extra.sh mnist a adversarial carlini 6812
./run_extra.sh mnist a relu carlini 6812
./run_extra.sh mnist b standard carlini 6812
./run_extra.sh mnist b adversarial carlini 6812
./run_extra.sh mnist b relu carlini 6812
./run_extra.sh mnist c standard carlini 6812
./run_extra.sh mnist c adversarial carlini 6812
./run_extra.sh mnist c relu carlini 6812
./run_extra.sh mnist a standard carlini 3021
./run_extra.sh mnist a adversarial carlini 3021
./run_extra.sh mnist a relu carlini 3021
./run_extra.sh mnist b standard carlini 3021
./run_extra.sh mnist b adversarial carlini 3021
./run_extra.sh mnist b relu carlini 3021
./run_extra.sh mnist c standard carlini 3021
./run_extra.sh mnist c adversarial carlini 3021
./run_extra.sh mnist c relu carlini 3021
./run_extra.sh mnist a standard carlini 974
./run_extra.sh mnist a adversarial carlini 974
./run_extra.sh mnist a relu carlini 974
./run_extra.sh mnist b standard carlini 974
./run_extra.sh mnist b adversarial carlini 974
./run_extra.sh mnist b relu carlini 974
./run_extra.sh mnist c standard carlini 974
./run_extra.sh mnist c adversarial carlini 974
./run_extra.sh mnist c relu carlini 974
./run_extra.sh mnist a standard carlini 6969
./run_extra.sh mnist a adversarial carlini 6969
./run_extra.sh mnist a relu carlini 6969
./run_extra.sh mnist b standard carlini 6969
./run_extra.sh mnist b adversarial carlini 6969
./run_extra.sh mnist b relu carlini 6969
./run_extra.sh mnist c standard carlini 6969
./run_extra.sh mnist c adversarial carlini 6969
./run_extra.sh mnist c relu carlini 6969
./run_extra.sh mnist a standard carlini 3766
./run_extra.sh mnist a adversarial carlini 3766
./run_extra.sh mnist a relu carlini 3766
./run_extra.sh mnist b standard carlini 3766
./run_extra.sh mnist b adversarial carlini 3766
./run_extra.sh mnist b relu carlini 3766
./run_extra.sh mnist c standard carlini 3766
./run_extra.sh mnist c adversarial carlini 3766
./run_extra.sh mnist c relu carlini 3766
./run_extra.sh mnist a standard carlini 616
./run_extra.sh mnist a adversarial carlini 616
./run_extra.sh mnist a relu carlini 616
./run_extra.sh mnist b standard carlini 616
./run_extra.sh mnist b adversarial carlini 616
./run_extra.sh mnist b relu carlini 616
./run_extra.sh mnist c standard carlini 616
./run_extra.sh mnist c adversarial carlini 616
./run_extra.sh mnist c relu carlini 616
./run_extra.sh mnist a standard carlini 8034
./run_extra.sh mnist a adversarial carlini 8034
./run_extra.sh mnist a relu carlini 8034
./run_extra.sh mnist b standard carlini 8034
./run_extra.sh mnist b adversarial carlini 8034
./run_extra.sh mnist b relu carlini 8034
./run_extra.sh mnist c standard carlini 8034
./run_extra.sh mnist c adversarial carlini 8034
./run_extra.sh mnist c relu carlini 8034
./run_extra.sh mnist a standard carlini 4503
./run_extra.sh mnist a adversarial carlini 4503
./run_extra.sh mnist a relu carlini 4503
./run_extra.sh mnist b standard carlini 4503
./run_extra.sh mnist b adversarial carlini 4503
./run_extra.sh mnist b relu carlini 4503
./run_extra.sh mnist c standard carlini 4503
./run_extra.sh mnist c adversarial carlini 4503
./run_extra.sh mnist c relu carlini 4503
./run_extra.sh mnist a standard carlini 6693
./run_extra.sh mnist a adversarial carlini 6693
./run_extra.sh mnist a relu carlini 6693
./run_extra.sh mnist b standard carlini 6693
./run_extra.sh mnist b adversarial carlini 6693
./run_extra.sh mnist b relu carlini 6693
./run_extra.sh mnist c standard carlini 6693
./run_extra.sh mnist c adversarial carlini 6693
./run_extra.sh mnist c relu carlini 6693
./run_extra.sh mnist a standard carlini 7268
./run_extra.sh mnist a adversarial carlini 7268
./run_extra.sh mnist a relu carlini 7268
./run_extra.sh mnist b standard carlini 7268
./run_extra.sh mnist b adversarial carlini 7268
./run_extra.sh mnist b relu carlini 7268
./run_extra.sh mnist c standard carlini 7268
./run_extra.sh mnist c adversarial carlini 7268
./run_extra.sh mnist c relu carlini 7268
./run_extra.sh mnist a standard carlini 3981
./run_extra.sh mnist a adversarial carlini 3981
./run_extra.sh mnist a relu carlini 3981
./run_extra.sh mnist b standard carlini 3981
./run_extra.sh mnist b adversarial carlini 3981
./run_extra.sh mnist b relu carlini 3981
./run_extra.sh mnist c standard carlini 3981
./run_extra.sh mnist c adversarial carlini 3981
./run_extra.sh mnist c relu carlini 3981
./run_extra.sh mnist a standard carlini 3353
./run_extra.sh mnist a adversarial carlini 3353
./run_extra.sh mnist a relu carlini 3353
./run_extra.sh mnist b standard carlini 3353
./run_extra.sh mnist b adversarial carlini 3353
./run_extra.sh mnist b relu carlini 3353
./run_extra.sh mnist c standard carlini 3353
./run_extra.sh mnist c adversarial carlini 3353
./run_extra.sh mnist c relu carlini 3353
./run_extra.sh mnist a standard carlini 8317
./run_extra.sh mnist a adversarial carlini 8317
./run_extra.sh mnist a relu carlini 8317
./run_extra.sh mnist b standard carlini 8317
./run_extra.sh mnist b adversarial carlini 8317
./run_extra.sh mnist b relu carlini 8317
./run_extra.sh mnist c standard carlini 8317
./run_extra.sh mnist c adversarial carlini 8317
./run_extra.sh mnist c relu carlini 8317
./run_extra.sh mnist a standard carlini 1728
./run_extra.sh mnist a adversarial carlini 1728
./run_extra.sh mnist a relu carlini 1728
./run_extra.sh mnist b standard carlini 1728
./run_extra.sh mnist b adversarial carlini 1728
./run_extra.sh mnist b relu carlini 1728
./run_extra.sh mnist c standard carlini 1728
./run_extra.sh mnist c adversarial carlini 1728
./run_extra.sh mnist c relu carlini 1728
./run_extra.sh mnist a standard carlini 1597
./run_extra.sh mnist a adversarial carlini 1597
./run_extra.sh mnist a relu carlini 1597
./run_extra.sh mnist b standard carlini 1597
./run_extra.sh mnist b adversarial carlini 1597
./run_extra.sh mnist b relu carlini 1597
./run_extra.sh mnist c standard carlini 1597
./run_extra.sh mnist c adversarial carlini 1597
./run_extra.sh mnist c relu carlini 1597
./run_extra.sh mnist a standard carlini 6582
./run_extra.sh mnist a adversarial carlini 6582
./run_extra.sh mnist a relu carlini 6582
./run_extra.sh mnist b standard carlini 6582
./run_extra.sh mnist b adversarial carlini 6582
./run_extra.sh mnist b relu carlini 6582
./run_extra.sh mnist c standard carlini 6582
./run_extra.sh mnist c adversarial carlini 6582
./run_extra.sh mnist c relu carlini 6582
./run_extra.sh mnist a standard carlini 6853
./run_extra.sh mnist a adversarial carlini 6853
./run_extra.sh mnist a relu carlini 6853
./run_extra.sh mnist b standard carlini 6853
./run_extra.sh mnist b adversarial carlini 6853
./run_extra.sh mnist b relu carlini 6853
./run_extra.sh mnist c standard carlini 6853
./run_extra.sh mnist c adversarial carlini 6853
./run_extra.sh mnist c relu carlini 6853
./run_extra.sh mnist a standard carlini 2538
./run_extra.sh mnist a adversarial carlini 2538
./run_extra.sh mnist a relu carlini 2538
./run_extra.sh mnist b standard carlini 2538
./run_extra.sh mnist b adversarial carlini 2538
./run_extra.sh mnist b relu carlini 2538
./run_extra.sh mnist c standard carlini 2538
./run_extra.sh mnist c adversarial carlini 2538
./run_extra.sh mnist c relu carlini 2538
./run_extra.sh mnist a standard carlini 7526
./run_extra.sh mnist a adversarial carlini 7526
./run_extra.sh mnist a relu carlini 7526
./run_extra.sh mnist b standard carlini 7526
./run_extra.sh mnist b adversarial carlini 7526
./run_extra.sh mnist b relu carlini 7526
./run_extra.sh mnist c standard carlini 7526
./run_extra.sh mnist c adversarial carlini 7526
./run_extra.sh mnist c relu carlini 7526
./run_extra.sh mnist a standard carlini 1894
./run_extra.sh mnist a adversarial carlini 1894
./run_extra.sh mnist a relu carlini 1894
./run_extra.sh mnist b standard carlini 1894
./run_extra.sh mnist b adversarial carlini 1894
./run_extra.sh mnist b relu carlini 1894
./run_extra.sh mnist c standard carlini 1894
./run_extra.sh mnist c adversarial carlini 1894
./run_extra.sh mnist c relu carlini 1894
./run_extra.sh mnist a standard carlini 3361
./run_extra.sh mnist a adversarial carlini 3361
./run_extra.sh mnist a relu carlini 3361
./run_extra.sh mnist b standard carlini 3361
./run_extra.sh mnist b adversarial carlini 3361
./run_extra.sh mnist b relu carlini 3361
./run_extra.sh mnist c standard carlini 3361
./run_extra.sh mnist c adversarial carlini 3361
./run_extra.sh mnist c relu carlini 3361
./run_extra.sh mnist a standard carlini 2306
./run_extra.sh mnist a adversarial carlini 2306
./run_extra.sh mnist a relu carlini 2306
./run_extra.sh mnist b standard carlini 2306
./run_extra.sh mnist b adversarial carlini 2306
./run_extra.sh mnist b relu carlini 2306
./run_extra.sh mnist c standard carlini 2306
./run_extra.sh mnist c adversarial carlini 2306
./run_extra.sh mnist c relu carlini 2306
./run_extra.sh mnist a standard carlini 6028
./run_extra.sh mnist a adversarial carlini 6028
./run_extra.sh mnist a relu carlini 6028
./run_extra.sh mnist b standard carlini 6028
./run_extra.sh mnist b adversarial carlini 6028
./run_extra.sh mnist b relu carlini 6028
./run_extra.sh mnist c standard carlini 6028
./run_extra.sh mnist c adversarial carlini 6028
./run_extra.sh mnist c relu carlini 6028
./run_extra.sh mnist a standard carlini 539
./run_extra.sh mnist a adversarial carlini 539
./run_extra.sh mnist a relu carlini 539
./run_extra.sh mnist b standard carlini 539
./run_extra.sh mnist b adversarial carlini 539
./run_extra.sh mnist b relu carlini 539
./run_extra.sh mnist c standard carlini 539
./run_extra.sh mnist c adversarial carlini 539
./run_extra.sh mnist c relu carlini 539
./run_extra.sh mnist a standard carlini 6488
./run_extra.sh mnist a adversarial carlini 6488
./run_extra.sh mnist a relu carlini 6488
./run_extra.sh mnist b standard carlini 6488
./run_extra.sh mnist b adversarial carlini 6488
./run_extra.sh mnist b relu carlini 6488
./run_extra.sh mnist c standard carlini 6488
./run_extra.sh mnist c adversarial carlini 6488
./run_extra.sh mnist c relu carlini 6488
./run_extra.sh mnist a standard carlini 4635
./run_extra.sh mnist a adversarial carlini 4635
./run_extra.sh mnist a relu carlini 4635
./run_extra.sh mnist b standard carlini 4635
./run_extra.sh mnist b adversarial carlini 4635
./run_extra.sh mnist b relu carlini 4635
./run_extra.sh mnist c standard carlini 4635
./run_extra.sh mnist c adversarial carlini 4635
./run_extra.sh mnist c relu carlini 4635
./run_extra.sh mnist a standard carlini 9223
./run_extra.sh mnist a adversarial carlini 9223
./run_extra.sh mnist a relu carlini 9223
./run_extra.sh mnist b standard carlini 9223
./run_extra.sh mnist b adversarial carlini 9223
./run_extra.sh mnist b relu carlini 9223
./run_extra.sh mnist c standard carlini 9223
./run_extra.sh mnist c adversarial carlini 9223
./run_extra.sh mnist c relu carlini 9223
./run_extra.sh mnist a standard carlini 6808
./run_extra.sh mnist a adversarial carlini 6808
./run_extra.sh mnist a relu carlini 6808
./run_extra.sh mnist b standard carlini 6808
./run_extra.sh mnist b adversarial carlini 6808
./run_extra.sh mnist b relu carlini 6808
./run_extra.sh mnist c standard carlini 6808
./run_extra.sh mnist c adversarial carlini 6808
./run_extra.sh mnist c relu carlini 6808
./run_extra.sh mnist a standard carlini 8260
./run_extra.sh mnist a adversarial carlini 8260
./run_extra.sh mnist a relu carlini 8260
./run_extra.sh mnist b standard carlini 8260
./run_extra.sh mnist b adversarial carlini 8260
./run_extra.sh mnist b relu carlini 8260
./run_extra.sh mnist c standard carlini 8260
./run_extra.sh mnist c adversarial carlini 8260
./run_extra.sh mnist c relu carlini 8260
./run_extra.sh mnist a standard carlini 2206
./run_extra.sh mnist a adversarial carlini 2206
./run_extra.sh mnist a relu carlini 2206
./run_extra.sh mnist b standard carlini 2206
./run_extra.sh mnist b adversarial carlini 2206
./run_extra.sh mnist b relu carlini 2206
./run_extra.sh mnist c standard carlini 2206
./run_extra.sh mnist c adversarial carlini 2206
./run_extra.sh mnist c relu carlini 2206
./run_extra.sh mnist a standard carlini 8121
./run_extra.sh mnist a adversarial carlini 8121
./run_extra.sh mnist a relu carlini 8121
./run_extra.sh mnist b standard carlini 8121
./run_extra.sh mnist b adversarial carlini 8121
./run_extra.sh mnist b relu carlini 8121
./run_extra.sh mnist c standard carlini 8121
./run_extra.sh mnist c adversarial carlini 8121
./run_extra.sh mnist c relu carlini 8121
./run_extra.sh mnist a standard carlini 2337
./run_extra.sh mnist a adversarial carlini 2337
./run_extra.sh mnist a relu carlini 2337
./run_extra.sh mnist b standard carlini 2337
./run_extra.sh mnist b adversarial carlini 2337
./run_extra.sh mnist b relu carlini 2337
./run_extra.sh mnist c standard carlini 2337
./run_extra.sh mnist c adversarial carlini 2337
./run_extra.sh mnist c relu carlini 2337
./run_extra.sh mnist a standard carlini 1613
./run_extra.sh mnist a adversarial carlini 1613
./run_extra.sh mnist a relu carlini 1613
./run_extra.sh mnist b standard carlini 1613
./run_extra.sh mnist b adversarial carlini 1613
./run_extra.sh mnist b relu carlini 1613
./run_extra.sh mnist c standard carlini 1613
./run_extra.sh mnist c adversarial carlini 1613
./run_extra.sh mnist c relu carlini 1613
./run_extra.sh mnist a standard carlini 6982
./run_extra.sh mnist a adversarial carlini 6982
./run_extra.sh mnist a relu carlini 6982
./run_extra.sh mnist b standard carlini 6982
./run_extra.sh mnist b adversarial carlini 6982
./run_extra.sh mnist b relu carlini 6982
./run_extra.sh mnist c standard carlini 6982
./run_extra.sh mnist c adversarial carlini 6982
./run_extra.sh mnist c relu carlini 6982
./run_extra.sh mnist a standard carlini 5963
./run_extra.sh mnist a adversarial carlini 5963
./run_extra.sh mnist a relu carlini 5963
./run_extra.sh mnist b standard carlini 5963
./run_extra.sh mnist b adversarial carlini 5963
./run_extra.sh mnist b relu carlini 5963
./run_extra.sh mnist c standard carlini 5963
./run_extra.sh mnist c adversarial carlini 5963
./run_extra.sh mnist c relu carlini 5963
./run_extra.sh mnist a standard carlini 6342
./run_extra.sh mnist a adversarial carlini 6342
./run_extra.sh mnist a relu carlini 6342
./run_extra.sh mnist b standard carlini 6342
./run_extra.sh mnist b adversarial carlini 6342
./run_extra.sh mnist b relu carlini 6342
./run_extra.sh mnist c standard carlini 6342
