./run_extra.sh mnist b relu carlini 8366
./run_extra.sh mnist c standard carlini 8366
./run_extra.sh mnist c adversarial carlini 8366
./run_extra.sh mnist c relu carlini 8366
./run_extra.sh mnist a standard carlini 5931
./run_extra.sh mnist a adversarial carlini 5931
./run_extra.sh mnist a relu carlini 5931
./run_extra.sh mnist b standard carlini 5931
./run_extra.sh mnist b adversarial carlini 5931
./run_extra.sh mnist b relu carlini 5931
./run_extra.sh mnist c standard carlini 5931
./run_extra.sh mnist c adversarial carlini 5931
./run_extra.sh mnist c relu carlini 5931
./run_extra.sh mnist a standard carlini 1075
./run_extra.sh mnist a adversarial carlini 1075
./run_extra.sh mnist a relu carlini 1075
./run_extra.sh mnist b standard carlini 1075
./run_extra.sh mnist b adversarial carlini 1075
./run_extra.sh mnist b relu carlini 1075
./run_extra.sh mnist c standard carlini 1075
./run_extra.sh mnist c adversarial carlini 1075
./run_extra.sh mnist c relu carlini 1075
./run_extra.sh mnist a standard carlini 7069
./run_extra.sh mnist a adversarial carlini 7069
./run_extra.sh mnist a relu carlini 7069
./run_extra.sh mnist b standard carlini 7069
./run_extra.sh mnist b adversarial carlini 7069
./run_extra.sh mnist b relu carlini 7069
./run_extra.sh mnist c standard carlini 7069
./run_extra.sh mnist c adversarial carlini 7069
./run_extra.sh mnist c relu carlini 7069
./run_extra.sh mnist a standard carlini 1958
./run_extra.sh mnist a adversarial carlini 1958
./run_extra.sh mnist a relu carlini 1958
./run_extra.sh mnist b standard carlini 1958
./run_extra.sh mnist b adversarial carlini 1958
./run_extra.sh mnist b relu carlini 1958
./run_extra.sh mnist c standard carlini 1958
./run_extra.sh mnist c adversarial carlini 1958
./run_extra.sh mnist c relu carlini 1958
./run_extra.sh mnist a standard carlini 6829
./run_extra.sh mnist a adversarial carlini 6829
./run_extra.sh mnist a relu carlini 6829
./run_extra.sh mnist b standard carlini 6829
./run_extra.sh mnist b adversarial carlini 6829
./run_extra.sh mnist b relu carlini 6829
./run_extra.sh mnist c standard carlini 6829
./run_extra.sh mnist c adversarial carlini 6829
./run_extra.sh mnist c relu carlini 6829
./run_extra.sh mnist a standard carlini 1289
./run_extra.sh mnist a adversarial carlini 1289
./run_extra.sh mnist a relu carlini 1289
./run_extra.sh mnist b standard carlini 1289
./run_extra.sh mnist b adversarial carlini 1289
./run_extra.sh mnist b relu carlini 1289
./run_extra.sh mnist c standard carlini 1289
./run_extra.sh mnist c adversarial carlini 1289
./run_extra.sh mnist c relu carlini 1289
./run_extra.sh mnist a standard carlini 2042
./run_extra.sh mnist a adversarial carlini 2042
./run_extra.sh mnist a relu carlini 2042
./run_extra.sh mnist b standard carlini 2042
./run_extra.sh mnist b adversarial carlini 2042
./run_extra.sh mnist b relu carlini 2042
./run_extra.sh mnist c standard carlini 2042
./run_extra.sh mnist c adversarial carlini 2042
./run_extra.sh mnist c relu carlini 2042
./run_extra.sh mnist a standard carlini 444
./run_extra.sh mnist a adversarial carlini 444
./run_extra.sh mnist a relu carlini 444
./run_extra.sh mnist b standard carlini 444
./run_extra.sh mnist b adversarial carlini 444
./run_extra.sh mnist b relu carlini 444
./run_extra.sh mnist c standard carlini 444
./run_extra.sh mnist c adversarial carlini 444
./run_extra.sh mnist c relu carlini 444
./run_extra.sh mnist a standard carlini 1142
./run_extra.sh mnist a adversarial carlini 1142
./run_extra.sh mnist a relu carlini 1142
./run_extra.sh mnist b standard carlini 1142
./run_extra.sh mnist b adversarial carlini 1142
./run_extra.sh mnist b relu carlini 1142
./run_extra.sh mnist c standard carlini 1142
./run_extra.sh mnist c adversarial carlini 1142
./run_extra.sh mnist c relu carlini 1142
./run_extra.sh mnist a standard carlini 3253
./run_extra.sh mnist a adversarial carlini 3253
./run_extra.sh mnist a relu carlini 3253
./run_extra.sh mnist b standard carlini 3253
./run_extra.sh mnist b adversarial carlini 3253
./run_extra.sh mnist b relu carlini 3253
./run_extra.sh mnist c standard carlini 3253
./run_extra.sh mnist c adversarial carlini 3253
./run_extra.sh mnist c relu carlini 3253
./run_extra.sh mnist a standard carlini 277
./run_extra.sh mnist a adversarial carlini 277
./run_extra.sh mnist a relu carlini 277
./run_extra.sh mnist b standard carlini 277
./run_extra.sh mnist b adversarial carlini 277
./run_extra.sh mnist b relu carlini 277
./run_extra.sh mnist c standard carlini 277
./run_extra.sh mnist c adversarial carlini 277
./run_extra.sh mnist c relu carlini 277
./run_extra.sh mnist a standard carlini 3588
./run_extra.sh mnist a adversarial carlini 3588
./run_extra.sh mnist a relu carlini 3588
./run_extra.sh mnist b standard carlini 3588
./run_extra.sh mnist b adversarial carlini 3588
./run_extra.sh mnist b relu carlini 3588
./run_extra.sh mnist c standard carlini 3588
./run_extra.sh mnist c adversarial carlini 3588
./run_extra.sh mnist c relu carlini 3588
./run_extra.sh mnist a standard carlini 6477
./run_extra.sh mnist a adversarial carlini 6477
./run_extra.sh mnist a relu carlini 6477
./run_extra.sh mnist b standard carlini 6477
./run_extra.sh mnist b adversarial carlini 6477
./run_extra.sh mnist b relu carlini 6477
./run_extra.sh mnist c standard carlini 6477
./run_extra.sh mnist c adversarial carlini 6477
./run_extra.sh mnist c relu carlini 6477
./run_extra.sh mnist a standard carlini 6152
./run_extra.sh mnist a adversarial carlini 6152
./run_extra.sh mnist a relu carlini 6152
./run_extra.sh mnist b standard carlini 6152
./run_extra.sh mnist b adversarial carlini 6152
./run_extra.sh mnist b relu carlini 6152
./run_extra.sh mnist c standard carlini 6152
./run_extra.sh mnist c adversarial carlini 6152
./run_extra.sh mnist c relu carlini 6152
./run_extra.sh mnist a standard carlini 887
./run_extra.sh mnist a adversarial carlini 887
./run_extra.sh mnist a relu carlini 887
./run_extra.sh mnist b standard carlini 887
./run_extra.sh mnist b adversarial carlini 887
./run_extra.sh mnist b relu carlini 887
./run_extra.sh mnist c standard carlini 887
./run_extra.sh mnist c adversarial carlini 887
./run_extra.sh mnist c relu carlini 887
./run_extra.sh mnist a standard carlini 5438
./run_extra.sh mnist a adversarial carlini 5438
./run_extra.sh mnist a relu carlini 5438
./run_extra.sh mnist b standard carlini 5438
./run_extra.sh mnist b adversarial carlini 5438
./run_extra.sh mnist b relu carlini 5438
./run_extra.sh mnist c standard carlini 5438
./run_extra.sh mnist c adversarial carlini 5438
./run_extra.sh mnist c relu carlini 5438
./run_extra.sh mnist a standard carlini 3934
./run_extra.sh mnist a adversarial carlini 3934
./run_extra.sh mnist a relu carlini 3934
./run_extra.sh mnist b standard carlini 3934
./run_extra.sh mnist b adversarial carlini 3934
./run_extra.sh mnist b relu carlini 3934
./run_extra.sh mnist c standard carlini 3934
./run_extra.sh mnist c adversarial carlini 3934
./run_extra.sh mnist c relu carlini 3934
./run_extra.sh mnist a standard carlini 8718
./run_extra.sh mnist a adversarial carlini 8718
./run_extra.sh mnist a relu carlini 8718
./run_extra.sh mnist b standard carlini 8718
./run_extra.sh mnist b adversarial carlini 8718
./run_extra.sh mnist b relu carlini 8718
./run_extra.sh mnist c standard carlini 8718
./run_extra.sh mnist c adversarial carlini 8718
./run_extra.sh mnist c relu carlini 8718
./run_extra.sh mnist a standard carlini 8664
./run_extra.sh mnist a adversarial carlini 8664
./run_extra.sh mnist a relu carlini 8664
./run_extra.sh mnist b standard carlini 8664
./run_extra.sh mnist b adversarial carlini 8664
./run_extra.sh mnist b relu carlini 8664
./run_extra.sh mnist c standard carlini 8664
./run_extra.sh mnist c adversarial carlini 8664
./run_extra.sh mnist c relu carlini 8664
./run_extra.sh mnist a standard carlini 5746
./run_extra.sh mnist a adversarial carlini 5746
./run_extra.sh mnist a relu carlini 5746
./run_extra.sh mnist b standard carlini 5746
./run_extra.sh mnist b adversarial carlini 5746
./run_extra.sh mnist b relu carlini 5746
./run_extra.sh mnist c standard carlini 5746
./run_extra.sh mnist c adversarial carlini 5746
./run_extra.sh mnist c relu carlini 5746
./run_extra.sh mnist a standard carlini 9447
./run_extra.sh mnist a adversarial carlini 9447
./run_extra.sh mnist a relu carlini 9447
./run_extra.sh mnist b standard carlini 9447
./run_extra.sh mnist b adversarial carlini 9447
./run_extra.sh mnist b relu carlini 9447
./run_extra.sh mnist c standard carlini 9447
./run_extra.sh mnist c adversarial carlini 9447
./run_extra.sh mnist c relu carlini 9447
./run_extra.sh mnist a standard carlini 479
./run_extra.sh mnist a adversarial carlini 479
./run_extra.sh mnist a relu carlini 479
./run_extra.sh mnist b standard carlini 479
./run_extra.sh mnist b adversarial carlini 479
./run_extra.sh mnist b relu carlini 479
./run_extra.sh mnist c standard carlini 479
./run_extra.sh mnist c adversarial carlini 479
./run_extra.sh mnist c relu carlini 479
./run_extra.sh mnist a standard carlini 7310
./run_extra.sh mnist a adversarial carlini 7310
./run_extra.sh mnist a relu carlini 7310
./run_extra.sh mnist b standard carlini 7310
./run_extra.sh mnist b adversarial carlini 7310
./run_extra.sh mnist b relu carlini 7310
./run_extra.sh mnist c standard carlini 7310
./run_extra.sh mnist c adversarial carlini 7310
./run_extra.sh mnist c relu carlini 7310
./run_extra.sh mnist a standard carlini 1832
./run_extra.sh mnist a adversarial carlini 1832
./run_extra.sh mnist a relu carlini 1832
./run_extra.sh mnist b standard carlini 1832
./run_extra.sh mnist b adversarial carlini 1832
./run_extra.sh mnist b relu carlini 1832
./run_extra.sh mnist c standard carlini 1832
./run_extra.sh mnist c adversarial carlini 1832
./run_extra.sh mnist c relu carlini 1832
./run_extra.sh mnist a standard carlini 5724
./run_extra.sh mnist a adversarial carlini 5724
./run_extra.sh mnist a relu carlini 5724
./run_extra.sh mnist b standard carlini 5724
./run_extra.sh mnist b adversarial carlini 5724
./run_extra.sh mnist b relu carlini 5724
./run_extra.sh mnist c standard carlini 5724
./run_extra.sh mnist c adversarial carlini 5724
./run_extra.sh mnist c relu carlini 5724
./run_extra.sh mnist a standard carlini 3386
./run_extra.sh mnist a adversarial carlini 3386
./run_extra.sh mnist a relu carlini 3386
./run_extra.sh mnist b standard carlini 3386
./run_extra.sh mnist b adversarial carlini 3386
./run_extra.sh mnist b relu carlini 3386
./run_extra.sh mnist c standard carlini 3386
./run_extra.sh mnist c adversarial carlini 3386
./run_extra.sh mnist c relu carlini 3386
./run_extra.sh mnist a standard carlini 3274
./run_extra.sh mnist a adversarial carlini 3274
./run_extra.sh mnist a relu carlini 3274
./run_extra.sh mnist b standard carlini 3274
./run_extra.sh mnist b adversarial carlini 3274
./run_extra.sh mnist b relu carlini 3274
./run_extra.sh mnist c standard carlini 3274
./run_extra.sh mnist c adversarial carlini 3274
./run_extra.sh mnist c relu carlini 3274
./run_extra.sh mnist a standard carlini 3599
./run_extra.sh mnist a adversarial carlini 3599
./run_extra.sh mnist a relu carlini 3599
./run_extra.sh mnist b standard carlini 3599
./run_extra.sh mnist b adversarial carlini 3599
./run_extra.sh mnist b relu carlini 3599
./run_extra.sh mnist c standard carlini 3599
./run_extra.sh mnist c adversarial carlini 3599
./run_extra.sh mnist c relu carlini 3599
./run_extra.sh mnist a standard carlini 6056
./run_extra.sh mnist a adversarial carlini 6056
./run_extra.sh mnist a relu carlini 6056
./run_extra.sh mnist b standard carlini 6056
./run_extra.sh mnist b adversarial carlini 6056
./run_extra.sh mnist b relu carlini 6056
./run_extra.sh mnist c standard carlini 6056
./run_extra.sh mnist c adversarial carlini 6056
./run_extra.sh mnist c relu carlini 6056
./run_extra.sh mnist a standard carlini 6851
./run_extra.sh mnist a adversarial carlini 6851
./run_extra.sh mnist a relu carlini 6851
./run_extra.sh mnist b standard carlini 6851
./run_extra.sh mnist b adversarial carlini 6851
./run_extra.sh mnist b relu carlini 6851
./run_extra.sh mnist c standard carlini 6851
./run_extra.sh mnist c adversarial carlini 6851
./run_extra.sh mnist c relu carlini 6851
./run_extra.sh mnist a standard carlini 5596
./run_extra.sh mnist a adversarial carlini 5596
./run_extra.sh mnist a relu carlini 5596
./run_extra.sh mnist b standard carlini 5596
./run_extra.sh mnist b adversarial carlini 5596
./run_extra.sh mnist b relu carlini 5596
./run_extra.sh mnist c standard carlini 5596
./run_extra.sh mnist c adversarial carlini 5596
./run_extra.sh mnist c relu carlini 5596
./run_extra.sh mnist a standard carlini 9302
./run_extra.sh mnist a adversarial carlini 9302
./run_extra.sh mnist a relu carlini 9302
./run_extra.sh mnist b standard carlini 9302
./run_extra.sh mnist b adversarial carlini 9302
./run_extra.sh mnist b relu carlini 9302
./run_extra.sh mnist c standard carlini 9302
./run_extra.sh mnist c adversarial carlini 9302
./run_extra.sh mnist c relu carlini 9302
./run_extra.sh mnist a standard carlini 1567
./run_extra.sh mnist a adversarial carlini 1567
./run_extra.sh mnist a relu carlini 1567
./run_extra.sh mnist b standard carlini 1567
./run_extra.sh mnist b adversarial carlini 1567
./run_extra.sh mnist b relu carlini 1567
./run_extra.sh mnist c standard carlini 1567
./run_extra.sh mnist c adversarial carlini 1567
./run_extra.sh mnist c relu carlini 1567
./run_extra.sh mnist a standard carlini 9009
./run_extra.sh mnist a adversarial carlini 9009
./run_extra.sh mnist a relu carlini 9009
./run_extra.sh mnist b standard carlini 9009
./run_extra.sh mnist b adversarial carlini 9009
./run_extra.sh mnist b relu carlini 9009
./run_extra.sh mnist c standard carlini 9009
./run_extra.sh mnist c adversarial carlini 9009
./run_extra.sh mnist c relu carlini 9009
./run_extra.sh mnist a standard carlini 2473
./run_extra.sh mnist a adversarial carlini 2473
./run_extra.sh mnist a relu carlini 2473
./run_extra.sh mnist b standard carlini 2473
./run_extra.sh mnist b adversarial carlini 2473
./run_extra.sh mnist b relu carlini 2473
./run_extra.sh mnist c standard carlini 2473
./run_extra.sh mnist c adversarial carlini 2473
./run_extra.sh mnist c relu carlini 2473
./run_extra.sh mnist a standard carlini 9805
./run_extra.sh mnist a adversarial carlini 9805
./run_extra.sh mnist a relu carlini 9805
./run_extra.sh mnist b standard carlini 9805
./run_extra.sh mnist b adversarial carlini 9805
./run_extra.sh mnist b relu carlini 9805
./run_extra.sh mnist c standard carlini 9805
./run_extra.sh mnist c adversarial carlini 9805
./run_extra.sh mnist c relu carlini 9805
./run_extra.sh mnist a standard carlini 8657
./run_extra.sh mnist a adversarial carlini 8657
./run_extra.sh mnist a relu carlini 8657
./run_extra.sh mnist b standard carlini 8657
./run_extra.sh mnist b adversarial carlini 8657
./run_extra.sh mnist b relu carlini 8657
./run_extra.sh mnist c standard carlini 8657
./run_extra.sh mnist c adversarial carlini 8657
./run_extra.sh mnist c relu carlini 8657
./run_extra.sh mnist a standard carlini 3848
./run_extra.sh mnist a adversarial carlini 3848
./run_extra.sh mnist a relu carlini 3848
./run_extra.sh mnist b standard carlini 3848
./run_extra.sh mnist b adversarial carlini 3848
./run_extra.sh mnist b relu carlini 3848
./run_extra.sh mnist c standard carlini 3848
./run_extra.sh mnist c adversarial carlini 3848
./run_extra.sh mnist c relu carlini 3848
./run_extra.sh mnist a standard carlini 6680
./run_extra.sh mnist a adversarial carlini 6680
./run_extra.sh mnist a relu carlini 6680
./run_extra.sh mnist b standard carlini 6680
./run_extra.sh mnist b adversarial carlini 6680
./run_extra.sh mnist b relu carlini 6680
./run_extra.sh mnist c standard carlini 6680
./run_extra.sh mnist c adversarial carlini 6680
./run_extra.sh mnist c relu carlini 6680
./run_extra.sh mnist a standard carlini 3083
./run_extra.sh mnist a adversarial carlini 3083
./run_extra.sh mnist a relu carlini 3083
./run_extra.sh mnist b standard carlini 3083
./run_extra.sh mnist b adversarial carlini 3083
./run_extra.sh mnist b relu carlini 3083
./run_extra.sh mnist c standard carlini 3083
./run_extra.sh mnist c adversarial carlini 3083
./run_extra.sh mnist c relu carlini 3083
./run_extra.sh mnist a standard carlini 6419
./run_extra.sh mnist a adversarial carlini 6419
./run_extra.sh mnist a relu carlini 6419
./run_extra.sh mnist b standard carlini 6419
./run_extra.sh mnist b adversarial carlini 6419
./run_extra.sh mnist b relu carlini 6419
./run_extra.sh mnist c standard carlini 6419
./run_extra.sh mnist c adversarial carlini 6419
./run_extra.sh mnist c relu carlini 6419
./run_extra.sh mnist a standard carlini 6444
./run_extra.sh mnist a adversarial carlini 6444
./run_extra.sh mnist a relu carlini 6444
./run_extra.sh mnist b standard carlini 6444
./run_extra.sh mnist b adversarial carlini 6444
./run_extra.sh mnist b relu carlini 6444
./run_extra.sh mnist c standard carlini 6444
./run_extra.sh mnist c adversarial carlini 6444
./run_extra.sh mnist c relu carlini 6444
./run_extra.sh mnist a standard carlini 598
./run_extra.sh mnist a adversarial carlini 598
./run_extra.sh mnist a relu carlini 598
./run_extra.sh mnist b standard carlini 598
./run_extra.sh mnist b adversarial carlini 598
./run_extra.sh mnist b relu carlini 598
./run_extra.sh mnist c standard carlini 598
./run_extra.sh mnist c adversarial carlini 598
./run_extra.sh mnist c relu carlini 598
./run_extra.sh mnist a standard carlini 3103
./run_extra.sh mnist a adversarial carlini 3103
./run_extra.sh mnist a relu carlini 3103
./run_extra.sh mnist b standard carlini 3103
./run_extra.sh mnist b adversarial carlini 3103
./run_extra.sh mnist b relu carlini 3103
./run_extra.sh mnist c standard carlini 3103
./run_extra.sh mnist c adversarial carlini 3103
./run_extra.sh mnist c relu carlini 3103
./run_extra.sh mnist a standard carlini 4370
./run_extra.sh mnist a adversarial carlini 4370
./run_extra.sh mnist a relu carlini 4370
./run_extra.sh mnist b standard carlini 4370
./run_extra.sh mnist b adversarial carlini 4370
./run_extra.sh mnist b relu carlini 4370
./run_extra.sh mnist c standard carlini 4370
./run_extra.sh mnist c adversarial carlini 4370
./run_extra.sh mnist c relu carlini 4370
./run_extra.sh mnist a standard carlini 6918
./run_extra.sh mnist a adversarial carlini 6918
./run_extra.sh mnist a relu carlini 6918
./run_extra.sh mnist b standard carlini 6918
./run_extra.sh mnist b adversarial carlini 6918
./run_extra.sh mnist b relu carlini 6918
./run_extra.sh mnist c standard carlini 6918
./run_extra.sh mnist c adversarial carlini 6918
./run_extra.sh mnist c relu carlini 6918
./run_extra.sh mnist a standard carlini 7929
./run_extra.sh mnist a adversarial carlini 7929
./run_extra.sh mnist a relu carlini 7929
./run_extra.sh mnist b standard carlini 7929
./run_extra.sh mnist b adversarial carlini 7929
./run_extra.sh mnist b relu carlini 7929
./run_extra.sh mnist c standard carlini 7929
./run_extra.sh mnist c adversarial carlini 7929
./run_extra.sh mnist c relu carlini 7929
./run_extra.sh mnist a standard carlini 9924
./run_extra.sh mnist a adversarial carlini 9924
./run_extra.sh mnist a relu carlini 9924
./run_extra.sh mnist b standard carlini 9924
./run_extra.sh mnist b adversarial carlini 9924
./run_extra.sh mnist b relu carlini 9924
./run_extra.sh mnist c standard carlini 9924
./run_extra.sh mnist c adversarial carlini 9924
./run_extra.sh mnist c relu carlini 9924
./run_extra.sh mnist a standard carlini 7410
./run_extra.sh mnist a adversarial carlini 7410
./run_extra.sh mnist a relu carlini 7410
./run_extra.sh mnist b standard carlini 7410
./run_extra.sh mnist b adversarial carlini 7410
./run_extra.sh mnist b relu carlini 7410
./run_extra.sh mnist c standard carlini 7410
./run_extra.sh mnist c adversarial carlini 7410
./run_extra.sh mnist c relu carlini 7410
./run_extra.sh mnist a standard carlini 3670
./run_extra.sh mnist a adversarial carlini 3670
./run_extra.sh mnist a relu carlini 3670
./run_extra.sh mnist b standard carlini 3670
./run_extra.sh mnist b adversarial carlini 3670
./run_extra.sh mnist b relu carlini 3670
./run_extra.sh mnist c standard carlini 3670
./run_extra.sh mnist c adversarial carlini 3670
./run_extra.sh mnist c relu carlini 3670
./run_extra.sh mnist a standard carlini 2980
./run_extra.sh mnist a adversarial carlini 2980
./run_extra.sh mnist a relu carlini 2980
./run_extra.sh mnist b standard carlini 2980
./run_extra.sh mnist b adversarial carlini 2980
./run_extra.sh mnist b relu carlini 2980
./run_extra.sh mnist c standard carlini 2980
./run_extra.sh mnist c adversarial carlini 2980
./run_extra.sh mnist c relu carlini 2980
./run_extra.sh mnist a standard carlini 3585
./run_extra.sh mnist a adversarial carlini 3585
./run_extra.sh mnist a relu carlini 3585
./run_extra.sh mnist b standard carlini 3585
./run_extra.sh mnist b adversarial carlini 3585
./run_extra.sh mnist b relu carlini 3585
./run_extra.sh mnist c standard carlini 3585
./run_extra.sh mnist c adversarial carlini 3585
./run_extra.sh mnist c relu carlini 3585
./run_extra.sh mnist a standard carlini 9341
./run_extra.sh mnist a adversarial carlini 9341
./run_extra.sh mnist a relu carlini 9341
./run_extra.sh mnist b standard carlini 9341
./run_extra.sh mnist b adversarial carlini 9341
./run_extra.sh mnist b relu carlini 9341
./run_extra.sh mnist c standard carlini 9341
./run_extra.sh mnist c adversarial carlini 9341
./run_extra.sh mnist c relu carlini 9341
./run_extra.sh mnist a standard carlini 2299
./run_extra.sh mnist a adversarial carlini 2299
./run_extra.sh mnist a relu carlini 2299
./run_extra.sh mnist b standard carlini 2299
./run_extra.sh mnist b adversarial carlini 2299
./run_extra.sh mnist b relu carlini 2299
./run_extra.sh mnist c standard carlini 2299
./run_extra.sh mnist c adversarial carlini 2299
./run_extra.sh mnist c relu carlini 2299
./run_extra.sh mnist a standard carlini 2565
./run_extra.sh mnist a adversarial carlini 2565
./run_extra.sh mnist a relu carlini 2565
./run_extra.sh mnist b standard carlini 2565
./run_extra.sh mnist b adversarial carlini 2565
./run_extra.sh mnist b relu carlini 2565
./run_extra.sh mnist c standard carlini 2565
./run_extra.sh mnist c adversarial carlini 2565
./run_extra.sh mnist c relu carlini 2565
./run_extra.sh mnist a standard carlini 3785
./run_extra.sh mnist a adversarial carlini 3785
./run_extra.sh mnist a relu carlini 3785
./run_extra.sh mnist b standard carlini 3785
./run_extra.sh mnist b adversarial carlini 3785
./run_extra.sh mnist b relu carlini 3785
./run_extra.sh mnist c standard carlini 3785
./run_extra.sh mnist c adversarial carlini 3785
./run_extra.sh mnist c relu carlini 3785
./run_extra.sh mnist a standard carlini 8623
./run_extra.sh mnist a adversarial carlini 8623
./run_extra.sh mnist a relu carlini 8623
./run_extra.sh mnist b standard carlini 8623
./run_extra.sh mnist b adversarial carlini 8623
./run_extra.sh mnist b relu carlini 8623
./run_extra.sh mnist c standard carlini 8623
./run_extra.sh mnist c adversarial carlini 8623
./run_extra.sh mnist c relu carlini 8623
./run_extra.sh mnist a standard carlini 4486
./run_extra.sh mnist a adversarial carlini 4486
./run_extra.sh mnist a relu carlini 4486
./run_extra.sh mnist b standard carlini 4486
./run_extra.sh mnist b adversarial carlini 4486
./run_extra.sh mnist b relu carlini 4486
./run_extra.sh mnist c standard carlini 4486
./run_extra.sh mnist c adversarial carlini 4486
./run_extra.sh mnist c relu carlini 4486
./run_extra.sh mnist a standard carlini 858
./run_extra.sh mnist a adversarial carlini 858
./run_extra.sh mnist a relu carlini 858
./run_extra.sh mnist b standard carlini 858
./run_extra.sh mnist b adversarial carlini 858
./run_extra.sh mnist b relu carlini 858
./run_extra.sh mnist c standard carlini 858
./run_extra.sh mnist c adversarial carlini 858
./run_extra.sh mnist c relu carlini 858
./run_extra.sh mnist a standard carlini 473
./run_extra.sh mnist a adversarial carlini 473
./run_extra.sh mnist a relu carlini 473
./run_extra.sh mnist b standard carlini 473
./run_extra.sh mnist b adversarial carlini 473
./run_extra.sh mnist b relu carlini 473
./run_extra.sh mnist c standard carlini 473
./run_extra.sh mnist c adversarial carlini 473
./run_extra.sh mnist c relu carlini 473
./run_extra.sh mnist a standard carlini 1747
./run_extra.sh mnist a adversarial carlini 1747
./run_extra.sh mnist a relu carlini 1747
./run_extra.sh mnist b standard carlini 1747
./run_extra.sh mnist b adversarial carlini 1747
./run_extra.sh mnist b relu carlini 1747
./run_extra.sh mnist c standard carlini 1747
./run_extra.sh mnist c adversarial carlini 1747
./run_extra.sh mnist c relu carlini 1747
./run_extra.sh mnist a standard carlini 3956
./run_extra.sh mnist a adversarial carlini 3956
./run_extra.sh mnist a relu carlini 3956
./run_extra.sh mnist b standard carlini 3956
./run_extra.sh mnist b adversarial carlini 3956
./run_extra.sh mnist b relu carlini 3956
./run_extra.sh mnist c standard carlini 3956
./run_extra.sh mnist c adversarial carlini 3956
./run_extra.sh mnist c relu carlini 3956
./run_extra.sh mnist a standard carlini 9087
./run_extra.sh mnist a adversarial carlini 9087
./run_extra.sh mnist a relu carlini 9087
./run_extra.sh mnist b standard carlini 9087
./run_extra.sh mnist b adversarial carlini 9087
./run_extra.sh mnist b relu carlini 9087
./run_extra.sh mnist c standard carlini 9087
./run_extra.sh mnist c adversarial carlini 9087
./run_extra.sh mnist c relu carlini 9087
./run_extra.sh mnist a standard carlini 5623
./run_extra.sh mnist a adversarial carlini 5623
./run_extra.sh mnist a relu carlini 5623
./run_extra.sh mnist b standard carlini 5623
./run_extra.sh mnist b adversarial carlini 5623
./run_extra.sh mnist b relu carlini 5623
./run_extra.sh mnist c standard carlini 5623
./run_extra.sh mnist c adversarial carlini 5623
./run_extra.sh mnist c relu carlini 5623
./run_extra.sh mnist a standard carlini 9736
./run_extra.sh mnist a adversarial carlini 9736
./run_extra.sh mnist a relu carlini 9736
./run_extra.sh mnist b standard carlini 9736
./run_extra.sh mnist b adversarial carlini 9736
./run_extra.sh mnist b relu carlini 9736
./run_extra.sh mnist c standard carlini 9736
./run_extra.sh mnist c adversarial carlini 9736
./run_extra.sh mnist c relu carlini 9736
./run_extra.sh mnist a standard carlini 2692
./run_extra.sh mnist a adversarial carlini 2692
./run_extra.sh mnist a relu carlini 2692
./run_extra.sh mnist b standard carlini 2692
./run_extra.sh mnist b adversarial carlini 2692
./run_extra.sh mnist b relu carlini 2692
./run_extra.sh mnist c standard carlini 2692
./run_extra.sh mnist c adversarial carlini 2692
./run_extra.sh mnist c relu carlini 2692
./run_extra.sh mnist a standard carlini 2569
./run_extra.sh mnist a adversarial carlini 2569
./run_extra.sh mnist a relu carlini 2569
./run_extra.sh mnist b standard carlini 2569
./run_extra.sh mnist b adversarial carlini 2569
./run_extra.sh mnist b relu carlini 2569
./run_extra.sh mnist c standard carlini 2569
./run_extra.sh mnist c adversarial carlini 2569
./run_extra.sh mnist c relu carlini 2569
./run_extra.sh mnist a standard carlini 5718
./run_extra.sh mnist a adversarial carlini 5718
./run_extra.sh mnist a relu carlini 5718
./run_extra.sh mnist b standard carlini 5718
./run_extra.sh mnist b adversarial carlini 5718
./run_extra.sh mnist b relu carlini 5718
./run_extra.sh mnist c standard carlini 5718
./run_extra.sh mnist c adversarial carlini 5718
./run_extra.sh mnist c relu carlini 5718
./run_extra.sh mnist a standard carlini 7490
./run_extra.sh mnist a adversarial carlini 7490
./run_extra.sh mnist a relu carlini 7490
./run_extra.sh mnist b standard carlini 7490
./run_extra.sh mnist b adversarial carlini 7490
./run_extra.sh mnist b relu carlini 7490
./run_extra.sh mnist c standard carlini 7490
./run_extra.sh mnist c adversarial carlini 7490
./run_extra.sh mnist c relu carlini 7490
./run_extra.sh mnist a standard carlini 1612
./run_extra.sh mnist a adversarial carlini 1612
./run_extra.sh mnist a relu carlini 1612
./run_extra.sh mnist b standard carlini 1612
./run_extra.sh mnist b adversarial carlini 1612
./run_extra.sh mnist b relu carlini 1612
./run_extra.sh mnist c standard carlini 1612
./run_extra.sh mnist c adversarial carlini 1612
./run_extra.sh mnist c relu carlini 1612
./run_extra.sh mnist a standard carlini 1030
./run_extra.sh mnist a adversarial carlini 1030
./run_extra.sh mnist a relu carlini 1030
./run_extra.sh mnist b standard carlini 1030
./run_extra.sh mnist b adversarial carlini 1030
./run_extra.sh mnist b relu carlini 1030
./run_extra.sh mnist c standard carlini 1030
./run_extra.sh mnist c adversarial carlini 1030
./run_extra.sh mnist c relu carlini 1030
./run_extra.sh mnist a standard carlini 5210
./run_extra.sh mnist a adversarial carlini 5210
./run_extra.sh mnist a relu carlini 5210
./run_extra.sh mnist b standard carlini 5210
./run_extra.sh mnist b adversarial carlini 5210
./run_extra.sh mnist b relu carlini 5210
./run_extra.sh mnist c standard carlini 5210
./run_extra.sh mnist c adversarial carlini 5210
./run_extra.sh mnist c relu carlini 5210
./run_extra.sh mnist a standard carlini 9837
./run_extra.sh mnist a adversarial carlini 9837
./run_extra.sh mnist a relu carlini 9837
./run_extra.sh mnist b standard carlini 9837
./run_extra.sh mnist b adversarial carlini 9837
./run_extra.sh mnist b relu carlini 9837
./run_extra.sh mnist c standard carlini 9837
./run_extra.sh mnist c adversarial carlini 9837
./run_extra.sh mnist c relu carlini 9837
./run_extra.sh mnist a standard carlini 9582
./run_extra.sh mnist a adversarial carlini 9582
./run_extra.sh mnist a relu carlini 9582
./run_extra.sh mnist b standard carlini 9582
./run_extra.sh mnist b adversarial carlini 9582
./run_extra.sh mnist b relu carlini 9582
./run_extra.sh mnist c standard carlini 9582
./run_extra.sh mnist c adversarial carlini 9582
./run_extra.sh mnist c relu carlini 9582
./run_extra.sh mnist a standard carlini 3259
./run_extra.sh mnist a adversarial carlini 3259
./run_extra.sh mnist a relu carlini 3259
./run_extra.sh mnist b standard carlini 3259
./run_extra.sh mnist b adversarial carlini 3259
./run_extra.sh mnist b relu carlini 3259
./run_extra.sh mnist c standard carlini 3259
./run_extra.sh mnist c adversarial carlini 3259
./run_extra.sh mnist c relu carlini 3259
./run_extra.sh mnist a standard carlini 7298
./run_extra.sh mnist a adversarial carlini 7298
./run_extra.sh mnist a relu carlini 7298
./run_extra.sh mnist b standard carlini 7298
./run_extra.sh mnist b adversarial carlini 7298
./run_extra.sh mnist b relu carlini 7298
./run_extra.sh mnist c standard carlini 7298
./run_extra.sh mnist c adversarial carlini 7298
./run_extra.sh mnist c relu carlini 7298
./run_extra.sh mnist a standard carlini 3193
./run_extra.sh mnist a adversarial carlini 3193
./run_extra.sh mnist a relu carlini 3193
./run_extra.sh mnist b standard carlini 3193
./run_extra.sh mnist b adversarial carlini 3193
./run_extra.sh mnist b relu carlini 3193
./run_extra.sh mnist c standard carlini 3193
./run_extra.sh mnist c adversarial carlini 3193
./run_extra.sh mnist c relu carlini 3193
./run_extra.sh mnist a standard carlini 3317
./run_extra.sh mnist a adversarial carlini 3317
./run_extra.sh mnist a relu carlini 3317
./run_extra.sh mnist b standard carlini 3317
./run_extra.sh mnist b adversarial carlini 3317
./run_extra.sh mnist b relu carlini 3317
./run_extra.sh mnist c standard carlini 3317
./run_extra.sh mnist c adversarial carlini 3317
./run_extra.sh mnist c relu carlini 3317
./run_extra.sh mnist a standard carlini 6985
./run_extra.sh mnist a adversarial carlini 6985
./run_extra.sh mnist a relu carlini 6985
./run_extra.sh mnist b standard carlini 6985
./run_extra.sh mnist b adversarial carlini 6985
./run_extra.sh mnist b relu carlini 6985
./run_extra.sh mnist c standard carlini 6985
./run_extra.sh mnist c adversarial carlini 6985
./run_extra.sh mnist c relu carlini 6985
./run_extra.sh mnist a standard carlini 6088
./run_extra.sh mnist a adversarial carlini 6088
./run_extra.sh mnist a relu carlini 6088
./run_extra.sh mnist b standard carlini 6088
./run_extra.sh mnist b adversarial carlini 6088
./run_extra.sh mnist b relu carlini 6088
./run_extra.sh mnist c standard carlini 6088
./run_extra.sh mnist c adversarial carlini 6088
./run_extra.sh mnist c relu carlini 6088
./run_extra.sh mnist a standard carlini 4020
./run_extra.sh mnist a adversarial carlini 4020
./run_extra.sh mnist a relu carlini 4020
./run_extra.sh mnist b standard carlini 4020
./run_extra.sh mnist b adversarial carlini 4020
./run_extra.sh mnist b relu carlini 4020
./run_extra.sh mnist c standard carlini 4020
./run_extra.sh mnist c adversarial carlini 4020
./run_extra.sh mnist c relu carlini 4020
./run_extra.sh mnist a standard carlini 8882
./run_extra.sh mnist a adversarial carlini 8882
./run_extra.sh mnist a relu carlini 8882
./run_extra.sh mnist b standard carlini 8882
./run_extra.sh mnist b adversarial carlini 8882
./run_extra.sh mnist b relu carlini 8882
./run_extra.sh mnist c standard carlini 8882
./run_extra.sh mnist c adversarial carlini 8882
./run_extra.sh mnist c relu carlini 8882
./run_extra.sh mnist a standard carlini 8012
./run_extra.sh mnist a adversarial carlini 8012
./run_extra.sh mnist a relu carlini 8012
./run_extra.sh mnist b standard carlini 8012
./run_extra.sh mnist b adversarial carlini 8012
./run_extra.sh mnist b relu carlini 8012
./run_extra.sh mnist c standard carlini 8012
./run_extra.sh mnist c adversarial carlini 8012
./run_extra.sh mnist c relu carlini 8012
./run_extra.sh mnist a standard carlini 8743
./run_extra.sh mnist a adversarial carlini 8743
./run_extra.sh mnist a relu carlini 8743
./run_extra.sh mnist b standard carlini 8743
./run_extra.sh mnist b adversarial carlini 8743
./run_extra.sh mnist b relu carlini 8743
./run_extra.sh mnist c standard carlini 8743
./run_extra.sh mnist c adversarial carlini 8743
./run_extra.sh mnist c relu carlini 8743
./run_extra.sh mnist a standard carlini 440
./run_extra.sh mnist a adversarial carlini 440
./run_extra.sh mnist a relu carlini 440
./run_extra.sh mnist b standard carlini 440
./run_extra.sh mnist b adversarial carlini 440
./run_extra.sh mnist b relu carlini 440
./run_extra.sh mnist c standard carlini 440
./run_extra.sh mnist c adversarial carlini 440
./run_extra.sh mnist c relu carlini 440
./run_extra.sh mnist a standard carlini 9822
./run_extra.sh mnist a adversarial carlini 9822
./run_extra.sh mnist a relu carlini 9822
./run_extra.sh mnist b standard carlini 9822
./run_extra.sh mnist b adversarial carlini 9822
./run_extra.sh mnist b relu carlini 9822
./run_extra.sh mnist c standard carlini 9822
./run_extra.sh mnist c adversarial carlini 9822
./run_extra.sh mnist c relu carlini 9822
./run_extra.sh mnist a standard carlini 1316
./run_extra.sh mnist a adversarial carlini 1316
./run_extra.sh mnist a relu carlini 1316
./run_extra.sh mnist b standard carlini 1316
./run_extra.sh mnist b adversarial carlini 1316
./run_extra.sh mnist b relu carlini 1316
./run_extra.sh mnist c standard carlini 1316
./run_extra.sh mnist c adversarial carlini 1316
./run_extra.sh mnist c relu carlini 1316
./run_extra.sh mnist a standard carlini 6765
./run_extra.sh mnist a adversarial carlini 6765
./run_extra.sh mnist a relu carlini 6765
./run_extra.sh mnist b standard carlini 6765
./run_extra.sh mnist b adversarial carlini 6765
./run_extra.sh mnist b relu carlini 6765
./run_extra.sh mnist c standard carlini 6765
./run_extra.sh mnist c adversarial carlini 6765
./run_extra.sh mnist c relu carlini 6765
./run_extra.sh mnist a standard carlini 3326
./run_extra.sh mnist a adversarial carlini 3326
./run_extra.sh mnist a relu carlini 3326
./run_extra.sh mnist b standard carlini 3326
./run_extra.sh mnist b adversarial carlini 3326
./run_extra.sh mnist b relu carlini 3326
./run_extra.sh mnist c standard carlini 3326
./run_extra.sh mnist c adversarial carlini 3326
./run_extra.sh mnist c relu carlini 3326
./run_extra.sh mnist a standard carlini 7893
./run_extra.sh mnist a adversarial carlini 7893
./run_extra.sh mnist a relu carlini 7893
./run_extra.sh mnist b standard carlini 7893
./run_extra.sh mnist b adversarial carlini 7893
./run_extra.sh mnist b relu carlini 7893
./run_extra.sh mnist c standard carlini 7893
./run_extra.sh mnist c adversarial carlini 7893
./run_extra.sh mnist c relu carlini 7893
./run_extra.sh mnist a standard carlini 5968
./run_extra.sh mnist a adversarial carlini 5968
./run_extra.sh mnist a relu carlini 5968
./run_extra.sh mnist b standard carlini 5968
./run_extra.sh mnist b adversarial carlini 5968
./run_extra.sh mnist b relu carlini 5968
./run_extra.sh mnist c standard carlini 5968
./run_extra.sh mnist c adversarial carlini 5968
./run_extra.sh mnist c relu carlini 5968
./run_extra.sh mnist a standard carlini 2755
./run_extra.sh mnist a adversarial carlini 2755
./run_extra.sh mnist a relu carlini 2755
./run_extra.sh mnist b standard carlini 2755
./run_extra.sh mnist b adversarial carlini 2755
./run_extra.sh mnist b relu carlini 2755
./run_extra.sh mnist c standard carlini 2755
./run_extra.sh mnist c adversarial carlini 2755
./run_extra.sh mnist c relu carlini 2755
./run_extra.sh mnist a standard carlini 8710
./run_extra.sh mnist a adversarial carlini 8710
./run_extra.sh mnist a relu carlini 8710
./run_extra.sh mnist b standard carlini 8710
./run_extra.sh mnist b adversarial carlini 8710
./run_extra.sh mnist b relu carlini 8710
./run_extra.sh mnist c standard carlini 8710
./run_extra.sh mnist c adversarial carlini 8710
./run_extra.sh mnist c relu carlini 8710
./run_extra.sh mnist a standard carlini 6541
./run_extra.sh mnist a adversarial carlini 6541
./run_extra.sh mnist a relu carlini 6541
./run_extra.sh mnist b standard carlini 6541
./run_extra.sh mnist b adversarial carlini 6541
./run_extra.sh mnist b relu carlini 6541
./run_extra.sh mnist c standard carlini 6541
./run_extra.sh mnist c adversarial carlini 6541
./run_extra.sh mnist c relu carlini 6541
./run_extra.sh mnist a standard carlini 8249
./run_extra.sh mnist a adversarial carlini 8249
./run_extra.sh mnist a relu carlini 8249
./run_extra.sh mnist b standard carlini 8249
./run_extra.sh mnist b adversarial carlini 8249
./run_extra.sh mnist b relu carlini 8249
./run_extra.sh mnist c standard carlini 8249
./run_extra.sh mnist c adversarial carlini 8249
./run_extra.sh mnist c relu carlini 8249
./run_extra.sh mnist a standard carlini 6990
./run_extra.sh mnist a adversarial carlini 6990
./run_extra.sh mnist a relu carlini 6990
./run_extra.sh mnist b standard carlini 6990
./run_extra.sh mnist b adversarial carlini 6990
./run_extra.sh mnist b relu carlini 6990
./run_extra.sh mnist c standard carlini 6990
./run_extra.sh mnist c adversarial carlini 6990
./run_extra.sh mnist c relu carlini 6990
./run_extra.sh mnist a standard carlini 2174
./run_extra.sh mnist a adversarial carlini 2174
./run_extra.sh mnist a relu carlini 2174
./run_extra.sh mnist b standard carlini 2174
./run_extra.sh mnist b adversarial carlini 2174
./run_extra.sh mnist b relu carlini 2174
./run_extra.sh mnist c standard carlini 2174
./run_extra.sh mnist c adversarial carlini 2174
./run_extra.sh mnist c relu carlini 2174
./run_extra.sh mnist a standard carlini 1276
./run_extra.sh mnist a adversarial carlini 1276
./run_extra.sh mnist a relu carlini 1276
./run_extra.sh mnist b standard carlini 1276
./run_extra.sh mnist b adversarial carlini 1276
./run_extra.sh mnist b relu carlini 1276
./run_extra.sh mnist c standard carlini 1276
./run_extra.sh mnist c adversarial carlini 1276
./run_extra.sh mnist c relu carlini 1276
./run_extra.sh mnist a standard carlini 5922
./run_extra.sh mnist a adversarial carlini 5922
./run_extra.sh mnist a relu carlini 5922
./run_extra.sh mnist b standard carlini 5922
./run_extra.sh mnist b adversarial carlini 5922
./run_extra.sh mnist b relu carlini 5922
./run_extra.sh mnist c standard carlini 5922
./run_extra.sh mnist c adversarial carlini 5922
./run_extra.sh mnist c relu carlini 5922
./run_extra.sh mnist a standard carlini 8553
./run_extra.sh mnist a adversarial carlini 8553
./run_extra.sh mnist a relu carlini 8553
./run_extra.sh mnist b standard carlini 8553
./run_extra.sh mnist b adversarial carlini 8553
./run_extra.sh mnist b relu carlini 8553
./run_extra.sh mnist c standard carlini 8553
./run_extra.sh mnist c adversarial carlini 8553
./run_extra.sh mnist c relu carlini 8553
./run_extra.sh mnist a standard carlini 5165
./run_extra.sh mnist a adversarial carlini 5165
./run_extra.sh mnist a relu carlini 5165
./run_extra.sh mnist b standard carlini 5165
./run_extra.sh mnist b adversarial carlini 5165
./run_extra.sh mnist b relu carlini 5165
./run_extra.sh mnist c standard carlini 5165
./run_extra.sh mnist c adversarial carlini 5165
./run_extra.sh mnist c relu carlini 5165
./run_extra.sh mnist a standard carlini 6867
./run_extra.sh mnist a adversarial carlini 6867
./run_extra.sh mnist a relu carlini 6867
./run_extra.sh mnist b standard carlini 6867
./run_extra.sh mnist b adversarial carlini 6867
./run_extra.sh mnist b relu carlini 6867
./run_extra.sh mnist c standard carlini 6867
./run_extra.sh mnist c adversarial carlini 6867
./run_extra.sh mnist c relu carlini 6867
./run_extra.sh mnist a standard carlini 780
./run_extra.sh mnist a adversarial carlini 780
./run_extra.sh mnist a relu carlini 780
./run_extra.sh mnist b standard carlini 780
./run_extra.sh mnist b adversarial carlini 780
./run_extra.sh mnist b relu carlini 780
./run_extra.sh mnist c standard carlini 780
./run_extra.sh mnist c adversarial carlini 780
./run_extra.sh mnist c relu carlini 780
./run_extra.sh mnist a standard carlini 1926
./run_extra.sh mnist a adversarial carlini 1926
./run_extra.sh mnist a relu carlini 1926
./run_extra.sh mnist b standard carlini 1926
./run_extra.sh mnist b adversarial carlini 1926
./run_extra.sh mnist b relu carlini 1926
./run_extra.sh mnist c standard carlini 1926
./run_extra.sh mnist c adversarial carlini 1926
./run_extra.sh mnist c relu carlini 1926
./run_extra.sh mnist a standard carlini 1772
./run_extra.sh mnist a adversarial carlini 1772
./run_extra.sh mnist a relu carlini 1772
./run_extra.sh mnist b standard carlini 1772
./run_extra.sh mnist b adversarial carlini 1772
./run_extra.sh mnist b relu carlini 1772
./run_extra.sh mnist c standard carlini 1772
./run_extra.sh mnist c adversarial carlini 1772
./run_extra.sh mnist c relu carlini 1772
./run_extra.sh mnist a standard carlini 6362
./run_extra.sh mnist a adversarial carlini 6362
./run_extra.sh mnist a relu carlini 6362
./run_extra.sh mnist b standard carlini 6362
./run_extra.sh mnist b adversarial carlini 6362
./run_extra.sh mnist b relu carlini 6362
./run_extra.sh mnist c standard carlini 6362
./run_extra.sh mnist c adversarial carlini 6362
./run_extra.sh mnist c relu carlini 6362
./run_extra.sh mnist a standard carlini 2781
./run_extra.sh mnist a adversarial carlini 2781
./run_extra.sh mnist a relu carlini 2781
./run_extra.sh mnist b standard carlini 2781
./run_extra.sh mnist b adversarial carlini 2781
./run_extra.sh mnist b relu carlini 2781
./run_extra.sh mnist c standard carlini 2781
./run_extra.sh mnist c adversarial carlini 2781
./run_extra.sh mnist c relu carlini 2781
./run_extra.sh mnist a standard carlini 9921
./run_extra.sh mnist a adversarial carlini 9921
./run_extra.sh mnist a relu carlini 9921
./run_extra.sh mnist b standard carlini 9921
./run_extra.sh mnist b adversarial carlini 9921
./run_extra.sh mnist b relu carlini 9921
./run_extra.sh mnist c standard carlini 9921
./run_extra.sh mnist c adversarial carlini 9921
./run_extra.sh mnist c relu carlini 9921
./run_extra.sh mnist a standard carlini 8226
./run_extra.sh mnist a adversarial carlini 8226
./run_extra.sh mnist a relu carlini 8226
./run_extra.sh mnist b standard carlini 8226
./run_extra.sh mnist b adversarial carlini 8226
./run_extra.sh mnist b relu carlini 8226
./run_extra.sh mnist c standard carlini 8226
./run_extra.sh mnist c adversarial carlini 8226
./run_extra.sh mnist c relu carlini 8226
./run_extra.sh mnist a standard carlini 4007
./run_extra.sh mnist a adversarial carlini 4007
./run_extra.sh mnist a relu carlini 4007
./run_extra.sh mnist b standard carlini 4007
./run_extra.sh mnist b adversarial carlini 4007
./run_extra.sh mnist b relu carlini 4007
./run_extra.sh mnist c standard carlini 4007
./run_extra.sh mnist c adversarial carlini 4007
./run_extra.sh mnist c relu carlini 4007
./run_extra.sh mnist a standard carlini 5391
./run_extra.sh mnist a adversarial carlini 5391
./run_extra.sh mnist a relu carlini 5391
./run_extra.sh mnist b standard carlini 5391
./run_extra.sh mnist b adversarial carlini 5391
./run_extra.sh mnist b relu carlini 5391
./run_extra.sh mnist c standard carlini 5391
./run_extra.sh mnist c adversarial carlini 5391
./run_extra.sh mnist c relu carlini 5391
./run_extra.sh mnist a standard carlini 6994
./run_extra.sh mnist a adversarial carlini 6994
./run_extra.sh mnist a relu carlini 6994
./run_extra.sh mnist b standard carlini 6994
./run_extra.sh mnist b adversarial carlini 6994
./run_extra.sh mnist b relu carlini 6994
./run_extra.sh mnist c standard carlini 6994
./run_extra.sh mnist c adversarial carlini 6994
./run_extra.sh mnist c relu carlini 6994
./run_extra.sh mnist a standard carlini 1254
./run_extra.sh mnist a adversarial carlini 1254
./run_extra.sh mnist a relu carlini 1254
./run_extra.sh mnist b standard carlini 1254
./run_extra.sh mnist b adversarial carlini 1254
./run_extra.sh mnist b relu carlini 1254
./run_extra.sh mnist c standard carlini 1254
./run_extra.sh mnist c adversarial carlini 1254
./run_extra.sh mnist c relu carlini 1254
./run_extra.sh mnist a standard carlini 9232
./run_extra.sh mnist a adversarial carlini 9232
./run_extra.sh mnist a relu carlini 9232
./run_extra.sh mnist b standard carlini 9232
./run_extra.sh mnist b adversarial carlini 9232
./run_extra.sh mnist b relu carlini 9232
./run_extra.sh mnist c standard carlini 9232
./run_extra.sh mnist c adversarial carlini 9232
./run_extra.sh mnist c relu carlini 9232
./run_extra.sh mnist a standard carlini 7949
./run_extra.sh mnist a adversarial carlini 7949
./run_extra.sh mnist a relu carlini 7949
./run_extra.sh mnist b standard carlini 7949
./run_extra.sh mnist b adversarial carlini 7949
./run_extra.sh mnist b relu carlini 7949
./run_extra.sh mnist c standard carlini 7949
./run_extra.sh mnist c adversarial carlini 7949
./run_extra.sh mnist c relu carlini 7949
./run_extra.sh mnist a standard carlini 8192
./run_extra.sh mnist a adversarial carlini 8192
./run_extra.sh mnist a relu carlini 8192
./run_extra.sh mnist b standard carlini 8192
./run_extra.sh mnist b adversarial carlini 8192
./run_extra.sh mnist b relu carlini 8192
./run_extra.sh mnist c standard carlini 8192
./run_extra.sh mnist c adversarial carlini 8192
./run_extra.sh mnist c relu carlini 8192
./run_extra.sh mnist a standard carlini 8997
./run_extra.sh mnist a adversarial carlini 8997
./run_extra.sh mnist a relu carlini 8997
./run_extra.sh mnist b standard carlini 8997
./run_extra.sh mnist b adversarial carlini 8997
./run_extra.sh mnist b relu carlini 8997
./run_extra.sh mnist c standard carlini 8997
./run_extra.sh mnist c adversarial carlini 8997
./run_extra.sh mnist c relu carlini 8997
./run_extra.sh mnist a standard carlini 9012
./run_extra.sh mnist a adversarial carlini 9012
./run_extra.sh mnist a relu carlini 9012
./run_extra.sh mnist b standard carlini 9012
./run_extra.sh mnist b adversarial carlini 9012
./run_extra.sh mnist b relu carlini 9012
./run_extra.sh mnist c standard carlini 9012
./run_extra.sh mnist c adversarial carlini 9012
./run_extra.sh mnist c relu carlini 9012
./run_extra.sh mnist a standard carlini 2266
./run_extra.sh mnist a adversarial carlini 2266
./run_extra.sh mnist a relu carlini 2266
./run_extra.sh mnist b standard carlini 2266
./run_extra.sh mnist b adversarial carlini 2266
./run_extra.sh mnist b relu carlini 2266
./run_extra.sh mnist c standard carlini 2266
./run_extra.sh mnist c adversarial carlini 2266
./run_extra.sh mnist c relu carlini 2266
./run_extra.sh mnist a standard carlini 8928
./run_extra.sh mnist a adversarial carlini 8928
./run_extra.sh mnist a relu carlini 8928
./run_extra.sh mnist b standard carlini 8928
./run_extra.sh mnist b adversarial carlini 8928
./run_extra.sh mnist b relu carlini 8928
./run_extra.sh mnist c standard carlini 8928
./run_extra.sh mnist c adversarial carlini 8928
./run_extra.sh mnist c relu carlini 8928
./run_extra.sh mnist a standard carlini 9469
./run_extra.sh mnist a adversarial carlini 9469
./run_extra.sh mnist a relu carlini 9469
./run_extra.sh mnist b standard carlini 9469
./run_extra.sh mnist b adversarial carlini 9469
./run_extra.sh mnist b relu carlini 9469
./run_extra.sh mnist c standard carlini 9469
./run_extra.sh mnist c adversarial carlini 9469
./run_extra.sh mnist c relu carlini 9469
./run_extra.sh mnist a standard carlini 1621
./run_extra.sh mnist a adversarial carlini 1621
./run_extra.sh mnist a relu carlini 1621
./run_extra.sh mnist b standard carlini 1621
./run_extra.sh mnist b adversarial carlini 1621
./run_extra.sh mnist b relu carlini 1621
./run_extra.sh mnist c standard carlini 1621
./run_extra.sh mnist c adversarial carlini 1621
./run_extra.sh mnist c relu carlini 1621
./run_extra.sh mnist a standard carlini 9901
./run_extra.sh mnist a adversarial carlini 9901
./run_extra.sh mnist a relu carlini 9901
./run_extra.sh mnist b standard carlini 9901
./run_extra.sh mnist b adversarial carlini 9901
./run_extra.sh mnist b relu carlini 9901
./run_extra.sh mnist c standard carlini 9901
./run_extra.sh mnist c adversarial carlini 9901
./run_extra.sh mnist c relu carlini 9901
./run_extra.sh mnist a standard carlini 4910
./run_extra.sh mnist a adversarial carlini 4910
./run_extra.sh mnist a relu carlini 4910
./run_extra.sh mnist b standard carlini 4910
./run_extra.sh mnist b adversarial carlini 4910
./run_extra.sh mnist b relu carlini 4910
./run_extra.sh mnist c standard carlini 4910
./run_extra.sh mnist c adversarial carlini 4910
./run_extra.sh mnist c relu carlini 4910
./run_extra.sh mnist a standard carlini 9645
./run_extra.sh mnist a adversarial carlini 9645
./run_extra.sh mnist a relu carlini 9645
./run_extra.sh mnist b standard carlini 9645
./run_extra.sh mnist b adversarial carlini 9645
./run_extra.sh mnist b relu carlini 9645
./run_extra.sh mnist c standard carlini 9645
./run_extra.sh mnist c adversarial carlini 9645
./run_extra.sh mnist c relu carlini 9645
./run_extra.sh mnist a standard carlini 5985
./run_extra.sh mnist a adversarial carlini 5985
./run_extra.sh mnist a relu carlini 5985
./run_extra.sh mnist b standard carlini 5985
./run_extra.sh mnist b adversarial carlini 5985
./run_extra.sh mnist b relu carlini 5985
./run_extra.sh mnist c standard carlini 5985
./run_extra.sh mnist c adversarial carlini 5985
./run_extra.sh mnist c relu carlini 5985
./run_extra.sh mnist a standard carlini 6789
./run_extra.sh mnist a adversarial carlini 6789
./run_extra.sh mnist a relu carlini 6789
./run_extra.sh mnist b standard carlini 6789
./run_extra.sh mnist b adversarial carlini 6789
./run_extra.sh mnist b relu carlini 6789
./run_extra.sh mnist c standard carlini 6789
./run_extra.sh mnist c adversarial carlini 6789
./run_extra.sh mnist c relu carlini 6789
./run_extra.sh mnist a standard carlini 2995
./run_extra.sh mnist a adversarial carlini 2995
./run_extra.sh mnist a relu carlini 2995
./run_extra.sh mnist b standard carlini 2995
./run_extra.sh mnist b adversarial carlini 2995
./run_extra.sh mnist b relu carlini 2995
./run_extra.sh mnist c standard carlini 2995
./run_extra.sh mnist c adversarial carlini 2995
./run_extra.sh mnist c relu carlini 2995
./run_extra.sh mnist a standard carlini 9050
./run_extra.sh mnist a adversarial carlini 9050
./run_extra.sh mnist a relu carlini 9050
./run_extra.sh mnist b standard carlini 9050
./run_extra.sh mnist b adversarial carlini 9050
./run_extra.sh mnist b relu carlini 9050
./run_extra.sh mnist c standard carlini 9050
./run_extra.sh mnist c adversarial carlini 9050
./run_extra.sh mnist c relu carlini 9050
./run_extra.sh mnist a standard carlini 8699
./run_extra.sh mnist a adversarial carlini 8699
./run_extra.sh mnist a relu carlini 8699
./run_extra.sh mnist b standard carlini 8699
./run_extra.sh mnist b adversarial carlini 8699
./run_extra.sh mnist b relu carlini 8699
./run_extra.sh mnist c standard carlini 8699
./run_extra.sh mnist c adversarial carlini 8699
./run_extra.sh mnist c relu carlini 8699
./run_extra.sh mnist a standard carlini 5803
./run_extra.sh mnist a adversarial carlini 5803
./run_extra.sh mnist a relu carlini 5803
./run_extra.sh mnist b standard carlini 5803
./run_extra.sh mnist b adversarial carlini 5803
./run_extra.sh mnist b relu carlini 5803
./run_extra.sh mnist c standard carlini 5803
./run_extra.sh mnist c adversarial carlini 5803
./run_extra.sh mnist c relu carlini 5803
./run_extra.sh mnist a standard carlini 6535
./run_extra.sh mnist a adversarial carlini 6535
./run_extra.sh mnist a relu carlini 6535
./run_extra.sh mnist b standard carlini 6535
./run_extra.sh mnist b adversarial carlini 6535
./run_extra.sh mnist b relu carlini 6535
./run_extra.sh mnist c standard carlini 6535
./run_extra.sh mnist c adversarial carlini 6535
./run_extra.sh mnist c relu carlini 6535
./run_extra.sh mnist a standard carlini 8883
./run_extra.sh mnist a adversarial carlini 8883
./run_extra.sh mnist a relu carlini 8883
./run_extra.sh mnist b standard carlini 8883
./run_extra.sh mnist b adversarial carlini 8883
./run_extra.sh mnist b relu carlini 8883
./run_extra.sh mnist c standard carlini 8883
./run_extra.sh mnist c adversarial carlini 8883
./run_extra.sh mnist c relu carlini 8883
./run_extra.sh mnist a standard carlini 4681
./run_extra.sh mnist a adversarial carlini 4681
./run_extra.sh mnist a relu carlini 4681
./run_extra.sh mnist b standard carlini 4681
./run_extra.sh mnist b adversarial carlini 4681
./run_extra.sh mnist b relu carlini 4681
./run_extra.sh mnist c standard carlini 4681
./run_extra.sh mnist c adversarial carlini 4681
./run_extra.sh mnist c relu carlini 4681
./run_extra.sh mnist a standard carlini 9934
./run_extra.sh mnist a adversarial carlini 9934
./run_extra.sh mnist a relu carlini 9934
./run_extra.sh mnist b standard carlini 9934
./run_extra.sh mnist b adversarial carlini 9934
./run_extra.sh mnist b relu carlini 9934
./run_extra.sh mnist c standard carlini 9934
./run_extra.sh mnist c adversarial carlini 9934
./run_extra.sh mnist c relu carlini 9934
./run_extra.sh mnist a standard carlini 3500
./run_extra.sh mnist a adversarial carlini 3500
./run_extra.sh mnist a relu carlini 3500
./run_extra.sh mnist b standard carlini 3500
./run_extra.sh mnist b adversarial carlini 3500
./run_extra.sh mnist b relu carlini 3500
./run_extra.sh mnist c standard carlini 3500
./run_extra.sh mnist c adversarial carlini 3500
./run_extra.sh mnist c relu carlini 3500
./run_extra.sh mnist a standard carlini 1625
./run_extra.sh mnist a adversarial carlini 1625
./run_extra.sh mnist a relu carlini 1625
./run_extra.sh mnist b standard carlini 1625
./run_extra.sh mnist b adversarial carlini 1625
./run_extra.sh mnist b relu carlini 1625
./run_extra.sh mnist c standard carlini 1625
./run_extra.sh mnist c adversarial carlini 1625
./run_extra.sh mnist c relu carlini 1625
./run_extra.sh mnist a standard carlini 5654
./run_extra.sh mnist a adversarial carlini 5654
./run_extra.sh mnist a relu carlini 5654
./run_extra.sh mnist b standard carlini 5654
./run_extra.sh mnist b adversarial carlini 5654
./run_extra.sh mnist b relu carlini 5654
./run_extra.sh mnist c standard carlini 5654
./run_extra.sh mnist c adversarial carlini 5654
./run_extra.sh mnist c relu carlini 5654
./run_extra.sh mnist a standard carlini 4791
./run_extra.sh mnist a adversarial carlini 4791
./run_extra.sh mnist a relu carlini 4791
./run_extra.sh mnist b standard carlini 4791
./run_extra.sh mnist b adversarial carlini 4791
./run_extra.sh mnist b relu carlini 4791
./run_extra.sh mnist c standard carlini 4791
./run_extra.sh mnist c adversarial carlini 4791
./run_extra.sh mnist c relu carlini 4791
./run_extra.sh mnist a standard carlini 9069
./run_extra.sh mnist a adversarial carlini 9069
./run_extra.sh mnist a relu carlini 9069
./run_extra.sh mnist b standard carlini 9069
./run_extra.sh mnist b adversarial carlini 9069
./run_extra.sh mnist b relu carlini 9069
./run_extra.sh mnist c standard carlini 9069
./run_extra.sh mnist c adversarial carlini 9069
./run_extra.sh mnist c relu carlini 9069
./run_extra.sh mnist a standard carlini 3190
./run_extra.sh mnist a adversarial carlini 3190
./run_extra.sh mnist a relu carlini 3190
./run_extra.sh mnist b standard carlini 3190
./run_extra.sh mnist b adversarial carlini 3190
./run_extra.sh mnist b relu carlini 3190
./run_extra.sh mnist c standard carlini 3190
./run_extra.sh mnist c adversarial carlini 3190
./run_extra.sh mnist c relu carlini 3190
./run_extra.sh mnist a standard carlini 7387
./run_extra.sh mnist a adversarial carlini 7387
./run_extra.sh mnist a relu carlini 7387
./run_extra.sh mnist b standard carlini 7387
./run_extra.sh mnist b adversarial carlini 7387
./run_extra.sh mnist b relu carlini 7387
./run_extra.sh mnist c standard carlini 7387
./run_extra.sh mnist c adversarial carlini 7387
./run_extra.sh mnist c relu carlini 7387
./run_extra.sh mnist a standard carlini 6946
./run_extra.sh mnist a adversarial carlini 6946
./run_extra.sh mnist a relu carlini 6946
./run_extra.sh mnist b standard carlini 6946
./run_extra.sh mnist b adversarial carlini 6946
./run_extra.sh mnist b relu carlini 6946
./run_extra.sh mnist c standard carlini 6946
./run_extra.sh mnist c adversarial carlini 6946
./run_extra.sh mnist c relu carlini 6946
./run_extra.sh mnist a standard carlini 4616
./run_extra.sh mnist a adversarial carlini 4616
./run_extra.sh mnist a relu carlini 4616
./run_extra.sh mnist b standard carlini 4616
./run_extra.sh mnist b adversarial carlini 4616
./run_extra.sh mnist b relu carlini 4616
./run_extra.sh mnist c standard carlini 4616
./run_extra.sh mnist c adversarial carlini 4616
./run_extra.sh mnist c relu carlini 4616
./run_extra.sh mnist a standard carlini 6703
./run_extra.sh mnist a adversarial carlini 6703
./run_extra.sh mnist a relu carlini 6703
./run_extra.sh mnist b standard carlini 6703
./run_extra.sh mnist b adversarial carlini 6703
./run_extra.sh mnist b relu carlini 6703
./run_extra.sh mnist c standard carlini 6703
./run_extra.sh mnist c adversarial carlini 6703
./run_extra.sh mnist c relu carlini 6703
./run_extra.sh mnist a standard carlini 8157
./run_extra.sh mnist a adversarial carlini 8157
./run_extra.sh mnist a relu carlini 8157
./run_extra.sh mnist b standard carlini 8157
./run_extra.sh mnist b adversarial carlini 8157
./run_extra.sh mnist b relu carlini 8157
./run_extra.sh mnist c standard carlini 8157
./run_extra.sh mnist c adversarial carlini 8157
./run_extra.sh mnist c relu carlini 8157
./run_extra.sh mnist a standard carlini 1584
./run_extra.sh mnist a adversarial carlini 1584
./run_extra.sh mnist a relu carlini 1584
./run_extra.sh mnist b standard carlini 1584
./run_extra.sh mnist b adversarial carlini 1584
./run_extra.sh mnist b relu carlini 1584
./run_extra.sh mnist c standard carlini 1584
./run_extra.sh mnist c adversarial carlini 1584
./run_extra.sh mnist c relu carlini 1584
./run_extra.sh mnist a standard carlini 3438
./run_extra.sh mnist a adversarial carlini 3438
./run_extra.sh mnist a relu carlini 3438
./run_extra.sh mnist b standard carlini 3438
./run_extra.sh mnist b adversarial carlini 3438
./run_extra.sh mnist b relu carlini 3438
./run_extra.sh mnist c standard carlini 3438
./run_extra.sh mnist c adversarial carlini 3438
./run_extra.sh mnist c relu carlini 3438
./run_extra.sh mnist a standard carlini 6335
./run_extra.sh mnist a adversarial carlini 6335
./run_extra.sh mnist a relu carlini 6335
./run_extra.sh mnist b standard carlini 6335
./run_extra.sh mnist b adversarial carlini 6335
./run_extra.sh mnist b relu carlini 6335
./run_extra.sh mnist c standard carlini 6335
./run_extra.sh mnist c adversarial carlini 6335
./run_extra.sh mnist c relu carlini 6335
./run_extra.sh mnist a standard carlini 672
./run_extra.sh mnist a adversarial carlini 672
./run_extra.sh mnist a relu carlini 672
./run_extra.sh mnist b standard carlini 672
./run_extra.sh mnist b adversarial carlini 672
./run_extra.sh mnist b relu carlini 672
./run_extra.sh mnist c standard carlini 672
./run_extra.sh mnist c adversarial carlini 672
./run_extra.sh mnist c relu carlini 672
./run_extra.sh mnist a standard carlini 621
./run_extra.sh mnist a adversarial carlini 621
./run_extra.sh mnist a relu carlini 621
./run_extra.sh mnist b standard carlini 621
./run_extra.sh mnist b adversarial carlini 621
./run_extra.sh mnist b relu carlini 621
./run_extra.sh mnist c standard carlini 621
./run_extra.sh mnist c adversarial carlini 621
./run_extra.sh mnist c relu carlini 621
./run_extra.sh mnist a standard carlini 2398
./run_extra.sh mnist a adversarial carlini 2398
./run_extra.sh mnist a relu carlini 2398
./run_extra.sh mnist b standard carlini 2398
./run_extra.sh mnist b adversarial carlini 2398
./run_extra.sh mnist b relu carlini 2398
./run_extra.sh mnist c standard carlini 2398
./run_extra.sh mnist c adversarial carlini 2398
./run_extra.sh mnist c relu carlini 2398
./run_extra.sh mnist a standard carlini 7012
./run_extra.sh mnist a adversarial carlini 7012
./run_extra.sh mnist a relu carlini 7012
./run_extra.sh mnist b standard carlini 7012
./run_extra.sh mnist b adversarial carlini 7012
./run_extra.sh mnist b relu carlini 7012
./run_extra.sh mnist c standard carlini 7012
./run_extra.sh mnist c adversarial carlini 7012
./run_extra.sh mnist c relu carlini 7012
./run_extra.sh mnist a standard carlini 7483
./run_extra.sh mnist a adversarial carlini 7483
./run_extra.sh mnist a relu carlini 7483
./run_extra.sh mnist b standard carlini 7483
./run_extra.sh mnist b adversarial carlini 7483
./run_extra.sh mnist b relu carlini 7483
./run_extra.sh mnist c standard carlini 7483
./run_extra.sh mnist c adversarial carlini 7483
./run_extra.sh mnist c relu carlini 7483
./run_extra.sh mnist a standard carlini 3629
./run_extra.sh mnist a adversarial carlini 3629
./run_extra.sh mnist a relu carlini 3629
./run_extra.sh mnist b standard carlini 3629
./run_extra.sh mnist b adversarial carlini 3629
./run_extra.sh mnist b relu carlini 3629
./run_extra.sh mnist c standard carlini 3629
./run_extra.sh mnist c adversarial carlini 3629
./run_extra.sh mnist c relu carlini 3629
./run_extra.sh mnist a standard carlini 5584
./run_extra.sh mnist a adversarial carlini 5584
./run_extra.sh mnist a relu carlini 5584
./run_extra.sh mnist b standard carlini 5584
./run_extra.sh mnist b adversarial carlini 5584
./run_extra.sh mnist b relu carlini 5584
./run_extra.sh mnist c standard carlini 5584
./run_extra.sh mnist c adversarial carlini 5584
./run_extra.sh mnist c relu carlini 5584
./run_extra.sh mnist a standard carlini 2090
./run_extra.sh mnist a adversarial carlini 2090
./run_extra.sh mnist a relu carlini 2090
./run_extra.sh mnist b standard carlini 2090
./run_extra.sh mnist b adversarial carlini 2090
./run_extra.sh mnist b relu carlini 2090
./run_extra.sh mnist c standard carlini 2090
./run_extra.sh mnist c adversarial carlini 2090
./run_extra.sh mnist c relu carlini 2090
./run_extra.sh mnist a standard carlini 1526
./run_extra.sh mnist a adversarial carlini 1526
./run_extra.sh mnist a relu carlini 1526
./run_extra.sh mnist b standard carlini 1526
./run_extra.sh mnist b adversarial carlini 1526
./run_extra.sh mnist b relu carlini 1526
./run_extra.sh mnist c standard carlini 1526
./run_extra.sh mnist c adversarial carlini 1526
./run_extra.sh mnist c relu carlini 1526
./run_extra.sh mnist a standard carlini 9331
./run_extra.sh mnist a adversarial carlini 9331
./run_extra.sh mnist a relu carlini 9331
./run_extra.sh mnist b standard carlini 9331
./run_extra.sh mnist b adversarial carlini 9331
./run_extra.sh mnist b relu carlini 9331
./run_extra.sh mnist c standard carlini 9331
./run_extra.sh mnist c adversarial carlini 9331
./run_extra.sh mnist c relu carlini 9331
./run_extra.sh mnist a standard carlini 8988
./run_extra.sh mnist a adversarial carlini 8988
./run_extra.sh mnist a relu carlini 8988
./run_extra.sh mnist b standard carlini 8988
./run_extra.sh mnist b adversarial carlini 8988
./run_extra.sh mnist b relu carlini 8988
./run_extra.sh mnist c standard carlini 8988
./run_extra.sh mnist c adversarial carlini 8988
./run_extra.sh mnist c relu carlini 8988
./run_extra.sh mnist a standard carlini 910
./run_extra.sh mnist a adversarial carlini 910
./run_extra.sh mnist a relu carlini 910
./run_extra.sh mnist b standard carlini 910
./run_extra.sh mnist b adversarial carlini 910
./run_extra.sh mnist b relu carlini 910
./run_extra.sh mnist c standard carlini 910
./run_extra.sh mnist c adversarial carlini 910
./run_extra.sh mnist c relu carlini 910
./run_extra.sh mnist a standard carlini 5864
./run_extra.sh mnist a adversarial carlini 5864
./run_extra.sh mnist a relu carlini 5864
./run_extra.sh mnist b standard carlini 5864
./run_extra.sh mnist b adversarial carlini 5864
./run_extra.sh mnist b relu carlini 5864
./run_extra.sh mnist c standard carlini 5864
./run_extra.sh mnist c adversarial carlini 5864
./run_extra.sh mnist c relu carlini 5864
./run_extra.sh mnist a standard carlini 1082
./run_extra.sh mnist a adversarial carlini 1082
./run_extra.sh mnist a relu carlini 1082
./run_extra.sh mnist b standard carlini 1082
./run_extra.sh mnist b adversarial carlini 1082
./run_extra.sh mnist b relu carlini 1082
./run_extra.sh mnist c standard carlini 1082
./run_extra.sh mnist c adversarial carlini 1082
./run_extra.sh mnist c relu carlini 1082
./run_extra.sh mnist a standard carlini 1730
./run_extra.sh mnist a adversarial carlini 1730
./run_extra.sh mnist a relu carlini 1730
./run_extra.sh mnist b standard carlini 1730
./run_extra.sh mnist b adversarial carlini 1730
./run_extra.sh mnist b relu carlini 1730
./run_extra.sh mnist c standard carlini 1730
./run_extra.sh mnist c adversarial carlini 1730
./run_extra.sh mnist c relu carlini 1730
./run_extra.sh mnist a standard carlini 519
./run_extra.sh mnist a adversarial carlini 519
./run_extra.sh mnist a relu carlini 519
./run_extra.sh mnist b standard carlini 519
./run_extra.sh mnist b adversarial carlini 519
./run_extra.sh mnist b relu carlini 519
./run_extra.sh mnist c standard carlini 519
./run_extra.sh mnist c adversarial carlini 519
./run_extra.sh mnist c relu carlini 519
./run_extra.sh mnist a standard carlini 1522
./run_extra.sh mnist a adversarial carlini 1522
./run_extra.sh mnist a relu carlini 1522
./run_extra.sh mnist b standard carlini 1522
./run_extra.sh mnist b adversarial carlini 1522
./run_extra.sh mnist b relu carlini 1522
./run_extra.sh mnist c standard carlini 1522
./run_extra.sh mnist c adversarial carlini 1522
./run_extra.sh mnist c relu carlini 1522
./run_extra.sh mnist a standard carlini 9602
./run_extra.sh mnist a adversarial carlini 9602
./run_extra.sh mnist a relu carlini 9602
./run_extra.sh mnist b standard carlini 9602
./run_extra.sh mnist b adversarial carlini 9602
./run_extra.sh mnist b relu carlini 9602
./run_extra.sh mnist c standard carlini 9602
./run_extra.sh mnist c adversarial carlini 9602
./run_extra.sh mnist c relu carlini 9602
./run_extra.sh mnist a standard carlini 1156
./run_extra.sh mnist a adversarial carlini 1156
./run_extra.sh mnist a relu carlini 1156
./run_extra.sh mnist b standard carlini 1156
./run_extra.sh mnist b adversarial carlini 1156
./run_extra.sh mnist b relu carlini 1156
./run_extra.sh mnist c standard carlini 1156
./run_extra.sh mnist c adversarial carlini 1156
./run_extra.sh mnist c relu carlini 1156
./run_extra.sh mnist a standard carlini 563
./run_extra.sh mnist a adversarial carlini 563
./run_extra.sh mnist a relu carlini 563
./run_extra.sh mnist b standard carlini 563
./run_extra.sh mnist b adversarial carlini 563
./run_extra.sh mnist b relu carlini 563
./run_extra.sh mnist c standard carlini 563
./run_extra.sh mnist c adversarial carlini 563
./run_extra.sh mnist c relu carlini 563
./run_extra.sh mnist a standard carlini 1068
./run_extra.sh mnist a adversarial carlini 1068
./run_extra.sh mnist a relu carlini 1068
./run_extra.sh mnist b standard carlini 1068
./run_extra.sh mnist b adversarial carlini 1068
./run_extra.sh mnist b relu carlini 1068
./run_extra.sh mnist c standard carlini 1068
./run_extra.sh mnist c adversarial carlini 1068
./run_extra.sh mnist c relu carlini 1068
./run_extra.sh mnist a standard carlini 2170
./run_extra.sh mnist a adversarial carlini 2170
./run_extra.sh mnist a relu carlini 2170
./run_extra.sh mnist b standard carlini 2170
./run_extra.sh mnist b adversarial carlini 2170
./run_extra.sh mnist b relu carlini 2170
./run_extra.sh mnist c standard carlini 2170
./run_extra.sh mnist c adversarial carlini 2170
./run_extra.sh mnist c relu carlini 2170
./run_extra.sh mnist a standard carlini 8544
./run_extra.sh mnist a adversarial carlini 8544
./run_extra.sh mnist a relu carlini 8544
./run_extra.sh mnist b standard carlini 8544
./run_extra.sh mnist b adversarial carlini 8544
./run_extra.sh mnist b relu carlini 8544
./run_extra.sh mnist c standard carlini 8544
./run_extra.sh mnist c adversarial carlini 8544
./run_extra.sh mnist c relu carlini 8544
./run_extra.sh mnist a standard carlini 1234
./run_extra.sh mnist a adversarial carlini 1234
./run_extra.sh mnist a relu carlini 1234
./run_extra.sh mnist b standard carlini 1234
./run_extra.sh mnist b adversarial carlini 1234
./run_extra.sh mnist b relu carlini 1234
./run_extra.sh mnist c standard carlini 1234
./run_extra.sh mnist c adversarial carlini 1234
./run_extra.sh mnist c relu carlini 1234
./run_extra.sh mnist a standard carlini 4604
./run_extra.sh mnist a adversarial carlini 4604
./run_extra.sh mnist a relu carlini 4604
./run_extra.sh mnist b standard carlini 4604
./run_extra.sh mnist b adversarial carlini 4604
./run_extra.sh mnist b relu carlini 4604
./run_extra.sh mnist c standard carlini 4604
./run_extra.sh mnist c adversarial carlini 4604
./run_extra.sh mnist c relu carlini 4604
./run_extra.sh mnist a standard carlini 4023
./run_extra.sh mnist a adversarial carlini 4023
./run_extra.sh mnist a relu carlini 4023
./run_extra.sh mnist b standard carlini 4023
./run_extra.sh mnist b adversarial carlini 4023
./run_extra.sh mnist b relu carlini 4023
./run_extra.sh mnist c standard carlini 4023
./run_extra.sh mnist c adversarial carlini 4023
./run_extra.sh mnist c relu carlini 4023
./run_extra.sh mnist a standard carlini 4321
./run_extra.sh mnist a adversarial carlini 4321
./run_extra.sh mnist a relu carlini 4321
./run_extra.sh mnist b standard carlini 4321
./run_extra.sh mnist b adversarial carlini 4321
./run_extra.sh mnist b relu carlini 4321
./run_extra.sh mnist c standard carlini 4321
./run_extra.sh mnist c adversarial carlini 4321
./run_extra.sh mnist c relu carlini 4321
./run_extra.sh mnist a standard carlini 5621
./run_extra.sh mnist a adversarial carlini 5621
./run_extra.sh mnist a relu carlini 5621
./run_extra.sh mnist b standard carlini 5621
./run_extra.sh mnist b adversarial carlini 5621
./run_extra.sh mnist b relu carlini 5621
./run_extra.sh mnist c standard carlini 5621
./run_extra.sh mnist c adversarial carlini 5621
./run_extra.sh mnist c relu carlini 5621
./run_extra.sh mnist a standard carlini 3551
./run_extra.sh mnist a adversarial carlini 3551
./run_extra.sh mnist a relu carlini 3551
./run_extra.sh mnist b standard carlini 3551
./run_extra.sh mnist b adversarial carlini 3551
./run_extra.sh mnist b relu carlini 3551
./run_extra.sh mnist c standard carlini 3551
./run_extra.sh mnist c adversarial carlini 3551
./run_extra.sh mnist c relu carlini 3551
./run_extra.sh mnist a standard carlini 3396
./run_extra.sh mnist a adversarial carlini 3396
./run_extra.sh mnist a relu carlini 3396
./run_extra.sh mnist b standard carlini 3396
./run_extra.sh mnist b adversarial carlini 3396
./run_extra.sh mnist b relu carlini 3396
./run_extra.sh mnist c standard carlini 3396
./run_extra.sh mnist c adversarial carlini 3396
./run_extra.sh mnist c relu carlini 3396
./run_extra.sh mnist a standard carlini 5523
./run_extra.sh mnist a adversarial carlini 5523
./run_extra.sh mnist a relu carlini 5523
./run_extra.sh mnist b standard carlini 5523
./run_extra.sh mnist b adversarial carlini 5523
./run_extra.sh mnist b relu carlini 5523
./run_extra.sh mnist c standard carlini 5523
./run_extra.sh mnist c adversarial carlini 5523
./run_extra.sh mnist c relu carlini 5523
./run_extra.sh mnist a standard carlini 9033
./run_extra.sh mnist a adversarial carlini 9033
./run_extra.sh mnist a relu carlini 9033
./run_extra.sh mnist b standard carlini 9033
./run_extra.sh mnist b adversarial carlini 9033
./run_extra.sh mnist b relu carlini 9033
./run_extra.sh mnist c standard carlini 9033
./run_extra.sh mnist c adversarial carlini 9033
./run_extra.sh mnist c relu carlini 9033
./run_extra.sh mnist a standard carlini 2081
./run_extra.sh mnist a adversarial carlini 2081
./run_extra.sh mnist a relu carlini 2081
./run_extra.sh mnist b standard carlini 2081
./run_extra.sh mnist b adversarial carlini 2081
./run_extra.sh mnist b relu carlini 2081
./run_extra.sh mnist c standard carlini 2081
./run_extra.sh mnist c adversarial carlini 2081
./run_extra.sh mnist c relu carlini 2081
./run_extra.sh mnist a standard carlini 7062
./run_extra.sh mnist a adversarial carlini 7062
./run_extra.sh mnist a relu carlini 7062
./run_extra.sh mnist b standard carlini 7062
./run_extra.sh mnist b adversarial carlini 7062
./run_extra.sh mnist b relu carlini 7062
./run_extra.sh mnist c standard carlini 7062
./run_extra.sh mnist c adversarial carlini 7062
./run_extra.sh mnist c relu carlini 7062
./run_extra.sh mnist a standard carlini 2034
./run_extra.sh mnist a adversarial carlini 2034
./run_extra.sh mnist a relu carlini 2034
./run_extra.sh mnist b standard carlini 2034
./run_extra.sh mnist b adversarial carlini 2034
./run_extra.sh mnist b relu carlini 2034
./run_extra.sh mnist c standard carlini 2034
./run_extra.sh mnist c adversarial carlini 2034
./run_extra.sh mnist c relu carlini 2034
./run_extra.sh mnist a standard carlini 470
./run_extra.sh mnist a adversarial carlini 470
./run_extra.sh mnist a relu carlini 470
./run_extra.sh mnist b standard carlini 470
./run_extra.sh mnist b adversarial carlini 470
./run_extra.sh mnist b relu carlini 470
./run_extra.sh mnist c standard carlini 470
./run_extra.sh mnist c adversarial carlini 470
./run_extra.sh mnist c relu carlini 470
./run_extra.sh mnist a standard carlini 6255
./run_extra.sh mnist a adversarial carlini 6255
./run_extra.sh mnist a relu carlini 6255
./run_extra.sh mnist b standard carlini 6255
./run_extra.sh mnist b adversarial carlini 6255
./run_extra.sh mnist b relu carlini 6255
./run_extra.sh mnist c standard carlini 6255
./run_extra.sh mnist c adversarial carlini 6255
./run_extra.sh mnist c relu carlini 6255
./run_extra.sh mnist a standard carlini 450
./run_extra.sh mnist a adversarial carlini 450
./run_extra.sh mnist a relu carlini 450
./run_extra.sh mnist b standard carlini 450
./run_extra.sh mnist b adversarial carlini 450
./run_extra.sh mnist b relu carlini 450
./run_extra.sh mnist c standard carlini 450
./run_extra.sh mnist c adversarial carlini 450
./run_extra.sh mnist c relu carlini 450
./run_extra.sh mnist a standard carlini 4345
./run_extra.sh mnist a adversarial carlini 4345
./run_extra.sh mnist a relu carlini 4345
./run_extra.sh mnist b standard carlini 4345
./run_extra.sh mnist b adversarial carlini 4345
./run_extra.sh mnist b relu carlini 4345
./run_extra.sh mnist c standard carlini 4345
./run_extra.sh mnist c adversarial carlini 4345
./run_extra.sh mnist c relu carlini 4345
./run_extra.sh mnist a standard carlini 8730
./run_extra.sh mnist a adversarial carlini 8730
./run_extra.sh mnist a relu carlini 8730
./run_extra.sh mnist b standard carlini 8730
./run_extra.sh mnist b adversarial carlini 8730
./run_extra.sh mnist b relu carlini 8730
./run_extra.sh mnist c standard carlini 8730
./run_extra.sh mnist c adversarial carlini 8730
./run_extra.sh mnist c relu carlini 8730
./run_extra.sh mnist a standard carlini 6065
./run_extra.sh mnist a adversarial carlini 6065
./run_extra.sh mnist a relu carlini 6065
./run_extra.sh mnist b standard carlini 6065
./run_extra.sh mnist b adversarial carlini 6065
./run_extra.sh mnist b relu carlini 6065
./run_extra.sh mnist c standard carlini 6065
./run_extra.sh mnist c adversarial carlini 6065
./run_extra.sh mnist c relu carlini 6065
./run_extra.sh mnist a standard carlini 6017
./run_extra.sh mnist a adversarial carlini 6017
./run_extra.sh mnist a relu carlini 6017
./run_extra.sh mnist b standard carlini 6017
./run_extra.sh mnist b adversarial carlini 6017
./run_extra.sh mnist b relu carlini 6017
./run_extra.sh mnist c standard carlini 6017
./run_extra.sh mnist c adversarial carlini 6017
./run_extra.sh mnist c relu carlini 6017
./run_extra.sh mnist a standard carlini 3885
./run_extra.sh mnist a adversarial carlini 3885
./run_extra.sh mnist a relu carlini 3885
./run_extra.sh mnist b standard carlini 3885
./run_extra.sh mnist b adversarial carlini 3885
./run_extra.sh mnist b relu carlini 3885
./run_extra.sh mnist c standard carlini 3885
./run_extra.sh mnist c adversarial carlini 3885
./run_extra.sh mnist c relu carlini 3885
./run_extra.sh mnist a standard carlini 7173
./run_extra.sh mnist a adversarial carlini 7173
./run_extra.sh mnist a relu carlini 7173
./run_extra.sh mnist b standard carlini 7173
./run_extra.sh mnist b adversarial carlini 7173
./run_extra.sh mnist b relu carlini 7173
./run_extra.sh mnist c standard carlini 7173
./run_extra.sh mnist c adversarial carlini 7173
./run_extra.sh mnist c relu carlini 7173
./run_extra.sh mnist a standard carlini 2818
./run_extra.sh mnist a adversarial carlini 2818
./run_extra.sh mnist a relu carlini 2818
./run_extra.sh mnist b standard carlini 2818
./run_extra.sh mnist b adversarial carlini 2818
./run_extra.sh mnist b relu carlini 2818
./run_extra.sh mnist c standard carlini 2818
./run_extra.sh mnist c adversarial carlini 2818
./run_extra.sh mnist c relu carlini 2818
./run_extra.sh mnist a standard carlini 3780
./run_extra.sh mnist a adversarial carlini 3780
./run_extra.sh mnist a relu carlini 3780
./run_extra.sh mnist b standard carlini 3780
./run_extra.sh mnist b adversarial carlini 3780
./run_extra.sh mnist b relu carlini 3780
./run_extra.sh mnist c standard carlini 3780
./run_extra.sh mnist c adversarial carlini 3780
./run_extra.sh mnist c relu carlini 3780
./run_extra.sh mnist a standard carlini 5040
./run_extra.sh mnist a adversarial carlini 5040
./run_extra.sh mnist a relu carlini 5040
./run_extra.sh mnist b standard carlini 5040
./run_extra.sh mnist b adversarial carlini 5040
./run_extra.sh mnist b relu carlini 5040
./run_extra.sh mnist c standard carlini 5040
./run_extra.sh mnist c adversarial carlini 5040
./run_extra.sh mnist c relu carlini 5040
./run_extra.sh mnist a standard carlini 6210
./run_extra.sh mnist a adversarial carlini 6210
./run_extra.sh mnist a relu carlini 6210
./run_extra.sh mnist b standard carlini 6210
./run_extra.sh mnist b adversarial carlini 6210
./run_extra.sh mnist b relu carlini 6210
./run_extra.sh mnist c standard carlini 6210
./run_extra.sh mnist c adversarial carlini 6210
./run_extra.sh mnist c relu carlini 6210
./run_extra.sh mnist a standard carlini 8519
./run_extra.sh mnist a adversarial carlini 8519
./run_extra.sh mnist a relu carlini 8519
./run_extra.sh mnist b standard carlini 8519
./run_extra.sh mnist b adversarial carlini 8519
./run_extra.sh mnist b relu carlini 8519
./run_extra.sh mnist c standard carlini 8519
./run_extra.sh mnist c adversarial carlini 8519
./run_extra.sh mnist c relu carlini 8519
./run_extra.sh mnist a standard carlini 6656
./run_extra.sh mnist a adversarial carlini 6656
./run_extra.sh mnist a relu carlini 6656
./run_extra.sh mnist b standard carlini 6656
./run_extra.sh mnist b adversarial carlini 6656
./run_extra.sh mnist b relu carlini 6656
./run_extra.sh mnist c standard carlini 6656
./run_extra.sh mnist c adversarial carlini 6656
./run_extra.sh mnist c relu carlini 6656
./run_extra.sh mnist a standard carlini 3535
./run_extra.sh mnist a adversarial carlini 3535
./run_extra.sh mnist a relu carlini 3535
./run_extra.sh mnist b standard carlini 3535
./run_extra.sh mnist b adversarial carlini 3535
./run_extra.sh mnist b relu carlini 3535
./run_extra.sh mnist c standard carlini 3535
./run_extra.sh mnist c adversarial carlini 3535
./run_extra.sh mnist c relu carlini 3535
./run_extra.sh mnist a standard carlini 2270
./run_extra.sh mnist a adversarial carlini 2270
./run_extra.sh mnist a relu carlini 2270
./run_extra.sh mnist b standard carlini 2270
./run_extra.sh mnist b adversarial carlini 2270
./run_extra.sh mnist b relu carlini 2270
./run_extra.sh mnist c standard carlini 2270
./run_extra.sh mnist c adversarial carlini 2270
./run_extra.sh mnist c relu carlini 2270
./run_extra.sh mnist a standard carlini 8915
./run_extra.sh mnist a adversarial carlini 8915
./run_extra.sh mnist a relu carlini 8915
./run_extra.sh mnist b standard carlini 8915
./run_extra.sh mnist b adversarial carlini 8915
./run_extra.sh mnist b relu carlini 8915
./run_extra.sh mnist c standard carlini 8915
./run_extra.sh mnist c adversarial carlini 8915
./run_extra.sh mnist c relu carlini 8915
./run_extra.sh mnist a standard carlini 8259
./run_extra.sh mnist a adversarial carlini 8259
./run_extra.sh mnist a relu carlini 8259
./run_extra.sh mnist b standard carlini 8259
./run_extra.sh mnist b adversarial carlini 8259
./run_extra.sh mnist b relu carlini 8259
./run_extra.sh mnist c standard carlini 8259
./run_extra.sh mnist c adversarial carlini 8259
./run_extra.sh mnist c relu carlini 8259
./run_extra.sh mnist a standard carlini 2531
./run_extra.sh mnist a adversarial carlini 2531
./run_extra.sh mnist a relu carlini 2531
./run_extra.sh mnist b standard carlini 2531
./run_extra.sh mnist b adversarial carlini 2531
./run_extra.sh mnist b relu carlini 2531
./run_extra.sh mnist c standard carlini 2531
./run_extra.sh mnist c adversarial carlini 2531
./run_extra.sh mnist c relu carlini 2531
./run_extra.sh mnist a standard carlini 7687
./run_extra.sh mnist a adversarial carlini 7687
./run_extra.sh mnist a relu carlini 7687
./run_extra.sh mnist b standard carlini 7687
./run_extra.sh mnist b adversarial carlini 7687
./run_extra.sh mnist b relu carlini 7687
./run_extra.sh mnist c standard carlini 7687
./run_extra.sh mnist c adversarial carlini 7687
./run_extra.sh mnist c relu carlini 7687
./run_extra.sh mnist a standard carlini 319
./run_extra.sh mnist a adversarial carlini 319
./run_extra.sh mnist a relu carlini 319
./run_extra.sh mnist b standard carlini 319
./run_extra.sh mnist b adversarial carlini 319
./run_extra.sh mnist b relu carlini 319
./run_extra.sh mnist c standard carlini 319
./run_extra.sh mnist c adversarial carlini 319
./run_extra.sh mnist c relu carlini 319
./run_extra.sh mnist a standard carlini 5042
./run_extra.sh mnist a adversarial carlini 5042
./run_extra.sh mnist a relu carlini 5042
./run_extra.sh mnist b standard carlini 5042
./run_extra.sh mnist b adversarial carlini 5042
./run_extra.sh mnist b relu carlini 5042
./run_extra.sh mnist c standard carlini 5042
./run_extra.sh mnist c adversarial carlini 5042
./run_extra.sh mnist c relu carlini 5042
./run_extra.sh mnist a standard carlini 6742
./run_extra.sh mnist a adversarial carlini 6742
./run_extra.sh mnist a relu carlini 6742
./run_extra.sh mnist b standard carlini 6742
./run_extra.sh mnist b adversarial carlini 6742
./run_extra.sh mnist b relu carlini 6742
./run_extra.sh mnist c standard carlini 6742
./run_extra.sh mnist c adversarial carlini 6742
./run_extra.sh mnist c relu carlini 6742
./run_extra.sh mnist a standard carlini 2968
./run_extra.sh mnist a adversarial carlini 2968
./run_extra.sh mnist a relu carlini 2968
./run_extra.sh mnist b standard carlini 2968
./run_extra.sh mnist b adversarial carlini 2968
./run_extra.sh mnist b relu carlini 2968
./run_extra.sh mnist c standard carlini 2968
./run_extra.sh mnist c adversarial carlini 2968
./run_extra.sh mnist c relu carlini 2968
./run_extra.sh mnist a standard carlini 7501
./run_extra.sh mnist a adversarial carlini 7501
./run_extra.sh mnist a relu carlini 7501
./run_extra.sh mnist b standard carlini 7501
./run_extra.sh mnist b adversarial carlini 7501
./run_extra.sh mnist b relu carlini 7501
./run_extra.sh mnist c standard carlini 7501
./run_extra.sh mnist c adversarial carlini 7501
./run_extra.sh mnist c relu carlini 7501
./run_extra.sh mnist a standard carlini 6506
./run_extra.sh mnist a adversarial carlini 6506
./run_extra.sh mnist a relu carlini 6506
./run_extra.sh mnist b standard carlini 6506
./run_extra.sh mnist b adversarial carlini 6506
./run_extra.sh mnist b relu carlini 6506
./run_extra.sh mnist c standard carlini 6506
./run_extra.sh mnist c adversarial carlini 6506
./run_extra.sh mnist c relu carlini 6506
./run_extra.sh mnist a standard carlini 917
./run_extra.sh mnist a adversarial carlini 917
./run_extra.sh mnist a relu carlini 917
./run_extra.sh mnist b standard carlini 917
./run_extra.sh mnist b adversarial carlini 917
./run_extra.sh mnist b relu carlini 917
./run_extra.sh mnist c standard carlini 917
./run_extra.sh mnist c adversarial carlini 917
./run_extra.sh mnist c relu carlini 917
./run_extra.sh mnist a standard carlini 5551
./run_extra.sh mnist a adversarial carlini 5551
./run_extra.sh mnist a relu carlini 5551
./run_extra.sh mnist b standard carlini 5551
./run_extra.sh mnist b adversarial carlini 5551
./run_extra.sh mnist b relu carlini 5551
./run_extra.sh mnist c standard carlini 5551
./run_extra.sh mnist c adversarial carlini 5551
./run_extra.sh mnist c relu carlini 5551
./run_extra.sh mnist a standard carlini 6107
./run_extra.sh mnist a adversarial carlini 6107
./run_extra.sh mnist a relu carlini 6107
./run_extra.sh mnist b standard carlini 6107
./run_extra.sh mnist b adversarial carlini 6107
./run_extra.sh mnist b relu carlini 6107
./run_extra.sh mnist c standard carlini 6107
./run_extra.sh mnist c adversarial carlini 6107
./run_extra.sh mnist c relu carlini 6107
./run_extra.sh mnist a standard carlini 5612
./run_extra.sh mnist a adversarial carlini 5612
./run_extra.sh mnist a relu carlini 5612
./run_extra.sh mnist b standard carlini 5612
./run_extra.sh mnist b adversarial carlini 5612
./run_extra.sh mnist b relu carlini 5612
./run_extra.sh mnist c standard carlini 5612
./run_extra.sh mnist c adversarial carlini 5612
./run_extra.sh mnist c relu carlini 5612
./run_extra.sh mnist a standard carlini 362
./run_extra.sh mnist a adversarial carlini 362
./run_extra.sh mnist a relu carlini 362
./run_extra.sh mnist b standard carlini 362
./run_extra.sh mnist b adversarial carlini 362
./run_extra.sh mnist b relu carlini 362
./run_extra.sh mnist c standard carlini 362
./run_extra.sh mnist c adversarial carlini 362
./run_extra.sh mnist c relu carlini 362
./run_extra.sh mnist a standard carlini 4940
./run_extra.sh mnist a adversarial carlini 4940
./run_extra.sh mnist a relu carlini 4940
./run_extra.sh mnist b standard carlini 4940
./run_extra.sh mnist b adversarial carlini 4940
./run_extra.sh mnist b relu carlini 4940
./run_extra.sh mnist c standard carlini 4940
./run_extra.sh mnist c adversarial carlini 4940
./run_extra.sh mnist c relu carlini 4940
./run_extra.sh mnist a standard carlini 4656
./run_extra.sh mnist a adversarial carlini 4656
./run_extra.sh mnist a relu carlini 4656
./run_extra.sh mnist b standard carlini 4656
./run_extra.sh mnist b adversarial carlini 4656
./run_extra.sh mnist b relu carlini 4656
./run_extra.sh mnist c standard carlini 4656
./run_extra.sh mnist c adversarial carlini 4656
./run_extra.sh mnist c relu carlini 4656
./run_extra.sh mnist a standard carlini 4674
./run_extra.sh mnist a adversarial carlini 4674
./run_extra.sh mnist a relu carlini 4674
./run_extra.sh mnist b standard carlini 4674
./run_extra.sh mnist b adversarial carlini 4674
./run_extra.sh mnist b relu carlini 4674
./run_extra.sh mnist c standard carlini 4674
./run_extra.sh mnist c adversarial carlini 4674
./run_extra.sh mnist c relu carlini 4674
./run_extra.sh mnist a standard carlini 8101
./run_extra.sh mnist a adversarial carlini 8101
./run_extra.sh mnist a relu carlini 8101
./run_extra.sh mnist b standard carlini 8101
./run_extra.sh mnist b adversarial carlini 8101
./run_extra.sh mnist b relu carlini 8101
./run_extra.sh mnist c standard carlini 8101
./run_extra.sh mnist c adversarial carlini 8101
./run_extra.sh mnist c relu carlini 8101
./run_extra.sh mnist a standard carlini 8131
./run_extra.sh mnist a adversarial carlini 8131
./run_extra.sh mnist a relu carlini 8131
./run_extra.sh mnist b standard carlini 8131
./run_extra.sh mnist b adversarial carlini 8131
./run_extra.sh mnist b relu carlini 8131
./run_extra.sh mnist c standard carlini 8131
./run_extra.sh mnist c adversarial carlini 8131
./run_extra.sh mnist c relu carlini 8131
./run_extra.sh mnist a standard carlini 596
./run_extra.sh mnist a adversarial carlini 596
./run_extra.sh mnist a relu carlini 596
./run_extra.sh mnist b standard carlini 596
./run_extra.sh mnist b adversarial carlini 596
./run_extra.sh mnist b relu carlini 596
./run_extra.sh mnist c standard carlini 596
./run_extra.sh mnist c adversarial carlini 596
./run_extra.sh mnist c relu carlini 596
./run_extra.sh mnist a standard carlini 2985
./run_extra.sh mnist a adversarial carlini 2985
./run_extra.sh mnist a relu carlini 2985
./run_extra.sh mnist b standard carlini 2985
./run_extra.sh mnist b adversarial carlini 2985
./run_extra.sh mnist b relu carlini 2985
./run_extra.sh mnist c standard carlini 2985
./run_extra.sh mnist c adversarial carlini 2985
./run_extra.sh mnist c relu carlini 2985
./run_extra.sh mnist a standard carlini 4825
./run_extra.sh mnist a adversarial carlini 4825
./run_extra.sh mnist a relu carlini 4825
./run_extra.sh mnist b standard carlini 4825
./run_extra.sh mnist b adversarial carlini 4825
./run_extra.sh mnist b relu carlini 4825
./run_extra.sh mnist c standard carlini 4825
./run_extra.sh mnist c adversarial carlini 4825
./run_extra.sh mnist c relu carlini 4825
./run_extra.sh mnist a standard carlini 5353
./run_extra.sh mnist a adversarial carlini 5353
./run_extra.sh mnist a relu carlini 5353
./run_extra.sh mnist b standard carlini 5353
./run_extra.sh mnist b adversarial carlini 5353
./run_extra.sh mnist b relu carlini 5353
./run_extra.sh mnist c standard carlini 5353
./run_extra.sh mnist c adversarial carlini 5353
./run_extra.sh mnist c relu carlini 5353
./run_extra.sh mnist a standard carlini 9940
./run_extra.sh mnist a adversarial carlini 9940
./run_extra.sh mnist a relu carlini 9940
./run_extra.sh mnist b standard carlini 9940
./run_extra.sh mnist b adversarial carlini 9940
./run_extra.sh mnist b relu carlini 9940
./run_extra.sh mnist c standard carlini 9940
./run_extra.sh mnist c adversarial carlini 9940
./run_extra.sh mnist c relu carlini 9940
./run_extra.sh mnist a standard carlini 3363
./run_extra.sh mnist a adversarial carlini 3363
./run_extra.sh mnist a relu carlini 3363
./run_extra.sh mnist b standard carlini 3363
./run_extra.sh mnist b adversarial carlini 3363
./run_extra.sh mnist b relu carlini 3363
./run_extra.sh mnist c standard carlini 3363
./run_extra.sh mnist c adversarial carlini 3363
./run_extra.sh mnist c relu carlini 3363
./run_extra.sh mnist a standard carlini 290
./run_extra.sh mnist a adversarial carlini 290
./run_extra.sh mnist a relu carlini 290
