./run_extra.sh mnist c adversarial carlini 5418
./run_extra.sh mnist c relu carlini 5418
./run_extra.sh mnist a standard carlini 3857
./run_extra.sh mnist a adversarial carlini 3857
./run_extra.sh mnist a relu carlini 3857
./run_extra.sh mnist b standard carlini 3857
./run_extra.sh mnist b adversarial carlini 3857
./run_extra.sh mnist b relu carlini 3857
./run_extra.sh mnist c standard carlini 3857
./run_extra.sh mnist c adversarial carlini 3857
./run_extra.sh mnist c relu carlini 3857
./run_extra.sh mnist a standard carlini 9933
./run_extra.sh mnist a adversarial carlini 9933
./run_extra.sh mnist a relu carlini 9933
./run_extra.sh mnist b standard carlini 9933
./run_extra.sh mnist b adversarial carlini 9933
./run_extra.sh mnist b relu carlini 9933
./run_extra.sh mnist c standard carlini 9933
./run_extra.sh mnist c adversarial carlini 9933
./run_extra.sh mnist c relu carlini 9933
./run_extra.sh mnist a standard carlini 3050
./run_extra.sh mnist a adversarial carlini 3050
./run_extra.sh mnist a relu carlini 3050
./run_extra.sh mnist b standard carlini 3050
./run_extra.sh mnist b adversarial carlini 3050
./run_extra.sh mnist b relu carlini 3050
./run_extra.sh mnist c standard carlini 3050
./run_extra.sh mnist c adversarial carlini 3050
./run_extra.sh mnist c relu carlini 3050
./run_extra.sh mnist a standard carlini 3128
./run_extra.sh mnist a adversarial carlini 3128
./run_extra.sh mnist a relu carlini 3128
./run_extra.sh mnist b standard carlini 3128
./run_extra.sh mnist b adversarial carlini 3128
./run_extra.sh mnist b relu carlini 3128
./run_extra.sh mnist c standard carlini 3128
./run_extra.sh mnist c adversarial carlini 3128
./run_extra.sh mnist c relu carlini 3128
./run_extra.sh mnist a standard carlini 7299
./run_extra.sh mnist a adversarial carlini 7299
./run_extra.sh mnist a relu carlini 7299
./run_extra.sh mnist b standard carlini 7299
./run_extra.sh mnist b adversarial carlini 7299
./run_extra.sh mnist b relu carlini 7299
./run_extra.sh mnist c standard carlini 7299
./run_extra.sh mnist c adversarial carlini 7299
./run_extra.sh mnist c relu carlini 7299
./run_extra.sh mnist a standard carlini 1643
./run_extra.sh mnist a adversarial carlini 1643
./run_extra.sh mnist a relu carlini 1643
./run_extra.sh mnist b standard carlini 1643
./run_extra.sh mnist b adversarial carlini 1643
./run_extra.sh mnist b relu carlini 1643
./run_extra.sh mnist c standard carlini 1643
./run_extra.sh mnist c adversarial carlini 1643
./run_extra.sh mnist c relu carlini 1643
./run_extra.sh mnist a standard carlini 2429
./run_extra.sh mnist a adversarial carlini 2429
./run_extra.sh mnist a relu carlini 2429
./run_extra.sh mnist b standard carlini 2429
./run_extra.sh mnist b adversarial carlini 2429
./run_extra.sh mnist b relu carlini 2429
./run_extra.sh mnist c standard carlini 2429
./run_extra.sh mnist c adversarial carlini 2429
./run_extra.sh mnist c relu carlini 2429
./run_extra.sh mnist a standard carlini 3768
./run_extra.sh mnist a adversarial carlini 3768
./run_extra.sh mnist a relu carlini 3768
./run_extra.sh mnist b standard carlini 3768
./run_extra.sh mnist b adversarial carlini 3768
./run_extra.sh mnist b relu carlini 3768
./run_extra.sh mnist c standard carlini 3768
./run_extra.sh mnist c adversarial carlini 3768
./run_extra.sh mnist c relu carlini 3768
./run_extra.sh mnist a standard carlini 7732
./run_extra.sh mnist a adversarial carlini 7732
./run_extra.sh mnist a relu carlini 7732
./run_extra.sh mnist b standard carlini 7732
./run_extra.sh mnist b adversarial carlini 7732
./run_extra.sh mnist b relu carlini 7732
./run_extra.sh mnist c standard carlini 7732
./run_extra.sh mnist c adversarial carlini 7732
./run_extra.sh mnist c relu carlini 7732
./run_extra.sh mnist a standard carlini 370
./run_extra.sh mnist a adversarial carlini 370
./run_extra.sh mnist a relu carlini 370
./run_extra.sh mnist b standard carlini 370
./run_extra.sh mnist b adversarial carlini 370
./run_extra.sh mnist b relu carlini 370
./run_extra.sh mnist c standard carlini 370
./run_extra.sh mnist c adversarial carlini 370
./run_extra.sh mnist c relu carlini 370
./run_extra.sh mnist a standard carlini 5388
./run_extra.sh mnist a adversarial carlini 5388
./run_extra.sh mnist a relu carlini 5388
./run_extra.sh mnist b standard carlini 5388
./run_extra.sh mnist b adversarial carlini 5388
./run_extra.sh mnist b relu carlini 5388
./run_extra.sh mnist c standard carlini 5388
./run_extra.sh mnist c adversarial carlini 5388
./run_extra.sh mnist c relu carlini 5388
./run_extra.sh mnist a standard carlini 341
./run_extra.sh mnist a adversarial carlini 341
./run_extra.sh mnist a relu carlini 341
./run_extra.sh mnist b standard carlini 341
./run_extra.sh mnist b adversarial carlini 341
./run_extra.sh mnist b relu carlini 341
./run_extra.sh mnist c standard carlini 341
./run_extra.sh mnist c adversarial carlini 341
./run_extra.sh mnist c relu carlini 341
./run_extra.sh mnist a standard carlini 3541
./run_extra.sh mnist a adversarial carlini 3541
./run_extra.sh mnist a relu carlini 3541
./run_extra.sh mnist b standard carlini 3541
./run_extra.sh mnist b adversarial carlini 3541
./run_extra.sh mnist b relu carlini 3541
./run_extra.sh mnist c standard carlini 3541
./run_extra.sh mnist c adversarial carlini 3541
./run_extra.sh mnist c relu carlini 3541
./run_extra.sh mnist a standard carlini 8493
./run_extra.sh mnist a adversarial carlini 8493
./run_extra.sh mnist a relu carlini 8493
./run_extra.sh mnist b standard carlini 8493
./run_extra.sh mnist b adversarial carlini 8493
./run_extra.sh mnist b relu carlini 8493
./run_extra.sh mnist c standard carlini 8493
./run_extra.sh mnist c adversarial carlini 8493
./run_extra.sh mnist c relu carlini 8493
./run_extra.sh mnist a standard carlini 9585
./run_extra.sh mnist a adversarial carlini 9585
./run_extra.sh mnist a relu carlini 9585
./run_extra.sh mnist b standard carlini 9585
./run_extra.sh mnist b adversarial carlini 9585
./run_extra.sh mnist b relu carlini 9585
./run_extra.sh mnist c standard carlini 9585
./run_extra.sh mnist c adversarial carlini 9585
./run_extra.sh mnist c relu carlini 9585
./run_extra.sh mnist a standard carlini 4368
./run_extra.sh mnist a adversarial carlini 4368
./run_extra.sh mnist a relu carlini 4368
./run_extra.sh mnist b standard carlini 4368
./run_extra.sh mnist b adversarial carlini 4368
./run_extra.sh mnist b relu carlini 4368
./run_extra.sh mnist c standard carlini 4368
./run_extra.sh mnist c adversarial carlini 4368
./run_extra.sh mnist c relu carlini 4368
./run_extra.sh mnist a standard carlini 4229
./run_extra.sh mnist a adversarial carlini 4229
./run_extra.sh mnist a relu carlini 4229
./run_extra.sh mnist b standard carlini 4229
./run_extra.sh mnist b adversarial carlini 4229
./run_extra.sh mnist b relu carlini 4229
./run_extra.sh mnist c standard carlini 4229
./run_extra.sh mnist c adversarial carlini 4229
./run_extra.sh mnist c relu carlini 4229
./run_extra.sh mnist a standard carlini 555
./run_extra.sh mnist a adversarial carlini 555
./run_extra.sh mnist a relu carlini 555
./run_extra.sh mnist b standard carlini 555
./run_extra.sh mnist b adversarial carlini 555
./run_extra.sh mnist b relu carlini 555
./run_extra.sh mnist c standard carlini 555
./run_extra.sh mnist c adversarial carlini 555
./run_extra.sh mnist c relu carlini 555
./run_extra.sh mnist a standard carlini 5814
./run_extra.sh mnist a adversarial carlini 5814
./run_extra.sh mnist a relu carlini 5814
./run_extra.sh mnist b standard carlini 5814
./run_extra.sh mnist b adversarial carlini 5814
./run_extra.sh mnist b relu carlini 5814
./run_extra.sh mnist c standard carlini 5814
./run_extra.sh mnist c adversarial carlini 5814
./run_extra.sh mnist c relu carlini 5814
./run_extra.sh mnist a standard carlini 6984
./run_extra.sh mnist a adversarial carlini 6984
./run_extra.sh mnist a relu carlini 6984
./run_extra.sh mnist b standard carlini 6984
./run_extra.sh mnist b adversarial carlini 6984
./run_extra.sh mnist b relu carlini 6984
./run_extra.sh mnist c standard carlini 6984
./run_extra.sh mnist c adversarial carlini 6984
./run_extra.sh mnist c relu carlini 6984
./run_extra.sh mnist a standard carlini 1362
./run_extra.sh mnist a adversarial carlini 1362
./run_extra.sh mnist a relu carlini 1362
./run_extra.sh mnist b standard carlini 1362
./run_extra.sh mnist b adversarial carlini 1362
./run_extra.sh mnist b relu carlini 1362
./run_extra.sh mnist c standard carlini 1362
./run_extra.sh mnist c adversarial carlini 1362
./run_extra.sh mnist c relu carlini 1362
./run_extra.sh mnist a standard carlini 5169
./run_extra.sh mnist a adversarial carlini 5169
./run_extra.sh mnist a relu carlini 5169
./run_extra.sh mnist b standard carlini 5169
./run_extra.sh mnist b adversarial carlini 5169
./run_extra.sh mnist b relu carlini 5169
./run_extra.sh mnist c standard carlini 5169
./run_extra.sh mnist c adversarial carlini 5169
./run_extra.sh mnist c relu carlini 5169
./run_extra.sh mnist a standard carlini 7423
./run_extra.sh mnist a adversarial carlini 7423
./run_extra.sh mnist a relu carlini 7423
./run_extra.sh mnist b standard carlini 7423
./run_extra.sh mnist b adversarial carlini 7423
./run_extra.sh mnist b relu carlini 7423
./run_extra.sh mnist c standard carlini 7423
./run_extra.sh mnist c adversarial carlini 7423
./run_extra.sh mnist c relu carlini 7423
./run_extra.sh mnist a standard carlini 4030
./run_extra.sh mnist a adversarial carlini 4030
./run_extra.sh mnist a relu carlini 4030
./run_extra.sh mnist b standard carlini 4030
./run_extra.sh mnist b adversarial carlini 4030
./run_extra.sh mnist b relu carlini 4030
./run_extra.sh mnist c standard carlini 4030
./run_extra.sh mnist c adversarial carlini 4030
./run_extra.sh mnist c relu carlini 4030
./run_extra.sh mnist a standard carlini 5302
./run_extra.sh mnist a adversarial carlini 5302
./run_extra.sh mnist a relu carlini 5302
./run_extra.sh mnist b standard carlini 5302
./run_extra.sh mnist b adversarial carlini 5302
./run_extra.sh mnist b relu carlini 5302
./run_extra.sh mnist c standard carlini 5302
./run_extra.sh mnist c adversarial carlini 5302
./run_extra.sh mnist c relu carlini 5302
./run_extra.sh mnist a standard carlini 1153
./run_extra.sh mnist a adversarial carlini 1153
./run_extra.sh mnist a relu carlini 1153
./run_extra.sh mnist b standard carlini 1153
./run_extra.sh mnist b adversarial carlini 1153
./run_extra.sh mnist b relu carlini 1153
./run_extra.sh mnist c standard carlini 1153
./run_extra.sh mnist c adversarial carlini 1153
./run_extra.sh mnist c relu carlini 1153
./run_extra.sh mnist a standard carlini 2183
./run_extra.sh mnist a adversarial carlini 2183
./run_extra.sh mnist a relu carlini 2183
./run_extra.sh mnist b standard carlini 2183
./run_extra.sh mnist b adversarial carlini 2183
./run_extra.sh mnist b relu carlini 2183
./run_extra.sh mnist c standard carlini 2183
./run_extra.sh mnist c adversarial carlini 2183
./run_extra.sh mnist c relu carlini 2183
./run_extra.sh mnist a standard carlini 8498
./run_extra.sh mnist a adversarial carlini 8498
./run_extra.sh mnist a relu carlini 8498
./run_extra.sh mnist b standard carlini 8498
./run_extra.sh mnist b adversarial carlini 8498
./run_extra.sh mnist b relu carlini 8498
./run_extra.sh mnist c standard carlini 8498
./run_extra.sh mnist c adversarial carlini 8498
./run_extra.sh mnist c relu carlini 8498
./run_extra.sh mnist a standard carlini 8048
./run_extra.sh mnist a adversarial carlini 8048
./run_extra.sh mnist a relu carlini 8048
./run_extra.sh mnist b standard carlini 8048
./run_extra.sh mnist b adversarial carlini 8048
./run_extra.sh mnist b relu carlini 8048
./run_extra.sh mnist c standard carlini 8048
./run_extra.sh mnist c adversarial carlini 8048
./run_extra.sh mnist c relu carlini 8048
./run_extra.sh mnist a standard carlini 4871
./run_extra.sh mnist a adversarial carlini 4871
./run_extra.sh mnist a relu carlini 4871
./run_extra.sh mnist b standard carlini 4871
./run_extra.sh mnist b adversarial carlini 4871
./run_extra.sh mnist b relu carlini 4871
./run_extra.sh mnist c standard carlini 4871
./run_extra.sh mnist c adversarial carlini 4871
./run_extra.sh mnist c relu carlini 4871
./run_extra.sh mnist a standard carlini 4745
./run_extra.sh mnist a adversarial carlini 4745
./run_extra.sh mnist a relu carlini 4745
./run_extra.sh mnist b standard carlini 4745
./run_extra.sh mnist b adversarial carlini 4745
./run_extra.sh mnist b relu carlini 4745
./run_extra.sh mnist c standard carlini 4745
./run_extra.sh mnist c adversarial carlini 4745
./run_extra.sh mnist c relu carlini 4745
./run_extra.sh mnist a standard carlini 2401
./run_extra.sh mnist a adversarial carlini 2401
./run_extra.sh mnist a relu carlini 2401
./run_extra.sh mnist b standard carlini 2401
./run_extra.sh mnist b adversarial carlini 2401
./run_extra.sh mnist b relu carlini 2401
./run_extra.sh mnist c standard carlini 2401
./run_extra.sh mnist c adversarial carlini 2401
./run_extra.sh mnist c relu carlini 2401
./run_extra.sh mnist a standard carlini 8724
./run_extra.sh mnist a adversarial carlini 8724
./run_extra.sh mnist a relu carlini 8724
./run_extra.sh mnist b standard carlini 8724
./run_extra.sh mnist b adversarial carlini 8724
./run_extra.sh mnist b relu carlini 8724
./run_extra.sh mnist c standard carlini 8724
./run_extra.sh mnist c adversarial carlini 8724
./run_extra.sh mnist c relu carlini 8724
./run_extra.sh mnist a standard carlini 8662
./run_extra.sh mnist a adversarial carlini 8662
./run_extra.sh mnist a relu carlini 8662
./run_extra.sh mnist b standard carlini 8662
./run_extra.sh mnist b adversarial carlini 8662
./run_extra.sh mnist b relu carlini 8662
./run_extra.sh mnist c standard carlini 8662
./run_extra.sh mnist c adversarial carlini 8662
./run_extra.sh mnist c relu carlini 8662
./run_extra.sh mnist a standard carlini 1640
./run_extra.sh mnist a adversarial carlini 1640
./run_extra.sh mnist a relu carlini 1640
./run_extra.sh mnist b standard carlini 1640
./run_extra.sh mnist b adversarial carlini 1640
./run_extra.sh mnist b relu carlini 1640
./run_extra.sh mnist c standard carlini 1640
./run_extra.sh mnist c adversarial carlini 1640
./run_extra.sh mnist c relu carlini 1640
./run_extra.sh mnist a standard carlini 7918
./run_extra.sh mnist a adversarial carlini 7918
./run_extra.sh mnist a relu carlini 7918
./run_extra.sh mnist b standard carlini 7918
./run_extra.sh mnist b adversarial carlini 7918
./run_extra.sh mnist b relu carlini 7918
./run_extra.sh mnist c standard carlini 7918
./run_extra.sh mnist c adversarial carlini 7918
./run_extra.sh mnist c relu carlini 7918
./run_extra.sh mnist a standard carlini 1395
./run_extra.sh mnist a adversarial carlini 1395
./run_extra.sh mnist a relu carlini 1395
./run_extra.sh mnist b standard carlini 1395
./run_extra.sh mnist b adversarial carlini 1395
./run_extra.sh mnist b relu carlini 1395
./run_extra.sh mnist c standard carlini 1395
./run_extra.sh mnist c adversarial carlini 1395
./run_extra.sh mnist c relu carlini 1395
./run_extra.sh mnist a standard carlini 6222
./run_extra.sh mnist a adversarial carlini 6222
./run_extra.sh mnist a relu carlini 6222
./run_extra.sh mnist b standard carlini 6222
./run_extra.sh mnist b adversarial carlini 6222
./run_extra.sh mnist b relu carlini 6222
./run_extra.sh mnist c standard carlini 6222
./run_extra.sh mnist c adversarial carlini 6222
./run_extra.sh mnist c relu carlini 6222
./run_extra.sh mnist a standard carlini 2770
./run_extra.sh mnist a adversarial carlini 2770
./run_extra.sh mnist a relu carlini 2770
./run_extra.sh mnist b standard carlini 2770
./run_extra.sh mnist b adversarial carlini 2770
./run_extra.sh mnist b relu carlini 2770
./run_extra.sh mnist c standard carlini 2770
./run_extra.sh mnist c adversarial carlini 2770
./run_extra.sh mnist c relu carlini 2770
./run_extra.sh mnist a standard carlini 393
./run_extra.sh mnist a adversarial carlini 393
./run_extra.sh mnist a relu carlini 393
./run_extra.sh mnist b standard carlini 393
./run_extra.sh mnist b adversarial carlini 393
./run_extra.sh mnist b relu carlini 393
./run_extra.sh mnist c standard carlini 393
./run_extra.sh mnist c adversarial carlini 393
./run_extra.sh mnist c relu carlini 393
./run_extra.sh mnist a standard carlini 3893
./run_extra.sh mnist a adversarial carlini 3893
./run_extra.sh mnist a relu carlini 3893
./run_extra.sh mnist b standard carlini 3893
./run_extra.sh mnist b adversarial carlini 3893
./run_extra.sh mnist b relu carlini 3893
./run_extra.sh mnist c standard carlini 3893
./run_extra.sh mnist c adversarial carlini 3893
./run_extra.sh mnist c relu carlini 3893
./run_extra.sh mnist a standard carlini 8967
./run_extra.sh mnist a adversarial carlini 8967
./run_extra.sh mnist a relu carlini 8967
./run_extra.sh mnist b standard carlini 8967
./run_extra.sh mnist b adversarial carlini 8967
./run_extra.sh mnist b relu carlini 8967
./run_extra.sh mnist c standard carlini 8967
./run_extra.sh mnist c adversarial carlini 8967
./run_extra.sh mnist c relu carlini 8967
./run_extra.sh mnist a standard carlini 7657
./run_extra.sh mnist a adversarial carlini 7657
./run_extra.sh mnist a relu carlini 7657
./run_extra.sh mnist b standard carlini 7657
./run_extra.sh mnist b adversarial carlini 7657
./run_extra.sh mnist b relu carlini 7657
./run_extra.sh mnist c standard carlini 7657
./run_extra.sh mnist c adversarial carlini 7657
./run_extra.sh mnist c relu carlini 7657
./run_extra.sh mnist a standard carlini 4743
./run_extra.sh mnist a adversarial carlini 4743
./run_extra.sh mnist a relu carlini 4743
./run_extra.sh mnist b standard carlini 4743
./run_extra.sh mnist b adversarial carlini 4743
./run_extra.sh mnist b relu carlini 4743
./run_extra.sh mnist c standard carlini 4743
./run_extra.sh mnist c adversarial carlini 4743
./run_extra.sh mnist c relu carlini 4743
./run_extra.sh mnist a standard carlini 2636
./run_extra.sh mnist a adversarial carlini 2636
./run_extra.sh mnist a relu carlini 2636
./run_extra.sh mnist b standard carlini 2636
./run_extra.sh mnist b adversarial carlini 2636
./run_extra.sh mnist b relu carlini 2636
./run_extra.sh mnist c standard carlini 2636
./run_extra.sh mnist c adversarial carlini 2636
./run_extra.sh mnist c relu carlini 2636
./run_extra.sh mnist a standard carlini 2247
./run_extra.sh mnist a adversarial carlini 2247
./run_extra.sh mnist a relu carlini 2247
./run_extra.sh mnist b standard carlini 2247
./run_extra.sh mnist b adversarial carlini 2247
./run_extra.sh mnist b relu carlini 2247
./run_extra.sh mnist c standard carlini 2247
./run_extra.sh mnist c adversarial carlini 2247
./run_extra.sh mnist c relu carlini 2247
./run_extra.sh mnist a standard carlini 5874
./run_extra.sh mnist a adversarial carlini 5874
./run_extra.sh mnist a relu carlini 5874
./run_extra.sh mnist b standard carlini 5874
./run_extra.sh mnist b adversarial carlini 5874
./run_extra.sh mnist b relu carlini 5874
./run_extra.sh mnist c standard carlini 5874
./run_extra.sh mnist c adversarial carlini 5874
./run_extra.sh mnist c relu carlini 5874
./run_extra.sh mnist a standard carlini 3724
./run_extra.sh mnist a adversarial carlini 3724
./run_extra.sh mnist a relu carlini 3724
./run_extra.sh mnist b standard carlini 3724
./run_extra.sh mnist b adversarial carlini 3724
./run_extra.sh mnist b relu carlini 3724
./run_extra.sh mnist c standard carlini 3724
./run_extra.sh mnist c adversarial carlini 3724
./run_extra.sh mnist c relu carlini 3724
./run_extra.sh mnist a standard carlini 3755
./run_extra.sh mnist a adversarial carlini 3755
./run_extra.sh mnist a relu carlini 3755
./run_extra.sh mnist b standard carlini 3755
./run_extra.sh mnist b adversarial carlini 3755
./run_extra.sh mnist b relu carlini 3755
./run_extra.sh mnist c standard carlini 3755
./run_extra.sh mnist c adversarial carlini 3755
./run_extra.sh mnist c relu carlini 3755
./run_extra.sh mnist a standard carlini 7103
./run_extra.sh mnist a adversarial carlini 7103
./run_extra.sh mnist a relu carlini 7103
./run_extra.sh mnist b standard carlini 7103
./run_extra.sh mnist b adversarial carlini 7103
./run_extra.sh mnist b relu carlini 7103
./run_extra.sh mnist c standard carlini 7103
./run_extra.sh mnist c adversarial carlini 7103
./run_extra.sh mnist c relu carlini 7103
./run_extra.sh mnist a standard carlini 9825
./run_extra.sh mnist a adversarial carlini 9825
./run_extra.sh mnist a relu carlini 9825
./run_extra.sh mnist b standard carlini 9825
./run_extra.sh mnist b adversarial carlini 9825
./run_extra.sh mnist b relu carlini 9825
./run_extra.sh mnist c standard carlini 9825
./run_extra.sh mnist c adversarial carlini 9825
./run_extra.sh mnist c relu carlini 9825
./run_extra.sh mnist a standard carlini 5988
./run_extra.sh mnist a adversarial carlini 5988
./run_extra.sh mnist a relu carlini 5988
./run_extra.sh mnist b standard carlini 5988
./run_extra.sh mnist b adversarial carlini 5988
./run_extra.sh mnist b relu carlini 5988
./run_extra.sh mnist c standard carlini 5988
./run_extra.sh mnist c adversarial carlini 5988
./run_extra.sh mnist c relu carlini 5988
./run_extra.sh mnist a standard carlini 8098
./run_extra.sh mnist a adversarial carlini 8098
./run_extra.sh mnist a relu carlini 8098
./run_extra.sh mnist b standard carlini 8098
./run_extra.sh mnist b adversarial carlini 8098
./run_extra.sh mnist b relu carlini 8098
./run_extra.sh mnist c standard carlini 8098
./run_extra.sh mnist c adversarial carlini 8098
./run_extra.sh mnist c relu carlini 8098
./run_extra.sh mnist a standard carlini 9578
./run_extra.sh mnist a adversarial carlini 9578
./run_extra.sh mnist a relu carlini 9578
./run_extra.sh mnist b standard carlini 9578
./run_extra.sh mnist b adversarial carlini 9578
./run_extra.sh mnist b relu carlini 9578
./run_extra.sh mnist c standard carlini 9578
./run_extra.sh mnist c adversarial carlini 9578
./run_extra.sh mnist c relu carlini 9578
./run_extra.sh mnist a standard carlini 1084
./run_extra.sh mnist a adversarial carlini 1084
./run_extra.sh mnist a relu carlini 1084
./run_extra.sh mnist b standard carlini 1084
./run_extra.sh mnist b adversarial carlini 1084
./run_extra.sh mnist b relu carlini 1084
./run_extra.sh mnist c standard carlini 1084
./run_extra.sh mnist c adversarial carlini 1084
./run_extra.sh mnist c relu carlini 1084
./run_extra.sh mnist a standard carlini 2041
./run_extra.sh mnist a adversarial carlini 2041
./run_extra.sh mnist a relu carlini 2041
./run_extra.sh mnist b standard carlini 2041
./run_extra.sh mnist b adversarial carlini 2041
./run_extra.sh mnist b relu carlini 2041
./run_extra.sh mnist c standard carlini 2041
./run_extra.sh mnist c adversarial carlini 2041
./run_extra.sh mnist c relu carlini 2041
./run_extra.sh mnist a standard carlini 1571
./run_extra.sh mnist a adversarial carlini 1571
./run_extra.sh mnist a relu carlini 1571
./run_extra.sh mnist b standard carlini 1571
./run_extra.sh mnist b adversarial carlini 1571
./run_extra.sh mnist b relu carlini 1571
./run_extra.sh mnist c standard carlini 1571
./run_extra.sh mnist c adversarial carlini 1571
./run_extra.sh mnist c relu carlini 1571
./run_extra.sh mnist a standard carlini 7522
./run_extra.sh mnist a adversarial carlini 7522
./run_extra.sh mnist a relu carlini 7522
./run_extra.sh mnist b standard carlini 7522
./run_extra.sh mnist b adversarial carlini 7522
./run_extra.sh mnist b relu carlini 7522
./run_extra.sh mnist c standard carlini 7522
./run_extra.sh mnist c adversarial carlini 7522
./run_extra.sh mnist c relu carlini 7522
./run_extra.sh mnist a standard carlini 6420
./run_extra.sh mnist a adversarial carlini 6420
./run_extra.sh mnist a relu carlini 6420
./run_extra.sh mnist b standard carlini 6420
./run_extra.sh mnist b adversarial carlini 6420
./run_extra.sh mnist b relu carlini 6420
./run_extra.sh mnist c standard carlini 6420
./run_extra.sh mnist c adversarial carlini 6420
./run_extra.sh mnist c relu carlini 6420
./run_extra.sh mnist a standard carlini 6734
./run_extra.sh mnist a adversarial carlini 6734
./run_extra.sh mnist a relu carlini 6734
./run_extra.sh mnist b standard carlini 6734
./run_extra.sh mnist b adversarial carlini 6734
./run_extra.sh mnist b relu carlini 6734
./run_extra.sh mnist c standard carlini 6734
./run_extra.sh mnist c adversarial carlini 6734
./run_extra.sh mnist c relu carlini 6734
./run_extra.sh mnist a standard carlini 9637
./run_extra.sh mnist a adversarial carlini 9637
./run_extra.sh mnist a relu carlini 9637
./run_extra.sh mnist b standard carlini 9637
./run_extra.sh mnist b adversarial carlini 9637
./run_extra.sh mnist b relu carlini 9637
./run_extra.sh mnist c standard carlini 9637
./run_extra.sh mnist c adversarial carlini 9637
./run_extra.sh mnist c relu carlini 9637
./run_extra.sh mnist a standard carlini 3749
./run_extra.sh mnist a adversarial carlini 3749
./run_extra.sh mnist a relu carlini 3749
./run_extra.sh mnist b standard carlini 3749
./run_extra.sh mnist b adversarial carlini 3749
./run_extra.sh mnist b relu carlini 3749
./run_extra.sh mnist c standard carlini 3749
./run_extra.sh mnist c adversarial carlini 3749
./run_extra.sh mnist c relu carlini 3749
./run_extra.sh mnist a standard carlini 3095
./run_extra.sh mnist a adversarial carlini 3095
./run_extra.sh mnist a relu carlini 3095
./run_extra.sh mnist b standard carlini 3095
./run_extra.sh mnist b adversarial carlini 3095
./run_extra.sh mnist b relu carlini 3095
./run_extra.sh mnist c standard carlini 3095
./run_extra.sh mnist c adversarial carlini 3095
./run_extra.sh mnist c relu carlini 3095
./run_extra.sh mnist a standard carlini 8863
./run_extra.sh mnist a adversarial carlini 8863
./run_extra.sh mnist a relu carlini 8863
./run_extra.sh mnist b standard carlini 8863
./run_extra.sh mnist b adversarial carlini 8863
./run_extra.sh mnist b relu carlini 8863
./run_extra.sh mnist c standard carlini 8863
./run_extra.sh mnist c adversarial carlini 8863
./run_extra.sh mnist c relu carlini 8863
./run_extra.sh mnist a standard carlini 5685
./run_extra.sh mnist a adversarial carlini 5685
./run_extra.sh mnist a relu carlini 5685
./run_extra.sh mnist b standard carlini 5685
./run_extra.sh mnist b adversarial carlini 5685
./run_extra.sh mnist b relu carlini 5685
./run_extra.sh mnist c standard carlini 5685
./run_extra.sh mnist c adversarial carlini 5685
./run_extra.sh mnist c relu carlini 5685
./run_extra.sh mnist a standard carlini 5094
./run_extra.sh mnist a adversarial carlini 5094
./run_extra.sh mnist a relu carlini 5094
./run_extra.sh mnist b standard carlini 5094
./run_extra.sh mnist b adversarial carlini 5094
./run_extra.sh mnist b relu carlini 5094
./run_extra.sh mnist c standard carlini 5094
./run_extra.sh mnist c adversarial carlini 5094
./run_extra.sh mnist c relu carlini 5094
./run_extra.sh mnist a standard carlini 2618
./run_extra.sh mnist a adversarial carlini 2618
./run_extra.sh mnist a relu carlini 2618
./run_extra.sh mnist b standard carlini 2618
./run_extra.sh mnist b adversarial carlini 2618
./run_extra.sh mnist b relu carlini 2618
./run_extra.sh mnist c standard carlini 2618
./run_extra.sh mnist c adversarial carlini 2618
./run_extra.sh mnist c relu carlini 2618
./run_extra.sh mnist a standard carlini 8102
./run_extra.sh mnist a adversarial carlini 8102
./run_extra.sh mnist a relu carlini 8102
./run_extra.sh mnist b standard carlini 8102
./run_extra.sh mnist b adversarial carlini 8102
./run_extra.sh mnist b relu carlini 8102
./run_extra.sh mnist c standard carlini 8102
./run_extra.sh mnist c adversarial carlini 8102
./run_extra.sh mnist c relu carlini 8102
./run_extra.sh mnist a standard carlini 8903
./run_extra.sh mnist a adversarial carlini 8903
./run_extra.sh mnist a relu carlini 8903
./run_extra.sh mnist b standard carlini 8903
./run_extra.sh mnist b adversarial carlini 8903
./run_extra.sh mnist b relu carlini 8903
./run_extra.sh mnist c standard carlini 8903
./run_extra.sh mnist c adversarial carlini 8903
./run_extra.sh mnist c relu carlini 8903
./run_extra.sh mnist a standard carlini 8467
./run_extra.sh mnist a adversarial carlini 8467
./run_extra.sh mnist a relu carlini 8467
./run_extra.sh mnist b standard carlini 8467
./run_extra.sh mnist b adversarial carlini 8467
./run_extra.sh mnist b relu carlini 8467
./run_extra.sh mnist c standard carlini 8467
./run_extra.sh mnist c adversarial carlini 8467
./run_extra.sh mnist c relu carlini 8467
./run_extra.sh mnist a standard carlini 280
./run_extra.sh mnist a adversarial carlini 280
./run_extra.sh mnist a relu carlini 280
./run_extra.sh mnist b standard carlini 280
./run_extra.sh mnist b adversarial carlini 280
./run_extra.sh mnist b relu carlini 280
./run_extra.sh mnist c standard carlini 280
./run_extra.sh mnist c adversarial carlini 280
./run_extra.sh mnist c relu carlini 280
./run_extra.sh mnist a standard carlini 936
./run_extra.sh mnist a adversarial carlini 936
./run_extra.sh mnist a relu carlini 936
./run_extra.sh mnist b standard carlini 936
./run_extra.sh mnist b adversarial carlini 936
./run_extra.sh mnist b relu carlini 936
./run_extra.sh mnist c standard carlini 936
./run_extra.sh mnist c adversarial carlini 936
./run_extra.sh mnist c relu carlini 936
./run_extra.sh mnist a standard carlini 487
./run_extra.sh mnist a adversarial carlini 487
./run_extra.sh mnist a relu carlini 487
./run_extra.sh mnist b standard carlini 487
./run_extra.sh mnist b adversarial carlini 487
./run_extra.sh mnist b relu carlini 487
./run_extra.sh mnist c standard carlini 487
./run_extra.sh mnist c adversarial carlini 487
./run_extra.sh mnist c relu carlini 487
./run_extra.sh mnist a standard carlini 8435
./run_extra.sh mnist a adversarial carlini 8435
./run_extra.sh mnist a relu carlini 8435
./run_extra.sh mnist b standard carlini 8435
./run_extra.sh mnist b adversarial carlini 8435
./run_extra.sh mnist b relu carlini 8435
./run_extra.sh mnist c standard carlini 8435
./run_extra.sh mnist c adversarial carlini 8435
./run_extra.sh mnist c relu carlini 8435
./run_extra.sh mnist a standard carlini 9996
./run_extra.sh mnist a adversarial carlini 9996
./run_extra.sh mnist a relu carlini 9996
./run_extra.sh mnist b standard carlini 9996
./run_extra.sh mnist b adversarial carlini 9996
./run_extra.sh mnist b relu carlini 9996
./run_extra.sh mnist c standard carlini 9996
./run_extra.sh mnist c adversarial carlini 9996
./run_extra.sh mnist c relu carlini 9996
./run_extra.sh mnist a standard carlini 3708
./run_extra.sh mnist a adversarial carlini 3708
./run_extra.sh mnist a relu carlini 3708
./run_extra.sh mnist b standard carlini 3708
./run_extra.sh mnist b adversarial carlini 3708
./run_extra.sh mnist b relu carlini 3708
./run_extra.sh mnist c standard carlini 3708
./run_extra.sh mnist c adversarial carlini 3708
./run_extra.sh mnist c relu carlini 3708
./run_extra.sh mnist a standard carlini 2238
./run_extra.sh mnist a adversarial carlini 2238
./run_extra.sh mnist a relu carlini 2238
./run_extra.sh mnist b standard carlini 2238
./run_extra.sh mnist b adversarial carlini 2238
./run_extra.sh mnist b relu carlini 2238
./run_extra.sh mnist c standard carlini 2238
./run_extra.sh mnist c adversarial carlini 2238
./run_extra.sh mnist c relu carlini 2238
./run_extra.sh mnist a standard carlini 9597
./run_extra.sh mnist a adversarial carlini 9597
./run_extra.sh mnist a relu carlini 9597
./run_extra.sh mnist b standard carlini 9597
./run_extra.sh mnist b adversarial carlini 9597
./run_extra.sh mnist b relu carlini 9597
./run_extra.sh mnist c standard carlini 9597
./run_extra.sh mnist c adversarial carlini 9597
./run_extra.sh mnist c relu carlini 9597
./run_extra.sh mnist a standard carlini 2154
./run_extra.sh mnist a adversarial carlini 2154
./run_extra.sh mnist a relu carlini 2154
./run_extra.sh mnist b standard carlini 2154
./run_extra.sh mnist b adversarial carlini 2154
./run_extra.sh mnist b relu carlini 2154
./run_extra.sh mnist c standard carlini 2154
./run_extra.sh mnist c adversarial carlini 2154
./run_extra.sh mnist c relu carlini 2154
./run_extra.sh mnist a standard carlini 2445
./run_extra.sh mnist a adversarial carlini 2445
./run_extra.sh mnist a relu carlini 2445
./run_extra.sh mnist b standard carlini 2445
./run_extra.sh mnist b adversarial carlini 2445
./run_extra.sh mnist b relu carlini 2445
./run_extra.sh mnist c standard carlini 2445
./run_extra.sh mnist c adversarial carlini 2445
./run_extra.sh mnist c relu carlini 2445
./run_extra.sh mnist a standard carlini 696
./run_extra.sh mnist a adversarial carlini 696
./run_extra.sh mnist a relu carlini 696
./run_extra.sh mnist b standard carlini 696
./run_extra.sh mnist b adversarial carlini 696
./run_extra.sh mnist b relu carlini 696
./run_extra.sh mnist c standard carlini 696
./run_extra.sh mnist c adversarial carlini 696
./run_extra.sh mnist c relu carlini 696
./run_extra.sh mnist a standard carlini 2973
./run_extra.sh mnist a adversarial carlini 2973
./run_extra.sh mnist a relu carlini 2973
./run_extra.sh mnist b standard carlini 2973
./run_extra.sh mnist b adversarial carlini 2973
./run_extra.sh mnist b relu carlini 2973
./run_extra.sh mnist c standard carlini 2973
./run_extra.sh mnist c adversarial carlini 2973
./run_extra.sh mnist c relu carlini 2973
./run_extra.sh mnist a standard carlini 9332
./run_extra.sh mnist a adversarial carlini 9332
./run_extra.sh mnist a relu carlini 9332
./run_extra.sh mnist b standard carlini 9332
./run_extra.sh mnist b adversarial carlini 9332
./run_extra.sh mnist b relu carlini 9332
./run_extra.sh mnist c standard carlini 9332
./run_extra.sh mnist c adversarial carlini 9332
./run_extra.sh mnist c relu carlini 9332
./run_extra.sh mnist a standard carlini 1676
./run_extra.sh mnist a adversarial carlini 1676
./run_extra.sh mnist a relu carlini 1676
./run_extra.sh mnist b standard carlini 1676
./run_extra.sh mnist b adversarial carlini 1676
./run_extra.sh mnist b relu carlini 1676
./run_extra.sh mnist c standard carlini 1676
./run_extra.sh mnist c adversarial carlini 1676
./run_extra.sh mnist c relu carlini 1676
./run_extra.sh mnist a standard carlini 5572
./run_extra.sh mnist a adversarial carlini 5572
./run_extra.sh mnist a relu carlini 5572
./run_extra.sh mnist b standard carlini 5572
./run_extra.sh mnist b adversarial carlini 5572
./run_extra.sh mnist b relu carlini 5572
./run_extra.sh mnist c standard carlini 5572
./run_extra.sh mnist c adversarial carlini 5572
./run_extra.sh mnist c relu carlini 5572
./run_extra.sh mnist a standard carlini 3464
./run_extra.sh mnist a adversarial carlini 3464
./run_extra.sh mnist a relu carlini 3464
./run_extra.sh mnist b standard carlini 3464
./run_extra.sh mnist b adversarial carlini 3464
./run_extra.sh mnist b relu carlini 3464
./run_extra.sh mnist c standard carlini 3464
./run_extra.sh mnist c adversarial carlini 3464
./run_extra.sh mnist c relu carlini 3464
./run_extra.sh mnist a standard carlini 1623
./run_extra.sh mnist a adversarial carlini 1623
./run_extra.sh mnist a relu carlini 1623
./run_extra.sh mnist b standard carlini 1623
./run_extra.sh mnist b adversarial carlini 1623
./run_extra.sh mnist b relu carlini 1623
./run_extra.sh mnist c standard carlini 1623
./run_extra.sh mnist c adversarial carlini 1623
./run_extra.sh mnist c relu carlini 1623
./run_extra.sh mnist a standard carlini 5651
./run_extra.sh mnist a adversarial carlini 5651
./run_extra.sh mnist a relu carlini 5651
./run_extra.sh mnist b standard carlini 5651
./run_extra.sh mnist b adversarial carlini 5651
./run_extra.sh mnist b relu carlini 5651
./run_extra.sh mnist c standard carlini 5651
./run_extra.sh mnist c adversarial carlini 5651
./run_extra.sh mnist c relu carlini 5651
./run_extra.sh mnist a standard carlini 9116
./run_extra.sh mnist a adversarial carlini 9116
./run_extra.sh mnist a relu carlini 9116
./run_extra.sh mnist b standard carlini 9116
./run_extra.sh mnist b adversarial carlini 9116
./run_extra.sh mnist b relu carlini 9116
./run_extra.sh mnist c standard carlini 9116
./run_extra.sh mnist c adversarial carlini 9116
./run_extra.sh mnist c relu carlini 9116
./run_extra.sh mnist a standard carlini 6025
./run_extra.sh mnist a adversarial carlini 6025
./run_extra.sh mnist a relu carlini 6025
./run_extra.sh mnist b standard carlini 6025
./run_extra.sh mnist b adversarial carlini 6025
./run_extra.sh mnist b relu carlini 6025
./run_extra.sh mnist c standard carlini 6025
./run_extra.sh mnist c adversarial carlini 6025
./run_extra.sh mnist c relu carlini 6025
./run_extra.sh mnist a standard carlini 3978
./run_extra.sh mnist a adversarial carlini 3978
./run_extra.sh mnist a relu carlini 3978
./run_extra.sh mnist b standard carlini 3978
./run_extra.sh mnist b adversarial carlini 3978
./run_extra.sh mnist b relu carlini 3978
./run_extra.sh mnist c standard carlini 3978
./run_extra.sh mnist c adversarial carlini 3978
./run_extra.sh mnist c relu carlini 3978
./run_extra.sh mnist a standard carlini 4259
./run_extra.sh mnist a adversarial carlini 4259
./run_extra.sh mnist a relu carlini 4259
./run_extra.sh mnist b standard carlini 4259
./run_extra.sh mnist b adversarial carlini 4259
./run_extra.sh mnist b relu carlini 4259
./run_extra.sh mnist c standard carlini 4259
./run_extra.sh mnist c adversarial carlini 4259
./run_extra.sh mnist c relu carlini 4259
./run_extra.sh mnist a standard carlini 266
./run_extra.sh mnist a adversarial carlini 266
./run_extra.sh mnist a relu carlini 266
./run_extra.sh mnist b standard carlini 266
./run_extra.sh mnist b adversarial carlini 266
./run_extra.sh mnist b relu carlini 266
./run_extra.sh mnist c standard carlini 266
./run_extra.sh mnist c adversarial carlini 266
./run_extra.sh mnist c relu carlini 266
./run_extra.sh mnist a standard carlini 4611
./run_extra.sh mnist a adversarial carlini 4611
./run_extra.sh mnist a relu carlini 4611
./run_extra.sh mnist b standard carlini 4611
./run_extra.sh mnist b adversarial carlini 4611
./run_extra.sh mnist b relu carlini 4611
./run_extra.sh mnist c standard carlini 4611
./run_extra.sh mnist c adversarial carlini 4611
./run_extra.sh mnist c relu carlini 4611
./run_extra.sh mnist a standard carlini 7055
./run_extra.sh mnist a adversarial carlini 7055
./run_extra.sh mnist a relu carlini 7055
./run_extra.sh mnist b standard carlini 7055
./run_extra.sh mnist b adversarial carlini 7055
./run_extra.sh mnist b relu carlini 7055
./run_extra.sh mnist c standard carlini 7055
./run_extra.sh mnist c adversarial carlini 7055
./run_extra.sh mnist c relu carlini 7055
./run_extra.sh mnist a standard carlini 7510
./run_extra.sh mnist a adversarial carlini 7510
./run_extra.sh mnist a relu carlini 7510
./run_extra.sh mnist b standard carlini 7510
./run_extra.sh mnist b adversarial carlini 7510
./run_extra.sh mnist b relu carlini 7510
./run_extra.sh mnist c standard carlini 7510
./run_extra.sh mnist c adversarial carlini 7510
./run_extra.sh mnist c relu carlini 7510
./run_extra.sh mnist a standard carlini 1976
./run_extra.sh mnist a adversarial carlini 1976
./run_extra.sh mnist a relu carlini 1976
./run_extra.sh mnist b standard carlini 1976
./run_extra.sh mnist b adversarial carlini 1976
./run_extra.sh mnist b relu carlini 1976
./run_extra.sh mnist c standard carlini 1976
./run_extra.sh mnist c adversarial carlini 1976
./run_extra.sh mnist c relu carlini 1976
./run_extra.sh mnist a standard carlini 3792
./run_extra.sh mnist a adversarial carlini 3792
./run_extra.sh mnist a relu carlini 3792
./run_extra.sh mnist b standard carlini 3792
./run_extra.sh mnist b adversarial carlini 3792
./run_extra.sh mnist b relu carlini 3792
./run_extra.sh mnist c standard carlini 3792
./run_extra.sh mnist c adversarial carlini 3792
./run_extra.sh mnist c relu carlini 3792
./run_extra.sh mnist a standard carlini 2617
./run_extra.sh mnist a adversarial carlini 2617
./run_extra.sh mnist a relu carlini 2617
./run_extra.sh mnist b standard carlini 2617
./run_extra.sh mnist b adversarial carlini 2617
./run_extra.sh mnist b relu carlini 2617
./run_extra.sh mnist c standard carlini 2617
./run_extra.sh mnist c adversarial carlini 2617
./run_extra.sh mnist c relu carlini 2617
./run_extra.sh mnist a standard carlini 877
./run_extra.sh mnist a adversarial carlini 877
./run_extra.sh mnist a relu carlini 877
./run_extra.sh mnist b standard carlini 877
./run_extra.sh mnist b adversarial carlini 877
./run_extra.sh mnist b relu carlini 877
./run_extra.sh mnist c standard carlini 877
./run_extra.sh mnist c adversarial carlini 877
./run_extra.sh mnist c relu carlini 877
./run_extra.sh mnist a standard carlini 3647
./run_extra.sh mnist a adversarial carlini 3647
./run_extra.sh mnist a relu carlini 3647
./run_extra.sh mnist b standard carlini 3647
./run_extra.sh mnist b adversarial carlini 3647
./run_extra.sh mnist b relu carlini 3647
./run_extra.sh mnist c standard carlini 3647
./run_extra.sh mnist c adversarial carlini 3647
./run_extra.sh mnist c relu carlini 3647
./run_extra.sh mnist a standard carlini 6737
./run_extra.sh mnist a adversarial carlini 6737
./run_extra.sh mnist a relu carlini 6737
./run_extra.sh mnist b standard carlini 6737
./run_extra.sh mnist b adversarial carlini 6737
./run_extra.sh mnist b relu carlini 6737
./run_extra.sh mnist c standard carlini 6737
./run_extra.sh mnist c adversarial carlini 6737
./run_extra.sh mnist c relu carlini 6737
./run_extra.sh mnist a standard carlini 7496
./run_extra.sh mnist a adversarial carlini 7496
./run_extra.sh mnist a relu carlini 7496
./run_extra.sh mnist b standard carlini 7496
./run_extra.sh mnist b adversarial carlini 7496
./run_extra.sh mnist b relu carlini 7496
./run_extra.sh mnist c standard carlini 7496
./run_extra.sh mnist c adversarial carlini 7496
./run_extra.sh mnist c relu carlini 7496
./run_extra.sh mnist a standard carlini 5399
./run_extra.sh mnist a adversarial carlini 5399
./run_extra.sh mnist a relu carlini 5399
./run_extra.sh mnist b standard carlini 5399
./run_extra.sh mnist b adversarial carlini 5399
./run_extra.sh mnist b relu carlini 5399
./run_extra.sh mnist c standard carlini 5399
./run_extra.sh mnist c adversarial carlini 5399
./run_extra.sh mnist c relu carlini 5399
./run_extra.sh mnist a standard carlini 1704
./run_extra.sh mnist a adversarial carlini 1704
./run_extra.sh mnist a relu carlini 1704
./run_extra.sh mnist b standard carlini 1704
./run_extra.sh mnist b adversarial carlini 1704
./run_extra.sh mnist b relu carlini 1704
./run_extra.sh mnist c standard carlini 1704
./run_extra.sh mnist c adversarial carlini 1704
./run_extra.sh mnist c relu carlini 1704
./run_extra.sh mnist a standard carlini 7028
./run_extra.sh mnist a adversarial carlini 7028
./run_extra.sh mnist a relu carlini 7028
./run_extra.sh mnist b standard carlini 7028
./run_extra.sh mnist b adversarial carlini 7028
./run_extra.sh mnist b relu carlini 7028
./run_extra.sh mnist c standard carlini 7028
./run_extra.sh mnist c adversarial carlini 7028
./run_extra.sh mnist c relu carlini 7028
./run_extra.sh mnist a standard carlini 1252
./run_extra.sh mnist a adversarial carlini 1252
./run_extra.sh mnist a relu carlini 1252
./run_extra.sh mnist b standard carlini 1252
./run_extra.sh mnist b adversarial carlini 1252
./run_extra.sh mnist b relu carlini 1252
./run_extra.sh mnist c standard carlini 1252
./run_extra.sh mnist c adversarial carlini 1252
./run_extra.sh mnist c relu carlini 1252
./run_extra.sh mnist a standard carlini 3587
./run_extra.sh mnist a adversarial carlini 3587
./run_extra.sh mnist a relu carlini 3587
./run_extra.sh mnist b standard carlini 3587
./run_extra.sh mnist b adversarial carlini 3587
./run_extra.sh mnist b relu carlini 3587
./run_extra.sh mnist c standard carlini 3587
./run_extra.sh mnist c adversarial carlini 3587
./run_extra.sh mnist c relu carlini 3587
./run_extra.sh mnist a standard carlini 8630
./run_extra.sh mnist a adversarial carlini 8630
./run_extra.sh mnist a relu carlini 8630
./run_extra.sh mnist b standard carlini 8630
./run_extra.sh mnist b adversarial carlini 8630
./run_extra.sh mnist b relu carlini 8630
./run_extra.sh mnist c standard carlini 8630
./run_extra.sh mnist c adversarial carlini 8630
./run_extra.sh mnist c relu carlini 8630
./run_extra.sh mnist a standard carlini 316
./run_extra.sh mnist a adversarial carlini 316
./run_extra.sh mnist a relu carlini 316
./run_extra.sh mnist b standard carlini 316
./run_extra.sh mnist b adversarial carlini 316
./run_extra.sh mnist b relu carlini 316
./run_extra.sh mnist c standard carlini 316
./run_extra.sh mnist c adversarial carlini 316
./run_extra.sh mnist c relu carlini 316
./run_extra.sh mnist a standard carlini 5033
./run_extra.sh mnist a adversarial carlini 5033
./run_extra.sh mnist a relu carlini 5033
./run_extra.sh mnist b standard carlini 5033
./run_extra.sh mnist b adversarial carlini 5033
./run_extra.sh mnist b relu carlini 5033
./run_extra.sh mnist c standard carlini 5033
./run_extra.sh mnist c adversarial carlini 5033
./run_extra.sh mnist c relu carlini 5033
./run_extra.sh mnist a standard carlini 1462
./run_extra.sh mnist a adversarial carlini 1462
./run_extra.sh mnist a relu carlini 1462
./run_extra.sh mnist b standard carlini 1462
./run_extra.sh mnist b adversarial carlini 1462
./run_extra.sh mnist b relu carlini 1462
./run_extra.sh mnist c standard carlini 1462
./run_extra.sh mnist c adversarial carlini 1462
./run_extra.sh mnist c relu carlini 1462
./run_extra.sh mnist a standard carlini 7398
./run_extra.sh mnist a adversarial carlini 7398
./run_extra.sh mnist a relu carlini 7398
./run_extra.sh mnist b standard carlini 7398
./run_extra.sh mnist b adversarial carlini 7398
./run_extra.sh mnist b relu carlini 7398
./run_extra.sh mnist c standard carlini 7398
./run_extra.sh mnist c adversarial carlini 7398
./run_extra.sh mnist c relu carlini 7398
./run_extra.sh mnist a standard carlini 8681
./run_extra.sh mnist a adversarial carlini 8681
./run_extra.sh mnist a relu carlini 8681
./run_extra.sh mnist b standard carlini 8681
./run_extra.sh mnist b adversarial carlini 8681
./run_extra.sh mnist b relu carlini 8681
./run_extra.sh mnist c standard carlini 8681
./run_extra.sh mnist c adversarial carlini 8681
./run_extra.sh mnist c relu carlini 8681
./run_extra.sh mnist a standard carlini 3891
./run_extra.sh mnist a adversarial carlini 3891
./run_extra.sh mnist a relu carlini 3891
./run_extra.sh mnist b standard carlini 3891
./run_extra.sh mnist b adversarial carlini 3891
./run_extra.sh mnist b relu carlini 3891
./run_extra.sh mnist c standard carlini 3891
./run_extra.sh mnist c adversarial carlini 3891
./run_extra.sh mnist c relu carlini 3891
./run_extra.sh mnist a standard carlini 4759
./run_extra.sh mnist a adversarial carlini 4759
./run_extra.sh mnist a relu carlini 4759
./run_extra.sh mnist b standard carlini 4759
./run_extra.sh mnist b adversarial carlini 4759
./run_extra.sh mnist b relu carlini 4759
./run_extra.sh mnist c standard carlini 4759
./run_extra.sh mnist c adversarial carlini 4759
./run_extra.sh mnist c relu carlini 4759
./run_extra.sh mnist a standard carlini 1800
./run_extra.sh mnist a adversarial carlini 1800
./run_extra.sh mnist a relu carlini 1800
./run_extra.sh mnist b standard carlini 1800
./run_extra.sh mnist b adversarial carlini 1800
./run_extra.sh mnist b relu carlini 1800
./run_extra.sh mnist c standard carlini 1800
./run_extra.sh mnist c adversarial carlini 1800
./run_extra.sh mnist c relu carlini 1800
./run_extra.sh mnist a standard carlini 4505
./run_extra.sh mnist a adversarial carlini 4505
./run_extra.sh mnist a relu carlini 4505
./run_extra.sh mnist b standard carlini 4505
./run_extra.sh mnist b adversarial carlini 4505
./run_extra.sh mnist b relu carlini 4505
./run_extra.sh mnist c standard carlini 4505
./run_extra.sh mnist c adversarial carlini 4505
./run_extra.sh mnist c relu carlini 4505
./run_extra.sh mnist a standard carlini 9266
./run_extra.sh mnist a adversarial carlini 9266
./run_extra.sh mnist a relu carlini 9266
./run_extra.sh mnist b standard carlini 9266
./run_extra.sh mnist b adversarial carlini 9266
./run_extra.sh mnist b relu carlini 9266
./run_extra.sh mnist c standard carlini 9266
./run_extra.sh mnist c adversarial carlini 9266
./run_extra.sh mnist c relu carlini 9266
./run_extra.sh mnist a standard carlini 4813
./run_extra.sh mnist a adversarial carlini 4813
./run_extra.sh mnist a relu carlini 4813
./run_extra.sh mnist b standard carlini 4813
./run_extra.sh mnist b adversarial carlini 4813
./run_extra.sh mnist b relu carlini 4813
./run_extra.sh mnist c standard carlini 4813
./run_extra.sh mnist c adversarial carlini 4813
./run_extra.sh mnist c relu carlini 4813
./run_extra.sh mnist a standard carlini 2793
./run_extra.sh mnist a adversarial carlini 2793
./run_extra.sh mnist a relu carlini 2793
./run_extra.sh mnist b standard carlini 2793
./run_extra.sh mnist b adversarial carlini 2793
./run_extra.sh mnist b relu carlini 2793
./run_extra.sh mnist c standard carlini 2793
./run_extra.sh mnist c adversarial carlini 2793
./run_extra.sh mnist c relu carlini 2793
./run_extra.sh mnist a standard carlini 3432
./run_extra.sh mnist a adversarial carlini 3432
./run_extra.sh mnist a relu carlini 3432
./run_extra.sh mnist b standard carlini 3432
./run_extra.sh mnist b adversarial carlini 3432
./run_extra.sh mnist b relu carlini 3432
./run_extra.sh mnist c standard carlini 3432
./run_extra.sh mnist c adversarial carlini 3432
./run_extra.sh mnist c relu carlini 3432
./run_extra.sh mnist a standard carlini 5309
./run_extra.sh mnist a adversarial carlini 5309
./run_extra.sh mnist a relu carlini 5309
./run_extra.sh mnist b standard carlini 5309
./run_extra.sh mnist b adversarial carlini 5309
./run_extra.sh mnist b relu carlini 5309
./run_extra.sh mnist c standard carlini 5309
./run_extra.sh mnist c adversarial carlini 5309
./run_extra.sh mnist c relu carlini 5309
./run_extra.sh mnist a standard carlini 650
./run_extra.sh mnist a adversarial carlini 650
./run_extra.sh mnist a relu carlini 650
./run_extra.sh mnist b standard carlini 650
./run_extra.sh mnist b adversarial carlini 650
./run_extra.sh mnist b relu carlini 650
./run_extra.sh mnist c standard carlini 650
./run_extra.sh mnist c adversarial carlini 650
./run_extra.sh mnist c relu carlini 650
./run_extra.sh mnist a standard carlini 4735
./run_extra.sh mnist a adversarial carlini 4735
./run_extra.sh mnist a relu carlini 4735
./run_extra.sh mnist b standard carlini 4735
./run_extra.sh mnist b adversarial carlini 4735
./run_extra.sh mnist b relu carlini 4735
./run_extra.sh mnist c standard carlini 4735
./run_extra.sh mnist c adversarial carlini 4735
./run_extra.sh mnist c relu carlini 4735
./run_extra.sh mnist a standard carlini 1590
./run_extra.sh mnist a adversarial carlini 1590
./run_extra.sh mnist a relu carlini 1590
./run_extra.sh mnist b standard carlini 1590
./run_extra.sh mnist b adversarial carlini 1590
./run_extra.sh mnist b relu carlini 1590
./run_extra.sh mnist c standard carlini 1590
./run_extra.sh mnist c adversarial carlini 1590
./run_extra.sh mnist c relu carlini 1590
./run_extra.sh mnist a standard carlini 2683
./run_extra.sh mnist a adversarial carlini 2683
./run_extra.sh mnist a relu carlini 2683
./run_extra.sh mnist b standard carlini 2683
./run_extra.sh mnist b adversarial carlini 2683
./run_extra.sh mnist b relu carlini 2683
./run_extra.sh mnist c standard carlini 2683
./run_extra.sh mnist c adversarial carlini 2683
./run_extra.sh mnist c relu carlini 2683
./run_extra.sh mnist a standard carlini 7947
./run_extra.sh mnist a adversarial carlini 7947
./run_extra.sh mnist a relu carlini 7947
./run_extra.sh mnist b standard carlini 7947
./run_extra.sh mnist b adversarial carlini 7947
./run_extra.sh mnist b relu carlini 7947
./run_extra.sh mnist c standard carlini 7947
./run_extra.sh mnist c adversarial carlini 7947
./run_extra.sh mnist c relu carlini 7947
./run_extra.sh mnist a standard carlini 3084
./run_extra.sh mnist a adversarial carlini 3084
./run_extra.sh mnist a relu carlini 3084
./run_extra.sh mnist b standard carlini 3084
./run_extra.sh mnist b adversarial carlini 3084
./run_extra.sh mnist b relu carlini 3084
./run_extra.sh mnist c standard carlini 3084
./run_extra.sh mnist c adversarial carlini 3084
./run_extra.sh mnist c relu carlini 3084
./run_extra.sh mnist a standard carlini 513
./run_extra.sh mnist a adversarial carlini 513
./run_extra.sh mnist a relu carlini 513
./run_extra.sh mnist b standard carlini 513
./run_extra.sh mnist b adversarial carlini 513
./run_extra.sh mnist b relu carlini 513
./run_extra.sh mnist c standard carlini 513
./run_extra.sh mnist c adversarial carlini 513
./run_extra.sh mnist c relu carlini 513
./run_extra.sh mnist a standard carlini 4067
./run_extra.sh mnist a adversarial carlini 4067
./run_extra.sh mnist a relu carlini 4067
./run_extra.sh mnist b standard carlini 4067
./run_extra.sh mnist b adversarial carlini 4067
./run_extra.sh mnist b relu carlini 4067
./run_extra.sh mnist c standard carlini 4067
./run_extra.sh mnist c adversarial carlini 4067
./run_extra.sh mnist c relu carlini 4067
./run_extra.sh mnist a standard carlini 2765
./run_extra.sh mnist a adversarial carlini 2765
./run_extra.sh mnist a relu carlini 2765
./run_extra.sh mnist b standard carlini 2765
./run_extra.sh mnist b adversarial carlini 2765
./run_extra.sh mnist b relu carlini 2765
./run_extra.sh mnist c standard carlini 2765
./run_extra.sh mnist c adversarial carlini 2765
./run_extra.sh mnist c relu carlini 2765
./run_extra.sh mnist a standard carlini 2037
./run_extra.sh mnist a adversarial carlini 2037
./run_extra.sh mnist a relu carlini 2037
./run_extra.sh mnist b standard carlini 2037
./run_extra.sh mnist b adversarial carlini 2037
./run_extra.sh mnist b relu carlini 2037
./run_extra.sh mnist c standard carlini 2037
./run_extra.sh mnist c adversarial carlini 2037
./run_extra.sh mnist c relu carlini 2037
./run_extra.sh mnist a standard carlini 395
./run_extra.sh mnist a adversarial carlini 395
./run_extra.sh mnist a relu carlini 395
./run_extra.sh mnist b standard carlini 395
./run_extra.sh mnist b adversarial carlini 395
./run_extra.sh mnist b relu carlini 395
./run_extra.sh mnist c standard carlini 395
./run_extra.sh mnist c adversarial carlini 395
./run_extra.sh mnist c relu carlini 395
./run_extra.sh mnist a standard carlini 6738
./run_extra.sh mnist a adversarial carlini 6738
./run_extra.sh mnist a relu carlini 6738
./run_extra.sh mnist b standard carlini 6738
./run_extra.sh mnist b adversarial carlini 6738
./run_extra.sh mnist b relu carlini 6738
./run_extra.sh mnist c standard carlini 6738
./run_extra.sh mnist c adversarial carlini 6738
./run_extra.sh mnist c relu carlini 6738
./run_extra.sh mnist a standard carlini 6080
./run_extra.sh mnist a adversarial carlini 6080
./run_extra.sh mnist a relu carlini 6080
./run_extra.sh mnist b standard carlini 6080
./run_extra.sh mnist b adversarial carlini 6080
./run_extra.sh mnist b relu carlini 6080
./run_extra.sh mnist c standard carlini 6080
./run_extra.sh mnist c adversarial carlini 6080
./run_extra.sh mnist c relu carlini 6080
./run_extra.sh mnist a standard carlini 3062
./run_extra.sh mnist a adversarial carlini 3062
./run_extra.sh mnist a relu carlini 3062
./run_extra.sh mnist b standard carlini 3062
./run_extra.sh mnist b adversarial carlini 3062
./run_extra.sh mnist b relu carlini 3062
./run_extra.sh mnist c standard carlini 3062
./run_extra.sh mnist c adversarial carlini 3062
./run_extra.sh mnist c relu carlini 3062
./run_extra.sh mnist a standard carlini 3518
./run_extra.sh mnist a adversarial carlini 3518
./run_extra.sh mnist a relu carlini 3518
./run_extra.sh mnist b standard carlini 3518
./run_extra.sh mnist b adversarial carlini 3518
./run_extra.sh mnist b relu carlini 3518
./run_extra.sh mnist c standard carlini 3518
./run_extra.sh mnist c adversarial carlini 3518
./run_extra.sh mnist c relu carlini 3518
./run_extra.sh mnist a standard carlini 7672
./run_extra.sh mnist a adversarial carlini 7672
./run_extra.sh mnist a relu carlini 7672
./run_extra.sh mnist b standard carlini 7672
./run_extra.sh mnist b adversarial carlini 7672
./run_extra.sh mnist b relu carlini 7672
./run_extra.sh mnist c standard carlini 7672
./run_extra.sh mnist c adversarial carlini 7672
./run_extra.sh mnist c relu carlini 7672
./run_extra.sh mnist a standard carlini 5393
./run_extra.sh mnist a adversarial carlini 5393
./run_extra.sh mnist a relu carlini 5393
./run_extra.sh mnist b standard carlini 5393
./run_extra.sh mnist b adversarial carlini 5393
./run_extra.sh mnist b relu carlini 5393
./run_extra.sh mnist c standard carlini 5393
./run_extra.sh mnist c adversarial carlini 5393
./run_extra.sh mnist c relu carlini 5393
./run_extra.sh mnist a standard carlini 4449
./run_extra.sh mnist a adversarial carlini 4449
./run_extra.sh mnist a relu carlini 4449
./run_extra.sh mnist b standard carlini 4449
./run_extra.sh mnist b adversarial carlini 4449
./run_extra.sh mnist b relu carlini 4449
./run_extra.sh mnist c standard carlini 4449
./run_extra.sh mnist c adversarial carlini 4449
./run_extra.sh mnist c relu carlini 4449
./run_extra.sh mnist a standard carlini 591
./run_extra.sh mnist a adversarial carlini 591
./run_extra.sh mnist a relu carlini 591
./run_extra.sh mnist b standard carlini 591
./run_extra.sh mnist b adversarial carlini 591
./run_extra.sh mnist b relu carlini 591
./run_extra.sh mnist c standard carlini 591
./run_extra.sh mnist c adversarial carlini 591
./run_extra.sh mnist c relu carlini 591
./run_extra.sh mnist a standard carlini 6179
./run_extra.sh mnist a adversarial carlini 6179
./run_extra.sh mnist a relu carlini 6179
./run_extra.sh mnist b standard carlini 6179
./run_extra.sh mnist b adversarial carlini 6179
./run_extra.sh mnist b relu carlini 6179
./run_extra.sh mnist c standard carlini 6179
./run_extra.sh mnist c adversarial carlini 6179
./run_extra.sh mnist c relu carlini 6179
./run_extra.sh mnist a standard carlini 2251
./run_extra.sh mnist a adversarial carlini 2251
./run_extra.sh mnist a relu carlini 2251
./run_extra.sh mnist b standard carlini 2251
./run_extra.sh mnist b adversarial carlini 2251
./run_extra.sh mnist b relu carlini 2251
./run_extra.sh mnist c standard carlini 2251
./run_extra.sh mnist c adversarial carlini 2251
./run_extra.sh mnist c relu carlini 2251
./run_extra.sh mnist a standard carlini 1787
./run_extra.sh mnist a adversarial carlini 1787
./run_extra.sh mnist a relu carlini 1787
./run_extra.sh mnist b standard carlini 1787
./run_extra.sh mnist b adversarial carlini 1787
./run_extra.sh mnist b relu carlini 1787
./run_extra.sh mnist c standard carlini 1787
./run_extra.sh mnist c adversarial carlini 1787
./run_extra.sh mnist c relu carlini 1787
./run_extra.sh mnist a standard carlini 7974
./run_extra.sh mnist a adversarial carlini 7974
./run_extra.sh mnist a relu carlini 7974
./run_extra.sh mnist b standard carlini 7974
./run_extra.sh mnist b adversarial carlini 7974
./run_extra.sh mnist b relu carlini 7974
./run_extra.sh mnist c standard carlini 7974
./run_extra.sh mnist c adversarial carlini 7974
./run_extra.sh mnist c relu carlini 7974
./run_extra.sh mnist a standard carlini 8351
./run_extra.sh mnist a adversarial carlini 8351
./run_extra.sh mnist a relu carlini 8351
./run_extra.sh mnist b standard carlini 8351
./run_extra.sh mnist b adversarial carlini 8351
./run_extra.sh mnist b relu carlini 8351
./run_extra.sh mnist c standard carlini 8351
./run_extra.sh mnist c adversarial carlini 8351
./run_extra.sh mnist c relu carlini 8351
./run_extra.sh mnist a standard carlini 9372
./run_extra.sh mnist a adversarial carlini 9372
./run_extra.sh mnist a relu carlini 9372
./run_extra.sh mnist b standard carlini 9372
./run_extra.sh mnist b adversarial carlini 9372
./run_extra.sh mnist b relu carlini 9372
./run_extra.sh mnist c standard carlini 9372
./run_extra.sh mnist c adversarial carlini 9372
./run_extra.sh mnist c relu carlini 9372
./run_extra.sh mnist a standard carlini 6719
./run_extra.sh mnist a adversarial carlini 6719
./run_extra.sh mnist a relu carlini 6719
./run_extra.sh mnist b standard carlini 6719
./run_extra.sh mnist b adversarial carlini 6719
./run_extra.sh mnist b relu carlini 6719
./run_extra.sh mnist c standard carlini 6719
./run_extra.sh mnist c adversarial carlini 6719
./run_extra.sh mnist c relu carlini 6719
./run_extra.sh mnist a standard carlini 7242
./run_extra.sh mnist a adversarial carlini 7242
./run_extra.sh mnist a relu carlini 7242
./run_extra.sh mnist b standard carlini 7242
./run_extra.sh mnist b adversarial carlini 7242
./run_extra.sh mnist b relu carlini 7242
./run_extra.sh mnist c standard carlini 7242
./run_extra.sh mnist c adversarial carlini 7242
./run_extra.sh mnist c relu carlini 7242
./run_extra.sh mnist a standard carlini 3222
./run_extra.sh mnist a adversarial carlini 3222
./run_extra.sh mnist a relu carlini 3222
./run_extra.sh mnist b standard carlini 3222
./run_extra.sh mnist b adversarial carlini 3222
./run_extra.sh mnist b relu carlini 3222
./run_extra.sh mnist c standard carlini 3222
./run_extra.sh mnist c adversarial carlini 3222
./run_extra.sh mnist c relu carlini 3222
./run_extra.sh mnist a standard carlini 9623
./run_extra.sh mnist a adversarial carlini 9623
./run_extra.sh mnist a relu carlini 9623
./run_extra.sh mnist b standard carlini 9623
./run_extra.sh mnist b adversarial carlini 9623
./run_extra.sh mnist b relu carlini 9623
./run_extra.sh mnist c standard carlini 9623
./run_extra.sh mnist c adversarial carlini 9623
./run_extra.sh mnist c relu carlini 9623
./run_extra.sh mnist a standard carlini 2027
./run_extra.sh mnist a adversarial carlini 2027
./run_extra.sh mnist a relu carlini 2027
./run_extra.sh mnist b standard carlini 2027
./run_extra.sh mnist b adversarial carlini 2027
./run_extra.sh mnist b relu carlini 2027
./run_extra.sh mnist c standard carlini 2027
./run_extra.sh mnist c adversarial carlini 2027
./run_extra.sh mnist c relu carlini 2027
./run_extra.sh mnist a standard carlini 1615
./run_extra.sh mnist a adversarial carlini 1615
./run_extra.sh mnist a relu carlini 1615
./run_extra.sh mnist b standard carlini 1615
./run_extra.sh mnist b adversarial carlini 1615
./run_extra.sh mnist b relu carlini 1615
./run_extra.sh mnist c standard carlini 1615
./run_extra.sh mnist c adversarial carlini 1615
./run_extra.sh mnist c relu carlini 1615
./run_extra.sh mnist a standard carlini 1913
./run_extra.sh mnist a adversarial carlini 1913
./run_extra.sh mnist a relu carlini 1913
./run_extra.sh mnist b standard carlini 1913
./run_extra.sh mnist b adversarial carlini 1913
./run_extra.sh mnist b relu carlini 1913
./run_extra.sh mnist c standard carlini 1913
./run_extra.sh mnist c adversarial carlini 1913
./run_extra.sh mnist c relu carlini 1913
./run_extra.sh mnist a standard carlini 1453
./run_extra.sh mnist a adversarial carlini 1453
./run_extra.sh mnist a relu carlini 1453
./run_extra.sh mnist b standard carlini 1453
./run_extra.sh mnist b adversarial carlini 1453
./run_extra.sh mnist b relu carlini 1453
./run_extra.sh mnist c standard carlini 1453
./run_extra.sh mnist c adversarial carlini 1453
./run_extra.sh mnist c relu carlini 1453
./run_extra.sh mnist a standard carlini 3888
./run_extra.sh mnist a adversarial carlini 3888
./run_extra.sh mnist a relu carlini 3888
./run_extra.sh mnist b standard carlini 3888
./run_extra.sh mnist b adversarial carlini 3888
./run_extra.sh mnist b relu carlini 3888
./run_extra.sh mnist c standard carlini 3888
./run_extra.sh mnist c adversarial carlini 3888
./run_extra.sh mnist c relu carlini 3888
./run_extra.sh mnist a standard carlini 9721
./run_extra.sh mnist a adversarial carlini 9721
./run_extra.sh mnist a relu carlini 9721
./run_extra.sh mnist b standard carlini 9721
./run_extra.sh mnist b adversarial carlini 9721
./run_extra.sh mnist b relu carlini 9721
./run_extra.sh mnist c standard carlini 9721
./run_extra.sh mnist c adversarial carlini 9721
./run_extra.sh mnist c relu carlini 9721
./run_extra.sh mnist a standard carlini 9288
./run_extra.sh mnist a adversarial carlini 9288
./run_extra.sh mnist a relu carlini 9288
./run_extra.sh mnist b standard carlini 9288
./run_extra.sh mnist b adversarial carlini 9288
./run_extra.sh mnist b relu carlini 9288
./run_extra.sh mnist c standard carlini 9288
./run_extra.sh mnist c adversarial carlini 9288
./run_extra.sh mnist c relu carlini 9288
./run_extra.sh mnist a standard carlini 1910
./run_extra.sh mnist a adversarial carlini 1910
./run_extra.sh mnist a relu carlini 1910
./run_extra.sh mnist b standard carlini 1910
./run_extra.sh mnist b adversarial carlini 1910
./run_extra.sh mnist b relu carlini 1910
./run_extra.sh mnist c standard carlini 1910
./run_extra.sh mnist c adversarial carlini 1910
./run_extra.sh mnist c relu carlini 1910
./run_extra.sh mnist a standard carlini 5582
./run_extra.sh mnist a adversarial carlini 5582
./run_extra.sh mnist a relu carlini 5582
./run_extra.sh mnist b standard carlini 5582
./run_extra.sh mnist b adversarial carlini 5582
./run_extra.sh mnist b relu carlini 5582
./run_extra.sh mnist c standard carlini 5582
./run_extra.sh mnist c adversarial carlini 5582
./run_extra.sh mnist c relu carlini 5582
./run_extra.sh mnist a standard carlini 1478
./run_extra.sh mnist a adversarial carlini 1478
./run_extra.sh mnist a relu carlini 1478
./run_extra.sh mnist b standard carlini 1478
./run_extra.sh mnist b adversarial carlini 1478
./run_extra.sh mnist b relu carlini 1478
./run_extra.sh mnist c standard carlini 1478
./run_extra.sh mnist c adversarial carlini 1478
./run_extra.sh mnist c relu carlini 1478
./run_extra.sh mnist a standard carlini 9723
./run_extra.sh mnist a adversarial carlini 9723
./run_extra.sh mnist a relu carlini 9723
./run_extra.sh mnist b standard carlini 9723
./run_extra.sh mnist b adversarial carlini 9723
./run_extra.sh mnist b relu carlini 9723
./run_extra.sh mnist c standard carlini 9723
./run_extra.sh mnist c adversarial carlini 9723
./run_extra.sh mnist c relu carlini 9723
./run_extra.sh mnist a standard carlini 8413
./run_extra.sh mnist a adversarial carlini 8413
./run_extra.sh mnist a relu carlini 8413
./run_extra.sh mnist b standard carlini 8413
./run_extra.sh mnist b adversarial carlini 8413
./run_extra.sh mnist b relu carlini 8413
./run_extra.sh mnist c standard carlini 8413
./run_extra.sh mnist c adversarial carlini 8413
./run_extra.sh mnist c relu carlini 8413
./run_extra.sh mnist a standard carlini 9278
./run_extra.sh mnist a adversarial carlini 9278
./run_extra.sh mnist a relu carlini 9278
./run_extra.sh mnist b standard carlini 9278
./run_extra.sh mnist b adversarial carlini 9278
./run_extra.sh mnist b relu carlini 9278
./run_extra.sh mnist c standard carlini 9278
./run_extra.sh mnist c adversarial carlini 9278
./run_extra.sh mnist c relu carlini 9278
./run_extra.sh mnist a standard carlini 488
./run_extra.sh mnist a adversarial carlini 488
./run_extra.sh mnist a relu carlini 488
./run_extra.sh mnist b standard carlini 488
./run_extra.sh mnist b adversarial carlini 488
./run_extra.sh mnist b relu carlini 488
./run_extra.sh mnist c standard carlini 488
./run_extra.sh mnist c adversarial carlini 488
./run_extra.sh mnist c relu carlini 488
./run_extra.sh mnist a standard carlini 9534
./run_extra.sh mnist a adversarial carlini 9534
./run_extra.sh mnist a relu carlini 9534
./run_extra.sh mnist b standard carlini 9534
./run_extra.sh mnist b adversarial carlini 9534
./run_extra.sh mnist b relu carlini 9534
./run_extra.sh mnist c standard carlini 9534
./run_extra.sh mnist c adversarial carlini 9534
./run_extra.sh mnist c relu carlini 9534
./run_extra.sh mnist a standard carlini 4875
./run_extra.sh mnist a adversarial carlini 4875
./run_extra.sh mnist a relu carlini 4875
./run_extra.sh mnist b standard carlini 4875
./run_extra.sh mnist b adversarial carlini 4875
./run_extra.sh mnist b relu carlini 4875
./run_extra.sh mnist c standard carlini 4875
./run_extra.sh mnist c adversarial carlini 4875
./run_extra.sh mnist c relu carlini 4875
./run_extra.sh mnist a standard carlini 3737
./run_extra.sh mnist a adversarial carlini 3737
./run_extra.sh mnist a relu carlini 3737
./run_extra.sh mnist b standard carlini 3737
./run_extra.sh mnist b adversarial carlini 3737
./run_extra.sh mnist b relu carlini 3737
./run_extra.sh mnist c standard carlini 3737
./run_extra.sh mnist c adversarial carlini 3737
./run_extra.sh mnist c relu carlini 3737
./run_extra.sh mnist a standard carlini 7813
./run_extra.sh mnist a adversarial carlini 7813
./run_extra.sh mnist a relu carlini 7813
./run_extra.sh mnist b standard carlini 7813
./run_extra.sh mnist b adversarial carlini 7813
./run_extra.sh mnist b relu carlini 7813
./run_extra.sh mnist c standard carlini 7813
./run_extra.sh mnist c adversarial carlini 7813
./run_extra.sh mnist c relu carlini 7813
./run_extra.sh mnist a standard carlini 4210
./run_extra.sh mnist a adversarial carlini 4210
./run_extra.sh mnist a relu carlini 4210
./run_extra.sh mnist b standard carlini 4210
./run_extra.sh mnist b adversarial carlini 4210
./run_extra.sh mnist b relu carlini 4210
./run_extra.sh mnist c standard carlini 4210
./run_extra.sh mnist c adversarial carlini 4210
./run_extra.sh mnist c relu carlini 4210
./run_extra.sh mnist a standard carlini 1048
./run_extra.sh mnist a adversarial carlini 1048
./run_extra.sh mnist a relu carlini 1048
./run_extra.sh mnist b standard carlini 1048
./run_extra.sh mnist b adversarial carlini 1048
./run_extra.sh mnist b relu carlini 1048
./run_extra.sh mnist c standard carlini 1048
./run_extra.sh mnist c adversarial carlini 1048
./run_extra.sh mnist c relu carlini 1048
./run_extra.sh mnist a standard carlini 7629
./run_extra.sh mnist a adversarial carlini 7629
./run_extra.sh mnist a relu carlini 7629
./run_extra.sh mnist b standard carlini 7629
./run_extra.sh mnist b adversarial carlini 7629
./run_extra.sh mnist b relu carlini 7629
./run_extra.sh mnist c standard carlini 7629
./run_extra.sh mnist c adversarial carlini 7629
./run_extra.sh mnist c relu carlini 7629
./run_extra.sh mnist a standard carlini 6599
./run_extra.sh mnist a adversarial carlini 6599
./run_extra.sh mnist a relu carlini 6599
./run_extra.sh mnist b standard carlini 6599
./run_extra.sh mnist b adversarial carlini 6599
./run_extra.sh mnist b relu carlini 6599
./run_extra.sh mnist c standard carlini 6599
./run_extra.sh mnist c adversarial carlini 6599
./run_extra.sh mnist c relu carlini 6599
./run_extra.sh mnist a standard carlini 3822
./run_extra.sh mnist a adversarial carlini 3822
./run_extra.sh mnist a relu carlini 3822
./run_extra.sh mnist b standard carlini 3822
./run_extra.sh mnist b adversarial carlini 3822
./run_extra.sh mnist b relu carlini 3822
./run_extra.sh mnist c standard carlini 3822
./run_extra.sh mnist c adversarial carlini 3822
./run_extra.sh mnist c relu carlini 3822
./run_extra.sh mnist a standard carlini 8409
./run_extra.sh mnist a adversarial carlini 8409
./run_extra.sh mnist a relu carlini 8409
./run_extra.sh mnist b standard carlini 8409
./run_extra.sh mnist b adversarial carlini 8409
./run_extra.sh mnist b relu carlini 8409
./run_extra.sh mnist c standard carlini 8409
./run_extra.sh mnist c adversarial carlini 8409
./run_extra.sh mnist c relu carlini 8409
./run_extra.sh mnist a standard carlini 489
./run_extra.sh mnist a adversarial carlini 489
./run_extra.sh mnist a relu carlini 489
./run_extra.sh mnist b standard carlini 489
./run_extra.sh mnist b adversarial carlini 489
./run_extra.sh mnist b relu carlini 489
./run_extra.sh mnist c standard carlini 489
./run_extra.sh mnist c adversarial carlini 489
./run_extra.sh mnist c relu carlini 489
./run_extra.sh mnist a standard carlini 2586
./run_extra.sh mnist a adversarial carlini 2586
./run_extra.sh mnist a relu carlini 2586
./run_extra.sh mnist b standard carlini 2586
./run_extra.sh mnist b adversarial carlini 2586
./run_extra.sh mnist b relu carlini 2586
./run_extra.sh mnist c standard carlini 2586
./run_extra.sh mnist c adversarial carlini 2586
./run_extra.sh mnist c relu carlini 2586
./run_extra.sh mnist a standard carlini 2972
./run_extra.sh mnist a adversarial carlini 2972
./run_extra.sh mnist a relu carlini 2972
./run_extra.sh mnist b standard carlini 2972
./run_extra.sh mnist b adversarial carlini 2972
./run_extra.sh mnist b relu carlini 2972
./run_extra.sh mnist c standard carlini 2972
./run_extra.sh mnist c adversarial carlini 2972
./run_extra.sh mnist c relu carlini 2972
./run_extra.sh mnist a standard carlini 2364
./run_extra.sh mnist a adversarial carlini 2364
./run_extra.sh mnist a relu carlini 2364
./run_extra.sh mnist b standard carlini 2364
./run_extra.sh mnist b adversarial carlini 2364
./run_extra.sh mnist b relu carlini 2364
./run_extra.sh mnist c standard carlini 2364
./run_extra.sh mnist c adversarial carlini 2364
./run_extra.sh mnist c relu carlini 2364
./run_extra.sh mnist a standard carlini 4325
./run_extra.sh mnist a adversarial carlini 4325
./run_extra.sh mnist a relu carlini 4325
./run_extra.sh mnist b standard carlini 4325
./run_extra.sh mnist b adversarial carlini 4325
./run_extra.sh mnist b relu carlini 4325
./run_extra.sh mnist c standard carlini 4325
./run_extra.sh mnist c adversarial carlini 4325
./run_extra.sh mnist c relu carlini 4325
./run_extra.sh mnist a standard carlini 4179
./run_extra.sh mnist a adversarial carlini 4179
./run_extra.sh mnist a relu carlini 4179
./run_extra.sh mnist b standard carlini 4179
./run_extra.sh mnist b adversarial carlini 4179
./run_extra.sh mnist b relu carlini 4179
./run_extra.sh mnist c standard carlini 4179
./run_extra.sh mnist c adversarial carlini 4179
./run_extra.sh mnist c relu carlini 4179
./run_extra.sh mnist a standard carlini 7968
./run_extra.sh mnist a adversarial carlini 7968
./run_extra.sh mnist a relu carlini 7968
./run_extra.sh mnist b standard carlini 7968
./run_extra.sh mnist b adversarial carlini 7968
./run_extra.sh mnist b relu carlini 7968
./run_extra.sh mnist c standard carlini 7968
./run_extra.sh mnist c adversarial carlini 7968
./run_extra.sh mnist c relu carlini 7968
./run_extra.sh mnist a standard carlini 7839
./run_extra.sh mnist a adversarial carlini 7839
./run_extra.sh mnist a relu carlini 7839
./run_extra.sh mnist b standard carlini 7839
./run_extra.sh mnist b adversarial carlini 7839
./run_extra.sh mnist b relu carlini 7839
./run_extra.sh mnist c standard carlini 7839
./run_extra.sh mnist c adversarial carlini 7839
./run_extra.sh mnist c relu carlini 7839
./run_extra.sh mnist a standard carlini 7584
./run_extra.sh mnist a adversarial carlini 7584
./run_extra.sh mnist a relu carlini 7584
./run_extra.sh mnist b standard carlini 7584
./run_extra.sh mnist b adversarial carlini 7584
./run_extra.sh mnist b relu carlini 7584
./run_extra.sh mnist c standard carlini 7584
./run_extra.sh mnist c adversarial carlini 7584
./run_extra.sh mnist c relu carlini 7584
./run_extra.sh mnist a standard carlini 4055
./run_extra.sh mnist a adversarial carlini 4055
./run_extra.sh mnist a relu carlini 4055
./run_extra.sh mnist b standard carlini 4055
./run_extra.sh mnist b adversarial carlini 4055
./run_extra.sh mnist b relu carlini 4055
./run_extra.sh mnist c standard carlini 4055
./run_extra.sh mnist c adversarial carlini 4055
./run_extra.sh mnist c relu carlini 4055
./run_extra.sh mnist a standard carlini 3821
./run_extra.sh mnist a adversarial carlini 3821
./run_extra.sh mnist a relu carlini 3821
./run_extra.sh mnist b standard carlini 3821
./run_extra.sh mnist b adversarial carlini 3821
./run_extra.sh mnist b relu carlini 3821
./run_extra.sh mnist c standard carlini 3821
./run_extra.sh mnist c adversarial carlini 3821
./run_extra.sh mnist c relu carlini 3821
./run_extra.sh mnist a standard carlini 1907
./run_extra.sh mnist a adversarial carlini 1907
./run_extra.sh mnist a relu carlini 1907
./run_extra.sh mnist b standard carlini 1907
./run_extra.sh mnist b adversarial carlini 1907
./run_extra.sh mnist b relu carlini 1907
./run_extra.sh mnist c standard carlini 1907
./run_extra.sh mnist c adversarial carlini 1907
./run_extra.sh mnist c relu carlini 1907
./run_extra.sh mnist a standard carlini 3276
./run_extra.sh mnist a adversarial carlini 3276
./run_extra.sh mnist a relu carlini 3276
./run_extra.sh mnist b standard carlini 3276
./run_extra.sh mnist b adversarial carlini 3276
./run_extra.sh mnist b relu carlini 3276
./run_extra.sh mnist c standard carlini 3276
./run_extra.sh mnist c adversarial carlini 3276
./run_extra.sh mnist c relu carlini 3276
./run_extra.sh mnist a standard carlini 8804
./run_extra.sh mnist a adversarial carlini 8804
./run_extra.sh mnist a relu carlini 8804
./run_extra.sh mnist b standard carlini 8804
./run_extra.sh mnist b adversarial carlini 8804
./run_extra.sh mnist b relu carlini 8804
./run_extra.sh mnist c standard carlini 8804
./run_extra.sh mnist c adversarial carlini 8804
./run_extra.sh mnist c relu carlini 8804
./run_extra.sh mnist a standard carlini 4302
./run_extra.sh mnist a adversarial carlini 4302
./run_extra.sh mnist a relu carlini 4302
./run_extra.sh mnist b standard carlini 4302
./run_extra.sh mnist b adversarial carlini 4302
./run_extra.sh mnist b relu carlini 4302
./run_extra.sh mnist c standard carlini 4302
./run_extra.sh mnist c adversarial carlini 4302
./run_extra.sh mnist c relu carlini 4302
./run_extra.sh mnist a standard carlini 1372
./run_extra.sh mnist a adversarial carlini 1372
./run_extra.sh mnist a relu carlini 1372
./run_extra.sh mnist b standard carlini 1372
./run_extra.sh mnist b adversarial carlini 1372
./run_extra.sh mnist b relu carlini 1372
./run_extra.sh mnist c standard carlini 1372
./run_extra.sh mnist c adversarial carlini 1372
./run_extra.sh mnist c relu carlini 1372
./run_extra.sh mnist a standard carlini 1452
./run_extra.sh mnist a adversarial carlini 1452
./run_extra.sh mnist a relu carlini 1452
./run_extra.sh mnist b standard carlini 1452
./run_extra.sh mnist b adversarial carlini 1452
./run_extra.sh mnist b relu carlini 1452
./run_extra.sh mnist c standard carlini 1452
./run_extra.sh mnist c adversarial carlini 1452
./run_extra.sh mnist c relu carlini 1452
./run_extra.sh mnist a standard carlini 5426
./run_extra.sh mnist a adversarial carlini 5426
./run_extra.sh mnist a relu carlini 5426
./run_extra.sh mnist b standard carlini 5426
./run_extra.sh mnist b adversarial carlini 5426
./run_extra.sh mnist b relu carlini 5426
./run_extra.sh mnist c standard carlini 5426
./run_extra.sh mnist c adversarial carlini 5426
./run_extra.sh mnist c relu carlini 5426
./run_extra.sh mnist a standard carlini 3997
./run_extra.sh mnist a adversarial carlini 3997
./run_extra.sh mnist a relu carlini 3997
./run_extra.sh mnist b standard carlini 3997
./run_extra.sh mnist b adversarial carlini 3997
./run_extra.sh mnist b relu carlini 3997
./run_extra.sh mnist c standard carlini 3997
./run_extra.sh mnist c adversarial carlini 3997
./run_extra.sh mnist c relu carlini 3997
./run_extra.sh mnist a standard carlini 967
./run_extra.sh mnist a adversarial carlini 967
./run_extra.sh mnist a relu carlini 967
./run_extra.sh mnist b standard carlini 967
./run_extra.sh mnist b adversarial carlini 967
./run_extra.sh mnist b relu carlini 967
./run_extra.sh mnist c standard carlini 967
./run_extra.sh mnist c adversarial carlini 967
./run_extra.sh mnist c relu carlini 967
./run_extra.sh mnist a standard carlini 4739
./run_extra.sh mnist a adversarial carlini 4739
./run_extra.sh mnist a relu carlini 4739
./run_extra.sh mnist b standard carlini 4739
./run_extra.sh mnist b adversarial carlini 4739
./run_extra.sh mnist b relu carlini 4739
./run_extra.sh mnist c standard carlini 4739
./run_extra.sh mnist c adversarial carlini 4739
./run_extra.sh mnist c relu carlini 4739
./run_extra.sh mnist a standard carlini 6175
./run_extra.sh mnist a adversarial carlini 6175
./run_extra.sh mnist a relu carlini 6175
./run_extra.sh mnist b standard carlini 6175
./run_extra.sh mnist b adversarial carlini 6175
./run_extra.sh mnist b relu carlini 6175
./run_extra.sh mnist c standard carlini 6175
./run_extra.sh mnist c adversarial carlini 6175
./run_extra.sh mnist c relu carlini 6175
./run_extra.sh mnist a standard carlini 7836
./run_extra.sh mnist a adversarial carlini 7836
./run_extra.sh mnist a relu carlini 7836
./run_extra.sh mnist b standard carlini 7836
./run_extra.sh mnist b adversarial carlini 7836
./run_extra.sh mnist b relu carlini 7836
./run_extra.sh mnist c standard carlini 7836
./run_extra.sh mnist c adversarial carlini 7836
./run_extra.sh mnist c relu carlini 7836
./run_extra.sh mnist a standard carlini 6500
./run_extra.sh mnist a adversarial carlini 6500
./run_extra.sh mnist a relu carlini 6500
./run_extra.sh mnist b standard carlini 6500
./run_extra.sh mnist b adversarial carlini 6500
./run_extra.sh mnist b relu carlini 6500
./run_extra.sh mnist c standard carlini 6500
./run_extra.sh mnist c adversarial carlini 6500
./run_extra.sh mnist c relu carlini 6500
./run_extra.sh mnist a standard carlini 5999
./run_extra.sh mnist a adversarial carlini 5999
./run_extra.sh mnist a relu carlini 5999
./run_extra.sh mnist b standard carlini 5999
./run_extra.sh mnist b adversarial carlini 5999
./run_extra.sh mnist b relu carlini 5999
./run_extra.sh mnist c standard carlini 5999
./run_extra.sh mnist c adversarial carlini 5999
./run_extra.sh mnist c relu carlini 5999
./run_extra.sh mnist a standard carlini 5508
./run_extra.sh mnist a adversarial carlini 5508
./run_extra.sh mnist a relu carlini 5508
./run_extra.sh mnist b standard carlini 5508
./run_extra.sh mnist b adversarial carlini 5508
./run_extra.sh mnist b relu carlini 5508
./run_extra.sh mnist c standard carlini 5508
./run_extra.sh mnist c adversarial carlini 5508
./run_extra.sh mnist c relu carlini 5508
./run_extra.sh mnist a standard carlini 7111
./run_extra.sh mnist a adversarial carlini 7111
./run_extra.sh mnist a relu carlini 7111
./run_extra.sh mnist b standard carlini 7111
./run_extra.sh mnist b adversarial carlini 7111
./run_extra.sh mnist b relu carlini 7111
./run_extra.sh mnist c standard carlini 7111
./run_extra.sh mnist c adversarial carlini 7111
./run_extra.sh mnist c relu carlini 7111
./run_extra.sh mnist a standard carlini 9513
./run_extra.sh mnist a adversarial carlini 9513
./run_extra.sh mnist a relu carlini 9513
./run_extra.sh mnist b standard carlini 9513
./run_extra.sh mnist b adversarial carlini 9513
./run_extra.sh mnist b relu carlini 9513
./run_extra.sh mnist c standard carlini 9513
./run_extra.sh mnist c adversarial carlini 9513
./run_extra.sh mnist c relu carlini 9513
./run_extra.sh mnist a standard carlini 8676
./run_extra.sh mnist a adversarial carlini 8676
./run_extra.sh mnist a relu carlini 8676
./run_extra.sh mnist b standard carlini 8676
./run_extra.sh mnist b adversarial carlini 8676
./run_extra.sh mnist b relu carlini 8676
./run_extra.sh mnist c standard carlini 8676
./run_extra.sh mnist c adversarial carlini 8676
./run_extra.sh mnist c relu carlini 8676
./run_extra.sh mnist a standard carlini 7389
./run_extra.sh mnist a adversarial carlini 7389
./run_extra.sh mnist a relu carlini 7389
./run_extra.sh mnist b standard carlini 7389
./run_extra.sh mnist b adversarial carlini 7389
./run_extra.sh mnist b relu carlini 7389
./run_extra.sh mnist c standard carlini 7389
./run_extra.sh mnist c adversarial carlini 7389
./run_extra.sh mnist c relu carlini 7389
./run_extra.sh mnist a standard carlini 5247
./run_extra.sh mnist a adversarial carlini 5247
./run_extra.sh mnist a relu carlini 5247
./run_extra.sh mnist b standard carlini 5247
./run_extra.sh mnist b adversarial carlini 5247
./run_extra.sh mnist b relu carlini 5247
./run_extra.sh mnist c standard carlini 5247
./run_extra.sh mnist c adversarial carlini 5247
./run_extra.sh mnist c relu carlini 5247
./run_extra.sh mnist a standard carlini 6352
./run_extra.sh mnist a adversarial carlini 6352
./run_extra.sh mnist a relu carlini 6352
./run_extra.sh mnist b standard carlini 6352
./run_extra.sh mnist b adversarial carlini 6352
./run_extra.sh mnist b relu carlini 6352
./run_extra.sh mnist c standard carlini 6352
./run_extra.sh mnist c adversarial carlini 6352
./run_extra.sh mnist c relu carlini 6352
./run_extra.sh mnist a standard carlini 2385
./run_extra.sh mnist a adversarial carlini 2385
./run_extra.sh mnist a relu carlini 2385
./run_extra.sh mnist b standard carlini 2385
./run_extra.sh mnist b adversarial carlini 2385
./run_extra.sh mnist b relu carlini 2385
./run_extra.sh mnist c standard carlini 2385
./run_extra.sh mnist c adversarial carlini 2385
./run_extra.sh mnist c relu carlini 2385
./run_extra.sh mnist a standard carlini 9025
./run_extra.sh mnist a adversarial carlini 9025
./run_extra.sh mnist a relu carlini 9025
./run_extra.sh mnist b standard carlini 9025
./run_extra.sh mnist b adversarial carlini 9025
./run_extra.sh mnist b relu carlini 9025
./run_extra.sh mnist c standard carlini 9025
./run_extra.sh mnist c adversarial carlini 9025
./run_extra.sh mnist c relu carlini 9025
./run_extra.sh mnist a standard carlini 5190
./run_extra.sh mnist a adversarial carlini 5190
./run_extra.sh mnist a relu carlini 5190
./run_extra.sh mnist b standard carlini 5190
./run_extra.sh mnist b adversarial carlini 5190
./run_extra.sh mnist b relu carlini 5190
./run_extra.sh mnist c standard carlini 5190
./run_extra.sh mnist c adversarial carlini 5190
./run_extra.sh mnist c relu carlini 5190
./run_extra.sh mnist a standard carlini 6074
./run_extra.sh mnist a adversarial carlini 6074
./run_extra.sh mnist a relu carlini 6074
./run_extra.sh mnist b standard carlini 6074
./run_extra.sh mnist b adversarial carlini 6074
./run_extra.sh mnist b relu carlini 6074
./run_extra.sh mnist c standard carlini 6074
./run_extra.sh mnist c adversarial carlini 6074
./run_extra.sh mnist c relu carlini 6074
./run_extra.sh mnist a standard carlini 6618
./run_extra.sh mnist a adversarial carlini 6618
./run_extra.sh mnist a relu carlini 6618
./run_extra.sh mnist b standard carlini 6618
./run_extra.sh mnist b adversarial carlini 6618
./run_extra.sh mnist b relu carlini 6618
./run_extra.sh mnist c standard carlini 6618
./run_extra.sh mnist c adversarial carlini 6618
./run_extra.sh mnist c relu carlini 6618
./run_extra.sh mnist a standard carlini 2563
./run_extra.sh mnist a adversarial carlini 2563
./run_extra.sh mnist a relu carlini 2563
./run_extra.sh mnist b standard carlini 2563
./run_extra.sh mnist b adversarial carlini 2563
./run_extra.sh mnist b relu carlini 2563
./run_extra.sh mnist c standard carlini 2563
./run_extra.sh mnist c adversarial carlini 2563
./run_extra.sh mnist c relu carlini 2563
./run_extra.sh mnist a standard carlini 7190
./run_extra.sh mnist a adversarial carlini 7190
./run_extra.sh mnist a relu carlini 7190
./run_extra.sh mnist b standard carlini 7190
./run_extra.sh mnist b adversarial carlini 7190
./run_extra.sh mnist b relu carlini 7190
./run_extra.sh mnist c standard carlini 7190
./run_extra.sh mnist c adversarial carlini 7190
./run_extra.sh mnist c relu carlini 7190
./run_extra.sh mnist a standard carlini 707
./run_extra.sh mnist a adversarial carlini 707
./run_extra.sh mnist a relu carlini 707
./run_extra.sh mnist b standard carlini 707
./run_extra.sh mnist b adversarial carlini 707
./run_extra.sh mnist b relu carlini 707
./run_extra.sh mnist c standard carlini 707
./run_extra.sh mnist c adversarial carlini 707
./run_extra.sh mnist c relu carlini 707
./run_extra.sh mnist a standard carlini 2076
./run_extra.sh mnist a adversarial carlini 2076
./run_extra.sh mnist a relu carlini 2076
./run_extra.sh mnist b standard carlini 2076
./run_extra.sh mnist b adversarial carlini 2076
./run_extra.sh mnist b relu carlini 2076
./run_extra.sh mnist c standard carlini 2076
./run_extra.sh mnist c adversarial carlini 2076
./run_extra.sh mnist c relu carlini 2076
./run_extra.sh mnist a standard carlini 2727
./run_extra.sh mnist a adversarial carlini 2727
./run_extra.sh mnist a relu carlini 2727
./run_extra.sh mnist b standard carlini 2727
./run_extra.sh mnist b adversarial carlini 2727
./run_extra.sh mnist b relu carlini 2727
./run_extra.sh mnist c standard carlini 2727
./run_extra.sh mnist c adversarial carlini 2727
./run_extra.sh mnist c relu carlini 2727
./run_extra.sh mnist a standard carlini 4153
./run_extra.sh mnist a adversarial carlini 4153
./run_extra.sh mnist a relu carlini 4153
./run_extra.sh mnist b standard carlini 4153
./run_extra.sh mnist b adversarial carlini 4153
./run_extra.sh mnist b relu carlini 4153
./run_extra.sh mnist c standard carlini 4153
./run_extra.sh mnist c adversarial carlini 4153
./run_extra.sh mnist c relu carlini 4153
./run_extra.sh mnist a standard carlini 7911
./run_extra.sh mnist a adversarial carlini 7911
./run_extra.sh mnist a relu carlini 7911
./run_extra.sh mnist b standard carlini 7911
./run_extra.sh mnist b adversarial carlini 7911
./run_extra.sh mnist b relu carlini 7911
./run_extra.sh mnist c standard carlini 7911
./run_extra.sh mnist c adversarial carlini 7911
./run_extra.sh mnist c relu carlini 7911
./run_extra.sh mnist a standard carlini 3213
./run_extra.sh mnist a adversarial carlini 3213
./run_extra.sh mnist a relu carlini 3213
./run_extra.sh mnist b standard carlini 3213
./run_extra.sh mnist b adversarial carlini 3213
./run_extra.sh mnist b relu carlini 3213
./run_extra.sh mnist c standard carlini 3213
./run_extra.sh mnist c adversarial carlini 3213
./run_extra.sh mnist c relu carlini 3213
./run_extra.sh mnist a standard carlini 6441
./run_extra.sh mnist a adversarial carlini 6441
./run_extra.sh mnist a relu carlini 6441
./run_extra.sh mnist b standard carlini 6441
./run_extra.sh mnist b adversarial carlini 6441
./run_extra.sh mnist b relu carlini 6441
./run_extra.sh mnist c standard carlini 6441
./run_extra.sh mnist c adversarial carlini 6441
./run_extra.sh mnist c relu carlini 6441
./run_extra.sh mnist a standard carlini 5683
./run_extra.sh mnist a adversarial carlini 5683
./run_extra.sh mnist a relu carlini 5683
./run_extra.sh mnist b standard carlini 5683
./run_extra.sh mnist b adversarial carlini 5683
./run_extra.sh mnist b relu carlini 5683
./run_extra.sh mnist c standard carlini 5683
./run_extra.sh mnist c adversarial carlini 5683
./run_extra.sh mnist c relu carlini 5683
./run_extra.sh mnist a standard carlini 9864
./run_extra.sh mnist a adversarial carlini 9864
./run_extra.sh mnist a relu carlini 9864
./run_extra.sh mnist b standard carlini 9864
./run_extra.sh mnist b adversarial carlini 9864
./run_extra.sh mnist b relu carlini 9864
./run_extra.sh mnist c standard carlini 9864
./run_extra.sh mnist c adversarial carlini 9864
./run_extra.sh mnist c relu carlini 9864
./run_extra.sh mnist a standard carlini 7896
./run_extra.sh mnist a adversarial carlini 7896
./run_extra.sh mnist a relu carlini 7896
./run_extra.sh mnist b standard carlini 7896
./run_extra.sh mnist b adversarial carlini 7896
./run_extra.sh mnist b relu carlini 7896
./run_extra.sh mnist c standard carlini 7896
./run_extra.sh mnist c adversarial carlini 7896
./run_extra.sh mnist c relu carlini 7896
./run_extra.sh mnist a standard carlini 7451
./run_extra.sh mnist a adversarial carlini 7451
./run_extra.sh mnist a relu carlini 7451
./run_extra.sh mnist b standard carlini 7451
./run_extra.sh mnist b adversarial carlini 7451
./run_extra.sh mnist b relu carlini 7451
./run_extra.sh mnist c standard carlini 7451
./run_extra.sh mnist c adversarial carlini 7451
./run_extra.sh mnist c relu carlini 7451
./run_extra.sh mnist a standard carlini 3663
./run_extra.sh mnist a adversarial carlini 3663
./run_extra.sh mnist a relu carlini 3663
./run_extra.sh mnist b standard carlini 3663
./run_extra.sh mnist b adversarial carlini 3663
./run_extra.sh mnist b relu carlini 3663
./run_extra.sh mnist c standard carlini 3663
./run_extra.sh mnist c adversarial carlini 3663
./run_extra.sh mnist c relu carlini 3663
./run_extra.sh mnist a standard carlini 8366
./run_extra.sh mnist a adversarial carlini 8366
./run_extra.sh mnist a relu carlini 8366
./run_extra.sh mnist b standard carlini 8366
./run_extra.sh mnist b adversarial carlini 8366
