./run_extra.sh mnist b standard carlini 7215
./run_extra.sh mnist b adversarial carlini 7215
./run_extra.sh mnist b relu carlini 7215
./run_extra.sh mnist c standard carlini 7215
./run_extra.sh mnist c adversarial carlini 7215
./run_extra.sh mnist c relu carlini 7215
./run_extra.sh mnist a standard carlini 7821
./run_extra.sh mnist a adversarial carlini 7821
./run_extra.sh mnist a relu carlini 7821
./run_extra.sh mnist b standard carlini 7821
./run_extra.sh mnist b adversarial carlini 7821
./run_extra.sh mnist b relu carlini 7821
./run_extra.sh mnist c standard carlini 7821
./run_extra.sh mnist c adversarial carlini 7821
./run_extra.sh mnist c relu carlini 7821
./run_extra.sh mnist a standard carlini 2077
./run_extra.sh mnist a adversarial carlini 2077
./run_extra.sh mnist a relu carlini 2077
./run_extra.sh mnist b standard carlini 2077
./run_extra.sh mnist b adversarial carlini 2077
./run_extra.sh mnist b relu carlini 2077
./run_extra.sh mnist c standard carlini 2077
./run_extra.sh mnist c adversarial carlini 2077
./run_extra.sh mnist c relu carlini 2077
./run_extra.sh mnist a standard carlini 3579
./run_extra.sh mnist a adversarial carlini 3579
./run_extra.sh mnist a relu carlini 3579
./run_extra.sh mnist b standard carlini 3579
./run_extra.sh mnist b adversarial carlini 3579
./run_extra.sh mnist b relu carlini 3579
./run_extra.sh mnist c standard carlini 3579
./run_extra.sh mnist c adversarial carlini 3579
./run_extra.sh mnist c relu carlini 3579
./run_extra.sh mnist a standard carlini 7894
./run_extra.sh mnist a adversarial carlini 7894
./run_extra.sh mnist a relu carlini 7894
./run_extra.sh mnist b standard carlini 7894
./run_extra.sh mnist b adversarial carlini 7894
./run_extra.sh mnist b relu carlini 7894
./run_extra.sh mnist c standard carlini 7894
./run_extra.sh mnist c adversarial carlini 7894
./run_extra.sh mnist c relu carlini 7894
./run_extra.sh mnist a standard carlini 3057
./run_extra.sh mnist a adversarial carlini 3057
./run_extra.sh mnist a relu carlini 3057
./run_extra.sh mnist b standard carlini 3057
./run_extra.sh mnist b adversarial carlini 3057
./run_extra.sh mnist b relu carlini 3057
./run_extra.sh mnist c standard carlini 3057
./run_extra.sh mnist c adversarial carlini 3057
./run_extra.sh mnist c relu carlini 3057
./run_extra.sh mnist a standard carlini 1248
./run_extra.sh mnist a adversarial carlini 1248
./run_extra.sh mnist a relu carlini 1248
./run_extra.sh mnist b standard carlini 1248
./run_extra.sh mnist b adversarial carlini 1248
./run_extra.sh mnist b relu carlini 1248
./run_extra.sh mnist c standard carlini 1248
./run_extra.sh mnist c adversarial carlini 1248
./run_extra.sh mnist c relu carlini 1248
./run_extra.sh mnist a standard carlini 9905
./run_extra.sh mnist a adversarial carlini 9905
./run_extra.sh mnist a relu carlini 9905
./run_extra.sh mnist b standard carlini 9905
./run_extra.sh mnist b adversarial carlini 9905
./run_extra.sh mnist b relu carlini 9905
./run_extra.sh mnist c standard carlini 9905
./run_extra.sh mnist c adversarial carlini 9905
./run_extra.sh mnist c relu carlini 9905
./run_extra.sh mnist a standard carlini 5123
./run_extra.sh mnist a adversarial carlini 5123
./run_extra.sh mnist a relu carlini 5123
./run_extra.sh mnist b standard carlini 5123
./run_extra.sh mnist b adversarial carlini 5123
./run_extra.sh mnist b relu carlini 5123
./run_extra.sh mnist c standard carlini 5123
./run_extra.sh mnist c adversarial carlini 5123
./run_extra.sh mnist c relu carlini 5123
./run_extra.sh mnist a standard carlini 5919
./run_extra.sh mnist a adversarial carlini 5919
./run_extra.sh mnist a relu carlini 5919
./run_extra.sh mnist b standard carlini 5919
./run_extra.sh mnist b adversarial carlini 5919
./run_extra.sh mnist b relu carlini 5919
./run_extra.sh mnist c standard carlini 5919
./run_extra.sh mnist c adversarial carlini 5919
./run_extra.sh mnist c relu carlini 5919
./run_extra.sh mnist a standard carlini 7023
./run_extra.sh mnist a adversarial carlini 7023
./run_extra.sh mnist a relu carlini 7023
./run_extra.sh mnist b standard carlini 7023
./run_extra.sh mnist b adversarial carlini 7023
./run_extra.sh mnist b relu carlini 7023
./run_extra.sh mnist c standard carlini 7023
./run_extra.sh mnist c adversarial carlini 7023
./run_extra.sh mnist c relu carlini 7023
./run_extra.sh mnist a standard carlini 4769
