./run_extra.sh mnist c relu carlini 397
./run_extra.sh mnist a standard carlini 6646
./run_extra.sh mnist a adversarial carlini 6646
./run_extra.sh mnist a relu carlini 6646
./run_extra.sh mnist b standard carlini 6646
./run_extra.sh mnist b adversarial carlini 6646
./run_extra.sh mnist b relu carlini 6646
./run_extra.sh mnist c standard carlini 6646
./run_extra.sh mnist c adversarial carlini 6646
./run_extra.sh mnist c relu carlini 6646
./run_extra.sh mnist a standard carlini 2608
./run_extra.sh mnist a adversarial carlini 2608
./run_extra.sh mnist a relu carlini 2608
./run_extra.sh mnist b standard carlini 2608
./run_extra.sh mnist b adversarial carlini 2608
./run_extra.sh mnist b relu carlini 2608
./run_extra.sh mnist c standard carlini 2608
./run_extra.sh mnist c adversarial carlini 2608
./run_extra.sh mnist c relu carlini 2608
./run_extra.sh mnist a standard carlini 2925
./run_extra.sh mnist a adversarial carlini 2925
./run_extra.sh mnist a relu carlini 2925
./run_extra.sh mnist b standard carlini 2925
./run_extra.sh mnist b adversarial carlini 2925
./run_extra.sh mnist b relu carlini 2925
./run_extra.sh mnist c standard carlini 2925
./run_extra.sh mnist c adversarial carlini 2925
./run_extra.sh mnist c relu carlini 2925
./run_extra.sh mnist a standard carlini 3955
./run_extra.sh mnist a adversarial carlini 3955
./run_extra.sh mnist a relu carlini 3955
./run_extra.sh mnist b standard carlini 3955
./run_extra.sh mnist b adversarial carlini 3955
./run_extra.sh mnist b relu carlini 3955
./run_extra.sh mnist c standard carlini 3955
./run_extra.sh mnist c adversarial carlini 3955
./run_extra.sh mnist c relu carlini 3955
./run_extra.sh mnist a standard carlini 3860
./run_extra.sh mnist a adversarial carlini 3860
./run_extra.sh mnist a relu carlini 3860
./run_extra.sh mnist b standard carlini 3860
./run_extra.sh mnist b adversarial carlini 3860
./run_extra.sh mnist b relu carlini 3860
./run_extra.sh mnist c standard carlini 3860
./run_extra.sh mnist c adversarial carlini 3860
./run_extra.sh mnist c relu carlini 3860
./run_extra.sh mnist a standard carlini 6573
./run_extra.sh mnist a adversarial carlini 6573
./run_extra.sh mnist a relu carlini 6573
./run_extra.sh mnist b standard carlini 6573
./run_extra.sh mnist b adversarial carlini 6573
./run_extra.sh mnist b relu carlini 6573
./run_extra.sh mnist c standard carlini 6573
./run_extra.sh mnist c adversarial carlini 6573
./run_extra.sh mnist c relu carlini 6573
./run_extra.sh mnist a standard carlini 8939
./run_extra.sh mnist a adversarial carlini 8939
./run_extra.sh mnist a relu carlini 8939
./run_extra.sh mnist b standard carlini 8939
./run_extra.sh mnist b adversarial carlini 8939
./run_extra.sh mnist b relu carlini 8939
./run_extra.sh mnist c standard carlini 8939
./run_extra.sh mnist c adversarial carlini 8939
./run_extra.sh mnist c relu carlini 8939
./run_extra.sh mnist a standard carlini 899
./run_extra.sh mnist a adversarial carlini 899
./run_extra.sh mnist a relu carlini 899
./run_extra.sh mnist b standard carlini 899
./run_extra.sh mnist b adversarial carlini 899
./run_extra.sh mnist b relu carlini 899
./run_extra.sh mnist c standard carlini 899
./run_extra.sh mnist c adversarial carlini 899
./run_extra.sh mnist c relu carlini 899
./run_extra.sh mnist a standard carlini 9253
./run_extra.sh mnist a adversarial carlini 9253
./run_extra.sh mnist a relu carlini 9253
./run_extra.sh mnist b standard carlini 9253
./run_extra.sh mnist b adversarial carlini 9253
./run_extra.sh mnist b relu carlini 9253
./run_extra.sh mnist c standard carlini 9253
./run_extra.sh mnist c adversarial carlini 9253
./run_extra.sh mnist c relu carlini 9253
./run_extra.sh mnist a standard carlini 720
./run_extra.sh mnist a adversarial carlini 720
./run_extra.sh mnist a relu carlini 720
./run_extra.sh mnist b standard carlini 720
./run_extra.sh mnist b adversarial carlini 720
./run_extra.sh mnist b relu carlini 720
./run_extra.sh mnist c standard carlini 720
./run_extra.sh mnist c adversarial carlini 720
./run_extra.sh mnist c relu carlini 720
./run_extra.sh mnist a standard carlini 8178
./run_extra.sh mnist a adversarial carlini 8178
./run_extra.sh mnist a relu carlini 8178
./run_extra.sh mnist b standard carlini 8178
./run_extra.sh mnist b adversarial carlini 8178
./run_extra.sh mnist b relu carlini 8178
./run_extra.sh mnist c standard carlini 8178
./run_extra.sh mnist c adversarial carlini 8178
./run_extra.sh mnist c relu carlini 8178
./run_extra.sh mnist a standard carlini 9129
./run_extra.sh mnist a adversarial carlini 9129
./run_extra.sh mnist a relu carlini 9129
./run_extra.sh mnist b standard carlini 9129
./run_extra.sh mnist b adversarial carlini 9129
./run_extra.sh mnist b relu carlini 9129
./run_extra.sh mnist c standard carlini 9129
./run_extra.sh mnist c adversarial carlini 9129
./run_extra.sh mnist c relu carlini 9129
./run_extra.sh mnist a standard carlini 418
./run_extra.sh mnist a adversarial carlini 418
./run_extra.sh mnist a relu carlini 418
./run_extra.sh mnist b standard carlini 418
./run_extra.sh mnist b adversarial carlini 418
./run_extra.sh mnist b relu carlini 418
./run_extra.sh mnist c standard carlini 418
./run_extra.sh mnist c adversarial carlini 418
./run_extra.sh mnist c relu carlini 418
./run_extra.sh mnist a standard carlini 8719
./run_extra.sh mnist a adversarial carlini 8719
./run_extra.sh mnist a relu carlini 8719
./run_extra.sh mnist b standard carlini 8719
./run_extra.sh mnist b adversarial carlini 8719
./run_extra.sh mnist b relu carlini 8719
./run_extra.sh mnist c standard carlini 8719
./run_extra.sh mnist c adversarial carlini 8719
./run_extra.sh mnist c relu carlini 8719
./run_extra.sh mnist a standard carlini 5105
./run_extra.sh mnist a adversarial carlini 5105
./run_extra.sh mnist a relu carlini 5105
./run_extra.sh mnist b standard carlini 5105
./run_extra.sh mnist b adversarial carlini 5105
./run_extra.sh mnist b relu carlini 5105
./run_extra.sh mnist c standard carlini 5105
./run_extra.sh mnist c adversarial carlini 5105
./run_extra.sh mnist c relu carlini 5105
./run_extra.sh mnist a standard carlini 793
./run_extra.sh mnist a adversarial carlini 793
./run_extra.sh mnist a relu carlini 793
./run_extra.sh mnist b standard carlini 793
./run_extra.sh mnist b adversarial carlini 793
./run_extra.sh mnist b relu carlini 793
./run_extra.sh mnist c standard carlini 793
./run_extra.sh mnist c adversarial carlini 793
./run_extra.sh mnist c relu carlini 793
./run_extra.sh mnist a standard carlini 575
./run_extra.sh mnist a adversarial carlini 575
./run_extra.sh mnist a relu carlini 575
./run_extra.sh mnist b standard carlini 575
./run_extra.sh mnist b adversarial carlini 575
./run_extra.sh mnist b relu carlini 575
./run_extra.sh mnist c standard carlini 575
./run_extra.sh mnist c adversarial carlini 575
./run_extra.sh mnist c relu carlini 575
./run_extra.sh mnist a standard carlini 9634
./run_extra.sh mnist a adversarial carlini 9634
./run_extra.sh mnist a relu carlini 9634
./run_extra.sh mnist b standard carlini 9634
./run_extra.sh mnist b adversarial carlini 9634
./run_extra.sh mnist b relu carlini 9634
./run_extra.sh mnist c standard carlini 9634
./run_extra.sh mnist c adversarial carlini 9634
./run_extra.sh mnist c relu carlini 9634
./run_extra.sh mnist a standard carlini 3196
./run_extra.sh mnist a adversarial carlini 3196
./run_extra.sh mnist a relu carlini 3196
./run_extra.sh mnist b standard carlini 3196
./run_extra.sh mnist b adversarial carlini 3196
./run_extra.sh mnist b relu carlini 3196
./run_extra.sh mnist c standard carlini 3196
./run_extra.sh mnist c adversarial carlini 3196
./run_extra.sh mnist c relu carlini 3196
./run_extra.sh mnist a standard carlini 3072
./run_extra.sh mnist a adversarial carlini 3072
./run_extra.sh mnist a relu carlini 3072
./run_extra.sh mnist b standard carlini 3072
./run_extra.sh mnist b adversarial carlini 3072
./run_extra.sh mnist b relu carlini 3072
./run_extra.sh mnist c standard carlini 3072
./run_extra.sh mnist c adversarial carlini 3072
./run_extra.sh mnist c relu carlini 3072
./run_extra.sh mnist a standard carlini 5215
./run_extra.sh mnist a adversarial carlini 5215
./run_extra.sh mnist a relu carlini 5215
./run_extra.sh mnist b standard carlini 5215
./run_extra.sh mnist b adversarial carlini 5215
./run_extra.sh mnist b relu carlini 5215
./run_extra.sh mnist c standard carlini 5215
./run_extra.sh mnist c adversarial carlini 5215
./run_extra.sh mnist c relu carlini 5215
./run_extra.sh mnist a standard carlini 5383
./run_extra.sh mnist a adversarial carlini 5383
./run_extra.sh mnist a relu carlini 5383
./run_extra.sh mnist b standard carlini 5383
./run_extra.sh mnist b adversarial carlini 5383
./run_extra.sh mnist b relu carlini 5383
./run_extra.sh mnist c standard carlini 5383
./run_extra.sh mnist c adversarial carlini 5383
./run_extra.sh mnist c relu carlini 5383
./run_extra.sh mnist a standard carlini 392
./run_extra.sh mnist a adversarial carlini 392
./run_extra.sh mnist a relu carlini 392
./run_extra.sh mnist b standard carlini 392
./run_extra.sh mnist b adversarial carlini 392
./run_extra.sh mnist b relu carlini 392
./run_extra.sh mnist c standard carlini 392
./run_extra.sh mnist c adversarial carlini 392
./run_extra.sh mnist c relu carlini 392
./run_extra.sh mnist a standard carlini 1934
./run_extra.sh mnist a adversarial carlini 1934
./run_extra.sh mnist a relu carlini 1934
./run_extra.sh mnist b standard carlini 1934
./run_extra.sh mnist b adversarial carlini 1934
./run_extra.sh mnist b relu carlini 1934
./run_extra.sh mnist c standard carlini 1934
./run_extra.sh mnist c adversarial carlini 1934
./run_extra.sh mnist c relu carlini 1934
./run_extra.sh mnist a standard carlini 8455
./run_extra.sh mnist a adversarial carlini 8455
./run_extra.sh mnist a relu carlini 8455
./run_extra.sh mnist b standard carlini 8455
./run_extra.sh mnist b adversarial carlini 8455
./run_extra.sh mnist b relu carlini 8455
./run_extra.sh mnist c standard carlini 8455
./run_extra.sh mnist c adversarial carlini 8455
./run_extra.sh mnist c relu carlini 8455
./run_extra.sh mnist a standard carlini 8776
./run_extra.sh mnist a adversarial carlini 8776
./run_extra.sh mnist a relu carlini 8776
./run_extra.sh mnist b standard carlini 8776
./run_extra.sh mnist b adversarial carlini 8776
./run_extra.sh mnist b relu carlini 8776
./run_extra.sh mnist c standard carlini 8776
./run_extra.sh mnist c adversarial carlini 8776
./run_extra.sh mnist c relu carlini 8776
./run_extra.sh mnist a standard carlini 9910
./run_extra.sh mnist a adversarial carlini 9910
./run_extra.sh mnist a relu carlini 9910
./run_extra.sh mnist b standard carlini 9910
./run_extra.sh mnist b adversarial carlini 9910
./run_extra.sh mnist b relu carlini 9910
./run_extra.sh mnist c standard carlini 9910
./run_extra.sh mnist c adversarial carlini 9910
./run_extra.sh mnist c relu carlini 9910
./run_extra.sh mnist a standard carlini 851
./run_extra.sh mnist a adversarial carlini 851
./run_extra.sh mnist a relu carlini 851
./run_extra.sh mnist b standard carlini 851
./run_extra.sh mnist b adversarial carlini 851
./run_extra.sh mnist b relu carlini 851
./run_extra.sh mnist c standard carlini 851
./run_extra.sh mnist c adversarial carlini 851
./run_extra.sh mnist c relu carlini 851
./run_extra.sh mnist a standard carlini 6788
./run_extra.sh mnist a adversarial carlini 6788
./run_extra.sh mnist a relu carlini 6788
./run_extra.sh mnist b standard carlini 6788
./run_extra.sh mnist b adversarial carlini 6788
./run_extra.sh mnist b relu carlini 6788
./run_extra.sh mnist c standard carlini 6788
./run_extra.sh mnist c adversarial carlini 6788
./run_extra.sh mnist c relu carlini 6788
./run_extra.sh mnist a standard carlini 4004
./run_extra.sh mnist a adversarial carlini 4004
./run_extra.sh mnist a relu carlini 4004
./run_extra.sh mnist b standard carlini 4004
./run_extra.sh mnist b adversarial carlini 4004
./run_extra.sh mnist b relu carlini 4004
./run_extra.sh mnist c standard carlini 4004
./run_extra.sh mnist c adversarial carlini 4004
./run_extra.sh mnist c relu carlini 4004
./run_extra.sh mnist a standard carlini 3738
./run_extra.sh mnist a adversarial carlini 3738
./run_extra.sh mnist a relu carlini 3738
./run_extra.sh mnist b standard carlini 3738
./run_extra.sh mnist b adversarial carlini 3738
./run_extra.sh mnist b relu carlini 3738
./run_extra.sh mnist c standard carlini 3738
./run_extra.sh mnist c adversarial carlini 3738
./run_extra.sh mnist c relu carlini 3738
./run_extra.sh mnist a standard carlini 4998
./run_extra.sh mnist a adversarial carlini 4998
./run_extra.sh mnist a relu carlini 4998
./run_extra.sh mnist b standard carlini 4998
./run_extra.sh mnist b adversarial carlini 4998
./run_extra.sh mnist b relu carlini 4998
./run_extra.sh mnist c standard carlini 4998
./run_extra.sh mnist c adversarial carlini 4998
./run_extra.sh mnist c relu carlini 4998
./run_extra.sh mnist a standard carlini 799
./run_extra.sh mnist a adversarial carlini 799
./run_extra.sh mnist a relu carlini 799
./run_extra.sh mnist b standard carlini 799
./run_extra.sh mnist b adversarial carlini 799
./run_extra.sh mnist b relu carlini 799
./run_extra.sh mnist c standard carlini 799
./run_extra.sh mnist c adversarial carlini 799
./run_extra.sh mnist c relu carlini 799
./run_extra.sh mnist a standard carlini 2368
./run_extra.sh mnist a adversarial carlini 2368
./run_extra.sh mnist a relu carlini 2368
./run_extra.sh mnist b standard carlini 2368
./run_extra.sh mnist b adversarial carlini 2368
./run_extra.sh mnist b relu carlini 2368
./run_extra.sh mnist c standard carlini 2368
./run_extra.sh mnist c adversarial carlini 2368
./run_extra.sh mnist c relu carlini 2368
./run_extra.sh mnist a standard carlini 9586
./run_extra.sh mnist a adversarial carlini 9586
./run_extra.sh mnist a relu carlini 9586
./run_extra.sh mnist b standard carlini 9586
./run_extra.sh mnist b adversarial carlini 9586
./run_extra.sh mnist b relu carlini 9586
./run_extra.sh mnist c standard carlini 9586
./run_extra.sh mnist c adversarial carlini 9586
./run_extra.sh mnist c relu carlini 9586
./run_extra.sh mnist a standard carlini 6480
./run_extra.sh mnist a adversarial carlini 6480
./run_extra.sh mnist a relu carlini 6480
./run_extra.sh mnist b standard carlini 6480
./run_extra.sh mnist b adversarial carlini 6480
./run_extra.sh mnist b relu carlini 6480
./run_extra.sh mnist c standard carlini 6480
./run_extra.sh mnist c adversarial carlini 6480
./run_extra.sh mnist c relu carlini 6480
./run_extra.sh mnist a standard carlini 7075
./run_extra.sh mnist a adversarial carlini 7075
./run_extra.sh mnist a relu carlini 7075
./run_extra.sh mnist b standard carlini 7075
./run_extra.sh mnist b adversarial carlini 7075
./run_extra.sh mnist b relu carlini 7075
./run_extra.sh mnist c standard carlini 7075
./run_extra.sh mnist c adversarial carlini 7075
./run_extra.sh mnist c relu carlini 7075
./run_extra.sh mnist a standard carlini 1012
./run_extra.sh mnist a adversarial carlini 1012
./run_extra.sh mnist a relu carlini 1012
./run_extra.sh mnist b standard carlini 1012
./run_extra.sh mnist b adversarial carlini 1012
./run_extra.sh mnist b relu carlini 1012
./run_extra.sh mnist c standard carlini 1012
./run_extra.sh mnist c adversarial carlini 1012
./run_extra.sh mnist c relu carlini 1012
./run_extra.sh mnist a standard carlini 6422
./run_extra.sh mnist a adversarial carlini 6422
./run_extra.sh mnist a relu carlini 6422
./run_extra.sh mnist b standard carlini 6422
./run_extra.sh mnist b adversarial carlini 6422
./run_extra.sh mnist b relu carlini 6422
./run_extra.sh mnist c standard carlini 6422
./run_extra.sh mnist c adversarial carlini 6422
./run_extra.sh mnist c relu carlini 6422
./run_extra.sh mnist a standard carlini 8829
./run_extra.sh mnist a adversarial carlini 8829
./run_extra.sh mnist a relu carlini 8829
./run_extra.sh mnist b standard carlini 8829
./run_extra.sh mnist b adversarial carlini 8829
./run_extra.sh mnist b relu carlini 8829
./run_extra.sh mnist c standard carlini 8829
./run_extra.sh mnist c adversarial carlini 8829
./run_extra.sh mnist c relu carlini 8829
./run_extra.sh mnist a standard carlini 3583
./run_extra.sh mnist a adversarial carlini 3583
./run_extra.sh mnist a relu carlini 3583
./run_extra.sh mnist b standard carlini 3583
./run_extra.sh mnist b adversarial carlini 3583
./run_extra.sh mnist b relu carlini 3583
./run_extra.sh mnist c standard carlini 3583
./run_extra.sh mnist c adversarial carlini 3583
./run_extra.sh mnist c relu carlini 3583
./run_extra.sh mnist a standard carlini 7703
./run_extra.sh mnist a adversarial carlini 7703
./run_extra.sh mnist a relu carlini 7703
./run_extra.sh mnist b standard carlini 7703
./run_extra.sh mnist b adversarial carlini 7703
./run_extra.sh mnist b relu carlini 7703
./run_extra.sh mnist c standard carlini 7703
./run_extra.sh mnist c adversarial carlini 7703
./run_extra.sh mnist c relu carlini 7703
./run_extra.sh mnist a standard carlini 6071
./run_extra.sh mnist a adversarial carlini 6071
./run_extra.sh mnist a relu carlini 6071
./run_extra.sh mnist b standard carlini 6071
./run_extra.sh mnist b adversarial carlini 6071
./run_extra.sh mnist b relu carlini 6071
./run_extra.sh mnist c standard carlini 6071
./run_extra.sh mnist c adversarial carlini 6071
./run_extra.sh mnist c relu carlini 6071
./run_extra.sh mnist a standard carlini 9561
./run_extra.sh mnist a adversarial carlini 9561
./run_extra.sh mnist a relu carlini 9561
./run_extra.sh mnist b standard carlini 9561
./run_extra.sh mnist b adversarial carlini 9561
./run_extra.sh mnist b relu carlini 9561
./run_extra.sh mnist c standard carlini 9561
./run_extra.sh mnist c adversarial carlini 9561
./run_extra.sh mnist c relu carlini 9561
./run_extra.sh mnist a standard carlini 5411
./run_extra.sh mnist a adversarial carlini 5411
./run_extra.sh mnist a relu carlini 5411
./run_extra.sh mnist b standard carlini 5411
./run_extra.sh mnist b adversarial carlini 5411
./run_extra.sh mnist b relu carlini 5411
./run_extra.sh mnist c standard carlini 5411
./run_extra.sh mnist c adversarial carlini 5411
./run_extra.sh mnist c relu carlini 5411
./run_extra.sh mnist a standard carlini 7591
./run_extra.sh mnist a adversarial carlini 7591
./run_extra.sh mnist a relu carlini 7591
./run_extra.sh mnist b standard carlini 7591
./run_extra.sh mnist b adversarial carlini 7591
./run_extra.sh mnist b relu carlini 7591
./run_extra.sh mnist c standard carlini 7591
./run_extra.sh mnist c adversarial carlini 7591
./run_extra.sh mnist c relu carlini 7591
./run_extra.sh mnist a standard carlini 8663
./run_extra.sh mnist a adversarial carlini 8663
./run_extra.sh mnist a relu carlini 8663
./run_extra.sh mnist b standard carlini 8663
./run_extra.sh mnist b adversarial carlini 8663
./run_extra.sh mnist b relu carlini 8663
./run_extra.sh mnist c standard carlini 8663
./run_extra.sh mnist c adversarial carlini 8663
./run_extra.sh mnist c relu carlini 8663
./run_extra.sh mnist a standard carlini 4832
./run_extra.sh mnist a adversarial carlini 4832
./run_extra.sh mnist a relu carlini 4832
./run_extra.sh mnist b standard carlini 4832
./run_extra.sh mnist b adversarial carlini 4832
./run_extra.sh mnist b relu carlini 4832
./run_extra.sh mnist c standard carlini 4832
./run_extra.sh mnist c adversarial carlini 4832
./run_extra.sh mnist c relu carlini 4832
./run_extra.sh mnist a standard carlini 1684
./run_extra.sh mnist a adversarial carlini 1684
./run_extra.sh mnist a relu carlini 1684
./run_extra.sh mnist b standard carlini 1684
./run_extra.sh mnist b adversarial carlini 1684
./run_extra.sh mnist b relu carlini 1684
./run_extra.sh mnist c standard carlini 1684
./run_extra.sh mnist c adversarial carlini 1684
./run_extra.sh mnist c relu carlini 1684
./run_extra.sh mnist a standard carlini 2500
./run_extra.sh mnist a adversarial carlini 2500
./run_extra.sh mnist a relu carlini 2500
./run_extra.sh mnist b standard carlini 2500
./run_extra.sh mnist b adversarial carlini 2500
./run_extra.sh mnist b relu carlini 2500
./run_extra.sh mnist c standard carlini 2500
./run_extra.sh mnist c adversarial carlini 2500
./run_extra.sh mnist c relu carlini 2500
./run_extra.sh mnist a standard carlini 3876
./run_extra.sh mnist a adversarial carlini 3876
./run_extra.sh mnist a relu carlini 3876
./run_extra.sh mnist b standard carlini 3876
./run_extra.sh mnist b adversarial carlini 3876
./run_extra.sh mnist b relu carlini 3876
./run_extra.sh mnist c standard carlini 3876
./run_extra.sh mnist c adversarial carlini 3876
./run_extra.sh mnist c relu carlini 3876
./run_extra.sh mnist a standard carlini 3620
./run_extra.sh mnist a adversarial carlini 3620
./run_extra.sh mnist a relu carlini 3620
./run_extra.sh mnist b standard carlini 3620
./run_extra.sh mnist b adversarial carlini 3620
./run_extra.sh mnist b relu carlini 3620
./run_extra.sh mnist c standard carlini 3620
./run_extra.sh mnist c adversarial carlini 3620
./run_extra.sh mnist c relu carlini 3620
./run_extra.sh mnist a standard carlini 3899
./run_extra.sh mnist a adversarial carlini 3899
./run_extra.sh mnist a relu carlini 3899
./run_extra.sh mnist b standard carlini 3899
./run_extra.sh mnist b adversarial carlini 3899
./run_extra.sh mnist b relu carlini 3899
./run_extra.sh mnist c standard carlini 3899
./run_extra.sh mnist c adversarial carlini 3899
./run_extra.sh mnist c relu carlini 3899
./run_extra.sh mnist a standard carlini 2599
./run_extra.sh mnist a adversarial carlini 2599
./run_extra.sh mnist a relu carlini 2599
./run_extra.sh mnist b standard carlini 2599
./run_extra.sh mnist b adversarial carlini 2599
./run_extra.sh mnist b relu carlini 2599
./run_extra.sh mnist c standard carlini 2599
./run_extra.sh mnist c adversarial carlini 2599
./run_extra.sh mnist c relu carlini 2599
./run_extra.sh mnist a standard carlini 1806
./run_extra.sh mnist a adversarial carlini 1806
./run_extra.sh mnist a relu carlini 1806
./run_extra.sh mnist b standard carlini 1806
./run_extra.sh mnist b adversarial carlini 1806
./run_extra.sh mnist b relu carlini 1806
./run_extra.sh mnist c standard carlini 1806
./run_extra.sh mnist c adversarial carlini 1806
./run_extra.sh mnist c relu carlini 1806
./run_extra.sh mnist a standard carlini 566
./run_extra.sh mnist a adversarial carlini 566
./run_extra.sh mnist a relu carlini 566
./run_extra.sh mnist b standard carlini 566
./run_extra.sh mnist b adversarial carlini 566
./run_extra.sh mnist b relu carlini 566
./run_extra.sh mnist c standard carlini 566
./run_extra.sh mnist c adversarial carlini 566
./run_extra.sh mnist c relu carlini 566
./run_extra.sh mnist a standard carlini 6061
./run_extra.sh mnist a adversarial carlini 6061
./run_extra.sh mnist a relu carlini 6061
./run_extra.sh mnist b standard carlini 6061
./run_extra.sh mnist b adversarial carlini 6061
./run_extra.sh mnist b relu carlini 6061
./run_extra.sh mnist c standard carlini 6061
./run_extra.sh mnist c adversarial carlini 6061
./run_extra.sh mnist c relu carlini 6061
./run_extra.sh mnist a standard carlini 5719
./run_extra.sh mnist a adversarial carlini 5719
./run_extra.sh mnist a relu carlini 5719
./run_extra.sh mnist b standard carlini 5719
./run_extra.sh mnist b adversarial carlini 5719
./run_extra.sh mnist b relu carlini 5719
./run_extra.sh mnist c standard carlini 5719
./run_extra.sh mnist c adversarial carlini 5719
./run_extra.sh mnist c relu carlini 5719
./run_extra.sh mnist a standard carlini 3150
./run_extra.sh mnist a adversarial carlini 3150
./run_extra.sh mnist a relu carlini 3150
./run_extra.sh mnist b standard carlini 3150
./run_extra.sh mnist b adversarial carlini 3150
./run_extra.sh mnist b relu carlini 3150
./run_extra.sh mnist c standard carlini 3150
./run_extra.sh mnist c adversarial carlini 3150
./run_extra.sh mnist c relu carlini 3150
./run_extra.sh mnist a standard carlini 8173
./run_extra.sh mnist a adversarial carlini 8173
./run_extra.sh mnist a relu carlini 8173
./run_extra.sh mnist b standard carlini 8173
./run_extra.sh mnist b adversarial carlini 8173
./run_extra.sh mnist b relu carlini 8173
./run_extra.sh mnist c standard carlini 8173
./run_extra.sh mnist c adversarial carlini 8173
./run_extra.sh mnist c relu carlini 8173
./run_extra.sh mnist a standard carlini 6066
./run_extra.sh mnist a adversarial carlini 6066
./run_extra.sh mnist a relu carlini 6066
./run_extra.sh mnist b standard carlini 6066
./run_extra.sh mnist b adversarial carlini 6066
./run_extra.sh mnist b relu carlini 6066
./run_extra.sh mnist c standard carlini 6066
./run_extra.sh mnist c adversarial carlini 6066
./run_extra.sh mnist c relu carlini 6066
./run_extra.sh mnist a standard carlini 8725
./run_extra.sh mnist a adversarial carlini 8725
./run_extra.sh mnist a relu carlini 8725
./run_extra.sh mnist b standard carlini 8725
./run_extra.sh mnist b adversarial carlini 8725
./run_extra.sh mnist b relu carlini 8725
./run_extra.sh mnist c standard carlini 8725
./run_extra.sh mnist c adversarial carlini 8725
./run_extra.sh mnist c relu carlini 8725
./run_extra.sh mnist a standard carlini 581
./run_extra.sh mnist a adversarial carlini 581
./run_extra.sh mnist a relu carlini 581
./run_extra.sh mnist b standard carlini 581
./run_extra.sh mnist b adversarial carlini 581
./run_extra.sh mnist b relu carlini 581
./run_extra.sh mnist c standard carlini 581
./run_extra.sh mnist c adversarial carlini 581
./run_extra.sh mnist c relu carlini 581
./run_extra.sh mnist a standard carlini 4001
./run_extra.sh mnist a adversarial carlini 4001
./run_extra.sh mnist a relu carlini 4001
./run_extra.sh mnist b standard carlini 4001
./run_extra.sh mnist b adversarial carlini 4001
./run_extra.sh mnist b relu carlini 4001
./run_extra.sh mnist c standard carlini 4001
./run_extra.sh mnist c adversarial carlini 4001
./run_extra.sh mnist c relu carlini 4001
./run_extra.sh mnist a standard carlini 8644
./run_extra.sh mnist a adversarial carlini 8644
./run_extra.sh mnist a relu carlini 8644
./run_extra.sh mnist b standard carlini 8644
./run_extra.sh mnist b adversarial carlini 8644
./run_extra.sh mnist b relu carlini 8644
./run_extra.sh mnist c standard carlini 8644
./run_extra.sh mnist c adversarial carlini 8644
./run_extra.sh mnist c relu carlini 8644
./run_extra.sh mnist a standard carlini 5010
./run_extra.sh mnist a adversarial carlini 5010
./run_extra.sh mnist a relu carlini 5010
./run_extra.sh mnist b standard carlini 5010
./run_extra.sh mnist b adversarial carlini 5010
./run_extra.sh mnist b relu carlini 5010
./run_extra.sh mnist c standard carlini 5010
./run_extra.sh mnist c adversarial carlini 5010
./run_extra.sh mnist c relu carlini 5010
./run_extra.sh mnist a standard carlini 6027
./run_extra.sh mnist a adversarial carlini 6027
./run_extra.sh mnist a relu carlini 6027
./run_extra.sh mnist b standard carlini 6027
./run_extra.sh mnist b adversarial carlini 6027
./run_extra.sh mnist b relu carlini 6027
./run_extra.sh mnist c standard carlini 6027
./run_extra.sh mnist c adversarial carlini 6027
./run_extra.sh mnist c relu carlini 6027
./run_extra.sh mnist a standard carlini 3043
./run_extra.sh mnist a adversarial carlini 3043
./run_extra.sh mnist a relu carlini 3043
./run_extra.sh mnist b standard carlini 3043
./run_extra.sh mnist b adversarial carlini 3043
./run_extra.sh mnist b relu carlini 3043
./run_extra.sh mnist c standard carlini 3043
./run_extra.sh mnist c adversarial carlini 3043
./run_extra.sh mnist c relu carlini 3043
./run_extra.sh mnist a standard carlini 6575
./run_extra.sh mnist a adversarial carlini 6575
./run_extra.sh mnist a relu carlini 6575
./run_extra.sh mnist b standard carlini 6575
./run_extra.sh mnist b adversarial carlini 6575
./run_extra.sh mnist b relu carlini 6575
./run_extra.sh mnist c standard carlini 6575
./run_extra.sh mnist c adversarial carlini 6575
./run_extra.sh mnist c relu carlini 6575
./run_extra.sh mnist a standard carlini 4603
./run_extra.sh mnist a adversarial carlini 4603
./run_extra.sh mnist a relu carlini 4603
./run_extra.sh mnist b standard carlini 4603
./run_extra.sh mnist b adversarial carlini 4603
./run_extra.sh mnist b relu carlini 4603
./run_extra.sh mnist c standard carlini 4603
./run_extra.sh mnist c adversarial carlini 4603
./run_extra.sh mnist c relu carlini 4603
./run_extra.sh mnist a standard carlini 6611
./run_extra.sh mnist a adversarial carlini 6611
./run_extra.sh mnist a relu carlini 6611
./run_extra.sh mnist b standard carlini 6611
./run_extra.sh mnist b adversarial carlini 6611
./run_extra.sh mnist b relu carlini 6611
./run_extra.sh mnist c standard carlini 6611
./run_extra.sh mnist c adversarial carlini 6611
./run_extra.sh mnist c relu carlini 6611
./run_extra.sh mnist a standard carlini 1359
./run_extra.sh mnist a adversarial carlini 1359
./run_extra.sh mnist a relu carlini 1359
./run_extra.sh mnist b standard carlini 1359
./run_extra.sh mnist b adversarial carlini 1359
./run_extra.sh mnist b relu carlini 1359
./run_extra.sh mnist c standard carlini 1359
./run_extra.sh mnist c adversarial carlini 1359
./run_extra.sh mnist c relu carlini 1359
./run_extra.sh mnist a standard carlini 6108
./run_extra.sh mnist a adversarial carlini 6108
./run_extra.sh mnist a relu carlini 6108
./run_extra.sh mnist b standard carlini 6108
./run_extra.sh mnist b adversarial carlini 6108
./run_extra.sh mnist b relu carlini 6108
./run_extra.sh mnist c standard carlini 6108
./run_extra.sh mnist c adversarial carlini 6108
./run_extra.sh mnist c relu carlini 6108
./run_extra.sh mnist a standard carlini 5359
./run_extra.sh mnist a adversarial carlini 5359
./run_extra.sh mnist a relu carlini 5359
./run_extra.sh mnist b standard carlini 5359
./run_extra.sh mnist b adversarial carlini 5359
./run_extra.sh mnist b relu carlini 5359
./run_extra.sh mnist c standard carlini 5359
./run_extra.sh mnist c adversarial carlini 5359
./run_extra.sh mnist c relu carlini 5359
./run_extra.sh mnist a standard carlini 8261
./run_extra.sh mnist a adversarial carlini 8261
./run_extra.sh mnist a relu carlini 8261
./run_extra.sh mnist b standard carlini 8261
./run_extra.sh mnist b adversarial carlini 8261
./run_extra.sh mnist b relu carlini 8261
./run_extra.sh mnist c standard carlini 8261
./run_extra.sh mnist c adversarial carlini 8261
./run_extra.sh mnist c relu carlini 8261
./run_extra.sh mnist a standard carlini 2285
./run_extra.sh mnist a adversarial carlini 2285
./run_extra.sh mnist a relu carlini 2285
./run_extra.sh mnist b standard carlini 2285
./run_extra.sh mnist b adversarial carlini 2285
./run_extra.sh mnist b relu carlini 2285
./run_extra.sh mnist c standard carlini 2285
./run_extra.sh mnist c adversarial carlini 2285
./run_extra.sh mnist c relu carlini 2285
./run_extra.sh mnist a standard carlini 4541
./run_extra.sh mnist a adversarial carlini 4541
./run_extra.sh mnist a relu carlini 4541
./run_extra.sh mnist b standard carlini 4541
./run_extra.sh mnist b adversarial carlini 4541
./run_extra.sh mnist b relu carlini 4541
./run_extra.sh mnist c standard carlini 4541
./run_extra.sh mnist c adversarial carlini 4541
./run_extra.sh mnist c relu carlini 4541
./run_extra.sh mnist a standard carlini 4012
./run_extra.sh mnist a adversarial carlini 4012
./run_extra.sh mnist a relu carlini 4012
./run_extra.sh mnist b standard carlini 4012
./run_extra.sh mnist b adversarial carlini 4012
./run_extra.sh mnist b relu carlini 4012
./run_extra.sh mnist c standard carlini 4012
./run_extra.sh mnist c adversarial carlini 4012
./run_extra.sh mnist c relu carlini 4012
./run_extra.sh mnist a standard carlini 4106
./run_extra.sh mnist a adversarial carlini 4106
./run_extra.sh mnist a relu carlini 4106
./run_extra.sh mnist b standard carlini 4106
./run_extra.sh mnist b adversarial carlini 4106
./run_extra.sh mnist b relu carlini 4106
./run_extra.sh mnist c standard carlini 4106
./run_extra.sh mnist c adversarial carlini 4106
./run_extra.sh mnist c relu carlini 4106
./run_extra.sh mnist a standard carlini 9887
./run_extra.sh mnist a adversarial carlini 9887
./run_extra.sh mnist a relu carlini 9887
./run_extra.sh mnist b standard carlini 9887
./run_extra.sh mnist b adversarial carlini 9887
./run_extra.sh mnist b relu carlini 9887
./run_extra.sh mnist c standard carlini 9887
./run_extra.sh mnist c adversarial carlini 9887
./run_extra.sh mnist c relu carlini 9887
./run_extra.sh mnist a standard carlini 2664
./run_extra.sh mnist a adversarial carlini 2664
./run_extra.sh mnist a relu carlini 2664
./run_extra.sh mnist b standard carlini 2664
./run_extra.sh mnist b adversarial carlini 2664
./run_extra.sh mnist b relu carlini 2664
./run_extra.sh mnist c standard carlini 2664
./run_extra.sh mnist c adversarial carlini 2664
./run_extra.sh mnist c relu carlini 2664
./run_extra.sh mnist a standard carlini 7975
./run_extra.sh mnist a adversarial carlini 7975
./run_extra.sh mnist a relu carlini 7975
./run_extra.sh mnist b standard carlini 7975
./run_extra.sh mnist b adversarial carlini 7975
./run_extra.sh mnist b relu carlini 7975
./run_extra.sh mnist c standard carlini 7975
./run_extra.sh mnist c adversarial carlini 7975
./run_extra.sh mnist c relu carlini 7975
./run_extra.sh mnist a standard carlini 767
./run_extra.sh mnist a adversarial carlini 767
./run_extra.sh mnist a relu carlini 767
./run_extra.sh mnist b standard carlini 767
./run_extra.sh mnist b adversarial carlini 767
./run_extra.sh mnist b relu carlini 767
./run_extra.sh mnist c standard carlini 767
./run_extra.sh mnist c adversarial carlini 767
./run_extra.sh mnist c relu carlini 767
./run_extra.sh mnist a standard carlini 8463
./run_extra.sh mnist a adversarial carlini 8463
./run_extra.sh mnist a relu carlini 8463
./run_extra.sh mnist b standard carlini 8463
./run_extra.sh mnist b adversarial carlini 8463
./run_extra.sh mnist b relu carlini 8463
./run_extra.sh mnist c standard carlini 8463
./run_extra.sh mnist c adversarial carlini 8463
./run_extra.sh mnist c relu carlini 8463
./run_extra.sh mnist a standard carlini 828
./run_extra.sh mnist a adversarial carlini 828
./run_extra.sh mnist a relu carlini 828
./run_extra.sh mnist b standard carlini 828
./run_extra.sh mnist b adversarial carlini 828
./run_extra.sh mnist b relu carlini 828
./run_extra.sh mnist c standard carlini 828
./run_extra.sh mnist c adversarial carlini 828
./run_extra.sh mnist c relu carlini 828
./run_extra.sh mnist a standard carlini 1379
./run_extra.sh mnist a adversarial carlini 1379
./run_extra.sh mnist a relu carlini 1379
./run_extra.sh mnist b standard carlini 1379
./run_extra.sh mnist b adversarial carlini 1379
./run_extra.sh mnist b relu carlini 1379
./run_extra.sh mnist c standard carlini 1379
./run_extra.sh mnist c adversarial carlini 1379
./run_extra.sh mnist c relu carlini 1379
./run_extra.sh mnist a standard carlini 3268
./run_extra.sh mnist a adversarial carlini 3268
./run_extra.sh mnist a relu carlini 3268
./run_extra.sh mnist b standard carlini 3268
./run_extra.sh mnist b adversarial carlini 3268
./run_extra.sh mnist b relu carlini 3268
./run_extra.sh mnist c standard carlini 3268
./run_extra.sh mnist c adversarial carlini 3268
./run_extra.sh mnist c relu carlini 3268
./run_extra.sh mnist a standard carlini 7057
./run_extra.sh mnist a adversarial carlini 7057
./run_extra.sh mnist a relu carlini 7057
./run_extra.sh mnist b standard carlini 7057
./run_extra.sh mnist b adversarial carlini 7057
./run_extra.sh mnist b relu carlini 7057
./run_extra.sh mnist c standard carlini 7057
./run_extra.sh mnist c adversarial carlini 7057
./run_extra.sh mnist c relu carlini 7057
./run_extra.sh mnist a standard carlini 6655
./run_extra.sh mnist a adversarial carlini 6655
./run_extra.sh mnist a relu carlini 6655
./run_extra.sh mnist b standard carlini 6655
./run_extra.sh mnist b adversarial carlini 6655
./run_extra.sh mnist b relu carlini 6655
./run_extra.sh mnist c standard carlini 6655
./run_extra.sh mnist c adversarial carlini 6655
./run_extra.sh mnist c relu carlini 6655
./run_extra.sh mnist a standard carlini 5503
./run_extra.sh mnist a adversarial carlini 5503
./run_extra.sh mnist a relu carlini 5503
./run_extra.sh mnist b standard carlini 5503
./run_extra.sh mnist b adversarial carlini 5503
./run_extra.sh mnist b relu carlini 5503
./run_extra.sh mnist c standard carlini 5503
./run_extra.sh mnist c adversarial carlini 5503
./run_extra.sh mnist c relu carlini 5503
./run_extra.sh mnist a standard carlini 343
./run_extra.sh mnist a adversarial carlini 343
./run_extra.sh mnist a relu carlini 343
./run_extra.sh mnist b standard carlini 343
./run_extra.sh mnist b adversarial carlini 343
./run_extra.sh mnist b relu carlini 343
./run_extra.sh mnist c standard carlini 343
./run_extra.sh mnist c adversarial carlini 343
./run_extra.sh mnist c relu carlini 343
./run_extra.sh mnist a standard carlini 860
./run_extra.sh mnist a adversarial carlini 860
./run_extra.sh mnist a relu carlini 860
./run_extra.sh mnist b standard carlini 860
./run_extra.sh mnist b adversarial carlini 860
./run_extra.sh mnist b relu carlini 860
./run_extra.sh mnist c standard carlini 860
./run_extra.sh mnist c adversarial carlini 860
./run_extra.sh mnist c relu carlini 860
./run_extra.sh mnist a standard carlini 9268
./run_extra.sh mnist a adversarial carlini 9268
./run_extra.sh mnist a relu carlini 9268
./run_extra.sh mnist b standard carlini 9268
./run_extra.sh mnist b adversarial carlini 9268
./run_extra.sh mnist b relu carlini 9268
./run_extra.sh mnist c standard carlini 9268
./run_extra.sh mnist c adversarial carlini 9268
./run_extra.sh mnist c relu carlini 9268
./run_extra.sh mnist a standard carlini 4642
./run_extra.sh mnist a adversarial carlini 4642
./run_extra.sh mnist a relu carlini 4642
./run_extra.sh mnist b standard carlini 4642
./run_extra.sh mnist b adversarial carlini 4642
./run_extra.sh mnist b relu carlini 4642
./run_extra.sh mnist c standard carlini 4642
./run_extra.sh mnist c adversarial carlini 4642
./run_extra.sh mnist c relu carlini 4642
./run_extra.sh mnist a standard carlini 8884
./run_extra.sh mnist a adversarial carlini 8884
./run_extra.sh mnist a relu carlini 8884
./run_extra.sh mnist b standard carlini 8884
./run_extra.sh mnist b adversarial carlini 8884
./run_extra.sh mnist b relu carlini 8884
./run_extra.sh mnist c standard carlini 8884
./run_extra.sh mnist c adversarial carlini 8884
./run_extra.sh mnist c relu carlini 8884
./run_extra.sh mnist a standard carlini 7727
./run_extra.sh mnist a adversarial carlini 7727
./run_extra.sh mnist a relu carlini 7727
./run_extra.sh mnist b standard carlini 7727
./run_extra.sh mnist b adversarial carlini 7727
./run_extra.sh mnist b relu carlini 7727
./run_extra.sh mnist c standard carlini 7727
./run_extra.sh mnist c adversarial carlini 7727
./run_extra.sh mnist c relu carlini 7727
./run_extra.sh mnist a standard carlini 8685
./run_extra.sh mnist a adversarial carlini 8685
./run_extra.sh mnist a relu carlini 8685
./run_extra.sh mnist b standard carlini 8685
./run_extra.sh mnist b adversarial carlini 8685
./run_extra.sh mnist b relu carlini 8685
./run_extra.sh mnist c standard carlini 8685
./run_extra.sh mnist c adversarial carlini 8685
./run_extra.sh mnist c relu carlini 8685
./run_extra.sh mnist a standard carlini 3657
./run_extra.sh mnist a adversarial carlini 3657
./run_extra.sh mnist a relu carlini 3657
./run_extra.sh mnist b standard carlini 3657
./run_extra.sh mnist b adversarial carlini 3657
./run_extra.sh mnist b relu carlini 3657
./run_extra.sh mnist c standard carlini 3657
./run_extra.sh mnist c adversarial carlini 3657
./run_extra.sh mnist c relu carlini 3657
./run_extra.sh mnist a standard carlini 6511
./run_extra.sh mnist a adversarial carlini 6511
./run_extra.sh mnist a relu carlini 6511
./run_extra.sh mnist b standard carlini 6511
./run_extra.sh mnist b adversarial carlini 6511
./run_extra.sh mnist b relu carlini 6511
./run_extra.sh mnist c standard carlini 6511
./run_extra.sh mnist c adversarial carlini 6511
./run_extra.sh mnist c relu carlini 6511
./run_extra.sh mnist a standard carlini 7255
./run_extra.sh mnist a adversarial carlini 7255
./run_extra.sh mnist a relu carlini 7255
./run_extra.sh mnist b standard carlini 7255
./run_extra.sh mnist b adversarial carlini 7255
./run_extra.sh mnist b relu carlini 7255
./run_extra.sh mnist c standard carlini 7255
./run_extra.sh mnist c adversarial carlini 7255
./run_extra.sh mnist c relu carlini 7255
./run_extra.sh mnist a standard carlini 8110
./run_extra.sh mnist a adversarial carlini 8110
./run_extra.sh mnist a relu carlini 8110
./run_extra.sh mnist b standard carlini 8110
./run_extra.sh mnist b adversarial carlini 8110
./run_extra.sh mnist b relu carlini 8110
./run_extra.sh mnist c standard carlini 8110
./run_extra.sh mnist c adversarial carlini 8110
./run_extra.sh mnist c relu carlini 8110
./run_extra.sh mnist a standard carlini 9159
./run_extra.sh mnist a adversarial carlini 9159
./run_extra.sh mnist a relu carlini 9159
./run_extra.sh mnist b standard carlini 9159
./run_extra.sh mnist b adversarial carlini 9159
./run_extra.sh mnist b relu carlini 9159
./run_extra.sh mnist c standard carlini 9159
./run_extra.sh mnist c adversarial carlini 9159
./run_extra.sh mnist c relu carlini 9159
./run_extra.sh mnist a standard carlini 2945
./run_extra.sh mnist a adversarial carlini 2945
./run_extra.sh mnist a relu carlini 2945
./run_extra.sh mnist b standard carlini 2945
./run_extra.sh mnist b adversarial carlini 2945
./run_extra.sh mnist b relu carlini 2945
./run_extra.sh mnist c standard carlini 2945
./run_extra.sh mnist c adversarial carlini 2945
./run_extra.sh mnist c relu carlini 2945
./run_extra.sh mnist a standard carlini 3568
./run_extra.sh mnist a adversarial carlini 3568
./run_extra.sh mnist a relu carlini 3568
./run_extra.sh mnist b standard carlini 3568
./run_extra.sh mnist b adversarial carlini 3568
./run_extra.sh mnist b relu carlini 3568
./run_extra.sh mnist c standard carlini 3568
./run_extra.sh mnist c adversarial carlini 3568
./run_extra.sh mnist c relu carlini 3568
./run_extra.sh mnist a standard carlini 1876
./run_extra.sh mnist a adversarial carlini 1876
./run_extra.sh mnist a relu carlini 1876
./run_extra.sh mnist b standard carlini 1876
./run_extra.sh mnist b adversarial carlini 1876
./run_extra.sh mnist b relu carlini 1876
./run_extra.sh mnist c standard carlini 1876
./run_extra.sh mnist c adversarial carlini 1876
./run_extra.sh mnist c relu carlini 1876
./run_extra.sh mnist a standard carlini 1334
./run_extra.sh mnist a adversarial carlini 1334
./run_extra.sh mnist a relu carlini 1334
./run_extra.sh mnist b standard carlini 1334
./run_extra.sh mnist b adversarial carlini 1334
./run_extra.sh mnist b relu carlini 1334
./run_extra.sh mnist c standard carlini 1334
./run_extra.sh mnist c adversarial carlini 1334
./run_extra.sh mnist c relu carlini 1334
./run_extra.sh mnist a standard carlini 1641
./run_extra.sh mnist a adversarial carlini 1641
./run_extra.sh mnist a relu carlini 1641
./run_extra.sh mnist b standard carlini 1641
./run_extra.sh mnist b adversarial carlini 1641
./run_extra.sh mnist b relu carlini 1641
./run_extra.sh mnist c standard carlini 1641
./run_extra.sh mnist c adversarial carlini 1641
./run_extra.sh mnist c relu carlini 1641
./run_extra.sh mnist a standard carlini 8842
./run_extra.sh mnist a adversarial carlini 8842
./run_extra.sh mnist a relu carlini 8842
./run_extra.sh mnist b standard carlini 8842
./run_extra.sh mnist b adversarial carlini 8842
./run_extra.sh mnist b relu carlini 8842
./run_extra.sh mnist c standard carlini 8842
./run_extra.sh mnist c adversarial carlini 8842
./run_extra.sh mnist c relu carlini 8842
./run_extra.sh mnist a standard carlini 9411
./run_extra.sh mnist a adversarial carlini 9411
./run_extra.sh mnist a relu carlini 9411
./run_extra.sh mnist b standard carlini 9411
./run_extra.sh mnist b adversarial carlini 9411
./run_extra.sh mnist b relu carlini 9411
./run_extra.sh mnist c standard carlini 9411
./run_extra.sh mnist c adversarial carlini 9411
./run_extra.sh mnist c relu carlini 9411
./run_extra.sh mnist a standard carlini 886
./run_extra.sh mnist a adversarial carlini 886
./run_extra.sh mnist a relu carlini 886
./run_extra.sh mnist b standard carlini 886
./run_extra.sh mnist b adversarial carlini 886
./run_extra.sh mnist b relu carlini 886
./run_extra.sh mnist c standard carlini 886
./run_extra.sh mnist c adversarial carlini 886
./run_extra.sh mnist c relu carlini 886
./run_extra.sh mnist a standard carlini 1960
./run_extra.sh mnist a adversarial carlini 1960
./run_extra.sh mnist a relu carlini 1960
./run_extra.sh mnist b standard carlini 1960
./run_extra.sh mnist b adversarial carlini 1960
./run_extra.sh mnist b relu carlini 1960
./run_extra.sh mnist c standard carlini 1960
./run_extra.sh mnist c adversarial carlini 1960
./run_extra.sh mnist c relu carlini 1960
./run_extra.sh mnist a standard carlini 617
./run_extra.sh mnist a adversarial carlini 617
./run_extra.sh mnist a relu carlini 617
./run_extra.sh mnist b standard carlini 617
./run_extra.sh mnist b adversarial carlini 617
./run_extra.sh mnist b relu carlini 617
./run_extra.sh mnist c standard carlini 617
./run_extra.sh mnist c adversarial carlini 617
./run_extra.sh mnist c relu carlini 617
./run_extra.sh mnist a standard carlini 6593
./run_extra.sh mnist a adversarial carlini 6593
./run_extra.sh mnist a relu carlini 6593
./run_extra.sh mnist b standard carlini 6593
./run_extra.sh mnist b adversarial carlini 6593
./run_extra.sh mnist b relu carlini 6593
./run_extra.sh mnist c standard carlini 6593
./run_extra.sh mnist c adversarial carlini 6593
./run_extra.sh mnist c relu carlini 6593
./run_extra.sh mnist a standard carlini 3504
./run_extra.sh mnist a adversarial carlini 3504
./run_extra.sh mnist a relu carlini 3504
./run_extra.sh mnist b standard carlini 3504
./run_extra.sh mnist b adversarial carlini 3504
./run_extra.sh mnist b relu carlini 3504
./run_extra.sh mnist c standard carlini 3504
./run_extra.sh mnist c adversarial carlini 3504
./run_extra.sh mnist c relu carlini 3504
./run_extra.sh mnist a standard carlini 7569
./run_extra.sh mnist a adversarial carlini 7569
./run_extra.sh mnist a relu carlini 7569
./run_extra.sh mnist b standard carlini 7569
./run_extra.sh mnist b adversarial carlini 7569
./run_extra.sh mnist b relu carlini 7569
./run_extra.sh mnist c standard carlini 7569
./run_extra.sh mnist c adversarial carlini 7569
./run_extra.sh mnist c relu carlini 7569
./run_extra.sh mnist a standard carlini 7441
./run_extra.sh mnist a adversarial carlini 7441
./run_extra.sh mnist a relu carlini 7441
./run_extra.sh mnist b standard carlini 7441
./run_extra.sh mnist b adversarial carlini 7441
./run_extra.sh mnist b relu carlini 7441
./run_extra.sh mnist c standard carlini 7441
./run_extra.sh mnist c adversarial carlini 7441
./run_extra.sh mnist c relu carlini 7441
./run_extra.sh mnist a standard carlini 5226
./run_extra.sh mnist a adversarial carlini 5226
./run_extra.sh mnist a relu carlini 5226
./run_extra.sh mnist b standard carlini 5226
./run_extra.sh mnist b adversarial carlini 5226
./run_extra.sh mnist b relu carlini 5226
./run_extra.sh mnist c standard carlini 5226
./run_extra.sh mnist c adversarial carlini 5226
./run_extra.sh mnist c relu carlini 5226
./run_extra.sh mnist a standard carlini 5027
./run_extra.sh mnist a adversarial carlini 5027
./run_extra.sh mnist a relu carlini 5027
./run_extra.sh mnist b standard carlini 5027
./run_extra.sh mnist b adversarial carlini 5027
./run_extra.sh mnist b relu carlini 5027
./run_extra.sh mnist c standard carlini 5027
./run_extra.sh mnist c adversarial carlini 5027
./run_extra.sh mnist c relu carlini 5027
./run_extra.sh mnist a standard carlini 6817
./run_extra.sh mnist a adversarial carlini 6817
./run_extra.sh mnist a relu carlini 6817
./run_extra.sh mnist b standard carlini 6817
./run_extra.sh mnist b adversarial carlini 6817
./run_extra.sh mnist b relu carlini 6817
./run_extra.sh mnist c standard carlini 6817
./run_extra.sh mnist c adversarial carlini 6817
./run_extra.sh mnist c relu carlini 6817
./run_extra.sh mnist a standard carlini 7981
./run_extra.sh mnist a adversarial carlini 7981
./run_extra.sh mnist a relu carlini 7981
./run_extra.sh mnist b standard carlini 7981
./run_extra.sh mnist b adversarial carlini 7981
./run_extra.sh mnist b relu carlini 7981
./run_extra.sh mnist c standard carlini 7981
./run_extra.sh mnist c adversarial carlini 7981
./run_extra.sh mnist c relu carlini 7981
./run_extra.sh mnist a standard carlini 3251
./run_extra.sh mnist a adversarial carlini 3251
./run_extra.sh mnist a relu carlini 3251
./run_extra.sh mnist b standard carlini 3251
./run_extra.sh mnist b adversarial carlini 3251
./run_extra.sh mnist b relu carlini 3251
./run_extra.sh mnist c standard carlini 3251
./run_extra.sh mnist c adversarial carlini 3251
./run_extra.sh mnist c relu carlini 3251
./run_extra.sh mnist a standard carlini 3689
./run_extra.sh mnist a adversarial carlini 3689
./run_extra.sh mnist a relu carlini 3689
./run_extra.sh mnist b standard carlini 3689
./run_extra.sh mnist b adversarial carlini 3689
./run_extra.sh mnist b relu carlini 3689
./run_extra.sh mnist c standard carlini 3689
./run_extra.sh mnist c adversarial carlini 3689
./run_extra.sh mnist c relu carlini 3689
./run_extra.sh mnist a standard carlini 5463
./run_extra.sh mnist a adversarial carlini 5463
./run_extra.sh mnist a relu carlini 5463
./run_extra.sh mnist b standard carlini 5463
./run_extra.sh mnist b adversarial carlini 5463
./run_extra.sh mnist b relu carlini 5463
./run_extra.sh mnist c standard carlini 5463
./run_extra.sh mnist c adversarial carlini 5463
./run_extra.sh mnist c relu carlini 5463
./run_extra.sh mnist a standard carlini 2304
./run_extra.sh mnist a adversarial carlini 2304
./run_extra.sh mnist a relu carlini 2304
./run_extra.sh mnist b standard carlini 2304
./run_extra.sh mnist b adversarial carlini 2304
./run_extra.sh mnist b relu carlini 2304
./run_extra.sh mnist c standard carlini 2304
./run_extra.sh mnist c adversarial carlini 2304
./run_extra.sh mnist c relu carlini 2304
./run_extra.sh mnist a standard carlini 4339
./run_extra.sh mnist a adversarial carlini 4339
./run_extra.sh mnist a relu carlini 4339
./run_extra.sh mnist b standard carlini 4339
./run_extra.sh mnist b adversarial carlini 4339
./run_extra.sh mnist b relu carlini 4339
./run_extra.sh mnist c standard carlini 4339
./run_extra.sh mnist c adversarial carlini 4339
./run_extra.sh mnist c relu carlini 4339
./run_extra.sh mnist a standard carlini 2993
./run_extra.sh mnist a adversarial carlini 2993
./run_extra.sh mnist a relu carlini 2993
./run_extra.sh mnist b standard carlini 2993
./run_extra.sh mnist b adversarial carlini 2993
./run_extra.sh mnist b relu carlini 2993
./run_extra.sh mnist c standard carlini 2993
./run_extra.sh mnist c adversarial carlini 2993
./run_extra.sh mnist c relu carlini 2993
./run_extra.sh mnist a standard carlini 5473
./run_extra.sh mnist a adversarial carlini 5473
./run_extra.sh mnist a relu carlini 5473
./run_extra.sh mnist b standard carlini 5473
./run_extra.sh mnist b adversarial carlini 5473
./run_extra.sh mnist b relu carlini 5473
./run_extra.sh mnist c standard carlini 5473
./run_extra.sh mnist c adversarial carlini 5473
./run_extra.sh mnist c relu carlini 5473
./run_extra.sh mnist a standard carlini 7386
./run_extra.sh mnist a adversarial carlini 7386
./run_extra.sh mnist a relu carlini 7386
./run_extra.sh mnist b standard carlini 7386
./run_extra.sh mnist b adversarial carlini 7386
./run_extra.sh mnist b relu carlini 7386
./run_extra.sh mnist c standard carlini 7386
./run_extra.sh mnist c adversarial carlini 7386
./run_extra.sh mnist c relu carlini 7386
./run_extra.sh mnist a standard carlini 2545
./run_extra.sh mnist a adversarial carlini 2545
./run_extra.sh mnist a relu carlini 2545
./run_extra.sh mnist b standard carlini 2545
./run_extra.sh mnist b adversarial carlini 2545
./run_extra.sh mnist b relu carlini 2545
./run_extra.sh mnist c standard carlini 2545
./run_extra.sh mnist c adversarial carlini 2545
./run_extra.sh mnist c relu carlini 2545
./run_extra.sh mnist a standard carlini 5311
./run_extra.sh mnist a adversarial carlini 5311
./run_extra.sh mnist a relu carlini 5311
./run_extra.sh mnist b standard carlini 5311
./run_extra.sh mnist b adversarial carlini 5311
./run_extra.sh mnist b relu carlini 5311
./run_extra.sh mnist c standard carlini 5311
./run_extra.sh mnist c adversarial carlini 5311
./run_extra.sh mnist c relu carlini 5311
./run_extra.sh mnist a standard carlini 6318
./run_extra.sh mnist a adversarial carlini 6318
./run_extra.sh mnist a relu carlini 6318
./run_extra.sh mnist b standard carlini 6318
./run_extra.sh mnist b adversarial carlini 6318
./run_extra.sh mnist b relu carlini 6318
./run_extra.sh mnist c standard carlini 6318
./run_extra.sh mnist c adversarial carlini 6318
./run_extra.sh mnist c relu carlini 6318
./run_extra.sh mnist a standard carlini 6660
./run_extra.sh mnist a adversarial carlini 6660
./run_extra.sh mnist a relu carlini 6660
./run_extra.sh mnist b standard carlini 6660
./run_extra.sh mnist b adversarial carlini 6660
./run_extra.sh mnist b relu carlini 6660
./run_extra.sh mnist c standard carlini 6660
./run_extra.sh mnist c adversarial carlini 6660
./run_extra.sh mnist c relu carlini 6660
./run_extra.sh mnist a standard carlini 1382
./run_extra.sh mnist a adversarial carlini 1382
./run_extra.sh mnist a relu carlini 1382
./run_extra.sh mnist b standard carlini 1382
./run_extra.sh mnist b adversarial carlini 1382
./run_extra.sh mnist b relu carlini 1382
./run_extra.sh mnist c standard carlini 1382
./run_extra.sh mnist c adversarial carlini 1382
./run_extra.sh mnist c relu carlini 1382
./run_extra.sh mnist a standard carlini 8568
./run_extra.sh mnist a adversarial carlini 8568
./run_extra.sh mnist a relu carlini 8568
./run_extra.sh mnist b standard carlini 8568
./run_extra.sh mnist b adversarial carlini 8568
./run_extra.sh mnist b relu carlini 8568
./run_extra.sh mnist c standard carlini 8568
./run_extra.sh mnist c adversarial carlini 8568
./run_extra.sh mnist c relu carlini 8568
./run_extra.sh mnist a standard carlini 7470
./run_extra.sh mnist a adversarial carlini 7470
./run_extra.sh mnist a relu carlini 7470
./run_extra.sh mnist b standard carlini 7470
./run_extra.sh mnist b adversarial carlini 7470
./run_extra.sh mnist b relu carlini 7470
./run_extra.sh mnist c standard carlini 7470
./run_extra.sh mnist c adversarial carlini 7470
./run_extra.sh mnist c relu carlini 7470
./run_extra.sh mnist a standard carlini 2693
./run_extra.sh mnist a adversarial carlini 2693
./run_extra.sh mnist a relu carlini 2693
./run_extra.sh mnist b standard carlini 2693
./run_extra.sh mnist b adversarial carlini 2693
./run_extra.sh mnist b relu carlini 2693
./run_extra.sh mnist c standard carlini 2693
./run_extra.sh mnist c adversarial carlini 2693
./run_extra.sh mnist c relu carlini 2693
./run_extra.sh mnist a standard carlini 7529
./run_extra.sh mnist a adversarial carlini 7529
./run_extra.sh mnist a relu carlini 7529
./run_extra.sh mnist b standard carlini 7529
./run_extra.sh mnist b adversarial carlini 7529
./run_extra.sh mnist b relu carlini 7529
./run_extra.sh mnist c standard carlini 7529
./run_extra.sh mnist c adversarial carlini 7529
./run_extra.sh mnist c relu carlini 7529
./run_extra.sh mnist a standard carlini 5867
./run_extra.sh mnist a adversarial carlini 5867
./run_extra.sh mnist a relu carlini 5867
./run_extra.sh mnist b standard carlini 5867
./run_extra.sh mnist b adversarial carlini 5867
./run_extra.sh mnist b relu carlini 5867
./run_extra.sh mnist c standard carlini 5867
./run_extra.sh mnist c adversarial carlini 5867
./run_extra.sh mnist c relu carlini 5867
./run_extra.sh mnist a standard carlini 5131
./run_extra.sh mnist a adversarial carlini 5131
./run_extra.sh mnist a relu carlini 5131
./run_extra.sh mnist b standard carlini 5131
./run_extra.sh mnist b adversarial carlini 5131
./run_extra.sh mnist b relu carlini 5131
./run_extra.sh mnist c standard carlini 5131
./run_extra.sh mnist c adversarial carlini 5131
./run_extra.sh mnist c relu carlini 5131
./run_extra.sh mnist a standard carlini 3957
./run_extra.sh mnist a adversarial carlini 3957
./run_extra.sh mnist a relu carlini 3957
./run_extra.sh mnist b standard carlini 3957
./run_extra.sh mnist b adversarial carlini 3957
./run_extra.sh mnist b relu carlini 3957
./run_extra.sh mnist c standard carlini 3957
./run_extra.sh mnist c adversarial carlini 3957
./run_extra.sh mnist c relu carlini 3957
./run_extra.sh mnist a standard carlini 1779
./run_extra.sh mnist a adversarial carlini 1779
./run_extra.sh mnist a relu carlini 1779
./run_extra.sh mnist b standard carlini 1779
./run_extra.sh mnist b adversarial carlini 1779
./run_extra.sh mnist b relu carlini 1779
./run_extra.sh mnist c standard carlini 1779
./run_extra.sh mnist c adversarial carlini 1779
./run_extra.sh mnist c relu carlini 1779
./run_extra.sh mnist a standard carlini 9170
./run_extra.sh mnist a adversarial carlini 9170
./run_extra.sh mnist a relu carlini 9170
./run_extra.sh mnist b standard carlini 9170
./run_extra.sh mnist b adversarial carlini 9170
./run_extra.sh mnist b relu carlini 9170
./run_extra.sh mnist c standard carlini 9170
./run_extra.sh mnist c adversarial carlini 9170
./run_extra.sh mnist c relu carlini 9170
./run_extra.sh mnist a standard carlini 662
./run_extra.sh mnist a adversarial carlini 662
./run_extra.sh mnist a relu carlini 662
./run_extra.sh mnist b standard carlini 662
./run_extra.sh mnist b adversarial carlini 662
./run_extra.sh mnist b relu carlini 662
./run_extra.sh mnist c standard carlini 662
./run_extra.sh mnist c adversarial carlini 662
./run_extra.sh mnist c relu carlini 662
./run_extra.sh mnist a standard carlini 6004
./run_extra.sh mnist a adversarial carlini 6004
./run_extra.sh mnist a relu carlini 6004
./run_extra.sh mnist b standard carlini 6004
./run_extra.sh mnist b adversarial carlini 6004
./run_extra.sh mnist b relu carlini 6004
./run_extra.sh mnist c standard carlini 6004
./run_extra.sh mnist c adversarial carlini 6004
./run_extra.sh mnist c relu carlini 6004
./run_extra.sh mnist a standard carlini 3413
./run_extra.sh mnist a adversarial carlini 3413
./run_extra.sh mnist a relu carlini 3413
./run_extra.sh mnist b standard carlini 3413
./run_extra.sh mnist b adversarial carlini 3413
./run_extra.sh mnist b relu carlini 3413
./run_extra.sh mnist c standard carlini 3413
./run_extra.sh mnist c adversarial carlini 3413
./run_extra.sh mnist c relu carlini 3413
./run_extra.sh mnist a standard carlini 2050
./run_extra.sh mnist a adversarial carlini 2050
./run_extra.sh mnist a relu carlini 2050
./run_extra.sh mnist b standard carlini 2050
./run_extra.sh mnist b adversarial carlini 2050
./run_extra.sh mnist b relu carlini 2050
./run_extra.sh mnist c standard carlini 2050
./run_extra.sh mnist c adversarial carlini 2050
./run_extra.sh mnist c relu carlini 2050
./run_extra.sh mnist a standard carlini 559
./run_extra.sh mnist a adversarial carlini 559
./run_extra.sh mnist a relu carlini 559
./run_extra.sh mnist b standard carlini 559
./run_extra.sh mnist b adversarial carlini 559
./run_extra.sh mnist b relu carlini 559
./run_extra.sh mnist c standard carlini 559
./run_extra.sh mnist c adversarial carlini 559
./run_extra.sh mnist c relu carlini 559
./run_extra.sh mnist a standard carlini 2486
./run_extra.sh mnist a adversarial carlini 2486
./run_extra.sh mnist a relu carlini 2486
./run_extra.sh mnist b standard carlini 2486
./run_extra.sh mnist b adversarial carlini 2486
./run_extra.sh mnist b relu carlini 2486
./run_extra.sh mnist c standard carlini 2486
./run_extra.sh mnist c adversarial carlini 2486
./run_extra.sh mnist c relu carlini 2486
./run_extra.sh mnist a standard carlini 7721
./run_extra.sh mnist a adversarial carlini 7721
./run_extra.sh mnist a relu carlini 7721
./run_extra.sh mnist b standard carlini 7721
./run_extra.sh mnist b adversarial carlini 7721
./run_extra.sh mnist b relu carlini 7721
./run_extra.sh mnist c standard carlini 7721
./run_extra.sh mnist c adversarial carlini 7721
./run_extra.sh mnist c relu carlini 7721
./run_extra.sh mnist a standard carlini 2624
./run_extra.sh mnist a adversarial carlini 2624
./run_extra.sh mnist a relu carlini 2624
./run_extra.sh mnist b standard carlini 2624
./run_extra.sh mnist b adversarial carlini 2624
./run_extra.sh mnist b relu carlini 2624
./run_extra.sh mnist c standard carlini 2624
./run_extra.sh mnist c adversarial carlini 2624
./run_extra.sh mnist c relu carlini 2624
./run_extra.sh mnist a standard carlini 9248
./run_extra.sh mnist a adversarial carlini 9248
./run_extra.sh mnist a relu carlini 9248
./run_extra.sh mnist b standard carlini 9248
./run_extra.sh mnist b adversarial carlini 9248
./run_extra.sh mnist b relu carlini 9248
./run_extra.sh mnist c standard carlini 9248
./run_extra.sh mnist c adversarial carlini 9248
./run_extra.sh mnist c relu carlini 9248
./run_extra.sh mnist a standard carlini 3316
./run_extra.sh mnist a adversarial carlini 3316
./run_extra.sh mnist a relu carlini 3316
./run_extra.sh mnist b standard carlini 3316
./run_extra.sh mnist b adversarial carlini 3316
./run_extra.sh mnist b relu carlini 3316
./run_extra.sh mnist c standard carlini 3316
./run_extra.sh mnist c adversarial carlini 3316
./run_extra.sh mnist c relu carlini 3316
./run_extra.sh mnist a standard carlini 8926
./run_extra.sh mnist a adversarial carlini 8926
./run_extra.sh mnist a relu carlini 8926
./run_extra.sh mnist b standard carlini 8926
./run_extra.sh mnist b adversarial carlini 8926
./run_extra.sh mnist b relu carlini 8926
./run_extra.sh mnist c standard carlini 8926
./run_extra.sh mnist c adversarial carlini 8926
./run_extra.sh mnist c relu carlini 8926
./run_extra.sh mnist a standard carlini 2585
./run_extra.sh mnist a adversarial carlini 2585
./run_extra.sh mnist a relu carlini 2585
./run_extra.sh mnist b standard carlini 2585
./run_extra.sh mnist b adversarial carlini 2585
./run_extra.sh mnist b relu carlini 2585
./run_extra.sh mnist c standard carlini 2585
./run_extra.sh mnist c adversarial carlini 2585
./run_extra.sh mnist c relu carlini 2585
./run_extra.sh mnist a standard carlini 5770
./run_extra.sh mnist a adversarial carlini 5770
./run_extra.sh mnist a relu carlini 5770
./run_extra.sh mnist b standard carlini 5770
./run_extra.sh mnist b adversarial carlini 5770
./run_extra.sh mnist b relu carlini 5770
./run_extra.sh mnist c standard carlini 5770
./run_extra.sh mnist c adversarial carlini 5770
./run_extra.sh mnist c relu carlini 5770
./run_extra.sh mnist a standard carlini 1656
./run_extra.sh mnist a adversarial carlini 1656
./run_extra.sh mnist a relu carlini 1656
./run_extra.sh mnist b standard carlini 1656
./run_extra.sh mnist b adversarial carlini 1656
./run_extra.sh mnist b relu carlini 1656
./run_extra.sh mnist c standard carlini 1656
./run_extra.sh mnist c adversarial carlini 1656
./run_extra.sh mnist c relu carlini 1656
./run_extra.sh mnist a standard carlini 889
./run_extra.sh mnist a adversarial carlini 889
./run_extra.sh mnist a relu carlini 889
./run_extra.sh mnist b standard carlini 889
./run_extra.sh mnist b adversarial carlini 889
./run_extra.sh mnist b relu carlini 889
./run_extra.sh mnist c standard carlini 889
./run_extra.sh mnist c adversarial carlini 889
./run_extra.sh mnist c relu carlini 889
./run_extra.sh mnist a standard carlini 7977
./run_extra.sh mnist a adversarial carlini 7977
./run_extra.sh mnist a relu carlini 7977
./run_extra.sh mnist b standard carlini 7977
./run_extra.sh mnist b adversarial carlini 7977
./run_extra.sh mnist b relu carlini 7977
./run_extra.sh mnist c standard carlini 7977
./run_extra.sh mnist c adversarial carlini 7977
./run_extra.sh mnist c relu carlini 7977
./run_extra.sh mnist a standard carlini 5735
./run_extra.sh mnist a adversarial carlini 5735
./run_extra.sh mnist a relu carlini 5735
./run_extra.sh mnist b standard carlini 5735
./run_extra.sh mnist b adversarial carlini 5735
./run_extra.sh mnist b relu carlini 5735
./run_extra.sh mnist c standard carlini 5735
./run_extra.sh mnist c adversarial carlini 5735
./run_extra.sh mnist c relu carlini 5735
./run_extra.sh mnist a standard carlini 6972
./run_extra.sh mnist a adversarial carlini 6972
./run_extra.sh mnist a relu carlini 6972
./run_extra.sh mnist b standard carlini 6972
./run_extra.sh mnist b adversarial carlini 6972
./run_extra.sh mnist b relu carlini 6972
./run_extra.sh mnist c standard carlini 6972
./run_extra.sh mnist c adversarial carlini 6972
./run_extra.sh mnist c relu carlini 6972
./run_extra.sh mnist a standard carlini 305
./run_extra.sh mnist a adversarial carlini 305
./run_extra.sh mnist a relu carlini 305
./run_extra.sh mnist b standard carlini 305
./run_extra.sh mnist b adversarial carlini 305
./run_extra.sh mnist b relu carlini 305
./run_extra.sh mnist c standard carlini 305
./run_extra.sh mnist c adversarial carlini 305
./run_extra.sh mnist c relu carlini 305
./run_extra.sh mnist a standard carlini 1837
./run_extra.sh mnist a adversarial carlini 1837
./run_extra.sh mnist a relu carlini 1837
./run_extra.sh mnist b standard carlini 1837
./run_extra.sh mnist b adversarial carlini 1837
./run_extra.sh mnist b relu carlini 1837
./run_extra.sh mnist c standard carlini 1837
./run_extra.sh mnist c adversarial carlini 1837
./run_extra.sh mnist c relu carlini 1837
./run_extra.sh mnist a standard carlini 9284
./run_extra.sh mnist a adversarial carlini 9284
./run_extra.sh mnist a relu carlini 9284
./run_extra.sh mnist b standard carlini 9284
./run_extra.sh mnist b adversarial carlini 9284
./run_extra.sh mnist b relu carlini 9284
./run_extra.sh mnist c standard carlini 9284
./run_extra.sh mnist c adversarial carlini 9284
./run_extra.sh mnist c relu carlini 9284
./run_extra.sh mnist a standard carlini 8579
./run_extra.sh mnist a adversarial carlini 8579
./run_extra.sh mnist a relu carlini 8579
./run_extra.sh mnist b standard carlini 8579
./run_extra.sh mnist b adversarial carlini 8579
./run_extra.sh mnist b relu carlini 8579
./run_extra.sh mnist c standard carlini 8579
./run_extra.sh mnist c adversarial carlini 8579
./run_extra.sh mnist c relu carlini 8579
./run_extra.sh mnist a standard carlini 1187
./run_extra.sh mnist a adversarial carlini 1187
./run_extra.sh mnist a relu carlini 1187
./run_extra.sh mnist b standard carlini 1187
./run_extra.sh mnist b adversarial carlini 1187
./run_extra.sh mnist b relu carlini 1187
./run_extra.sh mnist c standard carlini 1187
./run_extra.sh mnist c adversarial carlini 1187
./run_extra.sh mnist c relu carlini 1187
./run_extra.sh mnist a standard carlini 9811
./run_extra.sh mnist a adversarial carlini 9811
./run_extra.sh mnist a relu carlini 9811
./run_extra.sh mnist b standard carlini 9811
./run_extra.sh mnist b adversarial carlini 9811
./run_extra.sh mnist b relu carlini 9811
./run_extra.sh mnist c standard carlini 9811
./run_extra.sh mnist c adversarial carlini 9811
./run_extra.sh mnist c relu carlini 9811
./run_extra.sh mnist a standard carlini 6344
./run_extra.sh mnist a adversarial carlini 6344
./run_extra.sh mnist a relu carlini 6344
./run_extra.sh mnist b standard carlini 6344
./run_extra.sh mnist b adversarial carlini 6344
./run_extra.sh mnist b relu carlini 6344
./run_extra.sh mnist c standard carlini 6344
./run_extra.sh mnist c adversarial carlini 6344
./run_extra.sh mnist c relu carlini 6344
./run_extra.sh mnist a standard carlini 735
./run_extra.sh mnist a adversarial carlini 735
./run_extra.sh mnist a relu carlini 735
./run_extra.sh mnist b standard carlini 735
./run_extra.sh mnist b adversarial carlini 735
./run_extra.sh mnist b relu carlini 735
./run_extra.sh mnist c standard carlini 735
./run_extra.sh mnist c adversarial carlini 735
./run_extra.sh mnist c relu carlini 735
./run_extra.sh mnist a standard carlini 8161
./run_extra.sh mnist a adversarial carlini 8161
./run_extra.sh mnist a relu carlini 8161
./run_extra.sh mnist b standard carlini 8161
./run_extra.sh mnist b adversarial carlini 8161
./run_extra.sh mnist b relu carlini 8161
./run_extra.sh mnist c standard carlini 8161
./run_extra.sh mnist c adversarial carlini 8161
./run_extra.sh mnist c relu carlini 8161
./run_extra.sh mnist a standard carlini 2132
./run_extra.sh mnist a adversarial carlini 2132
./run_extra.sh mnist a relu carlini 2132
./run_extra.sh mnist b standard carlini 2132
./run_extra.sh mnist b adversarial carlini 2132
./run_extra.sh mnist b relu carlini 2132
./run_extra.sh mnist c standard carlini 2132
./run_extra.sh mnist c adversarial carlini 2132
./run_extra.sh mnist c relu carlini 2132
./run_extra.sh mnist a standard carlini 2173
./run_extra.sh mnist a adversarial carlini 2173
./run_extra.sh mnist a relu carlini 2173
./run_extra.sh mnist b standard carlini 2173
./run_extra.sh mnist b adversarial carlini 2173
./run_extra.sh mnist b relu carlini 2173
./run_extra.sh mnist c standard carlini 2173
./run_extra.sh mnist c adversarial carlini 2173
./run_extra.sh mnist c relu carlini 2173
./run_extra.sh mnist a standard carlini 2512
./run_extra.sh mnist a adversarial carlini 2512
./run_extra.sh mnist a relu carlini 2512
./run_extra.sh mnist b standard carlini 2512
./run_extra.sh mnist b adversarial carlini 2512
./run_extra.sh mnist b relu carlini 2512
./run_extra.sh mnist c standard carlini 2512
./run_extra.sh mnist c adversarial carlini 2512
./run_extra.sh mnist c relu carlini 2512
./run_extra.sh mnist a standard carlini 459
./run_extra.sh mnist a adversarial carlini 459
./run_extra.sh mnist a relu carlini 459
./run_extra.sh mnist b standard carlini 459
./run_extra.sh mnist b adversarial carlini 459
./run_extra.sh mnist b relu carlini 459
./run_extra.sh mnist c standard carlini 459
./run_extra.sh mnist c adversarial carlini 459
./run_extra.sh mnist c relu carlini 459
./run_extra.sh mnist a standard carlini 9952
./run_extra.sh mnist a adversarial carlini 9952
./run_extra.sh mnist a relu carlini 9952
./run_extra.sh mnist b standard carlini 9952
./run_extra.sh mnist b adversarial carlini 9952
./run_extra.sh mnist b relu carlini 9952
./run_extra.sh mnist c standard carlini 9952
./run_extra.sh mnist c adversarial carlini 9952
./run_extra.sh mnist c relu carlini 9952
./run_extra.sh mnist a standard carlini 1538
./run_extra.sh mnist a adversarial carlini 1538
./run_extra.sh mnist a relu carlini 1538
./run_extra.sh mnist b standard carlini 1538
./run_extra.sh mnist b adversarial carlini 1538
./run_extra.sh mnist b relu carlini 1538
./run_extra.sh mnist c standard carlini 1538
./run_extra.sh mnist c adversarial carlini 1538
./run_extra.sh mnist c relu carlini 1538
./run_extra.sh mnist a standard carlini 8325
./run_extra.sh mnist a adversarial carlini 8325
./run_extra.sh mnist a relu carlini 8325
./run_extra.sh mnist b standard carlini 8325
./run_extra.sh mnist b adversarial carlini 8325
./run_extra.sh mnist b relu carlini 8325
./run_extra.sh mnist c standard carlini 8325
./run_extra.sh mnist c adversarial carlini 8325
./run_extra.sh mnist c relu carlini 8325
./run_extra.sh mnist a standard carlini 400
./run_extra.sh mnist a adversarial carlini 400
./run_extra.sh mnist a relu carlini 400
./run_extra.sh mnist b standard carlini 400
./run_extra.sh mnist b adversarial carlini 400
./run_extra.sh mnist b relu carlini 400
./run_extra.sh mnist c standard carlini 400
./run_extra.sh mnist c adversarial carlini 400
./run_extra.sh mnist c relu carlini 400
./run_extra.sh mnist a standard carlini 1748
./run_extra.sh mnist a adversarial carlini 1748
./run_extra.sh mnist a relu carlini 1748
./run_extra.sh mnist b standard carlini 1748
./run_extra.sh mnist b adversarial carlini 1748
./run_extra.sh mnist b relu carlini 1748
./run_extra.sh mnist c standard carlini 1748
./run_extra.sh mnist c adversarial carlini 1748
./run_extra.sh mnist c relu carlini 1748
./run_extra.sh mnist a standard carlini 5837
./run_extra.sh mnist a adversarial carlini 5837
./run_extra.sh mnist a relu carlini 5837
./run_extra.sh mnist b standard carlini 5837
./run_extra.sh mnist b adversarial carlini 5837
./run_extra.sh mnist b relu carlini 5837
./run_extra.sh mnist c standard carlini 5837
./run_extra.sh mnist c adversarial carlini 5837
./run_extra.sh mnist c relu carlini 5837
./run_extra.sh mnist a standard carlini 8337
./run_extra.sh mnist a adversarial carlini 8337
./run_extra.sh mnist a relu carlini 8337
./run_extra.sh mnist b standard carlini 8337
./run_extra.sh mnist b adversarial carlini 8337
./run_extra.sh mnist b relu carlini 8337
./run_extra.sh mnist c standard carlini 8337
./run_extra.sh mnist c adversarial carlini 8337
./run_extra.sh mnist c relu carlini 8337
./run_extra.sh mnist a standard carlini 2378
./run_extra.sh mnist a adversarial carlini 2378
./run_extra.sh mnist a relu carlini 2378
./run_extra.sh mnist b standard carlini 2378
./run_extra.sh mnist b adversarial carlini 2378
./run_extra.sh mnist b relu carlini 2378
./run_extra.sh mnist c standard carlini 2378
./run_extra.sh mnist c adversarial carlini 2378
./run_extra.sh mnist c relu carlini 2378
./run_extra.sh mnist a standard carlini 1653
./run_extra.sh mnist a adversarial carlini 1653
./run_extra.sh mnist a relu carlini 1653
./run_extra.sh mnist b standard carlini 1653
./run_extra.sh mnist b adversarial carlini 1653
./run_extra.sh mnist b relu carlini 1653
./run_extra.sh mnist c standard carlini 1653
./run_extra.sh mnist c adversarial carlini 1653
./run_extra.sh mnist c relu carlini 1653
./run_extra.sh mnist a standard carlini 6376
./run_extra.sh mnist a adversarial carlini 6376
./run_extra.sh mnist a relu carlini 6376
./run_extra.sh mnist b standard carlini 6376
./run_extra.sh mnist b adversarial carlini 6376
./run_extra.sh mnist b relu carlini 6376
./run_extra.sh mnist c standard carlini 6376
./run_extra.sh mnist c adversarial carlini 6376
./run_extra.sh mnist c relu carlini 6376
./run_extra.sh mnist a standard carlini 6509
./run_extra.sh mnist a adversarial carlini 6509
./run_extra.sh mnist a relu carlini 6509
./run_extra.sh mnist b standard carlini 6509
./run_extra.sh mnist b adversarial carlini 6509
./run_extra.sh mnist b relu carlini 6509
./run_extra.sh mnist c standard carlini 6509
./run_extra.sh mnist c adversarial carlini 6509
./run_extra.sh mnist c relu carlini 6509
./run_extra.sh mnist a standard carlini 5500
./run_extra.sh mnist a adversarial carlini 5500
./run_extra.sh mnist a relu carlini 5500
./run_extra.sh mnist b standard carlini 5500
./run_extra.sh mnist b adversarial carlini 5500
./run_extra.sh mnist b relu carlini 5500
./run_extra.sh mnist c standard carlini 5500
./run_extra.sh mnist c adversarial carlini 5500
./run_extra.sh mnist c relu carlini 5500
./run_extra.sh mnist a standard carlini 6487
./run_extra.sh mnist a adversarial carlini 6487
./run_extra.sh mnist a relu carlini 6487
./run_extra.sh mnist b standard carlini 6487
./run_extra.sh mnist b adversarial carlini 6487
./run_extra.sh mnist b relu carlini 6487
./run_extra.sh mnist c standard carlini 6487
./run_extra.sh mnist c adversarial carlini 6487
./run_extra.sh mnist c relu carlini 6487
./run_extra.sh mnist a standard carlini 7914
./run_extra.sh mnist a adversarial carlini 7914
./run_extra.sh mnist a relu carlini 7914
./run_extra.sh mnist b standard carlini 7914
./run_extra.sh mnist b adversarial carlini 7914
./run_extra.sh mnist b relu carlini 7914
./run_extra.sh mnist c standard carlini 7914
./run_extra.sh mnist c adversarial carlini 7914
./run_extra.sh mnist c relu carlini 7914
./run_extra.sh mnist a standard carlini 4418
./run_extra.sh mnist a adversarial carlini 4418
./run_extra.sh mnist a relu carlini 4418
./run_extra.sh mnist b standard carlini 4418
./run_extra.sh mnist b adversarial carlini 4418
./run_extra.sh mnist b relu carlini 4418
./run_extra.sh mnist c standard carlini 4418
./run_extra.sh mnist c adversarial carlini 4418
./run_extra.sh mnist c relu carlini 4418
./run_extra.sh mnist a standard carlini 6221
./run_extra.sh mnist a adversarial carlini 6221
./run_extra.sh mnist a relu carlini 6221
./run_extra.sh mnist b standard carlini 6221
./run_extra.sh mnist b adversarial carlini 6221
./run_extra.sh mnist b relu carlini 6221
./run_extra.sh mnist c standard carlini 6221
./run_extra.sh mnist c adversarial carlini 6221
./run_extra.sh mnist c relu carlini 6221
./run_extra.sh mnist a standard carlini 2156
./run_extra.sh mnist a adversarial carlini 2156
./run_extra.sh mnist a relu carlini 2156
./run_extra.sh mnist b standard carlini 2156
./run_extra.sh mnist b adversarial carlini 2156
./run_extra.sh mnist b relu carlini 2156
./run_extra.sh mnist c standard carlini 2156
./run_extra.sh mnist c adversarial carlini 2156
./run_extra.sh mnist c relu carlini 2156
./run_extra.sh mnist a standard carlini 7946
./run_extra.sh mnist a adversarial carlini 7946
./run_extra.sh mnist a relu carlini 7946
./run_extra.sh mnist b standard carlini 7946
./run_extra.sh mnist b adversarial carlini 7946
./run_extra.sh mnist b relu carlini 7946
./run_extra.sh mnist c standard carlini 7946
./run_extra.sh mnist c adversarial carlini 7946
./run_extra.sh mnist c relu carlini 7946
./run_extra.sh mnist a standard carlini 3625
./run_extra.sh mnist a adversarial carlini 3625
./run_extra.sh mnist a relu carlini 3625
./run_extra.sh mnist b standard carlini 3625
./run_extra.sh mnist b adversarial carlini 3625
./run_extra.sh mnist b relu carlini 3625
./run_extra.sh mnist c standard carlini 3625
./run_extra.sh mnist c adversarial carlini 3625
./run_extra.sh mnist c relu carlini 3625
./run_extra.sh mnist a standard carlini 8241
./run_extra.sh mnist a adversarial carlini 8241
./run_extra.sh mnist a relu carlini 8241
./run_extra.sh mnist b standard carlini 8241
./run_extra.sh mnist b adversarial carlini 8241
./run_extra.sh mnist b relu carlini 8241
./run_extra.sh mnist c standard carlini 8241
./run_extra.sh mnist c adversarial carlini 8241
./run_extra.sh mnist c relu carlini 8241
./run_extra.sh mnist a standard carlini 6014
./run_extra.sh mnist a adversarial carlini 6014
./run_extra.sh mnist a relu carlini 6014
./run_extra.sh mnist b standard carlini 6014
./run_extra.sh mnist b adversarial carlini 6014
./run_extra.sh mnist b relu carlini 6014
./run_extra.sh mnist c standard carlini 6014
./run_extra.sh mnist c adversarial carlini 6014
./run_extra.sh mnist c relu carlini 6014
./run_extra.sh mnist a standard carlini 753
./run_extra.sh mnist a adversarial carlini 753
./run_extra.sh mnist a relu carlini 753
./run_extra.sh mnist b standard carlini 753
./run_extra.sh mnist b adversarial carlini 753
./run_extra.sh mnist b relu carlini 753
./run_extra.sh mnist c standard carlini 753
./run_extra.sh mnist c adversarial carlini 753
./run_extra.sh mnist c relu carlini 753
./run_extra.sh mnist a standard carlini 1469
./run_extra.sh mnist a adversarial carlini 1469
./run_extra.sh mnist a relu carlini 1469
./run_extra.sh mnist b standard carlini 1469
./run_extra.sh mnist b adversarial carlini 1469
./run_extra.sh mnist b relu carlini 1469
./run_extra.sh mnist c standard carlini 1469
./run_extra.sh mnist c adversarial carlini 1469
./run_extra.sh mnist c relu carlini 1469
./run_extra.sh mnist a standard carlini 6231
./run_extra.sh mnist a adversarial carlini 6231
./run_extra.sh mnist a relu carlini 6231
./run_extra.sh mnist b standard carlini 6231
./run_extra.sh mnist b adversarial carlini 6231
./run_extra.sh mnist b relu carlini 6231
./run_extra.sh mnist c standard carlini 6231
./run_extra.sh mnist c adversarial carlini 6231
./run_extra.sh mnist c relu carlini 6231
./run_extra.sh mnist a standard carlini 4536
./run_extra.sh mnist a adversarial carlini 4536
./run_extra.sh mnist a relu carlini 4536
./run_extra.sh mnist b standard carlini 4536
./run_extra.sh mnist b adversarial carlini 4536
./run_extra.sh mnist b relu carlini 4536
./run_extra.sh mnist c standard carlini 4536
./run_extra.sh mnist c adversarial carlini 4536
./run_extra.sh mnist c relu carlini 4536
./run_extra.sh mnist a standard carlini 2838
./run_extra.sh mnist a adversarial carlini 2838
./run_extra.sh mnist a relu carlini 2838
./run_extra.sh mnist b standard carlini 2838
./run_extra.sh mnist b adversarial carlini 2838
./run_extra.sh mnist b relu carlini 2838
./run_extra.sh mnist c standard carlini 2838
./run_extra.sh mnist c adversarial carlini 2838
./run_extra.sh mnist c relu carlini 2838
./run_extra.sh mnist a standard carlini 1329
./run_extra.sh mnist a adversarial carlini 1329
./run_extra.sh mnist a relu carlini 1329
./run_extra.sh mnist b standard carlini 1329
./run_extra.sh mnist b adversarial carlini 1329
./run_extra.sh mnist b relu carlini 1329
./run_extra.sh mnist c standard carlini 1329
./run_extra.sh mnist c adversarial carlini 1329
./run_extra.sh mnist c relu carlini 1329
./run_extra.sh mnist a standard carlini 1140
./run_extra.sh mnist a adversarial carlini 1140
./run_extra.sh mnist a relu carlini 1140
./run_extra.sh mnist b standard carlini 1140
./run_extra.sh mnist b adversarial carlini 1140
./run_extra.sh mnist b relu carlini 1140
./run_extra.sh mnist c standard carlini 1140
./run_extra.sh mnist c adversarial carlini 1140
./run_extra.sh mnist c relu carlini 1140
./run_extra.sh mnist a standard carlini 1385
./run_extra.sh mnist a adversarial carlini 1385
./run_extra.sh mnist a relu carlini 1385
./run_extra.sh mnist b standard carlini 1385
./run_extra.sh mnist b adversarial carlini 1385
./run_extra.sh mnist b relu carlini 1385
./run_extra.sh mnist c standard carlini 1385
./run_extra.sh mnist c adversarial carlini 1385
./run_extra.sh mnist c relu carlini 1385
./run_extra.sh mnist a standard carlini 6564
./run_extra.sh mnist a adversarial carlini 6564
./run_extra.sh mnist a relu carlini 6564
./run_extra.sh mnist b standard carlini 6564
./run_extra.sh mnist b adversarial carlini 6564
./run_extra.sh mnist b relu carlini 6564
./run_extra.sh mnist c standard carlini 6564
./run_extra.sh mnist c adversarial carlini 6564
./run_extra.sh mnist c relu carlini 6564
./run_extra.sh mnist a standard carlini 5316
./run_extra.sh mnist a adversarial carlini 5316
./run_extra.sh mnist a relu carlini 5316
./run_extra.sh mnist b standard carlini 5316
./run_extra.sh mnist b adversarial carlini 5316
./run_extra.sh mnist b relu carlini 5316
./run_extra.sh mnist c standard carlini 5316
./run_extra.sh mnist c adversarial carlini 5316
./run_extra.sh mnist c relu carlini 5316
./run_extra.sh mnist a standard carlini 7924
./run_extra.sh mnist a adversarial carlini 7924
./run_extra.sh mnist a relu carlini 7924
./run_extra.sh mnist b standard carlini 7924
./run_extra.sh mnist b adversarial carlini 7924
./run_extra.sh mnist b relu carlini 7924
./run_extra.sh mnist c standard carlini 7924
./run_extra.sh mnist c adversarial carlini 7924
./run_extra.sh mnist c relu carlini 7924
./run_extra.sh mnist a standard carlini 2110
./run_extra.sh mnist a adversarial carlini 2110
./run_extra.sh mnist a relu carlini 2110
./run_extra.sh mnist b standard carlini 2110
./run_extra.sh mnist b adversarial carlini 2110
./run_extra.sh mnist b relu carlini 2110
./run_extra.sh mnist c standard carlini 2110
./run_extra.sh mnist c adversarial carlini 2110
./run_extra.sh mnist c relu carlini 2110
./run_extra.sh mnist a standard carlini 1809
./run_extra.sh mnist a adversarial carlini 1809
./run_extra.sh mnist a relu carlini 1809
./run_extra.sh mnist b standard carlini 1809
./run_extra.sh mnist b adversarial carlini 1809
./run_extra.sh mnist b relu carlini 1809
./run_extra.sh mnist c standard carlini 1809
./run_extra.sh mnist c adversarial carlini 1809
./run_extra.sh mnist c relu carlini 1809
./run_extra.sh mnist a standard carlini 2436
./run_extra.sh mnist a adversarial carlini 2436
./run_extra.sh mnist a relu carlini 2436
./run_extra.sh mnist b standard carlini 2436
./run_extra.sh mnist b adversarial carlini 2436
./run_extra.sh mnist b relu carlini 2436
./run_extra.sh mnist c standard carlini 2436
./run_extra.sh mnist c adversarial carlini 2436
./run_extra.sh mnist c relu carlini 2436
./run_extra.sh mnist a standard carlini 5398
./run_extra.sh mnist a adversarial carlini 5398
./run_extra.sh mnist a relu carlini 5398
./run_extra.sh mnist b standard carlini 5398
./run_extra.sh mnist b adversarial carlini 5398
./run_extra.sh mnist b relu carlini 5398
./run_extra.sh mnist c standard carlini 5398
./run_extra.sh mnist c adversarial carlini 5398
./run_extra.sh mnist c relu carlini 5398
./run_extra.sh mnist a standard carlini 647
./run_extra.sh mnist a adversarial carlini 647
./run_extra.sh mnist a relu carlini 647
./run_extra.sh mnist b standard carlini 647
./run_extra.sh mnist b adversarial carlini 647
./run_extra.sh mnist b relu carlini 647
./run_extra.sh mnist c standard carlini 647
./run_extra.sh mnist c adversarial carlini 647
./run_extra.sh mnist c relu carlini 647
./run_extra.sh mnist a standard carlini 8512
./run_extra.sh mnist a adversarial carlini 8512
./run_extra.sh mnist a relu carlini 8512
./run_extra.sh mnist b standard carlini 8512
./run_extra.sh mnist b adversarial carlini 8512
./run_extra.sh mnist b relu carlini 8512
./run_extra.sh mnist c standard carlini 8512
./run_extra.sh mnist c adversarial carlini 8512
./run_extra.sh mnist c relu carlini 8512
./run_extra.sh mnist a standard carlini 6165
./run_extra.sh mnist a adversarial carlini 6165
./run_extra.sh mnist a relu carlini 6165
./run_extra.sh mnist b standard carlini 6165
./run_extra.sh mnist b adversarial carlini 6165
./run_extra.sh mnist b relu carlini 6165
./run_extra.sh mnist c standard carlini 6165
./run_extra.sh mnist c adversarial carlini 6165
./run_extra.sh mnist c relu carlini 6165
./run_extra.sh mnist a standard carlini 2874
./run_extra.sh mnist a adversarial carlini 2874
./run_extra.sh mnist a relu carlini 2874
./run_extra.sh mnist b standard carlini 2874
./run_extra.sh mnist b adversarial carlini 2874
./run_extra.sh mnist b relu carlini 2874
./run_extra.sh mnist c standard carlini 2874
./run_extra.sh mnist c adversarial carlini 2874
./run_extra.sh mnist c relu carlini 2874
./run_extra.sh mnist a standard carlini 8092
./run_extra.sh mnist a adversarial carlini 8092
./run_extra.sh mnist a relu carlini 8092
./run_extra.sh mnist b standard carlini 8092
./run_extra.sh mnist b adversarial carlini 8092
./run_extra.sh mnist b relu carlini 8092
./run_extra.sh mnist c standard carlini 8092
./run_extra.sh mnist c adversarial carlini 8092
./run_extra.sh mnist c relu carlini 8092
./run_extra.sh mnist a standard carlini 423
./run_extra.sh mnist a adversarial carlini 423
./run_extra.sh mnist a relu carlini 423
./run_extra.sh mnist b standard carlini 423
./run_extra.sh mnist b adversarial carlini 423
./run_extra.sh mnist b relu carlini 423
./run_extra.sh mnist c standard carlini 423
./run_extra.sh mnist c adversarial carlini 423
./run_extra.sh mnist c relu carlini 423
./run_extra.sh mnist a standard carlini 761
./run_extra.sh mnist a adversarial carlini 761
./run_extra.sh mnist a relu carlini 761
./run_extra.sh mnist b standard carlini 761
./run_extra.sh mnist b adversarial carlini 761
./run_extra.sh mnist b relu carlini 761
./run_extra.sh mnist c standard carlini 761
./run_extra.sh mnist c adversarial carlini 761
./run_extra.sh mnist c relu carlini 761
./run_extra.sh mnist a standard carlini 340
./run_extra.sh mnist a adversarial carlini 340
./run_extra.sh mnist a relu carlini 340
./run_extra.sh mnist b standard carlini 340
./run_extra.sh mnist b adversarial carlini 340
./run_extra.sh mnist b relu carlini 340
./run_extra.sh mnist c standard carlini 340
./run_extra.sh mnist c adversarial carlini 340
./run_extra.sh mnist c relu carlini 340
./run_extra.sh mnist a standard carlini 9220
./run_extra.sh mnist a adversarial carlini 9220
./run_extra.sh mnist a relu carlini 9220
./run_extra.sh mnist b standard carlini 9220
./run_extra.sh mnist b adversarial carlini 9220
./run_extra.sh mnist b relu carlini 9220
./run_extra.sh mnist c standard carlini 9220
./run_extra.sh mnist c adversarial carlini 9220
./run_extra.sh mnist c relu carlini 9220
./run_extra.sh mnist a standard carlini 5936
./run_extra.sh mnist a adversarial carlini 5936
./run_extra.sh mnist a relu carlini 5936
./run_extra.sh mnist b standard carlini 5936
./run_extra.sh mnist b adversarial carlini 5936
./run_extra.sh mnist b relu carlini 5936
./run_extra.sh mnist c standard carlini 5936
./run_extra.sh mnist c adversarial carlini 5936
./run_extra.sh mnist c relu carlini 5936
./run_extra.sh mnist a standard carlini 6513
./run_extra.sh mnist a adversarial carlini 6513
./run_extra.sh mnist a relu carlini 6513
./run_extra.sh mnist b standard carlini 6513
./run_extra.sh mnist b adversarial carlini 6513
./run_extra.sh mnist b relu carlini 6513
./run_extra.sh mnist c standard carlini 6513
./run_extra.sh mnist c adversarial carlini 6513
./run_extra.sh mnist c relu carlini 6513
./run_extra.sh mnist a standard carlini 3387
./run_extra.sh mnist a adversarial carlini 3387
./run_extra.sh mnist a relu carlini 3387
./run_extra.sh mnist b standard carlini 3387
./run_extra.sh mnist b adversarial carlini 3387
./run_extra.sh mnist b relu carlini 3387
./run_extra.sh mnist c standard carlini 3387
./run_extra.sh mnist c adversarial carlini 3387
./run_extra.sh mnist c relu carlini 3387
./run_extra.sh mnist a standard carlini 3412
./run_extra.sh mnist a adversarial carlini 3412
./run_extra.sh mnist a relu carlini 3412
./run_extra.sh mnist b standard carlini 3412
./run_extra.sh mnist b adversarial carlini 3412
./run_extra.sh mnist b relu carlini 3412
./run_extra.sh mnist c standard carlini 3412
./run_extra.sh mnist c adversarial carlini 3412
./run_extra.sh mnist c relu carlini 3412
./run_extra.sh mnist a standard carlini 8112
./run_extra.sh mnist a adversarial carlini 8112
./run_extra.sh mnist a relu carlini 8112
./run_extra.sh mnist b standard carlini 8112
./run_extra.sh mnist b adversarial carlini 8112
./run_extra.sh mnist b relu carlini 8112
./run_extra.sh mnist c standard carlini 8112
./run_extra.sh mnist c adversarial carlini 8112
./run_extra.sh mnist c relu carlini 8112
./run_extra.sh mnist a standard carlini 5934
./run_extra.sh mnist a adversarial carlini 5934
./run_extra.sh mnist a relu carlini 5934
./run_extra.sh mnist b standard carlini 5934
./run_extra.sh mnist b adversarial carlini 5934
./run_extra.sh mnist b relu carlini 5934
./run_extra.sh mnist c standard carlini 5934
./run_extra.sh mnist c adversarial carlini 5934
./run_extra.sh mnist c relu carlini 5934
./run_extra.sh mnist a standard carlini 3543
./run_extra.sh mnist a adversarial carlini 3543
./run_extra.sh mnist a relu carlini 3543
./run_extra.sh mnist b standard carlini 3543
./run_extra.sh mnist b adversarial carlini 3543
./run_extra.sh mnist b relu carlini 3543
./run_extra.sh mnist c standard carlini 3543
./run_extra.sh mnist c adversarial carlini 3543
./run_extra.sh mnist c relu carlini 3543
./run_extra.sh mnist a standard carlini 5134
./run_extra.sh mnist a adversarial carlini 5134
./run_extra.sh mnist a relu carlini 5134
./run_extra.sh mnist b standard carlini 5134
./run_extra.sh mnist b adversarial carlini 5134
./run_extra.sh mnist b relu carlini 5134
./run_extra.sh mnist c standard carlini 5134
./run_extra.sh mnist c adversarial carlini 5134
./run_extra.sh mnist c relu carlini 5134
./run_extra.sh mnist a standard carlini 1312
./run_extra.sh mnist a adversarial carlini 1312
./run_extra.sh mnist a relu carlini 1312
./run_extra.sh mnist b standard carlini 1312
./run_extra.sh mnist b adversarial carlini 1312
./run_extra.sh mnist b relu carlini 1312
./run_extra.sh mnist c standard carlini 1312
./run_extra.sh mnist c adversarial carlini 1312
./run_extra.sh mnist c relu carlini 1312
./run_extra.sh mnist a standard carlini 8202
./run_extra.sh mnist a adversarial carlini 8202
./run_extra.sh mnist a relu carlini 8202
./run_extra.sh mnist b standard carlini 8202
./run_extra.sh mnist b adversarial carlini 8202
./run_extra.sh mnist b relu carlini 8202
