./run_extra.sh mnist b standard carlini 290
./run_extra.sh mnist b adversarial carlini 290
./run_extra.sh mnist b relu carlini 290
./run_extra.sh mnist c standard carlini 290
./run_extra.sh mnist c adversarial carlini 290
./run_extra.sh mnist c relu carlini 290
./run_extra.sh mnist a standard carlini 592
./run_extra.sh mnist a adversarial carlini 592
./run_extra.sh mnist a relu carlini 592
./run_extra.sh mnist b standard carlini 592
./run_extra.sh mnist b adversarial carlini 592
./run_extra.sh mnist b relu carlini 592
./run_extra.sh mnist c standard carlini 592
./run_extra.sh mnist c adversarial carlini 592
./run_extra.sh mnist c relu carlini 592
./run_extra.sh mnist a standard carlini 2439
./run_extra.sh mnist a adversarial carlini 2439
./run_extra.sh mnist a relu carlini 2439
./run_extra.sh mnist b standard carlini 2439
./run_extra.sh mnist b adversarial carlini 2439
./run_extra.sh mnist b relu carlini 2439
./run_extra.sh mnist c standard carlini 2439
./run_extra.sh mnist c adversarial carlini 2439
./run_extra.sh mnist c relu carlini 2439
./run_extra.sh mnist a standard carlini 9611
./run_extra.sh mnist a adversarial carlini 9611
./run_extra.sh mnist a relu carlini 9611
./run_extra.sh mnist b standard carlini 9611
./run_extra.sh mnist b adversarial carlini 9611
./run_extra.sh mnist b relu carlini 9611
./run_extra.sh mnist c standard carlini 9611
./run_extra.sh mnist c adversarial carlini 9611
./run_extra.sh mnist c relu carlini 9611
./run_extra.sh mnist a standard carlini 2798
./run_extra.sh mnist a adversarial carlini 2798
./run_extra.sh mnist a relu carlini 2798
./run_extra.sh mnist b standard carlini 2798
./run_extra.sh mnist b adversarial carlini 2798
./run_extra.sh mnist b relu carlini 2798
./run_extra.sh mnist c standard carlini 2798
./run_extra.sh mnist c adversarial carlini 2798
./run_extra.sh mnist c relu carlini 2798
./run_extra.sh mnist a standard carlini 3365
./run_extra.sh mnist a adversarial carlini 3365
./run_extra.sh mnist a relu carlini 3365
./run_extra.sh mnist b standard carlini 3365
./run_extra.sh mnist b adversarial carlini 3365
./run_extra.sh mnist b relu carlini 3365
./run_extra.sh mnist c standard carlini 3365
./run_extra.sh mnist c adversarial carlini 3365
./run_extra.sh mnist c relu carlini 3365
./run_extra.sh mnist a standard carlini 6319
./run_extra.sh mnist a adversarial carlini 6319
./run_extra.sh mnist a relu carlini 6319
./run_extra.sh mnist b standard carlini 6319
./run_extra.sh mnist b adversarial carlini 6319
./run_extra.sh mnist b relu carlini 6319
./run_extra.sh mnist c standard carlini 6319
./run_extra.sh mnist c adversarial carlini 6319
./run_extra.sh mnist c relu carlini 6319
./run_extra.sh mnist a standard carlini 9852
./run_extra.sh mnist a adversarial carlini 9852
./run_extra.sh mnist a relu carlini 9852
./run_extra.sh mnist b standard carlini 9852
./run_extra.sh mnist b adversarial carlini 9852
./run_extra.sh mnist b relu carlini 9852
./run_extra.sh mnist c standard carlini 9852
./run_extra.sh mnist c adversarial carlini 9852
./run_extra.sh mnist c relu carlini 9852
./run_extra.sh mnist a standard carlini 4902
./run_extra.sh mnist a adversarial carlini 4902
./run_extra.sh mnist a relu carlini 4902
./run_extra.sh mnist b standard carlini 4902
./run_extra.sh mnist b adversarial carlini 4902
./run_extra.sh mnist b relu carlini 4902
./run_extra.sh mnist c standard carlini 4902
./run_extra.sh mnist c adversarial carlini 4902
./run_extra.sh mnist c relu carlini 4902
./run_extra.sh mnist a standard carlini 5573
./run_extra.sh mnist a adversarial carlini 5573
./run_extra.sh mnist a relu carlini 5573
./run_extra.sh mnist b standard carlini 5573
./run_extra.sh mnist b adversarial carlini 5573
./run_extra.sh mnist b relu carlini 5573
./run_extra.sh mnist c standard carlini 5573
./run_extra.sh mnist c adversarial carlini 5573
./run_extra.sh mnist c relu carlini 5573
./run_extra.sh mnist a standard carlini 7722
./run_extra.sh mnist a adversarial carlini 7722
./run_extra.sh mnist a relu carlini 7722
./run_extra.sh mnist b standard carlini 7722
./run_extra.sh mnist b adversarial carlini 7722
./run_extra.sh mnist b relu carlini 7722
./run_extra.sh mnist c standard carlini 7722
./run_extra.sh mnist c adversarial carlini 7722
./run_extra.sh mnist c relu carlini 7722
./run_extra.sh mnist a standard carlini 3736
./run_extra.sh mnist a adversarial carlini 3736
./run_extra.sh mnist a relu carlini 3736
./run_extra.sh mnist b standard carlini 3736
./run_extra.sh mnist b adversarial carlini 3736
./run_extra.sh mnist b relu carlini 3736
./run_extra.sh mnist c standard carlini 3736
./run_extra.sh mnist c adversarial carlini 3736
./run_extra.sh mnist c relu carlini 3736
./run_extra.sh mnist a standard carlini 963
./run_extra.sh mnist a adversarial carlini 963
./run_extra.sh mnist a relu carlini 963
./run_extra.sh mnist b standard carlini 963
./run_extra.sh mnist b adversarial carlini 963
./run_extra.sh mnist b relu carlini 963
./run_extra.sh mnist c standard carlini 963
./run_extra.sh mnist c adversarial carlini 963
./run_extra.sh mnist c relu carlini 963
./run_extra.sh mnist a standard carlini 7388
./run_extra.sh mnist a adversarial carlini 7388
./run_extra.sh mnist a relu carlini 7388
./run_extra.sh mnist b standard carlini 7388
./run_extra.sh mnist b adversarial carlini 7388
./run_extra.sh mnist b relu carlini 7388
./run_extra.sh mnist c standard carlini 7388
./run_extra.sh mnist c adversarial carlini 7388
./run_extra.sh mnist c relu carlini 7388
./run_extra.sh mnist a standard carlini 4306
./run_extra.sh mnist a adversarial carlini 4306
./run_extra.sh mnist a relu carlini 4306
./run_extra.sh mnist b standard carlini 4306
./run_extra.sh mnist b adversarial carlini 4306
./run_extra.sh mnist b relu carlini 4306
./run_extra.sh mnist c standard carlini 4306
./run_extra.sh mnist c adversarial carlini 4306
./run_extra.sh mnist c relu carlini 4306
./run_extra.sh mnist a standard carlini 4852
./run_extra.sh mnist a adversarial carlini 4852
./run_extra.sh mnist a relu carlini 4852
./run_extra.sh mnist b standard carlini 4852
./run_extra.sh mnist b adversarial carlini 4852
./run_extra.sh mnist b relu carlini 4852
./run_extra.sh mnist c standard carlini 4852
./run_extra.sh mnist c adversarial carlini 4852
./run_extra.sh mnist c relu carlini 4852
./run_extra.sh mnist a standard carlini 8244
./run_extra.sh mnist a adversarial carlini 8244
./run_extra.sh mnist a relu carlini 8244
./run_extra.sh mnist b standard carlini 8244
./run_extra.sh mnist b adversarial carlini 8244
./run_extra.sh mnist b relu carlini 8244
./run_extra.sh mnist c standard carlini 8244
./run_extra.sh mnist c adversarial carlini 8244
./run_extra.sh mnist c relu carlini 8244
./run_extra.sh mnist a standard carlini 798
./run_extra.sh mnist a adversarial carlini 798
./run_extra.sh mnist a relu carlini 798
./run_extra.sh mnist b standard carlini 798
./run_extra.sh mnist b adversarial carlini 798
./run_extra.sh mnist b relu carlini 798
./run_extra.sh mnist c standard carlini 798
./run_extra.sh mnist c adversarial carlini 798
./run_extra.sh mnist c relu carlini 798
./run_extra.sh mnist a standard carlini 1984
./run_extra.sh mnist a adversarial carlini 1984
./run_extra.sh mnist a relu carlini 1984
./run_extra.sh mnist b standard carlini 1984
./run_extra.sh mnist b adversarial carlini 1984
./run_extra.sh mnist b relu carlini 1984
./run_extra.sh mnist c standard carlini 1984
./run_extra.sh mnist c adversarial carlini 1984
./run_extra.sh mnist c relu carlini 1984
./run_extra.sh mnist a standard carlini 329
./run_extra.sh mnist a adversarial carlini 329
./run_extra.sh mnist a relu carlini 329
./run_extra.sh mnist b standard carlini 329
./run_extra.sh mnist b adversarial carlini 329
./run_extra.sh mnist b relu carlini 329
./run_extra.sh mnist c standard carlini 329
./run_extra.sh mnist c adversarial carlini 329
./run_extra.sh mnist c relu carlini 329
./run_extra.sh mnist a standard carlini 1273
./run_extra.sh mnist a adversarial carlini 1273
./run_extra.sh mnist a relu carlini 1273
./run_extra.sh mnist b standard carlini 1273
./run_extra.sh mnist b adversarial carlini 1273
./run_extra.sh mnist b relu carlini 1273
./run_extra.sh mnist c standard carlini 1273
./run_extra.sh mnist c adversarial carlini 1273
./run_extra.sh mnist c relu carlini 1273
./run_extra.sh mnist a standard carlini 6947
./run_extra.sh mnist a adversarial carlini 6947
./run_extra.sh mnist a relu carlini 6947
./run_extra.sh mnist b standard carlini 6947
./run_extra.sh mnist b adversarial carlini 6947
./run_extra.sh mnist b relu carlini 6947
./run_extra.sh mnist c standard carlini 6947
./run_extra.sh mnist c adversarial carlini 6947
./run_extra.sh mnist c relu carlini 6947
./run_extra.sh mnist a standard carlini 427
./run_extra.sh mnist a adversarial carlini 427
./run_extra.sh mnist a relu carlini 427
./run_extra.sh mnist b standard carlini 427
./run_extra.sh mnist b adversarial carlini 427
./run_extra.sh mnist b relu carlini 427
./run_extra.sh mnist c standard carlini 427
./run_extra.sh mnist c adversarial carlini 427
./run_extra.sh mnist c relu carlini 427
./run_extra.sh mnist a standard carlini 9352
./run_extra.sh mnist a adversarial carlini 9352
./run_extra.sh mnist a relu carlini 9352
./run_extra.sh mnist b standard carlini 9352
./run_extra.sh mnist b adversarial carlini 9352
./run_extra.sh mnist b relu carlini 9352
./run_extra.sh mnist c standard carlini 9352
./run_extra.sh mnist c adversarial carlini 9352
./run_extra.sh mnist c relu carlini 9352
./run_extra.sh mnist a standard carlini 4016
./run_extra.sh mnist a adversarial carlini 4016
./run_extra.sh mnist a relu carlini 4016
./run_extra.sh mnist b standard carlini 4016
./run_extra.sh mnist b adversarial carlini 4016
./run_extra.sh mnist b relu carlini 4016
./run_extra.sh mnist c standard carlini 4016
./run_extra.sh mnist c adversarial carlini 4016
./run_extra.sh mnist c relu carlini 4016
./run_extra.sh mnist a standard carlini 7205
./run_extra.sh mnist a adversarial carlini 7205
./run_extra.sh mnist a relu carlini 7205
./run_extra.sh mnist b standard carlini 7205
./run_extra.sh mnist b adversarial carlini 7205
./run_extra.sh mnist b relu carlini 7205
./run_extra.sh mnist c standard carlini 7205
./run_extra.sh mnist c adversarial carlini 7205
./run_extra.sh mnist c relu carlini 7205
./run_extra.sh mnist a standard carlini 2484
./run_extra.sh mnist a adversarial carlini 2484
./run_extra.sh mnist a relu carlini 2484
./run_extra.sh mnist b standard carlini 2484
./run_extra.sh mnist b adversarial carlini 2484
./run_extra.sh mnist b relu carlini 2484
./run_extra.sh mnist c standard carlini 2484
./run_extra.sh mnist c adversarial carlini 2484
./run_extra.sh mnist c relu carlini 2484
./run_extra.sh mnist a standard carlini 5649
./run_extra.sh mnist a adversarial carlini 5649
./run_extra.sh mnist a relu carlini 5649
./run_extra.sh mnist b standard carlini 5649
./run_extra.sh mnist b adversarial carlini 5649
./run_extra.sh mnist b relu carlini 5649
./run_extra.sh mnist c standard carlini 5649
./run_extra.sh mnist c adversarial carlini 5649
./run_extra.sh mnist c relu carlini 5649
./run_extra.sh mnist a standard carlini 5150
./run_extra.sh mnist a adversarial carlini 5150
./run_extra.sh mnist a relu carlini 5150
./run_extra.sh mnist b standard carlini 5150
./run_extra.sh mnist b adversarial carlini 5150
./run_extra.sh mnist b relu carlini 5150
./run_extra.sh mnist c standard carlini 5150
./run_extra.sh mnist c adversarial carlini 5150
./run_extra.sh mnist c relu carlini 5150
./run_extra.sh mnist a standard carlini 4594
./run_extra.sh mnist a adversarial carlini 4594
./run_extra.sh mnist a relu carlini 4594
./run_extra.sh mnist b standard carlini 4594
./run_extra.sh mnist b adversarial carlini 4594
./run_extra.sh mnist b relu carlini 4594
./run_extra.sh mnist c standard carlini 4594
./run_extra.sh mnist c adversarial carlini 4594
./run_extra.sh mnist c relu carlini 4594
./run_extra.sh mnist a standard carlini 4266
./run_extra.sh mnist a adversarial carlini 4266
./run_extra.sh mnist a relu carlini 4266
./run_extra.sh mnist b standard carlini 4266
./run_extra.sh mnist b adversarial carlini 4266
./run_extra.sh mnist b relu carlini 4266
./run_extra.sh mnist c standard carlini 4266
./run_extra.sh mnist c adversarial carlini 4266
./run_extra.sh mnist c relu carlini 4266
./run_extra.sh mnist a standard carlini 6279
./run_extra.sh mnist a adversarial carlini 6279
./run_extra.sh mnist a relu carlini 6279
./run_extra.sh mnist b standard carlini 6279
./run_extra.sh mnist b adversarial carlini 6279
./run_extra.sh mnist b relu carlini 6279
./run_extra.sh mnist c standard carlini 6279
./run_extra.sh mnist c adversarial carlini 6279
./run_extra.sh mnist c relu carlini 6279
./run_extra.sh mnist a standard carlini 4177
./run_extra.sh mnist a adversarial carlini 4177
./run_extra.sh mnist a relu carlini 4177
./run_extra.sh mnist b standard carlini 4177
./run_extra.sh mnist b adversarial carlini 4177
./run_extra.sh mnist b relu carlini 4177
./run_extra.sh mnist c standard carlini 4177
./run_extra.sh mnist c adversarial carlini 4177
./run_extra.sh mnist c relu carlini 4177
./run_extra.sh mnist a standard carlini 2064
./run_extra.sh mnist a adversarial carlini 2064
./run_extra.sh mnist a relu carlini 2064
./run_extra.sh mnist b standard carlini 2064
./run_extra.sh mnist b adversarial carlini 2064
./run_extra.sh mnist b relu carlini 2064
./run_extra.sh mnist c standard carlini 2064
./run_extra.sh mnist c adversarial carlini 2064
./run_extra.sh mnist c relu carlini 2064
./run_extra.sh mnist a standard carlini 4776
./run_extra.sh mnist a adversarial carlini 4776
./run_extra.sh mnist a relu carlini 4776
./run_extra.sh mnist b standard carlini 4776
./run_extra.sh mnist b adversarial carlini 4776
./run_extra.sh mnist b relu carlini 4776
./run_extra.sh mnist c standard carlini 4776
./run_extra.sh mnist c adversarial carlini 4776
./run_extra.sh mnist c relu carlini 4776
./run_extra.sh mnist a standard carlini 3772
./run_extra.sh mnist a adversarial carlini 3772
./run_extra.sh mnist a relu carlini 3772
./run_extra.sh mnist b standard carlini 3772
./run_extra.sh mnist b adversarial carlini 3772
./run_extra.sh mnist b relu carlini 3772
./run_extra.sh mnist c standard carlini 3772
./run_extra.sh mnist c adversarial carlini 3772
./run_extra.sh mnist c relu carlini 3772
./run_extra.sh mnist a standard carlini 3018
./run_extra.sh mnist a adversarial carlini 3018
./run_extra.sh mnist a relu carlini 3018
./run_extra.sh mnist b standard carlini 3018
./run_extra.sh mnist b adversarial carlini 3018
./run_extra.sh mnist b relu carlini 3018
./run_extra.sh mnist c standard carlini 3018
./run_extra.sh mnist c adversarial carlini 3018
./run_extra.sh mnist c relu carlini 3018
./run_extra.sh mnist a standard carlini 8652
./run_extra.sh mnist a adversarial carlini 8652
./run_extra.sh mnist a relu carlini 8652
./run_extra.sh mnist b standard carlini 8652
./run_extra.sh mnist b adversarial carlini 8652
./run_extra.sh mnist b relu carlini 8652
./run_extra.sh mnist c standard carlini 8652
./run_extra.sh mnist c adversarial carlini 8652
./run_extra.sh mnist c relu carlini 8652
./run_extra.sh mnist a standard carlini 8201
./run_extra.sh mnist a adversarial carlini 8201
./run_extra.sh mnist a relu carlini 8201
./run_extra.sh mnist b standard carlini 8201
./run_extra.sh mnist b adversarial carlini 8201
./run_extra.sh mnist b relu carlini 8201
./run_extra.sh mnist c standard carlini 8201
./run_extra.sh mnist c adversarial carlini 8201
./run_extra.sh mnist c relu carlini 8201
./run_extra.sh mnist a standard carlini 9379
./run_extra.sh mnist a adversarial carlini 9379
./run_extra.sh mnist a relu carlini 9379
./run_extra.sh mnist b standard carlini 9379
./run_extra.sh mnist b adversarial carlini 9379
./run_extra.sh mnist b relu carlini 9379
./run_extra.sh mnist c standard carlini 9379
./run_extra.sh mnist c adversarial carlini 9379
./run_extra.sh mnist c relu carlini 9379
./run_extra.sh mnist a standard carlini 9560
./run_extra.sh mnist a adversarial carlini 9560
./run_extra.sh mnist a relu carlini 9560
./run_extra.sh mnist b standard carlini 9560
./run_extra.sh mnist b adversarial carlini 9560
./run_extra.sh mnist b relu carlini 9560
./run_extra.sh mnist c standard carlini 9560
./run_extra.sh mnist c adversarial carlini 9560
./run_extra.sh mnist c relu carlini 9560
./run_extra.sh mnist a standard carlini 9631
./run_extra.sh mnist a adversarial carlini 9631
./run_extra.sh mnist a relu carlini 9631
./run_extra.sh mnist b standard carlini 9631
./run_extra.sh mnist b adversarial carlini 9631
./run_extra.sh mnist b relu carlini 9631
./run_extra.sh mnist c standard carlini 9631
./run_extra.sh mnist c adversarial carlini 9631
./run_extra.sh mnist c relu carlini 9631
./run_extra.sh mnist a standard carlini 850
./run_extra.sh mnist a adversarial carlini 850
./run_extra.sh mnist a relu carlini 850
./run_extra.sh mnist b standard carlini 850
./run_extra.sh mnist b adversarial carlini 850
./run_extra.sh mnist b relu carlini 850
./run_extra.sh mnist c standard carlini 850
./run_extra.sh mnist c adversarial carlini 850
./run_extra.sh mnist c relu carlini 850
./run_extra.sh mnist a standard carlini 9610
./run_extra.sh mnist a adversarial carlini 9610
./run_extra.sh mnist a relu carlini 9610
./run_extra.sh mnist b standard carlini 9610
./run_extra.sh mnist b adversarial carlini 9610
./run_extra.sh mnist b relu carlini 9610
./run_extra.sh mnist c standard carlini 9610
./run_extra.sh mnist c adversarial carlini 9610
./run_extra.sh mnist c relu carlini 9610
./run_extra.sh mnist a standard carlini 970
./run_extra.sh mnist a adversarial carlini 970
./run_extra.sh mnist a relu carlini 970
./run_extra.sh mnist b standard carlini 970
./run_extra.sh mnist b adversarial carlini 970
./run_extra.sh mnist b relu carlini 970
./run_extra.sh mnist c standard carlini 970
./run_extra.sh mnist c adversarial carlini 970
./run_extra.sh mnist c relu carlini 970
./run_extra.sh mnist a standard carlini 8033
./run_extra.sh mnist a adversarial carlini 8033
./run_extra.sh mnist a relu carlini 8033
./run_extra.sh mnist b standard carlini 8033
./run_extra.sh mnist b adversarial carlini 8033
./run_extra.sh mnist b relu carlini 8033
./run_extra.sh mnist c standard carlini 8033
./run_extra.sh mnist c adversarial carlini 8033
./run_extra.sh mnist c relu carlini 8033
./run_extra.sh mnist a standard carlini 7878
./run_extra.sh mnist a adversarial carlini 7878
./run_extra.sh mnist a relu carlini 7878
./run_extra.sh mnist b standard carlini 7878
./run_extra.sh mnist b adversarial carlini 7878
./run_extra.sh mnist b relu carlini 7878
./run_extra.sh mnist c standard carlini 7878
./run_extra.sh mnist c adversarial carlini 7878
./run_extra.sh mnist c relu carlini 7878
./run_extra.sh mnist a standard carlini 2866
./run_extra.sh mnist a adversarial carlini 2866
./run_extra.sh mnist a relu carlini 2866
./run_extra.sh mnist b standard carlini 2866
./run_extra.sh mnist b adversarial carlini 2866
./run_extra.sh mnist b relu carlini 2866
./run_extra.sh mnist c standard carlini 2866
./run_extra.sh mnist c adversarial carlini 2866
./run_extra.sh mnist c relu carlini 2866
./run_extra.sh mnist a standard carlini 415
./run_extra.sh mnist a adversarial carlini 415
./run_extra.sh mnist a relu carlini 415
./run_extra.sh mnist b standard carlini 415
./run_extra.sh mnist b adversarial carlini 415
./run_extra.sh mnist b relu carlini 415
./run_extra.sh mnist c standard carlini 415
./run_extra.sh mnist c adversarial carlini 415
./run_extra.sh mnist c relu carlini 415
./run_extra.sh mnist a standard carlini 6678
./run_extra.sh mnist a adversarial carlini 6678
./run_extra.sh mnist a relu carlini 6678
./run_extra.sh mnist b standard carlini 6678
./run_extra.sh mnist b adversarial carlini 6678
./run_extra.sh mnist b relu carlini 6678
./run_extra.sh mnist c standard carlini 6678
./run_extra.sh mnist c adversarial carlini 6678
./run_extra.sh mnist c relu carlini 6678
./run_extra.sh mnist a standard carlini 5507
./run_extra.sh mnist a adversarial carlini 5507
./run_extra.sh mnist a relu carlini 5507
./run_extra.sh mnist b standard carlini 5507
./run_extra.sh mnist b adversarial carlini 5507
./run_extra.sh mnist b relu carlini 5507
./run_extra.sh mnist c standard carlini 5507
./run_extra.sh mnist c adversarial carlini 5507
./run_extra.sh mnist c relu carlini 5507
./run_extra.sh mnist a standard carlini 6021
./run_extra.sh mnist a adversarial carlini 6021
./run_extra.sh mnist a relu carlini 6021
./run_extra.sh mnist b standard carlini 6021
./run_extra.sh mnist b adversarial carlini 6021
./run_extra.sh mnist b relu carlini 6021
./run_extra.sh mnist c standard carlini 6021
./run_extra.sh mnist c adversarial carlini 6021
./run_extra.sh mnist c relu carlini 6021
./run_extra.sh mnist a standard carlini 9422
./run_extra.sh mnist a adversarial carlini 9422
./run_extra.sh mnist a relu carlini 9422
./run_extra.sh mnist b standard carlini 9422
./run_extra.sh mnist b adversarial carlini 9422
./run_extra.sh mnist b relu carlini 9422
./run_extra.sh mnist c standard carlini 9422
./run_extra.sh mnist c adversarial carlini 9422
./run_extra.sh mnist c relu carlini 9422
./run_extra.sh mnist a standard carlini 934
./run_extra.sh mnist a adversarial carlini 934
./run_extra.sh mnist a relu carlini 934
./run_extra.sh mnist b standard carlini 934
./run_extra.sh mnist b adversarial carlini 934
./run_extra.sh mnist b relu carlini 934
./run_extra.sh mnist c standard carlini 934
./run_extra.sh mnist c adversarial carlini 934
./run_extra.sh mnist c relu carlini 934
./run_extra.sh mnist a standard carlini 1164
./run_extra.sh mnist a adversarial carlini 1164
./run_extra.sh mnist a relu carlini 1164
./run_extra.sh mnist b standard carlini 1164
./run_extra.sh mnist b adversarial carlini 1164
./run_extra.sh mnist b relu carlini 1164
./run_extra.sh mnist c standard carlini 1164
./run_extra.sh mnist c adversarial carlini 1164
./run_extra.sh mnist c relu carlini 1164
./run_extra.sh mnist a standard carlini 1306
./run_extra.sh mnist a adversarial carlini 1306
./run_extra.sh mnist a relu carlini 1306
./run_extra.sh mnist b standard carlini 1306
./run_extra.sh mnist b adversarial carlini 1306
./run_extra.sh mnist b relu carlini 1306
./run_extra.sh mnist c standard carlini 1306
./run_extra.sh mnist c adversarial carlini 1306
./run_extra.sh mnist c relu carlini 1306
./run_extra.sh mnist a standard carlini 6521
./run_extra.sh mnist a adversarial carlini 6521
./run_extra.sh mnist a relu carlini 6521
./run_extra.sh mnist b standard carlini 6521
./run_extra.sh mnist b adversarial carlini 6521
./run_extra.sh mnist b relu carlini 6521
./run_extra.sh mnist c standard carlini 6521
./run_extra.sh mnist c adversarial carlini 6521
./run_extra.sh mnist c relu carlini 6521
./run_extra.sh mnist a standard carlini 9291
./run_extra.sh mnist a adversarial carlini 9291
./run_extra.sh mnist a relu carlini 9291
./run_extra.sh mnist b standard carlini 9291
./run_extra.sh mnist b adversarial carlini 9291
./run_extra.sh mnist b relu carlini 9291
./run_extra.sh mnist c standard carlini 9291
./run_extra.sh mnist c adversarial carlini 9291
./run_extra.sh mnist c relu carlini 9291
./run_extra.sh mnist a standard carlini 5810
./run_extra.sh mnist a adversarial carlini 5810
./run_extra.sh mnist a relu carlini 5810
./run_extra.sh mnist b standard carlini 5810
./run_extra.sh mnist b adversarial carlini 5810
./run_extra.sh mnist b relu carlini 5810
./run_extra.sh mnist c standard carlini 5810
./run_extra.sh mnist c adversarial carlini 5810
./run_extra.sh mnist c relu carlini 5810
./run_extra.sh mnist a standard carlini 1957
./run_extra.sh mnist a adversarial carlini 1957
./run_extra.sh mnist a relu carlini 1957
./run_extra.sh mnist b standard carlini 1957
./run_extra.sh mnist b adversarial carlini 1957
./run_extra.sh mnist b relu carlini 1957
./run_extra.sh mnist c standard carlini 1957
./run_extra.sh mnist c adversarial carlini 1957
./run_extra.sh mnist c relu carlini 1957
./run_extra.sh mnist a standard carlini 638
./run_extra.sh mnist a adversarial carlini 638
./run_extra.sh mnist a relu carlini 638
./run_extra.sh mnist b standard carlini 638
./run_extra.sh mnist b adversarial carlini 638
./run_extra.sh mnist b relu carlini 638
./run_extra.sh mnist c standard carlini 638
./run_extra.sh mnist c adversarial carlini 638
./run_extra.sh mnist c relu carlini 638
./run_extra.sh mnist a standard carlini 7814
./run_extra.sh mnist a adversarial carlini 7814
./run_extra.sh mnist a relu carlini 7814
./run_extra.sh mnist b standard carlini 7814
./run_extra.sh mnist b adversarial carlini 7814
./run_extra.sh mnist b relu carlini 7814
./run_extra.sh mnist c standard carlini 7814
./run_extra.sh mnist c adversarial carlini 7814
./run_extra.sh mnist c relu carlini 7814
./run_extra.sh mnist a standard carlini 4560
./run_extra.sh mnist a adversarial carlini 4560
./run_extra.sh mnist a relu carlini 4560
./run_extra.sh mnist b standard carlini 4560
./run_extra.sh mnist b adversarial carlini 4560
./run_extra.sh mnist b relu carlini 4560
./run_extra.sh mnist c standard carlini 4560
./run_extra.sh mnist c adversarial carlini 4560
./run_extra.sh mnist c relu carlini 4560
./run_extra.sh mnist a standard carlini 5181
./run_extra.sh mnist a adversarial carlini 5181
./run_extra.sh mnist a relu carlini 5181
./run_extra.sh mnist b standard carlini 5181
./run_extra.sh mnist b adversarial carlini 5181
./run_extra.sh mnist b relu carlini 5181
./run_extra.sh mnist c standard carlini 5181
./run_extra.sh mnist c adversarial carlini 5181
./run_extra.sh mnist c relu carlini 5181
./run_extra.sh mnist a standard carlini 3661
./run_extra.sh mnist a adversarial carlini 3661
./run_extra.sh mnist a relu carlini 3661
./run_extra.sh mnist b standard carlini 3661
./run_extra.sh mnist b adversarial carlini 3661
./run_extra.sh mnist b relu carlini 3661
./run_extra.sh mnist c standard carlini 3661
./run_extra.sh mnist c adversarial carlini 3661
./run_extra.sh mnist c relu carlini 3661
./run_extra.sh mnist a standard carlini 5566
./run_extra.sh mnist a adversarial carlini 5566
./run_extra.sh mnist a relu carlini 5566
./run_extra.sh mnist b standard carlini 5566
./run_extra.sh mnist b adversarial carlini 5566
./run_extra.sh mnist b relu carlini 5566
./run_extra.sh mnist c standard carlini 5566
./run_extra.sh mnist c adversarial carlini 5566
./run_extra.sh mnist c relu carlini 5566
./run_extra.sh mnist a standard carlini 8641
./run_extra.sh mnist a adversarial carlini 8641
./run_extra.sh mnist a relu carlini 8641
./run_extra.sh mnist b standard carlini 8641
./run_extra.sh mnist b adversarial carlini 8641
./run_extra.sh mnist b relu carlini 8641
./run_extra.sh mnist c standard carlini 8641
./run_extra.sh mnist c adversarial carlini 8641
./run_extra.sh mnist c relu carlini 8641
./run_extra.sh mnist a standard carlini 4874
./run_extra.sh mnist a adversarial carlini 4874
./run_extra.sh mnist a relu carlini 4874
./run_extra.sh mnist b standard carlini 4874
./run_extra.sh mnist b adversarial carlini 4874
./run_extra.sh mnist b relu carlini 4874
./run_extra.sh mnist c standard carlini 4874
./run_extra.sh mnist c adversarial carlini 4874
./run_extra.sh mnist c relu carlini 4874
./run_extra.sh mnist a standard carlini 3743
./run_extra.sh mnist a adversarial carlini 3743
./run_extra.sh mnist a relu carlini 3743
./run_extra.sh mnist b standard carlini 3743
./run_extra.sh mnist b adversarial carlini 3743
./run_extra.sh mnist b relu carlini 3743
./run_extra.sh mnist c standard carlini 3743
./run_extra.sh mnist c adversarial carlini 3743
./run_extra.sh mnist c relu carlini 3743
./run_extra.sh mnist a standard carlini 2100
./run_extra.sh mnist a adversarial carlini 2100
./run_extra.sh mnist a relu carlini 2100
./run_extra.sh mnist b standard carlini 2100
./run_extra.sh mnist b adversarial carlini 2100
./run_extra.sh mnist b relu carlini 2100
./run_extra.sh mnist c standard carlini 2100
./run_extra.sh mnist c adversarial carlini 2100
./run_extra.sh mnist c relu carlini 2100
./run_extra.sh mnist a standard carlini 4984
./run_extra.sh mnist a adversarial carlini 4984
./run_extra.sh mnist a relu carlini 4984
./run_extra.sh mnist b standard carlini 4984
./run_extra.sh mnist b adversarial carlini 4984
./run_extra.sh mnist b relu carlini 4984
./run_extra.sh mnist c standard carlini 4984
./run_extra.sh mnist c adversarial carlini 4984
./run_extra.sh mnist c relu carlini 4984
./run_extra.sh mnist a standard carlini 1491
./run_extra.sh mnist a adversarial carlini 1491
./run_extra.sh mnist a relu carlini 1491
./run_extra.sh mnist b standard carlini 1491
./run_extra.sh mnist b adversarial carlini 1491
./run_extra.sh mnist b relu carlini 1491
./run_extra.sh mnist c standard carlini 1491
./run_extra.sh mnist c adversarial carlini 1491
./run_extra.sh mnist c relu carlini 1491
./run_extra.sh mnist a standard carlini 5369
./run_extra.sh mnist a adversarial carlini 5369
./run_extra.sh mnist a relu carlini 5369
./run_extra.sh mnist b standard carlini 5369
./run_extra.sh mnist b adversarial carlini 5369
./run_extra.sh mnist b relu carlini 5369
./run_extra.sh mnist c standard carlini 5369
./run_extra.sh mnist c adversarial carlini 5369
./run_extra.sh mnist c relu carlini 5369
./run_extra.sh mnist a standard carlini 7476
./run_extra.sh mnist a adversarial carlini 7476
./run_extra.sh mnist a relu carlini 7476
./run_extra.sh mnist b standard carlini 7476
./run_extra.sh mnist b adversarial carlini 7476
./run_extra.sh mnist b relu carlini 7476
./run_extra.sh mnist c standard carlini 7476
./run_extra.sh mnist c adversarial carlini 7476
./run_extra.sh mnist c relu carlini 7476
./run_extra.sh mnist a standard carlini 6585
./run_extra.sh mnist a adversarial carlini 6585
./run_extra.sh mnist a relu carlini 6585
./run_extra.sh mnist b standard carlini 6585
./run_extra.sh mnist b adversarial carlini 6585
./run_extra.sh mnist b relu carlini 6585
./run_extra.sh mnist c standard carlini 6585
./run_extra.sh mnist c adversarial carlini 6585
./run_extra.sh mnist c relu carlini 6585
./run_extra.sh mnist a standard carlini 4286
./run_extra.sh mnist a adversarial carlini 4286
./run_extra.sh mnist a relu carlini 4286
./run_extra.sh mnist b standard carlini 4286
./run_extra.sh mnist b adversarial carlini 4286
./run_extra.sh mnist b relu carlini 4286
./run_extra.sh mnist c standard carlini 4286
./run_extra.sh mnist c adversarial carlini 4286
./run_extra.sh mnist c relu carlini 4286
./run_extra.sh mnist a standard carlini 6986
./run_extra.sh mnist a adversarial carlini 6986
./run_extra.sh mnist a relu carlini 6986
./run_extra.sh mnist b standard carlini 6986
./run_extra.sh mnist b adversarial carlini 6986
./run_extra.sh mnist b relu carlini 6986
./run_extra.sh mnist c standard carlini 6986
./run_extra.sh mnist c adversarial carlini 6986
./run_extra.sh mnist c relu carlini 6986
./run_extra.sh mnist a standard carlini 2653
./run_extra.sh mnist a adversarial carlini 2653
./run_extra.sh mnist a relu carlini 2653
./run_extra.sh mnist b standard carlini 2653
./run_extra.sh mnist b adversarial carlini 2653
./run_extra.sh mnist b relu carlini 2653
./run_extra.sh mnist c standard carlini 2653
./run_extra.sh mnist c adversarial carlini 2653
./run_extra.sh mnist c relu carlini 2653
./run_extra.sh mnist a standard carlini 7025
./run_extra.sh mnist a adversarial carlini 7025
./run_extra.sh mnist a relu carlini 7025
./run_extra.sh mnist b standard carlini 7025
./run_extra.sh mnist b adversarial carlini 7025
./run_extra.sh mnist b relu carlini 7025
./run_extra.sh mnist c standard carlini 7025
./run_extra.sh mnist c adversarial carlini 7025
./run_extra.sh mnist c relu carlini 7025
./run_extra.sh mnist a standard carlini 1331
./run_extra.sh mnist a adversarial carlini 1331
./run_extra.sh mnist a relu carlini 1331
./run_extra.sh mnist b standard carlini 1331
./run_extra.sh mnist b adversarial carlini 1331
./run_extra.sh mnist b relu carlini 1331
./run_extra.sh mnist c standard carlini 1331
./run_extra.sh mnist c adversarial carlini 1331
./run_extra.sh mnist c relu carlini 1331
./run_extra.sh mnist a standard carlini 373
./run_extra.sh mnist a adversarial carlini 373
./run_extra.sh mnist a relu carlini 373
./run_extra.sh mnist b standard carlini 373
./run_extra.sh mnist b adversarial carlini 373
./run_extra.sh mnist b relu carlini 373
./run_extra.sh mnist c standard carlini 373
./run_extra.sh mnist c adversarial carlini 373
./run_extra.sh mnist c relu carlini 373
./run_extra.sh mnist a standard carlini 8604
./run_extra.sh mnist a adversarial carlini 8604
./run_extra.sh mnist a relu carlini 8604
./run_extra.sh mnist b standard carlini 8604
./run_extra.sh mnist b adversarial carlini 8604
./run_extra.sh mnist b relu carlini 8604
./run_extra.sh mnist c standard carlini 8604
./run_extra.sh mnist c adversarial carlini 8604
./run_extra.sh mnist c relu carlini 8604
./run_extra.sh mnist a standard carlini 430
./run_extra.sh mnist a adversarial carlini 430
./run_extra.sh mnist a relu carlini 430
./run_extra.sh mnist b standard carlini 430
./run_extra.sh mnist b adversarial carlini 430
./run_extra.sh mnist b relu carlini 430
./run_extra.sh mnist c standard carlini 430
./run_extra.sh mnist c adversarial carlini 430
./run_extra.sh mnist c relu carlini 430
./run_extra.sh mnist a standard carlini 7995
./run_extra.sh mnist a adversarial carlini 7995
./run_extra.sh mnist a relu carlini 7995
./run_extra.sh mnist b standard carlini 7995
./run_extra.sh mnist b adversarial carlini 7995
./run_extra.sh mnist b relu carlini 7995
./run_extra.sh mnist c standard carlini 7995
./run_extra.sh mnist c adversarial carlini 7995
./run_extra.sh mnist c relu carlini 7995
./run_extra.sh mnist a standard carlini 5430
./run_extra.sh mnist a adversarial carlini 5430
./run_extra.sh mnist a relu carlini 5430
./run_extra.sh mnist b standard carlini 5430
./run_extra.sh mnist b adversarial carlini 5430
./run_extra.sh mnist b relu carlini 5430
./run_extra.sh mnist c standard carlini 5430
./run_extra.sh mnist c adversarial carlini 5430
./run_extra.sh mnist c relu carlini 5430
./run_extra.sh mnist a standard carlini 2515
./run_extra.sh mnist a adversarial carlini 2515
./run_extra.sh mnist a relu carlini 2515
./run_extra.sh mnist b standard carlini 2515
./run_extra.sh mnist b adversarial carlini 2515
./run_extra.sh mnist b relu carlini 2515
./run_extra.sh mnist c standard carlini 2515
./run_extra.sh mnist c adversarial carlini 2515
./run_extra.sh mnist c relu carlini 2515
./run_extra.sh mnist a standard carlini 3952
./run_extra.sh mnist a adversarial carlini 3952
./run_extra.sh mnist a relu carlini 3952
./run_extra.sh mnist b standard carlini 3952
./run_extra.sh mnist b adversarial carlini 3952
./run_extra.sh mnist b relu carlini 3952
./run_extra.sh mnist c standard carlini 3952
./run_extra.sh mnist c adversarial carlini 3952
./run_extra.sh mnist c relu carlini 3952
./run_extra.sh mnist a standard carlini 4882
./run_extra.sh mnist a adversarial carlini 4882
./run_extra.sh mnist a relu carlini 4882
./run_extra.sh mnist b standard carlini 4882
./run_extra.sh mnist b adversarial carlini 4882
./run_extra.sh mnist b relu carlini 4882
./run_extra.sh mnist c standard carlini 4882
./run_extra.sh mnist c adversarial carlini 4882
./run_extra.sh mnist c relu carlini 4882
./run_extra.sh mnist a standard carlini 3751
./run_extra.sh mnist a adversarial carlini 3751
./run_extra.sh mnist a relu carlini 3751
./run_extra.sh mnist b standard carlini 3751
./run_extra.sh mnist b adversarial carlini 3751
./run_extra.sh mnist b relu carlini 3751
./run_extra.sh mnist c standard carlini 3751
./run_extra.sh mnist c adversarial carlini 3751
./run_extra.sh mnist c relu carlini 3751
./run_extra.sh mnist a standard carlini 9903
./run_extra.sh mnist a adversarial carlini 9903
./run_extra.sh mnist a relu carlini 9903
./run_extra.sh mnist b standard carlini 9903
./run_extra.sh mnist b adversarial carlini 9903
./run_extra.sh mnist b relu carlini 9903
./run_extra.sh mnist c standard carlini 9903
./run_extra.sh mnist c adversarial carlini 9903
./run_extra.sh mnist c relu carlini 9903
./run_extra.sh mnist a standard carlini 6872
./run_extra.sh mnist a adversarial carlini 6872
./run_extra.sh mnist a relu carlini 6872
./run_extra.sh mnist b standard carlini 6872
./run_extra.sh mnist b adversarial carlini 6872
./run_extra.sh mnist b relu carlini 6872
./run_extra.sh mnist c standard carlini 6872
./run_extra.sh mnist c adversarial carlini 6872
./run_extra.sh mnist c relu carlini 6872
./run_extra.sh mnist a standard carlini 9694
./run_extra.sh mnist a adversarial carlini 9694
./run_extra.sh mnist a relu carlini 9694
./run_extra.sh mnist b standard carlini 9694
./run_extra.sh mnist b adversarial carlini 9694
./run_extra.sh mnist b relu carlini 9694
./run_extra.sh mnist c standard carlini 9694
./run_extra.sh mnist c adversarial carlini 9694
./run_extra.sh mnist c relu carlini 9694
./run_extra.sh mnist a standard carlini 4600
./run_extra.sh mnist a adversarial carlini 4600
./run_extra.sh mnist a relu carlini 4600
./run_extra.sh mnist b standard carlini 4600
./run_extra.sh mnist b adversarial carlini 4600
./run_extra.sh mnist b relu carlini 4600
./run_extra.sh mnist c standard carlini 4600
./run_extra.sh mnist c adversarial carlini 4600
./run_extra.sh mnist c relu carlini 4600
./run_extra.sh mnist a standard carlini 3156
./run_extra.sh mnist a adversarial carlini 3156
./run_extra.sh mnist a relu carlini 3156
./run_extra.sh mnist b standard carlini 3156
./run_extra.sh mnist b adversarial carlini 3156
./run_extra.sh mnist b relu carlini 3156
./run_extra.sh mnist c standard carlini 3156
./run_extra.sh mnist c adversarial carlini 3156
./run_extra.sh mnist c relu carlini 3156
./run_extra.sh mnist a standard carlini 3608
./run_extra.sh mnist a adversarial carlini 3608
./run_extra.sh mnist a relu carlini 3608
./run_extra.sh mnist b standard carlini 3608
./run_extra.sh mnist b adversarial carlini 3608
./run_extra.sh mnist b relu carlini 3608
./run_extra.sh mnist c standard carlini 3608
./run_extra.sh mnist c adversarial carlini 3608
./run_extra.sh mnist c relu carlini 3608
./run_extra.sh mnist a standard carlini 5310
./run_extra.sh mnist a adversarial carlini 5310
./run_extra.sh mnist a relu carlini 5310
./run_extra.sh mnist b standard carlini 5310
./run_extra.sh mnist b adversarial carlini 5310
./run_extra.sh mnist b relu carlini 5310
./run_extra.sh mnist c standard carlini 5310
./run_extra.sh mnist c adversarial carlini 5310
./run_extra.sh mnist c relu carlini 5310
./run_extra.sh mnist a standard carlini 1947
./run_extra.sh mnist a adversarial carlini 1947
./run_extra.sh mnist a relu carlini 1947
./run_extra.sh mnist b standard carlini 1947
./run_extra.sh mnist b adversarial carlini 1947
./run_extra.sh mnist b relu carlini 1947
./run_extra.sh mnist c standard carlini 1947
./run_extra.sh mnist c adversarial carlini 1947
./run_extra.sh mnist c relu carlini 1947
./run_extra.sh mnist a standard carlini 2313
./run_extra.sh mnist a adversarial carlini 2313
./run_extra.sh mnist a relu carlini 2313
./run_extra.sh mnist b standard carlini 2313
./run_extra.sh mnist b adversarial carlini 2313
./run_extra.sh mnist b relu carlini 2313
./run_extra.sh mnist c standard carlini 2313
./run_extra.sh mnist c adversarial carlini 2313
./run_extra.sh mnist c relu carlini 2313
./run_extra.sh mnist a standard carlini 5648
./run_extra.sh mnist a adversarial carlini 5648
./run_extra.sh mnist a relu carlini 5648
./run_extra.sh mnist b standard carlini 5648
./run_extra.sh mnist b adversarial carlini 5648
./run_extra.sh mnist b relu carlini 5648
./run_extra.sh mnist c standard carlini 5648
./run_extra.sh mnist c adversarial carlini 5648
./run_extra.sh mnist c relu carlini 5648
./run_extra.sh mnist a standard carlini 7402
./run_extra.sh mnist a adversarial carlini 7402
./run_extra.sh mnist a relu carlini 7402
./run_extra.sh mnist b standard carlini 7402
./run_extra.sh mnist b adversarial carlini 7402
./run_extra.sh mnist b relu carlini 7402
./run_extra.sh mnist c standard carlini 7402
./run_extra.sh mnist c adversarial carlini 7402
./run_extra.sh mnist c relu carlini 7402
./run_extra.sh mnist a standard carlini 9828
./run_extra.sh mnist a adversarial carlini 9828
./run_extra.sh mnist a relu carlini 9828
./run_extra.sh mnist b standard carlini 9828
./run_extra.sh mnist b adversarial carlini 9828
./run_extra.sh mnist b relu carlini 9828
./run_extra.sh mnist c standard carlini 9828
./run_extra.sh mnist c adversarial carlini 9828
./run_extra.sh mnist c relu carlini 9828
./run_extra.sh mnist a standard carlini 6059
./run_extra.sh mnist a adversarial carlini 6059
./run_extra.sh mnist a relu carlini 6059
./run_extra.sh mnist b standard carlini 6059
./run_extra.sh mnist b adversarial carlini 6059
./run_extra.sh mnist b relu carlini 6059
./run_extra.sh mnist c standard carlini 6059
./run_extra.sh mnist c adversarial carlini 6059
./run_extra.sh mnist c relu carlini 6059
./run_extra.sh mnist a standard carlini 6701
./run_extra.sh mnist a adversarial carlini 6701
./run_extra.sh mnist a relu carlini 6701
./run_extra.sh mnist b standard carlini 6701
./run_extra.sh mnist b adversarial carlini 6701
./run_extra.sh mnist b relu carlini 6701
./run_extra.sh mnist c standard carlini 6701
./run_extra.sh mnist c adversarial carlini 6701
./run_extra.sh mnist c relu carlini 6701
./run_extra.sh mnist a standard carlini 7010
./run_extra.sh mnist a adversarial carlini 7010
./run_extra.sh mnist a relu carlini 7010
./run_extra.sh mnist b standard carlini 7010
./run_extra.sh mnist b adversarial carlini 7010
./run_extra.sh mnist b relu carlini 7010
./run_extra.sh mnist c standard carlini 7010
./run_extra.sh mnist c adversarial carlini 7010
./run_extra.sh mnist c relu carlini 7010
./run_extra.sh mnist a standard carlini 6860
./run_extra.sh mnist a adversarial carlini 6860
./run_extra.sh mnist a relu carlini 6860
./run_extra.sh mnist b standard carlini 6860
./run_extra.sh mnist b adversarial carlini 6860
./run_extra.sh mnist b relu carlini 6860
./run_extra.sh mnist c standard carlini 6860
./run_extra.sh mnist c adversarial carlini 6860
./run_extra.sh mnist c relu carlini 6860
./run_extra.sh mnist a standard carlini 3455
./run_extra.sh mnist a adversarial carlini 3455
./run_extra.sh mnist a relu carlini 3455
./run_extra.sh mnist b standard carlini 3455
./run_extra.sh mnist b adversarial carlini 3455
./run_extra.sh mnist b relu carlini 3455
./run_extra.sh mnist c standard carlini 3455
./run_extra.sh mnist c adversarial carlini 3455
./run_extra.sh mnist c relu carlini 3455
./run_extra.sh mnist a standard carlini 8084
./run_extra.sh mnist a adversarial carlini 8084
./run_extra.sh mnist a relu carlini 8084
./run_extra.sh mnist b standard carlini 8084
./run_extra.sh mnist b adversarial carlini 8084
./run_extra.sh mnist b relu carlini 8084
./run_extra.sh mnist c standard carlini 8084
./run_extra.sh mnist c adversarial carlini 8084
./run_extra.sh mnist c relu carlini 8084
./run_extra.sh mnist a standard carlini 5178
./run_extra.sh mnist a adversarial carlini 5178
./run_extra.sh mnist a relu carlini 5178
./run_extra.sh mnist b standard carlini 5178
./run_extra.sh mnist b adversarial carlini 5178
./run_extra.sh mnist b relu carlini 5178
./run_extra.sh mnist c standard carlini 5178
./run_extra.sh mnist c adversarial carlini 5178
./run_extra.sh mnist c relu carlini 5178
./run_extra.sh mnist a standard carlini 8330
./run_extra.sh mnist a adversarial carlini 8330
./run_extra.sh mnist a relu carlini 8330
./run_extra.sh mnist b standard carlini 8330
./run_extra.sh mnist b adversarial carlini 8330
./run_extra.sh mnist b relu carlini 8330
./run_extra.sh mnist c standard carlini 8330
./run_extra.sh mnist c adversarial carlini 8330
./run_extra.sh mnist c relu carlini 8330
./run_extra.sh mnist a standard carlini 7631
./run_extra.sh mnist a adversarial carlini 7631
./run_extra.sh mnist a relu carlini 7631
./run_extra.sh mnist b standard carlini 7631
./run_extra.sh mnist b adversarial carlini 7631
./run_extra.sh mnist b relu carlini 7631
./run_extra.sh mnist c standard carlini 7631
./run_extra.sh mnist c adversarial carlini 7631
./run_extra.sh mnist c relu carlini 7631
./run_extra.sh mnist a standard carlini 8067
./run_extra.sh mnist a adversarial carlini 8067
./run_extra.sh mnist a relu carlini 8067
./run_extra.sh mnist b standard carlini 8067
./run_extra.sh mnist b adversarial carlini 8067
./run_extra.sh mnist b relu carlini 8067
./run_extra.sh mnist c standard carlini 8067
./run_extra.sh mnist c adversarial carlini 8067
./run_extra.sh mnist c relu carlini 8067
./run_extra.sh mnist a standard carlini 9347
./run_extra.sh mnist a adversarial carlini 9347
./run_extra.sh mnist a relu carlini 9347
./run_extra.sh mnist b standard carlini 9347
./run_extra.sh mnist b adversarial carlini 9347
./run_extra.sh mnist b relu carlini 9347
./run_extra.sh mnist c standard carlini 9347
./run_extra.sh mnist c adversarial carlini 9347
./run_extra.sh mnist c relu carlini 9347
./run_extra.sh mnist a standard carlini 1918
./run_extra.sh mnist a adversarial carlini 1918
./run_extra.sh mnist a relu carlini 1918
./run_extra.sh mnist b standard carlini 1918
./run_extra.sh mnist b adversarial carlini 1918
./run_extra.sh mnist b relu carlini 1918
./run_extra.sh mnist c standard carlini 1918
./run_extra.sh mnist c adversarial carlini 1918
./run_extra.sh mnist c relu carlini 1918
./run_extra.sh mnist a standard carlini 7149
./run_extra.sh mnist a adversarial carlini 7149
./run_extra.sh mnist a relu carlini 7149
./run_extra.sh mnist b standard carlini 7149
./run_extra.sh mnist b adversarial carlini 7149
./run_extra.sh mnist b relu carlini 7149
./run_extra.sh mnist c standard carlini 7149
./run_extra.sh mnist c adversarial carlini 7149
./run_extra.sh mnist c relu carlini 7149
./run_extra.sh mnist a standard carlini 1318
./run_extra.sh mnist a adversarial carlini 1318
./run_extra.sh mnist a relu carlini 1318
./run_extra.sh mnist b standard carlini 1318
./run_extra.sh mnist b adversarial carlini 1318
./run_extra.sh mnist b relu carlini 1318
./run_extra.sh mnist c standard carlini 1318
./run_extra.sh mnist c adversarial carlini 1318
./run_extra.sh mnist c relu carlini 1318
./run_extra.sh mnist a standard carlini 2594
./run_extra.sh mnist a adversarial carlini 2594
./run_extra.sh mnist a relu carlini 2594
./run_extra.sh mnist b standard carlini 2594
./run_extra.sh mnist b adversarial carlini 2594
./run_extra.sh mnist b relu carlini 2594
./run_extra.sh mnist c standard carlini 2594
./run_extra.sh mnist c adversarial carlini 2594
./run_extra.sh mnist c relu carlini 2594
./run_extra.sh mnist a standard carlini 6478
./run_extra.sh mnist a adversarial carlini 6478
./run_extra.sh mnist a relu carlini 6478
./run_extra.sh mnist b standard carlini 6478
./run_extra.sh mnist b adversarial carlini 6478
./run_extra.sh mnist b relu carlini 6478
./run_extra.sh mnist c standard carlini 6478
./run_extra.sh mnist c adversarial carlini 6478
./run_extra.sh mnist c relu carlini 6478
./run_extra.sh mnist a standard carlini 807
./run_extra.sh mnist a adversarial carlini 807
./run_extra.sh mnist a relu carlini 807
./run_extra.sh mnist b standard carlini 807
./run_extra.sh mnist b adversarial carlini 807
./run_extra.sh mnist b relu carlini 807
./run_extra.sh mnist c standard carlini 807
./run_extra.sh mnist c adversarial carlini 807
./run_extra.sh mnist c relu carlini 807
./run_extra.sh mnist a standard carlini 9508
./run_extra.sh mnist a adversarial carlini 9508
./run_extra.sh mnist a relu carlini 9508
./run_extra.sh mnist b standard carlini 9508
./run_extra.sh mnist b adversarial carlini 9508
./run_extra.sh mnist b relu carlini 9508
./run_extra.sh mnist c standard carlini 9508
./run_extra.sh mnist c adversarial carlini 9508
./run_extra.sh mnist c relu carlini 9508
./run_extra.sh mnist a standard carlini 2744
./run_extra.sh mnist a adversarial carlini 2744
./run_extra.sh mnist a relu carlini 2744
./run_extra.sh mnist b standard carlini 2744
./run_extra.sh mnist b adversarial carlini 2744
./run_extra.sh mnist b relu carlini 2744
./run_extra.sh mnist c standard carlini 2744
./run_extra.sh mnist c adversarial carlini 2744
./run_extra.sh mnist c relu carlini 2744
./run_extra.sh mnist a standard carlini 5800
./run_extra.sh mnist a adversarial carlini 5800
./run_extra.sh mnist a relu carlini 5800
./run_extra.sh mnist b standard carlini 5800
./run_extra.sh mnist b adversarial carlini 5800
./run_extra.sh mnist b relu carlini 5800
./run_extra.sh mnist c standard carlini 5800
./run_extra.sh mnist c adversarial carlini 5800
./run_extra.sh mnist c relu carlini 5800
./run_extra.sh mnist a standard carlini 3552
./run_extra.sh mnist a adversarial carlini 3552
./run_extra.sh mnist a relu carlini 3552
./run_extra.sh mnist b standard carlini 3552
./run_extra.sh mnist b adversarial carlini 3552
./run_extra.sh mnist b relu carlini 3552
./run_extra.sh mnist c standard carlini 3552
./run_extra.sh mnist c adversarial carlini 3552
./run_extra.sh mnist c relu carlini 3552
./run_extra.sh mnist a standard carlini 5997
./run_extra.sh mnist a adversarial carlini 5997
./run_extra.sh mnist a relu carlini 5997
./run_extra.sh mnist b standard carlini 5997
./run_extra.sh mnist b adversarial carlini 5997
./run_extra.sh mnist b relu carlini 5997
./run_extra.sh mnist c standard carlini 5997
./run_extra.sh mnist c adversarial carlini 5997
./run_extra.sh mnist c relu carlini 5997
./run_extra.sh mnist a standard carlini 1115
./run_extra.sh mnist a adversarial carlini 1115
./run_extra.sh mnist a relu carlini 1115
./run_extra.sh mnist b standard carlini 1115
./run_extra.sh mnist b adversarial carlini 1115
./run_extra.sh mnist b relu carlini 1115
./run_extra.sh mnist c standard carlini 1115
./run_extra.sh mnist c adversarial carlini 1115
./run_extra.sh mnist c relu carlini 1115
./run_extra.sh mnist a standard carlini 5560
./run_extra.sh mnist a adversarial carlini 5560
./run_extra.sh mnist a relu carlini 5560
./run_extra.sh mnist b standard carlini 5560
./run_extra.sh mnist b adversarial carlini 5560
./run_extra.sh mnist b relu carlini 5560
./run_extra.sh mnist c standard carlini 5560
./run_extra.sh mnist c adversarial carlini 5560
./run_extra.sh mnist c relu carlini 5560
./run_extra.sh mnist a standard carlini 2619
./run_extra.sh mnist a adversarial carlini 2619
./run_extra.sh mnist a relu carlini 2619
./run_extra.sh mnist b standard carlini 2619
./run_extra.sh mnist b adversarial carlini 2619
./run_extra.sh mnist b relu carlini 2619
./run_extra.sh mnist c standard carlini 2619
./run_extra.sh mnist c adversarial carlini 2619
./run_extra.sh mnist c relu carlini 2619
./run_extra.sh mnist a standard carlini 4531
./run_extra.sh mnist a adversarial carlini 4531
./run_extra.sh mnist a relu carlini 4531
./run_extra.sh mnist b standard carlini 4531
./run_extra.sh mnist b adversarial carlini 4531
./run_extra.sh mnist b relu carlini 4531
./run_extra.sh mnist c standard carlini 4531
./run_extra.sh mnist c adversarial carlini 4531
./run_extra.sh mnist c relu carlini 4531
./run_extra.sh mnist a standard carlini 3653
./run_extra.sh mnist a adversarial carlini 3653
./run_extra.sh mnist a relu carlini 3653
./run_extra.sh mnist b standard carlini 3653
./run_extra.sh mnist b adversarial carlini 3653
./run_extra.sh mnist b relu carlini 3653
./run_extra.sh mnist c standard carlini 3653
./run_extra.sh mnist c adversarial carlini 3653
./run_extra.sh mnist c relu carlini 3653
./run_extra.sh mnist a standard carlini 6284
./run_extra.sh mnist a adversarial carlini 6284
./run_extra.sh mnist a relu carlini 6284
./run_extra.sh mnist b standard carlini 6284
./run_extra.sh mnist b adversarial carlini 6284
./run_extra.sh mnist b relu carlini 6284
./run_extra.sh mnist c standard carlini 6284
./run_extra.sh mnist c adversarial carlini 6284
./run_extra.sh mnist c relu carlini 6284
./run_extra.sh mnist a standard carlini 7142
./run_extra.sh mnist a adversarial carlini 7142
./run_extra.sh mnist a relu carlini 7142
./run_extra.sh mnist b standard carlini 7142
./run_extra.sh mnist b adversarial carlini 7142
./run_extra.sh mnist b relu carlini 7142
./run_extra.sh mnist c standard carlini 7142
./run_extra.sh mnist c adversarial carlini 7142
./run_extra.sh mnist c relu carlini 7142
./run_extra.sh mnist a standard carlini 296
./run_extra.sh mnist a adversarial carlini 296
./run_extra.sh mnist a relu carlini 296
./run_extra.sh mnist b standard carlini 296
./run_extra.sh mnist b adversarial carlini 296
./run_extra.sh mnist b relu carlini 296
./run_extra.sh mnist c standard carlini 296
./run_extra.sh mnist c adversarial carlini 296
./run_extra.sh mnist c relu carlini 296
./run_extra.sh mnist a standard carlini 6402
./run_extra.sh mnist a adversarial carlini 6402
./run_extra.sh mnist a relu carlini 6402
./run_extra.sh mnist b standard carlini 6402
./run_extra.sh mnist b adversarial carlini 6402
./run_extra.sh mnist b relu carlini 6402
./run_extra.sh mnist c standard carlini 6402
./run_extra.sh mnist c adversarial carlini 6402
./run_extra.sh mnist c relu carlini 6402
./run_extra.sh mnist a standard carlini 2682
./run_extra.sh mnist a adversarial carlini 2682
./run_extra.sh mnist a relu carlini 2682
./run_extra.sh mnist b standard carlini 2682
./run_extra.sh mnist b adversarial carlini 2682
./run_extra.sh mnist b relu carlini 2682
./run_extra.sh mnist c standard carlini 2682
./run_extra.sh mnist c adversarial carlini 2682
./run_extra.sh mnist c relu carlini 2682
./run_extra.sh mnist a standard carlini 9240
./run_extra.sh mnist a adversarial carlini 9240
./run_extra.sh mnist a relu carlini 9240
./run_extra.sh mnist b standard carlini 9240
./run_extra.sh mnist b adversarial carlini 9240
./run_extra.sh mnist b relu carlini 9240
./run_extra.sh mnist c standard carlini 9240
./run_extra.sh mnist c adversarial carlini 9240
./run_extra.sh mnist c relu carlini 9240
./run_extra.sh mnist a standard carlini 5616
./run_extra.sh mnist a adversarial carlini 5616
./run_extra.sh mnist a relu carlini 5616
./run_extra.sh mnist b standard carlini 5616
./run_extra.sh mnist b adversarial carlini 5616
./run_extra.sh mnist b relu carlini 5616
./run_extra.sh mnist c standard carlini 5616
./run_extra.sh mnist c adversarial carlini 5616
./run_extra.sh mnist c relu carlini 5616
./run_extra.sh mnist a standard carlini 4784
./run_extra.sh mnist a adversarial carlini 4784
./run_extra.sh mnist a relu carlini 4784
./run_extra.sh mnist b standard carlini 4784
./run_extra.sh mnist b adversarial carlini 4784
./run_extra.sh mnist b relu carlini 4784
./run_extra.sh mnist c standard carlini 4784
./run_extra.sh mnist c adversarial carlini 4784
./run_extra.sh mnist c relu carlini 4784
./run_extra.sh mnist a standard carlini 9895
./run_extra.sh mnist a adversarial carlini 9895
./run_extra.sh mnist a relu carlini 9895
./run_extra.sh mnist b standard carlini 9895
./run_extra.sh mnist b adversarial carlini 9895
./run_extra.sh mnist b relu carlini 9895
./run_extra.sh mnist c standard carlini 9895
./run_extra.sh mnist c adversarial carlini 9895
./run_extra.sh mnist c relu carlini 9895
./run_extra.sh mnist a standard carlini 5051
./run_extra.sh mnist a adversarial carlini 5051
./run_extra.sh mnist a relu carlini 5051
./run_extra.sh mnist b standard carlini 5051
./run_extra.sh mnist b adversarial carlini 5051
./run_extra.sh mnist b relu carlini 5051
./run_extra.sh mnist c standard carlini 5051
./run_extra.sh mnist c adversarial carlini 5051
./run_extra.sh mnist c relu carlini 5051
./run_extra.sh mnist a standard carlini 9860
./run_extra.sh mnist a adversarial carlini 9860
./run_extra.sh mnist a relu carlini 9860
./run_extra.sh mnist b standard carlini 9860
./run_extra.sh mnist b adversarial carlini 9860
./run_extra.sh mnist b relu carlini 9860
./run_extra.sh mnist c standard carlini 9860
./run_extra.sh mnist c adversarial carlini 9860
./run_extra.sh mnist c relu carlini 9860
./run_extra.sh mnist a standard carlini 8716
./run_extra.sh mnist a adversarial carlini 8716
./run_extra.sh mnist a relu carlini 8716
./run_extra.sh mnist b standard carlini 8716
./run_extra.sh mnist b adversarial carlini 8716
./run_extra.sh mnist b relu carlini 8716
./run_extra.sh mnist c standard carlini 8716
./run_extra.sh mnist c adversarial carlini 8716
./run_extra.sh mnist c relu carlini 8716
./run_extra.sh mnist a standard carlini 6706
./run_extra.sh mnist a adversarial carlini 6706
./run_extra.sh mnist a relu carlini 6706
./run_extra.sh mnist b standard carlini 6706
./run_extra.sh mnist b adversarial carlini 6706
./run_extra.sh mnist b relu carlini 6706
./run_extra.sh mnist c standard carlini 6706
./run_extra.sh mnist c adversarial carlini 6706
./run_extra.sh mnist c relu carlini 6706
./run_extra.sh mnist a standard carlini 9871
./run_extra.sh mnist a adversarial carlini 9871
./run_extra.sh mnist a relu carlini 9871
./run_extra.sh mnist b standard carlini 9871
./run_extra.sh mnist b adversarial carlini 9871
./run_extra.sh mnist b relu carlini 9871
./run_extra.sh mnist c standard carlini 9871
./run_extra.sh mnist c adversarial carlini 9871
./run_extra.sh mnist c relu carlini 9871
./run_extra.sh mnist a standard carlini 9732
./run_extra.sh mnist a adversarial carlini 9732
./run_extra.sh mnist a relu carlini 9732
./run_extra.sh mnist b standard carlini 9732
./run_extra.sh mnist b adversarial carlini 9732
./run_extra.sh mnist b relu carlini 9732
./run_extra.sh mnist c standard carlini 9732
./run_extra.sh mnist c adversarial carlini 9732
./run_extra.sh mnist c relu carlini 9732
./run_extra.sh mnist a standard carlini 5385
./run_extra.sh mnist a adversarial carlini 5385
./run_extra.sh mnist a relu carlini 5385
./run_extra.sh mnist b standard carlini 5385
./run_extra.sh mnist b adversarial carlini 5385
./run_extra.sh mnist b relu carlini 5385
./run_extra.sh mnist c standard carlini 5385
./run_extra.sh mnist c adversarial carlini 5385
./run_extra.sh mnist c relu carlini 5385
./run_extra.sh mnist a standard carlini 6091
./run_extra.sh mnist a adversarial carlini 6091
./run_extra.sh mnist a relu carlini 6091
./run_extra.sh mnist b standard carlini 6091
./run_extra.sh mnist b adversarial carlini 6091
./run_extra.sh mnist b relu carlini 6091
./run_extra.sh mnist c standard carlini 6091
./run_extra.sh mnist c adversarial carlini 6091
./run_extra.sh mnist c relu carlini 6091
./run_extra.sh mnist a standard carlini 9206
./run_extra.sh mnist a adversarial carlini 9206
./run_extra.sh mnist a relu carlini 9206
./run_extra.sh mnist b standard carlini 9206
./run_extra.sh mnist b adversarial carlini 9206
./run_extra.sh mnist b relu carlini 9206
./run_extra.sh mnist c standard carlini 9206
./run_extra.sh mnist c adversarial carlini 9206
./run_extra.sh mnist c relu carlini 9206
./run_extra.sh mnist a standard carlini 3918
./run_extra.sh mnist a adversarial carlini 3918
./run_extra.sh mnist a relu carlini 3918
./run_extra.sh mnist b standard carlini 3918
./run_extra.sh mnist b adversarial carlini 3918
./run_extra.sh mnist b relu carlini 3918
./run_extra.sh mnist c standard carlini 3918
./run_extra.sh mnist c adversarial carlini 3918
./run_extra.sh mnist c relu carlini 3918
./run_extra.sh mnist a standard carlini 6764
./run_extra.sh mnist a adversarial carlini 6764
./run_extra.sh mnist a relu carlini 6764
./run_extra.sh mnist b standard carlini 6764
./run_extra.sh mnist b adversarial carlini 6764
./run_extra.sh mnist b relu carlini 6764
./run_extra.sh mnist c standard carlini 6764
./run_extra.sh mnist c adversarial carlini 6764
./run_extra.sh mnist c relu carlini 6764
./run_extra.sh mnist a standard carlini 1761
./run_extra.sh mnist a adversarial carlini 1761
./run_extra.sh mnist a relu carlini 1761
./run_extra.sh mnist b standard carlini 1761
./run_extra.sh mnist b adversarial carlini 1761
./run_extra.sh mnist b relu carlini 1761
./run_extra.sh mnist c standard carlini 1761
./run_extra.sh mnist c adversarial carlini 1761
./run_extra.sh mnist c relu carlini 1761
./run_extra.sh mnist a standard carlini 959
./run_extra.sh mnist a adversarial carlini 959
./run_extra.sh mnist a relu carlini 959
./run_extra.sh mnist b standard carlini 959
./run_extra.sh mnist b adversarial carlini 959
./run_extra.sh mnist b relu carlini 959
./run_extra.sh mnist c standard carlini 959
./run_extra.sh mnist c adversarial carlini 959
./run_extra.sh mnist c relu carlini 959
./run_extra.sh mnist a standard carlini 629
./run_extra.sh mnist a adversarial carlini 629
./run_extra.sh mnist a relu carlini 629
./run_extra.sh mnist b standard carlini 629
./run_extra.sh mnist b adversarial carlini 629
./run_extra.sh mnist b relu carlini 629
./run_extra.sh mnist c standard carlini 629
./run_extra.sh mnist c adversarial carlini 629
./run_extra.sh mnist c relu carlini 629
./run_extra.sh mnist a standard carlini 7533
./run_extra.sh mnist a adversarial carlini 7533
./run_extra.sh mnist a relu carlini 7533
./run_extra.sh mnist b standard carlini 7533
./run_extra.sh mnist b adversarial carlini 7533
./run_extra.sh mnist b relu carlini 7533
./run_extra.sh mnist c standard carlini 7533
./run_extra.sh mnist c adversarial carlini 7533
./run_extra.sh mnist c relu carlini 7533
./run_extra.sh mnist a standard carlini 9535
./run_extra.sh mnist a adversarial carlini 9535
./run_extra.sh mnist a relu carlini 9535
./run_extra.sh mnist b standard carlini 9535
./run_extra.sh mnist b adversarial carlini 9535
./run_extra.sh mnist b relu carlini 9535
./run_extra.sh mnist c standard carlini 9535
./run_extra.sh mnist c adversarial carlini 9535
./run_extra.sh mnist c relu carlini 9535
./run_extra.sh mnist a standard carlini 8660
./run_extra.sh mnist a adversarial carlini 8660
./run_extra.sh mnist a relu carlini 8660
./run_extra.sh mnist b standard carlini 8660
./run_extra.sh mnist b adversarial carlini 8660
./run_extra.sh mnist b relu carlini 8660
./run_extra.sh mnist c standard carlini 8660
./run_extra.sh mnist c adversarial carlini 8660
./run_extra.sh mnist c relu carlini 8660
./run_extra.sh mnist a standard carlini 7748
./run_extra.sh mnist a adversarial carlini 7748
./run_extra.sh mnist a relu carlini 7748
./run_extra.sh mnist b standard carlini 7748
./run_extra.sh mnist b adversarial carlini 7748
./run_extra.sh mnist b relu carlini 7748
./run_extra.sh mnist c standard carlini 7748
./run_extra.sh mnist c adversarial carlini 7748
./run_extra.sh mnist c relu carlini 7748
./run_extra.sh mnist a standard carlini 6504
./run_extra.sh mnist a adversarial carlini 6504
./run_extra.sh mnist a relu carlini 6504
./run_extra.sh mnist b standard carlini 6504
./run_extra.sh mnist b adversarial carlini 6504
./run_extra.sh mnist b relu carlini 6504
./run_extra.sh mnist c standard carlini 6504
./run_extra.sh mnist c adversarial carlini 6504
./run_extra.sh mnist c relu carlini 6504
./run_extra.sh mnist a standard carlini 2256
./run_extra.sh mnist a adversarial carlini 2256
./run_extra.sh mnist a relu carlini 2256
./run_extra.sh mnist b standard carlini 2256
./run_extra.sh mnist b adversarial carlini 2256
./run_extra.sh mnist b relu carlini 2256
./run_extra.sh mnist c standard carlini 2256
./run_extra.sh mnist c adversarial carlini 2256
./run_extra.sh mnist c relu carlini 2256
./run_extra.sh mnist a standard carlini 4290
./run_extra.sh mnist a adversarial carlini 4290
./run_extra.sh mnist a relu carlini 4290
./run_extra.sh mnist b standard carlini 4290
./run_extra.sh mnist b adversarial carlini 4290
./run_extra.sh mnist b relu carlini 4290
./run_extra.sh mnist c standard carlini 4290
./run_extra.sh mnist c adversarial carlini 4290
./run_extra.sh mnist c relu carlini 4290
./run_extra.sh mnist a standard carlini 4704
./run_extra.sh mnist a adversarial carlini 4704
./run_extra.sh mnist a relu carlini 4704
./run_extra.sh mnist b standard carlini 4704
./run_extra.sh mnist b adversarial carlini 4704
./run_extra.sh mnist b relu carlini 4704
./run_extra.sh mnist c standard carlini 4704
./run_extra.sh mnist c adversarial carlini 4704
./run_extra.sh mnist c relu carlini 4704
./run_extra.sh mnist a standard carlini 812
./run_extra.sh mnist a adversarial carlini 812
./run_extra.sh mnist a relu carlini 812
./run_extra.sh mnist b standard carlini 812
./run_extra.sh mnist b adversarial carlini 812
./run_extra.sh mnist b relu carlini 812
./run_extra.sh mnist c standard carlini 812
./run_extra.sh mnist c adversarial carlini 812
./run_extra.sh mnist c relu carlini 812
./run_extra.sh mnist a standard carlini 6716
./run_extra.sh mnist a adversarial carlini 6716
./run_extra.sh mnist a relu carlini 6716
./run_extra.sh mnist b standard carlini 6716
./run_extra.sh mnist b adversarial carlini 6716
./run_extra.sh mnist b relu carlini 6716
./run_extra.sh mnist c standard carlini 6716
./run_extra.sh mnist c adversarial carlini 6716
./run_extra.sh mnist c relu carlini 6716
./run_extra.sh mnist a standard carlini 8747
./run_extra.sh mnist a adversarial carlini 8747
./run_extra.sh mnist a relu carlini 8747
./run_extra.sh mnist b standard carlini 8747
./run_extra.sh mnist b adversarial carlini 8747
./run_extra.sh mnist b relu carlini 8747
./run_extra.sh mnist c standard carlini 8747
./run_extra.sh mnist c adversarial carlini 8747
./run_extra.sh mnist c relu carlini 8747
./run_extra.sh mnist a standard carlini 2065
./run_extra.sh mnist a adversarial carlini 2065
./run_extra.sh mnist a relu carlini 2065
./run_extra.sh mnist b standard carlini 2065
./run_extra.sh mnist b adversarial carlini 2065
./run_extra.sh mnist b relu carlini 2065
./run_extra.sh mnist c standard carlini 2065
./run_extra.sh mnist c adversarial carlini 2065
./run_extra.sh mnist c relu carlini 2065
./run_extra.sh mnist a standard carlini 7094
./run_extra.sh mnist a adversarial carlini 7094
./run_extra.sh mnist a relu carlini 7094
./run_extra.sh mnist b standard carlini 7094
./run_extra.sh mnist b adversarial carlini 7094
./run_extra.sh mnist b relu carlini 7094
./run_extra.sh mnist c standard carlini 7094
./run_extra.sh mnist c adversarial carlini 7094
./run_extra.sh mnist c relu carlini 7094
./run_extra.sh mnist a standard carlini 6230
./run_extra.sh mnist a adversarial carlini 6230
./run_extra.sh mnist a relu carlini 6230
./run_extra.sh mnist b standard carlini 6230
./run_extra.sh mnist b adversarial carlini 6230
./run_extra.sh mnist b relu carlini 6230
./run_extra.sh mnist c standard carlini 6230
./run_extra.sh mnist c adversarial carlini 6230
./run_extra.sh mnist c relu carlini 6230
./run_extra.sh mnist a standard carlini 3231
./run_extra.sh mnist a adversarial carlini 3231
./run_extra.sh mnist a relu carlini 3231
./run_extra.sh mnist b standard carlini 3231
./run_extra.sh mnist b adversarial carlini 3231
./run_extra.sh mnist b relu carlini 3231
./run_extra.sh mnist c standard carlini 3231
./run_extra.sh mnist c adversarial carlini 3231
./run_extra.sh mnist c relu carlini 3231
./run_extra.sh mnist a standard carlini 3397
./run_extra.sh mnist a adversarial carlini 3397
./run_extra.sh mnist a relu carlini 3397
./run_extra.sh mnist b standard carlini 3397
./run_extra.sh mnist b adversarial carlini 3397
./run_extra.sh mnist b relu carlini 3397
./run_extra.sh mnist c standard carlini 3397
./run_extra.sh mnist c adversarial carlini 3397
./run_extra.sh mnist c relu carlini 3397
./run_extra.sh mnist a standard carlini 6534
./run_extra.sh mnist a adversarial carlini 6534
./run_extra.sh mnist a relu carlini 6534
./run_extra.sh mnist b standard carlini 6534
./run_extra.sh mnist b adversarial carlini 6534
./run_extra.sh mnist b relu carlini 6534
./run_extra.sh mnist c standard carlini 6534
./run_extra.sh mnist c adversarial carlini 6534
./run_extra.sh mnist c relu carlini 6534
./run_extra.sh mnist a standard carlini 7552
./run_extra.sh mnist a adversarial carlini 7552
./run_extra.sh mnist a relu carlini 7552
./run_extra.sh mnist b standard carlini 7552
./run_extra.sh mnist b adversarial carlini 7552
./run_extra.sh mnist b relu carlini 7552
./run_extra.sh mnist c standard carlini 7552
./run_extra.sh mnist c adversarial carlini 7552
./run_extra.sh mnist c relu carlini 7552
./run_extra.sh mnist a standard carlini 554
./run_extra.sh mnist a adversarial carlini 554
./run_extra.sh mnist a relu carlini 554
./run_extra.sh mnist b standard carlini 554
./run_extra.sh mnist b adversarial carlini 554
./run_extra.sh mnist b relu carlini 554
./run_extra.sh mnist c standard carlini 554
./run_extra.sh mnist c adversarial carlini 554
./run_extra.sh mnist c relu carlini 554
./run_extra.sh mnist a standard carlini 7506
./run_extra.sh mnist a adversarial carlini 7506
./run_extra.sh mnist a relu carlini 7506
./run_extra.sh mnist b standard carlini 7506
./run_extra.sh mnist b adversarial carlini 7506
./run_extra.sh mnist b relu carlini 7506
./run_extra.sh mnist c standard carlini 7506
./run_extra.sh mnist c adversarial carlini 7506
./run_extra.sh mnist c relu carlini 7506
./run_extra.sh mnist a standard carlini 8872
./run_extra.sh mnist a adversarial carlini 8872
./run_extra.sh mnist a relu carlini 8872
./run_extra.sh mnist b standard carlini 8872
./run_extra.sh mnist b adversarial carlini 8872
./run_extra.sh mnist b relu carlini 8872
./run_extra.sh mnist c standard carlini 8872
./run_extra.sh mnist c adversarial carlini 8872
./run_extra.sh mnist c relu carlini 8872
./run_extra.sh mnist a standard carlini 9000
./run_extra.sh mnist a adversarial carlini 9000
./run_extra.sh mnist a relu carlini 9000
./run_extra.sh mnist b standard carlini 9000
./run_extra.sh mnist b adversarial carlini 9000
./run_extra.sh mnist b relu carlini 9000
./run_extra.sh mnist c standard carlini 9000
./run_extra.sh mnist c adversarial carlini 9000
./run_extra.sh mnist c relu carlini 9000
./run_extra.sh mnist a standard carlini 1190
./run_extra.sh mnist a adversarial carlini 1190
./run_extra.sh mnist a relu carlini 1190
./run_extra.sh mnist b standard carlini 1190
./run_extra.sh mnist b adversarial carlini 1190
./run_extra.sh mnist b relu carlini 1190
./run_extra.sh mnist c standard carlini 1190
./run_extra.sh mnist c adversarial carlini 1190
./run_extra.sh mnist c relu carlini 1190
./run_extra.sh mnist a standard carlini 3075
./run_extra.sh mnist a adversarial carlini 3075
./run_extra.sh mnist a relu carlini 3075
./run_extra.sh mnist b standard carlini 3075
./run_extra.sh mnist b adversarial carlini 3075
./run_extra.sh mnist b relu carlini 3075
./run_extra.sh mnist c standard carlini 3075
./run_extra.sh mnist c adversarial carlini 3075
./run_extra.sh mnist c relu carlini 3075
./run_extra.sh mnist a standard carlini 4241
./run_extra.sh mnist a adversarial carlini 4241
./run_extra.sh mnist a relu carlini 4241
./run_extra.sh mnist b standard carlini 4241
./run_extra.sh mnist b adversarial carlini 4241
./run_extra.sh mnist b relu carlini 4241
./run_extra.sh mnist c standard carlini 4241
./run_extra.sh mnist c adversarial carlini 4241
./run_extra.sh mnist c relu carlini 4241
./run_extra.sh mnist a standard carlini 2736
./run_extra.sh mnist a adversarial carlini 2736
./run_extra.sh mnist a relu carlini 2736
./run_extra.sh mnist b standard carlini 2736
./run_extra.sh mnist b adversarial carlini 2736
./run_extra.sh mnist b relu carlini 2736
./run_extra.sh mnist c standard carlini 2736
./run_extra.sh mnist c adversarial carlini 2736
./run_extra.sh mnist c relu carlini 2736
./run_extra.sh mnist a standard carlini 365
./run_extra.sh mnist a adversarial carlini 365
./run_extra.sh mnist a relu carlini 365
./run_extra.sh mnist b standard carlini 365
./run_extra.sh mnist b adversarial carlini 365
./run_extra.sh mnist b relu carlini 365
./run_extra.sh mnist c standard carlini 365
./run_extra.sh mnist c adversarial carlini 365
./run_extra.sh mnist c relu carlini 365
./run_extra.sh mnist a standard carlini 7889
./run_extra.sh mnist a adversarial carlini 7889
./run_extra.sh mnist a relu carlini 7889
./run_extra.sh mnist b standard carlini 7889
./run_extra.sh mnist b adversarial carlini 7889
./run_extra.sh mnist b relu carlini 7889
./run_extra.sh mnist c standard carlini 7889
./run_extra.sh mnist c adversarial carlini 7889
./run_extra.sh mnist c relu carlini 7889
./run_extra.sh mnist a standard carlini 2244
./run_extra.sh mnist a adversarial carlini 2244
./run_extra.sh mnist a relu carlini 2244
./run_extra.sh mnist b standard carlini 2244
./run_extra.sh mnist b adversarial carlini 2244
./run_extra.sh mnist b relu carlini 2244
./run_extra.sh mnist c standard carlini 2244
./run_extra.sh mnist c adversarial carlini 2244
./run_extra.sh mnist c relu carlini 2244
./run_extra.sh mnist a standard carlini 8297
./run_extra.sh mnist a adversarial carlini 8297
./run_extra.sh mnist a relu carlini 8297
./run_extra.sh mnist b standard carlini 8297
./run_extra.sh mnist b adversarial carlini 8297
./run_extra.sh mnist b relu carlini 8297
./run_extra.sh mnist c standard carlini 8297
./run_extra.sh mnist c adversarial carlini 8297
./run_extra.sh mnist c relu carlini 8297
./run_extra.sh mnist a standard carlini 1679
./run_extra.sh mnist a adversarial carlini 1679
./run_extra.sh mnist a relu carlini 1679
./run_extra.sh mnist b standard carlini 1679
./run_extra.sh mnist b adversarial carlini 1679
./run_extra.sh mnist b relu carlini 1679
./run_extra.sh mnist c standard carlini 1679
./run_extra.sh mnist c adversarial carlini 1679
./run_extra.sh mnist c relu carlini 1679
./run_extra.sh mnist a standard carlini 2005
./run_extra.sh mnist a adversarial carlini 2005
./run_extra.sh mnist a relu carlini 2005
./run_extra.sh mnist b standard carlini 2005
./run_extra.sh mnist b adversarial carlini 2005
./run_extra.sh mnist b relu carlini 2005
./run_extra.sh mnist c standard carlini 2005
./run_extra.sh mnist c adversarial carlini 2005
./run_extra.sh mnist c relu carlini 2005
./run_extra.sh mnist a standard carlini 8215
./run_extra.sh mnist a adversarial carlini 8215
./run_extra.sh mnist a relu carlini 8215
./run_extra.sh mnist b standard carlini 8215
./run_extra.sh mnist b adversarial carlini 8215
./run_extra.sh mnist b relu carlini 8215
./run_extra.sh mnist c standard carlini 8215
./run_extra.sh mnist c adversarial carlini 8215
./run_extra.sh mnist c relu carlini 8215
./run_extra.sh mnist a standard carlini 4610
./run_extra.sh mnist a adversarial carlini 4610
./run_extra.sh mnist a relu carlini 4610
./run_extra.sh mnist b standard carlini 4610
./run_extra.sh mnist b adversarial carlini 4610
./run_extra.sh mnist b relu carlini 4610
./run_extra.sh mnist c standard carlini 4610
./run_extra.sh mnist c adversarial carlini 4610
./run_extra.sh mnist c relu carlini 4610
./run_extra.sh mnist a standard carlini 2322
./run_extra.sh mnist a adversarial carlini 2322
./run_extra.sh mnist a relu carlini 2322
./run_extra.sh mnist b standard carlini 2322
./run_extra.sh mnist b adversarial carlini 2322
./run_extra.sh mnist b relu carlini 2322
./run_extra.sh mnist c standard carlini 2322
./run_extra.sh mnist c adversarial carlini 2322
./run_extra.sh mnist c relu carlini 2322
./run_extra.sh mnist a standard carlini 6635
./run_extra.sh mnist a adversarial carlini 6635
./run_extra.sh mnist a relu carlini 6635
./run_extra.sh mnist b standard carlini 6635
./run_extra.sh mnist b adversarial carlini 6635
./run_extra.sh mnist b relu carlini 6635
./run_extra.sh mnist c standard carlini 6635
./run_extra.sh mnist c adversarial carlini 6635
./run_extra.sh mnist c relu carlini 6635
./run_extra.sh mnist a standard carlini 996
./run_extra.sh mnist a adversarial carlini 996
./run_extra.sh mnist a relu carlini 996
./run_extra.sh mnist b standard carlini 996
./run_extra.sh mnist b adversarial carlini 996
./run_extra.sh mnist b relu carlini 996
./run_extra.sh mnist c standard carlini 996
./run_extra.sh mnist c adversarial carlini 996
./run_extra.sh mnist c relu carlini 996
./run_extra.sh mnist a standard carlini 1232
./run_extra.sh mnist a adversarial carlini 1232
./run_extra.sh mnist a relu carlini 1232
./run_extra.sh mnist b standard carlini 1232
./run_extra.sh mnist b adversarial carlini 1232
./run_extra.sh mnist b relu carlini 1232
./run_extra.sh mnist c standard carlini 1232
./run_extra.sh mnist c adversarial carlini 1232
./run_extra.sh mnist c relu carlini 1232
./run_extra.sh mnist a standard carlini 5522
./run_extra.sh mnist a adversarial carlini 5522
./run_extra.sh mnist a relu carlini 5522
./run_extra.sh mnist b standard carlini 5522
./run_extra.sh mnist b adversarial carlini 5522
./run_extra.sh mnist b relu carlini 5522
./run_extra.sh mnist c standard carlini 5522
./run_extra.sh mnist c adversarial carlini 5522
./run_extra.sh mnist c relu carlini 5522
./run_extra.sh mnist a standard carlini 2078
./run_extra.sh mnist a adversarial carlini 2078
./run_extra.sh mnist a relu carlini 2078
./run_extra.sh mnist b standard carlini 2078
./run_extra.sh mnist b adversarial carlini 2078
./run_extra.sh mnist b relu carlini 2078
./run_extra.sh mnist c standard carlini 2078
./run_extra.sh mnist c adversarial carlini 2078
./run_extra.sh mnist c relu carlini 2078
./run_extra.sh mnist a standard carlini 1674
./run_extra.sh mnist a adversarial carlini 1674
./run_extra.sh mnist a relu carlini 1674
./run_extra.sh mnist b standard carlini 1674
./run_extra.sh mnist b adversarial carlini 1674
./run_extra.sh mnist b relu carlini 1674
./run_extra.sh mnist c standard carlini 1674
./run_extra.sh mnist c adversarial carlini 1674
./run_extra.sh mnist c relu carlini 1674
./run_extra.sh mnist a standard carlini 3390
./run_extra.sh mnist a adversarial carlini 3390
./run_extra.sh mnist a relu carlini 3390
./run_extra.sh mnist b standard carlini 3390
./run_extra.sh mnist b adversarial carlini 3390
./run_extra.sh mnist b relu carlini 3390
./run_extra.sh mnist c standard carlini 3390
./run_extra.sh mnist c adversarial carlini 3390
./run_extra.sh mnist c relu carlini 3390
./run_extra.sh mnist a standard carlini 9570
./run_extra.sh mnist a adversarial carlini 9570
./run_extra.sh mnist a relu carlini 9570
./run_extra.sh mnist b standard carlini 9570
./run_extra.sh mnist b adversarial carlini 9570
./run_extra.sh mnist b relu carlini 9570
./run_extra.sh mnist c standard carlini 9570
./run_extra.sh mnist c adversarial carlini 9570
./run_extra.sh mnist c relu carlini 9570
./run_extra.sh mnist a standard carlini 4022
./run_extra.sh mnist a adversarial carlini 4022
./run_extra.sh mnist a relu carlini 4022
./run_extra.sh mnist b standard carlini 4022
./run_extra.sh mnist b adversarial carlini 4022
./run_extra.sh mnist b relu carlini 4022
./run_extra.sh mnist c standard carlini 4022
./run_extra.sh mnist c adversarial carlini 4022
./run_extra.sh mnist c relu carlini 4022
./run_extra.sh mnist a standard carlini 2908
./run_extra.sh mnist a adversarial carlini 2908
./run_extra.sh mnist a relu carlini 2908
./run_extra.sh mnist b standard carlini 2908
./run_extra.sh mnist b adversarial carlini 2908
./run_extra.sh mnist b relu carlini 2908
./run_extra.sh mnist c standard carlini 2908
./run_extra.sh mnist c adversarial carlini 2908
./run_extra.sh mnist c relu carlini 2908
./run_extra.sh mnist a standard carlini 9218
./run_extra.sh mnist a adversarial carlini 9218
./run_extra.sh mnist a relu carlini 9218
./run_extra.sh mnist b standard carlini 9218
./run_extra.sh mnist b adversarial carlini 9218
./run_extra.sh mnist b relu carlini 9218
./run_extra.sh mnist c standard carlini 9218
./run_extra.sh mnist c adversarial carlini 9218
./run_extra.sh mnist c relu carlini 9218
./run_extra.sh mnist a standard carlini 4767
./run_extra.sh mnist a adversarial carlini 4767
./run_extra.sh mnist a relu carlini 4767
./run_extra.sh mnist b standard carlini 4767
./run_extra.sh mnist b adversarial carlini 4767
./run_extra.sh mnist b relu carlini 4767
./run_extra.sh mnist c standard carlini 4767
./run_extra.sh mnist c adversarial carlini 4767
./run_extra.sh mnist c relu carlini 4767
./run_extra.sh mnist a standard carlini 680
./run_extra.sh mnist a adversarial carlini 680
./run_extra.sh mnist a relu carlini 680
./run_extra.sh mnist b standard carlini 680
./run_extra.sh mnist b adversarial carlini 680
./run_extra.sh mnist b relu carlini 680
./run_extra.sh mnist c standard carlini 680
./run_extra.sh mnist c adversarial carlini 680
./run_extra.sh mnist c relu carlini 680
./run_extra.sh mnist a standard carlini 2826
./run_extra.sh mnist a adversarial carlini 2826
./run_extra.sh mnist a relu carlini 2826
./run_extra.sh mnist b standard carlini 2826
./run_extra.sh mnist b adversarial carlini 2826
./run_extra.sh mnist b relu carlini 2826
./run_extra.sh mnist c standard carlini 2826
./run_extra.sh mnist c adversarial carlini 2826
./run_extra.sh mnist c relu carlini 2826
./run_extra.sh mnist a standard carlini 9758
./run_extra.sh mnist a adversarial carlini 9758
./run_extra.sh mnist a relu carlini 9758
./run_extra.sh mnist b standard carlini 9758
./run_extra.sh mnist b adversarial carlini 9758
./run_extra.sh mnist b relu carlini 9758
./run_extra.sh mnist c standard carlini 9758
./run_extra.sh mnist c adversarial carlini 9758
./run_extra.sh mnist c relu carlini 9758
./run_extra.sh mnist a standard carlini 2963
./run_extra.sh mnist a adversarial carlini 2963
./run_extra.sh mnist a relu carlini 2963
./run_extra.sh mnist b standard carlini 2963
./run_extra.sh mnist b adversarial carlini 2963
./run_extra.sh mnist b relu carlini 2963
./run_extra.sh mnist c standard carlini 2963
./run_extra.sh mnist c adversarial carlini 2963
./run_extra.sh mnist c relu carlini 2963
./run_extra.sh mnist a standard carlini 5223
./run_extra.sh mnist a adversarial carlini 5223
./run_extra.sh mnist a relu carlini 5223
./run_extra.sh mnist b standard carlini 5223
./run_extra.sh mnist b adversarial carlini 5223
./run_extra.sh mnist b relu carlini 5223
./run_extra.sh mnist c standard carlini 5223
./run_extra.sh mnist c adversarial carlini 5223
./run_extra.sh mnist c relu carlini 5223
./run_extra.sh mnist a standard carlini 1557
./run_extra.sh mnist a adversarial carlini 1557
./run_extra.sh mnist a relu carlini 1557
./run_extra.sh mnist b standard carlini 1557
./run_extra.sh mnist b adversarial carlini 1557
./run_extra.sh mnist b relu carlini 1557
./run_extra.sh mnist c standard carlini 1557
./run_extra.sh mnist c adversarial carlini 1557
./run_extra.sh mnist c relu carlini 1557
./run_extra.sh mnist a standard carlini 9160
./run_extra.sh mnist a adversarial carlini 9160
./run_extra.sh mnist a relu carlini 9160
./run_extra.sh mnist b standard carlini 9160
./run_extra.sh mnist b adversarial carlini 9160
./run_extra.sh mnist b relu carlini 9160
./run_extra.sh mnist c standard carlini 9160
./run_extra.sh mnist c adversarial carlini 9160
./run_extra.sh mnist c relu carlini 9160
./run_extra.sh mnist a standard carlini 7575
./run_extra.sh mnist a adversarial carlini 7575
./run_extra.sh mnist a relu carlini 7575
./run_extra.sh mnist b standard carlini 7575
./run_extra.sh mnist b adversarial carlini 7575
./run_extra.sh mnist b relu carlini 7575
./run_extra.sh mnist c standard carlini 7575
./run_extra.sh mnist c adversarial carlini 7575
./run_extra.sh mnist c relu carlini 7575
./run_extra.sh mnist a standard carlini 819
./run_extra.sh mnist a adversarial carlini 819
./run_extra.sh mnist a relu carlini 819
./run_extra.sh mnist b standard carlini 819
./run_extra.sh mnist b adversarial carlini 819
./run_extra.sh mnist b relu carlini 819
./run_extra.sh mnist c standard carlini 819
./run_extra.sh mnist c adversarial carlini 819
./run_extra.sh mnist c relu carlini 819
./run_extra.sh mnist a standard carlini 9380
./run_extra.sh mnist a adversarial carlini 9380
./run_extra.sh mnist a relu carlini 9380
./run_extra.sh mnist b standard carlini 9380
./run_extra.sh mnist b adversarial carlini 9380
./run_extra.sh mnist b relu carlini 9380
./run_extra.sh mnist c standard carlini 9380
./run_extra.sh mnist c adversarial carlini 9380
./run_extra.sh mnist c relu carlini 9380
./run_extra.sh mnist a standard carlini 7785
./run_extra.sh mnist a adversarial carlini 7785
./run_extra.sh mnist a relu carlini 7785
./run_extra.sh mnist b standard carlini 7785
./run_extra.sh mnist b adversarial carlini 7785
./run_extra.sh mnist b relu carlini 7785
./run_extra.sh mnist c standard carlini 7785
./run_extra.sh mnist c adversarial carlini 7785
./run_extra.sh mnist c relu carlini 7785
./run_extra.sh mnist a standard carlini 4723
./run_extra.sh mnist a adversarial carlini 4723
./run_extra.sh mnist a relu carlini 4723
./run_extra.sh mnist b standard carlini 4723
./run_extra.sh mnist b adversarial carlini 4723
./run_extra.sh mnist b relu carlini 4723
./run_extra.sh mnist c standard carlini 4723
./run_extra.sh mnist c adversarial carlini 4723
./run_extra.sh mnist c relu carlini 4723
./run_extra.sh mnist a standard carlini 5220
./run_extra.sh mnist a adversarial carlini 5220
./run_extra.sh mnist a relu carlini 5220
./run_extra.sh mnist b standard carlini 5220
./run_extra.sh mnist b adversarial carlini 5220
./run_extra.sh mnist b relu carlini 5220
./run_extra.sh mnist c standard carlini 5220
./run_extra.sh mnist c adversarial carlini 5220
./run_extra.sh mnist c relu carlini 5220
./run_extra.sh mnist a standard carlini 1862
./run_extra.sh mnist a adversarial carlini 1862
./run_extra.sh mnist a relu carlini 1862
./run_extra.sh mnist b standard carlini 1862
./run_extra.sh mnist b adversarial carlini 1862
./run_extra.sh mnist b relu carlini 1862
./run_extra.sh mnist c standard carlini 1862
./run_extra.sh mnist c adversarial carlini 1862
./run_extra.sh mnist c relu carlini 1862
./run_extra.sh mnist a standard carlini 9624
./run_extra.sh mnist a adversarial carlini 9624
./run_extra.sh mnist a relu carlini 9624
./run_extra.sh mnist b standard carlini 9624
./run_extra.sh mnist b adversarial carlini 9624
./run_extra.sh mnist b relu carlini 9624
./run_extra.sh mnist c standard carlini 9624
./run_extra.sh mnist c adversarial carlini 9624
./run_extra.sh mnist c relu carlini 9624
./run_extra.sh mnist a standard carlini 5590
./run_extra.sh mnist a adversarial carlini 5590
./run_extra.sh mnist a relu carlini 5590
./run_extra.sh mnist b standard carlini 5590
./run_extra.sh mnist b adversarial carlini 5590
./run_extra.sh mnist b relu carlini 5590
./run_extra.sh mnist c standard carlini 5590
./run_extra.sh mnist c adversarial carlini 5590
./run_extra.sh mnist c relu carlini 5590
./run_extra.sh mnist a standard carlini 8673
./run_extra.sh mnist a adversarial carlini 8673
./run_extra.sh mnist a relu carlini 8673
./run_extra.sh mnist b standard carlini 8673
./run_extra.sh mnist b adversarial carlini 8673
./run_extra.sh mnist b relu carlini 8673
./run_extra.sh mnist c standard carlini 8673
./run_extra.sh mnist c adversarial carlini 8673
./run_extra.sh mnist c relu carlini 8673
./run_extra.sh mnist a standard carlini 6008
./run_extra.sh mnist a adversarial carlini 6008
./run_extra.sh mnist a relu carlini 6008
./run_extra.sh mnist b standard carlini 6008
./run_extra.sh mnist b adversarial carlini 6008
./run_extra.sh mnist b relu carlini 6008
./run_extra.sh mnist c standard carlini 6008
./run_extra.sh mnist c adversarial carlini 6008
./run_extra.sh mnist c relu carlini 6008
./run_extra.sh mnist a standard carlini 7198
./run_extra.sh mnist a adversarial carlini 7198
./run_extra.sh mnist a relu carlini 7198
./run_extra.sh mnist b standard carlini 7198
./run_extra.sh mnist b adversarial carlini 7198
./run_extra.sh mnist b relu carlini 7198
./run_extra.sh mnist c standard carlini 7198
./run_extra.sh mnist c adversarial carlini 7198
./run_extra.sh mnist c relu carlini 7198
./run_extra.sh mnist a standard carlini 9366
./run_extra.sh mnist a adversarial carlini 9366
./run_extra.sh mnist a relu carlini 9366
./run_extra.sh mnist b standard carlini 9366
./run_extra.sh mnist b adversarial carlini 9366
./run_extra.sh mnist b relu carlini 9366
./run_extra.sh mnist c standard carlini 9366
./run_extra.sh mnist c adversarial carlini 9366
./run_extra.sh mnist c relu carlini 9366
./run_extra.sh mnist a standard carlini 2243
./run_extra.sh mnist a adversarial carlini 2243
./run_extra.sh mnist a relu carlini 2243
./run_extra.sh mnist b standard carlini 2243
./run_extra.sh mnist b adversarial carlini 2243
./run_extra.sh mnist b relu carlini 2243
./run_extra.sh mnist c standard carlini 2243
./run_extra.sh mnist c adversarial carlini 2243
./run_extra.sh mnist c relu carlini 2243
./run_extra.sh mnist a standard carlini 2426
./run_extra.sh mnist a adversarial carlini 2426
./run_extra.sh mnist a relu carlini 2426
./run_extra.sh mnist b standard carlini 2426
./run_extra.sh mnist b adversarial carlini 2426
./run_extra.sh mnist b relu carlini 2426
./run_extra.sh mnist c standard carlini 2426
./run_extra.sh mnist c adversarial carlini 2426
./run_extra.sh mnist c relu carlini 2426
./run_extra.sh mnist a standard carlini 9627
./run_extra.sh mnist a adversarial carlini 9627
./run_extra.sh mnist a relu carlini 9627
./run_extra.sh mnist b standard carlini 9627
./run_extra.sh mnist b adversarial carlini 9627
./run_extra.sh mnist b relu carlini 9627
./run_extra.sh mnist c standard carlini 9627
./run_extra.sh mnist c adversarial carlini 9627
./run_extra.sh mnist c relu carlini 9627
./run_extra.sh mnist a standard carlini 6773
./run_extra.sh mnist a adversarial carlini 6773
./run_extra.sh mnist a relu carlini 6773
./run_extra.sh mnist b standard carlini 6773
./run_extra.sh mnist b adversarial carlini 6773
./run_extra.sh mnist b relu carlini 6773
./run_extra.sh mnist c standard carlini 6773
./run_extra.sh mnist c adversarial carlini 6773
./run_extra.sh mnist c relu carlini 6773
./run_extra.sh mnist a standard carlini 6372
./run_extra.sh mnist a adversarial carlini 6372
./run_extra.sh mnist a relu carlini 6372
./run_extra.sh mnist b standard carlini 6372
./run_extra.sh mnist b adversarial carlini 6372
./run_extra.sh mnist b relu carlini 6372
./run_extra.sh mnist c standard carlini 6372
./run_extra.sh mnist c adversarial carlini 6372
./run_extra.sh mnist c relu carlini 6372
./run_extra.sh mnist a standard carlini 1052
./run_extra.sh mnist a adversarial carlini 1052
./run_extra.sh mnist a relu carlini 1052
./run_extra.sh mnist b standard carlini 1052
./run_extra.sh mnist b adversarial carlini 1052
./run_extra.sh mnist b relu carlini 1052
./run_extra.sh mnist c standard carlini 1052
./run_extra.sh mnist c adversarial carlini 1052
./run_extra.sh mnist c relu carlini 1052
./run_extra.sh mnist a standard carlini 2040
./run_extra.sh mnist a adversarial carlini 2040
./run_extra.sh mnist a relu carlini 2040
./run_extra.sh mnist b standard carlini 2040
./run_extra.sh mnist b adversarial carlini 2040
./run_extra.sh mnist b relu carlini 2040
./run_extra.sh mnist c standard carlini 2040
./run_extra.sh mnist c adversarial carlini 2040
./run_extra.sh mnist c relu carlini 2040
./run_extra.sh mnist a standard carlini 6519
./run_extra.sh mnist a adversarial carlini 6519
./run_extra.sh mnist a relu carlini 6519
./run_extra.sh mnist b standard carlini 6519
./run_extra.sh mnist b adversarial carlini 6519
./run_extra.sh mnist b relu carlini 6519
./run_extra.sh mnist c standard carlini 6519
./run_extra.sh mnist c adversarial carlini 6519
./run_extra.sh mnist c relu carlini 6519
./run_extra.sh mnist a standard carlini 8771
./run_extra.sh mnist a adversarial carlini 8771
./run_extra.sh mnist a relu carlini 8771
./run_extra.sh mnist b standard carlini 8771
./run_extra.sh mnist b adversarial carlini 8771
./run_extra.sh mnist b relu carlini 8771
./run_extra.sh mnist c standard carlini 8771
./run_extra.sh mnist c adversarial carlini 8771
./run_extra.sh mnist c relu carlini 8771
./run_extra.sh mnist a standard carlini 4849
./run_extra.sh mnist a adversarial carlini 4849
./run_extra.sh mnist a relu carlini 4849
./run_extra.sh mnist b standard carlini 4849
./run_extra.sh mnist b adversarial carlini 4849
./run_extra.sh mnist b relu carlini 4849
./run_extra.sh mnist c standard carlini 4849
./run_extra.sh mnist c adversarial carlini 4849
./run_extra.sh mnist c relu carlini 4849
./run_extra.sh mnist a standard carlini 7068
